"""Hand-curated TAM-phrase gloss overrides for Mosaea 28 — the sons of Mosiah go to preach to the Lamanites; Mosiah translates the Jaredite record.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
subject `o ia` / agent `e ia` absorbed into the verb cluster, never split as a
bare "he" (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` fillers when a PP/object follows (rule 1), `mafai ona`/`ina ia`/
`ina ua` bound (rules 13/15), vocative `e`/`E …e` folded as "O X" (rule 12),
directional "forth" dropped (rule 12a). v1's trailing `Lamanā—` left as-is
(verse-end continuation dash). No pronoun/TAM word injected into a cell whose
span lacks that token; no content word repeats across adjacent cells (except
authentic Samoan doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah28.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 28
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "Now"),
        (2, 4, "it came to pass"),
        (5, 7, "after had finished"),
        (8, 8, "doing"),
        (9, 10, "the sons"),
        (11, 12, "of Mosiah"),
        (13, 15, "all these things,"),
        (16, 18, "they took"),
        (19, 21, "a small number"),
        (22, 25, "with them,"),
        (26, 29, "and returned"),
        (30, 33, "to their father,"),
        (34, 36, "the king,"),
        (37, 38, "and desired"),
        (39, 41, "of him"),
        (42, 46, "that he would grant"),
        (47, 50, "unto them,"),
        (51, 53, "that might"),
        (54, 56, "they,"),
        (57, 60, "with these"),
        (61, 63, "whom"),
        (64, 66, "they had selected,"),
        (67, 69, "go up"),
        (70, 72, "to the land"),
        (73, 74, "of Nephi,"),
        (75, 76, "that"),
        (77, 78, "might"),
        (79, 79, "they"),
        (80, 81, "preach"),
        (82, 83, "the things"),
        (84, 86, "which they had heard,"),
        (87, 87, "and"),
        (88, 89, "that"),
        (90, 91, "might"),
        (92, 92, "they"),
        (93, 94, "impart"),
        (95, 96, "the word"),
        (97, 99, "of God,"),
        (100, 103, "to their brethren,"),
        (104, 106, "the Lamanites—"),
    ],
    2: [
        (0, 1, "That perhaps"),
        (2, 4, "might"),
        (5, 7, "they bring"),
        (8, 10, "them"),
        (11, 13, "to the knowledge"),
        (14, 16, "of the Lord"),
        (17, 19, "their God,"),
        (20, 21, "and convince"),
        (22, 23, "them"),
        (24, 26, "of the iniquity"),
        (27, 30, "of their fathers;"),
        (31, 31, "and"),
        (32, 34, "that perhaps"),
        (35, 37, "might"),
        (38, 40, "they cure"),
        (41, 42, "them"),
        (43, 46, "of their hatred"),
        (47, 49, "towards"),
        (50, 51, "the Nephites,"),
        (52, 54, "that"),
        (55, 57, "might also"),
        (58, 61, "they be brought"),
        (62, 63, "to rejoice"),
        (64, 66, "in the Lord"),
        (67, 69, "their God,"),
        (70, 71, "that"),
        (72, 73, "might"),
        (74, 75, "they become friendly"),
        (76, 78, "one"),
        (79, 81, "to another,"),
        (82, 82, "and"),
        (83, 84, "that"),
        (85, 88, "there should be no more"),
        (89, 90, "contentions"),
        (91, 94, "in all the land"),
        (95, 97, "which had given"),
        (98, 100, "the Lord"),
        (101, 103, "their God"),
        (104, 107, "them."),
    ],
    3: [
        (0, 1, "Now"),
        (2, 4, "they were desirous"),
        (5, 7, "that should be declared"),
        (8, 9, "salvation"),
        (10, 12, "to every creature,"),
        (13, 13, "for"),
        (14, 17, "could not"),
        (18, 19, "they bear"),
        (20, 22, "the perishing of"),
        (23, 24, "the soul"),
        (25, 28, "of any human;"),
        (29, 29, "yea,"),
        (30, 33, "even the very"),
        (34, 36, "thoughts"),
        (37, 38, "that"),
        (39, 42, "shall come"),
        (43, 45, "to a soul"),
        (46, 47, "the torment"),
        (48, 50, "endless"),
        (51, 52, "did quake"),
        (53, 55, "and tremble"),
        (56, 57, "them."),
    ],
    4: [
        (0, 0, "And"),
        (1, 3, "thus"),
        (4, 4, "did work"),
        (5, 6, "the Spirit"),
        (7, 9, "of the Lord"),
        (10, 12, "upon"),
        (13, 14, "them,"),
        (15, 15, "for"),
        (16, 17, "were"),
        (18, 19, "they"),
        (20, 22, "the sinners"),
        (23, 25, "very vilest."),
        (26, 26, "And"),
        (27, 29, "saw fit"),
        (30, 31, "the Lord"),
        (32, 35, "in his tender mercy"),
        (36, 36, "infinite"),
        (37, 38, "to spare"),
        (39, 40, "them;"),
        (41, 44, "nevertheless"),
        (45, 47, "suffered much"),
        (48, 49, "they"),
        (50, 52, "in the anguish of"),
        (53, 55, "soul"),
        (56, 57, "because of"),
        (58, 60, "their iniquities,"),
        (61, 61, "and"),
        (62, 64, "suffering much"),
        (65, 66, "and fearing"),
        (67, 68, "lest"),
        (69, 70, "be cast off"),
        (71, 72, "they"),
        (73, 74, "forever."),
    ],
    5: [
        (0, 3, "And it came to pass"),
        (4, 6, "they did plead"),
        (7, 10, "with their father"),
        (11, 12, "for days"),
        (13, 14, "many"),
        (15, 16, "that"),
        (17, 18, "might"),
        (19, 19, "they"),
        (20, 21, "go up"),
        (22, 24, "to the land"),
        (25, 26, "of Nephi."),
    ],
    6: [
        (0, 0, "And"),
        (1, 3, "went"),
        (4, 6, "the king"),
        (7, 7, "Mosiah"),
        (8, 10, "and inquired"),
        (11, 13, "of the Lord"),
        (14, 16, "if he should"),
        (17, 20, "let"),
        (21, 22, "his sons"),
        (23, 25, "go up"),
        (26, 28, "among"),
        (29, 30, "the Lamanites"),
        (31, 33, "to preach"),
        (34, 35, "the word."),
    ],
    7: [
        (0, 0, "And"),
        (1, 3, "said"),
        (4, 5, "the Lord"),
        (6, 7, "unto Mosiah:"),
        (8, 9, "Let"),
        (10, 11, "them"),
        (12, 14, "go up,"),
        (15, 15, "for"),
        (16, 17, "many"),
        (18, 21, "shall believe"),
        (22, 24, "on their words,"),
        (25, 25, "and"),
        (26, 30, "they shall have"),
        (31, 32, "the life"),
        (33, 34, "eternal;"),
        (35, 35, "and"),
        (36, 40, "I will deliver"),
        (41, 42, "thy sons"),
        (43, 45, "out of the hands of"),
        (46, 47, "the Lamanites."),
    ],
    8: [
        (0, 3, "And it came to pass"),
        (4, 4, "granted"),
        (5, 6, "Mosiah"),
        (7, 10, "that they might go"),
        (11, 12, "and do"),
        (13, 15, "according to"),
        (16, 18, "their request."),
    ],
    9: [
        (0, 0, "And"),
        (1, 2, "took"),
        (3, 5, "their journey"),
        (6, 8, "into the wilderness"),
        (9, 11, "to go up"),
        (12, 14, "to preach"),
        (15, 16, "the word"),
        (17, 19, "among"),
        (20, 21, "the Lamanites;"),
        (22, 22, "and"),
        (23, 28, "I shall give"),
        (29, 30, "an account"),
        (31, 34, "of their proceedings,"),
        (35, 40, "hereafter."),
    ],
    10: [
        (0, 1, "Now"),
        (2, 5, "had no one"),
        (6, 7, "to Mosiah"),
        (8, 9, "the king"),
        (10, 14, "to confer"),
        (15, 17, "upon"),
        (18, 19, "the kingdom,"),
        (20, 20, "for"),
        (21, 24, "there was not any"),
        (25, 27, "of his sons"),
        (28, 30, "who would accept"),
        (31, 32, "the kingdom."),
    ],
    11: [
        (0, 1, "Therefore"),
        (2, 6, "he took"),
        (7, 7, "the records"),
        (8, 9, "which were engraven"),
        (10, 12, "on"),
        (13, 14, "the plates of brass,"),
        (15, 17, "and also the plates"),
        (18, 19, "of Nephi,"),
        (20, 22, "and all the things"),
        (23, 24, "which had been kept"),
        (25, 26, "and preserved"),
        (27, 29, "according to"),
        (30, 30, "the commandments"),
        (31, 33, "of God,"),
        (34, 36, "after had finished"),
        (37, 39, "he translating"),
        (40, 41, "and caused"),
        (42, 44, "to be written"),
        (45, 45, "the records"),
        (46, 49, "which were on"),
        (50, 51, "the plates of gold"),
        (52, 53, "which had been found"),
        (54, 56, "by the people"),
        (57, 58, "of Limhi,"),
        (59, 62, "which were delivered"),
        (63, 65, "to him"),
        (66, 68, "by the hand"),
        (69, 70, "of Limhi;"),
    ],
    12: [
        (0, 0, "And"),
        (1, 4, "he did"),
        (5, 6, "this"),
        (7, 8, "because of"),
        (9, 11, "the great anxiety"),
        (12, 14, "of his people;"),
        (15, 15, "for"),
        (16, 19, "they were desirous beyond measure"),
        (20, 22, "to know"),
        (23, 25, "concerning"),
        (26, 27, "those people"),
        (28, 29, "who had been destroyed."),
    ],
    13: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 6, "he translated"),
        (7, 7, "them"),
        (8, 10, "by the means of"),
        (11, 12, "those stones"),
        (13, 14, "two"),
        (15, 16, "which were fastened"),
        (17, 19, "into"),
        (20, 21, "the rims"),
        (22, 23, "two."),
    ],
    14: [
        (0, 1, "Now"),
        (2, 4, "these things"),
        (5, 7, "were prepared"),
        (8, 10, "from the beginning,"),
        (11, 11, "and"),
        (12, 17, "were handed down"),
        (18, 20, "from generation"),
        (21, 23, "to generation,"),
        (24, 26, "for the purpose"),
        (27, 29, "of interpreting"),
        (30, 31, "languages."),
    ],
    15: [
        (0, 0, "And"),
        (1, 2, "have been kept"),
        (3, 4, "and preserved"),
        (5, 6, "these things"),
        (7, 9, "by the hand"),
        (10, 12, "of the Lord,"),
        (13, 14, "that"),
        (15, 19, "he should discover"),
        (20, 22, "to every creature"),
        (23, 24, "who"),
        (25, 26, "should possess"),
        (27, 29, "the land,"),
        (30, 30, "the iniquities"),
        (31, 33, "and abominations"),
        (34, 36, "of his people;"),
    ],
    16: [
        (0, 0, "And"),
        (1, 4, "whosoever"),
        (5, 7, "has"),
        (8, 9, "these things,"),
        (10, 11, "is called"),
        (12, 14, "seer,"),
        (15, 17, "after the manner of"),
        (18, 21, "old times."),
    ],
    17: [
        (0, 1, "Now"),
        (2, 5, "after had finished"),
        (6, 6, "translating"),
        (7, 8, "Mosiah"),
        (9, 10, "these records,"),
        (11, 11, "behold,"),
        (12, 14, "it gave"),
        (15, 17, "in those records"),
        (18, 19, "an account"),
        (20, 22, "of the people"),
        (23, 26, "who were destroyed,"),
        (27, 29, "from the time"),
        (30, 32, "that were destroyed"),
        (33, 34, "they"),
        (35, 39, "back"),
        (40, 42, "to the building"),
        (43, 46, "of the great tower,"),
        (47, 49, "at the time"),
        (50, 52, "confounded"),
        (53, 55, "the Lord"),
        (56, 57, "the language"),
        (58, 59, "of the people,"),
        (60, 62, "and were scattered abroad"),
        (63, 64, "they"),
        (65, 67, "upon"),
        (68, 70, "the face of all the earth,"),
        (71, 71, "yea,"),
        (72, 75, "from that time"),
        (76, 77, "back,"),
        (78, 81, "even until"),
        (82, 84, "the creation"),
        (85, 86, "of Adam."),
    ],
    18: [
        (0, 1, "Now,"),
        (2, 4, "this account"),
        (5, 7, "did cause"),
        (8, 10, "much mourning"),
        (11, 13, "in the people"),
        (14, 15, "of Mosiah,"),
        (16, 16, "yea,"),
        (17, 18, "were filled"),
        (19, 20, "they"),
        (21, 23, "with sorrow;"),
        (24, 27, "nevertheless"),
        (28, 32, "they gained"),
        (33, 35, "much knowledge,"),
        (36, 38, "in the which"),
        (39, 42, "they did rejoice."),
    ],
    19: [
        (0, 0, "And"),
        (1, 3, "this account"),
        (4, 7, "shall be written"),
        (8, 13, "hereafter;"),
        (14, 14, "for"),
        (15, 15, "behold,"),
        (16, 17, "it behooveth"),
        (18, 20, "all people"),
        (21, 22, "should know"),
        (23, 23, "the things"),
        (24, 25, "which are written"),
        (26, 28, "in this account."),
    ],
    20: [
        (0, 0, "And"),
        (1, 2, "now,"),
        (3, 5, "as"),
        (6, 9, "I said"),
        (10, 12, "unto you,"),
        (13, 16, "after had finished"),
        (17, 17, "doing"),
        (18, 20, "the king"),
        (21, 22, "Mosiah"),
        (23, 24, "these things,"),
        (25, 28, "he took"),
        (29, 30, "the plates of brass,"),
        (31, 33, "and all the things"),
        (34, 37, "which he had kept,"),
        (38, 40, "and conferred"),
        (41, 42, "them"),
        (43, 45, "upon"),
        (46, 46, "Alma,"),
        (47, 50, "who was the son"),
        (51, 52, "of Alma;"),
        (53, 53, "yea,"),
        (54, 56, "all the records,"),
        (57, 59, "and the interpreters"),
        (60, 60, "also,"),
        (61, 63, "and conferred"),
        (64, 67, "upon him,"),
        (68, 70, "and commanded"),
        (71, 73, "him"),
        (74, 75, "that should keep"),
        (76, 79, "and preserve"),
        (80, 81, "them,"),
        (82, 82, "and"),
        (83, 85, "also keep"),
        (86, 88, "a record of"),
        (89, 90, "the people,"),
        (91, 94, "handing down"),
        (95, 96, "them"),
        (97, 100, "from one generation"),
        (101, 104, "to another,"),
        (105, 108, "even as"),
        (109, 111, "had been handed down"),
        (112, 113, "they"),
        (114, 116, "from the time"),
        (117, 119, "that left"),
        (120, 121, "Lehi"),
        (122, 122, "Jerusalem."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
