"""Hand-curated TAM-phrase gloss overrides for Mosaea 23 — Alma's people settle Helam; the coming of the Lamanites and Amulon.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
subject `o ia` / agent `e ia` absorbed into the verb cluster, never split as a
bare "he" (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` fillers when a PP/object follows (rule 1), `mafai ona`/`ina ia`/
`ina ua` bound (rules 13/15), vocative `e`/`E …e` folded as "O X" (rule 12),
directional "forth" dropped (rule 12a). Em-dash `lea—soo` in v22 split in the
source per rule 11. No pronoun/TAM word injected into a cell whose span lacks
that token; no content word repeats across adjacent cells (except authentic
Samoan doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah23.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 23
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "Now"),
        (2, 3, "Alma,"),
        (4, 5, "having"),
        (6, 8, "been warned"),
        (9, 11, "of the Lord"),
        (12, 16, "that would come"),
        (17, 17, "the armies"),
        (18, 20, "of king"),
        (21, 22, "Noah"),
        (23, 24, "to fall upon"),
        (25, 26, "them,"),
        (27, 27, "and"),
        (28, 31, "when had finished"),
        (32, 33, "making known"),
        (34, 36, "to his people,"),
        (37, 38, "therefore"),
        (39, 43, "they gathered together"),
        (44, 46, "their flocks,"),
        (47, 48, "and took"),
        (49, 51, "their grain,"),
        (52, 55, "and departed"),
        (56, 58, "into the wilderness"),
        (59, 60, "before"),
        (61, 62, "came"),
        (63, 63, "the armies"),
        (64, 66, "of king"),
        (67, 68, "Noah."),
    ],
    2: [
        (0, 0, "And"),
        (1, 2, "did strengthen"),
        (3, 4, "them"),
        (5, 7, "the Lord,"),
        (8, 8, "that"),
        (9, 11, "could not"),
        (12, 13, "the people"),
        (14, 16, "of king"),
        (17, 18, "Noah"),
        (19, 21, "overtake"),
        (22, 23, "them"),
        (24, 25, "to destroy"),
        (26, 27, "them."),
    ],
    3: [
        (0, 0, "And"),
        (1, 3, "they fled"),
        (4, 6, "into the wilderness"),
        (7, 9, "a journey"),
        (10, 11, "of days"),
        (12, 13, "eight."),
    ],
    4: [
        (0, 0, "And"),
        (1, 3, "they came"),
        (4, 6, "to a land,"),
        (7, 7, "yea,"),
        (8, 10, "a land"),
        (11, 12, "very beautiful"),
        (13, 14, "and pleasant,"),
        (15, 17, "a land"),
        (18, 20, "of pure water."),
    ],
    5: [
        (0, 0, "And"),
        (1, 3, "they pitched"),
        (4, 6, "their tents,"),
        (7, 8, "and began"),
        (9, 10, "to till"),
        (11, 12, "the ground,"),
        (13, 14, "and began"),
        (15, 16, "to build"),
        (17, 17, "buildings;"),
        (18, 18, "yea,"),
        (19, 21, "they were industrious,"),
        (22, 24, "and did labor exceedingly."),
    ],
    6: [
        (0, 0, "And"),
        (1, 2, "were desirous"),
        (3, 4, "the people"),
        (5, 6, "that should be"),
        (7, 7, "Alma"),
        (8, 8, "as"),
        (9, 11, "their king,"),
        (12, 12, "for"),
        (13, 16, "he was beloved"),
        (17, 19, "by his people."),
    ],
    7: [
        (0, 0, "But"),
        (1, 5, "he said"),
        (6, 9, "unto them:"),
        (10, 10, "Behold"),
        (11, 14, "it is not expedient"),
        (15, 16, "there be"),
        (17, 19, "a king"),
        (20, 23, "unto us;"),
        (24, 24, "for"),
        (25, 29, "thus saith"),
        (30, 32, "the Lord:"),
        (33, 33, "do not"),
        (34, 36, "ye esteem above"),
        (37, 40, "in your thoughts"),
        (41, 43, "one man"),
        (44, 47, "above another;"),
        (48, 49, "nor think"),
        (50, 53, "a single man"),
        (54, 58, "himself above"),
        (59, 62, "above"),
        (63, 65, "another man;"),
        (66, 67, "therefore"),
        (68, 72, "I say"),
        (73, 75, "unto you"),
        (76, 79, "it is not expedient"),
        (80, 81, "there be"),
        (82, 84, "a king of yours."),
    ],
    8: [
        (0, 3, "Nevertheless,"),
        (4, 6, "if it were so"),
        (7, 9, "could"),
        (10, 11, "ye have"),
        (12, 12, "always"),
        (13, 15, "just men"),
        (16, 18, "to be"),
        (19, 21, "your kings"),
        (22, 23, "it would be well"),
        (24, 25, "to have"),
        (26, 29, "a king of yours."),
    ],
    9: [
        (0, 0, "But"),
        (1, 2, "remember"),
        (3, 4, "the iniquity"),
        (5, 7, "of king"),
        (8, 9, "Noah"),
        (10, 10, "and"),
        (11, 12, "his priests;"),
        (13, 13, "and"),
        (14, 16, "was also caught"),
        (17, 19, "myself"),
        (20, 22, "in a snare,"),
        (23, 25, "and did"),
        (26, 26, "things"),
        (27, 28, "many"),
        (29, 30, "which were abominable"),
        (31, 33, "in the sight"),
        (34, 36, "of the Lord,"),
        (37, 40, "which brought"),
        (41, 43, "unto me"),
        (44, 46, "sore repentance."),
    ],
    10: [
        (0, 3, "Nevertheless,"),
        (4, 6, "after had passed"),
        (7, 9, "my much tribulation,"),
        (10, 12, "it came to pass"),
        (13, 14, "did hear"),
        (15, 16, "the Lord"),
        (17, 19, "my cries,"),
        (20, 22, "and did answer"),
        (23, 25, "my prayers,"),
        (26, 26, "and"),
        (27, 31, "he has made me"),
        (32, 34, "an instrument"),
        (35, 37, "in his hands"),
        (38, 40, "in bringing"),
        (41, 44, "of so many"),
        (45, 46, "of you"),
        (47, 49, "to a knowledge"),
        (50, 52, "of his truth."),
    ],
    11: [
        (0, 3, "Nevertheless,"),
        (4, 7, "I do not glory"),
        (8, 10, "in this,"),
        (11, 11, "for"),
        (12, 15, "I am unworthy"),
        (16, 18, "to glory"),
        (19, 23, "of myself."),
    ],
    12: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 6, "I say"),
        (7, 9, "unto you,"),
        (10, 12, "ye have been oppressed"),
        (13, 15, "by king"),
        (16, 17, "Noah,"),
        (18, 18, "and"),
        (19, 21, "have been in bondage"),
        (22, 24, "to him"),
        (25, 25, "and"),
        (26, 27, "his priests,"),
        (28, 28, "and"),
        (29, 31, "have been brought"),
        (32, 34, "into iniquity"),
        (35, 37, "by them;"),
        (38, 39, "therefore"),
        (40, 42, "were bound"),
        (43, 43, "ye"),
        (44, 45, "with the bands"),
        (46, 48, "of iniquity."),
    ],
    13: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "as"),
        (6, 6, "have been delivered"),
        (7, 7, "ye"),
        (8, 10, "by the power"),
        (11, 13, "of God"),
        (14, 16, "out of these bonds;"),
        (17, 17, "yea,"),
        (18, 20, "even out"),
        (21, 22, "from the hands"),
        (23, 25, "of king"),
        (26, 27, "Noah"),
        (28, 28, "and"),
        (29, 30, "his people,"),
        (31, 31, "and"),
        (32, 34, "also from the bonds"),
        (35, 37, "of iniquity,"),
        (38, 41, "even so"),
        (42, 43, "I desire"),
        (44, 45, "that ye"),
        (46, 47, "should stand fast"),
        (48, 50, "in this liberty"),
        (51, 53, "wherewith have been made free"),
        (54, 54, "ye,"),
        (55, 55, "and"),
        (56, 59, "that ye trust not"),
        (60, 62, "any man"),
        (63, 66, "to be a king"),
        (67, 70, "over you."),
    ],
    14: [
        (0, 2, "And also"),
        (3, 6, "ye trust not"),
        (7, 9, "any one"),
        (10, 12, "to be"),
        (13, 15, "your teacher"),
        (16, 17, "nor"),
        (18, 20, "your minister,"),
        (21, 22, "except"),
        (23, 24, "he be"),
        (25, 27, "a man"),
        (28, 30, "of God,"),
        (31, 33, "walking"),
        (34, 36, "in his ways"),
        (37, 38, "and keeping"),
        (39, 41, "his commandments."),
    ],
    15: [
        (0, 2, "Thus"),
        (3, 3, "taught"),
        (4, 5, "Alma"),
        (6, 7, "his people,"),
        (8, 9, "that should love"),
        (10, 11, "every man"),
        (12, 16, "his neighbor"),
        (17, 19, "as"),
        (20, 24, "himself,"),
        (25, 26, "that"),
        (27, 27, "there be no"),
        (28, 29, "contention"),
        (30, 32, "among"),
        (33, 34, "them."),
    ],
    16: [
        (0, 0, "And"),
        (1, 2, "now,"),
        (3, 4, "was"),
        (5, 5, "Alma"),
        (6, 6, "as"),
        (7, 10, "their high priest,"),
        (11, 11, "for"),
        (12, 13, "it was he"),
        (14, 15, "who founded"),
        (16, 18, "their church."),
    ],
    17: [
        (0, 3, "And it came to pass"),
        (4, 7, "none"),
        (8, 11, "received"),
        (12, 13, "authority"),
        (14, 15, "to preach"),
        (16, 19, "or to teach"),
        (20, 21, "except"),
        (22, 25, "it were by him"),
        (26, 28, "from God."),
        (29, 30, "Therefore"),
        (31, 35, "he consecrated"),
        (36, 39, "all their priests"),
        (40, 40, "and"),
        (41, 44, "all their teachers;"),
        (45, 45, "and"),
        (46, 47, "none were"),
        (48, 49, "others"),
        (50, 51, "consecrated"),
        (52, 53, "except"),
        (54, 56, "they"),
        (57, 60, "were just men."),
    ],
    18: [
        (0, 1, "Therefore"),
        (2, 5, "they did watch over"),
        (6, 9, "their people,"),
        (10, 11, "and did nourish"),
        (12, 13, "them"),
        (14, 16, "with things pertaining"),
        (17, 19, "to righteousness."),
    ],
    19: [
        (0, 3, "And it came to pass"),
        (4, 5, "began"),
        (6, 7, "they to prosper"),
        (8, 8, "exceedingly"),
        (9, 11, "in the land;"),
        (12, 12, "and"),
        (13, 15, "they called"),
        (16, 17, "the land"),
        (18, 19, "Helam."),
    ],
    20: [
        (0, 3, "And it came to pass"),
        (4, 5, "they did multiply"),
        (6, 8, "and prosper exceedingly"),
        (9, 11, "in the land"),
        (12, 13, "of Helam;"),
        (14, 14, "and"),
        (15, 17, "they built"),
        (18, 19, "a city,"),
        (20, 20, "which"),
        (21, 23, "they called"),
        (24, 26, "the city"),
        (27, 28, "of Helam."),
    ],
    21: [
        (0, 3, "Nevertheless"),
        (4, 5, "seeth fit"),
        (6, 7, "the Lord"),
        (8, 10, "fitting to"),
        (11, 11, "chasten"),
        (12, 13, "his people;"),
        (14, 14, "yea,"),
        (15, 17, "he trieth"),
        (18, 20, "their patience"),
        (21, 21, "and"),
        (22, 24, "their faith."),
    ],
    22: [
        (0, 3, "Nevertheless—"),
        (4, 6, "whosoever"),
        (7, 9, "putteth"),
        (10, 11, "his trust"),
        (12, 14, "in him"),
        (15, 18, "the same"),
        (19, 23, "shall be lifted up"),
        (24, 26, "at the day"),
        (27, 27, "last."),
        (28, 28, "Yea,"),
        (29, 29, "and"),
        (30, 34, "thus it was"),
        (35, 37, "with this people."),
    ],
    23: [
        (0, 0, "For"),
        (1, 1, "behold,"),
        (2, 7, "I will show"),
        (8, 10, "unto you"),
        (11, 12, "were brought"),
        (13, 14, "they"),
        (15, 17, "into bondage,"),
        (18, 18, "and"),
        (19, 22, "none"),
        (23, 25, "could"),
        (26, 26, "deliver"),
        (27, 28, "them"),
        (29, 30, "but"),
        (31, 33, "the Lord"),
        (34, 36, "their God,"),
        (37, 37, "yea,"),
        (38, 41, "even the God"),
        (42, 43, "of Abraham"),
        (44, 45, "and Isaac"),
        (46, 47, "and of Jacob."),
    ],
    24: [
        (0, 3, "And it came to pass"),
        (4, 9, "he did deliver them,"),
        (10, 10, "and"),
        (11, 14, "he did show forth"),
        (15, 17, "his mighty power"),
        (18, 21, "unto them,"),
        (22, 22, "and"),
        (23, 25, "great were"),
        (26, 28, "their rejoicings."),
    ],
    25: [
        (0, 0, "For"),
        (1, 1, "behold,"),
        (2, 4, "it came to pass"),
        (5, 7, "while were"),
        (8, 9, "they"),
        (10, 12, "in the land"),
        (13, 14, "of Helam,"),
        (15, 15, "yea,"),
        (16, 18, "in the city"),
        (19, 20, "of Helam,"),
        (21, 23, "while tilling"),
        (24, 25, "the land"),
        (26, 28, "round about,"),
        (29, 29, "behold"),
        (30, 32, "there was"),
        (33, 34, "an army"),
        (35, 37, "of the Lamanites"),
        (38, 40, "in the borders of"),
        (41, 42, "the land."),
    ],
    26: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "it came to pass"),
        (6, 6, "fled"),
        (7, 7, "the brethren"),
        (8, 9, "of Alma"),
        (10, 13, "from their fields,"),
        (14, 17, "and gathered together"),
        (18, 20, "themselves"),
        (21, 23, "in the city"),
        (24, 25, "of Helam;"),
        (26, 26, "and"),
        (27, 30, "they were much frightened"),
        (31, 32, "because of"),
        (33, 36, "the coming of"),
        (37, 38, "the Lamanites."),
    ],
    27: [
        (0, 0, "But"),
        (1, 3, "went forth"),
        (4, 4, "Alma"),
        (5, 7, "and stood"),
        (8, 10, "among"),
        (11, 12, "them,"),
        (13, 15, "and exhorted"),
        (16, 19, "them"),
        (20, 22, "that should not"),
        (23, 25, "they be frightened,"),
        (26, 26, "but"),
        (27, 29, "that they should remember"),
        (30, 31, "the Lord"),
        (32, 34, "their God"),
        (35, 35, "and"),
        (36, 40, "he would deliver"),
        (41, 42, "them."),
    ],
    28: [
        (0, 1, "Therefore"),
        (2, 5, "they hushed"),
        (6, 8, "their fears,"),
        (9, 11, "and began"),
        (12, 14, "they to cry"),
        (15, 17, "unto the Lord"),
        (18, 21, "that he would soften"),
        (22, 23, "the hearts of"),
        (24, 25, "the Lamanites,"),
        (26, 27, "that"),
        (28, 29, "they would spare"),
        (30, 31, "them,"),
        (32, 32, "and"),
        (33, 35, "their wives,"),
        (36, 36, "and"),
        (37, 39, "their children."),
    ],
    29: [
        (0, 3, "And it came to pass"),
        (4, 4, "did soften"),
        (5, 7, "the Lord"),
        (8, 9, "the hearts of"),
        (10, 11, "the Lamanites."),
        (12, 12, "And"),
        (13, 15, "went forth"),
        (16, 16, "Alma"),
        (17, 19, "and his brethren"),
        (20, 22, "and delivered up"),
        (23, 25, "themselves"),
        (26, 29, "into their hands;"),
        (30, 30, "and"),
        (31, 32, "took"),
        (33, 35, "the Lamanites"),
        (36, 37, "the land"),
        (38, 39, "of Helam"),
        (40, 42, "for themselves."),
    ],
    30: [
        (0, 1, "Now"),
        (2, 3, "the armies"),
        (4, 6, "of the Lamanites,"),
        (7, 9, "which had followed"),
        (10, 12, "after the people"),
        (13, 15, "of king"),
        (16, 17, "Limhi,"),
        (18, 19, "had been lost"),
        (20, 22, "in the wilderness"),
        (23, 24, "for days"),
        (25, 26, "many."),
    ],
    31: [
        (0, 0, "And"),
        (1, 1, "behold"),
        (2, 4, "they had found"),
        (5, 6, "those priests"),
        (7, 9, "of king"),
        (10, 11, "Noah,"),
        (12, 14, "in a place"),
        (15, 17, "which they called"),
        (18, 19, "Amulon;"),
        (20, 20, "and"),
        (21, 23, "had begun"),
        (24, 25, "they to possess"),
        (26, 28, "for themselves"),
        (29, 30, "the land"),
        (31, 32, "of Amulon"),
        (33, 35, "and had begun"),
        (36, 37, "they to till"),
        (38, 39, "the ground."),
    ],
    32: [
        (0, 1, "Now"),
        (2, 4, "the name"),
        (5, 7, "of the leader"),
        (8, 10, "of those priests,"),
        (11, 12, "was Amulon."),
    ],
    33: [
        (0, 3, "And it came to pass"),
        (4, 5, "did plead"),
        (6, 6, "Amulon"),
        (7, 9, "with the Lamanites;"),
        (10, 10, "and"),
        (11, 16, "he also sent"),
        (17, 19, "their wives,"),
        (20, 21, "who"),
        (22, 23, "were the daughters"),
        (24, 26, "of the Lamanites,"),
        (27, 29, "to plead"),
        (30, 33, "with their brethren,"),
        (34, 35, "that they"),
        (36, 37, "should not destroy"),
        (38, 40, "their husbands."),
    ],
    34: [
        (0, 0, "And"),
        (1, 2, "had compassion on"),
        (3, 3, "Amulon"),
        (4, 4, "and"),
        (5, 6, "his brethren"),
        (7, 9, "the Lamanites,"),
        (10, 10, "and"),
        (11, 14, "did not destroy"),
        (15, 16, "them,"),
        (17, 18, "because of"),
        (19, 21, "their wives."),
    ],
    35: [
        (0, 0, "And"),
        (1, 3, "did join"),
        (4, 4, "Amulon"),
        (5, 5, "and"),
        (6, 7, "his brethren"),
        (8, 9, "together with"),
        (10, 11, "the Lamanites,"),
        (12, 12, "and"),
        (13, 16, "they were traveling"),
        (17, 19, "in the wilderness"),
        (20, 21, "in search of"),
        (22, 23, "the land"),
        (24, 25, "of Nephi"),
        (26, 26, "when"),
        (27, 29, "they discovered"),
        (30, 31, "the land"),
        (32, 33, "of Helam,"),
        (34, 34, "which"),
        (35, 37, "dwelt in by"),
        (38, 38, "Alma"),
        (39, 41, "and his brethren."),
    ],
    36: [
        (0, 3, "And it came to pass"),
        (4, 5, "promised"),
        (6, 8, "the Lamanites"),
        (9, 10, "unto Alma"),
        (11, 13, "and his brethren,"),
        (14, 14, "if"),
        (15, 18, "they would show"),
        (19, 22, "them"),
        (23, 24, "the way"),
        (25, 28, "which led to"),
        (29, 30, "the land"),
        (31, 32, "of Nephi,"),
        (33, 38, "that they would grant"),
        (39, 42, "unto them"),
        (43, 45, "their lives"),
        (46, 46, "and"),
        (47, 49, "their liberty."),
    ],
    37: [
        (0, 0, "But"),
        (1, 4, "after had finished"),
        (5, 6, "showing"),
        (7, 8, "Alma"),
        (9, 12, "them"),
        (13, 14, "the way"),
        (15, 17, "to the land"),
        (18, 19, "of Nephi,"),
        (20, 22, "would not keep"),
        (23, 25, "the Lamanites"),
        (26, 28, "their promise;"),
        (29, 29, "but"),
        (30, 33, "they set round about"),
        (34, 34, "guards"),
        (35, 37, "the land"),
        (38, 39, "of Helam,"),
        (40, 42, "over"),
        (43, 43, "Alma"),
        (44, 44, "and"),
        (45, 46, "his brethren."),
    ],
    38: [
        (0, 0, "And"),
        (1, 3, "the part"),
        (4, 5, "that remained"),
        (6, 8, "of them"),
        (9, 11, "went"),
        (12, 14, "to the land"),
        (15, 16, "of Nephi;"),
        (17, 17, "and"),
        (18, 20, "a part"),
        (21, 24, "of them,"),
        (25, 28, "returned"),
        (29, 31, "to the land"),
        (32, 33, "of Helam,"),
        (34, 34, "and"),
        (35, 37, "they brought"),
        (38, 38, "also"),
        (39, 42, "with them"),
        (43, 43, "the wives"),
        (44, 45, "and the children"),
        (46, 47, "of the guards"),
        (48, 49, "who"),
        (50, 51, "had been left"),
        (52, 54, "in the land."),
    ],
    39: [
        (0, 0, "And"),
        (1, 3, "had granted"),
        (4, 6, "the king"),
        (7, 9, "of the Lamanites"),
        (10, 11, "unto Amulon"),
        (12, 15, "that he should be"),
        (16, 17, "a king"),
        (18, 19, "and a ruler"),
        (20, 22, "over"),
        (23, 24, "his people,"),
        (25, 26, "who"),
        (27, 30, "were in the land"),
        (31, 32, "of Helam;"),
        (33, 36, "nevertheless,"),
        (37, 41, "he should have no"),
        (42, 43, "power"),
        (44, 47, "to do"),
        (48, 50, "anything,"),
        (51, 54, "contrary to"),
        (55, 57, "the will"),
        (58, 60, "of the king"),
        (61, 63, "of the Lamanites."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
