"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 17 — the sons of
Mosiah meet Alma; their missions among the Lamanites; Ammon becomes a
servant to king Lamoni and defends the king's flocks at the waters of
Sebus.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15).

    python3 build_overrides_alma17.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 17

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "it came to pass that"),
        (6, 8, "as was journeying"),
        (9, 9, "Alma"),
        (10, 14, "from the land of Gideon"),
        (15, 16, "toward"),
        (17, 20, "the south,"),
        (21, 25, "away to"),
        (26, 29, "the land of Manti,"),
        (30, 30, "behold,"),
        (31, 34, "he was astonished,"),
        (35, 38, "at his meeting with"),
        (39, 41, "the sons of Mosiah,"),
        (42, 46, "journeying toward"),
        (47, 50, "the land of Zarahemla."),
    ],
    2: [
        (0, 1, "Now"),
        (2, 4, "these sons"),
        (5, 6, "of Mosiah"),
        (7, 9, "were with"),
        (10, 10, "Alma"),
        (11, 13, "at the time"),
        (14, 18, "first appeared"),
        (19, 20, "the angel"),
        (21, 23, "unto him;"),
        (24, 25, "therefore"),
        (26, 28, "did rejoice exceedingly"),
        (29, 29, "Alma"),
        (30, 34, "to see"),
        (35, 36, "his brethren;"),
        (37, 40, "and what"),
        (41, 44, "added more"),
        (45, 46, "to his joy,"),
        (47, 47, "was that"),
        (48, 52, "they were still"),
        (53, 55, "his brethren"),
        (56, 58, "in the Lord;"),
        (59, 59, "yea,"),
        (60, 64, "and they had waxed strong"),
        (65, 68, "in the knowledge of"),
        (69, 70, "the truth;"),
        (71, 71, "for"),
        (72, 74, "they were"),
        (75, 79, "men of a sound understanding"),
        (80, 83, "and they had searched"),
        (84, 86, "the scriptures"),
        (87, 89, "diligently,"),
        (90, 93, "that they might know"),
        (94, 96, "the word of"),
        (97, 98, "God."),
    ],
    3: [
        (0, 0, "But"),
        (1, 5, "this is not all;"),
        (6, 9, "they had given"),
        (10, 12, "themselves"),
        (13, 16, "to much prayer,"),
        (17, 19, "and fasting;"),
        (20, 21, "therefore"),
        (22, 25, "there was"),
        (26, 28, "in them"),
        (29, 32, "the spirit of prophecy,"),
        (33, 37, "and the spirit of revelation,"),
        (38, 42, "and when they taught,"),
        (43, 46, "they taught"),
        (47, 49, "with power"),
        (50, 52, "and authority"),
        (53, 55, "of God."),
    ],
    4: [
        (0, 4, "And they had been teaching"),
        (5, 9, "the word of God"),
        (10, 14, "among the Lamanites"),
        (15, 18, "for the space of"),
        (19, 22, "fourteen years,"),
        (23, 26, "having had much success"),
        (27, 28, "they"),
        (29, 33, "in bringing"),
        (34, 35, "many"),
        (36, 39, "to the knowledge of"),
        (40, 41, "the truth;"),
        (42, 42, "yea,"),
        (43, 46, "by the power of"),
        (47, 49, "their words"),
        (50, 52, "were brought"),
        (53, 54, "many"),
        (55, 57, "before"),
        (58, 62, "the altar of God,"),
        (63, 66, "to call on"),
        (67, 68, "his name"),
        (69, 71, "and confess"),
        (72, 74, "their sins"),
        (75, 77, "before him."),
    ],
    5: [
        (0, 1, "Now"),
        (2, 4, "these were the circumstances"),
        (5, 10, "which attended them"),
        (11, 13, "in their journeyings,"),
        (14, 14, "for"),
        (15, 16, "were many"),
        (17, 19, "their afflictions;"),
        (20, 23, "they did suffer much,"),
        (24, 26, "in body"),
        (27, 29, "and in mind,"),
        (30, 32, "such as"),
        (33, 35, "hunger,"),
        (36, 37, "thirst"),
        (38, 41, "and fatigue,"),
        (42, 46, "and also much"),
        (47, 47, "labor"),
        (48, 51, "in the spirit."),
    ],
    6: [
        (0, 1, "Now"),
        (2, 6, "these are their journeyings:"),
        (7, 10, "Having taken leave of"),
        (11, 13, "their father,"),
        (14, 15, "Mosiah,"),
        (16, 19, "in the first year"),
        (20, 21, "of the judges;"),
        (22, 25, "having refused"),
        (26, 27, "the kingdom"),
        (28, 30, "which desired"),
        (31, 33, "their father"),
        (34, 35, "to confer"),
        (36, 39, "upon them,"),
        (40, 40, "and"),
        (41, 45, "this also was"),
        (46, 49, "in the mind of"),
        (50, 51, "the people;"),
    ],
    7: [
        (0, 3, "Nevertheless"),
        (4, 8, "they departed"),
        (9, 13, "out of the land of Zarahemla,"),
        (14, 15, "and took"),
        (16, 18, "their swords,"),
        (19, 22, "and their spears,"),
        (23, 26, "and their bows,"),
        (27, 30, "and their arrows,"),
        (31, 34, "and their slings;"),
        (35, 38, "and they did"),
        (39, 40, "this"),
        (41, 44, "that might"),
        (45, 46, "they provide"),
        (47, 49, "food"),
        (50, 53, "for themselves"),
        (54, 57, "while they were"),
        (58, 60, "in the wilderness."),
    ],
    8: [
        (0, 3, "And thus"),
        (4, 7, "they departed"),
        (8, 10, "into the wilderness"),
        (11, 12, "with"),
        (13, 17, "their numbers"),
        (18, 20, "which they had selected,"),
        (21, 24, "to go up to"),
        (25, 28, "the land of Nephi,"),
        (29, 31, "to preach"),
        (32, 36, "the word of God"),
        (37, 39, "unto the Lamanites."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they journeyed"),
        (7, 9, "in the wilderness"),
        (10, 13, "many days,"),
        (14, 18, "and they fasted much"),
        (19, 21, "and prayed much"),
        (22, 25, "that would grant"),
        (26, 28, "the Lord"),
        (29, 33, "a portion of his Spirit"),
        (34, 37, "to go with"),
        (38, 39, "them"),
        (40, 43, "and abide with"),
        (44, 45, "them,"),
        (46, 49, "that might"),
        (50, 52, "they be"),
        (53, 55, "an instrument"),
        (56, 60, "in the hands of God"),
        (61, 62, "to bring"),
        (63, 66, "if it were possible,"),
        (67, 69, "their brethren,"),
        (70, 72, "the Lamanites,"),
        (73, 76, "to the knowledge of"),
        (77, 78, "the truth,"),
        (79, 82, "to the knowledge of"),
        (83, 85, "the baseness of"),
        (86, 87, "the traditions of"),
        (88, 90, "their fathers,"),
        (91, 94, "which were not correct."),
    ],
    10: [
        (0, 3, "And it came to pass that"),
        (4, 5, "did visit"),
        (6, 7, "the Lord"),
        (8, 11, "them"),
        (12, 14, "with"),
        (15, 16, "his Spirit,"),
        (17, 19, "and said"),
        (20, 23, "unto them:"),
        (24, 26, "Be ye comforted."),
        (27, 29, "And were comforted"),
        (30, 31, "they."),
    ],
    11: [
        (0, 4, "And also said"),
        (5, 6, "the Lord"),
        (7, 10, "unto them:"),
        (11, 14, "Go ye forth"),
        (15, 19, "among the Lamanites,"),
        (20, 22, "your brethren,"),
        (23, 24, "and establish"),
        (25, 26, "my word;"),
        (27, 27, "yet"),
        (28, 30, "ye shall be patient"),
        (31, 33, "in long-suffering"),
        (34, 35, "and afflictions,"),
        (36, 39, "that may"),
        (40, 42, "ye show forth"),
        (43, 44, "good examples"),
        (45, 48, "unto them"),
        (49, 51, "through"),
        (52, 54, "me,"),
        (55, 60, "and I will make"),
        (61, 61, "you"),
        (62, 65, "an instrument"),
        (66, 68, "in my hands"),
        (69, 72, "unto the salvation of"),
        (73, 75, "many souls."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 4, "took courage"),
        (5, 6, "the hearts of"),
        (7, 9, "the sons of Mosiah,"),
        (10, 13, "and also those"),
        (14, 18, "who were with"),
        (19, 20, "them,"),
        (21, 23, "to go forth"),
        (24, 26, "unto the Lamanites"),
        (27, 29, "to declare"),
        (30, 33, "unto them"),
        (34, 38, "the word of God."),
    ],
    13: [
        (0, 3, "And it came to pass"),
        (4, 7, "when they had arrived"),
        (8, 10, "in the borders of"),
        (11, 15, "the land of the Lamanites,"),
        (16, 18, "that they separated"),
        (19, 21, "themselves"),
        (22, 25, "and departed"),
        (26, 30, "one from another,"),
        (31, 33, "trusting in"),
        (34, 35, "the Lord"),
        (36, 41, "that they should meet again"),
        (42, 45, "at the close of"),
        (46, 48, "their harvest;"),
        (49, 49, "for"),
        (50, 52, "they supposed"),
        (53, 55, "that great was"),
        (56, 57, "the work"),
        (58, 61, "which they had undertaken."),
    ],
    14: [
        (0, 3, "And assuredly"),
        (4, 7, "it was great,"),
        (8, 8, "for"),
        (9, 11, "they had undertaken"),
        (12, 14, "to preach"),
        (15, 19, "the word of God"),
        (20, 23, "to a wild people,"),
        (24, 25, "and hardened"),
        (26, 27, "and ferocious;"),
        (28, 30, "a people"),
        (31, 33, "who delighted in"),
        (34, 38, "murdering the Nephites,"),
        (39, 42, "and robbing and plundering"),
        (43, 45, "their goods;"),
        (46, 48, "and were set"),
        (49, 51, "their hearts"),
        (52, 53, "upon riches,"),
        (54, 58, "or upon gold and silver,"),
        (59, 61, "and precious stones;"),
        (62, 62, "yet"),
        (63, 65, "they sought"),
        (66, 67, "to obtain"),
        (68, 69, "these things"),
        (70, 73, "by murdering"),
        (74, 76, "and plundering,"),
        (77, 81, "that they might not labor"),
        (82, 86, "with their own hands"),
        (87, 89, "for these."),
    ],
    15: [
        (0, 4, "Thus were"),
        (5, 6, "they"),
        (7, 11, "a very indolent people,"),
        (12, 15, "many of"),
        (16, 17, "whom"),
        (18, 21, "did worship idols,"),
        (22, 25, "and had fallen"),
        (26, 29, "upon them"),
        (30, 34, "the curse of God"),
        (35, 36, "because of"),
        (37, 38, "the traditions of"),
        (39, 41, "their fathers;"),
        (42, 45, "notwithstanding"),
        (46, 48, "were extended"),
        (49, 52, "unto them"),
        (53, 56, "the promises of the Lord"),
        (57, 61, "on the conditions of"),
        (62, 63, "repentance."),
    ],
    16: [
        (0, 1, "Therefore,"),
        (2, 5, "this was the cause"),
        (6, 8, "for which undertook"),
        (9, 12, "the sons of Mosiah"),
        (13, 16, "the work,"),
        (17, 18, "that perhaps"),
        (19, 22, "might"),
        (23, 24, "they bring"),
        (25, 27, "them"),
        (28, 30, "unto repentance;"),
        (31, 32, "that perhaps"),
        (33, 36, "might"),
        (37, 38, "they bring"),
        (39, 41, "them"),
        (42, 44, "to know"),
        (45, 47, "of"),
        (48, 52, "the plan of redemption."),
    ],
    17: [
        (0, 1, "Therefore"),
        (2, 5, "they separated"),
        (6, 8, "themselves"),
        (9, 11, "one from another,"),
        (12, 14, "and went forth"),
        (15, 17, "among them,"),
        (18, 21, "every man"),
        (22, 23, "alone,"),
        (24, 26, "according to"),
        (27, 28, "the word"),
        (29, 32, "and the power of"),
        (33, 34, "God"),
        (35, 37, "which was given"),
        (38, 40, "unto him."),
    ],
    18: [
        (0, 1, "Now"),
        (2, 4, "Ammon being"),
        (5, 6, "the chief"),
        (7, 9, "among them,"),
        (10, 11, "or rather"),
        (12, 15, "he did administer"),
        (16, 19, "unto them,"),
        (20, 25, "he departed"),
        (26, 29, "from them,"),
        (30, 35, "after having blessed"),
        (36, 39, "them"),
        (40, 42, "according to"),
        (43, 46, "their several stations,"),
        (47, 51, "after he had"),
        (52, 53, "imparted"),
        (54, 57, "the word of"),
        (58, 59, "God"),
        (60, 63, "unto them,"),
        (64, 66, "or administered"),
        (67, 70, "unto them"),
        (71, 77, "before he departed;"),
        (78, 81, "and thus"),
        (82, 84, "they took"),
        (85, 88, "their several journeys"),
        (89, 92, "throughout all the land."),
    ],
    19: [
        (0, 0, "And"),
        (1, 3, "went"),
        (4, 4, "Ammon"),
        (5, 9, "to the land of Ishmael,"),
        (10, 13, "the land"),
        (14, 16, "being called after"),
        (17, 19, "the sons of Ishmael,"),
        (20, 20, "who"),
        (21, 24, "also became"),
        (25, 26, "Lamanites."),
    ],
    20: [
        (0, 4, "And as entered"),
        (5, 5, "Ammon"),
        (6, 10, "the land of Ishmael,"),
        (11, 14, "took him"),
        (15, 17, "the Lamanites"),
        (18, 21, "and bound him,"),
        (22, 24, "according to"),
        (25, 27, "their custom"),
        (28, 31, "of binding"),
        (32, 34, "all the Nephites"),
        (35, 37, "who fell"),
        (38, 41, "into their hands,"),
        (42, 43, "and carry"),
        (44, 45, "them"),
        (46, 50, "before the king;"),
        (51, 54, "and thus"),
        (55, 56, "it was left"),
        (57, 60, "to the pleasure of"),
        (61, 62, "the king"),
        (63, 64, "to slay"),
        (65, 66, "them,"),
        (67, 68, "or to retain"),
        (69, 70, "them"),
        (71, 72, "in captivity,"),
        (73, 74, "or to cast"),
        (75, 76, "them"),
        (77, 79, "into prison,"),
        (80, 82, "or to cast out"),
        (83, 84, "them"),
        (85, 87, "out of his land,"),
        (88, 90, "according to"),
        (91, 92, "his will"),
        (93, 95, "and pleasure."),
    ],
    21: [
        (0, 3, "And thus"),
        (4, 4, "was carried"),
        (5, 6, "Ammon"),
        (7, 11, "before the king"),
        (12, 16, "who was over"),
        (17, 20, "the land of Ishmael;"),
        (21, 24, "and his name"),
        (25, 26, "was Lamoni;"),
        (27, 29, "and he was"),
        (30, 34, "a descendant"),
        (35, 36, "of Ishmael."),
    ],
    22: [
        (0, 0, "And"),
        (1, 3, "inquired"),
        (4, 5, "the king"),
        (6, 7, "of Ammon"),
        (8, 8, "if"),
        (9, 11, "it were his desire"),
        (12, 14, "to dwell"),
        (15, 17, "in the land"),
        (18, 22, "among the Lamanites,"),
        (23, 26, "or among"),
        (27, 28, "his people."),
    ],
    23: [
        (0, 0, "And"),
        (1, 3, "said"),
        (4, 4, "Ammon"),
        (5, 7, "unto him:"),
        (8, 8, "Yea,"),
        (9, 11, "I desire"),
        (12, 14, "to dwell"),
        (15, 19, "among this people"),
        (20, 22, "for a time;"),
        (23, 23, "yea,"),
        (24, 26, "and perhaps"),
        (27, 29, "until"),
        (30, 31, "the day"),
        (32, 35, "I die."),
    ],
    24: [
        (0, 3, "And it came to pass that"),
        (4, 5, "was much pleased"),
        (6, 9, "king Lamoni"),
        (10, 11, "with Ammon,"),
        (12, 14, "and caused"),
        (15, 16, "that should be loosed"),
        (17, 18, "his bands;"),
        (19, 22, "and he would"),
        (23, 24, "that should take"),
        (25, 26, "Ammon"),
        (27, 31, "one of his daughters"),
        (32, 36, "to wife."),
    ],
    25: [
        (0, 0, "But"),
        (1, 3, "said"),
        (4, 4, "Ammon"),
        (5, 7, "unto him:"),
        (8, 9, "Nay,"),
        (10, 10, "but"),
        (11, 15, "I will be"),
        (16, 18, "thy servant."),
        (19, 20, "Therefore"),
        (21, 23, "became"),
        (24, 24, "Ammon"),
        (25, 27, "a servant"),
        (28, 32, "to king Lamoni."),
        (33, 36, "And it came to pass that"),
        (37, 39, "he was set"),
        (40, 43, "among"),
        (44, 45, "other servants"),
        (46, 47, "to watch"),
        (48, 51, "the flocks of Lamoni,"),
        (52, 54, "according to"),
        (55, 57, "the custom of"),
        (58, 59, "the Lamanites."),
    ],
    26: [
        (0, 3, "And after had passed"),
        (4, 6, "three days"),
        (7, 12, "since he had served"),
        (13, 15, "the king,"),
        (16, 19, "as they were with"),
        (20, 22, "the Lamanitish servants"),
        (23, 25, "going forth"),
        (26, 30, "with their flocks"),
        (31, 33, "to a place"),
        (34, 37, "where was water,"),
        (38, 41, "which was called"),
        (42, 45, "the water of Sebus,"),
        (46, 48, "and thither"),
        (49, 53, "did drive"),
        (54, 56, "the Lamanites"),
        (57, 60, "their flocks,"),
        (61, 64, "that may"),
        (65, 67, "they have"),
        (68, 69, "water—"),
    ],
    27: [
        (0, 1, "Therefore"),
        (2, 4, "as were driving forth"),
        (5, 7, "Ammon and"),
        (8, 11, "the servants of the king"),
        (12, 15, "their flocks"),
        (16, 19, "to this place of"),
        (20, 21, "the water,"),
        (22, 22, "behold,"),
        (23, 25, "stood"),
        (26, 30, "a certain number of the Lamanites,"),
        (31, 34, "who were at"),
        (35, 36, "the water"),
        (37, 38, "with"),
        (39, 42, "their flocks,"),
        (43, 44, "and scattered"),
        (45, 48, "the flocks of Ammon"),
        (49, 53, "and the servants of the king,"),
        (54, 58, "and they did scatter greatly"),
        (59, 60, "them"),
        (61, 64, "insomuch that"),
        (65, 67, "they fled"),
        (68, 70, "in many ways."),
    ],
    28: [
        (0, 1, "Now"),
        (2, 4, "began to"),
        (5, 5, "murmur"),
        (6, 10, "the servants of the king,"),
        (11, 12, "saying:"),
        (13, 17, "Now will slay"),
        (18, 19, "us"),
        (20, 22, "the king,"),
        (23, 27, "as he has done"),
        (28, 31, "to our brethren"),
        (32, 32, "because"),
        (33, 34, "were scattered"),
        (35, 38, "their flocks"),
        (39, 43, "by the wickedness of"),
        (44, 45, "these men."),
        (46, 49, "And began to"),
        (50, 52, "they weep exceedingly,"),
        (53, 54, "saying:"),
        (55, 55, "Behold,"),
        (56, 58, "are scattered already"),
        (59, 62, "our flocks."),
    ],
    29: [
        (0, 1, "Now"),
        (2, 4, "they wept"),
        (5, 8, "because of the fear"),
        (9, 10, "of being slain"),
        (11, 12, "they."),
        (13, 14, "Now"),
        (15, 18, "when saw"),
        (19, 19, "Ammon"),
        (20, 22, "this"),
        (23, 24, "was swollen"),
        (25, 26, "his heart"),
        (27, 30, "within him"),
        (31, 33, "with joy;"),
        (34, 34, "for,"),
        (35, 39, "said he,"),
        (40, 45, "I will show forth"),
        (46, 47, "my power"),
        (48, 52, "unto these"),
        (53, 57, "my fellow-servants,"),
        (58, 61, "or the power"),
        (62, 65, "which is in me,"),
        (66, 69, "in restoring"),
        (70, 72, "these flocks"),
        (73, 75, "unto the king,"),
        (76, 79, "that may"),
        (80, 82, "I win"),
        (83, 84, "the hearts of"),
        (85, 89, "these my fellow-servants,"),
        (90, 93, "that may"),
        (94, 96, "I lead"),
        (97, 99, "them"),
        (100, 101, "to believe"),
        (102, 104, "in my words."),
    ],
    30: [
        (0, 0, "And"),
        (1, 2, "now,"),
        (3, 5, "these were the thoughts"),
        (6, 7, "of Ammon,"),
        (8, 13, "when he saw"),
        (14, 16, "the afflictions of"),
        (17, 18, "those"),
        (19, 23, "whom he termed"),
        (24, 26, "his brethren."),
    ],
    31: [
        (0, 3, "And it came to pass that"),
        (4, 5, "he encouraged"),
        (6, 7, "them"),
        (8, 10, "by his words"),
        (11, 13, "saying:"),
        (14, 16, "My brethren,"),
        (17, 19, "be ye of good cheer"),
        (20, 23, "and let us go"),
        (24, 26, "to search for"),
        (27, 28, "the flocks,"),
        (29, 33, "and we will"),
        (34, 36, "gather together"),
        (37, 38, "them"),
        (39, 41, "and bring back"),
        (42, 43, "them"),
        (44, 47, "unto the place of"),
        (48, 49, "water;"),
        (50, 55, "and thus"),
        (56, 58, "we will preserve"),
        (59, 60, "the flocks"),
        (61, 63, "unto the king"),
        (64, 64, "and"),
        (65, 71, "he will not slay"),
        (72, 73, "us."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they went"),
        (7, 9, "in search of"),
        (10, 11, "the flocks,"),
        (12, 16, "and they did follow"),
        (17, 18, "Ammon,"),
        (19, 23, "and they rushed forth"),
        (24, 27, "with much swiftness"),
        (28, 30, "and did head"),
        (31, 35, "the flocks of the king,"),
        (36, 40, "and did gather together again"),
        (41, 42, "them"),
        (43, 46, "to the place of"),
        (47, 48, "water."),
    ],
    33: [
        (0, 4, "And stood again"),
        (5, 6, "those men"),
        (7, 8, "to scatter"),
        (9, 12, "their flocks;"),
        (13, 13, "but"),
        (14, 16, "said"),
        (17, 17, "Ammon"),
        (18, 20, "unto his brethren:"),
        (21, 22, "Encircle round about"),
        (23, 25, "the flocks"),
        (26, 29, "that they flee not;"),
        (30, 34, "and I will"),
        (35, 36, "go"),
        (37, 39, "and contend with"),
        (40, 41, "these men"),
        (42, 45, "who do scatter"),
        (46, 49, "our flocks."),
    ],
    34: [
        (0, 1, "Therefore"),
        (2, 4, "they did"),
        (5, 9, "as commanded"),
        (10, 11, "them"),
        (12, 13, "Ammon,"),
        (14, 19, "and he went forth"),
        (20, 21, "and stood"),
        (22, 24, "to contend with"),
        (25, 28, "those who"),
        (29, 30, "stood"),
        (31, 33, "by"),
        (34, 36, "the waters of Sebus;"),
        (37, 39, "and they were many"),
        (40, 42, "not a few"),
        (43, 44, "they."),
    ],
    35: [
        (0, 1, "Therefore"),
        (2, 5, "they did not fear"),
        (6, 7, "Ammon,"),
        (8, 8, "for"),
        (9, 11, "they supposed"),
        (12, 13, "could"),
        (14, 17, "that one of"),
        (18, 21, "their men"),
        (22, 22, "slay"),
        (23, 25, "him"),
        (26, 28, "according to"),
        (29, 31, "their pleasure,"),
        (32, 32, "for"),
        (33, 36, "they knew not"),
        (37, 39, "had promised"),
        (40, 41, "the Lord"),
        (42, 43, "Mosiah"),
        (44, 48, "that he would deliver"),
        (49, 50, "his sons"),
        (51, 54, "out of their hands;"),
        (55, 59, "neither did they know"),
        (60, 61, "anything"),
        (62, 64, "concerning"),
        (65, 66, "the Lord;"),
        (67, 68, "therefore"),
        (69, 72, "they delighted"),
        (73, 76, "in the destruction of"),
        (77, 79, "their brethren;"),
        (80, 84, "and for this cause"),
        (85, 89, "they stood"),
        (90, 91, "to scatter"),
        (92, 96, "the flocks of the king."),
    ],
    36: [
        (0, 0, "But"),
        (1, 3, "stood forth"),
        (4, 4, "Ammon"),
        (5, 7, "and began to"),
        (8, 10, "he cast"),
        (11, 12, "stones"),
        (13, 16, "at them"),
        (17, 19, "with his sling;"),
        (20, 20, "yea,"),
        (21, 25, "he did sling stones"),
        (26, 29, "with mighty power"),
        (30, 34, "amongst them;"),
        (35, 38, "and thus"),
        (39, 41, "he slew"),
        (42, 45, "a certain number of"),
        (46, 47, "them"),
        (48, 51, "insomuch that"),
        (52, 56, "they began to be astonished"),
        (57, 59, "at his power;"),
        (60, 63, "nevertheless"),
        (64, 66, "they were angry"),
        (67, 68, "because of"),
        (69, 71, "their brethren"),
        (72, 73, "who were slain,"),
        (74, 77, "and they were determined"),
        (78, 80, "that should"),
        (81, 83, "he fall;"),
        (84, 85, "therefore,"),
        (86, 88, "seeing"),
        (89, 92, "that could not"),
        (93, 95, "he be hit"),
        (96, 99, "with their stones,"),
        (100, 103, "they came forth"),
        (104, 107, "with their clubs"),
        (108, 112, "to slay him."),
    ],
    37: [
        (0, 1, "But behold,"),
        (2, 5, "every man"),
        (6, 9, "that lifted"),
        (10, 11, "his club"),
        (12, 14, "to smite Ammon,"),
        (15, 18, "he smote off"),
        (19, 21, "their arms"),
        (22, 24, "with his sword;"),
        (25, 25, "for"),
        (26, 28, "he did withstand"),
        (29, 31, "their blows"),
        (32, 35, "by smiting"),
        (36, 38, "their arms"),
        (39, 42, "with the edge of"),
        (43, 44, "his sword,"),
        (45, 47, "insomuch that"),
        (48, 51, "they began to be astonished,"),
        (52, 56, "and began to flee"),
        (57, 59, "before him;"),
        (60, 60, "yea,"),
        (61, 64, "and were not few"),
        (65, 67, "their number;"),
        (68, 71, "and he caused"),
        (72, 75, "them to flee"),
        (76, 78, "by"),
        (79, 81, "the strength of"),
        (82, 83, "his arm."),
    ],
    38: [
        (0, 1, "Now"),
        (2, 5, "six of them"),
        (6, 7, "had fallen"),
        (8, 10, "by the sling,"),
        (11, 11, "but"),
        (12, 15, "he did not slay"),
        (16, 17, "any"),
        (18, 20, "with his sword"),
        (21, 22, "save"),
        (23, 25, "their leader;"),
        (26, 30, "and he smote off"),
        (31, 33, "as many of"),
        (34, 36, "their arms"),
        (37, 38, "as were lifted"),
        (39, 43, "against him,"),
        (44, 47, "and they were not a few"),
        (48, 49, "they."),
    ],
    39: [
        (0, 5, "And when he had"),
        (6, 8, "driven afar off"),
        (9, 10, "them,"),
        (11, 15, "he returned"),
        (16, 18, "and they watered"),
        (19, 22, "their flocks"),
        (23, 25, "and returned"),
        (26, 27, "them"),
        (28, 29, "to the land"),
        (30, 33, "for keeping the flocks"),
        (34, 36, "of the king,"),
        (37, 39, "and then they"),
        (40, 43, "went in"),
        (44, 46, "unto the king,"),
        (47, 49, "bearing"),
        (50, 50, "the arms"),
        (51, 53, "which had been smitten off"),
        (54, 58, "by the sword of Ammon,"),
        (59, 63, "of those who"),
        (64, 65, "sought"),
        (66, 67, "to slay"),
        (68, 70, "him;"),
        (71, 72, "and were carried"),
        (73, 74, "they"),
        (75, 77, "unto the king"),
        (78, 81, "for a testimony of"),
        (82, 85, "the things which they had done."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
