"""Hand-curated TAM-phrase gloss overrides for 1 Nifae 20 — Isaiah 48 quotation."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "1nephi"
CHAPTER_NUM = 20
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "Hearken"),
        (4, 6, "and hear"),
        (7, 10, "to this,"),
        (11, 13, "O house"),
        (14, 15, "of Jacob,"),
        (16, 19, "who are called"),
        (20, 22, "by the name"),
        (23, 24, "of Israel,"),
        (25, 29, "and come out"),
        (30, 32, "the waters of Judah,"),
        (33, 35, "or coming"),
        (36, 38, "up"),
        (39, 39, "of waters"),
        (40, 42, "of baptism,"),
        (43, 45, "who have"),
        (46, 46, "sworn"),
        (47, 49, "by the name"),
        (50, 52, "of the Lord,"),
        (53, 55, "and make mention"),
        (56, 57, "the God"),
        (58, 59, "of Israel,"),
        (60, 63, "yet they do not"),
        (64, 64, "swear"),
        (65, 67, "in truth"),
        (68, 71, "nor in righteousness."),
    ],
    2: [
        (0, 3, "Nevertheless,"),
        (4, 6, "they call"),
        (7, 9, "themselves"),
        (10, 13, "of the holy city,"),
        (14, 17, "but they do not"),
        (18, 18, "stay"),
        (19, 21, "upon the God"),
        (22, 23, "of Israel,"),
        (24, 26, "who is"),
        (27, 28, "the Lord"),
        (29, 30, "of Hosts;"),
        (31, 31, "yea,"),
        (32, 34, "the Lord"),
        (35, 36, "of Hosts"),
        (37, 40, "is his name."),
    ],
    3: [
        (0, 0, "Behold,"),
        (1, 4, "I have declared"),
        (5, 9, "the former things"),
        (10, 12, "from the beginning;"),
        (13, 16, "and went"),
        (17, 18, "those things"),
        (19, 21, "out of my mouth,"),
        (22, 26, "and I showed"),
        (27, 28, "them."),
        (29, 31, "suddenly did"),
        (32, 34, "I show"),
        (35, 37, "them."),
    ],
    4: [
        (0, 3, "And I did"),
        (4, 5, "this thing"),
        (6, 9, "because I knew"),
        (10, 12, "thou art obstinate"),
        (13, 16, "and thy neck"),
        (17, 20, "an iron sinew,"),
        (21, 24, "and thy brow"),
        (25, 27, "brass;"),
    ],
    5: [
        (0, 4, "And I have declared"),
        (5, 5, "even"),
        (6, 8, "unto thee"),
        (9, 11, "from the beginning;"),
        (12, 15, "before it came to pass"),
        (16, 17, "those things"),
        (18, 22, "I showed"),
        (23, 24, "them"),
        (25, 27, "unto thee;"),
        (28, 32, "and I showed"),
        (33, 34, "them"),
        (35, 37, "for fear"),
        (38, 41, "lest thou say:"),
        (42, 44, "mine idol"),
        (45, 48, "hath done them,"),
        (49, 53, "and my graven image,"),
        (54, 57, "and my molten image"),
        (58, 61, "hath commanded them."),
    ],
    6: [
        (0, 1, "Thou hast"),
        (2, 2, "seen"),
        (3, 4, "and heard"),
        (5, 8, "all this;"),
        (9, 12, "and will ye not"),
        (13, 15, "declare?"),
        (16, 17, "them?"),
        (18, 22, "And I have showed"),
        (23, 23, "also"),
        (24, 26, "unto thee"),
        (27, 28, "new things"),
        (29, 32, "from this time,"),
        (33, 36, "even hidden things,"),
        (37, 41, "but thou didst not know"),
        (42, 43, "them."),
    ],
    7: [
        (0, 2, "are created now"),
        (3, 4, "they,"),
        (5, 8, "and not from"),
        (9, 11, "the beginning,"),
        (12, 16, "but were declared"),
        (17, 21, "them unto thee"),
        (22, 23, "before"),
        (24, 27, "came the day"),
        (28, 32, "thou heardest not"),
        (33, 36, "them,"),
        (37, 40, "lest thou say—Behold"),
        (41, 43, "I knew"),
        (44, 45, "them."),
    ],
    8: [
        (0, 0, "Yea,"),
        (1, 5, "and thou heardest not"),
        (6, 6, "indeed;"),
        (7, 7, "yea,"),
        (8, 12, "thou knewest not;"),
        (13, 13, "yea,"),
        (14, 16, "from that time"),
        (17, 20, "was not opened"),
        (21, 22, "thine ear;"),
        (23, 26, "for I knew"),
        (27, 30, "thou wouldst"),
        (31, 31, "deal"),
        (32, 34, "very treacherously,"),
        (35, 37, "and wast called"),
        (38, 38, "thou"),
        (39, 42, "a transgressor"),
        (43, 47, "from the womb."),
    ],
    9: [
        (0, 3, "Nevertheless,"),
        (4, 7, "will I"),
        (8, 9, "defer"),
        (10, 11, "mine anger"),
        (12, 15, "for my name's sake,"),
        (16, 19, "and for my praise"),
        (20, 23, "will I"),
        (24, 25, "refrain"),
        (26, 26, "myself"),
        (27, 30, "from thee,"),
        (31, 33, "that I"),
        (34, 35, "not cut off"),
        (36, 36, "thee."),
    ],
    10: [
        (0, 1, "For behold,"),
        (2, 4, "I have refined"),
        (5, 5, "thee,"),
        (6, 8, "I have chosen"),
        (9, 9, "thee"),
        (10, 13, "in the furnace"),
        (14, 15, "of affliction."),
    ],
    11: [
        (0, 3, "For mine own sake,"),
        (4, 4, "yea,"),
        (5, 8, "for mine own sake"),
        (9, 12, "will I"),
        (13, 14, "do"),
        (15, 16, "this thing,"),
        (17, 21, "for will I"),
        (22, 22, "not"),
        (23, 23, "suffer"),
        (24, 25, "my name"),
        (26, 27, "to be polluted,"),
        (28, 32, "and will I"),
        (33, 33, "not"),
        (34, 35, "give"),
        (36, 37, "my glory"),
        (38, 40, "unto another."),
    ],
    12: [
        (0, 2, "Hearken"),
        (3, 5, "unto me,"),
        (6, 7, "O Jacob,"),
        (8, 9, "and Israel"),
        (10, 12, "my called,"),
        (13, 15, "for I"),
        (16, 17, "am he;"),
        (18, 19, "I am"),
        (20, 23, "the first,"),
        (24, 26, "and I am"),
        (27, 27, "also"),
        (28, 31, "the last."),
    ],
    13: [
        (0, 3, "Mine hand also"),
        (4, 5, "hath laid"),
        (6, 7, "the foundation"),
        (8, 10, "of the earth,"),
        (11, 12, "and"),
        (13, 15, "my right hand"),
        (16, 17, "hath spanned"),
        (18, 19, "the heavens."),
        (20, 23, "I call unto"),
        (24, 27, "them"),
        (28, 30, "and they"),
        (31, 32, "stand together"),
        (33, 35, "up."),
    ],
    14: [
        (0, 1, "All ye,"),
        (2, 4, "assemble"),
        (5, 6, "yourselves,"),
        (7, 7, "and"),
        (8, 9, "hear;"),
        (10, 12, "who"),
        (13, 15, "among"),
        (16, 19, "them"),
        (20, 23, "hath declared"),
        (24, 25, "these things"),
        (26, 29, "unto them?"),
        (30, 31, "hath loved"),
        (32, 33, "the Lord"),
        (34, 36, "him;"),
        (37, 37, "yea,"),
        (38, 41, "and will"),
        (42, 44, "he fulfill"),
        (45, 46, "his word"),
        (47, 50, "which he hath declared"),
        (51, 53, "by"),
        (54, 57, "them;"),
        (58, 61, "and will"),
        (62, 64, "he do"),
        (65, 66, "his pleasure"),
        (67, 70, "on Babylon,"),
        (71, 74, "and shall"),
        (75, 76, "come"),
        (77, 78, "his arm"),
        (79, 82, "upon the Chaldeans."),
    ],
    15: [
        (0, 2, "Also,"),
        (3, 5, "saith"),
        (6, 7, "the Lord:"),
        (8, 9, "I"),
        (10, 12, "the Lord,"),
        (13, 13, "yea,"),
        (14, 17, "I have spoken;"),
        (18, 18, "yea,"),
        (19, 23, "I have called him"),
        (24, 26, "to declare,"),
        (27, 31, "I have brought him,"),
        (32, 35, "and shall"),
        (36, 38, "he make"),
        (39, 40, "his way"),
        (41, 42, "prosperous."),
    ],
    16: [
        (0, 1, "Come ye"),
        (2, 5, "near"),
        (6, 8, "unto me;"),
        (9, 13, "I have not spoken"),
        (14, 14, "in secret;"),
        (15, 16, "even from"),
        (17, 19, "the beginning,"),
        (20, 22, "from the time"),
        (23, 26, "that was declared"),
        (27, 28, "this thing"),
        (29, 33, "have I spoken;"),
        (34, 37, "and the Lord"),
        (38, 39, "God,"),
        (40, 42, "and his Spirit,"),
        (43, 45, "hath sent"),
        (46, 46, "me."),
    ],
    17: [
        (0, 2, "And thus"),
        (3, 5, "saith"),
        (6, 8, "the Lord,"),
        (9, 10, "thy Redeemer,"),
        (11, 14, "the Holy One"),
        (15, 16, "of Israel;"),
        (17, 20, "I have sent"),
        (21, 22, "him,"),
        (23, 24, "the Lord"),
        (25, 26, "thy God"),
        (27, 31, "who teacheth"),
        (32, 34, "thee"),
        (35, 37, "to profit,"),
        (38, 41, "who leadeth"),
        (42, 44, "thee"),
        (45, 47, "by the way"),
        (48, 50, "should"),
        (51, 53, "thou go,"),
        (54, 57, "hath done it."),
    ],
    18: [
        (0, 0, "O,"),
        (1, 3, "that thou hadst"),
        (4, 6, "hearkened"),
        (7, 9, "to my commandments—then"),
        (10, 12, "had been as"),
        (13, 13, "thy"),
        (14, 14, "peace"),
        (15, 17, "as a river,"),
        (18, 20, "and thy righteousness"),
        (21, 23, "as"),
        (24, 27, "the waves of the sea;"),
    ],
    19: [
        (0, 3, "Thy seed also"),
        (4, 6, "had been as"),
        (7, 9, "the sand;"),
        (10, 12, "the offspring also"),
        (13, 15, "of thy bowels"),
        (16, 18, "like"),
        (19, 21, "its gravel;"),
        (22, 26, "should not have been cut off"),
        (27, 29, "nor destroyed"),
        (30, 31, "his name"),
        (32, 35, "from before me."),
    ],
    20: [
        (0, 1, "Ye"),
        (2, 5, "go"),
        (6, 7, "from Babylon,"),
        (8, 9, "ye"),
        (10, 13, "flee"),
        (14, 15, "from the Chaldeans,"),
        (16, 18, "with"),
        (19, 20, "a voice"),
        (21, 22, "of singing"),
        (23, 26, "declare ye,"),
        (27, 28, "tell"),
        (29, 30, "this,"),
        (31, 33, "utter"),
        (34, 35, "to the end"),
        (36, 38, "of the earth;"),
        (39, 42, "say ye:"),
        (43, 44, "Hath redeemed"),
        (45, 47, "the Lord"),
        (48, 49, "his servant"),
        (50, 51, "Jacob."),
    ],
    21: [
        (0, 4, "And they did not"),
        (5, 5, "thirst;"),
        (6, 9, "he led"),
        (10, 11, "them"),
        (12, 14, "through"),
        (15, 16, "the deserts;"),
        (17, 20, "he caused"),
        (21, 23, "to flow"),
        (24, 25, "the waters"),
        (26, 30, "out of the rock"),
        (31, 33, "for them;"),
        (34, 38, "he clave also"),
        (39, 40, "the rock"),
        (41, 44, "and gushed out"),
        (45, 46, "the waters."),
    ],
    22: [
        (0, 3, "And notwithstanding"),
        (4, 7, "he hath done"),
        (8, 10, "all this,"),
        (11, 15, "and greater also,"),
        (16, 19, "there is no peace,"),
        (20, 23, "saith"),
        (24, 25, "the Lord,"),
        (26, 29, "unto the wicked."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
