"""Hand-curated TAM-phrase gloss overrides for Ominae 1 — Multiple authors record dwindling Nephite/Zarahemla lineage."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "omni"
CHAPTER_NUM = 1
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "Behold,"),
        (1, 4, "it came to pass was commanded"),
        (5, 7, "I, Omni,"),
        (8, 12, "by my father, Jarom,"),
        (13, 15, "that should"),
        (16, 18, "I write"),
        (19, 23, "upon these plates,"),
        (24, 26, "to preserve"),
        (27, 29, "our genealogy—"),
    ],
    2: [
        (0, 3, "Wherefore,"),
        (4, 6, "in my days,"),
        (7, 9, "I would that"),
        (10, 12, "ye know"),
        (13, 16, "I have greatly"),
        (17, 20, "fought with the sword"),
        (21, 23, "to preserve"),
        (24, 25, "my people,"),
        (26, 28, "the Nephites,"),
        (29, 32, "from falling"),
        (33, 35, "into the hands"),
        (36, 38, "of their enemies,"),
        (39, 41, "the Lamanites."),
        (42, 43, "But behold,"),
        (44, 47, "I of myself"),
        (48, 51, "am a wicked man,"),
        (52, 56, "and I have not kept"),
        (57, 59, "the statutes and commandments"),
        (60, 62, "of the Lord"),
        (63, 65, "as"),
        (66, 68, "ought"),
        (69, 71, "of me"),
        (72, 73, "to do."),
    ],
    3: [
        (0, 0, "And"),
        (1, 5, "it came to pass passed away"),
        (6, 10, "the two hundred and seventy"),
        (11, 15, "and six years,"),
        (16, 16, "and"),
        (17, 22, "many seasons of peace"),
        (23, 25, "which we had;"),
        (26, 26, "and"),
        (27, 32, "many seasons also of wars"),
        (33, 36, "severe and much bloodshed"),
        (37, 43, "did we suffer."),
        (44, 45, "Yea, and"),
        (46, 48, "in fine,"),
        (49, 52, "passed away"),
        (53, 56, "the two hundred and eighty"),
        (57, 61, "and two years,"),
        (62, 62, "and"),
        (63, 67, "I have kept these plates"),
        (68, 71, "according to the commandments"),
        (72, 74, "of my fathers;"),
        (75, 75, "and"),
        (76, 79, "I have conferred"),
        (80, 82, "them unto"),
        (83, 86, "my son Amaron."),
        (87, 87, "And"),
        (88, 90, "I make an end"),
        (91, 92, "of my writing."),
    ],
    4: [
        (0, 2, "And now,"),
        (3, 6, "I, Amaron,"),
        (7, 9, "do write"),
        (10, 13, "the things which I write,"),
        (14, 16, "which are few,"),
        (17, 19, "in the book"),
        (20, 22, "of my father."),
    ],
    5: [
        (0, 0, "Behold,"),
        (1, 5, "it came to pass passed away"),
        (6, 9, "the three hundred"),
        (10, 14, "and twenty years,"),
        (15, 15, "and"),
        (16, 19, "was destroyed the part"),
        (20, 23, "the more wicked part"),
        (24, 26, "of the Nephites."),
    ],
    6: [
        (0, 6, "For the Lord will not suffer,"),
        (7, 13, "after that he had led away"),
        (14, 16, "them"),
        (17, 21, "from the land of Jerusalem"),
        (22, 27, "and had kept and preserved them"),
        (28, 31, "from falling"),
        (32, 34, "into the hands"),
        (35, 37, "of their enemies,"),
        (38, 38, "yea,"),
        (39, 42, "he will not suffer"),
        (43, 45, "that not be verified"),
        (46, 47, "the words which"),
        (48, 51, "he spake"),
        (52, 55, "unto our fathers,"),
        (56, 57, "saying:"),
        (58, 61, "Inasmuch as"),
        (62, 65, "ye will not keep"),
        (66, 68, "my commandments"),
        (69, 74, "ye shall not prosper"),
        (75, 77, "in the land."),
    ],
    7: [
        (0, 3, "Wherefore,"),
        (4, 7, "did visit"),
        (8, 9, "the Lord"),
        (10, 13, "unto them"),
        (14, 17, "with a great judgment;"),
        (18, 21, "nevertheless,"),
        (22, 25, "he did spare"),
        (26, 27, "the righteous"),
        (28, 33, "that they should not perish,"),
        (34, 34, "but"),
        (35, 38, "did he deliver"),
        (39, 40, "them"),
        (41, 42, "from the hands"),
        (43, 46, "of their enemies."),
    ],
    8: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 6, "I delivered"),
        (7, 7, "the plates"),
        (8, 12, "unto my brother Chemish."),
    ],
    9: [
        (0, 1, "Now,"),
        (2, 5, "I, Chemish,"),
        (6, 8, "do write"),
        (9, 10, "the few things"),
        (11, 13, "which I write,"),
        (14, 18, "in the same book"),
        (19, 22, "with my brother;"),
        (23, 24, "for behold,"),
        (25, 27, "I saw"),
        (28, 30, "the last"),
        (31, 34, "which he wrote,"),
        (35, 35, "and"),
        (36, 39, "he wrote"),
        (40, 43, "with his own hand;"),
        (44, 44, "and"),
        (45, 48, "he wrote them"),
        (49, 52, "in the same day"),
        (53, 58, "that he delivered"),
        (59, 59, "the plates"),
        (60, 62, "unto me."),
        (63, 63, "And"),
        (64, 67, "in this manner"),
        (68, 71, "we do keep"),
        (72, 72, "the records,"),
        (73, 73, "for"),
        (74, 76, "it is according"),
        (77, 78, "to the manner"),
        (79, 83, "of the commandments of our fathers."),
        (84, 84, "And"),
        (85, 87, "I make an end"),
        (88, 89, "of my writing."),
    ],
    10: [
        (0, 0, "Behold,"),
        (1, 4, "I, Abinadom,"),
        (5, 9, "am the son of Chemish."),
        (10, 10, "Behold,"),
        (11, 15, "it came to pass I saw"),
        (16, 21, "much war and contentions"),
        (22, 27, "between my people,"),
        (28, 30, "the Nephites,"),
        (31, 33, "and the Lamanites;"),
        (34, 34, "and"),
        (35, 36, "I of myself,"),
        (37, 39, "did slay"),
        (40, 43, "with my own sword,"),
        (44, 47, "many warriors"),
        (48, 50, "of the Lamanites"),
        (51, 53, "in the defense"),
        (54, 56, "of my brethren."),
    ],
    11: [
        (0, 1, "And behold,"),
        (2, 7, "the record of this people"),
        (8, 9, "is engraven"),
        (10, 13, "upon plates"),
        (14, 17, "kept by kings,"),
        (18, 20, "according to"),
        (21, 23, "the reigns of kings;"),
        (24, 24, "and"),
        (25, 28, "I know not"),
        (29, 30, "of any revelation"),
        (31, 34, "save that written,"),
        (35, 38, "or a prophecy;"),
        (39, 42, "wherefore,"),
        (43, 46, "the things written"),
        (47, 49, "are sufficient."),
        (50, 50, "And"),
        (51, 53, "I make an end"),
        (54, 55, "of my writing."),
    ],
    12: [
        (0, 0, "Behold,"),
        (1, 4, "I, Amaleki,"),
        (5, 8, "the son of Abinadom."),
        (9, 9, "Behold,"),
        (10, 14, "I speak myself"),
        (15, 17, "unto you"),
        (18, 21, "concerning Mosiah,"),
        (22, 23, "who"),
        (24, 27, "was made king"),
        (28, 32, "over the land"),
        (33, 34, "of Zarahemla;"),
        (35, 36, "for behold,"),
        (37, 39, "was warned"),
        (40, 44, "he by the Lord"),
        (45, 47, "that should"),
        (48, 50, "flee away"),
        (51, 52, "he"),
        (53, 57, "out of the land of Nephi,"),
        (58, 58, "and"),
        (59, 61, "should also"),
        (62, 65, "many of them"),
        (66, 66, "who"),
        (67, 69, "would hearken"),
        (70, 75, "unto the voice of the Lord"),
        (76, 76, "that"),
        (77, 79, "should depart"),
        (80, 82, "out of the land"),
        (83, 85, "with him,"),
        (86, 88, "into the wilderness—"),
    ],
    13: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 6, "he did"),
        (7, 11, "as commanded"),
        (12, 16, "he by the Lord."),
        (17, 17, "And"),
        (18, 22, "they did depart"),
        (23, 25, "out of the land"),
        (26, 28, "into the wilderness,"),
        (29, 34, "as many of them"),
        (35, 36, "who"),
        (37, 39, "would hearken"),
        (40, 45, "unto the voice of the Lord;"),
        (46, 46, "and"),
        (47, 50, "were led they"),
        (51, 54, "by preachings and prophesyings"),
        (55, 56, "many."),
        (57, 57, "And"),
        (58, 61, "were admonished they"),
        (62, 64, "continually"),
        (65, 70, "by the word of God;"),
        (71, 71, "and"),
        (72, 75, "were led they"),
        (76, 78, "in the wilderness"),
        (79, 84, "by the power of his arm,"),
        (85, 87, "until"),
        (88, 90, "they came down"),
        (91, 93, "into the land"),
        (94, 96, "which is called"),
        (97, 100, "the land of Zarahemla."),
    ],
    14: [
        (0, 0, "And"),
        (1, 3, "they discovered"),
        (4, 5, "a people,"),
        (6, 9, "who were called"),
        (10, 14, "the people of Zarahemla."),
        (15, 16, "Now,"),
        (17, 19, "did rejoice exceedingly"),
        (20, 23, "the people of Zarahemla;"),
        (24, 24, "and"),
        (25, 28, "did also rejoice exceedingly"),
        (29, 29, "Zarahemla,"),
        (30, 30, "because"),
        (31, 33, "had sent"),
        (34, 36, "the Lord"),
        (37, 40, "the people of Mosiah"),
        (41, 43, "and the plates of brass"),
        (44, 46, "which contained"),
        (47, 51, "the record of the Jews."),
    ],
    15: [
        (0, 0, "Behold,"),
        (1, 3, "it came to pass"),
        (4, 6, "discovered Mosiah"),
        (7, 10, "the people of Zarahemla"),
        (11, 14, "came out"),
        (15, 15, "from Jerusalem"),
        (16, 18, "at the time"),
        (19, 22, "when was carried captive"),
        (23, 23, "Zedekiah,"),
        (24, 27, "the king of Judah,"),
        (28, 29, "into Babylon."),
    ],
    16: [
        (0, 0, "And"),
        (1, 3, "they journeyed"),
        (4, 6, "in the wilderness,"),
        (7, 7, "and"),
        (8, 14, "were brought by the hand of the Lord"),
        (15, 20, "across the many waters,"),
        (21, 23, "into the land"),
        (24, 27, "which found thereto"),
        (28, 31, "them Mosiah;"),
        (32, 32, "and"),
        (33, 34, "there"),
        (35, 38, "they did dwell"),
        (39, 41, "from that time"),
        (42, 44, "and forward"),
        (45, 47, "into the future."),
    ],
    17: [
        (0, 0, "And"),
        (1, 3, "at the time"),
        (4, 6, "when were found"),
        (7, 10, "they by Mosiah,"),
        (11, 14, "were exceeding numerous"),
        (15, 16, "they."),
        (17, 20, "Nevertheless,"),
        (21, 26, "there had been many wars and serious contentions"),
        (27, 31, "which they had had among them,"),
        (32, 32, "and"),
        (33, 38, "they had fallen by the sword"),
        (39, 44, "from time to time;"),
        (45, 45, "and"),
        (46, 49, "was no more clear"),
        (50, 52, "their language;"),
        (53, 53, "and"),
        (54, 57, "they had not brought"),
        (58, 61, "with them"),
        (62, 63, "any records;"),
        (64, 64, "and"),
        (65, 67, "they denied"),
        (68, 70, "the being"),
        (71, 74, "of their Creator;"),
        (75, 75, "and"),
        (76, 79, "could not"),
        (80, 81, "understand Mosiah,"),
        (82, 87, "nor the people of Mosiah,"),
        (88, 91, "them."),
    ],
    18: [
        (0, 0, "But"),
        (1, 3, "it came to pass"),
        (4, 6, "Mosiah caused"),
        (7, 10, "that they be taught"),
        (11, 13, "in his language."),
        (14, 14, "And"),
        (15, 17, "it came to pass"),
        (18, 21, "after they had been taught"),
        (22, 24, "them"),
        (25, 29, "in the language of Mosiah,"),
        (30, 34, "did rehearse Zarahemla"),
        (35, 36, "the genealogy"),
        (37, 39, "of his fathers,"),
        (40, 44, "according to his memory;"),
        (45, 45, "and"),
        (46, 49, "they are written,"),
        (50, 51, "but not"),
        (52, 54, "upon the plates"),
        (55, 55, "these."),
    ],
    19: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 5, "united together"),
        (6, 9, "the people of Zarahemla,"),
        (10, 10, "and"),
        (11, 14, "the people of Mosiah;"),
        (15, 15, "and"),
        (16, 18, "was appointed Mosiah"),
        (19, 21, "to be"),
        (22, 24, "their king."),
    ],
    20: [
        (0, 0, "And"),
        (1, 2, "it came to pass"),
        (3, 6, "in the days of Mosiah,"),
        (7, 9, "was brought thereto"),
        (10, 12, "unto him"),
        (13, 15, "a large stone"),
        (16, 18, "which had"),
        (19, 20, "engravings"),
        (21, 23, "upon it;"),
        (24, 24, "and"),
        (25, 28, "he did interpret"),
        (29, 29, "the engravings"),
        (30, 32, "by the gift"),
        (33, 35, "and the power"),
        (36, 38, "of God."),
    ],
    21: [
        (0, 0, "And"),
        (1, 3, "did give an account"),
        (4, 5, "the engravings"),
        (6, 7, "a record"),
        (8, 10, "of a man"),
        (11, 13, "whose name was"),
        (14, 14, "Coriantumr,"),
        (15, 15, "and"),
        (16, 19, "the people of his kingdom"),
        (20, 21, "who were slain."),
        (22, 22, "And"),
        (23, 25, "was found Coriantumr"),
        (26, 30, "by the people of Zarahemla;"),
        (31, 31, "and"),
        (32, 35, "did dwell he"),
        (36, 39, "with them"),
        (40, 42, "for the space"),
        (43, 46, "of nine moons."),
    ],
    22: [
        (0, 4, "It gave also thereto"),
        (5, 7, "a few words"),
        (8, 12, "concerning his fathers."),
        (13, 13, "And"),
        (14, 17, "his first parents"),
        (18, 20, "came out"),
        (21, 23, "from the tower,"),
        (24, 26, "at the time"),
        (27, 29, "when did confound"),
        (30, 32, "the Lord"),
        (33, 36, "the language of the people;"),
        (37, 37, "and"),
        (38, 40, "it came to pass"),
        (41, 42, "did fall down"),
        (43, 46, "upon them"),
        (47, 52, "the severity of the Lord"),
        (53, 57, "according to his judgments,"),
        (58, 59, "which are just;"),
        (60, 60, "and"),
        (61, 64, "their bones"),
        (65, 69, "are strewn scattered about"),
        (70, 72, "in the land"),
        (73, 74, "in the north."),
    ],
    23: [
        (0, 0, "Behold,"),
        (1, 4, "I, Amaleki,"),
        (5, 7, "was born"),
        (8, 11, "in the days of Mosiah;"),
        (12, 12, "and"),
        (13, 15, "I have lived"),
        (16, 17, "to see"),
        (18, 20, "his death;"),
        (21, 21, "and"),
        (22, 25, "Benjamin, his son,"),
        (26, 27, "reigns"),
        (28, 29, "in stead"),
        (30, 32, "of him."),
    ],
    24: [
        (0, 1, "And behold,"),
        (2, 4, "I saw,"),
        (5, 11, "in the days of King Benjamin,"),
        (12, 14, "a great war"),
        (15, 18, "and much bloodshed"),
        (19, 22, "between"),
        (23, 24, "the Nephites"),
        (25, 27, "and the Lamanites."),
        (28, 29, "But behold,"),
        (30, 33, "were exceedingly strong"),
        (34, 35, "the Nephites"),
        (36, 39, "than they;"),
        (40, 40, "yea,"),
        (41, 43, "it came to pass"),
        (44, 47, "did drive them"),
        (48, 52, "King Benjamin"),
        (53, 55, "out of the land"),
        (56, 57, "of Zarahemla."),
    ],
    25: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 5, "began to"),
        (6, 7, "I old age;"),
        (8, 8, "and,"),
        (9, 9, "because"),
        (10, 13, "was no seed of mine,"),
        (14, 14, "and"),
        (15, 18, "because I know"),
        (19, 23, "that King Benjamin"),
        (24, 27, "is a just man"),
        (28, 32, "before the Lord,"),
        (33, 36, "wherefore,"),
        (37, 42, "I shall deliver up"),
        (43, 44, "these plates"),
        (45, 49, "unto him,"),
        (50, 50, "and"),
        (51, 55, "exhorting all men"),
        (56, 61, "to come unto God,"),
        (62, 67, "the Holy One of Israel,"),
        (68, 71, "and believe in prophesyings,"),
        (72, 73, "and revelations,"),
        (74, 77, "and the ministering of angels,"),
        (78, 85, "and the gift of speaking in tongues,"),
        (86, 93, "and the gift of the interpreting of tongues,"),
        (94, 99, "and all things which are good;"),
        (100, 100, "for"),
        (101, 105, "there is no good thing"),
        (106, 107, "save that"),
        (108, 112, "which cometh from the Lord:"),
        (113, 113, "and"),
        (114, 118, "that which is evil"),
        (119, 121, "cometh from"),
        (122, 124, "the devil."),
    ],
    26: [
        (0, 2, "And now,"),
        (3, 6, "my beloved brethren,"),
        (7, 9, "I would that"),
        (10, 11, "ye"),
        (12, 15, "come unto Christ,"),
        (16, 17, "who"),
        (18, 24, "is the Holy One of Israel,"),
        (25, 26, "and partake"),
        (27, 29, "of his salvation,"),
        (30, 35, "and the power of his redemption."),
        (36, 36, "Yea,"),
        (37, 41, "come unto him,"),
        (42, 42, "and"),
        (43, 44, "offer"),
        (45, 48, "your whole souls"),
        (49, 52, "as an offering"),
        (53, 55, "unto him,"),
        (56, 56, "and"),
        (57, 57, "fast"),
        (58, 60, "and pray still"),
        (61, 63, "continually,"),
        (64, 64, "and"),
        (65, 65, "endure"),
        (66, 70, "to the end;"),
        (71, 71, "and"),
        (72, 75, "as liveth"),
        (76, 77, "the Lord,"),
        (78, 81, "ye shall be saved"),
        (82, 82, "ye."),
    ],
    27: [
        (0, 2, "And now,"),
        (3, 8, "I would speak myself"),
        (9, 11, "concerning"),
        (12, 14, "a certain group"),
        (15, 16, "of people"),
        (17, 18, "who"),
        (19, 21, "went up"),
        (22, 24, "into the wilderness"),
        (25, 27, "to return"),
        (28, 32, "into the land of Nephi;"),
        (33, 33, "for"),
        (34, 36, "there was"),
        (37, 41, "a large number of people"),
        (42, 43, "who"),
        (44, 48, "did desire to possess"),
        (49, 51, "the land"),
        (52, 54, "of their inheritance."),
    ],
    28: [
        (0, 3, "Wherefore,"),
        (4, 8, "they did go up thereto"),
        (9, 11, "into the wilderness."),
        (12, 12, "And"),
        (13, 17, "because their leader"),
        (18, 24, "was a strong and mighty man,"),
        (25, 25, "and"),
        (26, 30, "a stiffnecked man,"),
        (31, 34, "wherefore,"),
        (35, 39, "he did stir up thereto"),
        (40, 46, "a contention among them;"),
        (47, 47, "and"),
        (48, 53, "were slain all of them"),
        (54, 55, "in the wilderness,"),
        (56, 57, "save"),
        (58, 59, "fifty,"),
        (60, 60, "and"),
        (61, 65, "they did return again"),
        (66, 70, "into the land of Zarahemla."),
    ],
    29: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 6, "they took also"),
        (7, 8, "others"),
        (9, 12, "in exceeding great numbers,"),
        (13, 13, "and"),
        (14, 18, "took again their journey"),
        (19, 21, "into the wilderness."),
    ],
    30: [
        (0, 4, "And I, Amaleki,"),
        (5, 7, "had"),
        (8, 9, "a brother,"),
        (10, 13, "who did also journey"),
        (14, 17, "with them;"),
        (18, 18, "and"),
        (19, 22, "since that time"),
        (23, 26, "I have not known"),
        (27, 34, "anything concerning them."),
        (35, 35, "And"),
        (36, 38, "I am about"),
        (39, 41, "to lie down"),
        (42, 44, "in my grave;"),
        (45, 45, "and"),
        (46, 49, "are full these plates."),
        (50, 50, "And"),
        (51, 53, "I make an end"),
        (54, 56, "of my words."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
