"""
Hand-curated TAM-phrase gloss overrides for Helamana (Helaman) 1 — the contention
over the judgment-seat among the sons of Pahoran; Paanchi's conspiracy and
execution, the murder of Pahoran the younger by Kishkumen, the Lamanite invasion
under Coriantumr that seizes Zarahemla, and the counterattack of Moronihah and
Lehi that recovers the city.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_helaman1.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "helaman"
CHAPTER_NUM = 1

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 5, "it came to pass"),
        (6, 9, "in the commencement of"),
        (10, 13, "the fortieth year"),
        (14, 17, "of the reign of"),
        (18, 18, "the judges"),
        (19, 22, "over the people of"),
        (23, 23, "Nephi,"),
        (24, 29, "there began to be"),
        (30, 33, "a serious difficulty"),
        (34, 36, "among"),
        (37, 39, "the Nephite people."),
    ],
    2: [
        (0, 1, "For behold,"),
        (2, 3, "had died"),
        (4, 4, "Pahoran,"),
        (5, 7, "and had gone"),
        (8, 11, "the way of"),
        (12, 14, "all the world;"),
        (15, 16, "therefore"),
        (17, 22, "there began to be"),
        (23, 26, "a serious contention"),
        (27, 29, "concerning"),
        (30, 34, "who should obtain"),
        (35, 36, "the judgment-seat"),
        (37, 40, "among the brethren,"),
        (41, 46, "who were the sons of"),
        (47, 47, "Pahoran."),
    ],
    3: [
        (0, 1, "Now"),
        (2, 7, "these are the names of them"),
        (8, 11, "who contended"),
        (12, 14, "for the judgment-seat,"),
        (15, 17, "who also"),
        (18, 22, "caused to contend"),
        (23, 25, "the people:"),
        (26, 27, "Pahoran,"),
        (28, 28, "Paanchi,"),
        (29, 30, "and Pacumeni."),
    ],
    4: [
        (0, 1, "Now"),
        (2, 8, "these are not all the sons of"),
        (9, 9, "Pahoran,"),
        (10, 10, "(for"),
        (11, 14, "he had"),
        (15, 18, "many sons),"),
        (19, 23, "but these"),
        (24, 25, "who contended"),
        (26, 28, "for the judgment-seat;"),
        (29, 30, "therefore"),
        (31, 34, "they caused"),
        (35, 38, "three divisions"),
        (39, 41, "among"),
        (42, 43, "the people."),
    ],
    5: [
        (0, 3, "Nevertheless,"),
        (4, 6, "it came to pass that"),
        (7, 8, "Pahoran was appointed"),
        (9, 12, "by the voice of"),
        (13, 14, "the people"),
        (15, 17, "to become"),
        (18, 19, "chief judge"),
        (20, 22, "and a governor"),
        (23, 26, "over the people of"),
        (27, 27, "Nephi."),
    ],
    6: [
        (0, 3, "And it came to pass that"),
        (4, 5, "saw"),
        (6, 7, "Pacumeni"),
        (8, 11, "could not"),
        (12, 13, "he obtain"),
        (14, 16, "the judgment-seat,"),
        (17, 20, "he did unite"),
        (21, 24, "with the will of"),
        (25, 26, "the people."),
    ],
    7: [
        (0, 1, "But behold,"),
        (2, 3, "Paanchi,"),
        (4, 8, "and that part of"),
        (9, 10, "the people"),
        (11, 14, "that were desirous"),
        (15, 20, "that he should become"),
        (21, 24, "their governor,"),
        (25, 27, "was exceedingly wroth;"),
        (28, 29, "therefore"),
        (30, 33, "he sought"),
        (34, 36, "to lead away"),
        (37, 38, "those people"),
        (39, 41, "with flattering words"),
        (42, 44, "to rise up"),
        (45, 46, "to rebel"),
        (47, 48, "against"),
        (49, 51, "their brethren."),
    ],
    8: [
        (0, 3, "And it came to pass that"),
        (4, 7, "he was about to do"),
        (8, 9, "this thing,"),
        (10, 10, "behold,"),
        (11, 14, "he was taken,"),
        (15, 16, "and was tried"),
        (17, 19, "according to"),
        (20, 22, "the will of"),
        (23, 24, "the people,"),
        (25, 28, "and was condemned"),
        (29, 31, "to death;"),
        (32, 32, "for"),
        (33, 36, "he rose up"),
        (37, 39, "in rebellion"),
        (40, 41, "and sought"),
        (42, 43, "to destroy"),
        (44, 46, "the liberty of"),
        (47, 48, "the people."),
    ],
    9: [
        (0, 1, "Now"),
        (2, 4, "when saw"),
        (5, 6, "they"),
        (7, 10, "who were desirous"),
        (11, 14, "that he become"),
        (15, 18, "their governor"),
        (19, 22, "he was condemned"),
        (23, 25, "to death,"),
        (26, 27, "therefore"),
        (28, 31, "they were angry,"),
        (32, 33, "and behold,"),
        (34, 37, "they sent"),
        (38, 39, "one"),
        (40, 43, "named Kishkumen,"),
        (44, 48, "even to the judgment-seat of"),
        (49, 49, "Pahoran,"),
        (50, 51, "and slew"),
        (52, 52, "Pahoran"),
        (53, 56, "as he sat"),
        (57, 59, "upon"),
        (60, 61, "the judgment-seat."),
    ],
    10: [
        (0, 4, "And he was pursued"),
        (5, 7, "by the servants of"),
        (8, 8, "Pahoran;"),
        (9, 10, "but behold,"),
        (11, 13, "was so swift"),
        (14, 16, "the flight of"),
        (17, 17, "Kishkumen,"),
        (18, 21, "that could not"),
        (22, 24, "any man"),
        (25, 28, "overtake him."),
    ],
    11: [
        (0, 5, "And he went"),
        (6, 8, "unto those"),
        (9, 13, "who sent"),
        (14, 15, "him,"),
        (16, 20, "and they all made"),
        (21, 22, "a covenant,"),
        (23, 23, "yea,"),
        (24, 27, "they swore by"),
        (28, 32, "Him who made them"),
        (33, 36, "who endures forever,"),
        (37, 42, "they would not tell"),
        (43, 45, "anyone"),
        (46, 47, "that Kishkumen"),
        (48, 49, "had slain"),
        (50, 50, "Pahoran."),
    ],
    12: [
        (0, 1, "Therefore,"),
        (2, 4, "was not known"),
        (5, 5, "Kishkumen"),
        (6, 8, "among"),
        (9, 11, "the people of Nephi,"),
        (12, 12, "for"),
        (13, 17, "he was disguised"),
        (18, 20, "at the time"),
        (21, 24, "he slew"),
        (25, 25, "Pahoran."),
        (26, 28, "And Kishkumen"),
        (29, 31, "and his band,"),
        (32, 35, "who made"),
        (36, 37, "the covenant"),
        (38, 40, "with him,"),
        (41, 43, "they mingled"),
        (44, 46, "themselves"),
        (47, 49, "among"),
        (50, 50, "the people,"),
        (51, 53, "in a way"),
        (54, 59, "that could not be found"),
        (60, 62, "all of them;"),
        (63, 69, "but many of them"),
        (70, 71, "who were found"),
        (72, 73, "were condemned"),
        (74, 76, "to death."),
    ],
    13: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 5, "was appointed"),
        (6, 6, "Pacumeni,"),
        (7, 9, "according to"),
        (10, 12, "the voice of"),
        (13, 14, "the people,"),
        (15, 17, "to become"),
        (18, 20, "a chief judge"),
        (21, 23, "and a governor"),
        (24, 26, "over"),
        (27, 28, "the people,"),
        (29, 32, "to reign in place"),
        (33, 36, "of his brother"),
        (37, 37, "Pahoran;"),
        (38, 41, "and it accorded with"),
        (42, 43, "his succession"),
        (44, 47, "and his right."),
        (48, 52, "And all this"),
        (53, 54, "was done"),
        (55, 60, "in the fortieth year"),
        (61, 64, "of the reign of"),
        (65, 65, "the judges;"),
        (66, 68, "and ended"),
        (69, 70, "the year."),
    ],
    14: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the forty"),
        (7, 11, "and first year"),
        (12, 15, "of the reign of"),
        (16, 16, "the judges,"),
        (17, 19, "gathered together"),
        (20, 22, "the Lamanites"),
        (23, 26, "an army of men"),
        (27, 29, "innumerable,"),
        (30, 33, "and they armed"),
        (34, 35, "them"),
        (36, 37, "with swords,"),
        (38, 39, "and with cimeters,"),
        (40, 41, "and with bows,"),
        (42, 43, "and with arrows,"),
        (44, 45, "and with head-plates,"),
        (46, 47, "and with breastplates,"),
        (48, 50, "and shields of"),
        (51, 54, "all diverse kinds."),
    ],
    15: [
        (0, 5, "And they came down again"),
        (6, 10, "that they might raise"),
        (11, 12, "the war"),
        (13, 14, "against"),
        (15, 17, "the Nephites."),
        (18, 20, "And were led"),
        (21, 22, "they"),
        (23, 25, "by a man"),
        (26, 29, "named Coriantumr;"),
        (30, 34, "and he was one"),
        (35, 38, "descended from"),
        (39, 39, "Zarahemla;"),
        (40, 44, "and he was one"),
        (45, 46, "who dissented"),
        (47, 49, "from among"),
        (50, 51, "the Nephites;"),
        (52, 57, "and he was a man"),
        (58, 60, "of great stature"),
        (61, 63, "and might."),
    ],
    16: [
        (0, 1, "Therefore,"),
        (2, 5, "the king of"),
        (6, 7, "the Lamanites,"),
        (8, 10, "whose name"),
        (11, 12, "was Tubaloth,"),
        (13, 18, "who was the son of"),
        (19, 19, "Ammoron,"),
        (20, 21, "supposed"),
        (22, 23, "that Coriantumr,"),
        (24, 26, "because he was"),
        (27, 30, "a mighty man,"),
        (31, 33, "could"),
        (34, 37, "he stand forth"),
        (38, 39, "against"),
        (40, 42, "the Nephites,"),
        (43, 45, "with his strength"),
        (46, 50, "and also with his great wisdom,"),
        (51, 53, "insomuch that"),
        (54, 57, "he would gain"),
        (58, 59, "the power"),
        (60, 63, "over the Nephite people"),
        (64, 67, "by the sending of"),
        (68, 69, "him—"),
    ],
    17: [
        (0, 1, "Therefore"),
        (2, 5, "he stirred up"),
        (6, 7, "them"),
        (8, 10, "to anger,"),
        (11, 15, "and he gathered together"),
        (16, 17, "his armies,"),
        (18, 21, "and he appointed"),
        (22, 22, "Coriantumr"),
        (23, 25, "to be"),
        (26, 28, "their leader,"),
        (29, 32, "and he commanded"),
        (33, 36, "that they march down"),
        (37, 38, "below"),
        (39, 42, "to the land of"),
        (43, 43, "Zarahemla"),
        (44, 46, "to war against"),
        (47, 50, "the Nephite people."),
    ],
    18: [
        (0, 2, "And it came to pass"),
        (3, 4, "because of"),
        (5, 7, "many contentions"),
        (8, 11, "and many difficulties"),
        (12, 14, "that were"),
        (15, 17, "in the government,"),
        (18, 22, "they did not set"),
        (23, 24, "enough"),
        (25, 26, "guards"),
        (27, 30, "in the land of"),
        (31, 31, "Zarahemla;"),
        (32, 32, "for"),
        (33, 35, "they supposed"),
        (36, 37, "were afraid"),
        (38, 39, "the Lamanites"),
        (40, 42, "to come"),
        (43, 46, "into the midst of"),
        (47, 49, "their lands"),
        (50, 51, "to attack"),
        (52, 55, "that great city of"),
        (56, 56, "Zarahemla."),
    ],
    19: [
        (0, 0, "But"),
        (1, 3, "it came to pass that"),
        (4, 5, "marched"),
        (6, 6, "Coriantumr"),
        (7, 9, "at the head of"),
        (10, 12, "his numerous army,"),
        (13, 15, "and came"),
        (16, 18, "upon"),
        (19, 20, "the people of"),
        (21, 22, "the city,"),
        (23, 27, "and so exceedingly swift was"),
        (28, 30, "their march"),
        (31, 34, "there was no time"),
        (35, 37, "for the Nephites"),
        (38, 41, "to gather together"),
        (42, 44, "their armies."),
    ],
    20: [
        (0, 1, "Therefore"),
        (2, 3, "struck down"),
        (4, 5, "Coriantumr"),
        (6, 9, "the gate guard of"),
        (10, 11, "the city,"),
        (12, 14, "and marched"),
        (15, 16, "together with"),
        (17, 19, "his whole army"),
        (20, 22, "into"),
        (23, 24, "the city,"),
        (25, 28, "and they slew"),
        (29, 30, "all people"),
        (31, 35, "who resisted"),
        (36, 39, "them,"),
        (40, 44, "insomuch that"),
        (45, 46, "they took"),
        (47, 49, "the whole city."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 5, "Pacumeni,"),
        (6, 10, "who was the chief judge,"),
        (11, 12, "fled"),
        (13, 15, "before"),
        (16, 16, "Coriantumr,"),
        (17, 20, "even unto"),
        (21, 22, "the walls of"),
        (23, 24, "the city."),
        (25, 28, "And it came to pass that"),
        (29, 31, "he was struck"),
        (32, 33, "by Coriantumr"),
        (34, 36, "against the wall,"),
        (37, 40, "insomuch that"),
        (41, 43, "he died."),
        (44, 46, "And thus"),
        (47, 48, "ended"),
        (49, 51, "the days of"),
        (52, 52, "Pacumeni."),
    ],
    22: [
        (0, 2, "And now,"),
        (3, 5, "when saw"),
        (6, 6, "Coriantumr"),
        (7, 9, "he possessed"),
        (10, 12, "the city of"),
        (13, 13, "Zarahemla,"),
        (14, 16, "and saw"),
        (17, 18, "had fled"),
        (19, 20, "the Nephites"),
        (21, 24, "before them,"),
        (25, 27, "and were slain,"),
        (28, 29, "and were taken,"),
        (30, 32, "and were cast"),
        (33, 35, "into prison,"),
        (36, 39, "and he had gained"),
        (40, 45, "the strongest stronghold"),
        (46, 49, "in all the land,"),
        (50, 51, "was emboldened"),
        (52, 53, "his heart"),
        (54, 57, "insomuch that"),
        (58, 62, "he was about to go"),
        (63, 65, "against"),
        (66, 68, "all the land."),
    ],
    23: [
        (0, 2, "And now"),
        (3, 8, "he did not stay"),
        (9, 12, "in the land of"),
        (13, 13, "Zarahemla,"),
        (14, 19, "but he marched forth"),
        (20, 21, "together with"),
        (22, 24, "a large army,"),
        (25, 29, "even toward"),
        (30, 32, "the city of"),
        (33, 33, "Bountiful;"),
        (34, 35, "because of"),
        (36, 38, "his eager desire"),
        (39, 41, "to go forth"),
        (42, 44, "and clear"),
        (45, 46, "his way"),
        (47, 49, "with the sword,"),
        (50, 53, "that he may"),
        (54, 55, "he obtain"),
        (56, 60, "the northern parts of"),
        (61, 62, "the land."),
    ],
    24: [
        (0, 0, "And,"),
        (1, 4, "supposing that"),
        (5, 9, "their greatest strength"),
        (10, 14, "was in the center of"),
        (15, 16, "the land,"),
        (17, 18, "therefore"),
        (19, 23, "he marched forth,"),
        (24, 27, "without giving"),
        (28, 31, "them"),
        (32, 33, "time"),
        (34, 38, "they gather together"),
        (39, 41, "themselves"),
        (42, 43, "except"),
        (44, 47, "in small groups;"),
        (48, 52, "and in this manner"),
        (53, 55, "attacked"),
        (56, 57, "them"),
        (58, 60, "and struck down"),
        (61, 62, "them"),
        (63, 65, "to the earth."),
    ],
    25: [
        (0, 1, "But behold,"),
        (2, 5, "this march of"),
        (6, 6, "Coriantumr"),
        (7, 10, "through"),
        (11, 13, "the middle of"),
        (14, 15, "the land"),
        (16, 19, "gave"),
        (20, 21, "to Moronihah"),
        (22, 26, "a great advantage"),
        (27, 29, "over"),
        (30, 31, "them,"),
        (32, 34, "notwithstanding"),
        (35, 38, "the great number of"),
        (39, 40, "the Nephites"),
        (41, 44, "who were slain."),
    ],
    26: [
        (0, 1, "For behold,"),
        (2, 3, "supposed"),
        (4, 4, "Moronihah"),
        (5, 6, "were afraid"),
        (7, 8, "the Lamanites"),
        (9, 11, "to come"),
        (12, 15, "into the center of"),
        (16, 17, "the land,"),
        (18, 18, "but"),
        (19, 23, "they would attack"),
        (24, 24, "the cities"),
        (25, 29, "that lie round about"),
        (30, 31, "in the borders"),
        (32, 34, "as"),
        (35, 37, "they had done"),
        (38, 41, "up to"),
        (42, 44, "the present time;"),
        (45, 46, "therefore"),
        (47, 49, "commanded"),
        (50, 51, "Moronihah"),
        (52, 53, "that be set"),
        (54, 57, "their strong armies"),
        (58, 59, "to keep"),
        (60, 60, "the parts"),
        (61, 63, "that lie near"),
        (64, 65, "the borders."),
    ],
    27: [
        (0, 1, "But behold,"),
        (2, 4, "were not afraid"),
        (5, 6, "the Lamanites"),
        (7, 9, "according to"),
        (10, 11, "his desire,"),
        (12, 16, "but they came"),
        (17, 20, "into the center of"),
        (21, 22, "the land,"),
        (23, 26, "and they took"),
        (27, 28, "the capital,"),
        (29, 33, "which was the city of"),
        (34, 34, "Zarahemla,"),
        (35, 37, "and were marching"),
        (38, 41, "through"),
        (42, 46, "the most important parts of"),
        (47, 48, "the land,"),
        (49, 50, "and slaying"),
        (51, 51, "the people"),
        (52, 55, "with a great slaughter,"),
        (56, 58, "including"),
        (59, 59, "men,"),
        (60, 61, "women,"),
        (62, 63, "and children,"),
        (64, 69, "and they took for themselves"),
        (70, 73, "many cities"),
        (74, 77, "and many of"),
        (78, 79, "strongholds."),
    ],
    28: [
        (0, 3, "But when discovered"),
        (4, 5, "Moronihah"),
        (6, 7, "this thing,"),
        (8, 13, "he quickly sent"),
        (14, 14, "Lehi"),
        (15, 17, "with an army"),
        (18, 20, "round about"),
        (21, 23, "to stop"),
        (24, 25, "them"),
        (26, 31, "before they arrived"),
        (32, 35, "to the land of"),
        (36, 36, "Bountiful."),
    ],
    29: [
        (0, 5, "And thus he did;"),
        (6, 10, "and he stopped"),
        (11, 12, "them"),
        (13, 18, "before they arrived"),
        (19, 22, "at the land of"),
        (23, 23, "Bountiful,"),
        (24, 28, "and fought with them,"),
        (29, 31, "insomuch that"),
        (32, 33, "began to"),
        (34, 38, "they retreat backward"),
        (39, 40, "toward"),
        (41, 43, "the land of"),
        (44, 44, "Zarahemla."),
    ],
    30: [
        (0, 3, "And it came to pass that"),
        (4, 5, "stopped"),
        (6, 7, "them"),
        (8, 9, "Moronihah"),
        (10, 15, "in their retreat,"),
        (16, 21, "and fought with them,"),
        (22, 24, "insomuch that"),
        (25, 26, "it became"),
        (27, 30, "an exceedingly bloody battle;"),
        (31, 31, "yea,"),
        (32, 33, "many"),
        (34, 35, "were slain,"),
        (36, 38, "and from"),
        (39, 40, "the number of"),
        (41, 44, "those slain"),
        (45, 49, "was also found"),
        (50, 50, "Coriantumr."),
    ],
    31: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 7, "could not"),
        (8, 8, "retreat"),
        (9, 10, "the Lamanites"),
        (11, 14, "in any direction,"),
        (15, 16, "neither"),
        (17, 21, "on the north side,"),
        (22, 23, "nor"),
        (24, 28, "on the south side,"),
        (29, 30, "nor"),
        (31, 35, "on the east side,"),
        (36, 37, "nor"),
        (38, 42, "on the west side,"),
        (43, 43, "for"),
        (44, 47, "they were surrounded"),
        (48, 50, "on every side"),
        (51, 53, "by the Nephites."),
    ],
    32: [
        (0, 2, "And thus"),
        (3, 5, "had cast"),
        (6, 7, "Coriantumr"),
        (8, 9, "the Lamanites"),
        (10, 13, "into the midst of"),
        (14, 15, "the Nephites,"),
        (16, 18, "insomuch that"),
        (19, 22, "they were caught"),
        (23, 26, "in the power of"),
        (27, 28, "the Nephites,"),
        (29, 33, "and he himself"),
        (34, 35, "was slain,"),
        (36, 39, "and gave up"),
        (40, 42, "the Lamanites"),
        (43, 45, "themselves"),
        (46, 48, "into the hands of"),
        (49, 50, "the Nephites."),
    ],
    33: [
        (0, 3, "And it came to pass that"),
        (4, 5, "regained"),
        (6, 7, "Moronihah"),
        (8, 10, "the city of"),
        (11, 11, "Zarahemla,"),
        (12, 15, "and he commanded"),
        (16, 18, "that the Lamanites"),
        (19, 23, "who had been taken prisoners"),
        (24, 26, "should"),
        (27, 29, "go out"),
        (30, 32, "out of the land"),
        (33, 35, "in peace."),
    ],
    34: [
        (0, 2, "And thus"),
        (3, 4, "ended"),
        (5, 8, "the fortieth"),
        (9, 13, "and first year"),
        (14, 17, "of the reign of"),
        (18, 18, "the judges."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
