"""Hand-curated TAM-phrase gloss overrides for Iakopo 7 — Sherem the anti-Christ / Jacob's farewell."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "jacob"
CHAPTER_NUM = 7
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 6, "after passed"),
        (7, 8, "some years,"),
        (9, 11, "it came to pass"),
        (12, 14, "came a man"),
        (15, 18, "in the midst of the people"),
        (19, 21, "of Nephi,"),
        (22, 24, "his name was"),
        (25, 26, "Sherem."),
    ],
    2: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 6, "began to preach"),
        (7, 8, "he"),
        (9, 13, "among the people,"),
        (14, 16, "and said"),
        (17, 20, "unto them,"),
        (21, 24, "there should not be"),
        (25, 27, "any"),
        (28, 29, "a Christ."),
        (30, 30, "And"),
        (31, 33, "preached"),
        (34, 35, "by him"),
        (36, 38, "many things"),
        (39, 40, "which flattered"),
        (41, 42, "the people;"),
        (43, 43, "and"),
        (44, 47, "did this by him"),
        (48, 49, "this thing"),
        (50, 53, "that may"),
        (54, 56, "he overthrow thereto"),
        (57, 61, "the doctrine of Christ."),
    ],
    3: [
        (0, 0, "And"),
        (1, 4, "labored he"),
        (5, 7, "with diligence"),
        (8, 10, "that may"),
        (11, 17, "he lead away the hearts"),
        (18, 19, "of the people,"),
        (20, 22, "did lead"),
        (23, 24, "by him"),
        (25, 26, "the hearts"),
        (27, 27, "of people"),
        (28, 29, "many;"),
        (30, 30, "and"),
        (31, 34, "knew by him,"),
        (35, 38, "that I, Jacob,"),
        (39, 41, "I had faith"),
        (42, 43, "in Christ"),
        (44, 45, "the one"),
        (46, 50, "who should come,"),
        (51, 55, "thereto sought"),
        (56, 57, "by him"),
        (58, 60, "an opportunity"),
        (61, 65, "that may come"),
        (66, 67, "he"),
        (68, 70, "unto me."),
    ],
    4: [
        (0, 0, "And"),
        (1, 4, "was learned he,"),
        (5, 10, "wherefore he had"),
        (11, 13, "a perfect knowledge"),
        (14, 16, "of the language"),
        (17, 19, "of the people;"),
        (20, 23, "wherefore,"),
        (24, 27, "he had"),
        (28, 29, "the skill"),
        (30, 32, "to use thereto"),
        (33, 35, "much flattery,"),
        (36, 39, "and great power"),
        (40, 43, "of speech,"),
        (44, 46, "according to"),
        (47, 48, "the power"),
        (49, 51, "of the devil."),
    ],
    5: [
        (0, 0, "And"),
        (1, 4, "hoped he"),
        (5, 8, "to shake away"),
        (9, 11, "me from the faith,"),
        (12, 13, "notwithstanding"),
        (14, 17, "the many revelations"),
        (18, 23, "and the many things I had seen"),
        (24, 28, "thereto concerning"),
        (29, 33, "these things;"),
        (34, 34, "for"),
        (35, 37, "I had seen"),
        (38, 41, "truly indeed angels,"),
        (42, 42, "and"),
        (43, 45, "they ministered"),
        (46, 49, "unto me."),
        (50, 52, "And again,"),
        (53, 55, "I had heard"),
        (56, 58, "the voice"),
        (59, 61, "of the Lord"),
        (62, 64, "speaking"),
        (65, 67, "unto me"),
        (68, 71, "in very truth,"),
        (72, 77, "from time to time;"),
        (78, 81, "wherefore,"),
        (82, 85, "could not"),
        (86, 89, "be shaken I."),
    ],
    6: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 5, "came"),
        (6, 9, "he unto me,"),
        (10, 11, "and on"),
        (12, 13, "this manner"),
        (14, 17, "did he speak"),
        (18, 22, "unto me,"),
        (23, 24, "saying:"),
        (25, 27, "Brother"),
        (28, 28, "Jacob,"),
        (29, 31, "I have sought"),
        (32, 35, "verily an opportunity"),
        (36, 38, "that may"),
        (39, 42, "I speak"),
        (43, 45, "unto thee;"),
        (46, 46, "for"),
        (47, 53, "I have heard and known"),
        (54, 54, "also"),
        (55, 60, "that thou hast traveled much,"),
        (61, 63, "preaching"),
        (64, 67, "that which thou callest"),
        (68, 71, "the gospel,"),
        (72, 78, "or the doctrine of Christ."),
    ],
    7: [
        (0, 0, "And"),
        (1, 5, "ye have led away"),
        (6, 9, "many of this people"),
        (10, 13, "that they pervert thereto"),
        (14, 19, "the right way of God,"),
        (20, 23, "and keep not"),
        (24, 27, "the law of Moses"),
        (28, 32, "which is the right way;"),
        (33, 33, "and"),
        (34, 38, "convert the law of Moses"),
        (39, 42, "into the worship"),
        (43, 45, "of a being"),
        (46, 49, "which ye say"),
        (50, 54, "shall come"),
        (55, 61, "many hundreds of years hence."),
        (62, 65, "And now behold,"),
        (66, 69, "I, behold,"),
        (70, 73, "I, Sherem,"),
        (74, 77, "declare unto thee"),
        (78, 80, "that"),
        (81, 87, "this is blasphemy against God;"),
        (88, 88, "for"),
        (89, 93, "no man knoweth"),
        (94, 99, "of such things;"),
        (100, 107, "for he cannot tell"),
        (108, 115, "of things to come."),
        (116, 116, "And"),
        (117, 121, "thus contended Sherem"),
        (122, 125, "against me thereto"),
        (126, 132, "did he contend against me."),
    ],
    8: [
        (0, 1, "But behold,"),
        (2, 4, "poured out"),
        (5, 9, "the Lord God"),
        (10, 11, "his Spirit"),
        (12, 16, "into my soul,"),
        (17, 19, "it came to pass"),
        (20, 22, "I did confound"),
        (23, 24, "him"),
        (25, 28, "in all his words."),
    ],
    9: [
        (0, 0, "And"),
        (1, 4, "I said"),
        (5, 7, "unto him:"),
        (8, 11, "Deniest thou"),
        (12, 13, "the Christ"),
        (14, 15, "who"),
        (16, 20, "shall come?"),
        (21, 21, "And"),
        (22, 25, "said he:"),
        (26, 26, "If"),
        (27, 32, "there should be a Christ,"),
        (33, 33, "a Christ,"),
        (34, 38, "I would not deny"),
        (39, 40, "him;"),
        (41, 41, "but"),
        (42, 44, "I know"),
        (45, 48, "there is no Christ,"),
        (49, 52, "neither hath been,"),
        (53, 58, "nor ever will be."),
    ],
    10: [
        (0, 0, "And"),
        (1, 4, "I said"),
        (5, 7, "unto him:"),
        (8, 10, "Believest thou"),
        (11, 13, "the scriptures?"),
        (14, 14, "And"),
        (15, 17, "said he:"),
        (18, 19, "Yea."),
        (20, 20, "Yea."),
    ],
    11: [
        (0, 0, "And"),
        (1, 4, "I said"),
        (5, 7, "unto him:"),
        (8, 10, "Then meaneth"),
        (11, 11, "thou"),
        (12, 17, "thou understandest them not;"),
        (18, 18, "for"),
        (19, 23, "they truly testify"),
        (24, 27, "of Christ."),
        (28, 28, "Behold,"),
        (29, 32, "I say"),
        (33, 35, "unto thee"),
        (36, 39, "none of the prophets"),
        (40, 43, "have written"),
        (44, 44, "or"),
        (45, 46, "have prophesied,"),
        (47, 48, "save thereto"),
        (49, 52, "they have spoken"),
        (53, 54, "concerning"),
        (55, 57, "this Christ."),
    ],
    12: [
        (0, 0, "And"),
        (1, 4, "is not all"),
        (5, 5, "this—"),
        (6, 8, "was shown"),
        (9, 11, "unto me,"),
        (12, 12, "for"),
        (13, 17, "I have heard and seen;"),
        (18, 18, "and"),
        (19, 21, "was shown also"),
        (22, 25, "unto me"),
        (26, 32, "by the power of the Holy Spirit;"),
        (33, 36, "wherefore,"),
        (37, 40, "I know thereto"),
        (41, 41, "if"),
        (42, 44, "there be not made"),
        (45, 46, "an atonement"),
        (47, 49, "shall be lost"),
        (50, 52, "all mankind."),
    ],
    13: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 7, "said he"),
        (8, 10, "unto me:"),
        (11, 12, "Show"),
        (13, 15, "unto me"),
        (16, 17, "a sign"),
        (18, 20, "by way of"),
        (21, 23, "this power"),
        (24, 27, "of the Holy Spirit,"),
        (28, 28, "wherein"),
        (29, 32, "thou knowest"),
        (33, 36, "these many things."),
    ],
    14: [
        (0, 0, "And"),
        (1, 4, "I said"),
        (5, 7, "unto him:"),
        (8, 9, "Who am"),
        (10, 14, "I that I should tempt thereto"),
        (15, 17, "the God"),
        (18, 23, "to show unto thee"),
        (24, 25, "a sign"),
        (26, 27, "in the thing"),
        (28, 30, "which thou knowest"),
        (31, 32, "are true?"),
        (33, 38, "Yet wilt thou deny,"),
        (39, 41, "because thou art"),
        (42, 46, "of the devil."),
        (47, 50, "Nevertheless,"),
        (51, 55, "not done my will;"),
        (56, 56, "but"),
        (57, 58, "if"),
        (59, 63, "shalt thou be smitten by God,"),
        (64, 68, "let that be a sign"),
        (69, 71, "unto thee"),
        (72, 75, "that thou shalt know thereto"),
        (76, 81, "he hath thereto the power,"),
        (82, 88, "both in heaven and earth;"),
        (89, 91, "and also,"),
        (92, 96, "shall come Christ."),
        (97, 97, "And"),
        (98, 101, "O Lord,"),
        (102, 105, "be thy will done,"),
        (106, 110, "and not my will."),
    ],
    15: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 8, "after I had spoken"),
        (9, 12, "these words,"),
        (13, 14, "I, Jacob,"),
        (15, 17, "came down"),
        (18, 20, "upon him"),
        (21, 25, "the power of the Lord,"),
        (26, 26, "and"),
        (27, 29, "it came to pass"),
        (30, 32, "he fell"),
        (33, 37, "to the ground."),
        (38, 38, "And"),
        (39, 41, "it came to pass"),
        (42, 44, "was nourished he"),
        (45, 47, "for the space"),
        (48, 51, "of many days."),
    ],
    16: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 7, "said he"),
        (8, 10, "unto the people:"),
        (11, 13, "Gather together"),
        (14, 18, "on the morrow,"),
        (19, 24, "for I shall die;"),
        (25, 28, "wherefore,"),
        (29, 33, "I desire to speak"),
        (34, 36, "unto the people"),
        (37, 41, "before I die."),
    ],
    17: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 9, "did gather together the multitude"),
        (10, 12, "on the morrow;"),
        (13, 15, "and"),
        (16, 22, "did speak plainly he"),
        (23, 26, "unto them,"),
        (27, 29, "and denied"),
        (30, 33, "the things which he had taught"),
        (34, 37, "unto them,"),
        (38, 39, "and confessed"),
        (40, 42, "the Christ,"),
        (43, 50, "and the power of the Holy Spirit,"),
        (51, 54, "and the ministering of angels."),
    ],
    18: [
        (0, 0, "And"),
        (1, 4, "told plainly thereto"),
        (5, 6, "by him"),
        (7, 10, "unto them,"),
        (11, 14, "he had been deceived"),
        (15, 20, "by the power of the devil."),
        (21, 21, "And"),
        (22, 26, "spake he"),
        (27, 30, "concerning hell,"),
        (31, 33, "and concerning"),
        (34, 36, "eternity,"),
        (37, 39, "and concerning"),
        (40, 42, "the punishment"),
        (43, 44, "endless."),
    ],
    19: [
        (0, 0, "And"),
        (1, 5, "said he:"),
        (6, 8, "I fear"),
        (9, 13, "lest I have committed"),
        (14, 16, "the unpardonable sin,"),
        (17, 19, "for I have"),
        (20, 23, "lied unto God;"),
        (24, 24, "for"),
        (25, 27, "I denied"),
        (28, 29, "the Christ,"),
        (30, 32, "and said"),
        (33, 36, "I believed"),
        (37, 39, "in the scriptures;"),
        (40, 40, "and"),
        (41, 46, "they truly testify thereto"),
        (47, 51, "of him."),
        (52, 52, "And"),
        (53, 57, "because thus"),
        (58, 61, "I have lied unto God"),
        (62, 65, "I fear greatly"),
        (66, 67, "lest"),
        (68, 73, "be awful the my state;"),
        (74, 74, "but"),
        (75, 77, "I confess"),
        (78, 81, "unto God."),
    ],
    20: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 8, "after he had said"),
        (9, 13, "these words"),
        (14, 17, "could not"),
        (18, 22, "again speak he,"),
        (23, 24, "and"),
        (25, 27, "he gave up the ghost."),
    ],
    21: [
        (0, 0, "And"),
        (1, 3, "when had witnessed"),
        (4, 8, "by the multitude of the people"),
        (9, 13, "had he spoken"),
        (14, 16, "these things"),
        (17, 23, "as he was about to give"),
        (24, 27, "the breath,"),
        (28, 30, "they were astonished"),
        (31, 31, "greatly;"),
        (32, 34, "it came to pass"),
        (35, 37, "came down"),
        (38, 42, "the power of God"),
        (43, 47, "upon them,"),
        (48, 49, "and"),
        (50, 51, "overcome were"),
        (52, 53, "they"),
        (54, 57, "it came to pass"),
    
    ],
    22: [
        (0, 1, "Now,"),
        (2, 5, "was good"),
        (6, 8, "this thing"),
        (9, 11, "unto me,"),
        (12, 14, "I, Jacob,"),
        (15, 18, "for I had requested"),
        (19, 20, "it of"),
        (21, 23, "my Father"),
        (24, 24, "who is"),
        (25, 27, "in heaven;"),
        (28, 31, "for he had heard"),
        (32, 33, "my cry"),
        (34, 35, "and answered"),
        (36, 38, "my prayer."),
    ],
    23: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 5, "returned"),
        (6, 7, "the peace"),
        (8, 10, "and the love"),
        (11, 13, "of the God"),
        (14, 18, "in the midst of the people;"),
        (19, 19, "and"),
        (20, 22, "they did search"),
        (23, 25, "the scriptures,"),
        (26, 29, "and hearkened no more"),
        (30, 33, "to the words of"),
        (34, 35, "this man"),
    
    ],
    24: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 8, "were devised many means"),
        (9, 15, "to reclaim and restore"),
        (16, 22, "the Lamanites to the knowledge of the truth;"),
        (23, 24, "but"),
        (25, 29, "it was all in vain,"),
        (30, 31, "for"),
        (32, 35, "they delighted"),
        (36, 38, "in wars"),
        (39, 39, "and bloodshed,"),
        (40, 40, "and"),
        (41, 48, "they had eternal hatred"),
        (49, 52, "against us,"),
        (53, 56, "their brethren."),
        (57, 57, "And"),
        (58, 64, "they sought by the power of their arms"),
        (65, 69, "of weapons of war"),
        (70, 75, "to destroy us continually."),
    ],
    25: [
        (0, 3, "Wherefore,"),
        (4, 8, "fortified strongly"),
        (9, 11, "the people of Nephi"),
        (12, 18, "against them"),
        (19, 19, "with"),
        (20, 24, "their weapons of war,"),
        (25, 29, "and with all their might,"),
        (30, 35, "and with their trust in the God"),
        (36, 38, "and the rock"),
        (39, 42, "of their salvation;"),
        (43, 46, "wherefore,"),
        (47, 52, "did prevail thereto they"),
        (53, 56, "over their enemies"),
        (57, 63, "until this present time."),
    ],
    26: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 6, "that I,"),
        (7, 8, "Jacob,"),
        (9, 12, "had begun to be old;"),
        (13, 13, "and"),
        (14, 16, "because of"),
        (17, 20, "the record of this people"),
        (21, 27, "being kept on the other plates of Nephi,"),
        (28, 31, "wherefore,"),
        (32, 36, "I make an end"),
        (37, 37, "thereto"),
        (38, 38, "this record,"),
        (39, 40, "and declare"),
        (41, 43, "that I have written"),
        (44, 53, "according to the best of my knowledge,"),
        (54, 56, "saying"),
        (57, 57, "thereto,"),
        (58, 60, "passed away"),
        (61, 67, "the time from us,"),
        (68, 68, "and"),
        (69, 71, "passed away also"),
        (72, 75, "our lives"),
        (76, 80, "like as a dream,"),
        (81, 89, "we being a lonesome and a solemn people,"),
        (90, 93, "wanderers,"),
        (94, 98, "cast out from Jerusalem,"),
        (99, 102, "born in tribulation,"),
        (103, 105, "in a wilderness,"),
        (106, 112, "and hated by our brethren,"),
        (113, 118, "which caused wars and contentions;"),
        (119, 122, "wherefore,"),
        (123, 129, "we did mourn out our"),
        (130, 133, "days."),
    ],
    27: [
        (0, 0, "And"),
        (1, 4, "I, Jacob,"),
        (5, 7, "saw thereto"),
        (8, 12, "soon must I go down"),
        (13, 15, "to my grave;"),
        (16, 18, "wherefore,"),
        (19, 27, "I said unto my son Enos:"),
        (28, 32, "Take thou these plates."),
        (33, 37, "Ia e ave nei papatusi."),
        (38, 38, "And"),
        (39, 42, "I told"),
        (43, 49, "unto him the things which had commanded thereto me"),
        (50, 55, "by my brother Nephi,"),
        (56, 56, "and"),
        (57, 61, "he promised"),
        (62, 65, "obedience to the commandments."),
        (66, 66, "And"),
        (67, 75, "I make an end of my writing"),
        (76, 82, "upon these plates,"),
        (83, 92, "which writing has been small;"),
        (93, 93, "and"),
        (94, 95, "to"),
        (96, 97, "the reader"),
        (98, 99, "thereto,"),
        (100, 102, "I bid farewell,"),
        (103, 109, "hoping that may many of my brethren"),
        (110, 112, "read"),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
