"""Hand-curated TAM-phrase gloss overrides for Mosaea 7 — Ammon's expedition to Lehi-Nephi and King Limhi's address.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
pronouns absorbed only when their token is IN the span (rule 2), NP/PP atoms
split (rule 3), `mai`-as-"from" (rule 7), no anaphoric-`ai` fillers when a
PP/object follows (rule 1), `mafai ona`/`ina ia`/`ina ua` bound (rules 13/15),
vocative `e`/`E …e` folded as "O X" (rule 12), directional "forth" dropped
(rule 12a). No pronoun/TAM word injected into a cell whose span lacks that
token; no content word repeats across adjacent cells (except authentic Samoan
doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah7.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 7
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now,"),
        (3, 4, "it came to pass"),
        (5, 7, "after"),
        (8, 9, "had obtained"),
        (10, 14, "king Mosiah"),
        (15, 16, "the peace"),
        (17, 19, "which continued"),
        (20, 22, "for the space"),
        (23, 26, "of three years,"),
        (27, 30, "he was desirous to know"),
        (31, 34, "concerning the people"),
        (35, 39, "who went up"),
        (40, 41, "to dwell"),
        (42, 44, "in the land"),
        (45, 46, "of Lehi-Nephi,"),
        (47, 50, "or in the city"),
        (51, 52, "of Lehi-Nephi;"),
        (53, 57, "for there was no tidings"),
        (58, 59, "which had received"),
        (60, 62, "his people"),
        (63, 67, "from them"),
        (68, 70, "from the time"),
        (71, 74, "they left"),
        (75, 78, "the land of Zarahemla;"),
        (79, 80, "therefore,"),
        (81, 84, "they wearied"),
        (85, 87, "him"),
        (88, 92, "with their teasings."),
    ],
    2: [
        (0, 2, "And it came to pass"),
        (3, 4, "that granted"),
        (5, 9, "king Mosiah"),
        (10, 14, "their strong men"),
        (15, 16, "sixteen"),
        (17, 19, "might go up"),
        (20, 24, "to the land of Lehi-Nephi,"),
        (25, 26, "to inquire"),
        (27, 29, "concerning"),
        (30, 32, "their brethren."),
    ],
    3: [
        (0, 2, "And it came to pass"),
        (3, 5, "that began"),
        (6, 8, "they to go up"),
        (9, 11, "on the day"),
        (12, 14, "following,"),
        (15, 17, "and was with"),
        (18, 20, "them"),
        (21, 23, "one man"),
        (24, 27, "named Ammon,"),
        (28, 29, "he is"),
        (30, 33, "a strong man"),
        (34, 38, "and mighty of body,"),
        (39, 43, "and a descendant"),
        (44, 46, "of Zarahemla;"),
        (47, 50, "and he also"),
        (51, 52, "was the leader"),
        (53, 56, "unto them."),
    ],
    4: [
        (0, 2, "And now,"),
        (3, 6, "they knew not"),
        (7, 8, "the course"),
        (9, 11, "which they should"),
        (12, 14, "travel"),
        (15, 17, "in the wilderness"),
        (18, 21, "to go up"),
        (22, 26, "to the land of Lehi-Nephi;"),
        (27, 28, "therefore"),
        (29, 32, "they wandered"),
        (33, 35, "in the wilderness"),
        (36, 39, "many days,"),
        (40, 44, "even forty days"),
        (45, 48, "did they wander."),
    ],
    5: [
        (0, 3, "And after"),
        (4, 7, "forty days"),
        (8, 10, "of their wandering,"),
        (11, 14, "they came"),
        (15, 17, "to a hill,"),
        (18, 20, "which is north"),
        (21, 25, "of the land of Shilom,"),
        (26, 28, "and there"),
        (29, 32, "they pitched"),
        (33, 35, "their tents."),
    ],
    6: [
        (0, 2, "And took"),
        (3, 4, "Ammon"),
        (5, 7, "of his brethren"),
        (8, 9, "three,"),
        (10, 14, "and their names"),
        (15, 16, "were Amaleki,"),
        (17, 17, "Helem,"),
        (18, 19, "and Hem,"),
        (20, 24, "and they went down"),
        (25, 27, "into the land"),
        (28, 29, "of Nephi."),
    ],
    7: [
        (0, 1, "And behold,"),
        (2, 4, "they met"),
        (5, 7, "with the king"),
        (8, 9, "of the people"),
        (10, 14, "who were"),
        (15, 19, "in the land of Nephi,"),
        (20, 23, "and in the land"),
        (24, 25, "of Shilom;"),
        (26, 30, "and they were surrounded"),
        (31, 32, "by the guard"),
        (33, 35, "of the king,"),
        (36, 39, "and were taken,"),
        (40, 41, "and were bound,"),
        (42, 43, "and were put"),
        (44, 46, "in prison."),
    ],
    8: [
        (0, 2, "And it came to pass"),
        (3, 6, "when for two days"),
        (7, 11, "they had been"),
        (12, 14, "in prison"),
        (15, 19, "they were again brought"),
        (20, 24, "before the king,"),
        (25, 27, "and were loosed"),
        (28, 30, "their bands;"),
        (31, 34, "and they stood"),
        (35, 39, "before the king,"),
        (40, 42, "and were permitted,"),
        (43, 46, "or rather commanded"),
        (47, 48, "them,"),
        (49, 52, "that they should answer"),
        (53, 54, "the questions"),
        (55, 61, "which he should ask"),
        (62, 65, "them."),
    ],
    9: [
        (0, 5, "And he said"),
        (6, 9, "unto them:"),
        (10, 10, "Behold,"),
        (11, 14, "I am Limhi,"),
        (15, 19, "the son of Noah,"),
        (20, 21, "he is"),
        (22, 26, "the son of Zeniff,"),
        (27, 30, "who came"),
        (31, 35, "from the land of Zarahemla"),
        (36, 40, "for his inheritance"),
        (41, 43, "this land,"),
        (44, 47, "which was the land"),
        (48, 51, "of their fathers,"),
        (52, 55, "who was appointed"),
        (56, 57, "to be"),
        (58, 60, "a king"),
        (61, 63, "by the voice"),
        (64, 66, "of the people."),
    ],
    10: [
        (0, 2, "And now,"),
        (3, 6, "I desire to know"),
        (7, 8, "the cause"),
        (9, 13, "whereby ye were so bold"),
        (14, 16, "as to come"),
        (17, 19, "near the walls"),
        (20, 22, "of the city,"),
        (23, 26, "when I myself,"),
        (27, 29, "I was with"),
        (30, 32, "my guard"),
        (33, 37, "outside the gate?"),
    ],
    11: [
        (0, 2, "And now,"),
        (3, 6, "this is the cause"),
        (7, 11, "that I have suffered"),
        (12, 14, "that ye be preserved,"),
        (15, 16, "that"),
        (17, 18, "might"),
        (19, 21, "I inquire of you,"),
        (22, 24, "or else,"),
        (25, 28, "I should have caused"),
        (29, 31, "that ye be slain"),
        (32, 34, "by my guards."),
        (35, 37, "Ye are permitted"),
        (38, 41, "to speak."),
    ],
    12: [
        (0, 2, "And now,"),
        (3, 6, "when saw"),
        (7, 7, "Ammon"),
        (8, 11, "that he was permitted"),
        (12, 14, "to speak,"),
        (15, 19, "he went"),
        (20, 22, "and bowed down"),
        (23, 25, "himself"),
        (26, 30, "before the king;"),
        (31, 38, "and when he rose again"),
        (39, 42, "he said:"),
        (43, 45, "O king,"),
        (46, 50, "I am very thankful"),
        (51, 55, "before God"),
        (56, 58, "this day"),
        (59, 63, "because I am yet alive,"),
        (64, 67, "and am permitted"),
        (68, 71, "to speak;"),
        (72, 72, "and"),
        (73, 77, "I will endeavor"),
        (78, 80, "to speak"),
        (81, 83, "with boldness."),
    ],
    13: [
        (0, 3, "For I am assured"),
        (4, 7, "that if thou hadst known"),
        (8, 8, "me"),
        (9, 13, "thou wouldst not have suffered"),
        (14, 16, "that I be bound"),
        (17, 19, "in these bands."),
        (20, 24, "For I am Ammon,"),
        (25, 27, "and I am"),
        (28, 31, "a descendant"),
        (32, 34, "of Zarahemla,"),
        (35, 38, "and I have come"),
        (39, 43, "from the land of Zarahemla"),
        (44, 45, "to inquire"),
        (46, 48, "concerning"),
        (49, 51, "our brethren,"),
        (52, 55, "whom brought"),
        (56, 57, "Zeniff"),
        (58, 60, "out of that land."),
    ],
    14: [
        (0, 2, "And now,"),
        (3, 4, "it came to pass"),
        (5, 8, "after had made an end"),
        (9, 10, "of hearing"),
        (11, 12, "Limhi"),
        (13, 16, "the words of Ammon,"),
        (17, 23, "he was exceedingly glad,"),
        (24, 26, "and said:"),
        (27, 28, "Now,"),
        (29, 31, "I know"),
        (32, 34, "of a surety"),
        (35, 38, "are yet alive"),
        (39, 40, "my brethren"),
        (41, 45, "who were"),
        (46, 50, "in the land of Zarahemla."),
        (51, 53, "And now,"),
        (54, 58, "I will rejoice;"),
        (59, 62, "and on the day"),
        (63, 64, "of tomorrow"),
        (65, 70, "I will cause that"),
        (71, 73, "rejoice also"),
        (74, 75, "my people."),
    ],
    15: [
        (0, 1, "For behold,"),
        (2, 6, "we are now in bondage"),
        (7, 9, "to the Lamanites,"),
        (10, 13, "and pay tribute"),
        (14, 15, "we"),
        (16, 18, "with a tax"),
        (19, 21, "which is grievous"),
        (22, 23, "to be borne."),
        (24, 27, "And now, behold,"),
        (28, 31, "will deliver"),
        (32, 33, "us"),
        (34, 37, "by our brethren"),
        (38, 41, "out of our bondage,"),
        (42, 45, "or out of the hands"),
        (46, 48, "of the Lamanites,"),
        (49, 53, "and we will become"),
        (54, 55, "we"),
        (56, 59, "their slaves;"),
        (60, 62, "for is better"),
        (63, 65, "our bondage"),
        (66, 69, "to the Nephites"),
        (70, 73, "than the paying"),
        (74, 75, "of tribute"),
        (76, 78, "to the king"),
        (79, 81, "of the Lamanites."),
    ],
    16: [
        (0, 2, "And now,"),
        (3, 4, "commanded"),
        (5, 9, "king Limhi"),
        (10, 11, "his guards"),
        (12, 14, "that no more"),
        (15, 18, "they bind"),
        (19, 19, "Ammon"),
        (20, 23, "nor his brethren,"),
        (24, 25, "but commanded"),
        (26, 29, "that they should go"),
        (30, 32, "to the hill"),
        (33, 38, "which was on the north"),
        (39, 40, "of Shilom,"),
        (41, 42, "and bring"),
        (43, 45, "their brethren"),
        (46, 48, "into the city,"),
        (49, 50, "that"),
        (51, 53, "might"),
        (54, 55, "they eat,"),
        (56, 57, "and drink,"),
        (58, 62, "and rest themselves"),
        (63, 64, "from the toils"),
        (65, 68, "of their journey;"),
        (69, 72, "for they had suffered"),
        (73, 76, "many things;"),
        (77, 79, "they had suffered"),
        (80, 83, "hunger,"),
        (84, 85, "thirst,"),
        (86, 88, "and fatigue."),
    ],
    17: [
        (0, 2, "And now"),
        (3, 4, "it came to pass"),
        (5, 7, "that sent"),
        (8, 12, "king Limhi"),
        (13, 15, "on the day"),
        (16, 18, "following,"),
        (19, 20, "a proclamation"),
        (21, 24, "among all his people,"),
        (25, 26, "that"),
        (27, 28, "might"),
        (29, 32, "they gather together"),
        (33, 35, "themselves"),
        (36, 38, "to the temple,"),
        (39, 40, "to hear"),
        (41, 42, "the words"),
        (43, 50, "which he should speak"),
        (51, 54, "unto them."),
    ],
    18: [
        (0, 2, "And it came to pass"),
        (3, 8, "when they had gathered together"),
        (9, 11, "themselves,"),
        (12, 16, "he spake"),
        (17, 20, "unto them"),
        (21, 23, "in this wise,"),
        (24, 25, "saying:"),
        (26, 28, "O ye,"),
        (29, 31, "my people,"),
        (32, 36, "lift up"),
        (37, 39, "your heads"),
        (40, 43, "and be comforted;"),
        (44, 45, "for behold,"),
        (46, 50, "the time is at hand,"),
        (51, 55, "or is not far,"),
        (56, 57, "the time"),
        (58, 61, "when we shall"),
        (62, 65, "no longer be"),
        (66, 68, "in the subjection"),
        (69, 72, "of our enemies,"),
        (73, 77, "notwithstanding the many"),
        (78, 81, "of our strugglings,"),
        (82, 85, "which were in vain;"),
        (86, 89, "yet I trust"),
        (90, 92, "there remaineth"),
        (93, 95, "an effectual struggle"),
        (96, 99, "to be made."),
    ],
    19: [
        (0, 1, "Therefore,"),
        (2, 5, "lift up"),
        (6, 8, "your heads,"),
        (9, 11, "and rejoice,"),
        (12, 14, "and put"),
        (15, 17, "your trust"),
        (18, 20, "in God,"),
        (21, 23, "in that God"),
        (24, 27, "who was"),
        (28, 29, "the God"),
        (30, 31, "of Abraham,"),
        (32, 33, "and Isaac,"),
        (34, 35, "and Jacob;"),
        (36, 40, "and also, that God,"),
        (41, 44, "who brought"),
        (45, 48, "the children of Israel"),
        (49, 53, "out of the land of Egypt,"),
        (54, 57, "and caused"),
        (58, 60, "that they should walk"),
        (61, 62, "through"),
        (63, 66, "the Red Sea"),
        (67, 69, "upon"),
        (70, 72, "the dry ground,"),
        (73, 76, "and fed them"),
        (77, 79, "with manna"),
        (80, 81, "that"),
        (82, 84, "they perish not"),
        (85, 87, "in the wilderness;"),
        (88, 90, "and many more"),
        (91, 93, "other things"),
        (94, 97, "did he do"),
        (98, 100, "for them."),
    ],
    20: [
        (0, 2, "And again,"),
        (3, 7, "that same God"),
        (8, 10, "hath brought"),
        (11, 13, "our fathers"),
        (14, 18, "out of the land of Jerusalem,"),
        (19, 21, "and hath kept"),
        (22, 23, "and preserved"),
        (24, 25, "his people"),
        (26, 28, "even unto"),
        (29, 32, "this time;"),
        (33, 34, "and behold,"),
        (35, 39, "because of our iniquities"),
        (40, 42, "and abominations"),
        (43, 47, "that he hath brought"),
        (48, 49, "us"),
        (50, 52, "into bondage."),
    ],
    21: [
        (0, 3, "And ye all"),
        (4, 5, "are witnesses"),
        (6, 8, "this day,"),
        (9, 10, "that Zeniff,"),
        (11, 14, "who was made"),
        (15, 16, "king"),
        (17, 19, "over this people,"),
        (20, 23, "because of his over-zeal"),
        (24, 28, "to obtain as his inheritance"),
        (29, 33, "the land of his fathers,"),
        (34, 35, "therefore"),
        (36, 40, "he was deceived"),
        (41, 43, "by the cunning"),
        (44, 46, "and the craftiness"),
        (47, 51, "of king Laman,"),
        (52, 55, "who deceived"),
        (56, 58, "him"),
        (59, 65, "after he had made"),
        (66, 68, "a treaty"),
        (69, 73, "with king Zeniff,"),
        (74, 78, "and after had ended"),
        (79, 81, "his yielding up"),
        (82, 84, "into his hands"),
        (85, 89, "the possession of a part"),
        (90, 92, "of the land,"),
        (93, 96, "or the city"),
        (97, 98, "of Lehi-Nephi,"),
        (99, 103, "and the city of Shilom;"),
        (104, 106, "and the land"),
        (107, 108, "round about—"),
    ],
    22: [
        (0, 4, "And he did"),
        (5, 7, "all these things,"),
        (8, 12, "for the sole purpose,"),
        (13, 16, "the bringing"),
        (17, 19, "of this people"),
        (20, 22, "into subjection"),
        (23, 27, "or into bondage."),
        (28, 29, "And behold,"),
        (30, 31, "we"),
        (32, 35, "at this time"),
        (36, 40, "do pay"),
        (41, 41, "tribute"),
        (42, 44, "to the king"),
        (45, 47, "of the Lamanites,"),
        (48, 50, "to the amount"),
        (51, 53, "of one half"),
        (54, 57, "of our corn,"),
        (58, 61, "and our barley,"),
        (62, 65, "and even"),
        (66, 68, "our grain"),
        (69, 72, "of every kind,"),
        (73, 77, "and one half"),
        (78, 79, "of the increase"),
        (80, 83, "of our flocks"),
        (84, 85, "and herds;"),
        (86, 89, "and even"),
        (90, 92, "of one half"),
        (93, 95, "of all things"),
        (96, 100, "which we have"),
        (101, 103, "or the things"),
        (104, 106, "which we possess"),
        (107, 108, "doth exact"),
        (109, 114, "the king of the Lamanites"),
        (115, 119, "of us,"),
        (120, 121, "or else,"),
        (122, 125, "our lives."),
    ],
    23: [
        (0, 2, "And now,"),
        (3, 7, "is it not grievous"),
        (8, 10, "for us to bear"),
        (11, 12, "this thing?"),
        (13, 17, "And is it not great"),
        (18, 21, "this our affliction?"),
        (22, 24, "Now behold,"),
        (25, 27, "how great is"),
        (28, 29, "the reason"),
        (30, 33, "we have to mourn."),
    ],
    24: [
        (0, 0, "Yea,"),
        (1, 4, "I say"),
        (5, 7, "unto you,"),
        (8, 11, "great are the reasons"),
        (12, 16, "which we have"),
        (17, 19, "to mourn;"),
        (20, 21, "for behold"),
        (22, 23, "how many"),
        (24, 26, "of our brethren"),
        (27, 28, "have been slain,"),
        (29, 32, "and hath been spilt in vain"),
        (33, 35, "their blood,"),
        (36, 39, "and all these things"),
        (40, 41, "have happened"),
        (42, 45, "because of iniquity."),
    ],
    25: [
        (0, 5, "For if had not fallen"),
        (6, 7, "this people"),
        (8, 10, "into transgression"),
        (11, 14, "would not have suffered"),
        (15, 17, "the Lord"),
        (18, 21, "this great evil"),
        (22, 24, "that should come"),
        (25, 28, "upon them."),
        (29, 30, "But behold,"),
        (31, 35, "they would not hearken"),
        (36, 38, "unto his words;"),
        (39, 42, "but there arose"),
        (43, 43, "contentions"),
        (44, 48, "among them,"),
        (49, 54, "even so exceedingly great"),
        (55, 57, "that it came to pass"),
        (58, 60, "they did shed"),
        (61, 62, "the blood"),
        (63, 64, "among"),
        (65, 68, "themselves."),
    ],
    26: [
        (0, 3, "And they have slain"),
        (4, 8, "a prophet of the Lord;"),
        (9, 9, "yea,"),
        (10, 13, "a chosen man"),
        (14, 16, "of God,"),
        (17, 22, "who told"),
        (23, 26, "them"),
        (27, 29, "their wickedness"),
        (30, 32, "and abominations,"),
        (33, 35, "and prophesied"),
        (36, 40, "concerning the many"),
        (41, 42, "things"),
        (43, 47, "which are to come,"),
        (48, 48, "yea,"),
        (49, 51, "even"),
        (52, 55, "the coming"),
        (56, 57, "of Christ."),
    ],
    27: [
        (0, 1, "And because"),
        (2, 6, "he said"),
        (7, 10, "unto them"),
        (11, 12, "that Christ"),
        (13, 16, "was the God,"),
        (17, 19, "the Father"),
        (20, 23, "of all things,"),
        (24, 26, "and said"),
        (27, 32, "that he should take"),
        (33, 35, "upon him"),
        (36, 39, "the image of man,"),
        (40, 44, "and the very image"),
        (45, 50, "after which was created"),
        (51, 52, "man"),
        (53, 55, "in the beginning;"),
        (56, 58, "or in"),
        (59, 61, "other words,"),
        (62, 66, "he said"),
        (67, 70, "that man was created"),
        (71, 75, "after the image of God,"),
        (76, 81, "and should come down"),
        (82, 83, "God"),
        (84, 88, "among the children of men,"),
        (89, 90, "and take"),
        (91, 93, "upon him"),
        (94, 95, "flesh"),
        (96, 98, "and blood,"),
        (99, 101, "and go about"),
        (102, 106, "upon the face of the earth—"),
    ],
    28: [
        (0, 2, "And now,"),
        (3, 3, "because"),
        (4, 8, "he said"),
        (9, 10, "these things,"),
        (11, 13, "they did slay"),
        (14, 16, "him;"),
        (17, 20, "and many more"),
        (21, 22, "things"),
        (23, 25, "did they do"),
        (26, 29, "which came"),
        (30, 33, "upon them"),
        (34, 38, "the wrath of God."),
        (39, 40, "Therefore,"),
        (41, 44, "who wondereth"),
        (45, 48, "that they are"),
        (49, 51, "in bondage,"),
        (52, 56, "and that they are smitten"),
        (57, 59, "with sore afflictions?"),
    ],
    29: [
        (0, 1, "For behold,"),
        (2, 4, "hath said"),
        (5, 6, "the Lord:"),
        (7, 10, "I will not succor"),
        (11, 13, "my people"),
        (14, 16, "in the day"),
        (17, 20, "of their transgression;"),
        (21, 26, "but I will hedge up"),
        (27, 29, "their ways"),
        (30, 31, "that"),
        (32, 34, "they prosper not;"),
        (35, 39, "and their doings"),
        (40, 41, "to be done"),
        (42, 45, "shall be as"),
        (46, 48, "a stumbling block"),
        (49, 52, "before them."),
    ],
    30: [
        (0, 2, "And again,"),
        (3, 7, "he saith:"),
        (8, 10, "If shall sow"),
        (11, 13, "my people"),
        (14, 15, "filthiness"),
        (16, 19, "they shall reap"),
        (20, 22, "thereof"),
        (23, 24, "the chaff"),
        (25, 27, "in the whirlwind;"),
        (28, 31, "and the effect thereof"),
        (32, 35, "is poison."),
    ],
    31: [
        (0, 4, "And again saith"),
        (5, 6, "he:"),
        (7, 9, "If shall sow"),
        (10, 12, "my people"),
        (13, 14, "filthiness"),
        (15, 19, "they shall reap"),
        (20, 23, "the east wind,"),
        (24, 27, "which quickly"),
        (28, 30, "bringeth"),
        (31, 32, "destruction."),
    ],
    32: [
        (0, 3, "And now, behold,"),
        (4, 5, "is fulfilled"),
        (6, 7, "the promise"),
        (8, 10, "of the Lord,"),
        (11, 14, "and ye are smitten"),
        (15, 16, "and afflicted."),
    ],
    33: [
        (0, 1, "But if"),
        (2, 5, "ye turn"),
        (6, 8, "to the Lord"),
        (9, 12, "with full purpose"),
        (13, 15, "of heart,"),
        (16, 18, "and put"),
        (19, 21, "your trust"),
        (22, 24, "in him,"),
        (25, 27, "and serve"),
        (28, 30, "him"),
        (31, 34, "with all diligence"),
        (35, 37, "of mind,"),
        (38, 41, "if ye do"),
        (42, 43, "that thing,"),
        (44, 50, "he will deliver you"),
        (51, 53, "according to"),
        (54, 56, "his own will"),
        (57, 59, "and his pleasure,"),
        (60, 62, "out of bondage."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
