"""
Hand-curated TAM-phrase gloss overrides for Eteru (Ether) 10 — the succession of Jaredite
kings continues: Shez rebuilds after the famine; Riplakish reigns in oppression and
luxury and is slain; Morianton restores the kingdom and builds; the line passes through
Kim, Levi, Corom, Kish, Lib, and others. Under Lib the poisonous serpents are destroyed,
the land is developed with mighty works and abundant industry, and the people prosper
exceedingly across a land choice above all.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15, vocative 12). `o le a` stays atomic and is never
fused with a following `se X` NP; cells go past 5 only for rule-2 (absorbed
subject) or rule-7 (`o le a` + verb + directional) clusters.

    python3 build_overrides_ether10.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "ether"
CHAPTER_NUM = 10

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 5, "Shez,"),
        (6, 10, "who did descend"),
        (11, 12, "from Heth—"),
        (13, 15, "for did perish"),
        (16, 16, "Heth"),
        (17, 19, "in the famine,"),
        (20, 23, "and all his family"),
        (24, 26, "save Shez—"),
        (27, 30, "wherefore,"),
        (31, 35, "did begin"),
        (36, 37, "Shez"),
        (38, 40, "to build up again"),
        (41, 42, "a people"),
        (43, 44, "that was fallen."),
    ],
    2: [
        (0, 3, "And it came to pass that"),
        (4, 6, "remembered Shez"),
        (7, 8, "the destruction"),
        (9, 11, "of his fathers,"),
        (12, 15, "and he built up"),
        (16, 18, "a righteous kingdom;"),
        (19, 22, "for he remembered"),
        (23, 25, "the things done"),
        (26, 28, "by the Lord"),
        (29, 31, "in the bringing of"),
        (32, 36, "Jared and his brother"),
        (37, 41, "over the deep;"),
        (42, 46, "and he walked"),
        (47, 51, "in the ways of the Lord;"),
        (52, 55, "and he begat"),
        (56, 58, "sons and daughters."),
    ],
    3: [
        (0, 1, "And"),
        (2, 4, "his firstborn son,"),
        (5, 6, "who"),
        (7, 9, "his name"),
        (10, 11, "was Shez,"),
        (12, 13, "rebelled"),
        (14, 16, "against him;"),
        (17, 20, "nevertheless,"),
        (21, 22, "was smitten"),
        (23, 23, "Shez"),
        (24, 26, "by the hand"),
        (27, 29, "of a robber,"),
        (30, 31, "because of"),
        (32, 34, "his great wealth,"),
        (35, 39, "which restored"),
        (40, 41, "peace"),
        (42, 44, "unto his father."),
    ],
    4: [
        (0, 3, "And it came to pass that"),
        (4, 4, "built"),
        (5, 7, "his father"),
        (8, 8, "cities"),
        (9, 10, "many"),
        (11, 15, "upon the land,"),
        (16, 20, "and once more began"),
        (21, 23, "the people to spread forth"),
        (24, 26, "upon"),
        (27, 29, "all the land."),
        (30, 32, "And lived"),
        (33, 33, "Shez"),
        (34, 38, "unto years"),
        (39, 41, "of great old age;"),
        (42, 46, "and he begat"),
        (47, 47, "Riplakish."),
        (48, 52, "And he died,"),
        (53, 55, "and did reign"),
        (56, 56, "Riplakish"),
        (57, 61, "in his place."),
    ],
    5: [
        (0, 3, "And it came to pass that"),
        (4, 6, "did not do"),
        (7, 8, "Riplakish"),
        (9, 11, "that which was right"),
        (12, 14, "in the sight"),
        (15, 17, "of the Lord,"),
        (18, 22, "for unto him were"),
        (23, 24, "wives"),
        (25, 29, "and many concubines,"),
        (30, 33, "and he did lay"),
        (34, 37, "upon the shoulders"),
        (38, 39, "of men"),
        (40, 42, "things heavy"),
        (43, 44, "to be borne;"),
        (45, 45, "yea,"),
        (46, 48, "he did burden"),
        (49, 50, "them"),
        (51, 53, "with heavy taxes;"),
        (54, 57, "and he did build"),
        (58, 62, "many spacious buildings"),
        (63, 64, "with the taxes."),
    ],
    6: [
        (0, 3, "And he did build"),
        (4, 6, "for himself"),
        (7, 10, "a most beautiful throne;"),
        (11, 14, "and he did build"),
        (15, 18, "many prisons,"),
        (19, 23, "and whosoever"),
        (24, 26, "would not"),
        (27, 28, "pay"),
        (29, 30, "the tax"),
        (31, 33, "he did cast"),
        (34, 36, "into prison;"),
        (37, 41, "and whosoever"),
        (42, 44, "could not"),
        (45, 47, "to pay"),
        (48, 49, "the tax"),
        (50, 52, "he did cast"),
        (53, 55, "into prison;"),
        (56, 60, "and he did command"),
        (61, 64, "that they labor continually"),
        (65, 68, "for their maintenance;"),
        (69, 73, "and whosoever"),
        (74, 77, "refused to work"),
        (78, 81, "he did order"),
        (82, 83, "to be slain."),
    ],
    7: [
        (0, 3, "Wherefore"),
        (4, 7, "he did obtain"),
        (8, 11, "all his fine work,"),
        (12, 12, "yea,"),
        (13, 15, "even"),
        (16, 19, "his pure gold,"),
        (20, 22, "he did order"),
        (23, 24, "to be refined"),
        (25, 27, "in prison;"),
        (28, 31, "and all fine works"),
        (32, 33, "beautiful"),
        (34, 36, "of divers kinds"),
        (37, 39, "he did order"),
        (40, 41, "to be made"),
        (42, 44, "in prison."),
        (45, 48, "And it came to pass that"),
        (49, 50, "he did afflict"),
        (51, 51, "the people"),
        (52, 54, "with his whoredoms"),
        (55, 57, "and abominations."),
    ],
    8: [
        (0, 3, "And after"),
        (4, 6, "the space of"),
        (7, 10, "forty years"),
        (11, 13, "and two,"),
        (14, 17, "of his reigning"),
        (18, 20, "it came to pass that"),
        (21, 24, "rose up the people"),
        (25, 27, "to rebel against"),
        (28, 30, "him;"),
        (31, 34, "and there began"),
        (35, 37, "again to be"),
        (38, 39, "wars"),
        (40, 42, "in the land,"),
        (43, 47, "until was slain"),
        (48, 48, "Riplakish,"),
        (49, 52, "and were driven out"),
        (53, 54, "his seed"),
        (55, 57, "from the land."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 5, "when had passed"),
        (6, 8, "the space of"),
        (9, 11, "many years,"),
        (12, 14, "did assemble"),
        (15, 16, "Morianton,"),
        (17, 20, "(he was one"),
        (21, 23, "who descended"),
        (24, 25, "of Riplakish)"),
        (26, 29, "an army from men"),
        (30, 32, "who were expelled,"),
        (33, 35, "and went"),
        (36, 38, "and gave battle to"),
        (39, 40, "the people;"),
        (41, 44, "and it came to pass that"),
        (45, 46, "he gained"),
        (47, 48, "power"),
        (49, 52, "over the cities"),
        (53, 54, "many;"),
        (55, 58, "and it came to pass that"),
        (59, 61, "very sore was"),
        (62, 63, "the war,"),
        (64, 66, "and did continue"),
        (67, 71, "for many years;"),
        (72, 75, "and it came to pass that"),
        (76, 78, "he did gain"),
        (79, 80, "power"),
        (81, 83, "upon"),
        (84, 86, "all the land,"),
        (87, 90, "and did establish"),
        (91, 93, "himself"),
        (94, 97, "to be king"),
        (98, 100, "over"),
        (101, 103, "all the land."),
    ],
    10: [
        (0, 3, "And after that"),
        (4, 6, "he had set up"),
        (7, 9, "himself"),
        (10, 11, "as king,"),
        (12, 14, "he did lighten"),
        (15, 19, "the burden of the people,"),
        (20, 22, "a thing which"),
        (23, 27, "did please him"),
        (28, 32, "in the sight of the people,"),
        (33, 37, "and they did anoint"),
        (38, 39, "him"),
        (40, 42, "to be"),
        (43, 45, "their king."),
    ],
    11: [
        (0, 3, "And he administered"),
        (4, 5, "just things"),
        (6, 7, "unto the people,"),
        (8, 12, "but he did not so"),
        (13, 16, "unto himself,"),
        (17, 18, "because of"),
        (19, 22, "his many whoredoms;"),
        (23, 26, "wherefore"),
        (27, 32, "he was cut off"),
        (33, 34, "from the presence"),
        (35, 37, "of the Lord."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 6, "built Morianton"),
        (7, 9, "many cities,"),
        (10, 13, "and it came to pass that"),
        (14, 16, "grew rich the people"),
        (17, 21, "under his reign,"),
        (22, 23, "in buildings,"),
        (24, 26, "and in gold"),
        (27, 28, "and silver,"),
        (29, 33, "and in the raising"),
        (34, 36, "of grain,"),
        (37, 39, "and in flocks,"),
        (40, 41, "and herds,"),
        (42, 44, "and such things"),
        (45, 47, "which were restored"),
        (48, 51, "unto them."),
    ],
    13: [
        (0, 2, "And lived"),
        (3, 3, "Morianton"),
        (4, 8, "very many years,"),
        (9, 13, "then he begat"),
        (14, 15, "Kim;"),
        (16, 19, "and Kim reigned"),
        (20, 24, "in place of his father;"),
        (25, 29, "and he did reign"),
        (30, 33, "eight years,"),
        (34, 36, "and died"),
        (37, 38, "his father."),
        (39, 42, "And it came to pass that"),
        (43, 45, "reigned not Kim"),
        (46, 48, "in righteousness,"),
        (49, 52, "wherefore"),
        (53, 56, "was not pleased"),
        (57, 58, "the Lord"),
        (59, 61, "with him."),
    ],
    14: [
        (0, 3, "And rose up"),
        (4, 5, "his brother"),
        (6, 9, "to rebel against"),
        (10, 12, "him,"),
        (13, 17, "whereby he did bring"),
        (18, 20, "him into captivity;"),
        (21, 25, "and he remained"),
        (26, 28, "in captivity"),
        (29, 32, "all his days;"),
        (33, 36, "and he begat"),
        (37, 39, "sons and daughters"),
        (40, 41, "while yet a captive;"),
        (42, 44, "and in the days"),
        (45, 48, "of his old age"),
        (49, 52, "he did beget"),
        (53, 53, "Levi;"),
        (54, 58, "and he died."),
    ],
    15: [
        (0, 3, "And it came to pass that"),
        (4, 5, "did serve"),
        (6, 6, "Levi"),
        (7, 7, "in captivity"),
        (8, 10, "after"),
        (11, 12, "the death"),
        (13, 15, "of his father,"),
        (16, 19, "for the space"),
        (20, 22, "of forty"),
        (23, 26, "and two years."),
        (27, 31, "And he raised war"),
        (32, 33, "against"),
        (34, 36, "the king"),
        (37, 39, "of the land,"),
        (40, 44, "whereby he obtained"),
        (45, 47, "unto himself"),
        (48, 49, "the kingdom."),
    ],
    16: [
        (0, 3, "And after that"),
        (4, 6, "he had obtained"),
        (7, 9, "the kingdom"),
        (10, 12, "unto himself"),
        (13, 15, "he did"),
        (16, 18, "that which was right"),
        (19, 21, "in the sight"),
        (22, 24, "of the Lord;"),
        (25, 27, "and did prosper"),
        (28, 28, "the people"),
        (29, 33, "upon the land;"),
        (34, 38, "and he did live"),
        (39, 43, "unto a long life,"),
        (44, 47, "and he begat"),
        (48, 51, "sons and daughters;"),
        (52, 57, "and he also begat"),
        (58, 58, "Corom,"),
        (59, 63, "whom he did anoint"),
        (64, 67, "to be king"),
        (68, 72, "in his place."),
    ],
    17: [
        (0, 3, "And it came to pass that"),
        (4, 6, "did Corom"),
        (7, 9, "that which was good"),
        (10, 12, "in the sight"),
        (13, 15, "of the Lord"),
        (16, 19, "all his days;"),
        (20, 23, "and he begat"),
        (24, 28, "many sons and daughters;"),
        (29, 33, "and after that he"),
        (34, 36, "had lived"),
        (37, 40, "many days"),
        (41, 44, "he died,"),
        (45, 47, "even as"),
        (48, 50, "all people"),
        (51, 53, "of the world;"),
        (54, 57, "and Kish reigned"),
        (58, 62, "in his place."),
    ],
    18: [
        (0, 3, "And it came to pass that"),
        (4, 5, "died also"),
        (6, 6, "Kish,"),
        (7, 9, "and reigned"),
        (10, 10, "Lib"),
        (11, 15, "in his stead."),
    ],
    19: [
        (0, 4, "And it also came to pass"),
        (5, 5, "did do"),
        (6, 7, "Lib"),
        (8, 10, "that which was good"),
        (11, 13, "in the sight"),
        (14, 16, "of the Lord."),
        (17, 21, "And in Lib's days"),
        (22, 24, "were destroyed"),
        (25, 26, "the poisonous serpents."),
        (27, 30, "Wherefore"),
        (31, 35, "they did go forth"),
        (36, 40, "into the south country,"),
        (41, 43, "to seek food"),
        (44, 48, "for the people of the land,"),
        (49, 51, "for was full"),
        (52, 53, "the land"),
        (54, 58, "with wild animals."),
        (59, 62, "And also became"),
        (63, 65, "Lib himself"),
        (66, 69, "a mighty hunter."),
    ],
    20: [
        (0, 3, "And they did build"),
        (4, 6, "a great city"),
        (7, 9, "by the border"),
        (10, 12, "of the narrow land,"),
        (13, 15, "by the point"),
        (16, 20, "where divides the sea"),
        (21, 23, "and the land."),
    ],
    21: [
        (0, 3, "And they did preserve"),
        (4, 7, "the land southward"),
        (8, 11, "as a wilderness"),
        (12, 14, "unworked,"),
        (15, 18, "to hunt game."),
        (19, 23, "And the whole face"),
        (24, 28, "of the land northward"),
        (29, 31, "was all inhabited"),
        (32, 33, "by men."),
    ],
    22: [
        (0, 2, "And they became"),
        (3, 4, "very diligent,"),
        (5, 9, "and they did buy"),
        (10, 12, "and sell"),
        (13, 14, "and did traffic"),
        (15, 17, "one"),
        (18, 20, "with another,"),
        (21, 24, "that they might get"),
        (25, 26, "gain."),
    ],
    23: [
        (0, 4, "And they did work"),
        (5, 7, "in all manner"),
        (8, 10, "of ores;"),
        (11, 14, "and they did make"),
        (15, 15, "gold,"),
        (16, 17, "and silver,"),
        (18, 19, "and iron,"),
        (20, 21, "and brass,"),
        (22, 24, "and all kinds"),
        (25, 27, "of metals;"),
        (28, 32, "and they did dig up"),
        (33, 35, "out of the earth;"),
        (36, 39, "wherefore,"),
        (40, 43, "they did cast"),
        (44, 45, "up"),
        (46, 48, "great mounds"),
        (49, 51, "of earth"),
        (52, 55, "that might be gotten"),
        (56, 57, "ore and gold,"),
        (58, 59, "and silver,"),
        (60, 62, "and iron,"),
        (63, 64, "and brass."),
        (65, 68, "And they did make"),
        (69, 70, "beautiful things"),
        (71, 73, "of every kind."),
    ],
    24: [
        (0, 3, "And they had"),
        (4, 4, "silks,"),
        (5, 9, "and fine-twined linen;"),
        (10, 13, "and they did make"),
        (14, 17, "cloth of every kind,"),
        (18, 22, "that they might"),
        (23, 26, "clothe themselves"),
        (27, 31, "from their nakedness."),
    ],
    25: [
        (0, 3, "And they did make"),
        (4, 4, "implements"),
        (5, 8, "of every kind"),
        (9, 11, "to work"),
        (12, 13, "the ground,"),
        (14, 15, "to plow"),
        (16, 18, "and to sow"),
        (19, 20, "the ground,"),
        (21, 22, "to reap"),
        (23, 25, "and to weed,"),
        (26, 28, "and to thresh"),
        (29, 30, "the corn."),
    ],
    26: [
        (0, 3, "And they did make"),
        (4, 4, "implements"),
        (5, 8, "of every kind"),
        (9, 12, "wherewith they worked"),
        (13, 15, "their animals."),
    ],
    27: [
        (0, 3, "And they did make"),
        (4, 4, "weapons"),
        (5, 8, "of every kind"),
        (9, 10, "of war."),
        (11, 14, "And they did make"),
        (15, 16, "all kinds"),
        (17, 19, "of workmanship"),
        (20, 21, "of divers sorts."),
    ],
    28: [
        (0, 4, "And there was no people"),
        (5, 7, "more blessed"),
        (8, 11, "than them,"),
        (12, 17, "nor more made rich"),
        (18, 20, "by the hand"),
        (21, 23, "of the Lord."),
        (24, 28, "And they dwelt"),
        (29, 31, "in a land"),
        (32, 35, "which was choice"),
        (36, 40, "above all lands,"),
        (41, 45, "for had spoken it"),
        (46, 47, "the Lord."),
    ],
    29: [
        (0, 3, "And it came to pass that"),
        (4, 5, "lived Lib"),
        (6, 9, "many years,"),
        (10, 13, "and he begat"),
        (14, 17, "sons and daughters;"),
        (18, 22, "and he also begat"),
        (23, 23, "Hearthom."),
    ],
    30: [
        (0, 3, "And it came to pass that"),
        (4, 5, "Hearthom reigned"),
        (6, 10, "in place of his father."),
        (11, 13, "And when"),
        (14, 18, "twenty and four"),
        (19, 19, "years"),
        (20, 22, "of Hearthom's reigning,"),
        (23, 23, "behold,"),
        (24, 25, "was taken away"),
        (26, 27, "the kingdom"),
        (28, 31, "from him."),
        (32, 36, "And he did serve"),
        (37, 37, "in captivity"),
        (38, 41, "many years,"),
        (42, 42, "yea,"),
        (43, 46, "all his days"),
        (47, 49, "that remained."),
    ],
    31: [
        (0, 3, "And he begat"),
        (4, 4, "Heth,"),
        (5, 7, "and dwelt"),
        (8, 9, "Heth a captive"),
        (10, 13, "all his days."),
        (14, 16, "And begat"),
        (17, 18, "Heth"),
        (19, 20, "Aaron,"),
        (21, 23, "and dwelt"),
        (24, 25, "Aaron a captive"),
        (26, 29, "all his days;"),
        (30, 33, "and he begat"),
        (34, 34, "Amnigaddah,"),
        (35, 38, "and dwelt also"),
        (39, 40, "Amnigaddah a captive"),
        (41, 44, "all his days;"),
        (45, 48, "and he begat"),
        (49, 49, "Coriantum,"),
        (50, 52, "and dwelt"),
        (53, 54, "Coriantum a captive"),
        (55, 58, "all his days;"),
        (59, 62, "and he begat"),
        (63, 63, "Com."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 6, "drew away Com"),
        (7, 9, "the half"),
        (10, 12, "of the kingdom."),
        (13, 17, "And he did reign"),
        (18, 20, "over"),
        (21, 25, "the half of the kingdom"),
        (26, 30, "forty years"),
        (31, 33, "and two;"),
        (34, 38, "and he did battle"),
        (39, 41, "against the king,"),
        (42, 43, "Amnigaddah,"),
        (44, 48, "and the two fought"),
        (49, 52, "for the space of"),
        (53, 55, "many years,"),
        (56, 59, "in which time"),
        (60, 62, "prevailed over"),
        (63, 64, "Com"),
        (65, 66, "over Amnigaddah,"),
        (67, 70, "and got the rule"),
        (71, 73, "over"),
        (74, 77, "the part that remained"),
        (78, 80, "of the kingdom."),
    ],
    33: [
        (0, 1, "And in"),
        (2, 4, "the days of Com"),
        (5, 9, "there began to be"),
        (10, 11, "robbers"),
        (12, 14, "in the land;"),
        (15, 18, "and they did follow"),
        (19, 21, "the old designs,"),
        (22, 25, "and they took oaths"),
        (26, 30, "to follow the manner"),
        (31, 33, "of the ancients,"),
        (34, 36, "and again sought"),
        (37, 38, "to overthrow"),
        (39, 40, "the kingdom."),
    ],
    34: [
        (0, 1, "Now"),
        (2, 4, "did much fight"),
        (5, 5, "Com"),
        (6, 7, "against"),
        (8, 11, "them;"),
        (12, 15, "nevertheless,"),
        (16, 20, "he did not prevail"),
        (21, 24, "against them."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
