"""
Hand-curated TAM-phrase gloss overrides for 3 Nifae (3 Nephi) 20 — Jesus miraculously
provides bread and wine and administers the sacrament again; he prophesies of the
covenant of the Father to gather scattered Israel, the restoration of the remnant of
Jacob and the Gentiles' role, the fulfilment of Isaiah, and the establishment of the
New Jerusalem; he quotes Moses and the prophets that a Prophet like unto Moses would
come, and warns the Gentiles that if they harden their hearts the covenant people of
Israel shall be as a young lion among the flocks, treading them down.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits applied to bom_books.json before glossing:
    20:11  Isaia—faauta    ->  Isaia—    +  faauta
    20:27  lalolagi—i      ->  lalolagi— +  i
    20:34  olioli—Ia       ->  olioli—   +  Ia

    python3 build_overrides_3nephi20.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "3nephi"
CHAPTER_NUM = 20

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 7, "he commanded"),
        (8, 12, "the multitude"),
        (13, 16, "and his disciples also"),
        (17, 22, "that they cease"),
        (23, 25, "their praying."),
        (26, 30, "And he commanded"),
        (31, 34, "them"),
        (35, 40, "that they cease not praying"),
        (41, 44, "in their hearts."),
    ],
    2: [
        (0, 5, "And he commanded them"),
        (6, 8, "that they arise"),
        (9, 12, "and stand up"),
        (13, 16, "upon their feet."),
        (17, 20, "And they arose"),
        (21, 24, "and stood up"),
        (25, 28, "upon their feet."),
    ],
    3: [
        (0, 3, "And it came to pass that"),
        (4, 7, "he broke again"),
        (8, 9, "the bread"),
        (10, 13, "and blessed it,"),
        (14, 15, "and gave it"),
        (16, 19, "to the disciples"),
        (20, 22, "to eat."),
    ],
    4: [
        (0, 6, "And when they had eaten,"),
        (7, 11, "he commanded them"),
        (12, 16, "that they break the bread,"),
        (17, 18, "and give it"),
        (19, 23, "unto the multitude."),
    ],
    5: [
        (0, 6, "And when they had given it"),
        (7, 11, "unto the multitude"),
        (12, 15, "he also gave"),
        (16, 19, "unto them"),
        (20, 24, "the wine to drink,"),
        (25, 28, "and commanded them"),
        (29, 33, "that they give it"),
        (34, 38, "unto the multitude."),
    ],
    6: [
        (0, 1, "Now,"),
        (2, 5, "there was no bread,"),
        (6, 9, "nor wine,"),
        (10, 15, "brought by the disciples,"),
        (16, 21, "nor by the multitude;"),
    ],
    7: [
        (0, 5, "But verily he did give"),
        (6, 9, "unto them"),
        (10, 14, "the bread to eat,"),
        (15, 18, "and also the wine"),
        (19, 21, "to drink."),
    ],
    8: [
        (0, 4, "And he said"),
        (5, 8, "unto them:"),
        (9, 14, "He that eateth"),
        (15, 17, "this bread"),
        (18, 20, "eateth"),
        (21, 23, "of my body"),
        (24, 26, "to his soul;"),
        (27, 32, "and he that drinketh"),
        (33, 35, "of this wine"),
        (36, 39, "drinketh"),
        (40, 42, "of my blood"),
        (43, 45, "to his soul;"),
        (46, 53, "and his soul shall never hunger"),
        (54, 56, "nor thirst,"),
        (57, 58, "his soul,"),
        (59, 63, "but shall be filled."),
    ],
    9: [
        (0, 1, "Now,"),
        (2, 6, "when they had eaten"),
        (7, 8, "and drunk,"),
        (9, 13, "the whole multitude,"),
        (14, 14, "behold,"),
        (15, 18, "they were filled"),
        (19, 21, "with the Spirit;"),
        (22, 26, "and they did cry out together"),
        (27, 31, "with one voice,"),
        (32, 35, "and gave glory"),
        (36, 37, "to Jesus,"),
        (38, 42, "whom they saw"),
        (43, 46, "and heard."),
    ],
    10: [
        (0, 3, "And it came to pass that"),
        (4, 7, "when they had given"),
        (8, 11, "all of them"),
        (12, 14, "glory"),
        (15, 16, "unto Jesus,"),
        (17, 20, "he said"),
        (21, 24, "unto them:"),
        (25, 25, "Behold"),
        (26, 27, "now"),
        (28, 32, "I finish"),
        (33, 36, "the commandment which"),
        (37, 40, "was commanded me"),
        (41, 43, "by the Father"),
        (44, 46, "concerning"),
        (47, 48, "this people,"),
        (49, 53, "who are a portion"),
        (54, 55, "of the remnant"),
        (56, 58, "of the house"),
        (59, 60, "of Israel."),
    ],
    11: [
        (0, 2, "Ye remember"),
        (3, 6, "that I spake"),
        (7, 9, "unto you,"),
        (10, 12, "and said,"),
        (13, 15, "when should be fulfilled"),
        (16, 18, "the words of Isaiah—"),
        (19, 19, "behold"),
        (20, 23, "they are written,"),
        (24, 28, "ye have them"),
        (29, 32, "before you,"),
        (33, 34, "therefore"),
        (35, 39, "search ye them—"),
    ],
    12: [
        (0, 2, "And verily,"),
        (3, 4, "verily,"),
        (5, 8, "I say"),
        (9, 11, "unto you,"),
        (12, 16, "when they shall be fulfilled"),
        (17, 20, "then is the fulfilling"),
        (21, 24, "of the covenant which"),
        (25, 26, "was made"),
        (27, 29, "by the Father"),
        (30, 32, "unto his people,"),
        (33, 35, "O house"),
        (36, 37, "of Israel."),
    ],
    13: [
        (0, 4, "And then"),
        (5, 10, "shall be gathered in"),
        (11, 13, "the remnants,"),
        (14, 19, "which shall be scattered abroad"),
        (20, 24, "upon the face of the earth,"),
        (25, 26, "from the east"),
        (27, 29, "and from the west,"),
        (30, 32, "and from the south"),
        (33, 35, "and from the north;"),
        (36, 42, "and they shall be brought"),
        (43, 45, "to the knowledge"),
        (46, 48, "of the Lord"),
        (49, 51, "their God,"),
        (52, 55, "who hath redeemed"),
        (56, 57, "them."),
    ],
    14: [
        (0, 3, "And ... hath commanded me"),
        (4, 6, "the Father"),
        (7, 10, "that I should give"),
        (11, 13, "unto you"),
        (14, 15, "this land,"),
        (16, 19, "for your inheritance."),
    ],
    15: [
        (0, 4, "And I say"),
        (5, 7, "unto you,"),
        (8, 11, "that if do not repent"),
        (12, 12, "the Gentiles"),
        (13, 15, "after"),
        (16, 18, "the blessing which"),
        (19, 23, "they shall receive,"),
        (24, 29, "after they have scattered"),
        (30, 32, "my people—"),
    ],
    16: [
        (0, 3, "Then shall go forth"),
        (4, 5, "ye,"),
        (6, 10, "who are a portion"),
        (11, 12, "of the remnant"),
        (13, 15, "of the house"),
        (16, 17, "of Jacob,"),
        (18, 19, "among"),
        (20, 23, "them;"),
        (24, 30, "and ye shall be"),
        (31, 33, "in the midst"),
        (34, 36, "of them"),
        (37, 38, "who"),
        (39, 42, "shall be many;"),
        (43, 49, "and ye shall be"),
        (50, 51, "among"),
        (52, 55, "them"),
        (56, 60, "as a lion"),
        (61, 64, "among the beasts"),
        (65, 67, "of the forest,"),
        (68, 70, "and as"),
        (71, 74, "a young lion"),
        (75, 78, "among the flocks"),
        (79, 80, "of sheep,"),
        (81, 82, "who,"),
        (83, 83, "if"),
        (84, 89, "he go through"),
        (90, 96, "he treadeth down"),
        (97, 98, "them"),
        (99, 100, "and teareth"),
        (101, 101, "in pieces,"),
        (102, 105, "and none"),
        (106, 109, "can deliver."),
    ],
    17: [
        (0, 4, "Shall be lifted up"),
        (5, 6, "my hand"),
        (7, 9, "upon"),
        (10, 11, "thine adversaries,"),
        (12, 17, "and shall be cut off"),
        (18, 20, "all thine enemies."),
    ],
    18: [
        (0, 6, "And I will gather together"),
        (7, 8, "my people"),
        (9, 13, "as gathereth together"),
        (14, 16, "a man"),
        (17, 19, "his sheaves"),
        (20, 22, "into"),
        (23, 24, "the floor."),
    ],
    19: [
        (0, 5, "For I will make"),
        (6, 7, "my people"),
        (8, 12, "with whom hath covenanted"),
        (13, 14, "the Father,"),
        (15, 15, "yea,"),
        (16, 20, "I will make"),
        (21, 22, "thy horn"),
        (23, 24, "iron,"),
        (25, 30, "and I will make"),
        (31, 32, "thy hoofs"),
        (33, 34, "brass."),
        (35, 40, "And thou shalt beat in pieces"),
        (41, 43, "many people;"),
        (44, 49, "and I will consecrate"),
        (50, 52, "their gain"),
        (53, 55, "unto the Lord,"),
        (56, 59, "and their substance"),
        (60, 62, "unto the Lord"),
        (63, 66, "of the whole earth."),
        (67, 68, "And behold,"),
        (69, 71, "I myself am"),
        (72, 75, "he who doeth"),
        (76, 77, "these things."),
    ],
    20: [
        (0, 5, "And it shall come to pass,"),
        (6, 9, "saith"),
        (10, 11, "the Father,"),
        (12, 16, "shall hang over"),
        (17, 19, "over"),
        (20, 21, "them"),
        (22, 23, "the sword"),
        (24, 26, "of my justice"),
        (27, 29, "at that day;"),
        (30, 33, "and except"),
        (34, 36, "they repent"),
        (37, 41, "it shall fall"),
        (42, 44, "upon"),
        (45, 46, "them,"),
        (47, 50, "saith"),
        (51, 52, "the Father,"),
        (53, 53, "yea,"),
        (54, 56, "even upon"),
        (57, 59, "all the nations"),
        (60, 61, "of the Gentiles."),
    ],
    21: [
        (0, 5, "And it shall come to pass that"),
        (6, 10, "I will establish"),
        (11, 12, "my people,"),
        (13, 15, "O house"),
        (16, 17, "of Israel."),
    ],
    22: [
        (0, 1, "And behold,"),
        (2, 6, "will I establish"),
        (7, 8, "this people"),
        (9, 11, "in this land,"),
        (12, 14, "unto the fulfilling of"),
        (15, 16, "the covenant"),
        (17, 19, "which I made"),
        (20, 23, "with your father"),
        (24, 25, "Jacob;"),
        (26, 32, "and it shall become a"),
        (33, 34, "New Jerusalem."),
        (35, 40, "And ... shall be"),
        (41, 43, "in the midst of"),
        (44, 45, "this people"),
        (46, 46, "the powers"),
        (47, 49, "of heaven;"),
        (50, 50, "yea,"),
        (51, 56, "even I will be"),
        (57, 59, "in the midst"),
        (60, 61, "of you."),
    ],
    23: [
        (0, 0, "Behold,"),
        (1, 4, "I am he"),
        (5, 9, "of whom Moses spake,"),
        (10, 12, "saying:"),
        (13, 17, "Shall raise up"),
        (18, 20, "the Lord"),
        (21, 22, "God"),
        (23, 24, "a prophet"),
        (25, 27, "unto you"),
        (28, 28, "of"),
        (29, 31, "your brethren,"),
        (32, 35, "like unto me;"),
        (36, 38, "shall ye hear"),
        (39, 41, "him"),
        (42, 45, "in all things whatsoever"),
        (46, 50, "he shall say"),
        (51, 53, "unto you."),
        (54, 60, "And it shall come to pass that"),
        (61, 62, "shall be cut off"),
        (63, 65, "from among"),
        (66, 67, "the people"),
        (68, 70, "every soul who"),
        (71, 75, "will not hear"),
        (76, 78, "that prophet."),
    ],
    24: [
        (0, 1, "Verily"),
        (2, 5, "I say"),
        (6, 8, "unto you,"),
        (9, 9, "yea,"),
        (10, 13, "and all the prophets"),
        (14, 16, "from Samuel"),
        (17, 19, "and those"),
        (20, 24, "that follow after,"),
        (25, 27, "as many"),
        (28, 31, "as have spoken,"),
        (32, 34, "have all testified"),
        (35, 37, "of me."),
    ],
    25: [
        (0, 1, "And behold,"),
        (2, 5, "ye are the children"),
        (6, 7, "of the prophets;"),
        (8, 11, "and ye are"),
        (12, 14, "of the house"),
        (15, 16, "of Israel;"),
        (17, 20, "and ye are"),
        (21, 24, "of the covenant which"),
        (25, 26, "made"),
        (27, 29, "the Father"),
        (30, 33, "with your fathers,"),
        (34, 37, "saying"),
        (38, 39, "unto Abraham:"),
        (40, 43, "And in thy seed"),
        (44, 48, "shall be blessed"),
        (49, 50, "all the kindreds"),
        (51, 53, "of the earth."),
    ],
    26: [
        (0, 3, "Having raised me up"),
        (4, 6, "the Father"),
        (7, 8, "first"),
        (9, 11, "unto you,"),
        (12, 15, "and sent me"),
        (16, 17, "to bless"),
        (18, 20, "you"),
        (21, 24, "in turning away"),
        (25, 27, "every one of you"),
        (28, 29, "from"),
        (30, 31, "his iniquities;"),
        (32, 35, "and the reason is"),
        (36, 40, "because ye are the children"),
        (41, 43, "of the covenant—"),
    ],
    27: [
        (0, 5, "And after ye were blessed"),
        (6, 7, "ye"),
        (8, 11, "then fulfilleth"),
        (12, 14, "the Father"),
        (15, 17, "the covenant which"),
        (18, 20, "he made"),
        (21, 22, "with Abraham,"),
        (23, 24, "saying:"),
        (25, 27, "In thy seed"),
        (28, 32, "shall be blessed"),
        (33, 34, "all the kindreds"),
        (35, 37, "of the earth—"),
        (38, 41, "unto the pouring out"),
        (42, 45, "of the Holy Ghost"),
        (46, 48, "through"),
        (49, 51, "me"),
        (52, 54, "upon"),
        (55, 55, "the Gentiles,"),
        (56, 59, "which blessing"),
        (60, 62, "upon"),
        (63, 63, "the Gentiles"),
        (64, 68, "shall make"),
        (69, 70, "them"),
        (71, 73, "to be greater"),
        (74, 76, "in their strength"),
        (77, 79, "above"),
        (80, 81, "all people,"),
        (82, 84, "even unto"),
        (85, 86, "the scattering"),
        (87, 89, "of my people,"),
        (90, 92, "O house"),
        (93, 94, "of Israel."),
    ],
    28: [
        (0, 6, "And they shall be"),
        (7, 9, "a scourge"),
        (10, 11, "unto the people"),
        (12, 14, "of this land."),
        (15, 18, "Nevertheless,"),
        (19, 24, "when they shall have received"),
        (25, 27, "the fulness"),
        (28, 30, "of my gospel,"),
        (31, 35, "and if they shall harden"),
        (36, 38, "their hearts"),
        (39, 40, "against"),
        (41, 43, "me"),
        (44, 49, "I will return"),
        (50, 52, "their iniquities"),
        (53, 55, "upon"),
        (56, 59, "their own heads,"),
        (60, 63, "saith"),
        (64, 65, "the Father."),
    ],
    29: [
        (0, 5, "And I will remember"),
        (6, 8, "the covenant which"),
        (9, 11, "I have made"),
        (12, 14, "with my people;"),
        (15, 18, "and I have covenanted"),
        (19, 21, "with them"),
        (22, 27, "that I would gather together"),
        (28, 29, "them"),
        (30, 33, "in mine own due time,"),
        (34, 41, "and that I would give again"),
        (42, 45, "unto them"),
        (46, 47, "the land"),
        (48, 51, "of their fathers"),
        (52, 55, "for their inheritance,"),
        (56, 59, "which is the land"),
        (60, 61, "of Jerusalem,"),
        (62, 65, "which is the land"),
        (66, 68, "that was promised"),
        (69, 71, "unto them"),
        (72, 73, "forever,"),
        (74, 77, "saith"),
        (78, 79, "the Father."),
    ],
    30: [
        (0, 6, "And it shall come to pass that"),
        (7, 8, "shall come"),
        (9, 10, "the time"),
        (11, 16, "when shall be preached"),
        (17, 18, "the fulness"),
        (19, 21, "of my gospel"),
        (22, 25, "unto them;"),
    ],
    31: [
        (0, 5, "And they shall believe"),
        (6, 8, "in me,"),
        (9, 11, "that I am"),
        (12, 13, "Jesus Christ,"),
        (14, 16, "the Son"),
        (17, 19, "of God,"),
        (20, 26, "and shall pray"),
        (27, 29, "unto the Father"),
        (30, 32, "in my name."),
    ],
    32: [
        (0, 3, "Then shall lift up"),
        (4, 5, "on high"),
        (6, 9, "their watchmen"),
        (10, 13, "their voice,"),
        (14, 19, "and they shall sing"),
        (20, 20, "together;"),
        (21, 21, "for"),
        (22, 26, "they shall see one another"),
        (27, 29, "each other."),
    ],
    33: [
        (0, 4, "Then will again gather together"),
        (5, 7, "them"),
        (8, 10, "the Father,"),
        (11, 13, "and give"),
        (14, 17, "unto them"),
        (18, 18, "Jerusalem"),
        (19, 21, "for the land"),
        (22, 25, "of their inheritance."),
    ],
    34: [
        (0, 3, "Then shall they break forth"),
        (4, 6, "into joy—"),
        (7, 9, "Sing together,"),
        (10, 12, "ye waste places"),
        (13, 14, "of Jerusalem;"),
        (15, 15, "for"),
        (16, 17, "hath comforted"),
        (18, 20, "the Father"),
        (21, 22, "his people,"),
        (23, 25, "he hath redeemed"),
        (26, 26, "Jerusalem."),
    ],
    35: [
        (0, 1, "Hath made bare"),
        (2, 4, "the Father"),
        (5, 7, "his holy arm"),
        (8, 11, "in the eyes"),
        (12, 14, "of all the nations;"),
        (15, 19, "and shall see"),
        (20, 21, "all the ends"),
        (22, 24, "of the earth"),
        (25, 27, "the salvation"),
        (28, 30, "of the Father;"),
        (31, 34, "and the Father"),
        (35, 36, "and I"),
        (37, 38, "are one."),
    ],
    36: [
        (0, 4, "And then shall be brought to pass"),
        (5, 7, "that which"),
        (8, 9, "is written:"),
        (10, 12, "Awake,"),
        (13, 17, "awake again;"),
        (18, 19, "and put on"),
        (20, 21, "thy strength,"),
        (22, 23, "O Zion;"),
        (24, 25, "put on"),
        (26, 28, "thy beautiful garments,"),
        (29, 30, "O Jerusalem,"),
        (31, 33, "the holy city,"),
        (34, 35, "for"),
        (36, 40, "henceforth"),
        (41, 45, "and evermore"),
        (46, 49, "shall no more come"),
        (50, 52, "into thee"),
        (53, 56, "the uncircumcised"),
        (57, 60, "and the unclean."),
    ],
    37: [
        (0, 2, "Shake thyself"),
        (3, 3, "from"),
        (4, 5, "the dust;"),
        (6, 6, "arise,"),
        (7, 9, "sit down,"),
        (10, 11, "O Jerusalem;"),
        (12, 14, "loose thyself"),
        (15, 16, "from the bands"),
        (17, 19, "of thy neck,"),
        (20, 23, "the captive daughter"),
        (24, 25, "of Zion."),
    ],
    38: [
        (0, 0, "For"),
        (1, 5, "thus saith"),
        (6, 8, "the Lord:"),
        (9, 12, "Ye have sold"),
        (13, 14, "yourselves"),
        (15, 17, "for nought;"),
        (18, 22, "and shall be redeemed"),
        (23, 23, "ye"),
        (24, 28, "without money."),
    ],
    39: [
        (0, 1, "Verily,"),
        (2, 3, "verily,"),
        (4, 7, "I say"),
        (8, 10, "unto you,"),
        (11, 14, "shall know"),
        (15, 17, "my people"),
        (18, 19, "my name;"),
        (20, 20, "yea,"),
        (21, 25, "they shall know"),
        (26, 28, "in that day"),
        (29, 33, "that I myself am he"),
        (34, 39, "that doth speak."),
    ],
    40: [
        (0, 7, "And then shall they say:"),
        (8, 12, "How beautiful"),
        (13, 15, "upon"),
        (16, 16, "the mountains"),
        (17, 18, "are the feet"),
        (19, 23, "of him that bringeth"),
        (24, 26, "good tidings"),
        (27, 30, "unto them,"),
        (31, 35, "that publisheth"),
        (36, 37, "peace;"),
        (38, 42, "that bringeth"),
        (43, 45, "good tidings"),
        (46, 49, "unto them"),
        (50, 51, "of good,"),
        (52, 56, "that publisheth"),
        (57, 58, "salvation;"),
        (59, 63, "that saith"),
        (64, 65, "unto Zion:"),
        (66, 67, "reigneth"),
        (68, 69, "Thy God!"),
    ],
    41: [
        (0, 5, "And then shall go forth"),
        (6, 8, "a cry:"),
        (9, 13, "Depart ye,"),
        (14, 17, "depart ye,"),
        (18, 21, "go ye"),
        (22, 23, "out"),
        (24, 24, "from"),
        (25, 26, "thence,"),
        (27, 30, "touch not"),
        (31, 32, "the thing"),
        (33, 35, "that is unclean;"),
        (36, 40, "go ye out"),
        (41, 42, "of the midst"),
        (43, 44, "of her;"),
        (45, 47, "be ye clean"),
        (48, 50, "that bear"),
        (51, 51, "the vessels"),
        (52, 54, "of the Lord."),
    ],
    42: [
        (0, 0, "For"),
        (1, 8, "ye shall not go out"),
        (9, 10, "forth"),
        (11, 13, "with haste,"),
        (14, 17, "nor by flight;"),
        (18, 18, "for"),
        (19, 22, "will go before"),
        (23, 24, "the Lord"),
        (25, 27, "you,"),
        (28, 32, "and shall be the rearward"),
        (33, 34, "the God"),
        (35, 36, "of Israel"),
        (37, 39, "for you."),
    ],
    43: [
        (0, 0, "Behold,"),
        (1, 7, "shall deal prudently"),
        (8, 9, "my servant;"),
        (10, 13, "he shall be exalted"),
        (14, 17, "and extolled"),
        (18, 24, "and be very high."),
    ],
    44: [
        (0, 3, "As many"),
        (4, 5, "were astonished"),
        (6, 8, "at thee—"),
        (9, 11, "his visage"),
        (12, 13, "was marred,"),
        (14, 17, "more than"),
        (18, 20, "any man,"),
        (21, 23, "and his form"),
        (24, 27, "more than"),
        (28, 29, "the sons"),
        (30, 31, "of men—"),
    ],
    45: [
        (0, 4, "So shall it be"),
        (5, 7, "he shall sprinkle"),
        (8, 10, "many nations;"),
        (11, 14, "shall shut"),
        (15, 16, "the kings"),
        (17, 19, "their mouths"),
        (20, 22, "at him,"),
        (23, 23, "for"),
        (24, 28, "they shall see"),
        (29, 30, "that which"),
        (31, 34, "had not been told"),
        (35, 38, "them;"),
        (39, 44, "and they shall consider"),
        (45, 46, "that which"),
        (47, 52, "they had not heard."),
    ],
    46: [
        (0, 1, "Verily,"),
        (2, 3, "verily,"),
        (4, 7, "I say"),
        (8, 10, "unto you,"),
        (11, 14, "all these things"),
        (15, 18, "shall surely"),
        (19, 21, "come to pass,"),
        (22, 24, "even as"),
        (25, 28, "hath commanded me"),
        (29, 31, "the Father."),
        (32, 35, "Then shall be fulfilled"),
        (36, 39, "this covenant which"),
        (40, 42, "hath covenanted"),
        (43, 44, "the Father"),
        (45, 47, "with his people;"),
        (48, 53, "and then shall again be inhabited"),
        (54, 55, "Jerusalem"),
        (56, 58, "with my people,"),
        (59, 64, "and it shall become"),
        (65, 65, "the land"),
        (66, 69, "of their inheritance."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
