"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 46 — Amalickiah seeks
to be king; Moroni raises the Title of Liberty and rallies the people by
covenant; the people flock to the standard; Amalickiah flees with a few to the
Lamanites; the men of Amalickiah are pursued and made to covenant peace or slain;
the land is at peace for a time.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits done up front against bom_books.json:
  v12 `luga—Mo`, v12 `fanau—ma`, v17 `saute—O`, v24 `ia—E`,
  v29 `Amalekiā—ma`, v31 `filemu—ma`, v40 `tausaga—ae`

    python3 build_overrides_alma46.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 46

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 8, "as many as"),
        (9, 12, "would not hearken"),
        (13, 15, "to the words of"),
        (16, 16, "Helaman"),
        (17, 19, "and his brethren"),
        (20, 22, "were gathered together"),
        (23, 25, "to oppose"),
        (26, 29, "their brethren."),
    ],
    2: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 7, "they were exceedingly angry,"),
        (8, 11, "insomuch that"),
        (12, 13, "they desired"),
        (14, 15, "to slay"),
        (16, 17, "them."),
    ],
    3: [
        (0, 1, "Now"),
        (2, 4, "the leader"),
        (5, 7, "of them"),
        (8, 11, "who were angry"),
        (12, 14, "against"),
        (15, 17, "their brethren"),
        (18, 20, "was a man"),
        (21, 22, "large of body"),
        (23, 25, "and strong;"),
        (26, 29, "and his name"),
        (30, 31, "was Amalickiah."),
    ],
    4: [
        (0, 3, "And Amalickiah desired"),
        (4, 7, "that he become"),
        (8, 9, "a king;"),
        (10, 13, "and these people"),
        (14, 17, "who were angry"),
        (18, 21, "they also desired"),
        (22, 25, "that he become"),
        (26, 29, "their king;"),
        (30, 33, "and the greater part"),
        (34, 36, "of them"),
        (37, 39, "were the lower judges"),
        (40, 42, "of the land,"),
        (43, 46, "and they sought"),
        (47, 49, "for power."),
    ],
    5: [
        (0, 4, "And they were led"),
        (5, 8, "by the flattering words of"),
        (9, 9, "Amalickiah,"),
        (10, 11, "that"),
        (12, 15, "if they would support"),
        (16, 17, "him"),
        (18, 21, "and set him up"),
        (22, 24, "to become"),
        (25, 27, "their king"),
        (28, 32, "he would make"),
        (33, 34, "them"),
        (35, 36, "rulers"),
        (37, 39, "over"),
        (40, 41, "the people."),
    ],
    6: [
        (0, 5, "And thus they were led away"),
        (6, 7, "by Amalickiah"),
        (8, 10, "into dissension,"),
        (11, 14, "notwithstanding"),
        (15, 16, "the preaching"),
        (17, 18, "of Helaman"),
        (19, 21, "and his brethren,"),
        (22, 22, "yea,"),
        (23, 26, "notwithstanding"),
        (27, 31, "their exceedingly great care"),
        (32, 35, "in the watching over"),
        (36, 37, "the church,"),
        (38, 41, "for they were"),
        (42, 44, "high priests"),
        (45, 47, "of the church."),
    ],
    7: [
        (0, 3, "And there were"),
        (4, 5, "many"),
        (6, 8, "in the church"),
        (9, 12, "who believed"),
        (13, 16, "in the flattering words of"),
        (17, 17, "Amalickiah,"),
        (18, 21, "wherefore"),
        (22, 27, "they dissented"),
        (28, 30, "from the church;"),
        (31, 34, "and thus were"),
        (35, 39, "critical and very dangerous"),
        (40, 41, "the affairs of"),
        (42, 45, "the people of Nephi,"),
        (46, 48, "notwithstanding"),
        (49, 52, "their great victory"),
        (53, 55, "over"),
        (56, 57, "the Lamanites,"),
        (58, 62, "and their great joy"),
        (63, 64, "which was had"),
        (65, 66, "because of"),
        (67, 68, "the deliverance"),
        (69, 71, "of them"),
        (72, 75, "by the hand of"),
        (76, 77, "the Lord."),
    ],
    8: [
        (0, 5, "Thus we see"),
        (6, 9, "how quickly"),
        (10, 11, "do forget"),
        (12, 15, "the children of"),
        (16, 16, "men"),
        (17, 19, "the Lord"),
        (20, 22, "their God,"),
        (23, 23, "yea,"),
        (24, 26, "how quickly"),
        (27, 28, "to do"),
        (29, 31, "iniquity,"),
        (32, 33, "and to be led away"),
        (34, 37, "by the wicked one."),
    ],
    9: [
        (0, 0, "Yea,"),
        (1, 6, "and we also see"),
        (7, 10, "the great wickedness"),
        (11, 13, "which can"),
        (14, 16, "a wicked man"),
        (17, 18, "one alone"),
        (19, 20, "cause to arise"),
        (21, 23, "among"),
        (24, 27, "the children of men."),
    ],
    10: [
        (0, 0, "Yea,"),
        (1, 3, "we see"),
        (4, 5, "that Amalickiah,"),
        (6, 8, "because he"),
        (9, 11, "was a man"),
        (12, 14, "of wicked cunning craft"),
        (15, 18, "and a man"),
        (19, 21, "of many flattering words,"),
        (22, 26, "he led away"),
        (27, 28, "the hearts of"),
        (29, 31, "many people"),
        (32, 33, "to do"),
        (34, 35, "wickedness;"),
        (36, 36, "yea,"),
        (37, 38, "and to seek"),
        (39, 40, "to destroy"),
        (41, 42, "the church"),
        (43, 45, "of God,"),
        (46, 47, "and to destroy"),
        (48, 50, "the foundation of"),
        (51, 52, "liberty"),
        (53, 56, "which was granted"),
        (57, 59, "by God"),
        (60, 63, "unto them,"),
        (64, 67, "or a blessing"),
        (68, 71, "which was sent"),
        (72, 74, "by God"),
        (75, 77, "upon"),
        (78, 79, "the land"),
        (80, 82, "for the benefit"),
        (83, 86, "of the righteous."),
    ],
    11: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 7, "when had heard"),
        (8, 8, "Moroni,"),
        (9, 13, "who was"),
        (14, 15, "chief commander"),
        (16, 18, "of the armies of"),
        (19, 20, "the Nephites,"),
        (21, 23, "of these dissensions,"),
        (24, 27, "he was angry"),
        (28, 29, "with Amalickiah."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 6, "he rent"),
        (7, 8, "his coat;"),
        (9, 12, "and he took"),
        (13, 14, "a piece,"),
        (15, 18, "and he wrote"),
        (19, 20, "upon it—"),
        (21, 23, "In remembrance"),
        (24, 27, "of our God,"),
        (28, 31, "and our worship,"),
        (32, 34, "and liberty,"),
        (35, 38, "and our peace,"),
        (39, 41, "our wives,"),
        (42, 45, "and our children—"),
        (46, 49, "and he tied it"),
        (50, 52, "upon"),
        (53, 54, "the end"),
        (55, 57, "of a pole."),
    ],
    13: [
        (0, 3, "And he put on"),
        (4, 5, "his head-plate,"),
        (6, 8, "and his breastplate,"),
        (9, 11, "and his shields,"),
        (12, 13, "and girded on"),
        (14, 15, "his armor"),
        (16, 17, "around"),
        (18, 19, "his loins;"),
        (20, 23, "and he took"),
        (24, 25, "the pole,"),
        (26, 29, "which had"),
        (30, 32, "on its end"),
        (33, 34, "his coat"),
        (35, 36, "which was rent,"),
        (37, 40, "(and he named"),
        (41, 44, "the standard of"),
        (45, 46, "liberty)"),
        (47, 49, "and bowed"),
        (50, 52, "himself"),
        (53, 55, "to the ground,"),
        (56, 60, "and prayed earnestly"),
        (61, 63, "unto his God"),
        (64, 66, "for the blessings of"),
        (67, 68, "liberty"),
        (69, 72, "to be upon"),
        (73, 74, "his brethren,"),
        (75, 76, "as long as"),
        (77, 80, "there still be"),
        (81, 83, "a group of"),
        (84, 85, "Christian people"),
        (86, 87, "who remain"),
        (88, 90, "to hold for"),
        (91, 92, "themselves"),
        (93, 94, "the land—"),
    ],
    14: [
        (0, 4, "For thus were named"),
        (5, 7, "all the people"),
        (8, 10, "who truly believed"),
        (11, 12, "in Christ,"),
        (13, 16, "who belonged"),
        (17, 19, "to the church"),
        (20, 22, "of God,"),
        (23, 25, "by them"),
        (26, 30, "who did not belong"),
        (31, 33, "to the church."),
    ],
    15: [
        (0, 3, "And those"),
        (4, 7, "who belonged"),
        (8, 10, "to the church"),
        (11, 12, "were faithful;"),
        (13, 13, "yea,"),
        (14, 17, "all of them"),
        (18, 22, "who truly believed"),
        (23, 24, "in Christ"),
        (25, 27, "they took"),
        (28, 30, "gladly"),
        (31, 34, "upon themselves"),
        (35, 37, "the name of"),
        (38, 38, "Christ,"),
        (39, 40, "or"),
        (41, 43, "the Christians"),
        (44, 49, "even as were called"),
        (50, 51, "them,"),
        (52, 53, "because of"),
        (54, 56, "their belief"),
        (57, 58, "in Christ"),
        (59, 60, "who"),
        (61, 65, "should come."),
    ],
    16: [
        (0, 2, "Therefore,"),
        (3, 6, "prayed"),
        (7, 7, "Moroni,"),
        (8, 11, "at that time,"),
        (12, 16, "that might be favored"),
        (17, 19, "the cause of"),
        (20, 22, "the Christians,"),
        (23, 26, "and the liberty of"),
        (27, 28, "the land."),
    ],
    17: [
        (0, 3, "And it came to pass that"),
        (4, 7, "when he had given up"),
        (8, 9, "his soul"),
        (10, 12, "to God,"),
        (13, 15, "he named"),
        (16, 18, "the whole land"),
        (19, 19, "which"),
        (20, 21, "was on"),
        (22, 25, "the south side"),
        (26, 29, "of the land of"),
        (30, 30, "Desolation,"),
        (31, 31, "yea,"),
        (32, 35, "and in summary,"),
        (36, 38, "the whole land"),
        (39, 39, "which,"),
        (40, 42, "all the north"),
        (43, 44, "and south—"),
        (45, 47, "A land"),
        (48, 48, "chosen,"),
        (49, 52, "and the land of"),
        (53, 54, "liberty."),
    ],
    18: [
        (0, 4, "And he said:"),
        (5, 6, "Surely"),
        (7, 12, "will not allow"),
        (13, 15, "God"),
        (16, 17, "us,"),
        (18, 21, "who are hated"),
        (22, 25, "because we have taken"),
        (26, 29, "upon ourselves"),
        (30, 32, "the name of"),
        (33, 33, "Christ,"),
        (34, 37, "that we be trodden"),
        (38, 39, "down"),
        (40, 41, "and destroyed,"),
        (42, 43, "except"),
        (44, 46, "we bring it"),
        (47, 50, "upon ourselves"),
        (51, 53, "by way of"),
        (54, 56, "our own transgressions."),
    ],
    19: [
        (0, 6, "And when had said"),
        (7, 8, "Moroni"),
        (9, 11, "these words,"),
        (12, 15, "he went forth"),
        (16, 18, "among"),
        (19, 20, "the people,"),
        (21, 23, "waving"),
        (24, 26, "in the air"),
        (27, 29, "the part of"),
        (30, 31, "his coat"),
        (32, 33, "which was rent,"),
        (34, 36, "that might"),
        (37, 39, "all men"),
        (40, 41, "see"),
        (42, 43, "the writing"),
        (44, 47, "which he had written"),
        (48, 50, "upon"),
        (51, 53, "the part of"),
        (54, 57, "the rent coat,"),
        (58, 60, "and crying out"),
        (61, 64, "with a loud voice,"),
        (65, 66, "thus:"),
    ],
    20: [
        (0, 0, "Behold,"),
        (1, 3, "whosoever"),
        (4, 5, "desires"),
        (6, 7, "to maintain"),
        (8, 9, "this standard"),
        (10, 12, "upon"),
        (13, 14, "the land,"),
        (15, 18, "let them come"),
        (19, 20, "forward"),
        (21, 24, "in the strength of"),
        (25, 26, "the Lord,"),
        (27, 29, "and enter"),
        (30, 32, "into a covenant"),
        (33, 37, "that they will maintain"),
        (38, 40, "their rights,"),
        (41, 44, "and their worship,"),
        (45, 47, "that may bless"),
        (48, 49, "them"),
        (50, 52, "the Lord"),
        (53, 54, "God."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 8, "when had proclaimed"),
        (9, 10, "Moroni"),
        (11, 13, "these words,"),
        (14, 14, "behold,"),
        (15, 18, "ran together"),
        (19, 20, "the people"),
        (21, 24, "with their armor"),
        (25, 27, "girded around"),
        (28, 31, "about their loins,"),
        (32, 33, "rending"),
        (34, 36, "their garments"),
        (37, 40, "as a sign,"),
        (41, 44, "or a covenant,"),
        (45, 51, "that they would not forsake"),
        (52, 53, "the Lord"),
        (54, 56, "their God;"),
        (57, 58, "or thus,"),
        (59, 62, "if they transgress"),
        (63, 64, "the commandments of"),
        (65, 66, "God,"),
        (67, 69, "or fall"),
        (70, 72, "into transgression,"),
        (73, 74, "and be ashamed"),
        (75, 76, "to take"),
        (77, 80, "upon themselves"),
        (81, 83, "the name of"),
        (84, 84, "Christ,"),
        (85, 87, "the Lord"),
        (88, 90, "should rend"),
        (91, 92, "them"),
        (93, 96, "even as"),
        (97, 98, "they rent"),
        (99, 101, "their garments."),
    ],
    22: [
        (0, 1, "Now"),
        (2, 5, "this is the covenant"),
        (6, 8, "which they made,"),
        (9, 13, "and they cast"),
        (14, 16, "their garments"),
        (17, 19, "at the feet of"),
        (20, 20, "Moroni,"),
        (21, 23, "saying:"),
        (24, 27, "We make a covenant"),
        (28, 31, "with our God,"),
        (32, 33, "that be destroyed"),
        (34, 35, "we,"),
        (36, 39, "even as"),
        (40, 42, "our brethren"),
        (43, 45, "in the land"),
        (46, 47, "northward,"),
        (48, 53, "if we fall"),
        (54, 56, "into transgression;"),
        (57, 57, "yea,"),
        (58, 61, "let him cast"),
        (62, 63, "us"),
        (64, 66, "at the feet of"),
        (67, 69, "our enemies,"),
        (70, 73, "even as"),
        (74, 76, "we cast"),
        (77, 79, "our garments"),
        (80, 82, "at thy feet"),
        (83, 86, "to be trodden down"),
        (87, 88, "by feet,"),
        (89, 94, "if we fall"),
        (95, 97, "into transgression."),
    ],
    23: [
        (0, 2, "Said"),
        (3, 3, "Moroni"),
        (4, 7, "unto them:"),
        (8, 8, "Behold,"),
        (9, 11, "we are"),
        (12, 16, "a remaining part"),
        (17, 20, "of the seed of"),
        (21, 21, "Jacob;"),
        (22, 22, "yea,"),
        (23, 25, "we are"),
        (26, 30, "a remaining part"),
        (31, 34, "of the seed of"),
        (35, 35, "Joseph,"),
        (36, 39, "whose"),
        (40, 41, "coat"),
        (42, 43, "was rent"),
        (44, 46, "by his brethren"),
        (47, 50, "into pieces"),
        (51, 52, "many;"),
        (53, 53, "yea,"),
        (54, 56, "and now"),
        (57, 57, "behold,"),
        (58, 60, "let us remember"),
        (61, 63, "to keep"),
        (64, 65, "the commandments of"),
        (66, 67, "God,"),
        (68, 69, "otherwise"),
        (70, 73, "shall be rent"),
        (74, 76, "our garments"),
        (77, 80, "by our brethren,"),
        (81, 84, "and we be cast"),
        (85, 87, "into prison,"),
        (88, 92, "or we be sold,"),
        (93, 94, "or be slain."),
    ],
    24: [
        (0, 0, "Yea,"),
        (1, 3, "let us preserve"),
        (4, 6, "our liberty"),
        (7, 11, "as a remaining part"),
        (12, 13, "of Joseph;"),
        (14, 14, "yea,"),
        (15, 17, "let us remember"),
        (18, 19, "the words of"),
        (20, 20, "Jacob,"),
        (21, 25, "before he died,"),
        (26, 27, "for behold,"),
        (28, 31, "he saw"),
        (32, 33, "was preserved"),
        (34, 36, "a part of"),
        (37, 38, "the remnant"),
        (39, 42, "of the coat of"),
        (43, 43, "Joseph"),
        (44, 47, "and had not rotted."),
        (48, 53, "And he said—"),
        (54, 57, "Even as was preserved"),
        (58, 60, "this remnant of"),
        (61, 62, "the coat"),
        (63, 65, "of my son,"),
        (66, 72, "so likewise shall be preserved"),
        (73, 76, "by the hand of"),
        (77, 78, "God"),
        (79, 82, "a remaining part"),
        (83, 86, "of the seed of"),
        (87, 88, "my son,"),
        (89, 91, "and be taken"),
        (92, 94, "unto himself,"),
        (95, 95, "while"),
        (96, 99, "the remaining part"),
        (100, 103, "of the seed of"),
        (104, 104, "Joseph"),
        (105, 108, "shall perish,"),
        (109, 112, "even as"),
        (113, 116, "the remaining part"),
        (117, 119, "of his coat."),
    ],
    25: [
        (0, 1, "Now"),
        (2, 2, "behold,"),
        (3, 5, "brings"),
        (6, 7, "this thing"),
        (8, 9, "sorrow"),
        (10, 12, "to my soul;"),
        (13, 16, "nevertheless,"),
        (17, 18, "rejoiceth"),
        (19, 20, "my soul"),
        (21, 23, "in my son,"),
        (24, 25, "because of"),
        (26, 28, "that part of"),
        (29, 30, "his seed"),
        (31, 36, "which shall be given"),
        (37, 39, "unto God."),
    ],
    26: [
        (0, 1, "Now"),
        (2, 2, "behold,"),
        (3, 6, "this is the language"),
        (7, 8, "of Jacob."),
    ],
    27: [
        (0, 2, "And now"),
        (3, 7, "who knows"),
        (8, 8, "but"),
        (9, 12, "the remaining part"),
        (13, 16, "of the seed of"),
        (17, 17, "Joseph,"),
        (18, 22, "which shall perish"),
        (23, 25, "like"),
        (26, 27, "his coat,"),
        (28, 31, "are these"),
        (32, 36, "who have dissented"),
        (37, 40, "from us?"),
        (41, 41, "Yea,"),
        (42, 45, "and it may be us"),
        (46, 47, "also,"),
        (48, 54, "if we do not stand steadfast"),
        (55, 57, "in the faith"),
        (58, 59, "in Christ."),
    ],
    28: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 10, "when had said"),
        (11, 12, "Moroni"),
        (13, 14, "these words"),
        (15, 19, "he went forth,"),
        (20, 23, "and also sent"),
        (24, 25, "messengers"),
        (26, 29, "into all parts of"),
        (30, 31, "the land"),
        (32, 34, "where were"),
        (35, 35, "dissensions,"),
        (36, 38, "and gathered together"),
        (39, 40, "all the people"),
        (41, 44, "who desired"),
        (45, 46, "to maintain"),
        (47, 49, "their liberty,"),
        (50, 51, "to stand"),
        (52, 55, "to oppose"),
        (56, 57, "Amalickiah"),
        (58, 60, "and those"),
        (61, 64, "who had dissented,"),
        (65, 68, "who were called"),
        (69, 71, "the Amalickiahites."),
    ],
    29: [
        (0, 3, "And it came to pass that"),
        (4, 5, "when saw"),
        (6, 6, "Amalickiah"),
        (7, 11, "were more numerous"),
        (12, 14, "the people of Moroni"),
        (15, 16, "than"),
        (17, 18, "the Amalickiahites—"),
        (19, 23, "and he also saw"),
        (24, 25, "were doubtful"),
        (26, 27, "his people"),
        (28, 30, "concerning"),
        (31, 32, "the rightness"),
        (33, 35, "of the cause"),
        (36, 38, "which they had made—"),
        (39, 40, "therefore,"),
        (41, 43, "in fear"),
        (44, 44, "lest"),
        (45, 47, "he not obtain"),
        (48, 49, "the objective,"),
        (50, 53, "he took"),
        (54, 55, "them"),
        (56, 58, "of his people"),
        (59, 62, "who were willing"),
        (63, 64, "to it,"),
        (65, 69, "and departed"),
        (70, 73, "into the land of"),
        (74, 74, "Nephi."),
    ],
    30: [
        (0, 1, "Now"),
        (2, 4, "Moroni thought"),
        (5, 8, "it was not right that"),
        (9, 10, "should gain more"),
        (11, 13, "the Lamanites"),
        (14, 16, "increased strength;"),
        (17, 18, "therefore"),
        (19, 23, "he thought"),
        (24, 26, "to cut off"),
        (27, 29, "the people of Amalickiah,"),
        (30, 31, "or to seize"),
        (32, 33, "them"),
        (34, 36, "and bring back"),
        (37, 38, "them,"),
        (39, 41, "and to slay"),
        (42, 42, "Amalickiah;"),
        (43, 43, "yea,"),
        (44, 47, "for he knew"),
        (48, 52, "that he would stir up"),
        (53, 54, "the Lamanites"),
        (55, 56, "to anger"),
        (57, 59, "against"),
        (60, 63, "them,"),
        (64, 65, "and urge"),
        (66, 67, "them"),
        (68, 70, "to come"),
        (71, 74, "to fight against"),
        (75, 78, "them;"),
        (79, 83, "and he knew"),
        (84, 87, "would do"),
        (88, 89, "Amalickiah"),
        (90, 91, "this thing"),
        (92, 98, "that he might obtain"),
        (99, 101, "his purposes."),
    ],
    31: [
        (0, 1, "Therefore"),
        (2, 5, "Moroni thought"),
        (6, 8, "it was necessary that"),
        (9, 10, "he take"),
        (11, 13, "his armies,"),
        (14, 15, "who"),
        (16, 19, "had gathered together"),
        (20, 22, "themselves,"),
        (23, 25, "and had armed"),
        (26, 28, "themselves,"),
        (29, 32, "and had entered"),
        (33, 35, "into a covenant"),
        (36, 37, "to keep"),
        (38, 39, "the peace—"),
        (40, 43, "and it came to pass that"),
        (44, 46, "he took"),
        (47, 48, "his army"),
        (49, 51, "and marched"),
        (52, 53, "out"),
        (54, 55, "together with"),
        (56, 57, "his tents"),
        (58, 60, "into the wilderness,"),
        (61, 62, "to block"),
        (63, 64, "the path"),
        (65, 66, "of Amalickiah"),
        (67, 69, "in the wilderness."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 6, "he did"),
        (7, 9, "according to"),
        (10, 11, "his desires,"),
        (12, 14, "and marched"),
        (15, 17, "into the wilderness,"),
        (18, 19, "and went ahead"),
        (20, 22, "to intercept"),
        (23, 25, "the armies of Amalickiah."),
    ],
    33: [
        (0, 3, "And it came to pass that"),
        (4, 5, "Amalickiah fled"),
        (6, 9, "with a small part"),
        (10, 12, "of his men,"),
        (13, 17, "and those who remained"),
        (18, 20, "were delivered"),
        (21, 23, "into the hands of"),
        (24, 24, "Moroni"),
        (25, 29, "and were brought back"),
        (30, 33, "into the land of"),
        (34, 34, "Zarahemla."),
    ],
    34: [
        (0, 1, "Now,"),
        (2, 3, "because"),
        (4, 4, "Moroni"),
        (5, 7, "was a man"),
        (8, 11, "who was appointed"),
        (12, 14, "by the chief judge"),
        (15, 18, "and the voice of"),
        (19, 20, "the people,"),
        (21, 22, "therefore"),
        (23, 28, "he had"),
        (29, 30, "the power"),
        (31, 33, "to do"),
        (34, 36, "anything"),
        (37, 39, "according to"),
        (40, 41, "the thing"),
        (42, 45, "which he willed,"),
        (46, 48, "with the armies of"),
        (49, 50, "the Nephites,"),
        (51, 52, "to establish"),
        (53, 55, "and to carry out"),
        (56, 57, "the authority"),
        (58, 60, "over"),
        (61, 62, "them."),
    ],
    35: [
        (0, 3, "And it came to pass that"),
        (4, 8, "whosoever of"),
        (9, 10, "the Amalickiahites"),
        (11, 13, "who would not"),
        (14, 15, "make a covenant"),
        (16, 17, "to support"),
        (18, 19, "the cause"),
        (20, 22, "of liberty,"),
        (23, 27, "that they might"),
        (28, 29, "keep"),
        (30, 32, "a free government,"),
        (33, 35, "he commanded"),
        (36, 38, "that they be slain;"),
        (39, 43, "and few were they"),
        (44, 45, "who denied"),
        (46, 47, "the covenant"),
        (48, 50, "of liberty."),
    ],
    36: [
        (0, 4, "And it came to pass also that"),
        (5, 8, "he commanded,"),
        (9, 11, "to be raised"),
        (12, 13, "up"),
        (14, 16, "the standard of"),
        (17, 18, "liberty"),
        (19, 21, "on all the towers"),
        (22, 23, "which were in"),
        (24, 26, "the whole land,"),
        (27, 30, "which belonged to"),
        (31, 32, "the Nephites;"),
        (33, 37, "and thus set up"),
        (38, 39, "Moroni"),
        (40, 42, "the standard of"),
        (43, 44, "liberty"),
        (45, 47, "among"),
        (48, 49, "the Nephites."),
    ],
    37: [
        (0, 4, "And they began to"),
        (5, 6, "have again"),
        (7, 9, "peace"),
        (10, 12, "in the land;"),
        (13, 17, "and thus they"),
        (18, 18, "kept"),
        (19, 21, "peace"),
        (22, 24, "in the land"),
        (25, 28, "until almost reaching"),
        (29, 31, "the end"),
        (32, 36, "of the nineteenth"),
        (37, 38, "year"),
        (39, 43, "of the reign of the judges."),
    ],
    38: [
        (0, 3, "And also maintained"),
        (4, 5, "Helaman"),
        (6, 8, "and the high priests"),
        (9, 10, "order"),
        (11, 13, "in the church;"),
        (14, 14, "yea,"),
        (15, 19, "insomuch that they"),
        (20, 20, "had"),
        (21, 23, "great peace"),
        (24, 26, "and joy"),
        (27, 29, "in the church"),
        (30, 33, "in the space of"),
        (34, 36, "the four years."),
    ],
    39: [
        (0, 3, "And it came to pass that"),
        (4, 4, "died"),
        (5, 6, "many,"),
        (7, 10, "with firm belief"),
        (11, 12, "were redeemed"),
        (13, 15, "their souls"),
        (16, 18, "by the Lord"),
        (19, 21, "Jesus Christ;"),
        (22, 23, "therefore"),
        (24, 27, "they left"),
        (28, 29, "the world"),
        (30, 32, "with joy."),
    ],
    40: [
        (0, 3, "And there were"),
        (4, 5, "some"),
        (6, 9, "who died"),
        (10, 11, "with fevers,"),
        (12, 16, "which were commonly widespread"),
        (17, 19, "in the land"),
        (20, 24, "at some seasons of"),
        (25, 26, "the year—"),
        (27, 31, "but not so very many"),
        (32, 33, "died"),
        (34, 35, "with fevers,"),
        (36, 37, "because of"),
        (38, 40, "the excellent usefulness"),
        (41, 44, "of the many"),
        (45, 47, "plants and roots"),
        (48, 49, "which were prepared"),
        (50, 52, "by God"),
        (53, 55, "to take away"),
        (56, 59, "the cause of diseases,"),
        (60, 63, "which afflicted"),
        (64, 64, "men"),
        (65, 66, "because of"),
        (67, 69, "the nature of"),
        (70, 71, "the climate—"),
    ],
    41: [
        (0, 2, "But many"),
        (3, 5, "who died"),
        (6, 8, "because were long"),
        (9, 11, "their lives;"),
        (12, 15, "and those"),
        (16, 19, "who died"),
        (20, 22, "with faith"),
        (23, 24, "in Christ"),
        (25, 26, "are happy"),
        (27, 29, "in him,"),
        (30, 35, "as we must"),
        (36, 38, "suppose it."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
