"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 62 — Moroni marches to
Pahoran's aid, joins forces and puts down the king-men, executing Pachus and the
rebel leaders; the combined armies retake Nephihah and the other cities, drive
out the Lamanites, and Ammoron is slain; the war ends, Moroni yields the command
to Moronihah and retires, Helaman returns to the ministry, and there is peace.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_alma62.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 62

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 7, "had received"),
        (8, 9, "Moroni"),
        (10, 11, "this epistle"),
        (12, 15, "his heart did take courage,"),
        (16, 18, "and was filled"),
        (19, 23, "with exceeding great joy"),
        (24, 25, "because of"),
        (26, 28, "the faithfulness of"),
        (29, 29, "Pahoran,"),
        (30, 30, "that"),
        (31, 38, "he was not also a traitor"),
        (39, 41, "to the freedom"),
        (42, 45, "and the cause of"),
        (46, 47, "his country."),
    ],
    2: [
        (0, 5, "But he did also mourn exceedingly"),
        (6, 7, "because of"),
        (8, 10, "the iniquity of"),
        (11, 12, "them"),
        (13, 16, "who drove out"),
        (17, 17, "Pahoran"),
        (18, 20, "from the judgment-seat,"),
        (21, 21, "yea,"),
        (22, 24, "in short,"),
        (25, 28, "because of those"),
        (29, 32, "who rebelled"),
        (33, 34, "against"),
        (35, 37, "their country"),
        (38, 42, "and also their God."),
    ],
    3: [
        (0, 3, "And it came to pass that"),
        (4, 6, "Moroni took"),
        (7, 10, "a small number of"),
        (11, 12, "his men,"),
        (13, 15, "according to"),
        (16, 19, "the desire of"),
        (20, 20, "Pahoran,"),
        (21, 23, "and gave"),
        (24, 27, "unto Lehi and Teancum"),
        (28, 29, "the command"),
        (30, 32, "over"),
        (33, 36, "those remaining of"),
        (37, 38, "his army,"),
        (39, 42, "and took his march"),
        (43, 45, "toward"),
        (46, 48, "the land of"),
        (49, 49, "Gideon."),
    ],
    4: [
        (0, 3, "And he raised"),
        (4, 6, "the standard of"),
        (7, 8, "liberty"),
        (9, 12, "in whatever place"),
        (13, 18, "he entered into,"),
        (19, 22, "and gathered"),
        (23, 25, "whatever army"),
        (26, 30, "he was able to obtain"),
        (31, 34, "in all his march"),
        (35, 37, "toward"),
        (38, 40, "the land of"),
        (41, 41, "Gideon."),
    ],
    5: [
        (0, 3, "And it came to pass that"),
        (4, 5, "flocked"),
        (6, 9, "the thousands"),
        (10, 12, "unto his standard,"),
        (13, 16, "and they took up"),
        (17, 19, "their swords"),
        (20, 23, "in the defence of"),
        (24, 26, "their freedom,"),
        (27, 31, "that they might not"),
        (32, 34, "they go"),
        (35, 37, "into bondage."),
    ],
    6: [
        (0, 2, "And thus,"),
        (3, 6, "when had finished"),
        (7, 8, "gathering together"),
        (9, 10, "by Moroni"),
        (11, 12, "men"),
        (13, 17, "he was able to obtain"),
        (18, 21, "in all his march,"),
        (22, 26, "he then arrived"),
        (27, 30, "to the land of"),
        (31, 31, "Gideon;"),
        (32, 35, "and when he united"),
        (36, 37, "his armies"),
        (38, 40, "with the armies of"),
        (41, 41, "Pahoran,"),
        (42, 44, "insomuch that"),
        (45, 48, "they were very strong,"),
        (49, 53, "were mightier"),
        (54, 57, "even than"),
        (58, 60, "the men of"),
        (61, 61, "Pachus,"),
        (62, 63, "who"),
        (64, 67, "was the king of"),
        (68, 71, "those dissenters"),
        (72, 75, "who drove out"),
        (76, 76, "the freemen"),
        (77, 80, "of the land of"),
        (81, 81, "Zarahemla"),
        (82, 87, "and made theirs"),
        (88, 89, "the land."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 5, "went down"),
        (6, 8, "Moroni and Pahoran"),
        (9, 12, "with their armies"),
        (13, 16, "into the land of"),
        (17, 17, "Zarahemla,"),
        (18, 20, "and went forth"),
        (21, 23, "against"),
        (24, 25, "the city,"),
        (26, 29, "and met with"),
        (30, 31, "the men of"),
        (32, 32, "Pachus,"),
        (33, 36, "which caused"),
        (37, 40, "they fought."),
    ],
    8: [
        (0, 1, "And behold,"),
        (2, 3, "was slain"),
        (4, 4, "Pachus"),
        (5, 7, "and were made prisoners"),
        (8, 9, "his men,"),
        (10, 12, "and was restored"),
        (13, 13, "Pahoran"),
        (14, 16, "to his judgment-seat."),
    ],
    9: [
        (0, 2, "And received"),
        (3, 5, "the men of"),
        (6, 6, "Pachus"),
        (7, 9, "their trial,"),
        (10, 12, "according to"),
        (13, 14, "the law,"),
        (15, 18, "and also those king-men"),
        (19, 22, "who were taken"),
        (23, 24, "and cast"),
        (25, 27, "into prison;"),
        (28, 30, "and were slain"),
        (31, 32, "them"),
        (33, 35, "according to"),
        (36, 37, "the law;"),
        (38, 38, "yea,"),
        (39, 42, "those men of"),
        (43, 43, "Pachus"),
        (44, 48, "and whosoever of"),
        (49, 50, "those king-men,"),
        (51, 54, "who refused"),
        (55, 56, "to take up"),
        (57, 59, "weapons of war"),
        (60, 63, "in the defence of"),
        (64, 66, "their country,"),
        (67, 67, "but"),
        (68, 72, "fought against it,"),
        (73, 74, "were put to death."),
    ],
    10: [
        (0, 2, "And thus"),
        (3, 4, "it was necessary"),
        (5, 8, "to strictly keep"),
        (9, 10, "this law"),
        (11, 14, "for the safety of"),
        (15, 17, "their country;"),
        (18, 18, "yea,"),
        (19, 23, "and whosoever"),
        (24, 25, "was found"),
        (26, 27, "denying"),
        (28, 30, "their freedom"),
        (31, 35, "was speedily executed"),
        (36, 39, "according to"),
        (40, 41, "the law."),
    ],
    11: [
        (0, 2, "And thus"),
        (3, 4, "ended"),
        (5, 7, "the year"),
        (8, 9, "thirtieth"),
        (10, 13, "of the reign of"),
        (14, 14, "the judges"),
        (15, 18, "over the people of"),
        (19, 19, "Nephi;"),
        (20, 23, "having restored"),
        (24, 27, "by Moroni and Pahoran"),
        (28, 29, "the peace"),
        (30, 33, "to the land of"),
        (34, 34, "Zarahemla,"),
        (35, 37, "among"),
        (38, 41, "their own people,"),
        (42, 45, "after that"),
        (46, 50, "the inflicting of death"),
        (51, 54, "upon all those"),
        (55, 59, "who were not true"),
        (60, 63, "to the cause of"),
        (64, 65, "freedom."),
    ],
    12: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the commencement of"),
        (7, 8, "the year"),
        (9, 13, "thirty and one"),
        (14, 17, "of the reign of"),
        (18, 18, "the judges"),
        (19, 21, "over"),
        (22, 25, "the people of Nephi,"),
        (26, 30, "quickly commanded"),
        (31, 32, "Moroni"),
        (33, 35, "that should"),
        (36, 37, "be sent"),
        (38, 39, "provisions,"),
        (40, 43, "and also should"),
        (44, 45, "be sent"),
        (46, 49, "an army of men"),
        (50, 52, "six thousand"),
        (53, 54, "unto Helaman,"),
        (55, 56, "to help"),
        (57, 59, "him"),
        (60, 63, "in the preserving of"),
        (64, 66, "that part of"),
        (67, 68, "the land."),
    ],
    13: [
        (0, 5, "And he also caused"),
        (6, 8, "that be sent"),
        (9, 13, "an army of men"),
        (14, 16, "six thousand,"),
        (17, 18, "together with"),
        (19, 22, "a quantity of food"),
        (23, 24, "sufficient,"),
        (25, 27, "to the armies of"),
        (28, 30, "Lehi and Teancum."),
        (31, 34, "And it came to pass that"),
        (35, 37, "this was done"),
        (38, 40, "to strengthen"),
        (41, 42, "the land"),
        (43, 44, "against"),
        (45, 47, "the Lamanites."),
    ],
    14: [
        (0, 3, "And it came to pass that"),
        (4, 4, "left"),
        (5, 8, "by Moroni and Pahoran"),
        (9, 13, "a large body of men"),
        (14, 17, "in the land of"),
        (18, 18, "Zarahemla,"),
        (19, 20, "but went"),
        (21, 23, "their march"),
        (24, 25, "together with"),
        (26, 29, "a great number of men"),
        (30, 33, "toward"),
        (34, 36, "the land of"),
        (37, 37, "Nephihah,"),
        (38, 40, "with determination"),
        (41, 42, "to overthrow"),
        (43, 44, "the Lamanites"),
        (45, 46, "who were in"),
        (47, 48, "that city."),
    ],
    15: [
        (0, 3, "And it came to pass that"),
        (4, 9, "as they were marching"),
        (10, 12, "towards the land,"),
        (13, 15, "they took"),
        (16, 18, "a large number of"),
        (19, 21, "the Lamanite men,"),
        (22, 23, "and slew"),
        (24, 26, "many of"),
        (27, 28, "them,"),
        (29, 30, "and took"),
        (31, 33, "their provisions"),
        (34, 37, "and their weapons"),
        (38, 39, "of war."),
    ],
    16: [
        (0, 3, "And it came to pass that"),
        (4, 8, "after they had taken"),
        (9, 11, "them,"),
        (12, 14, "they commanded"),
        (15, 16, "them"),
        (17, 19, "that they make"),
        (20, 21, "a covenant"),
        (22, 27, "they would never again take up"),
        (28, 30, "their weapons"),
        (31, 32, "of war"),
        (33, 36, "against"),
        (37, 39, "the Nephites."),
    ],
    17: [
        (0, 4, "And when had finished"),
        (5, 6, "they made"),
        (7, 9, "this covenant,"),
        (10, 13, "they sent"),
        (14, 15, "them"),
        (16, 19, "to dwell with"),
        (20, 22, "the people of"),
        (23, 23, "Ammon,"),
        (24, 30, "and they were in number"),
        (31, 35, "who had not been slain"),
        (36, 38, "about"),
        (39, 41, "four thousand."),
    ],
    18: [
        (0, 3, "And it came to pass that"),
        (4, 10, "when they had sent away"),
        (11, 13, "them"),
        (14, 16, "they continued"),
        (17, 19, "their march"),
        (20, 22, "toward"),
        (23, 25, "the land of"),
        (26, 26, "Nephihah."),
        (27, 30, "And it came to pass that"),
        (31, 34, "they arrived"),
        (35, 38, "at the city of"),
        (39, 39, "Nephihah,"),
        (40, 42, "they set up"),
        (43, 45, "their tents"),
        (46, 49, "in the plains of"),
        (50, 50, "Nephihah,"),
        (51, 54, "which was near"),
        (55, 57, "the city of"),
        (58, 58, "Nephihah."),
    ],
    19: [
        (0, 1, "Now"),
        (2, 4, "Moroni desired"),
        (5, 7, "that come out"),
        (8, 9, "the Lamanites"),
        (10, 11, "forth"),
        (12, 13, "to fight"),
        (14, 16, "with them,"),
        (17, 19, "upon"),
        (20, 21, "the plains;"),
        (22, 25, "but because knew"),
        (26, 28, "the Lamanites"),
        (29, 32, "their exceeding courage,"),
        (33, 35, "and they saw"),
        (36, 39, "the great number of"),
        (40, 42, "their host,"),
        (43, 44, "therefore"),
        (45, 48, "they were afraid"),
        (49, 53, "to come out"),
        (54, 56, "against"),
        (57, 60, "them;"),
        (61, 62, "therefore"),
        (63, 68, "they did not come"),
        (69, 70, "to fight"),
        (71, 74, "in that day."),
    ],
    20: [
        (0, 4, "And when came"),
        (5, 6, "the night,"),
        (7, 9, "went forth"),
        (10, 10, "Moroni"),
        (11, 14, "in the darkness of"),
        (15, 16, "the night,"),
        (17, 19, "and went up"),
        (20, 22, "upon"),
        (23, 25, "the top of"),
        (26, 27, "the wall"),
        (28, 29, "to spy out"),
        (30, 33, "which"),
        (34, 36, "part of"),
        (37, 38, "the city"),
        (39, 41, "camped"),
        (42, 43, "the Lamanites"),
        (44, 45, "together with"),
        (46, 48, "their army."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 7, "they were"),
        (8, 12, "on the east side,"),
        (13, 15, "beside"),
        (16, 17, "the gate;"),
        (18, 22, "and they were all asleep."),
        (23, 25, "And now"),
        (26, 29, "returned"),
        (30, 30, "Moroni"),
        (31, 33, "to his army,"),
        (34, 35, "and commanded"),
        (36, 39, "that they quickly prepare"),
        (40, 42, "strong cords"),
        (43, 44, "and ladders,"),
        (45, 49, "to be lowered down"),
        (50, 52, "from the top of"),
        (53, 55, "the wall,"),
        (56, 61, "on the inner side of"),
        (62, 63, "the wall."),
    ],
    22: [
        (0, 3, "And it came to pass that"),
        (4, 6, "Moroni caused"),
        (7, 9, "that march"),
        (10, 11, "his men"),
        (12, 14, "and go up"),
        (15, 20, "upon the top of"),
        (21, 22, "the wall,"),
        (23, 25, "and lower"),
        (26, 28, "themselves"),
        (29, 30, "down"),
        (31, 33, "into"),
        (34, 37, "that part of"),
        (38, 39, "the city,"),
        (40, 40, "yea,"),
        (41, 44, "the very side"),
        (45, 46, "on the west,"),
        (47, 51, "where did not camp"),
        (52, 53, "the Lamanites"),
        (54, 55, "together with"),
        (56, 58, "their armies."),
    ],
    23: [
        (0, 3, "And it came to pass that"),
        (4, 5, "were lowered"),
        (6, 8, "all of them"),
        (9, 10, "down"),
        (11, 13, "into"),
        (14, 15, "the city"),
        (16, 18, "by night,"),
        (19, 24, "by their strong cords"),
        (25, 28, "and their ladders;"),
        (29, 30, "thus"),
        (31, 33, "when dawned"),
        (34, 35, "the morning"),
        (36, 40, "they were all"),
        (41, 43, "within"),
        (44, 45, "the walls of"),
        (46, 47, "the city."),
    ],
    24: [
        (0, 2, "And now,"),
        (3, 6, "when awoke"),
        (7, 8, "the Lamanites"),
        (9, 11, "and saw"),
        (12, 14, "were present"),
        (15, 17, "the armies of Moroni"),
        (18, 20, "within"),
        (21, 21, "the walls,"),
        (22, 25, "they were affrighted exceedingly,"),
        (26, 28, "insomuch that"),
        (29, 32, "they fled out"),
        (33, 35, "through the gate"),
        (36, 39, "the passage"),
        (40, 41, "within."),
    ],
    25: [
        (0, 2, "And now,"),
        (3, 7, "when Moroni saw"),
        (8, 11, "that they fled"),
        (12, 14, "before him,"),
        (15, 17, "he commanded"),
        (18, 20, "that march"),
        (21, 22, "his men"),
        (23, 24, "against"),
        (25, 28, "them,"),
        (29, 30, "and slew"),
        (31, 32, "many,"),
        (33, 34, "and surrounded"),
        (35, 37, "many others,"),
        (38, 42, "and took them prisoners;"),
        (43, 46, "but those"),
        (47, 50, "who remained"),
        (51, 53, "fled"),
        (54, 57, "into the land of"),
        (58, 58, "Moroni,"),
        (59, 62, "which was in the borders"),
        (63, 65, "by the side of"),
        (66, 67, "the seashore."),
    ],
    26: [
        (0, 1, "Thus"),
        (2, 3, "obtained"),
        (4, 7, "by Moroni and Pahoran"),
        (8, 10, "the city of"),
        (11, 11, "Nephihah"),
        (12, 14, "without"),
        (15, 18, "one single person"),
        (19, 20, "lost;"),
        (21, 23, "and many were"),
        (24, 25, "the Lamanites"),
        (26, 29, "who were slain."),
    ],
    27: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 8, "many of"),
        (9, 10, "the Lamanites"),
        (11, 12, "that were prisoners,"),
        (13, 14, "were desirous"),
        (15, 17, "to join with"),
        (18, 20, "the people of"),
        (21, 21, "Ammon"),
        (22, 24, "and become"),
        (25, 26, "a free people."),
    ],
    28: [
        (0, 3, "And it came to pass that"),
        (4, 9, "all those of them"),
        (10, 12, "who so desired,"),
        (13, 15, "was granted"),
        (16, 18, "unto them"),
        (19, 21, "according to"),
        (22, 24, "their desires."),
    ],
    29: [
        (0, 1, "Therefore,"),
        (2, 4, "all the prisoners"),
        (5, 6, "of the Lamanites,"),
        (7, 9, "joined with"),
        (10, 12, "the people of"),
        (13, 13, "Ammon,"),
        (14, 17, "and began to"),
        (18, 20, "they labor mightily,"),
        (21, 24, "in the tilling of"),
        (25, 26, "the ground,"),
        (27, 29, "and planting grain"),
        (30, 33, "of every kind,"),
        (34, 36, "and keeping flocks"),
        (37, 39, "and herds of"),
        (40, 43, "diverse kinds of animals;"),
        (44, 46, "and thus"),
        (47, 49, "were eased"),
        (50, 52, "the Nephites"),
        (53, 56, "from a great burden;"),
        (57, 57, "yea,"),
        (58, 60, "insomuch that"),
        (61, 62, "they were eased"),
        (63, 64, "from the prisoners"),
        (65, 67, "of all the Lamanites."),
    ],
    30: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 8, "after had obtained"),
        (9, 10, "Moroni"),
        (11, 13, "the city of"),
        (14, 14, "Nephihah,"),
        (15, 20, "after he had taken"),
        (21, 24, "many prisoners,"),
        (25, 30, "which greatly reduced"),
        (31, 32, "the armies of"),
        (33, 34, "the Lamanites,"),
        (35, 40, "and when had regained"),
        (41, 43, "many of"),
        (44, 45, "the Nephites"),
        (46, 50, "who had been taken prisoners,"),
        (51, 55, "which greatly strengthened"),
        (56, 58, "the army of"),
        (59, 59, "Moroni;"),
        (60, 61, "therefore"),
        (62, 65, "went forth"),
        (66, 66, "Moroni"),
        (67, 70, "from the land of"),
        (71, 71, "Nephihah"),
        (72, 75, "to the land of"),
        (76, 76, "Lehi."),
    ],
    31: [
        (0, 3, "And it came to pass that"),
        (4, 6, "saw"),
        (7, 8, "the Lamanites"),
        (9, 11, "was coming"),
        (12, 12, "Moroni"),
        (13, 15, "against"),
        (16, 19, "them,"),
        (20, 23, "they were again frightened"),
        (24, 26, "and fled"),
        (27, 29, "from before"),
        (30, 32, "the army of"),
        (33, 33, "Moroni."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 4, "pursued"),
        (5, 6, "them"),
        (7, 11, "by Moroni and his army"),
        (12, 14, "from that city"),
        (15, 17, "to that city,"),
        (18, 20, "until"),
        (21, 23, "they were met"),
        (24, 27, "by Lehi and Teancum;"),
        (28, 31, "and fled"),
        (32, 33, "the Lamanites"),
        (34, 35, "from"),
        (36, 38, "Lehi and Teancum,"),
        (39, 42, "even down to"),
        (43, 46, "upon"),
        (47, 47, "the borders"),
        (48, 50, "by the side of"),
        (51, 52, "the seashore,"),
        (53, 55, "until"),
        (56, 58, "they arrived"),
        (59, 62, "to the land of"),
        (63, 63, "Moroni."),
    ],
    33: [
        (0, 3, "And were gathered together"),
        (4, 6, "all the armies of"),
        (7, 8, "the Lamanites,"),
        (9, 11, "insomuch that"),
        (12, 15, "they were all"),
        (16, 20, "in one body"),
        (21, 24, "in the land of"),
        (25, 25, "Moroni."),
        (26, 27, "Now"),
        (28, 29, "Ammoron,"),
        (30, 32, "the king of"),
        (33, 34, "the Lamanites,"),
        (35, 39, "was also present"),
        (40, 42, "with them."),
    ],
    34: [
        (0, 3, "And it came to pass that"),
        (4, 4, "camped"),
        (5, 9, "Moroni and Lehi and Teancum"),
        (10, 13, "with their armies"),
        (14, 14, "round about"),
        (15, 17, "in the borders of"),
        (18, 20, "the land of"),
        (21, 21, "Moroni,"),
        (22, 24, "insomuch that"),
        (25, 27, "were surrounded"),
        (28, 29, "the Lamanites"),
        (30, 33, "within the borders"),
        (34, 37, "by the side of"),
        (38, 39, "the wilderness"),
        (40, 44, "on the south,"),
        (45, 47, "and in the borders"),
        (48, 51, "by the side of"),
        (52, 53, "the wilderness"),
        (54, 58, "on the east."),
    ],
    35: [
        (0, 2, "And thus"),
        (3, 5, "they camped"),
        (6, 8, "for the night."),
        (9, 10, "For behold,"),
        (11, 13, "were also weary"),
        (14, 15, "the Nephites"),
        (16, 18, "and the Lamanites"),
        (19, 20, "because of"),
        (21, 24, "the greatness of"),
        (25, 26, "the march;"),
        (27, 28, "therefore"),
        (29, 33, "they did not consider"),
        (34, 36, "concerning"),
        (37, 38, "a stratagem"),
        (39, 40, "to be done"),
        (41, 44, "in the time of"),
        (45, 46, "the night,"),
        (47, 48, "except"),
        (49, 49, "Teancum;"),
        (50, 50, "for"),
        (51, 55, "he was very angry"),
        (56, 57, "with Ammoron;"),
        (58, 58, "for"),
        (59, 62, "he supposed,"),
        (63, 64, "Ammoron,"),
        (65, 67, "and his brother"),
        (68, 69, "Amalickiah,"),
        (70, 74, "were the cause of"),
        (75, 77, "this great war"),
        (78, 80, "and long"),
        (81, 84, "between them"),
        (85, 87, "and the Lamanites,"),
        (88, 92, "which caused"),
        (93, 95, "much war"),
        (96, 99, "and bloodshed,"),
        (100, 100, "yea,"),
        (101, 103, "and the famine"),
        (104, 105, "exceeding great."),
    ],
    36: [
        (0, 3, "And it came to pass that"),
        (4, 5, "went forth"),
        (6, 6, "Teancum"),
        (7, 9, "in his anger"),
        (10, 13, "into the camp of"),
        (14, 15, "the Lamanites,"),
        (16, 21, "and lowered himself"),
        (22, 23, "down"),
        (24, 26, "from over"),
        (27, 28, "the walls of"),
        (29, 30, "the city."),
        (31, 36, "And he went"),
        (37, 39, "with a cord,"),
        (40, 42, "from that place"),
        (43, 45, "to that place,"),
        (46, 48, "insomuch that"),
        (49, 50, "he found"),
        (51, 52, "the king;"),
        (53, 56, "and he cast"),
        (57, 58, "at him"),
        (59, 61, "a javelin,"),
        (62, 65, "which pierced"),
        (66, 67, "him"),
        (68, 71, "near the heart."),
        (72, 73, "But behold,"),
        (74, 75, "awoke"),
        (76, 78, "the king"),
        (79, 80, "his servants"),
        (81, 85, "before he died,"),
        (86, 88, "insomuch that"),
        (89, 90, "they pursued"),
        (91, 91, "Teancum,"),
        (92, 93, "and slew"),
        (94, 96, "him."),
    ],
    37: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 6, "knew"),
        (7, 10, "Lehi and Moroni"),
        (11, 12, "was dead"),
        (13, 13, "Teancum,"),
        (14, 18, "they were exceedingly sorrowful;"),
        (19, 20, "for behold,"),
        (21, 25, "he was a man"),
        (26, 30, "who fought faithfully"),
        (31, 33, "for his country,"),
        (34, 34, "yea,"),
        (35, 38, "a true friend"),
        (39, 41, "to liberty;"),
        (42, 45, "and he suffered"),
        (46, 49, "in the many of"),
        (50, 51, "sore afflictions."),
        (52, 53, "But behold,"),
        (54, 57, "he was dead,"),
        (58, 61, "and had gone"),
        (62, 64, "the way of"),
        (65, 68, "all the world."),
    ],
    38: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 6, "marched"),
        (7, 7, "Moroni"),
        (8, 13, "on the next day,"),
        (14, 16, "and came"),
        (17, 19, "upon"),
        (20, 21, "the Lamanites,"),
        (22, 24, "insomuch that"),
        (25, 26, "they slew"),
        (27, 28, "them"),
        (29, 32, "with a great slaughter;"),
        (33, 37, "and they drove out"),
        (38, 39, "them"),
        (40, 42, "from the land;"),
        (43, 47, "and they did flee,"),
        (48, 50, "insomuch that"),
        (51, 55, "they returned no more"),
        (56, 59, "at that time"),
        (60, 62, "against"),
        (63, 65, "the Nephites."),
    ],
    39: [
        (0, 2, "And thus"),
        (3, 4, "ended"),
        (5, 7, "the year"),
        (8, 12, "thirty and one"),
        (13, 16, "of the reign of"),
        (17, 17, "the judges"),
        (18, 21, "over the people of"),
        (22, 22, "Nephi;"),
        (23, 25, "and thus"),
        (26, 30, "came upon them"),
        (31, 32, "wars,"),
        (33, 35, "and bloodsheds,"),
        (36, 37, "and famine,"),
        (38, 39, "and affliction,"),
        (40, 43, "for the space of"),
        (44, 47, "many years."),
    ],
    40: [
        (0, 3, "And there was"),
        (4, 6, "murder,"),
        (7, 8, "and contentions,"),
        (9, 10, "and dissensions,"),
        (11, 14, "and every kind of"),
        (15, 16, "diverse iniquity"),
        (17, 19, "among"),
        (20, 23, "the people of Nephi;"),
        (24, 27, "nevertheless"),
        (28, 31, "for the good of"),
        (32, 33, "the righteous,"),
        (34, 34, "yea,"),
        (35, 36, "because of"),
        (37, 38, "the prayers of"),
        (39, 40, "the righteous,"),
        (41, 44, "they were spared."),
    ],
    41: [
        (0, 1, "But behold,"),
        (2, 3, "because of"),
        (4, 7, "the great length of"),
        (8, 9, "the war"),
        (10, 13, "between"),
        (14, 15, "the Nephites"),
        (16, 18, "and the Lamanites,"),
        (19, 20, "many"),
        (21, 22, "were hardened,"),
        (23, 24, "because of"),
        (25, 29, "the exceeding great length of"),
        (30, 31, "the war;"),
        (32, 34, "but many"),
        (35, 36, "were softened"),
        (37, 38, "because of"),
        (39, 41, "their afflictions,"),
        (42, 44, "insomuch that"),
        (45, 46, "they humbled"),
        (47, 49, "themselves"),
        (50, 52, "before"),
        (53, 54, "God,"),
        (55, 58, "even unto"),
        (59, 61, "the depth of"),
        (62, 63, "humility."),
    ],
    42: [
        (0, 3, "And it came to pass that"),
        (4, 7, "after had fortified"),
        (8, 9, "Moroni"),
        (10, 12, "those parts of"),
        (13, 14, "the land"),
        (15, 20, "which were most near"),
        (21, 23, "to the Lamanites,"),
        (24, 26, "until"),
        (27, 30, "their strength was enough,"),
        (31, 35, "he returned"),
        (36, 39, "to the city of"),
        (40, 40, "Zarahemla;"),
        (41, 46, "and also returned"),
        (47, 47, "Helaman"),
        (48, 51, "to the place of"),
        (52, 53, "his inheritance;"),
        (54, 57, "and was regained"),
        (58, 59, "the peace"),
        (60, 62, "among"),
        (63, 66, "the people of Nephi."),
    ],
    43: [
        (0, 3, "And gave up"),
        (4, 5, "Moroni"),
        (6, 8, "the command over"),
        (9, 10, "his armies"),
        (11, 13, "into the hands of"),
        (14, 15, "his son,"),
        (16, 18, "whose name"),
        (19, 20, "was Moronihah;"),
        (21, 26, "and he retired"),
        (27, 30, "to his own house"),
        (31, 34, "that he may"),
        (35, 36, "he spend"),
        (37, 40, "his remaining days"),
        (41, 43, "in peace."),
    ],
    44: [
        (0, 4, "And returned"),
        (5, 5, "Pahoran"),
        (6, 8, "to his judgment-seat;"),
        (9, 12, "and took again"),
        (13, 14, "Helaman"),
        (15, 18, "upon himself"),
        (19, 21, "to preach"),
        (22, 23, "unto the people"),
        (24, 26, "the word of"),
        (27, 28, "God;"),
        (29, 31, "because"),
        (32, 35, "the exceeding many of"),
        (36, 38, "wars and contentions"),
        (39, 40, "therefore"),
        (41, 43, "it was necessary"),
        (44, 46, "to make again"),
        (47, 49, "a regulation"),
        (50, 52, "in the church."),
    ],
    45: [
        (0, 1, "Therefore,"),
        (2, 5, "went forth"),
        (6, 6, "Helaman"),
        (7, 9, "and his brethren,"),
        (10, 12, "and preached"),
        (13, 15, "the word of"),
        (16, 17, "God"),
        (18, 19, "with"),
        (20, 22, "great power"),
        (23, 25, "insomuch that"),
        (26, 27, "were convinced"),
        (28, 31, "many people"),
        (32, 35, "of their wickedness,"),
        (36, 38, "which thing"),
        (39, 41, "urged"),
        (42, 43, "them"),
        (44, 45, "to repent"),
        (46, 49, "of their sins"),
        (50, 51, "and be baptized"),
        (52, 54, "unto the Lord"),
        (55, 57, "their God."),
    ],
    46: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they re-established"),
        (7, 9, "the church of"),
        (10, 11, "God,"),
        (12, 15, "throughout all the land."),
    ],
    47: [
        (0, 0, "Yea,"),
        (1, 3, "and were made"),
        (4, 5, "regulations"),
        (6, 9, "according to"),
        (10, 11, "the law."),
        (12, 14, "And were chosen"),
        (15, 17, "their judges,"),
        (18, 22, "and their chief judges."),
    ],
    48: [
        (0, 3, "And began to"),
        (4, 5, "prosper again"),
        (6, 8, "the people of Nephi"),
        (9, 11, "in the land,"),
        (12, 14, "and began to"),
        (15, 15, "multiply"),
        (16, 18, "and to grow"),
        (19, 22, "very strong again"),
        (23, 25, "in the land."),
        (26, 29, "And began to"),
        (30, 32, "they grow up"),
        (33, 37, "in exceeding riches."),
    ],
    49: [
        (0, 2, "But notwithstanding"),
        (3, 5, "their riches,"),
        (6, 7, "or"),
        (8, 10, "their strength,"),
        (11, 12, "or"),
        (13, 15, "their prosperity,"),
        (16, 18, "were not puffed up"),
        (19, 20, "they"),
        (21, 23, "in the pride"),
        (24, 27, "as seen"),
        (28, 31, "in their eyes;"),
        (32, 32, "neither"),
        (33, 36, "were slow to"),
        (37, 38, "they remember"),
        (39, 41, "the Lord"),
        (42, 44, "their God;"),
        (45, 49, "but they did humble themselves exceedingly"),
        (50, 52, "themselves"),
        (53, 55, "before him."),
    ],
    50: [
        (0, 0, "Yea,"),
        (1, 3, "they remembered"),
        (4, 5, "the great things"),
        (6, 7, "which were done"),
        (8, 10, "by the Lord"),
        (11, 13, "for them,"),
        (14, 17, "he delivered"),
        (18, 19, "them"),
        (20, 22, "from death,"),
        (23, 25, "and from bonds,"),
        (26, 28, "and from prisons,"),
        (29, 33, "and from every kind of"),
        (34, 35, "diverse afflictions,"),
        (36, 39, "and he delivered"),
        (40, 41, "them"),
        (42, 44, "from the hands of"),
        (45, 47, "their enemies."),
    ],
    51: [
        (0, 4, "And they did pray"),
        (5, 7, "unto the Lord"),
        (8, 10, "their God"),
        (11, 13, "continually,"),
        (14, 16, "insomuch that"),
        (17, 19, "were blessed"),
        (20, 22, "by the Lord,"),
        (23, 25, "according to"),
        (26, 27, "his word,"),
        (28, 30, "so that"),
        (31, 33, "they grew strong"),
        (34, 36, "and prospered"),
        (37, 39, "in the land."),
    ],
    52: [
        (0, 3, "And it came to pass that"),
        (4, 5, "were done"),
        (6, 10, "all these things."),
        (11, 13, "And died"),
        (14, 14, "Helaman,"),
        (15, 17, "in the year"),
        (18, 22, "thirty and five"),
        (23, 26, "of the reign of"),
        (27, 27, "the judges"),
        (28, 30, "over"),
        (31, 34, "the people of Nephi."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
