"""Hand-curated TAM-phrase gloss overrides for 2 Nifae 21 — Isaiah 11."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "2nephi"
CHAPTER_NUM = 21
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "And"),
        (1, 5, "shall come up"),
        (6, 7, "a rod"),
        (8, 10, "out of the stem"),
        (11, 12, "of Jesse,"),
        (13, 13, "and"),
        (14, 18, "shall grow up"),
        (19, 20, "a branch"),
        (21, 23, "out of his roots."),
    ],
    2: [
        (0, 0, "And"),
        (1, 4, "shall rest"),
        (5, 7, "upon him"),
        (8, 9, "the Spirit"),
        (10, 12, "of the Lord,"),
        (13, 15, "the spirit"),
        (16, 18, "of wisdom"),
        (19, 19, "and"),
        (20, 21, "the understanding,"),
        (22, 24, "the spirit"),
        (25, 27, "of counsel"),
        (28, 28, "and"),
        (29, 30, "the might,"),
        (31, 33, "the spirit"),
        (34, 36, "of knowledge"),
        (37, 37, "and"),
        (38, 39, "the fear"),
        (40, 42, "of the Lord;"),
    ],
    3: [
        (0, 3, "And shall"),
        (4, 6, "quickly may receive"),
        (7, 7, "thereto"),
        (8, 9, "by him"),
        (10, 11, "the understanding"),
        (12, 14, "in the fear"),
        (15, 17, "of the Lord;"),
        (18, 18, "and"),
        (19, 23, "shall not judge"),
        (24, 25, "he"),
        (26, 28, "according to"),
        (29, 30, "the sight"),
        (31, 33, "of his eyes,"),
        (34, 34, "neither"),
        (35, 36, "reprove"),
        (37, 39, "according to"),
        (40, 41, "the hearing"),
        (42, 44, "of his ears."),
    ],
    4: [
        (0, 0, "But"),
        (1, 4, "shall judge"),
        (5, 6, "by him"),
        (7, 7, "those"),
        (8, 8, "poor"),
        (9, 11, "with righteousness,"),
        (12, 12, "and"),
        (13, 14, "reprove"),
        (15, 16, "he"),
        (17, 19, "with equity"),
        (20, 21, "for those"),
        (22, 22, "meek"),
        (23, 25, "of the earth;"),
        (26, 26, "and"),
        (27, 30, "shall smite"),
        (31, 32, "by him"),
        (33, 34, "the earth"),
        (35, 37, "with the rod"),
        (38, 40, "of his mouth,"),
        (41, 41, "and"),
        (42, 44, "with the breath"),
        (45, 47, "of his lips"),
        (48, 52, "shall slay thereto"),
        (53, 54, "by him"),
        (55, 56, "the wicked."),
    ],
    5: [
        (0, 0, "And"),
        (1, 4, "shall be"),
        (5, 6, "righteousness"),
        (7, 7, "as"),
        (8, 8, "girdle"),
        (9, 11, "of his loins,"),
        (12, 12, "and"),
        (13, 15, "make faithfulness"),
        (16, 16, "as"),
        (17, 17, "girdle"),
        (18, 20, "of his reins."),
    ],
    6: [
        (0, 3, "Shall dwell"),
        (4, 4, "together"),
        (5, 5, "also"),
        (6, 7, "the wolf"),
        (8, 8, "with"),
        (9, 11, "the lamb,"),
        (12, 12, "and"),
        (13, 16, "shall lie down"),
        (17, 18, "the leopard"),
        (19, 19, "together"),
        (20, 20, "with"),
        (21, 23, "the kid,"),
        (24, 24, "and"),
        (25, 28, "shall be together"),
        (29, 31, "the calf"),
        (32, 32, "and"),
        (33, 35, "the young lion"),
        (36, 36, "and"),
        (37, 38, "fatling;"),
        (39, 39, "and"),
        (40, 43, "shall be led"),
        (44, 45, "them"),
        (46, 46, "by"),
        (47, 48, "the child."),
    ],
    7: [
        (0, 0, "And"),
        (1, 4, "shall feed"),
        (5, 5, "together"),
        (6, 7, "the cow"),
        (8, 8, "and"),
        (9, 10, "the bear;"),
        (11, 14, "shall lie down"),
        (15, 15, "together"),
        (16, 17, "their"),
        (18, 18, "young;"),
        (19, 19, "and"),
        (20, 23, "shall eat"),
        (24, 24, "by"),
        (25, 26, "the lion"),
        (27, 27, "stalks"),
        (28, 29, "of grain"),
        (30, 32, "like unto"),
        (33, 34, "the ox."),
    ],
    8: [
        (0, 0, "And"),
        (1, 4, "shall play"),
        (5, 6, "the child"),
        (7, 8, "not yet"),
        (9, 9, "departed"),
        (10, 10, "with"),
        (11, 12, "the breast"),
        (13, 15, "on the hole"),
        (16, 18, "of the snake"),
        (19, 19, "venomous"),
        (20, 22, "of the asp,"),
        (23, 23, "and"),
        (24, 26, "the child"),
        (27, 28, "departed"),
        (29, 29, "from"),
        (30, 31, "the breast"),
        (32, 35, "shall put"),
        (36, 37, "his hand"),
        (38, 40, "on the hole"),
        (41, 43, "of the snake"),
        (44, 44, "venomous"),
        (45, 47, "of the cockatrice."),
    ],
    9: [
        (0, 3, "they shall"),
        (4, 5, "not hurt"),
        (6, 6, "nor"),
        (7, 7, "destroy"),
        (8, 10, "in my mountain"),
        (11, 11, "holy"),
        (12, 12, "all,"),
        (13, 13, "for"),
        (14, 17, "shall be full"),
        (18, 19, "the earth"),
        (20, 22, "with the knowledge"),
        (23, 25, "of the Lord,"),
        (26, 28, "as"),
        (29, 29, "covered"),
        (30, 31, "the sea"),
        (32, 32, "by"),
        (33, 34, "the waters."),
    ],
    10: [
        (0, 0, "And"),
        (1, 3, "in that day"),
        (4, 8, "shall be"),
        (9, 10, "a root"),
        (11, 12, "of Jesse,"),
        (13, 17, "shall stand"),
        (18, 20, "to become as"),
        (21, 22, "an ensign"),
        (23, 25, "of the people;"),
        (26, 27, "he"),
        (28, 32, "shall seek"),
        (33, 34, "thereto"),
        (35, 35, "the Gentiles;"),
        (36, 36, "and"),
        (37, 39, "his rest"),
        (40, 43, "shall be glorious."),
    ],
    11: [
        (0, 0, "And"),
        (1, 5, "shall come"),
        (6, 6, "also"),
        (7, 9, "in that day"),
        (10, 13, "shall again"),
        (14, 15, "set thereto"),
        (16, 18, "by the Lord"),
        (19, 20, "his hand"),
        (21, 23, "at the time"),
        (24, 25, "his second"),
        (26, 27, "to recover"),
        (28, 30, "the portion"),
        (31, 32, "left"),
        (33, 35, "of his people"),
        (36, 37, "who remain,"),
        (38, 38, "from"),
        (39, 39, "Assyria,"),
        (40, 40, "and"),
        (41, 41, "from"),
        (42, 42, "Egypt,"),
        (43, 43, "and"),
        (44, 44, "from"),
        (45, 45, "Pathros,"),
        (46, 46, "and"),
        (47, 47, "from"),
        (48, 48, "Cush,"),
        (49, 49, "and"),
        (50, 50, "from"),
        (51, 51, "Elam,"),
        (52, 52, "and"),
        (53, 53, "from"),
        (54, 54, "Shinar,"),
        (55, 55, "and"),
        (56, 56, "from"),
        (57, 57, "Hamath,"),
        (58, 58, "and"),
        (59, 59, "from"),
        (60, 60, "the islands"),
        (61, 63, "of the sea."),
    ],
    12: [
        (0, 0, "And"),
        (1, 4, "shall set up"),
        (5, 6, "by him"),
        (7, 8, "an ensign"),
        (9, 10, "for the nations,"),
        (11, 13, "and assemble"),
        (14, 14, "those"),
        (15, 16, "are driven"),
        (17, 18, "of Israel,"),
        (19, 22, "and gather together"),
        (23, 25, "those who are dispersed"),
        (26, 27, "of Judah"),
        (28, 29, "from"),
        (30, 32, "the four corners"),
        (33, 35, "of the earth."),
    ],
    13: [
        (0, 4, "Shall depart"),
        (5, 5, "also"),
        (6, 7, "the envy"),
        (8, 9, "of Ephraim,"),
        (10, 10, "and"),
        (11, 15, "shall be cut off"),
        (16, 16, "adversaries"),
        (17, 18, "of Judah;"),
        (19, 23, "shall not envy"),
        (24, 24, "Ephraim"),
        (25, 26, "against Judah,"),
        (27, 27, "and"),
        (28, 32, "shall not vex"),
        (33, 33, "Judah"),
        (34, 35, "against Ephraim."),
    ],
    14: [
        (0, 0, "But"),
        (1, 4, "they two shall"),
        (5, 6, "fly"),
        (7, 8, "upon"),
        (9, 10, "shoulders"),
        (11, 12, "of the Philistines"),
        (13, 13, "toward"),
        (14, 15, "the west;"),
        (16, 19, "they two shall"),
        (20, 20, "plunder"),
        (21, 21, "together"),
        (22, 23, "them"),
        (24, 25, "of the east;"),
        (26, 29, "they shall"),
        (30, 30, "lay"),
        (31, 33, "their hand"),
        (34, 36, "upon"),
        (37, 39, "Edom and Moab;"),
        (40, 40, "and"),
        (41, 44, "shall obey"),
        (45, 46, "the children"),
        (47, 48, "of Ammon"),
        (49, 52, "them."),
    ],
    15: [
        (0, 0, "And"),
        (1, 4, "shall utterly"),
        (5, 5, "destroy"),
        (6, 6, "verily"),
        (7, 9, "by the Lord"),
        (10, 11, "the tongue"),
        (12, 14, "of the sea"),
        (15, 16, "of Egypt;"),
        (17, 17, "and"),
        (18, 21, "shall he"),
        (22, 22, "shake"),
        (23, 24, "his hand"),
        (25, 26, "over"),
        (27, 29, "the river"),
        (30, 30, "with"),
        (31, 32, "his wind"),
        (33, 33, "mighty,"),
        (34, 34, "and"),
        (35, 35, "smite"),
        (36, 38, "in the streams"),
        (39, 40, "seven,"),
        (41, 41, "and"),
        (42, 44, "make go over thereto"),
        (45, 45, "men"),
        (46, 47, "dryshod."),
    ],
    16: [
        (0, 0, "And"),
        (1, 5, "there shall be"),
        (6, 7, "a highway"),
        (8, 8, "special"),
        (9, 11, "for the portion"),
        (12, 13, "left"),
        (14, 16, "of his people"),
        (17, 18, "who remain,"),
        (19, 19, "from"),
        (20, 20, "Assyria,"),
        (21, 23, "as"),
        (24, 24, "done"),
        (25, 26, "to Israel"),
        (27, 29, "in the day"),
        (30, 33, "came up thereto"),
        (34, 35, "he"),
        (36, 36, "from"),
        (37, 38, "the land"),
        (39, 40, "of Egypt."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
