"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 52 — Ammoron succeeds
Amalickiah as Lamanite king; Teancum guards the coast; Moroni, Teancum, and Lehi
by stratagem recapture the city of Mulek, drawing the Lamanites out and crushing
Jacob's army; Ammoron's men are surrounded and surrender.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits done up front against bom_books.json:
  v19 `taua—i`

    python3 build_overrides_alma52.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 52

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now,"),
        (3, 4, "it came to pass"),
        (5, 11, "in the twenty and sixth"),
        (12, 13, "year"),
        (14, 18, "of the reign of the judges"),
        (19, 21, "over"),
        (22, 25, "the people of Nephi,"),
        (26, 26, "behold,"),
        (27, 30, "when awoke"),
        (31, 32, "the Lamanites"),
        (33, 36, "on the first morning"),
        (37, 40, "of the first month,"),
        (41, 41, "behold,"),
        (42, 44, "they found"),
        (45, 47, "Amalickiah was dead"),
        (48, 51, "in his own tent;"),
        (52, 55, "and they also saw"),
        (56, 57, "was prepared"),
        (58, 58, "Teancum"),
        (59, 61, "to fight with"),
        (62, 63, "them"),
        (64, 67, "on that day."),
    ],
    2: [
        (0, 2, "Now,"),
        (3, 6, "when saw"),
        (7, 8, "the Lamanites"),
        (9, 11, "this thing"),
        (12, 14, "they were afraid;"),
        (15, 18, "and they cast aside"),
        (19, 21, "their plan"),
        (22, 24, "to march"),
        (25, 29, "into the land northward,"),
        (30, 31, "but withdrew"),
        (32, 37, "together with all their army"),
        (38, 41, "into the city of"),
        (42, 42, "Mulek,"),
        (43, 44, "and sought"),
        (45, 46, "protection"),
        (47, 50, "in their towers."),
    ],
    3: [
        (0, 3, "And it came to pass that"),
        (4, 4, "was appointed"),
        (5, 7, "the brother of"),
        (8, 8, "Amalickiah"),
        (9, 12, "to become king"),
        (13, 15, "of the people;"),
        (16, 19, "and his name"),
        (20, 21, "was Ammoron;"),
        (22, 23, "thus"),
        (24, 28, "king Ammoron,"),
        (29, 31, "the brother of"),
        (32, 35, "king Amalickiah,"),
        (36, 37, "was appointed"),
        (38, 39, "to reign"),
        (40, 42, "in his place."),
    ],
    4: [
        (0, 3, "And it came to pass that"),
        (4, 7, "he commanded"),
        (8, 10, "that should"),
        (11, 12, "his people"),
        (13, 15, "they hold"),
        (16, 17, "those cities,"),
        (18, 21, "which they took"),
        (22, 24, "by means of"),
        (25, 27, "the shedding of"),
        (28, 29, "blood;"),
        (30, 30, "for"),
        (31, 34, "there was no city"),
        (35, 37, "they took"),
        (38, 41, "without shedding"),
        (42, 44, "much of"),
        (45, 47, "their blood."),
    ],
    5: [
        (0, 2, "And now,"),
        (3, 5, "saw"),
        (6, 6, "Teancum"),
        (7, 8, "were resolved"),
        (9, 10, "the Lamanites"),
        (11, 12, "to hold"),
        (13, 14, "those cities"),
        (15, 17, "which they took,"),
        (18, 20, "and the parts of"),
        (21, 23, "the land which"),
        (24, 28, "they took for themselves;"),
        (29, 32, "and also seeing"),
        (33, 36, "the greatness of"),
        (37, 39, "their number,"),
        (40, 41, "therefore"),
        (42, 45, "Teancum thought"),
        (46, 51, "it was not right that he attempt"),
        (52, 53, "to attack"),
        (54, 55, "them"),
        (56, 59, "in their towers."),
    ],
    6: [
        (0, 3, "But he placed"),
        (4, 5, "his men"),
        (6, 6, "round about,"),
        (7, 8, "as if"),
        (9, 12, "they were making"),
        (13, 16, "preparations for war;"),
        (17, 17, "yea,"),
        (18, 22, "and in truth,"),
        (23, 25, "he prepared"),
        (26, 27, "to defend"),
        (28, 30, "himself"),
        (31, 35, "from them,"),
        (36, 39, "by the building of"),
        (40, 42, "walls round about"),
        (43, 44, "and preparing"),
        (45, 48, "places of protection."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 8, "he kept thus preparing"),
        (9, 10, "for war"),
        (11, 13, "until"),
        (14, 15, "sent"),
        (16, 17, "Moroni"),
        (18, 21, "a great number of"),
        (22, 22, "men"),
        (23, 25, "to strengthen"),
        (26, 27, "his army."),
    ],
    8: [
        (0, 4, "And also sent"),
        (5, 6, "Moroni"),
        (7, 8, "orders"),
        (9, 11, "unto him"),
        (12, 16, "that he should keep"),
        (17, 18, "all the prisoners"),
        (19, 23, "who fell"),
        (24, 26, "into his hands;"),
        (27, 30, "for because"),
        (31, 35, "had taken the Lamanites"),
        (36, 38, "many prisoners,"),
        (39, 43, "that he should keep"),
        (44, 47, "all the prisoners of"),
        (48, 49, "the Lamanites"),
        (50, 53, "as a ransom"),
        (54, 56, "for those"),
        (57, 60, "whom had taken"),
        (61, 63, "the Lamanites."),
    ],
    9: [
        (0, 5, "And he also sent"),
        (6, 7, "orders"),
        (8, 10, "unto him"),
        (11, 15, "that he should fortify"),
        (16, 19, "the land of Bountiful,"),
        (20, 22, "and firmly guard"),
        (23, 25, "the narrow pass"),
        (26, 29, "which led"),
        (30, 34, "into the land northward,"),
        (35, 36, "lest obtain"),
        (37, 39, "the Lamanites"),
        (40, 43, "that piece of land"),
        (44, 46, "and gain"),
        (47, 48, "the power"),
        (49, 51, "to attack"),
        (52, 53, "them"),
        (54, 56, "on all sides."),
    ],
    10: [
        (0, 4, "And also sent"),
        (5, 6, "Moroni"),
        (7, 9, "unto him,"),
        (10, 11, "desiring"),
        (12, 14, "him"),
        (15, 19, "that he be faithful"),
        (20, 23, "in the defending of"),
        (24, 27, "that quarter of"),
        (28, 29, "the land,"),
        (30, 34, "and that he seek"),
        (35, 36, "every chance"),
        (37, 39, "to afflict"),
        (40, 41, "the Lamanites"),
        (42, 44, "in that quarter,"),
        (45, 48, "according to"),
        (49, 54, "the strength he had,"),
        (55, 55, "perhaps"),
        (56, 63, "he might regain"),
        (64, 66, "by a stratagem"),
        (67, 71, "or some other way,"),
        (72, 73, "those cities"),
        (74, 76, "which were taken"),
        (77, 80, "from their hands;"),
        (81, 87, "and that he also fortify"),
        (88, 89, "and strengthen"),
        (90, 93, "the cities round about,"),
        (94, 98, "which had not fallen"),
        (99, 101, "into the hands of"),
        (102, 103, "the Lamanites."),
    ],
    11: [
        (0, 5, "And he also said"),
        (6, 8, "unto him,"),
        (9, 13, "I wish to come"),
        (14, 16, "unto thee,"),
        (17, 18, "but behold,"),
        (19, 21, "have come"),
        (22, 23, "the Lamanites"),
        (24, 27, "upon us"),
        (28, 30, "in the borders of"),
        (31, 32, "the land"),
        (33, 35, "by the side of"),
        (36, 39, "the west sea;"),
        (40, 41, "and behold,"),
        (42, 44, "I go"),
        (45, 46, "against"),
        (47, 50, "them,"),
        (51, 52, "therefore"),
        (53, 60, "I cannot come"),
        (61, 63, "unto thee."),
    ],
    12: [
        (0, 1, "Now,"),
        (2, 5, "had departed"),
        (6, 7, "the king"),
        (8, 9, "(Ammoron)"),
        (10, 13, "from the land of"),
        (14, 14, "Zarahemla,"),
        (15, 19, "and he made known"),
        (20, 22, "to the queen"),
        (23, 25, "concerning"),
        (26, 28, "the death of"),
        (29, 30, "his brother,"),
        (31, 35, "and he gathered together"),
        (36, 39, "a great number of"),
        (40, 40, "men,"),
        (41, 44, "and marched forth"),
        (45, 46, "against"),
        (47, 49, "the Nephites"),
        (50, 51, "on the borders"),
        (52, 54, "by the side of"),
        (55, 58, "the west sea."),
    ],
    13: [
        (0, 5, "And thus he endeavored"),
        (6, 7, "to attack"),
        (8, 9, "the Nephites,"),
        (10, 12, "and to draw away"),
        (13, 15, "a part of"),
        (16, 18, "their forces"),
        (19, 23, "to that part of"),
        (24, 25, "the land,"),
        (26, 28, "while he commanded"),
        (29, 30, "those"),
        (31, 35, "whom he left"),
        (36, 38, "to dwell in"),
        (39, 40, "the cities"),
        (41, 43, "which he took,"),
        (44, 47, "that they also attack"),
        (48, 49, "the Nephites"),
        (50, 52, "who were on the borders"),
        (53, 55, "by the side of"),
        (56, 59, "the east sea,"),
        (60, 63, "and that they take"),
        (64, 66, "their lands"),
        (67, 69, "according to"),
        (70, 74, "the greatness of the power"),
        (75, 79, "which they had,"),
        (80, 82, "according to"),
        (83, 85, "the strength of"),
        (86, 88, "their armies."),
    ],
    14: [
        (0, 5, "And thus were"),
        (6, 8, "the Nephites"),
        (9, 12, "in those difficult conditions"),
        (13, 16, "in the end of"),
        (17, 22, "the twenty and sixth"),
        (23, 24, "year"),
        (25, 29, "of the reign of the judges"),
        (30, 33, "over the people of"),
        (34, 34, "Nephi."),
    ],
    15: [
        (0, 1, "But behold,"),
        (2, 3, "it came to pass"),
        (4, 6, "in the year"),
        (7, 11, "twenty and seven"),
        (12, 16, "of the reign of the judges,"),
        (17, 19, "received"),
        (20, 21, "Teancum,"),
        (22, 24, "by means of"),
        (25, 26, "a command"),
        (27, 29, "from Moroni—"),
        (30, 34, "who set up"),
        (35, 36, "armies"),
        (37, 38, "to protect"),
        (39, 44, "the south and west borders of"),
        (45, 46, "the land,"),
        (47, 49, "and had begun"),
        (50, 51, "his march"),
        (52, 53, "towards"),
        (54, 57, "the land of Bountiful,"),
        (58, 63, "that he might help"),
        (64, 65, "Teancum"),
        (66, 68, "and his men"),
        (69, 72, "in the retaking of"),
        (73, 75, "those cities"),
        (76, 78, "which were taken"),
        (79, 82, "from them—"),
    ],
    16: [
        (0, 2, "It came to pass that"),
        (3, 4, "received"),
        (5, 6, "Teancum"),
        (7, 8, "orders"),
        (9, 12, "to launch an attack"),
        (13, 15, "upon"),
        (16, 19, "the city of Mulek,"),
        (20, 22, "and retake"),
        (23, 24, "the city"),
        (25, 28, "if it be possible."),
    ],
    17: [
        (0, 3, "And it came to pass that"),
        (4, 4, "made"),
        (5, 6, "Teancum"),
        (7, 7, "preparations"),
        (8, 12, "to launch an attack"),
        (13, 15, "upon"),
        (16, 19, "the city of Mulek,"),
        (20, 22, "and march forth"),
        (23, 25, "with his army"),
        (26, 27, "against"),
        (28, 30, "the Lamanites;"),
        (31, 31, "but"),
        (32, 35, "he saw"),
        (36, 41, "he could not overpower"),
        (42, 43, "them"),
        (44, 48, "while they were"),
        (49, 52, "in their towers;"),
        (53, 54, "therefore"),
        (55, 58, "he abandoned"),
        (59, 60, "his plans"),
        (61, 64, "and returned"),
        (65, 69, "to the city of Bountiful,"),
        (70, 72, "to wait"),
        (73, 75, "for the coming of"),
        (76, 77, "Moroni,"),
        (78, 83, "that he might gain"),
        (84, 86, "a reinforcement"),
        (87, 89, "to his army."),
    ],
    18: [
        (0, 3, "And it came to pass that"),
        (4, 6, "did arrive"),
        (7, 7, "Moroni"),
        (8, 10, "with his army"),
        (11, 14, "at the land of"),
        (15, 15, "Bountiful,"),
        (16, 19, "in the latter end of"),
        (20, 25, "the twenty and seventh"),
        (26, 27, "year"),
        (28, 32, "of the reign of the judges"),
        (33, 36, "over the people of"),
        (37, 37, "Nephi."),
    ],
    19: [
        (0, 0, "And"),
        (1, 3, "in the beginning"),
        (4, 10, "of the twenty and eighth"),
        (11, 12, "year,"),
        (13, 15, "held"),
        (16, 19, "Moroni and Teancum"),
        (20, 23, "and many of"),
        (24, 25, "the chief captains"),
        (26, 28, "a council of"),
        (29, 30, "war—"),
        (31, 33, "as to what"),
        (34, 38, "they should do"),
        (39, 41, "to entice"),
        (42, 43, "the Lamanites"),
        (44, 46, "that they come"),
        (47, 49, "against"),
        (50, 53, "them"),
        (54, 56, "to battle;"),
        (57, 60, "or by some stratagem"),
        (61, 67, "they might flatter"),
        (68, 69, "them"),
        (70, 73, "to come out"),
        (74, 75, "from"),
        (76, 78, "their fortresses,"),
        (79, 84, "that they might gain"),
        (85, 90, "a better position"),
        (91, 93, "over"),
        (94, 95, "them,"),
        (96, 99, "and retake"),
        (100, 103, "the city of Mulek."),
    ],
    20: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they sent"),
        (7, 8, "messengers"),
        (9, 12, "to the army of"),
        (13, 14, "the Lamanites,"),
        (15, 17, "who defended"),
        (18, 21, "the city of Mulek,"),
        (22, 25, "to their leader,"),
        (26, 28, "his name"),
        (29, 30, "was Jacob,"),
        (31, 32, "desiring"),
        (33, 35, "him,"),
        (36, 38, "that he come"),
        (39, 41, "with his armies"),
        (42, 44, "to meet with"),
        (45, 46, "them"),
        (47, 49, "upon"),
        (50, 51, "level lands"),
        (52, 54, "between"),
        (55, 58, "the two cities."),
        (59, 60, "But behold,"),
        (61, 62, "Jacob,"),
        (63, 68, "who was a Zoramite,"),
        (69, 74, "would not come"),
        (75, 77, "with his army"),
        (78, 80, "to meet with"),
        (81, 82, "them"),
        (83, 85, "upon"),
        (86, 87, "level lands."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 7, "had no hope"),
        (8, 9, "Moroni,"),
        (10, 13, "of meeting"),
        (14, 15, "them"),
        (16, 18, "upon"),
        (19, 21, "equal terms,"),
        (22, 23, "therefore,"),
        (24, 27, "he devised"),
        (28, 30, "a plan"),
        (31, 36, "that he might lure out"),
        (37, 38, "outward"),
        (39, 40, "the Lamanites"),
        (41, 42, "from"),
        (43, 45, "their strongholds."),
    ],
    22: [
        (0, 1, "Therefore"),
        (2, 5, "he commanded"),
        (6, 6, "Teancum"),
        (7, 9, "that he take"),
        (10, 13, "a small part of"),
        (14, 15, "fighting men"),
        (16, 18, "and march down"),
        (19, 20, "near"),
        (21, 22, "the seashore;"),
        (23, 25, "but Moroni"),
        (26, 28, "and his army,"),
        (29, 31, "marched"),
        (32, 34, "in the night"),
        (35, 37, "in the wilderness,"),
        (38, 43, "on the west side of"),
        (44, 47, "the city of Mulek;"),
        (48, 50, "and thus,"),
        (51, 56, "on the following day,"),
        (57, 60, "when had discovered"),
        (61, 65, "the guards of the Lamanites"),
        (66, 66, "Teancum,"),
        (67, 69, "they ran"),
        (70, 72, "and told"),
        (73, 74, "Jacob,"),
        (75, 77, "their leader."),
    ],
    23: [
        (0, 3, "And it came to pass that"),
        (4, 5, "marched out"),
        (6, 7, "the armies of"),
        (8, 9, "the Lamanites"),
        (10, 11, "against"),
        (12, 13, "Teancum,"),
        (14, 15, "they thought"),
        (16, 19, "by their numbers"),
        (20, 25, "they would overpower"),
        (26, 26, "Teancum"),
        (27, 28, "because of"),
        (29, 31, "the smallness of"),
        (32, 36, "the number of his army."),
        (37, 41, "And when saw"),
        (42, 42, "Teancum"),
        (43, 45, "coming"),
        (46, 49, "the armies of the Lamanites"),
        (50, 52, "against"),
        (53, 55, "him,"),
        (56, 61, "he began to withdraw down"),
        (62, 64, "by the side of"),
        (65, 66, "the seashore,"),
        (67, 71, "on the north side."),
    ],
    24: [
        (0, 3, "And it came to pass that"),
        (4, 6, "when saw"),
        (7, 8, "the Lamanites"),
        (9, 14, "he began to flee,"),
        (15, 17, "they took courage"),
        (18, 20, "and pursued"),
        (21, 22, "them"),
        (23, 25, "with strength."),
        (26, 31, "And while thus leading away"),
        (32, 33, "Teancum"),
        (34, 35, "the Lamanites"),
        (36, 43, "who pursued them"),
        (44, 46, "but did not catch them,"),
        (47, 47, "behold,"),
        (48, 50, "commanded"),
        (51, 51, "Moroni"),
        (52, 55, "to a part of"),
        (56, 57, "his army"),
        (58, 61, "who were together"),
        (62, 63, "with him,"),
        (64, 68, "that should march"),
        (69, 71, "into the city,"),
        (72, 76, "and take it for themselves."),
    ],
    25: [
        (0, 5, "And thus they did,"),
        (6, 7, "and slew"),
        (8, 10, "all of them"),
        (11, 14, "who remained"),
        (15, 16, "to defend"),
        (17, 18, "the city,"),
        (19, 19, "yea,"),
        (20, 23, "all of them"),
        (24, 28, "who did not wish"),
        (29, 31, "to yield up"),
        (32, 34, "their weapons"),
        (35, 36, "of war."),
    ],
    26: [
        (0, 4, "And thus took"),
        (5, 6, "Moroni"),
        (7, 9, "the city of"),
        (10, 10, "Mulek"),
        (11, 14, "with a part of"),
        (15, 16, "his army,"),
        (17, 20, "while he marched"),
        (21, 24, "with those who remained"),
        (25, 26, "to meet"),
        (27, 28, "the Lamanites"),
        (29, 33, "when they return"),
        (34, 37, "from the pursuit of"),
        (38, 38, "Teancum."),
    ],
    27: [
        (0, 3, "And it came to pass that"),
        (4, 7, "pursued the Lamanites"),
        (8, 8, "Teancum"),
        (9, 11, "until"),
        (12, 15, "they came near"),
        (16, 19, "to the city of"),
        (20, 20, "Bountiful,"),
        (21, 25, "and then were met"),
        (26, 28, "they"),
        (29, 30, "by Lehi"),
        (31, 34, "and a small army,"),
        (35, 37, "which was left"),
        (38, 39, "to defend"),
        (40, 43, "the city of Bountiful."),
    ],
    28: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 7, "when saw"),
        (8, 10, "the chief captains of"),
        (11, 12, "the Lamanites"),
        (13, 15, "were coming"),
        (16, 16, "Lehi"),
        (17, 19, "with his army"),
        (20, 22, "against"),
        (23, 26, "them,"),
        (27, 29, "they fled"),
        (30, 33, "in great confusion,"),
        (34, 35, "lest"),
        (36, 39, "they be overtaken"),
        (40, 41, "by Lehi"),
        (42, 46, "before they reached"),
        (47, 51, "the city of Mulek;"),
        (52, 55, "for they were weary"),
        (56, 57, "because of"),
        (58, 60, "their march,"),
        (61, 64, "but were fresh"),
        (65, 67, "the men of Lehi."),
    ],
    29: [
        (0, 1, "Now"),
        (2, 4, "did not know"),
        (5, 7, "the Lamanites"),
        (8, 10, "was"),
        (11, 11, "Moroni"),
        (12, 14, "with his army"),
        (15, 18, "in their rear;"),
        (19, 23, "and the only thing"),
        (24, 28, "which they feared"),
        (29, 30, "was Lehi"),
        (31, 33, "and his men."),
    ],
    30: [
        (0, 1, "Now"),
        (2, 4, "did not wish"),
        (5, 5, "Lehi"),
        (6, 8, "to overtake"),
        (9, 10, "them"),
        (11, 13, "until"),
        (14, 15, "they meet"),
        (16, 17, "with Moroni"),
        (18, 20, "and his army."),
    ],
    31: [
        (0, 3, "And it came to pass that"),
        (4, 7, "before had gone far"),
        (8, 10, "the retreat of"),
        (11, 12, "the Lamanites"),
        (13, 15, "but were surrounded"),
        (16, 17, "they"),
        (18, 20, "by the Nephites,"),
        (21, 24, "by the men of Moroni"),
        (25, 28, "on one side,"),
        (29, 32, "and the men of Lehi"),
        (33, 36, "on the other side,"),
        (37, 39, "all men"),
        (40, 43, "who were renewed"),
        (44, 48, "and filled with strength;"),
        (49, 52, "but the Lamanites"),
        (53, 55, "were weary"),
        (56, 57, "because of"),
        (58, 61, "their long march."),
    ],
    32: [
        (0, 2, "And commanded"),
        (3, 4, "Moroni"),
        (5, 6, "his men"),
        (7, 9, "that they attack"),
        (10, 11, "them"),
        (12, 14, "until"),
        (15, 17, "they gave up"),
        (18, 20, "their weapons"),
        (21, 22, "of war."),
    ],
    33: [
        (0, 2, "And it came to pass"),
        (3, 5, "because Jacob,"),
        (6, 11, "who was their leader,"),
        (12, 20, "and being also a Zoramite,"),
        (21, 26, "and because he had"),
        (27, 30, "an unyielding spirit,"),
        (31, 34, "he led forth"),
        (35, 36, "the Lamanites"),
        (37, 38, "to fight"),
        (39, 42, "with great anger"),
        (43, 44, "against"),
        (45, 46, "Moroni."),
    ],
    34: [
        (0, 3, "Because was"),
        (4, 4, "Moroni"),
        (5, 8, "in the path of"),
        (9, 11, "their march,"),
        (12, 13, "therefore"),
        (14, 16, "resolved"),
        (17, 17, "Jacob"),
        (18, 19, "to slay"),
        (20, 21, "them"),
        (22, 26, "and force through"),
        (27, 28, "his path"),
        (29, 32, "to pass through to"),
        (33, 36, "the city of Mulek."),
        (37, 38, "But behold,"),
        (39, 41, "was greater"),
        (42, 44, "the strength of"),
        (45, 48, "Moroni and his men;"),
        (49, 50, "therefore"),
        (51, 55, "they did not retreat"),
        (56, 58, "before"),
        (59, 60, "the Lamanites."),
    ],
    35: [
        (0, 3, "And it came to pass that"),
        (4, 5, "they fought"),
        (6, 10, "on both sides"),
        (11, 14, "with great anger;"),
        (15, 17, "and many"),
        (18, 19, "were slain"),
        (20, 24, "on both sides;"),
        (25, 25, "yea,"),
        (26, 28, "and was wounded"),
        (29, 29, "Moroni"),
        (30, 32, "and was slain"),
        (33, 33, "Jacob."),
    ],
    36: [
        (0, 2, "And pressed hard"),
        (3, 4, "Lehi"),
        (5, 9, "their rear part"),
        (10, 13, "with great fury"),
        (14, 17, "with his strong men,"),
        (18, 21, "insomuch that"),
        (22, 23, "gave up"),
        (24, 26, "the Lamanites"),
        (27, 32, "who were at the back"),
        (33, 35, "their weapons"),
        (36, 38, "of war;"),
        (39, 43, "but those who remained"),
        (44, 46, "of them,"),
        (47, 50, "because were very confused,"),
        (51, 53, "knew not"),
        (54, 56, "whether to flee"),
        (57, 58, "or attack."),
    ],
    37: [
        (0, 1, "Now"),
        (2, 4, "when saw"),
        (5, 5, "Moroni"),
        (6, 9, "their confusion,"),
        (10, 13, "he said"),
        (14, 17, "unto them:"),
        (18, 21, "If ye bring"),
        (22, 24, "your weapons"),
        (25, 26, "of war"),
        (27, 29, "and give up,"),
        (30, 30, "behold"),
        (31, 35, "we will stop"),
        (36, 38, "the shedding of"),
        (39, 40, "your blood."),
    ],
    38: [
        (0, 3, "And it came to pass that"),
        (4, 6, "when had heard"),
        (7, 8, "the Lamanites"),
        (9, 11, "these words,"),
        (12, 16, "their chief captains,"),
        (17, 20, "and all of them"),
        (21, 25, "who were not slain,"),
        (26, 30, "came forward"),
        (31, 34, "and cast down"),
        (35, 37, "their weapons"),
        (38, 39, "of war,"),
        (40, 42, "at the feet of"),
        (43, 43, "Moroni,"),
        (44, 46, "and also commanded"),
        (47, 49, "their men"),
        (50, 54, "that they should do"),
        (55, 59, "that same thing."),
    ],
    39: [
        (0, 1, "But behold,"),
        (2, 6, "there were many"),
        (7, 11, "who would not do it;"),
        (12, 15, "and those"),
        (16, 22, "who would not give up"),
        (23, 25, "their swords"),
        (26, 27, "were taken"),
        (28, 29, "and bound,"),
        (30, 33, "and were taken away"),
        (34, 37, "from them"),
        (38, 43, "their weapons of war,"),
        (44, 47, "and they were compelled"),
        (48, 50, "to march"),
        (51, 52, "together with"),
        (53, 55, "their brethren"),
        (56, 59, "into the land of"),
        (60, 60, "Bountiful."),
    ],
    40: [
        (0, 2, "And now"),
        (3, 6, "the number of"),
        (7, 7, "prisoners"),
        (8, 11, "who were taken"),
        (12, 14, "was greater"),
        (15, 18, "than the number"),
        (19, 22, "of those who were slain,"),
        (23, 23, "yea,"),
        (24, 27, "more than"),
        (28, 30, "those who were killed"),
        (31, 35, "on both sides."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
