"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 42 — Alma concludes
his charge to Corianton on the justice and mercy of God: the fall of Adam,
the probationary state, the demands of justice, the atonement that appeases
justice and brings mercy, and the plan of redemption.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits done up front against bom_books.json:
  v1  `ai—ia`            -> 73 tokens
  v2  `la’ua—ioe,`       -> 89 tokens
  v6  `fogaeleele—ma`    -> 54 tokens
  v19 `mai—afai` and `ia—pe` -> 36 tokens

    python3 build_overrides_alma42.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 42

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 8, "I perceive"),
        (9, 13, "there is yet some"),
        (14, 16, "more thing"),
        (17, 20, "which worrieth"),
        (21, 22, "your mind,"),
        (23, 28, "which ye cannot"),
        (29, 31, "understand—"),
        (32, 35, "which is concerning"),
        (36, 40, "the justice of God"),
        (41, 43, "in the punishment"),
        (44, 47, "of the sinner;"),
        (48, 48, "for"),
        (49, 53, "ye do try to suppose"),
        (54, 55, "that"),
        (56, 60, "it is injustice"),
        (61, 63, "the consigning of"),
        (64, 66, "the sinner"),
        (67, 70, "to a state of"),
        (71, 72, "misery."),
    ],
    2: [
        (0, 2, "Now behold,"),
        (3, 5, "my son,"),
        (6, 11, "I will explain"),
        (12, 14, "unto thee"),
        (15, 16, "this thing."),
        (17, 18, "For behold,"),
        (19, 22, "after"),
        (23, 25, "had sent forth"),
        (26, 30, "the Lord God"),
        (31, 34, "our first parents"),
        (35, 39, "from the garden of Eden,"),
        (40, 43, "to till the ground,"),
        (44, 47, "from whence taken"),
        (48, 49, "were they—"),
        (50, 50, "yea,"),
        (51, 54, "he drew out"),
        (55, 56, "the man,"),
        (57, 60, "and he placed"),
        (61, 65, "at the east end"),
        (66, 70, "of the garden of Eden,"),
        (71, 71, "cherubim,"),
        (72, 76, "and a flaming sword"),
        (77, 81, "which turned every way,"),
        (82, 83, "to keep"),
        (84, 88, "the tree of life."),
    ],
    3: [
        (0, 1, "Now,"),
        (2, 4, "we see"),
        (5, 8, "the man had become"),
        (9, 13, "as God,"),
        (14, 17, "knowing"),
        (18, 19, "good"),
        (20, 22, "and evil;"),
        (23, 27, "and lest he put forth"),
        (28, 29, "his hand,"),
        (30, 33, "and take also from"),
        (34, 38, "the tree of life,"),
        (39, 40, "and eat"),
        (41, 45, "and live forever,"),
        (46, 47, "therefore"),
        (48, 50, "placed"),
        (51, 55, "the Lord God"),
        (56, 57, "cherubim"),
        (58, 62, "and the flaming sword,"),
        (63, 67, "that he should not"),
        (68, 70, "partake"),
        (71, 73, "of the fruit—"),
    ],
    4: [
        (0, 4, "And thus we"),
        (5, 6, "see,"),
        (7, 11, "that there was a time"),
        (12, 17, "granted unto man"),
        (18, 20, "to repent,"),
        (21, 21, "yea,"),
        (22, 24, "a time"),
        (25, 28, "of probation,"),
        (29, 33, "a time to repent"),
        (34, 36, "and to serve"),
        (37, 39, "God."),
    ],
    5: [
        (0, 1, "For behold,"),
        (2, 5, "if immediately"),
        (6, 7, "had put forth"),
        (8, 12, "the hand of Adam,"),
        (13, 15, "and eaten of"),
        (16, 20, "the tree of life,"),
        (21, 25, "he would have lived"),
        (26, 27, "forever,"),
        (28, 30, "according to"),
        (31, 35, "the word of God,"),
        (36, 39, "there being no time"),
        (40, 42, "for repentance;"),
        (43, 43, "yea,"),
        (44, 48, "and also there would be no"),
        (49, 50, "worth"),
        (51, 54, "of the word of"),
        (55, 56, "God,"),
        (57, 61, "and would not be accomplished"),
        (62, 65, "the great plan of"),
        (66, 67, "salvation."),
    ],
    6: [
        (0, 1, "But behold,"),
        (2, 6, "it was appointed unto man"),
        (7, 8, "to die—"),
        (9, 10, "therefore,"),
        (11, 15, "as were cut off"),
        (16, 17, "they"),
        (18, 21, "from the tree of"),
        (22, 23, "life"),
        (24, 29, "so they should also be cut"),
        (30, 31, "off,"),
        (32, 36, "from the face of the earth—"),
        (37, 41, "and became lost"),
        (42, 43, "man"),
        (44, 45, "forever,"),
        (46, 46, "yea,"),
        (47, 50, "they became"),
        (51, 53, "fallen man."),
    ],
    7: [
        (0, 2, "And now,"),
        (3, 5, "ye see"),
        (6, 8, "by this"),
        (9, 12, "were cut off"),
        (13, 15, "temporally and spiritually"),
        (16, 19, "our first parents"),
        (20, 24, "from the presence of the Lord;"),
        (25, 29, "and thus we"),
        (30, 31, "see"),
        (32, 35, "they became"),
        (36, 38, "subjects"),
        (39, 41, "to follow after"),
        (42, 45, "their own will."),
    ],
    8: [
        (0, 2, "Now behold,"),
        (3, 6, "it was not expedient"),
        (7, 8, "to reclaim"),
        (9, 11, "man"),
        (12, 15, "from this temporal death,"),
        (16, 16, "for"),
        (17, 21, "that would destroy"),
        (22, 25, "the great plan of"),
        (26, 27, "happiness."),
    ],
    9: [
        (0, 1, "Therefore,"),
        (2, 7, "as could never"),
        (8, 8, "die"),
        (9, 11, "the soul,"),
        (12, 14, "and had brought"),
        (15, 17, "the fall"),
        (18, 22, "upon all men"),
        (23, 25, "a spiritual death"),
        (26, 28, "as well as"),
        (29, 31, "a temporal death,"),
        (32, 34, "that is,"),
        (35, 39, "they were cut off"),
        (40, 44, "from the presence of the Lord,"),
        (45, 46, "therefore"),
        (47, 50, "it was expedient"),
        (51, 52, "to reclaim"),
        (53, 54, "mankind"),
        (55, 58, "from this spiritual death."),
    ],
    10: [
        (0, 1, "Therefore,"),
        (2, 4, "as"),
        (5, 8, "they had become"),
        (9, 12, "carnal,"),
        (13, 13, "sensual,"),
        (14, 15, "and devilish,"),
        (16, 19, "by nature,"),
        (20, 21, "therefore"),
        (22, 26, "this state became"),
        (27, 30, "of probation"),
        (31, 33, "a life"),
        (34, 39, "for them to prepare;"),
        (40, 41, "it became"),
        (42, 45, "a preparatory state."),
    ],
    11: [
        (0, 2, "And now"),
        (3, 5, "remember,"),
        (6, 8, "my son,"),
        (9, 11, "were it not for"),
        (12, 16, "the plan of redemption,"),
        (17, 20, "(laying it aside),"),
        (21, 24, "as soon"),
        (25, 28, "as they were dead"),
        (29, 31, "miserable were"),
        (32, 34, "their souls,"),
        (35, 35, "being"),
        (36, 38, "cut off"),
        (39, 43, "from the presence of the Lord."),
    ],
    12: [
        (0, 2, "And now,"),
        (3, 6, "there was no means"),
        (7, 10, "to reclaim men"),
        (11, 14, "from this fallen state,"),
        (15, 17, "which had brought"),
        (18, 20, "man"),
        (21, 24, "upon himself"),
        (25, 26, "because of"),
        (27, 30, "his own disobedience;"),
    ],
    13: [
        (0, 1, "Therefore,"),
        (2, 6, "according to justice,"),
        (7, 11, "could not be brought about"),
        (12, 15, "the plan of"),
        (16, 17, "redemption,"),
        (18, 22, "only on conditions"),
        (23, 27, "of repentance of men"),
        (28, 30, "in this life"),
        (31, 34, "of probation,"),
        (35, 35, "yea,"),
        (36, 38, "this preparatory state;"),
        (39, 43, "for except these conditions"),
        (44, 48, "could not take effect"),
        (49, 51, "mercy"),
        (52, 56, "except it should destroy"),
        (57, 61, "the work of justice."),
        (62, 63, "Now"),
        (64, 68, "could not be destroyed"),
        (69, 73, "the work of justice;"),
        (74, 75, "if so,"),
        (76, 80, "would cease to be"),
        (81, 82, "God"),
        (83, 84, "a God."),
    ],
    14: [
        (0, 4, "And thus we"),
        (5, 6, "see"),
        (7, 10, "all mankind were fallen,"),
        (11, 15, "and unto them was"),
        (16, 17, "the grasp"),
        (18, 20, "of justice;"),
        (21, 21, "yea,"),
        (22, 26, "the justice of God,"),
        (27, 31, "which consigned them"),
        (32, 37, "to be cut off from his presence"),
        (38, 39, "forever."),
    ],
    15: [
        (0, 2, "And now,"),
        (3, 7, "could not be brought about"),
        (8, 10, "the plan of"),
        (11, 13, "mercy"),
        (14, 15, "except"),
        (16, 19, "an atonement be made;"),
        (20, 21, "therefore"),
        (22, 24, "atoneth"),
        (25, 29, "God himself"),
        (30, 34, "for the sins of the world,"),
        (35, 37, "to bring about"),
        (38, 40, "the plan of"),
        (41, 43, "mercy,"),
        (44, 47, "to appease the demands"),
        (48, 50, "of justice,"),
        (51, 55, "that might be"),
        (56, 57, "God"),
        (58, 61, "a perfect God,"),
        (62, 62, "just,"),
        (63, 65, "and a God"),
        (66, 68, "merciful also."),
    ],
    16: [
        (0, 1, "Now,"),
        (2, 5, "could not"),
        (6, 7, "come"),
        (8, 9, "repentance"),
        (10, 11, "unto men"),
        (12, 15, "except there were"),
        (16, 17, "a punishment,"),
        (18, 22, "which also was eternal"),
        (23, 27, "as should be"),
        (28, 31, "the life of"),
        (32, 33, "the soul,"),
        (34, 35, "affixed"),
        (36, 38, "opposite to"),
        (39, 43, "the plan of happiness,"),
        (44, 47, "which was also eternal"),
        (48, 50, "even as"),
        (51, 55, "the life of the soul."),
    ],
    17: [
        (0, 1, "Now,"),
        (2, 6, "how could repent"),
        (7, 9, "a man"),
        (10, 11, "except"),
        (12, 15, "he should sin?"),
        (16, 22, "how could he sin"),
        (23, 26, "if there were no"),
        (27, 28, "law?"),
        (29, 33, "how could there be"),
        (34, 36, "a law"),
        (37, 41, "save there were"),
        (42, 43, "a punishment?"),
    ],
    18: [
        (0, 1, "Now,"),
        (2, 4, "there was"),
        (5, 7, "a punishment affixed,"),
        (8, 11, "and a just law"),
        (12, 14, "given,"),
        (15, 18, "which brought"),
        (19, 23, "remorse of conscience"),
        (24, 26, "unto man."),
    ],
    19: [
        (0, 1, "Now,"),
        (2, 6, "if there was no law"),
        (7, 9, "given—"),
        (10, 13, "if murdered"),
        (14, 15, "a man,"),
        (16, 21, "he should die—"),
        (22, 24, "would he be afraid"),
        (25, 30, "he would die"),
        (31, 35, "if he should murder?"),
    ],
    20: [
        (0, 2, "And also,"),
        (3, 7, "if there was no law"),
        (8, 10, "given"),
        (11, 15, "against sin"),
        (16, 20, "would not be afraid"),
        (21, 21, "men"),
        (22, 23, "to sin."),
    ],
    21: [
        (0, 3, "and if there were no"),
        (4, 5, "law"),
        (6, 8, "given,"),
        (9, 12, "if men sinned,"),
        (13, 17, "what"),
        (18, 21, "could do"),
        (22, 24, "justice,"),
        (25, 29, "or mercy"),
        (30, 30, "either,"),
        (31, 31, "for"),
        (32, 35, "there would be no"),
        (36, 38, "claim of theirs"),
        (39, 43, "upon the creature?"),
    ],
    22: [
        (0, 0, "But"),
        (1, 5, "there is a law"),
        (6, 8, "given,"),
        (9, 13, "and a punishment affixed,"),
        (14, 16, "and a repentance"),
        (17, 19, "granted;"),
        (20, 22, "which repentance,"),
        (23, 25, "claimeth"),
        (26, 28, "mercy;"),
        (29, 30, "otherwise,"),
        (31, 35, "justice claimeth"),
        (36, 37, "the creature"),
        (38, 41, "and executeth the law,"),
        (42, 45, "and the law"),
        (46, 48, "inflicteth"),
        (49, 50, "the punishment;"),
        (51, 54, "if not so,"),
        (55, 58, "would be destroyed"),
        (59, 62, "the works of justice,"),
        (63, 67, "and would cease"),
        (68, 69, "to be"),
        (70, 72, "God"),
        (73, 74, "a God."),
    ],
    23: [
        (0, 3, "But ceaseth not"),
        (4, 8, "the being of God"),
        (9, 10, "as God,"),
        (11, 14, "and claimeth"),
        (15, 17, "mercy"),
        (18, 21, "the penitent,"),
        (22, 25, "and cometh"),
        (26, 28, "mercy"),
        (29, 32, "because of the atonement;"),
        (33, 35, "and bringeth to pass"),
        (36, 38, "the atonement"),
        (39, 41, "the resurrection"),
        (42, 45, "of the dead;"),
        (46, 50, "and the resurrection"),
        (51, 54, "of the dead"),
        (55, 59, "bringeth back men"),
        (60, 64, "into the presence of God;"),
        (65, 69, "and thus are restored"),
        (70, 72, "they"),
        (73, 75, "into his presence,"),
        (76, 77, "to be judged"),
        (78, 80, "according to"),
        (81, 83, "their works,"),
        (84, 88, "according to the law"),
        (89, 91, "and justice."),
    ],
    24: [
        (0, 1, "For behold,"),
        (2, 6, "justice exerciseth"),
        (7, 9, "all his demands;"),
        (10, 13, "and also claimeth"),
        (14, 17, "mercy"),
        (18, 19, "all things"),
        (20, 23, "which are her own;"),
        (24, 26, "and thus,"),
        (27, 30, "none"),
        (31, 35, "but only they"),
        (36, 38, "who truly repent"),
        (39, 40, "are saved."),
    ],
    25: [
        (0, 2, "What,"),
        (3, 6, "do ye suppose"),
        (7, 8, "can"),
        (9, 12, "mercy"),
        (13, 14, "rob"),
        (15, 16, "justice?"),
        (17, 20, "I say"),
        (21, 23, "unto you,"),
        (24, 25, "Nay;"),
        (26, 29, "not one whit"),
        (30, 31, "single."),
        (32, 34, "If so,"),
        (35, 39, "would cease to be"),
        (40, 41, "God"),
        (42, 43, "a God."),
    ],
    26: [
        (0, 4, "and thus bringeth about"),
        (5, 7, "God"),
        (8, 10, "his great purposes"),
        (11, 12, "and eternal,"),
        (13, 16, "which were prepared"),
        (17, 21, "from the foundation of the world."),
        (22, 27, "and thus cometh about"),
        (28, 30, "the salvation"),
        (31, 35, "and the redemption of men,"),
        (36, 39, "and their destruction"),
        (40, 44, "and their misery also."),
    ],
    27: [
        (0, 1, "Therefore,"),
        (2, 4, "my son,"),
        (5, 7, "whosoever"),
        (8, 10, "will come"),
        (11, 14, "may come"),
        (15, 17, "and drink freely"),
        (18, 22, "of the waters of life;"),
        (23, 26, "and whosoever"),
        (27, 30, "will not come,"),
        (31, 34, "the same"),
        (35, 39, "is not compelled to come;"),
        (40, 44, "but in the last day,"),
        (45, 49, "it shall be restored"),
        (50, 52, "unto him"),
        (53, 57, "according to his deeds."),
    ],
    28: [
        (0, 4, "If he has desired"),
        (5, 8, "to do evil,"),
        (9, 12, "and hath not repented"),
        (13, 15, "in his days,"),
        (16, 16, "behold,"),
        (17, 20, "shall be done"),
        (21, 22, "evil"),
        (23, 25, "unto him,"),
        (26, 28, "according to"),
        (29, 33, "the restoration of God."),
    ],
    29: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 8, "I desire"),
        (9, 13, "that ye let these things"),
        (14, 17, "trouble no more"),
        (18, 20, "you,"),
        (21, 25, "and only your sins"),
        (26, 30, "let trouble you,"),
        (31, 33, "with that trouble"),
        (34, 39, "which shall bring you down"),
        (40, 42, "unto repentance."),
    ],
    30: [
        (0, 0, "O,"),
        (1, 3, "my son,"),
        (4, 6, "I desire"),
        (7, 11, "that ye deny no more"),
        (12, 16, "the justice of God."),
        (17, 20, "Do not endeavor"),
        (21, 24, "to excuse yourself"),
        (25, 28, "in the least point"),
        (29, 32, "because of your sins,"),
        (33, 35, "by denying"),
        (36, 38, "the justice"),
        (39, 41, "of God;"),
        (42, 46, "but let"),
        (47, 51, "the justice of God,"),
        (52, 55, "and his mercy,"),
        (56, 58, "and his long-suffering"),
        (59, 62, "have full sway upon"),
        (63, 64, "your heart;"),
        (65, 68, "and let"),
        (69, 70, "this thing"),
        (71, 75, "bring you down"),
        (76, 77, "low"),
        (78, 80, "to the dust"),
        (81, 83, "in humility."),
    ],
    31: [
        (0, 2, "And now,"),
        (3, 5, "O my son,"),
        (6, 11, "ye are called of God"),
        (12, 17, "to preach the word"),
        (18, 20, "unto this people."),
        (21, 23, "And now,"),
        (24, 26, "my son,"),
        (27, 31, "go thy way,"),
        (32, 35, "declare the word"),
        (36, 38, "with truth"),
        (39, 41, "and soberness,"),
        (42, 47, "that thou mayest bring"),
        (48, 49, "souls"),
        (50, 52, "unto repentance,"),
        (53, 57, "that may have"),
        (58, 61, "the great plan"),
        (62, 65, "of mercy"),
        (66, 67, "claim"),
        (68, 70, "upon them."),
        (71, 75, "And may God grant"),
        (76, 78, "grant"),
        (79, 81, "unto you"),
        (82, 85, "even according to"),
        (86, 87, "my words."),
        (88, 88, "Amen."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
