"""Hand-curated TAM-phrase gloss overrides for Mosaea 3 — the angel's words to King Benjamin concerning Christ.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
pronouns absorbed only when their token is IN the span (rule 2), NP/PP atoms
split (rule 3), `mai`-as-"from" (rule 7), no anaphoric-`ai` fillers when a
PP/object follows (rule 1), `mafai ona`/`ina ia`/`ina ua` bound (rules 13/15),
vocative `e`/`E …e` folded as "O X" (rule 12), directional "forth" dropped
(rule 12a). No pronoun/TAM word injected into a cell whose span lacks that
token; no content word repeats across adjacent cells (except authentic Samoan
doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah3.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 3
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And again also,"),
        (3, 5, "O my brethren,"),
        (6, 8, "I desire"),
        (9, 10, "that"),
        (11, 13, "ye hearken,"),
        (14, 17, "for there are many"),
        (18, 20, "other things"),
        (21, 23, "I desire"),
        (24, 26, "to speak"),
        (27, 29, "unto you;"),
        (30, 31, "for behold,"),
        (32, 35, "I have"),
        (36, 37, "things"),
        (38, 40, "to tell"),
        (41, 43, "unto you"),
        (44, 47, "concerning that"),
        (48, 52, "which is to come."),
    ],
    2: [
        (0, 0, "And"),
        (1, 2, "the things"),
        (3, 8, "which I shall tell"),
        (9, 11, "unto you"),
        (12, 14, "are made known"),
        (15, 17, "unto me"),
        (18, 20, "by an angel"),
        (21, 23, "from God."),
        (24, 24, "And"),
        (25, 29, "he said"),
        (30, 32, "unto me:"),
        (33, 35, "Awake;"),
        (36, 36, "and"),
        (37, 39, "I awoke,"),
        (40, 41, "and behold"),
        (42, 46, "he stood"),
        (47, 49, "before me."),
    ],
    3: [
        (0, 0, "And"),
        (1, 5, "he said"),
        (6, 8, "unto me:"),
        (9, 11, "Awake,"),
        (12, 14, "and hear"),
        (15, 16, "the words"),
        (17, 22, "which I shall tell"),
        (23, 25, "thee;"),
        (26, 27, "for behold,"),
        (28, 30, "I am come"),
        (31, 33, "to declare"),
        (34, 36, "unto thee"),
        (37, 38, "glad tidings"),
        (39, 42, "of great joy."),
    ],
    4: [
        (0, 0, "For"),
        (1, 4, "the Lord hath heard"),
        (5, 7, "thy prayers,"),
        (8, 12, "and hath judged"),
        (13, 14, "thy righteousness,"),
        (15, 19, "and hath sent"),
        (20, 20, "me"),
        (21, 23, "to declare"),
        (24, 26, "unto thee"),
        (27, 28, "that"),
        (29, 30, "thou rejoice;"),
        (31, 31, "and"),
        (32, 33, "that"),
        (34, 35, "mayest"),
        (36, 38, "thou declare"),
        (39, 41, "unto thy people,"),
        (42, 43, "that"),
        (44, 46, "may also"),
        (47, 47, "be filled"),
        (48, 49, "they"),
        (50, 52, "with joy."),
    ],
    5: [
        (0, 1, "For behold,"),
        (2, 6, "the time cometh,"),
        (7, 10, "and is not"),
        (11, 13, "far distant,"),
        (14, 18, "shall come down"),
        (19, 21, "from heaven"),
        (22, 26, "among the children"),
        (27, 28, "of men,"),
        (29, 31, "with power,"),
        (32, 35, "the Lord Omnipotent"),
        (36, 39, "who reigneth,"),
        (40, 44, "who was,"),
        (45, 49, "and is,"),
        (50, 53, "from all eternity"),
        (54, 55, "even unto"),
        (56, 59, "all eternity,"),
        (60, 66, "and he shall dwell"),
        (67, 71, "in a tabernacle of clay,"),
        (72, 72, "and"),
        (73, 77, "shall go forth"),
        (78, 81, "amongst men,"),
        (82, 85, "working mighty miracles,"),
        (86, 88, "such as"),
        (89, 90, "healing"),
        (91, 93, "of the sick,"),
        (94, 95, "raising"),
        (96, 99, "the dead,"),
        (100, 100, "causing to walk"),
        (101, 104, "the lame,"),
        (105, 106, "and causing to see"),
        (107, 109, "the blind,"),
        (110, 113, "and making to hear"),
        (114, 116, "the deaf,"),
        (117, 118, "and curing"),
        (119, 123, "all manner of diseases."),
    ],
    6: [
        (0, 0, "And"),
        (1, 7, "he shall cast out"),
        (8, 8, "devils"),
        (9, 12, "or the evil spirits"),
        (13, 14, "which dwell"),
        (15, 16, "in the hearts"),
        (17, 19, "of the children"),
        (20, 21, "of men."),
    ],
    7: [
        (0, 1, "And behold,"),
        (2, 7, "he shall suffer"),
        (8, 9, "temptations,"),
        (10, 14, "and pain of body,"),
        (15, 18, "hunger,"),
        (19, 22, "thirst,"),
        (23, 25, "and fatigue,"),
        (26, 28, "even more"),
        (29, 32, "than that"),
        (33, 37, "which man can"),
        (38, 39, "suffer,"),
        (40, 43, "except unto death;"),
        (44, 45, "for behold,"),
        (46, 49, "blood cometh"),
        (50, 53, "from every pore,"),
        (54, 54, "for"),
        (55, 59, "so great shall be"),
        (60, 62, "his anguish"),
        (63, 66, "for the wickedness"),
        (67, 69, "and the abominations"),
        (70, 72, "of his people."),
    ],
    8: [
        (0, 6, "And he shall be called"),
        (7, 9, "Jesus Christ,"),
        (10, 12, "the Son"),
        (13, 15, "of God,"),
        (16, 18, "the Father"),
        (19, 21, "of heaven"),
        (22, 24, "and earth,"),
        (25, 27, "the Creator"),
        (28, 30, "of all things"),
        (31, 33, "from the beginning;"),
        (34, 34, "and"),
        (35, 37, "his mother"),
        (38, 41, "shall be called"),
        (42, 43, "Mary."),
    ],
    9: [
        (0, 1, "And behold,"),
        (2, 6, "he cometh"),
        (7, 10, "unto his own,"),
        (11, 12, "that"),
        (13, 14, "might"),
        (15, 19, "salvation come"),
        (20, 24, "unto the children of men"),
        (25, 27, "even through"),
        (28, 30, "faith"),
        (31, 33, "on his name;"),
        (34, 37, "and even notwithstanding"),
        (38, 41, "all these things"),
        (42, 46, "they shall consider"),
        (47, 48, "him"),
        (49, 51, "a man,"),
        (52, 54, "and say"),
        (55, 58, "that he hath"),
        (59, 60, "a devil,"),
        (61, 61, "and"),
        (62, 66, "they shall scourge"),
        (67, 69, "him,"),
        (70, 70, "and"),
        (71, 76, "they shall also crucify"),
        (77, 78, "him."),
    ],
    10: [
        (0, 0, "And"),
        (1, 7, "he shall rise"),
        (8, 12, "the third day"),
        (13, 16, "from the dead;"),
        (17, 18, "and behold,"),
        (19, 22, "he standeth"),
        (23, 26, "to judge the world;"),
        (27, 28, "and behold,"),
        (29, 30, "are done"),
        (31, 33, "all these things"),
        (34, 35, "that"),
        (36, 38, "might come"),
        (39, 41, "a righteous judgment"),
        (42, 44, "upon"),
        (45, 46, "the children"),
        (47, 48, "of men."),
    ],
    11: [
        (0, 1, "For behold,"),
        (2, 4, "and also atoneth"),
        (5, 6, "his blood"),
        (7, 11, "for the sins of those"),
        (12, 15, "who have fallen"),
        (16, 18, "by the transgression"),
        (19, 20, "of Adam,"),
        (21, 24, "who have died"),
        (25, 29, "not knowing"),
        (30, 32, "the will"),
        (33, 35, "of God"),
        (36, 37, "concerning"),
        (38, 41, "them,"),
        (42, 46, "or who have sinned"),
        (47, 50, "ignorantly."),
    ],
    12: [
        (0, 0, "But"),
        (1, 2, "wo, wo"),
        (3, 6, "unto him who knoweth"),
        (7, 10, "that he rebelleth"),
        (11, 14, "against God!"),
        (15, 15, "For"),
        (16, 19, "cometh not"),
        (20, 21, "salvation"),
        (22, 25, "to none such"),
        (26, 29, "except through"),
        (30, 32, "repentance"),
        (33, 35, "and faith"),
        (36, 38, "on the Lord"),
        (39, 41, "Jesus Christ."),
    ],
    13: [
        (0, 3, "And hath sent"),
        (4, 8, "the Lord God"),
        (9, 11, "his holy prophets"),
        (12, 16, "among the children"),
        (17, 17, "all"),
        (18, 19, "of men,"),
        (20, 22, "to declare"),
        (23, 24, "these things"),
        (25, 27, "to every kindred,"),
        (28, 28, "nation,"),
        (29, 30, "and tongue,"),
        (31, 32, "that"),
        (33, 33, "might"),
        (34, 37, "whosoever"),
        (38, 40, "of them"),
        (41, 42, "should believe"),
        (43, 47, "that should come"),
        (48, 48, "Christ,"),
        (49, 50, "then receive"),
        (51, 52, "remission"),
        (53, 56, "of their sins,"),
        (57, 58, "and rejoice"),
        (59, 62, "with exceeding great joy,"),
        (63, 65, "even as though"),
        (66, 72, "he had already come"),
        (73, 77, "among them."),
    ],
    14: [
        (0, 0, "Yet"),
        (1, 2, "saw"),
        (3, 6, "the Lord God"),
        (7, 9, "that his people"),
        (10, 12, "were a people"),
        (13, 15, "stiffnecked,"),
        (16, 20, "and he appointed"),
        (21, 23, "unto them"),
        (24, 25, "a law,"),
        (26, 30, "even the law"),
        (31, 32, "of Moses."),
    ],
    15: [
        (0, 3, "And many signs,"),
        (4, 6, "and wonders,"),
        (7, 8, "and types,"),
        (9, 11, "and shadows"),
        (12, 16, "showed he"),
        (17, 20, "unto them,"),
        (21, 23, "concerning"),
        (24, 26, "his coming;"),
        (27, 31, "and also spake"),
        (32, 33, "holy prophets"),
        (34, 37, "unto them"),
        (38, 40, "concerning"),
        (41, 43, "his coming;"),
        (44, 45, "and yet"),
        (46, 48, "they hardened"),
        (49, 51, "their hearts,"),
        (52, 55, "and understood not"),
        (56, 59, "that there is no worth"),
        (60, 62, "of the law"),
        (63, 64, "of Moses"),
        (65, 69, "except through"),
        (70, 72, "the atonement"),
        (73, 75, "of his blood."),
    ],
    16: [
        (0, 4, "And even if"),
        (5, 8, "were possible to sin"),
        (9, 10, "little children"),
        (11, 15, "could not be saved"),
        (16, 17, "them;"),
        (18, 22, "but I say"),
        (23, 25, "unto you"),
        (26, 29, "they are blessed;"),
        (30, 31, "for behold,"),
        (32, 35, "as in Adam,"),
        (36, 40, "or by nature,"),
        (41, 44, "they fall,"),
        (45, 47, "even so"),
        (48, 49, "atoneth"),
        (50, 51, "the blood"),
        (52, 53, "of Christ"),
        (54, 57, "for their sins."),
    ],
    17: [
        (0, 0, "And"),
        (1, 5, "moreover,"),
        (6, 9, "I say"),
        (10, 12, "unto you,"),
        (13, 15, "there shall"),
        (16, 18, "be no"),
        (19, 21, "other name"),
        (22, 24, "given"),
        (25, 29, "nor any other"),
        (30, 30, "way"),
        (31, 34, "nor means"),
        (35, 37, "whereby can"),
        (38, 40, "come"),
        (41, 42, "salvation"),
        (43, 45, "unto the children"),
        (46, 47, "of men,"),
        (48, 52, "only in the name"),
        (53, 54, "of Christ,"),
        (55, 58, "the Lord Omnipotent."),
    ],
    18: [
        (0, 1, "For behold"),
        (2, 6, "he judgeth,"),
        (7, 9, "and is just"),
        (10, 11, "his judgment;"),
        (12, 15, "and perisheth not"),
        (16, 18, "the infant"),
        (19, 20, "that dieth"),
        (21, 23, "in his infancy;"),
        (24, 24, "but"),
        (25, 26, "drink"),
        (27, 29, "grown men"),
        (30, 31, "damnation"),
        (32, 36, "to their own souls"),
        (37, 38, "except"),
        (39, 41, "they humble"),
        (42, 44, "themselves"),
        (45, 46, "and become"),
        (47, 51, "as little children,"),
        (52, 53, "and believe"),
        (54, 56, "that salvation"),
        (57, 59, "was,"),
        (60, 63, "and is,"),
        (64, 64, "and"),
        (65, 69, "is to come,"),
        (70, 72, "through"),
        (73, 76, "the atoning blood"),
        (77, 78, "of Christ,"),
        (79, 82, "the Lord Omnipotent."),
    ],
    19: [
        (0, 0, "For"),
        (1, 4, "the natural man"),
        (5, 7, "is an enemy"),
        (8, 10, "to God,"),
        (11, 14, "and has been"),
        (15, 19, "from the fall of Adam,"),
        (20, 20, "and"),
        (21, 25, "will be so,"),
        (26, 29, "forever and ever,"),
        (30, 31, "unless"),
        (32, 36, "he yields"),
        (37, 38, "to the enticings"),
        (39, 42, "of the Holy Spirit,"),
        (43, 45, "and putteth off"),
        (46, 48, "the natural man"),
        (49, 53, "and becometh a saint"),
        (54, 55, "through"),
        (56, 58, "the atonement"),
        (59, 62, "of Christ the Lord,"),
        (63, 64, "and becometh"),
        (65, 69, "as a child,"),
        (70, 71, "submissive,"),
        (72, 72, "meek,"),
        (73, 73, "humble,"),
        (74, 74, "patient,"),
        (75, 78, "full of love,"),
        (79, 81, "willing to submit"),
        (82, 84, "to all things"),
        (85, 89, "which the Lord seeth fit"),
        (90, 92, "fit to"),
        (93, 94, "inflict"),
        (95, 97, "upon him,"),
        (98, 101, "even as submitteth"),
        (102, 104, "a child"),
        (105, 107, "to his father."),
    ],
    20: [
        (0, 0, "And"),
        (1, 5, "moreover,"),
        (6, 9, "I say"),
        (10, 12, "unto you,"),
        (13, 17, "shall come"),
        (18, 19, "the time"),
        (20, 23, "when shall spread"),
        (24, 25, "the knowledge"),
        (26, 28, "of a Savior"),
        (29, 31, "throughout every nation,"),
        (32, 32, "kindred,"),
        (33, 33, "tongue,"),
        (34, 35, "and people."),
    ],
    21: [
        (0, 1, "And behold,"),
        (2, 6, "when that time cometh,"),
        (7, 9, "there shall be"),
        (10, 12, "none"),
        (13, 14, "found"),
        (15, 17, "blameless"),
        (18, 22, "before God,"),
        (23, 26, "except little children,"),
        (27, 31, "only through"),
        (32, 34, "repentance"),
        (35, 37, "and faith"),
        (38, 40, "on the name"),
        (41, 43, "of the Lord"),
        (44, 47, "God Omnipotent."),
    ],
    22: [
        (0, 0, "And"),
        (1, 3, "even"),
        (4, 7, "at this time,"),
        (8, 10, "when thou hast ended"),
        (11, 13, "thy teaching"),
        (14, 16, "thy people"),
        (17, 17, "the things"),
        (18, 21, "which hath commanded thee"),
        (22, 26, "the Lord thy God,"),
        (27, 30, "no longer"),
        (31, 33, "are found"),
        (34, 35, "they"),
        (36, 39, "blameless"),
        (40, 42, "in the sight"),
        (43, 45, "of God,"),
        (46, 48, "only"),
        (49, 51, "according to"),
        (52, 52, "the words"),
        (53, 57, "which I have spoken"),
        (58, 60, "unto thee."),
    ],
    23: [
        (0, 2, "And now"),
        (3, 6, "I have spoken"),
        (7, 8, "the words"),
        (9, 12, "which hath commanded me"),
        (13, 17, "the Lord God."),
    ],
    24: [
        (0, 3, "And thus"),
        (4, 5, "saith"),
        (6, 8, "the Lord:"),
        (9, 13, "shall stand"),
        (14, 15, "these words"),
        (16, 19, "as a bright testimony"),
        (20, 24, "against this people,"),
        (25, 28, "at the judgment day;"),
        (29, 32, "wherefore"),
        (33, 37, "shall be judged"),
        (38, 39, "them,"),
        (40, 42, "every man"),
        (43, 45, "according to"),
        (46, 47, "his works,"),
        (48, 49, "whether good,"),
        (50, 51, "or evil."),
    ],
    25: [
        (0, 0, "And"),
        (1, 4, "if be not right"),
        (5, 7, "their works"),
        (8, 11, "they are consigned"),
        (12, 16, "to an awful view"),
        (17, 21, "of their own guilt"),
        (22, 26, "and abominations,"),
        (27, 27, "which"),
        (28, 31, "they shall"),
        (32, 34, "shrink away"),
        (35, 39, "from the presence of the Lord"),
        (40, 42, "into a state"),
        (43, 45, "of misery"),
        (46, 48, "and torment"),
        (49, 51, "endless,"),
        (52, 55, "they cannot"),
        (56, 60, "return again;"),
        (61, 62, "therefore"),
        (63, 66, "they have drunk"),
        (67, 68, "damnation"),
        (69, 73, "to their own souls."),
    ],
    26: [
        (0, 1, "Therefore,"),
        (2, 5, "they have drunk"),
        (6, 8, "out of the cup"),
        (9, 11, "of the wrath"),
        (12, 14, "of God,"),
        (15, 17, "which justice"),
        (18, 21, "could not"),
        (22, 23, "deny"),
        (24, 27, "unto them"),
        (28, 30, "than"),
        (31, 34, "could deny"),
        (35, 36, "it"),
        (37, 39, "the necessity"),
        (40, 44, "of the fall of Adam"),
        (45, 48, "because of his partaking"),
        (49, 52, "of the forbidden fruit;"),
        (53, 54, "therefore,"),
        (55, 57, "no more"),
        (58, 60, "could"),
        (61, 61, "obtain"),
        (62, 65, "mercy"),
        (66, 67, "claim"),
        (68, 71, "on them"),
        (72, 73, "forever."),
    ],
    27: [
        (0, 0, "And"),
        (1, 4, "their torment"),
        (5, 9, "is as a lake"),
        (10, 10, "of fire"),
        (11, 13, "and brimstone,"),
        (14, 17, "whose flames"),
        (18, 20, "are unquenchable,"),
        (21, 24, "and whose smoke"),
        (25, 28, "ascendeth up"),
        (29, 30, "on high"),
        (31, 35, "forever and ever."),
        (36, 39, "Thus hath commanded"),
        (40, 41, "me"),
        (42, 44, "the Lord."),
        (45, 45, "Amen."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
