"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 20 — the Lord
directs Ammon and Lamoni to Middoni; they meet Lamoni's father, the king
over all the land; Ammon defends Lamoni and confounds his father; the
father grants the release of the imprisoned brethren.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15).

Em-dash token split in the source per rule 11: `a’u—Alu` (v5) — so
v5 = 50 tokens.

    python3 build_overrides_alma20.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 20

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 8, "when they had established"),
        (9, 10, "a church"),
        (11, 13, "in that land,"),
        (14, 15, "desired"),
        (16, 19, "king Lamoni"),
        (20, 21, "that Ammon"),
        (22, 27, "should go with him"),
        (28, 32, "to the land of Nephi,"),
        (33, 36, "that might"),
        (37, 39, "he show"),
        (40, 41, "him"),
        (42, 44, "unto his father."),
    ],
    2: [
        (0, 3, "And came"),
        (4, 8, "the voice of the Lord"),
        (9, 10, "to Ammon,"),
        (11, 13, "saying:"),
        (14, 16, "thou shalt not"),
        (17, 19, "go up to"),
        (20, 23, "the land of Nephi,"),
        (24, 25, "for behold,"),
        (26, 29, "will seek"),
        (30, 32, "the king"),
        (33, 34, "thy life;"),
        (35, 39, "but thou shalt go to"),
        (40, 43, "the land of Middoni;"),
        (44, 45, "for behold,"),
        (46, 50, "thy brother Aaron,"),
        (51, 53, "and also Muloki"),
        (54, 55, "and Ammah,"),
        (56, 59, "are in"),
        (60, 61, "prison."),
    ],
    3: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 7, "when Ammon had heard"),
        (8, 10, "this,"),
        (11, 14, "he said"),
        (15, 16, "unto Lamoni:"),
        (17, 17, "Behold,"),
        (18, 20, "my brother"),
        (21, 24, "and brethren"),
        (25, 28, "are in"),
        (29, 30, "prison"),
        (31, 32, "at Middoni,"),
        (33, 36, "and I go"),
        (37, 40, "that may"),
        (41, 42, "I deliver"),
        (43, 44, "them."),
    ],
    4: [
        (0, 1, "Now"),
        (2, 4, "said"),
        (5, 5, "Lamoni"),
        (6, 7, "unto Ammon:"),
        (8, 10, "I know,"),
        (11, 15, "thou canst do"),
        (16, 18, "all things"),
        (19, 22, "in the strength of"),
        (23, 24, "the Lord."),
        (25, 26, "But behold,"),
        (27, 30, "I will"),
        (31, 32, "go"),
        (33, 35, "with thee"),
        (36, 40, "to the land of Middoni;"),
        (41, 45, "for the king of"),
        (46, 49, "the land of Middoni,"),
        (50, 54, "whose name was Antiomno,"),
        (55, 57, "is a friend"),
        (58, 60, "unto me;"),
        (61, 62, "therefore"),
        (63, 66, "I go"),
        (67, 68, "unto"),
        (69, 72, "the land of Middoni,"),
        (73, 76, "that may"),
        (77, 78, "I flatter"),
        (79, 83, "the king of the land,"),
        (84, 84, "and"),
        (85, 90, "he will bring forth"),
        (91, 92, "out"),
        (93, 94, "thy brethren"),
        (95, 97, "out of prison."),
        (98, 99, "Now"),
        (100, 102, "said"),
        (103, 103, "Lamoni"),
        (104, 106, "unto him:"),
        (107, 108, "Who"),
        (109, 112, "told"),
        (113, 115, "thee"),
        (116, 120, "that thy brethren were"),
        (121, 123, "in prison?"),
    ],
    5: [
        (0, 0, "And"),
        (1, 3, "said"),
        (4, 4, "Ammon"),
        (5, 7, "unto him:"),
        (8, 11, "No one"),
        (12, 15, "hath told"),
        (16, 18, "me,"),
        (19, 20, "save it be"),
        (21, 22, "God;"),
        (23, 23, "and"),
        (24, 27, "he said"),
        (28, 30, "unto me—"),
        (31, 31, "Go"),
        (32, 33, "and deliver"),
        (34, 35, "thy brethren,"),
        (36, 36, "for"),
        (37, 41, "they are"),
        (42, 44, "in prison"),
        (45, 49, "in the land of Middoni."),
    ],
    6: [
        (0, 1, "Now"),
        (2, 5, "when had heard"),
        (6, 6, "Lamoni"),
        (7, 9, "this,"),
        (10, 13, "he caused"),
        (14, 15, "that should make ready"),
        (16, 18, "his servants"),
        (19, 20, "his horses"),
        (21, 23, "and his chariots."),
    ],
    7: [
        (0, 0, "And"),
        (1, 4, "he said"),
        (5, 6, "unto Ammon:"),
        (7, 9, "Come,"),
        (10, 13, "I will"),
        (14, 15, "go"),
        (16, 18, "with thee"),
        (19, 23, "to the land of Middoni,"),
        (24, 28, "and I will"),
        (29, 30, "plead"),
        (31, 33, "with the king"),
        (34, 34, "that"),
        (35, 40, "he will bring forth"),
        (41, 43, "out"),
        (44, 45, "thy brethren"),
        (46, 48, "out of prison."),
    ],
    8: [
        (0, 3, "And it came to pass that"),
        (4, 6, "as were journeying"),
        (7, 9, "Ammon and Lamoni"),
        (10, 10, "thither,"),
        (11, 14, "they met"),
        (15, 18, "the father of Lamoni,"),
        (19, 23, "who was"),
        (24, 24, "king"),
        (25, 27, "over"),
        (28, 30, "all the land."),
    ],
    9: [
        (0, 1, "And behold,"),
        (2, 4, "said"),
        (5, 8, "the father of Lamoni"),
        (9, 11, "unto him:"),
        (12, 12, "Why"),
        (13, 17, "didst thou not come"),
        (18, 20, "to the feast"),
        (21, 25, "on that great day"),
        (26, 29, "when I made"),
        (30, 31, "a feast"),
        (32, 35, "unto all my sons,"),
        (36, 39, "and unto my people?"),
    ],
    10: [
        (0, 0, "And"),
        (1, 5, "he also said:"),
        (6, 7, "Whither"),
        (8, 12, "art thou going"),
        (13, 14, "thither"),
        (15, 18, "with this Nephite,"),
        (19, 22, "who is one of"),
        (23, 24, "the children of"),
        (25, 27, "a liar?"),
    ],
    11: [
        (0, 3, "And it came to pass that"),
        (4, 5, "rehearsed"),
        (6, 7, "Lamoni"),
        (8, 10, "unto him"),
        (11, 12, "the place"),
        (13, 17, "where he was going"),
        (18, 19, "thither,"),
        (20, 20, "for"),
        (21, 24, "he feared"),
        (25, 26, "to offend"),
        (27, 29, "him."),
    ],
    12: [
        (0, 5, "And he also rehearsed"),
        (6, 8, "unto him"),
        (9, 12, "all the cause of"),
        (13, 16, "his tarrying"),
        (17, 20, "in his own kingdom,"),
        (21, 26, "that he did not go"),
        (27, 29, "unto his father"),
        (30, 32, "to the feast"),
        (33, 36, "which he had prepared."),
    ],
    13: [
        (0, 2, "And now"),
        (3, 8, "when had rehearsed"),
        (9, 10, "Lamoni"),
        (11, 13, "all these things"),
        (14, 16, "unto him,"),
        (17, 17, "behold,"),
        (18, 21, "to his astonishment,"),
        (22, 24, "was angry"),
        (25, 26, "his father"),
        (27, 29, "with him,"),
        (30, 32, "and said:"),
        (33, 33, "Lamoni,"),
        (34, 38, "thou art going"),
        (39, 39, "forth"),
        (40, 41, "to deliver"),
        (42, 44, "these Nephites,"),
        (45, 49, "who are sons of"),
        (50, 52, "a liar."),
        (53, 53, "Behold,"),
        (54, 57, "he robbed"),
        (58, 60, "our fathers;"),
        (61, 63, "and now"),
        (64, 67, "are also come"),
        (68, 69, "his children"),
        (70, 74, "amongst us"),
        (75, 77, "that they may"),
        (78, 83, "by their cunning"),
        (84, 87, "and their lyings"),
        (88, 90, "deceive"),
        (91, 92, "us,"),
        (93, 96, "that may"),
        (97, 99, "they again rob"),
        (100, 102, "our property."),
    ],
    14: [
        (0, 1, "Now"),
        (2, 3, "commanded"),
        (4, 8, "the father of Lamoni"),
        (9, 10, "him"),
        (11, 13, "that should"),
        (14, 15, "he slay"),
        (16, 16, "Ammon"),
        (17, 19, "with the sword."),
        (20, 24, "And he also commanded"),
        (25, 26, "him"),
        (27, 33, "that he should not go"),
        (34, 38, "to the land of Middoni,"),
        (39, 45, "but that he should return"),
        (46, 48, "with him"),
        (49, 53, "to the land of Ishmael."),
    ],
    15: [
        (0, 0, "But"),
        (1, 3, "said"),
        (4, 4, "Lamoni"),
        (5, 7, "unto him:"),
        (8, 11, "I will not slay"),
        (12, 12, "Ammon,"),
        (13, 15, "neither will I"),
        (16, 19, "return to"),
        (20, 23, "the land of Ishmael,"),
        (24, 28, "but I go to"),
        (29, 32, "the land of Middoni"),
        (33, 37, "that I may"),
        (38, 38, "release"),
        (39, 41, "the brethren of Ammon,"),
        (42, 42, "for"),
        (43, 45, "I know"),
        (46, 48, "that they"),
        (49, 52, "are just men"),
        (53, 57, "and holy prophets of"),
        (58, 60, "the true God."),
    ],
    16: [
        (0, 1, "Now"),
        (2, 5, "when had heard"),
        (6, 7, "his father"),
        (8, 10, "these words,"),
        (11, 14, "he was angry"),
        (15, 17, "with him,"),
        (18, 21, "and he drew"),
        (22, 23, "his sword"),
        (24, 27, "that might"),
        (28, 29, "he smite"),
        (30, 31, "him"),
        (32, 34, "to the earth."),
    ],
    17: [
        (0, 0, "But"),
        (1, 3, "stood forth"),
        (4, 4, "Ammon"),
        (5, 7, "and said"),
        (8, 10, "unto him:"),
        (11, 11, "Behold,"),
        (12, 16, "thou shalt not slay"),
        (17, 18, "thy son;"),
        (19, 22, "nevertheless,"),
        (23, 26, "it were better"),
        (27, 32, "that he should fall"),
        (33, 35, "than thee,"),
        (36, 37, "for behold,"),
        (38, 41, "he has repented"),
        (42, 44, "of his sins;"),
        (45, 50, "but if thou shouldst fall"),
        (51, 54, "at this time,"),
        (55, 57, "in thine anger,"),
        (58, 62, "could not be saved"),
        (63, 64, "thy soul."),
    ],
    18: [
        (0, 2, "And again,"),
        (3, 6, "it is expedient that"),
        (7, 8, "thou shouldst forbear;"),
        (9, 9, "for"),
        (10, 14, "if thou shouldst slay"),
        (15, 16, "thy son,"),
        (17, 19, "he being"),
        (20, 24, "an innocent man,"),
        (25, 29, "would cry"),
        (30, 31, "his blood"),
        (32, 34, "from the ground"),
        (35, 39, "to the Lord his God,"),
        (40, 42, "for vengeance"),
        (43, 45, "to come"),
        (46, 48, "upon thee;"),
        (49, 50, "and perhaps"),
        (51, 55, "would be lost"),
        (56, 57, "thy soul."),
    ],
    19: [
        (0, 1, "Now"),
        (2, 7, "when had said"),
        (8, 9, "Ammon"),
        (10, 11, "these words"),
        (12, 14, "unto him,"),
        (15, 18, "he answered"),
        (19, 21, "him,"),
        (22, 23, "saying:"),
        (24, 26, "I know"),
        (27, 30, "that if I should slay"),
        (31, 32, "my son,"),
        (33, 37, "that I should shed"),
        (38, 41, "innocent blood;"),
        (42, 42, "for"),
        (43, 45, "it is thou that"),
        (46, 47, "hast sought"),
        (48, 49, "to destroy"),
        (50, 51, "him."),
    ],
    20: [
        (0, 4, "And he stretched forth"),
        (5, 6, "his hand"),
        (7, 8, "to slay"),
        (9, 9, "Ammon."),
        (10, 10, "But"),
        (11, 14, "Ammon withstood"),
        (15, 16, "his blows,"),
        (17, 20, "and also smote"),
        (21, 22, "his arm"),
        (23, 27, "that could not"),
        (28, 29, "he use it."),
    ],
    21: [
        (0, 1, "Now"),
        (2, 5, "when saw"),
        (6, 7, "the king"),
        (8, 13, "that Ammon could slay"),
        (14, 15, "him,"),
        (16, 18, "he began to"),
        (19, 21, "he plead"),
        (22, 23, "with Ammon"),
        (24, 27, "that he would spare"),
        (28, 29, "his life."),
    ],
    22: [
        (0, 0, "But"),
        (1, 4, "Ammon raised"),
        (5, 6, "his sword,"),
        (7, 9, "and said"),
        (10, 12, "unto him:"),
        (13, 13, "Behold,"),
        (14, 18, "I will smite"),
        (19, 19, "thee"),
        (20, 21, "except"),
        (22, 25, "thou wilt grant"),
        (26, 28, "unto me"),
        (29, 32, "that I may"),
        (33, 35, "bring forth"),
        (36, 37, "my brethren"),
        (38, 40, "out of prison."),
    ],
    23: [
        (0, 1, "Now"),
        (2, 7, "the king fearing"),
        (8, 9, "lest be taken away"),
        (10, 11, "his life,"),
        (12, 14, "said:"),
        (15, 18, "If thou wilt spare"),
        (19, 19, "me,"),
        (20, 23, "I will"),
        (24, 25, "grant"),
        (26, 28, "unto thee"),
        (29, 31, "whatsoever"),
        (32, 36, "thou wilt ask,"),
        (37, 40, "even unto"),
        (41, 43, "half of"),
        (44, 45, "the kingdom."),
    ],
    24: [
        (0, 1, "Now"),
        (2, 6, "when Ammon saw"),
        (7, 9, "that he had wrought upon"),
        (10, 12, "the old king"),
        (13, 17, "according to his desire,"),
        (18, 21, "he said"),
        (22, 24, "unto him:"),
        (25, 29, "If thou wilt grant"),
        (30, 35, "that may be brought forth"),
        (36, 37, "my brethren"),
        (38, 40, "out of prison,"),
        (41, 44, "and also that may retain"),
        (45, 46, "Lamoni"),
        (47, 48, "his kingdom,"),
        (49, 54, "and that thou wilt not be displeased"),
        (55, 57, "with him,"),
        (58, 60, "but grant"),
        (61, 65, "that he may do"),
        (66, 69, "according to"),
        (70, 72, "his own desires"),
        (73, 76, "in whatsoever thing"),
        (77, 82, "he thinketh"),
        (83, 86, "then will I spare"),
        (87, 88, "thee;"),
        (89, 90, "but if not,"),
        (91, 95, "I will smite"),
        (96, 96, "thee"),
        (97, 99, "to the earth."),
    ],
    25: [
        (0, 1, "Now"),
        (2, 7, "when had said"),
        (8, 9, "Ammon"),
        (10, 11, "these words,"),
        (12, 15, "began to rejoice"),
        (16, 17, "the king"),
        (18, 20, "because of his life."),
    ],
    26: [
        (0, 5, "And when he saw"),
        (6, 9, "that had no desire"),
        (10, 11, "Ammon"),
        (12, 13, "to destroy"),
        (14, 15, "him,"),
        (16, 21, "and when he also saw"),
        (22, 25, "the great love"),
        (26, 27, "he had"),
        (28, 32, "for his son Lamoni,"),
        (33, 37, "he was astonished exceedingly,"),
        (38, 40, "and said:"),
        (41, 43, "Because"),
        (44, 48, "this is all"),
        (49, 53, "that thou hast desired,"),
        (54, 56, "that I would release"),
        (57, 58, "thy brethren,"),
        (59, 61, "and suffer"),
        (62, 64, "that should retain"),
        (65, 69, "my son Lamoni"),
        (70, 71, "his kingdom,"),
        (72, 72, "behold,"),
        (73, 76, "I will"),
        (77, 78, "grant"),
        (79, 81, "unto thee"),
        (82, 84, "that may retain"),
        (85, 87, "my son"),
        (88, 89, "his kingdom"),
        (90, 94, "from this time"),
        (95, 97, "and forever;"),
        (98, 102, "and I will"),
        (103, 105, "no more govern"),
        (106, 107, "him—"),
    ],
    27: [
        (0, 4, "and I will"),
        (5, 7, "also grant"),
        (8, 10, "unto thee"),
        (11, 16, "that may be brought forth"),
        (17, 18, "thy brethren"),
        (19, 21, "out of prison,"),
        (22, 27, "and may come"),
        (28, 32, "thou and thy brethren"),
        (33, 35, "unto me"),
        (36, 38, "in my kingdom;"),
        (39, 39, "for"),
        (40, 45, "I shall desire to see"),
        (46, 46, "greatly"),
        (47, 49, "thee."),
        (50, 53, "Now was astonished"),
        (54, 55, "the king"),
        (56, 57, "at the words"),
        (58, 62, "which he had spoken,"),
        (63, 65, "and also the words"),
        (66, 69, "which had spoken"),
        (70, 73, "his son Lamoni,"),
        (74, 75, "therefore"),
        (76, 79, "he was desirous"),
        (80, 83, "to learn them."),
    ],
    28: [
        (0, 3, "And it came to pass that"),
        (4, 8, "Ammon and Lamoni proceeded"),
        (9, 11, "their journey"),
        (12, 13, "towards"),
        (14, 17, "the land of Middoni."),
        (18, 20, "And found favor"),
        (21, 21, "Lamoni"),
        (22, 25, "in the eyes of"),
        (26, 30, "the king of the land;"),
        (31, 32, "therefore"),
        (33, 37, "were brought forth"),
        (38, 40, "the brethren of Ammon"),
        (41, 43, "out of prison."),
    ],
    29: [
        (0, 4, "And when Ammon did meet"),
        (5, 7, "them"),
        (8, 12, "he was exceedingly sorrowful,"),
        (13, 14, "for behold"),
        (15, 19, "they were naked,"),
        (20, 24, "and were exceedingly worn"),
        (25, 27, "their skins"),
        (28, 30, "because of being bound"),
        (31, 33, "with strong cords."),
        (34, 39, "And they also had suffered"),
        (40, 43, "hunger,"),
        (44, 45, "thirst,"),
        (46, 50, "and all kinds of afflictions;"),
        (51, 54, "nevertheless"),
        (55, 57, "they were patient"),
        (58, 62, "in all their sufferings."),
    ],
    30: [
        (0, 0, "And,"),
        (1, 4, "as it happened,"),
        (5, 8, "it was their lot"),
        (9, 12, "to have fallen"),
        (13, 15, "into the hands of"),
        (16, 17, "a people"),
        (18, 20, "more hardened"),
        (21, 23, "and more stiffnecked;"),
        (24, 25, "therefore"),
        (26, 31, "they would not hearken"),
        (32, 35, "unto their words,"),
        (36, 41, "and they had driven out"),
        (42, 43, "them"),
        (44, 45, "forth,"),
        (46, 48, "and had smitten"),
        (49, 50, "them,"),
        (51, 52, "and had driven"),
        (53, 54, "them"),
        (55, 57, "from house"),
        (58, 60, "to house,"),
        (61, 65, "and from place"),
        (66, 68, "to place,"),
        (69, 71, "even until"),
        (72, 74, "they had arrived"),
        (75, 79, "in the land of Middoni;"),
        (80, 82, "and there"),
        (83, 87, "they were taken"),
        (88, 89, "and cast"),
        (90, 92, "into prison,"),
        (93, 94, "and bound"),
        (95, 97, "with strong cords,"),
        (98, 99, "and kept"),
        (100, 101, "them"),
        (102, 104, "in prison"),
        (105, 108, "many days,"),
        (109, 113, "and were delivered"),
        (114, 117, "by Lamoni and Ammon."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
