"""
Hand-curated TAM-phrase gloss overrides for Eteru (Ether) 3 — the brother of Jared molts
sixteen small clear stones and carries them up Mount Shelem, asking the Lord to touch
them that they may shine in the barges. The Lord stretches forth his hand and touches the
stones one by one; the veil is taken away and the brother of Jared sees the finger of the
Lord. Because of his exceeding faith he cannot be kept from within the veil, and the Lord
shows himself, declaring he is Jesus Christ, the Father and the Son, and that man is
created after his own body.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15, vocative 12). `o le a` stays atomic and is never
fused with a following `se X` NP; cells go past 5 only for rule-2 (absorbed
subject) or rule-7 (`o le a` + verb + directional) clusters.

    python3 build_overrides_ether3.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "ether"
CHAPTER_NUM = 3

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 5, "went forth"),
        (6, 9, "the brother of Jared,"),
        (10, 11, "(now"),
        (12, 16, "the number of the barges"),
        (17, 21, "which were prepared"),
        (22, 23, "was eight)"),
        (24, 26, "unto the mount,"),
        (27, 30, "which they called"),
        (31, 35, "the mount Shelem,"),
        (36, 37, "because of"),
        (38, 40, "its great height,"),
        (41, 43, "and did make"),
        (44, 46, "out of a rock"),
        (47, 49, "small stones"),
        (50, 54, "sixteen;"),
        (55, 57, "and were white"),
        (58, 61, "and transparent the stones,"),
        (62, 64, "even like"),
        (65, 68, "clear glass;"),
        (69, 72, "and he did carry"),
        (73, 74, "the stones"),
        (75, 77, "in his hands"),
        (78, 79, "up"),
        (80, 82, "upon the top"),
        (83, 85, "of the mount,"),
        (86, 89, "and cried again"),
        (90, 92, "unto the Lord,"),
        (93, 95, "saying:"),
    ],
    2: [
        (0, 2, "O Lord,"),
        (3, 6, "thou hast said"),
        (7, 10, "shall be encompassed"),
        (11, 12, "us"),
        (13, 14, "by the floods."),
        (15, 17, "Now behold,"),
        (18, 20, "O Lord,"),
        (21, 22, "and"),
        (23, 26, "be not angry"),
        (27, 29, "with thy servant"),
        (30, 33, "because of his weakness"),
        (34, 36, "before thee;"),
        (37, 40, "for we know"),
        (41, 43, "that thou art holy"),
        (44, 47, "and dwellest"),
        (48, 50, "in the heavens,"),
        (51, 55, "and we are unworthy"),
        (56, 58, "before thee;"),
        (59, 62, "because of the fall"),
        (63, 65, "which hath come"),
        (66, 70, "evil without ceasing"),
        (71, 73, "our natures;"),
        (74, 77, "nevertheless,"),
        (78, 80, "O Lord,"),
        (81, 84, "thou hast given"),
        (85, 88, "unto us"),
        (89, 90, "a commandment"),
        (91, 96, "that we must call"),
        (97, 99, "upon thee,"),
        (100, 102, "that from thee"),
        (103, 107, "we may receive"),
        (108, 110, "according to"),
        (111, 113, "our desires."),
    ],
    3: [
        (0, 0, "Behold,"),
        (1, 3, "O Lord,"),
        (4, 8, "thou hast smitten us"),
        (9, 10, "because of"),
        (11, 13, "our iniquity,"),
        (14, 18, "and hast driven out"),
        (19, 20, "us,"),
        (21, 25, "and we have dwelt"),
        (26, 28, "in the wilderness"),
        (29, 33, "for these many years;"),
        (34, 37, "nevertheless,"),
        (38, 43, "thou hast still been merciful"),
        (44, 47, "unto us."),
        (48, 50, "O Lord,"),
        (51, 53, "look thou"),
        (54, 56, "upon me"),
        (57, 59, "in mercy,"),
        (60, 64, "and turn away thy anger"),
        (65, 69, "from this my people,"),
        (70, 74, "and suffer not"),
        (75, 76, "them"),
        (77, 79, "to sail forth"),
        (80, 82, "upon"),
        (83, 85, "this raging deep"),
        (86, 88, "in darkness;"),
        (89, 91, "but behold"),
        (92, 94, "these things"),
        (95, 97, "which I have made"),
        (98, 100, "out of the rock."),
    ],
    4: [
        (0, 3, "And I know,"),
        (4, 6, "O Lord,"),
        (7, 10, "that thou hast"),
        (11, 13, "all power,"),
        (14, 19, "and canst do"),
        (20, 23, "whatsoever thing"),
        (24, 28, "thou desirest"),
        (29, 33, "for the benefit of man;"),
        (34, 35, "therefore,"),
        (36, 37, "touch"),
        (38, 40, "these stones,"),
        (41, 43, "O Lord,"),
        (44, 46, "with thy finger,"),
        (47, 50, "and prepare them"),
        (51, 54, "that they may shine"),
        (55, 57, "in darkness;"),
        (58, 58, "and"),
        (59, 64, "they shall shine forth"),
        (65, 68, "unto us"),
        (69, 72, "within the barges"),
        (73, 75, "which we have prepared,"),
        (76, 79, "that we may have"),
        (80, 81, "light"),
        (82, 85, "as we sail forth"),
        (86, 88, "upon the sea."),
    ],
    5: [
        (0, 0, "Behold,"),
        (1, 3, "O Lord,"),
        (4, 8, "thou canst do"),
        (9, 10, "this thing."),
        (11, 13, "We know"),
        (14, 19, "that thou canst show"),
        (20, 22, "great power,"),
        (23, 26, "which appeareth small"),
        (27, 31, "unto the understanding of men."),
    ],
    6: [
        (0, 3, "And it came to pass that"),
        (4, 8, "when had spoken"),
        (9, 13, "the brother of Jared"),
        (14, 16, "these words,"),
        (17, 17, "behold,"),
        (18, 20, "stretched forth"),
        (21, 23, "the Lord"),
        (24, 25, "his hand"),
        (26, 28, "and touched"),
        (29, 31, "each of the stones"),
        (32, 34, "with his finger."),
        (35, 37, "And was taken away"),
        (38, 39, "the veil"),
        (40, 41, "from the eyes"),
        (42, 46, "of the brother of Jared,"),
        (47, 50, "and he saw"),
        (51, 53, "the finger"),
        (54, 56, "of the Lord;"),
        (57, 59, "and it was as"),
        (60, 62, "the finger"),
        (63, 65, "of a man,"),
        (66, 70, "as it were flesh"),
        (71, 73, "and blood;"),
        (74, 77, "and fell down"),
        (78, 81, "the brother of Jared"),
        (82, 86, "before the Lord,"),
        (87, 91, "for he was struck"),
        (92, 94, "with fear."),
    ],
    7: [
        (0, 3, "And beheld"),
        (4, 5, "the Lord"),
        (6, 10, "had fallen to the earth"),
        (11, 14, "the brother of Jared;"),
        (15, 18, "and said"),
        (19, 20, "the Lord"),
        (21, 23, "unto him:"),
        (24, 25, "Arise,"),
        (26, 30, "why art thou fallen?"),
    ],
    8: [
        (0, 4, "And he said"),
        (5, 7, "unto the Lord:"),
        (8, 10, "I saw"),
        (11, 13, "the finger"),
        (14, 16, "of the Lord,"),
        (17, 20, "and I feared"),
        (21, 22, "lest he smite"),
        (23, 25, "me;"),
        (26, 30, "for I knew not"),
        (31, 33, "that there was in"),
        (34, 36, "the Lord"),
        (37, 41, "flesh and blood."),
    ],
    9: [
        (0, 3, "And said"),
        (4, 5, "the Lord"),
        (6, 8, "unto him:"),
        (9, 12, "Because of thy faith"),
        (13, 16, "thou hast seen"),
        (17, 21, "that I shall take"),
        (22, 23, "upon"),
        (24, 26, "myself"),
        (27, 29, "a body of flesh"),
        (30, 32, "and blood;"),
        (33, 37, "and never came"),
        (38, 40, "before me"),
        (41, 42, "a man"),
        (43, 46, "with such great faith"),
        (47, 51, "even like unto thee;"),
        (52, 56, "for were it not so"),
        (57, 61, "thou couldst not"),
        (62, 63, "have seen"),
        (64, 66, "my finger."),
        (67, 71, "Sawest thou"),
        (72, 74, "aught"),
        (75, 77, "greater"),
        (78, 80, "than this?"),
    ],
    10: [
        (0, 0, "And"),
        (1, 5, "he answered:"),
        (6, 7, "Nay;"),
        (8, 10, "O Lord,"),
        (11, 15, "show thyself"),
        (16, 18, "unto me."),
    ],
    11: [
        (0, 3, "And said"),
        (4, 5, "the Lord"),
        (6, 8, "unto him:"),
        (9, 12, "Believest thou"),
        (13, 14, "the words"),
        (15, 21, "which I shall speak?"),
    ],
    12: [
        (0, 0, "And"),
        (1, 5, "he answered:"),
        (6, 6, "Yea,"),
        (7, 9, "O Lord,"),
        (10, 12, "I know"),
        (13, 15, "that thou speakest"),
        (16, 18, "the truth,"),
        (19, 21, "for thou art"),
        (22, 24, "a God"),
        (25, 27, "of truth,"),
        (28, 33, "and canst not lie."),
    ],
    13: [
        (0, 3, "And when"),
        (4, 6, "had spoken"),
        (7, 8, "he"),
        (9, 11, "these words,"),
        (12, 12, "behold,"),
        (13, 15, "showed"),
        (16, 18, "the Lord"),
        (19, 21, "himself"),
        (22, 24, "unto him,"),
        (25, 27, "and said:"),
        (28, 31, "Because thou knowest"),
        (32, 33, "these things,"),
        (34, 36, "art redeemed"),
        (37, 39, "from the fall;"),
        (40, 41, "therefore"),
        (42, 46, "thou art brought back"),
        (47, 49, "into my presence;"),
        (50, 51, "therefore"),
        (52, 56, "do I show"),
        (57, 58, "myself"),
        (59, 61, "unto thee."),
    ],
    14: [
        (0, 0, "Behold,"),
        (1, 2, "I am"),
        (3, 7, "he who was prepared"),
        (8, 12, "from the foundation of the world"),
        (13, 16, "to redeem my people."),
        (17, 17, "Behold,"),
        (18, 19, "I am"),
        (20, 22, "Jesus Christ."),
        (23, 24, "I am"),
        (25, 27, "the Father"),
        (28, 30, "and the Son."),
        (31, 35, "In me is found"),
        (36, 38, "by all men"),
        (39, 40, "the life,"),
        (41, 43, "and that forever,"),
        (44, 47, "even they themselves"),
        (48, 51, "who believe"),
        (52, 54, "on my name;"),
        (55, 55, "and"),
        (56, 59, "shall become"),
        (60, 61, "they"),
        (62, 64, "my sons"),
        (65, 67, "and my daughters."),
    ],
    15: [
        (0, 4, "And never have I shown"),
        (5, 6, "myself"),
        (7, 9, "unto man"),
        (10, 14, "whom I have created,"),
        (15, 17, "for never"),
        (18, 19, "hath man"),
        (20, 22, "believed"),
        (23, 25, "in me"),
        (26, 28, "even as"),
        (29, 31, "thou hast believed."),
        (32, 36, "Seest thou"),
        (37, 39, "that thou art created"),
        (40, 43, "in mine own image?"),
        (44, 44, "Yea,"),
        (45, 46, "even"),
        (47, 49, "all men"),
        (50, 51, "were created"),
        (52, 54, "in the beginning"),
        (55, 58, "after mine own image."),
    ],
    16: [
        (0, 0, "Behold,"),
        (1, 3, "this body,"),
        (4, 8, "which thou beholdest"),
        (9, 11, "at this time,"),
        (12, 15, "is the body"),
        (16, 18, "of my spirit;"),
        (19, 22, "and I have created"),
        (23, 24, "man"),
        (25, 29, "after the body"),
        (30, 32, "of my spirit;"),
        (33, 39, "and even as I appear"),
        (40, 42, "unto thee"),
        (43, 46, "in the spirit"),
        (47, 51, "even so shall"),
        (52, 55, "I appear"),
        (56, 58, "unto my people"),
        (59, 62, "in the flesh."),
    ],
    17: [
        (0, 2, "And now,"),
        (3, 4, "I,"),
        (5, 6, "Moroni,"),
        (7, 12, "as I said,"),
        (13, 18, "I cannot make"),
        (19, 21, "a full account"),
        (22, 24, "of these things"),
        (25, 26, "which are written,"),
        (27, 28, "therefore"),
        (29, 31, "it sufficeth"),
        (32, 34, "me"),
        (35, 38, "to say"),
        (39, 41, "showed"),
        (42, 43, "Jesus"),
        (44, 46, "himself"),
        (47, 49, "unto this man"),
        (50, 53, "in the spirit,"),
        (54, 56, "even after"),
        (57, 59, "the likeness"),
        (60, 61, "and form"),
        (62, 66, "of the very same body"),
        (67, 68, "the one,"),
        (69, 73, "wherein he showed"),
        (74, 76, "himself"),
        (77, 80, "unto the Nephites."),
    ],
    18: [
        (0, 4, "And he did minister"),
        (5, 7, "unto him"),
        (8, 14, "even as he ministered"),
        (15, 18, "unto the Nephites;"),
        (19, 20, "was done"),
        (21, 23, "all these things,"),
        (24, 26, "that might know"),
        (27, 29, "this man"),
        (30, 31, "that he"),
        (32, 34, "was God,"),
        (35, 38, "because of the many"),
        (39, 41, "great works"),
        (42, 43, "which had shown"),
        (44, 46, "the Lord"),
        (47, 49, "unto him."),
    ],
    19: [
        (0, 4, "And because of the knowledge"),
        (5, 7, "of this man"),
        (8, 11, "he could not"),
        (12, 13, "be restrained"),
        (14, 15, "him"),
        (16, 19, "from beholding"),
        (20, 24, "within the veil;"),
        (25, 29, "and he saw"),
        (30, 34, "the finger of Jesus,"),
        (35, 35, "which,"),
        (36, 41, "when he saw it,"),
        (42, 47, "he fell down"),
        (48, 50, "with fear;"),
        (51, 54, "for he knew"),
        (55, 58, "that it was the finger"),
        (59, 61, "of the Lord;"),
        (62, 65, "and no more"),
        (66, 68, "had he"),
        (69, 70, "faith,"),
        (71, 74, "for he had a perfect knowledge,"),
        (75, 77, "nothing doubting"),
        (78, 80, "in anything."),
    ],
    20: [
        (0, 3, "Wherefore,"),
        (4, 8, "because he had obtained"),
        (9, 11, "this perfect knowledge"),
        (12, 14, "of God,"),
        (15, 18, "he could not"),
        (19, 21, "be restrained"),
        (22, 26, "from within the veil;"),
        (27, 28, "therefore"),
        (29, 32, "he did see"),
        (33, 34, "Jesus;"),
        (35, 40, "and he did minister"),
        (41, 43, "unto him."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 5, "said"),
        (6, 7, "the Lord"),
        (8, 12, "unto the brother of Jared:"),
        (13, 13, "Behold,"),
        (14, 17, "suffer not"),
        (18, 19, "these things"),
        (20, 24, "which thou hast seen and heard"),
        (25, 27, "to go forth"),
        (28, 30, "unto the world,"),
        (31, 35, "until the time"),
        (36, 41, "that I shall glorify"),
        (42, 43, "my name"),
        (44, 47, "in the flesh;"),
        (48, 51, "wherefore,"),
        (52, 55, "thou shalt keep"),
        (56, 57, "the things"),
        (58, 62, "which thou hast seen and heard,"),
        (63, 68, "and show it not"),
        (69, 71, "to any man."),
    ],
    22: [
        (0, 1, "And behold,"),
        (2, 4, "when"),
        (5, 6, "thou comest"),
        (7, 9, "unto me,"),
        (10, 12, "thou shalt write"),
        (13, 14, "these things"),
        (15, 16, "and seal them up,"),
        (17, 21, "that no one"),
        (22, 25, "can interpret them;"),
        (26, 26, "for"),
        (27, 31, "thou shalt write"),
        (32, 33, "these things"),
        (34, 36, "in a language"),
        (37, 42, "which they cannot read."),
    ],
    23: [
        (0, 1, "And behold,"),
        (2, 5, "I give"),
        (6, 8, "unto thee"),
        (9, 12, "these two stones,"),
        (13, 17, "and thou shalt also seal up"),
        (18, 20, "with the things"),
        (21, 25, "which thou shalt write."),
    ],
    24: [
        (0, 1, "For behold,"),
        (2, 4, "the language"),
        (5, 10, "which thou shalt write"),
        (11, 13, "I have confounded;"),
        (14, 17, "wherefore"),
        (18, 23, "I will cause"),
        (24, 27, "in mine own time"),
        (28, 30, "appointed"),
        (31, 34, "shall magnify"),
        (35, 37, "these stones"),
        (38, 42, "to the eyes of men"),
        (43, 44, "these things"),
        (45, 49, "which thou shalt write."),
    ],
    25: [
        (0, 3, "And when"),
        (4, 6, "had said"),
        (7, 9, "the Lord"),
        (10, 12, "these words,"),
        (13, 16, "he showed"),
        (17, 21, "unto the brother of Jared"),
        (22, 26, "all the people of the earth"),
        (27, 31, "who had lived,"),
        (32, 36, "and also all of them"),
        (37, 41, "who should be;"),
        (42, 46, "and he kept not back"),
        (47, 48, "them"),
        (49, 51, "from his sight,"),
        (52, 55, "even unto"),
        (56, 59, "the ends of the earth."),
    ],
    26: [
        (0, 4, "For he had said"),
        (5, 7, "unto him"),
        (8, 10, "in former times,"),
        (11, 15, "if he would believe"),
        (16, 18, "in him"),
        (19, 23, "he could"),
        (24, 28, "show unto him"),
        (29, 30, "all things—"),
        (31, 35, "they should be shown"),
        (36, 38, "unto him;"),
        (39, 43, "therefore could not"),
        (44, 46, "the Lord"),
        (47, 51, "withhold anything"),
        (52, 55, "from him,"),
        (56, 59, "for he knew"),
        (60, 64, "that the Lord could"),
        (65, 67, "show forth"),
        (68, 70, "all things"),
        (71, 73, "unto him."),
    ],
    27: [
        (0, 3, "And said"),
        (4, 5, "the Lord"),
        (6, 8, "unto him:"),
        (9, 10, "Write"),
        (11, 12, "these things"),
        (13, 14, "and seal them up;"),
        (15, 15, "and"),
        (16, 21, "I will show forth"),
        (22, 23, "them"),
        (24, 27, "in mine own time"),
        (28, 30, "appointed,"),
        (31, 35, "unto the children of men."),
    ],
    28: [
        (0, 3, "And it came to pass that"),
        (4, 6, "commanded him"),
        (7, 9, "the Lord"),
        (10, 13, "that he should seal up"),
        (14, 16, "the two stones"),
        (17, 21, "which he had received,"),
        (22, 27, "and show them not,"),
        (28, 32, "until should show forth"),
        (33, 35, "the Lord"),
        (36, 40, "unto the children of men."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
