"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 24 — the
Amalekites stir up the Lamanites to anger against the Anti-Nephi-Lehies;
the converted king (Anti-Nephi-Lehi) exhorts his people to bury their
weapons of war; they covenant never to shed blood again, and are slain
without resistance; more Lamanites are converted than were slain.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15).

    python3 build_overrides_alma24.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 24

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 6, "the Amalekites"),
        (7, 9, "and the Amulonites"),
        (10, 12, "and the Lamanites"),
        (13, 16, "who were in"),
        (17, 20, "the land of Amulon,"),
        (21, 25, "and also who were in"),
        (26, 29, "the land of Helam,"),
        (30, 33, "and who were in"),
        (34, 37, "the land of Jerusalem,"),
        (38, 41, "and in fine,"),
        (42, 46, "in all the land"),
        (47, 49, "round about,"),
        (50, 54, "who had not been converted"),
        (55, 58, "and had not taken"),
        (59, 62, "upon them"),
        (63, 66, "the name of Anti-Nephi-Lehi,"),
        (67, 71, "were stirred up by the Amalekites"),
        (72, 74, "and the Amulonites"),
        (75, 76, "to anger"),
        (77, 81, "against their brethren."),
    ],
    2: [
        (0, 3, "And it came to pass that"),
        (4, 6, "became exceedingly sore"),
        (7, 9, "their hatred"),
        (10, 11, "against"),
        (12, 15, "them,"),
        (16, 19, "even insomuch that"),
        (20, 23, "they began to rebel"),
        (24, 28, "against their king,"),
        (29, 31, "insomuch that"),
        (32, 34, "they would not"),
        (35, 38, "that he should be"),
        (39, 42, "their king;"),
        (43, 44, "therefore,"),
        (45, 48, "they took up"),
        (49, 51, "weapons of war"),
        (52, 54, "against"),
        (55, 58, "the people of Anti-Nephi-Lehi."),
    ],
    3: [
        (0, 3, "Now conferred"),
        (4, 6, "the king"),
        (7, 8, "the kingdom"),
        (9, 13, "upon his son,"),
        (14, 17, "and he called"),
        (18, 20, "him"),
        (21, 22, "Anti-Nephi-Lehi."),
    ],
    4: [
        (0, 2, "And died"),
        (3, 4, "the king"),
        (5, 9, "in that selfsame year"),
        (10, 14, "that began to make"),
        (15, 17, "the Lamanites"),
        (18, 18, "preparations"),
        (19, 21, "for war"),
        (22, 24, "against"),
        (25, 28, "the people of God."),
    ],
    5: [
        (0, 1, "Now"),
        (2, 5, "when Ammon saw"),
        (6, 8, "and his brethren"),
        (9, 12, "and all those"),
        (13, 14, "who"),
        (15, 17, "had come up"),
        (18, 20, "with him"),
        (21, 23, "the preparations of"),
        (24, 25, "the Lamanites"),
        (26, 27, "to destroy"),
        (28, 30, "their brethren,"),
        (31, 35, "they came forth to"),
        (36, 39, "the land of Midian,"),
        (40, 42, "and there"),
        (43, 46, "Ammon met"),
        (47, 50, "all his brethren;"),
        (51, 53, "and from thence"),
        (54, 59, "they came to"),
        (60, 63, "the land of Ishmael"),
        (64, 69, "that they might hold"),
        (70, 72, "a council"),
        (73, 75, "with Lamoni"),
        (76, 79, "and also his brother"),
        (80, 81, "Anti-Nephi-Lehi,"),
        (82, 85, "what"),
        (86, 87, "thing"),
        (88, 92, "they should do"),
        (93, 95, "to defend"),
        (96, 98, "themselves"),
        (99, 103, "against the Lamanites."),
    ],
    6: [
        (0, 1, "Now"),
        (2, 5, "there was not a soul"),
        (6, 7, "one"),
        (8, 12, "among all the people"),
        (13, 16, "who had been converted"),
        (17, 19, "unto the Lord,"),
        (20, 23, "that would take up"),
        (24, 26, "weapons of war"),
        (27, 29, "against"),
        (30, 32, "their brethren;"),
        (33, 34, "nay,"),
        (35, 40, "they would not even make"),
        (41, 42, "any preparations"),
        (43, 45, "for war;"),
        (46, 46, "yea,"),
        (47, 52, "and also they were commanded"),
        (53, 56, "by their king"),
        (57, 61, "that they should not do it."),
    ],
    7: [
        (0, 1, "Now,"),
        (2, 4, "these are the words"),
        (5, 8, "which he said"),
        (9, 11, "unto the people"),
        (12, 16, "concerning the matter:"),
        (17, 19, "I thank"),
        (20, 22, "my God,"),
        (23, 26, "my beloved people,"),
        (27, 29, "has sent"),
        (30, 33, "unto us"),
        (34, 38, "our great God"),
        (39, 41, "in his goodness"),
        (42, 45, "these our brethren,"),
        (46, 48, "the Nephites,"),
        (49, 51, "to preach"),
        (52, 55, "unto us,"),
        (56, 59, "and to convince us"),
        (60, 64, "concerning the traditions of"),
        (65, 68, "our wicked fathers."),
    ],
    8: [
        (0, 1, "And behold,"),
        (2, 4, "I thank"),
        (5, 8, "my great God"),
        (9, 9, "that"),
        (10, 13, "he has given"),
        (14, 17, "unto us"),
        (18, 22, "a portion of his Spirit,"),
        (23, 24, "to soften"),
        (25, 27, "our hearts,"),
        (28, 31, "that we have opened"),
        (32, 33, "a correspondence"),
        (34, 36, "with these brethren,"),
        (37, 39, "the Nephites."),
    ],
    9: [
        (0, 1, "And behold,"),
        (2, 5, "I also thank"),
        (6, 8, "my God,"),
        (9, 13, "because of the opening of"),
        (14, 15, "this correspondence"),
        (16, 19, "we have been convinced"),
        (20, 21, "concerning"),
        (22, 24, "our sins,"),
        (25, 28, "and concerning"),
        (29, 31, "the many"),
        (32, 34, "murders"),
        (35, 37, "which we have committed."),
    ],
    10: [
        (0, 4, "And I also thank"),
        (5, 7, "my God,"),
        (8, 8, "yea,"),
        (9, 11, "my great God,"),
        (12, 12, "that"),
        (13, 16, "he hath granted"),
        (17, 20, "unto us"),
        (21, 26, "that we might repent"),
        (27, 29, "of these things,"),
        (30, 34, "and also he hath forgiven"),
        (35, 36, "us"),
        (37, 40, "of our sins"),
        (41, 44, "and the murders"),
        (45, 46, "many"),
        (47, 49, "which we have committed,"),
        (50, 51, "and taken away"),
        (52, 54, "the guilt"),
        (55, 59, "from our hearts,"),
        (60, 64, "through the merits of"),
        (65, 66, "his Son."),
    ],
    11: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 6, "my brethren,"),
        (7, 9, "since"),
        (10, 14, "it is all that"),
        (15, 19, "we could do"),
        (20, 24, "(for we were"),
        (25, 26, "people"),
        (27, 31, "most far gone astray"),
        (32, 34, "of all men)"),
        (35, 38, "to repent"),
        (39, 42, "of our"),
        (43, 44, "all sins"),
        (45, 48, "and the murders"),
        (49, 50, "many"),
        (51, 53, "which we have committed,"),
        (54, 58, "and to cause God"),
        (59, 63, "that he take them away"),
        (64, 67, "from our hearts,"),
        (68, 68, "for"),
        (69, 72, "it was all"),
        (73, 74, "that"),
        (75, 79, "we could do"),
        (80, 85, "that our repentance might suffice"),
        (86, 90, "before God"),
        (91, 95, "that he take away"),
        (96, 98, "our stain—"),
    ],
    12: [
        (0, 1, "Now,"),
        (2, 4, "my brethren"),
        (5, 8, "most beloved,"),
        (9, 11, "since"),
        (12, 16, "God hath taken away"),
        (17, 19, "our stains,"),
        (20, 22, "and have become bright"),
        (23, 25, "our swords,"),
        (26, 27, "then"),
        (28, 33, "let us no more stain"),
        (34, 36, "our swords"),
        (37, 40, "with the blood of"),
        (41, 43, "our brethren."),
    ],
    13: [
        (0, 0, "Behold,"),
        (1, 4, "I say"),
        (5, 7, "unto you,"),
        (8, 9, "Nay,"),
        (10, 13, "but let us retain"),
        (14, 16, "our swords"),
        (17, 20, "that they be not stained"),
        (21, 24, "with the blood of"),
        (25, 27, "our brethren;"),
        (28, 29, "for perhaps,"),
        (30, 34, "if we should stain again"),
        (35, 37, "our swords"),
        (38, 43, "they can no more"),
        (44, 46, "be washed bright"),
        (47, 48, "them"),
        (49, 53, "through the blood"),
        (54, 54, "of"),
        (55, 57, "the Son of"),
        (58, 61, "our great God,"),
        (62, 66, "which shall be shed"),
        (67, 70, "for the atonement of"),
        (71, 73, "our sins."),
    ],
    14: [
        (0, 4, "And has had mercy"),
        (5, 7, "the great God"),
        (8, 11, "on us,"),
        (12, 14, "and made known"),
        (15, 16, "these things"),
        (17, 19, "unto us"),
        (20, 24, "that we might not perish;"),
        (25, 25, "yea,"),
        (26, 29, "and he hath beforehand"),
        (30, 31, "made known"),
        (32, 33, "these things"),
        (34, 36, "unto us,"),
        (37, 37, "because"),
        (38, 41, "he loveth"),
        (42, 45, "our souls"),
        (46, 51, "even as he loveth"),
        (52, 55, "our children;"),
        (56, 57, "therefore,"),
        (58, 61, "in his mercy"),
        (62, 66, "he doth visit"),
        (67, 69, "us"),
        (70, 74, "by his angels,"),
        (75, 80, "that might be made known"),
        (81, 84, "unto us"),
        (85, 89, "the plan of salvation"),
        (90, 92, "as well as"),
        (93, 97, "unto future generations."),
    ],
    15: [
        (0, 0, "Oh,"),
        (1, 4, "how merciful is"),
        (5, 7, "our God!"),
        (8, 10, "And now"),
        (11, 11, "behold,"),
        (12, 14, "since"),
        (15, 18, "it is all"),
        (19, 20, "that"),
        (21, 25, "we could do"),
        (26, 28, "to take away"),
        (29, 31, "our stains"),
        (32, 35, "from us,"),
        (36, 38, "and are made bright"),
        (39, 41, "our swords,"),
        (42, 44, "let us hide away"),
        (45, 46, "them"),
        (47, 52, "that may be kept"),
        (53, 55, "their brightness,"),
        (56, 58, "as a testimony"),
        (59, 62, "to our God,"),
        (63, 66, "at the last day,"),
        (67, 70, "or at the day"),
        (71, 75, "that shall be brought"),
        (76, 77, "we"),
        (78, 82, "to stand before him"),
        (83, 84, "to be judged,"),
        (85, 88, "that we have not stained"),
        (89, 91, "our swords"),
        (92, 95, "in the blood of"),
        (96, 98, "our brethren"),
        (99, 100, "since"),
        (101, 105, "he imparted his word"),
        (106, 109, "unto us"),
        (110, 113, "and hath made clean thereby"),
        (114, 115, "us."),
    ],
    16: [
        (0, 2, "And now,"),
        (3, 5, "my brethren,"),
        (6, 8, "if seek"),
        (9, 11, "our brethren"),
        (12, 15, "to destroy us,"),
        (16, 16, "behold,"),
        (17, 20, "we will"),
        (21, 22, "hide away"),
        (23, 25, "our swords,"),
        (26, 26, "yea,"),
        (27, 30, "we will"),
        (31, 32, "bury deep"),
        (33, 34, "them"),
        (35, 37, "in the earth,"),
        (38, 41, "that may be kept"),
        (42, 44, "their brightness,"),
        (45, 47, "as a testimony,"),
        (48, 51, "at the last day,"),
        (52, 56, "that we have never used"),
        (57, 58, "them;"),
        (59, 62, "and if they destroy"),
        (63, 64, "us"),
        (65, 68, "by our brethren,"),
        (69, 69, "behold,"),
        (70, 73, "we shall"),
        (74, 75, "go"),
        (76, 79, "to our God"),
        (80, 84, "and shall be saved"),
        (85, 86, "we."),
    ],
    17: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 10, "when had made an end"),
        (11, 13, "the king"),
        (14, 15, "these sayings,"),
        (16, 19, "and were assembled together"),
        (20, 22, "all the people,"),
        (23, 25, "they took"),
        (26, 28, "their swords,"),
        (29, 31, "and all the weapons"),
        (32, 35, "which were used for"),
        (36, 38, "the shedding of"),
        (39, 41, "man's blood,"),
        (42, 46, "and they did bury deep"),
        (47, 48, "them"),
        (49, 51, "in the earth."),
    ],
    18: [
        (0, 4, "And this they did,"),
        (5, 9, "it being"),
        (10, 13, "in their view"),
        (14, 16, "a testimony"),
        (17, 19, "to God,"),
        (20, 23, "and also to men,"),
        (24, 29, "that they never again"),
        (30, 30, "would use"),
        (31, 31, "weapons"),
        (32, 35, "for the shedding of"),
        (36, 39, "man's blood;"),
        (40, 43, "and they did"),
        (44, 45, "this thing,"),
        (46, 50, "vouching and covenanting"),
        (51, 53, "with God,"),
        (54, 58, "rather than the shedding of"),
        (59, 61, "the blood of"),
        (62, 64, "their brethren,"),
        (65, 68, "they would"),
        (69, 70, "give up"),
        (71, 74, "their own lives;"),
        (75, 79, "and rather than taking"),
        (80, 80, "away"),
        (81, 83, "from a brother"),
        (84, 87, "they would"),
        (88, 89, "give"),
        (90, 92, "unto him;"),
        (93, 97, "and rather than wasting"),
        (98, 98, "of"),
        (99, 101, "their days"),
        (102, 104, "in idleness,"),
        (105, 108, "they would"),
        (109, 110, "labor abundantly"),
        (111, 115, "with their own hands."),
    ],
    19: [
        (0, 3, "and thus"),
        (4, 6, "we see,"),
        (7, 9, "when were brought"),
        (10, 12, "these Lamanites"),
        (13, 14, "to believe"),
        (15, 18, "and to know"),
        (19, 20, "the truth,"),
        (21, 24, "they were firm,"),
        (25, 27, "and would suffer"),
        (28, 31, "even to come"),
        (32, 33, "death"),
        (34, 37, "unto them,"),
        (38, 42, "rather than the committing of"),
        (43, 44, "sin;"),
        (45, 48, "and thus"),
        (49, 51, "we see"),
        (52, 54, "they buried"),
        (55, 58, "their weapons of"),
        (59, 60, "peace,"),
        (61, 64, "or they buried"),
        (65, 67, "the weapons of war,"),
        (68, 70, "for peace."),
    ],
    20: [
        (0, 3, "And it came to pass that"),
        (4, 8, "their brethren made"),
        (9, 11, "the Lamanites,"),
        (12, 12, "preparations"),
        (13, 15, "for war,"),
        (16, 20, "and came up to"),
        (21, 24, "the land of Nephi"),
        (25, 27, "for the purpose"),
        (28, 31, "to destroy the king,"),
        (32, 35, "and to place another"),
        (36, 40, "in his stead,"),
        (41, 44, "and also of the purpose"),
        (45, 47, "to destroy"),
        (48, 50, "the people of Anti-Nephi-Lehi"),
        (51, 53, "out of the land."),
    ],
    21: [
        (0, 1, "Now"),
        (2, 5, "when saw"),
        (6, 7, "the people"),
        (8, 12, "that they were coming"),
        (13, 14, "against"),
        (15, 18, "them,"),
        (19, 22, "they went out"),
        (23, 24, "to meet"),
        (25, 26, "them,"),
        (27, 31, "and they prostrated"),
        (32, 34, "themselves"),
        (35, 37, "to the earth"),
        (38, 41, "before them,"),
        (42, 46, "and they began to"),
        (47, 48, "call"),
        (49, 52, "on the name of"),
        (53, 54, "the Lord;"),
        (55, 59, "and this was the posture"),
        (60, 63, "in which they"),
        (64, 65, "were"),
        (66, 69, "when began to"),
        (70, 71, "fall"),
        (72, 74, "the Lamanites"),
        (75, 78, "upon them,"),
        (79, 82, "and began to slay"),
        (83, 85, "them"),
        (86, 88, "with the sword."),
    ],
    22: [
        (0, 2, "And thus,"),
        (3, 5, "without"),
        (6, 9, "their meeting"),
        (10, 11, "any resistance,"),
        (12, 14, "they did slay"),
        (15, 19, "a thousand"),
        (20, 22, "and five"),
        (23, 25, "of them;"),
        (26, 29, "and we know"),
        (30, 33, "that they are blessed,"),
        (34, 34, "for"),
        (35, 38, "they have gone"),
        (39, 42, "to dwell with"),
        (43, 45, "their God."),
    ],
    23: [
        (0, 1, "Now"),
        (2, 5, "when saw"),
        (6, 7, "the Lamanites"),
        (8, 11, "that would not flee"),
        (12, 14, "their brethren"),
        (15, 17, "from the sword,"),
        (18, 21, "neither would turn aside"),
        (22, 23, "they"),
        (24, 27, "to the right hand"),
        (28, 32, "or to the left,"),
        (33, 36, "but they would lie"),
        (37, 38, "down"),
        (39, 40, "and perish,"),
        (41, 43, "and praised"),
        (44, 46, "God"),
        (47, 50, "in the very moment"),
        (51, 53, "of perishing"),
        (54, 56, "by the sword—"),
    ],
    24: [
        (0, 1, "Now"),
        (2, 5, "when saw"),
        (6, 7, "the Lamanites"),
        (8, 10, "this,"),
        (11, 14, "they did forbear"),
        (15, 19, "from slaying them;"),
        (20, 24, "and many of them"),
        (25, 26, "who"),
        (27, 31, "whose hearts were swollen"),
        (32, 36, "within them,"),
        (37, 39, "for those"),
        (40, 43, "of their brethren"),
        (44, 48, "who had fallen"),
        (49, 51, "under the sword,"),
        (52, 52, "for"),
        (53, 55, "they repented"),
        (56, 57, "of the things"),
        (58, 60, "which they had done."),
    ],
    25: [
        (0, 3, "And it came to pass that"),
        (4, 7, "they threw down"),
        (8, 12, "their weapons of war,"),
        (13, 17, "and they no more"),
        (18, 20, "would take them,"),
        (21, 21, "for"),
        (22, 25, "they were stung"),
        (26, 30, "because of the murders"),
        (31, 33, "which they had committed;"),
        (34, 38, "and they came down"),
        (39, 40, "below"),
        (41, 44, "even as"),
        (45, 47, "their brethren,"),
        (48, 50, "relying upon"),
        (51, 54, "the mercies of"),
        (55, 56, "those"),
        (57, 61, "who had lifted up"),
        (62, 64, "their arms"),
        (65, 68, "to slay them."),
    ],
    26: [
        (0, 3, "And it came to pass that"),
        (4, 6, "there joined unto"),
        (7, 10, "the people of God"),
        (11, 13, "that day"),
        (14, 18, "more people"),
        (19, 22, "than the number"),
        (23, 24, "of those who"),
        (25, 26, "had been slain;"),
        (27, 30, "and they"),
        (31, 32, "who"),
        (33, 34, "had been slain"),
        (35, 39, "were righteous people,"),
        (40, 41, "therefore"),
        (42, 46, "there is no reason"),
        (47, 50, "for us to doubt"),
        (51, 55, "but that they were saved."),
    ],
    27: [
        (0, 4, "and there was not a man"),
        (5, 5, "wicked"),
        (6, 9, "among"),
        (10, 11, "them"),
        (12, 15, "who was slain;"),
        (16, 20, "but there were more than"),
        (21, 22, "a thousand"),
        (23, 26, "of them who"),
        (27, 28, "were brought"),
        (29, 32, "to the knowledge of"),
        (33, 34, "the truth;"),
        (35, 38, "thus we"),
        (39, 40, "see"),
        (41, 43, "many are the ways"),
        (44, 48, "in which the Lord worketh"),
        (49, 53, "to bring salvation"),
        (54, 56, "to his people."),
    ],
    28: [
        (0, 1, "Now"),
        (2, 6, "the greatest"),
        (7, 7, "number"),
        (8, 10, "of them"),
        (11, 13, "of the Lamanites"),
        (14, 18, "who slew"),
        (19, 22, "so many of"),
        (23, 25, "their brethren,"),
        (26, 28, "were Amalekites"),
        (29, 31, "and Amulonites,"),
        (32, 35, "the greater part of"),
        (36, 37, "them"),
        (38, 40, "were after"),
        (41, 45, "the order of the Nehors."),
    ],
    29: [
        (0, 1, "Now,"),
        (2, 6, "among them"),
        (7, 11, "who joined"),
        (12, 16, "the people of the Lord,"),
        (17, 21, "there was no Amalekite"),
        (22, 26, "or Amulonite"),
        (27, 29, "among them,"),
        (30, 33, "or any who"),
        (34, 36, "were"),
        (37, 41, "of the order of Nehor,"),
        (42, 46, "but only they"),
        (47, 51, "who were true descendants"),
        (52, 52, "from"),
        (53, 56, "Laman and Lemuel."),
    ],
    30: [
        (0, 3, "And thus"),
        (4, 7, "we can plainly discern,"),
        (8, 12, "that after have been enlightened"),
        (13, 15, "a people"),
        (16, 21, "by the Spirit of"),
        (22, 23, "God,"),
        (24, 26, "and have had"),
        (27, 29, "great knowledge"),
        (30, 33, "concerning things"),
        (34, 37, "pertaining to righteousness,"),
        (38, 39, "and then"),
        (40, 44, "have fallen away"),
        (45, 47, "into sin"),
        (48, 50, "and transgression,"),
        (51, 55, "becometh greater"),
        (56, 58, "their hardness,"),
        (59, 60, "and thus"),
        (61, 64, "becometh worse"),
        (65, 66, "the evil"),
        (67, 69, "of their state"),
        (70, 74, "than as if"),
        (75, 79, "they had never known"),
        (80, 81, "these things."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
