"""
Hand-curated TAM-phrase gloss overrides for Eteru (Ether) 9 — the secret combination
murders Omer and enthrones Jared, but Akish then murders Jared and usurps the throne,
leading to a long civil war that nearly destroys the whole kingdom. Omer is restored and
succeeded by Emer, who reigns in righteousness and sees the Son of Righteousness. The
generations pass through Coriantum, Com, Heth; Heth embraces secret plans, and in his day
a great dearth and poisonous serpents come upon the land until the people repent.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15, vocative 12). `o le a` stays atomic and is never
fused with a following `se X` NP; cells go past 5 only for rule-2 (absorbed
subject) or rule-7 (`o le a` + verb + directional) clusters.

    python3 build_overrides_ether9.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "ether"
CHAPTER_NUM = 9

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 4, "I,"),
        (5, 6, "Moroni,"),
        (7, 10, "do continue"),
        (11, 13, "with my record."),
        (14, 15, "Therefore,"),
        (16, 16, "behold,"),
        (17, 20, "because of the secret combinations"),
        (21, 22, "of Akish"),
        (23, 25, "and his friends,"),
        (26, 26, "behold,"),
        (27, 30, "it came to pass that"),
        (31, 32, "they overthrew"),
        (33, 36, "the kingdom of Omer."),
    ],
    2: [
        (0, 3, "Nevertheless,"),
        (4, 6, "showed tender mercy"),
        (7, 8, "the Lord"),
        (9, 10, "unto Omer,"),
        (11, 14, "and also his sons"),
        (15, 17, "and his daughters"),
        (18, 19, "who"),
        (20, 23, "sought not"),
        (24, 25, "his destruction."),
    ],
    3: [
        (0, 2, "And was warned"),
        (3, 3, "Omer"),
        (4, 6, "by the Lord"),
        (7, 9, "in a dream"),
        (10, 13, "that he should"),
        (14, 16, "depart away"),
        (17, 19, "out of the land;"),
        (20, 23, "wherefore"),
        (24, 28, "did depart"),
        (29, 29, "Omer"),
        (30, 33, "with his household"),
        (34, 36, "from the land,"),
        (37, 38, "and journeyed"),
        (39, 42, "many days,"),
        (43, 45, "and went up"),
        (46, 48, "and came by"),
        (49, 53, "by the hill"),
        (54, 55, "of Shim,"),
        (56, 58, "and came"),
        (59, 61, "hard by"),
        (62, 64, "the place"),
        (65, 68, "where were destroyed"),
        (69, 70, "the Nephites,"),
        (71, 73, "and thence"),
        (74, 75, "toward the east,"),
        (76, 78, "and came"),
        (79, 81, "unto a place"),
        (82, 85, "called Ablom,"),
        (86, 88, "beside"),
        (89, 91, "the seashore,"),
        (92, 94, "and there"),
        (95, 98, "he pitched"),
        (99, 100, "his tent,"),
        (101, 104, "and also his sons"),
        (105, 107, "and his daughters,"),
        (108, 111, "and all his household,"),
        (112, 114, "save Jared"),
        (115, 117, "and his family."),
    ],
    4: [
        (0, 3, "And it came to pass that"),
        (4, 5, "Jared was anointed"),
        (6, 8, "a king"),
        (9, 13, "over the people,"),
        (14, 16, "by the hand"),
        (17, 19, "of wickedness;"),
        (20, 22, "and did give"),
        (23, 24, "unto Akish"),
        (25, 26, "his daughter"),
        (27, 29, "to be"),
        (30, 31, "his wife."),
    ],
    5: [
        (0, 3, "And it came to pass that"),
        (4, 4, "sought"),
        (5, 6, "Akish"),
        (7, 8, "the life"),
        (9, 11, "of the father"),
        (12, 14, "of his wife;"),
        (15, 19, "and he did speak"),
        (20, 22, "unto them"),
        (23, 27, "whom he had bound"),
        (28, 30, "by the oath"),
        (31, 33, "of the ancients,"),
        (34, 38, "and they severed"),
        (39, 41, "off the head"),
        (42, 44, "of the father"),
        (45, 47, "of his wife,"),
        (48, 51, "while he sat"),
        (52, 56, "upon his throne,"),
        (57, 60, "as he gave audience"),
        (61, 63, "to his people."),
    ],
    6: [
        (0, 4, "For exceeding great was"),
        (5, 6, "the spread"),
        (7, 10, "of this evil society"),
        (11, 12, "and secret,"),
        (13, 15, "which corrupted"),
        (16, 19, "the hearts of all men;"),
        (20, 21, "therefore"),
        (22, 24, "was murdered"),
        (25, 25, "Jared"),
        (26, 30, "upon his throne,"),
        (31, 33, "and did reign"),
        (34, 34, "Akish"),
        (35, 37, "in his place."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 6, "began to envy"),
        (7, 7, "Akish"),
        (8, 10, "his son,"),
        (11, 12, "wherefore"),
        (13, 16, "he did imprison"),
        (17, 18, "him"),
        (19, 21, "in prison,"),
        (22, 25, "and kept him"),
        (26, 29, "with a little food"),
        (30, 34, "or with none,"),
        (35, 37, "until"),
        (38, 40, "he suffered"),
        (41, 43, "unto death."),
    ],
    8: [
        (0, 2, "And now"),
        (3, 7, "the brother of him"),
        (8, 10, "who suffered"),
        (11, 13, "in death,"),
        (14, 17, "(and his name"),
        (18, 19, "was Nimrah)"),
        (20, 21, "was angry"),
        (22, 24, "with his father"),
        (25, 28, "because of that"),
        (29, 30, "which did"),
        (31, 33, "his father"),
        (34, 36, "unto his brother."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 4, "gathered"),
        (5, 6, "Nimrah"),
        (7, 11, "a small number of men,"),
        (12, 14, "and fled away"),
        (15, 17, "out of the land,"),
        (18, 21, "and went over"),
        (22, 25, "and dwelt with"),
        (26, 27, "Omer."),
    ],
    10: [
        (0, 3, "And it came to pass that"),
        (4, 6, "Akish begat"),
        (7, 8, "other sons,"),
        (9, 11, "and were pleased"),
        (12, 13, "the people"),
        (14, 17, "with them,"),
        (18, 20, "notwithstanding"),
        (21, 23, "they had sworn"),
        (24, 26, "unto him"),
        (27, 31, "that they would do"),
        (32, 35, "all manner of iniquity"),
        (36, 38, "according to"),
        (39, 39, "that which"),
        (40, 45, "he desired."),
    ],
    11: [
        (0, 1, "Now"),
        (2, 3, "did desire"),
        (4, 6, "the people of Akish"),
        (7, 8, "after riches,"),
        (9, 11, "even as"),
        (12, 13, "Akish craved"),
        (14, 16, "power;"),
        (17, 20, "wherefore,"),
        (21, 24, "did give"),
        (25, 28, "unto them"),
        (29, 32, "the sons of Akish"),
        (33, 34, "money,"),
        (35, 38, "by which way"),
        (39, 41, "they enticed"),
        (42, 44, "away"),
        (45, 49, "the greater part of the people"),
        (50, 52, "to follow after"),
        (53, 56, "them."),
    ],
    12: [
        (0, 3, "And there began"),
        (4, 5, "to be"),
        (6, 8, "a war"),
        (9, 11, "between"),
        (12, 15, "the sons of Akish"),
        (16, 17, "and Akish,"),
        (18, 20, "which was waged"),
        (21, 24, "for the space"),
        (25, 27, "of many years,"),
        (28, 28, "yea,"),
        (29, 31, "until"),
        (32, 35, "almost were destroyed"),
        (36, 40, "all the people of the kingdom,"),
        (41, 41, "yea,"),
        (42, 44, "even all,"),
        (45, 46, "except"),
        (47, 50, "thirty souls,"),
        (51, 53, "and they"),
        (54, 58, "who escaped with"),
        (59, 63, "the family of Omer."),
    ],
    13: [
        (0, 3, "Wherefore"),
        (4, 6, "was restored"),
        (7, 7, "Omer"),
        (8, 10, "to the land"),
        (11, 13, "of his inheritance."),
    ],
    14: [
        (0, 3, "And it came to pass that"),
        (4, 6, "began to grow old"),
        (7, 8, "Omer;"),
        (9, 12, "nevertheless,"),
        (13, 16, "he begat"),
        (17, 17, "Emer"),
        (18, 22, "in his old age;"),
        (23, 26, "and he anointed"),
        (27, 27, "Emer"),
        (28, 31, "to be a king"),
        (32, 33, "to reign"),
        (34, 38, "in his place."),
    ],
    15: [
        (0, 3, "And after that"),
        (4, 6, "he had anointed"),
        (7, 8, "Emer"),
        (9, 12, "to become king"),
        (13, 16, "he beheld"),
        (17, 19, "peace"),
        (20, 22, "in the land"),
        (23, 26, "for the space"),
        (27, 29, "of two years,"),
        (30, 34, "and he died,"),
        (35, 38, "after that"),
        (39, 39, "seeing"),
        (40, 44, "many days,"),
        (45, 47, "which were full"),
        (48, 50, "of sorrow."),
        (51, 54, "And it came to pass that"),
        (55, 56, "Emer reigned"),
        (57, 61, "in his stead,"),
        (62, 66, "and he did follow"),
        (67, 71, "in the ways of his father."),
    ],
    16: [
        (0, 4, "And once more began"),
        (5, 5, "to take away"),
        (6, 8, "by the Lord"),
        (9, 10, "the curse"),
        (11, 13, "from the land,"),
        (14, 18, "and did greatly prosper"),
        (19, 22, "the house of Emer"),
        (23, 25, "under"),
        (26, 29, "the reign of Emer;"),
        (30, 34, "and in the space"),
        (35, 37, "of sixty"),
        (38, 42, "and two years"),
        (43, 46, "became they"),
        (47, 51, "exceedingly mighty people,"),
        (52, 54, "insomuch that"),
        (55, 58, "they grew very rich—"),
    ],
    17: [
        (0, 2, "They obtained"),
        (3, 5, "all manner of fruit,"),
        (6, 7, "and grain,"),
        (8, 9, "and silks,"),
        (10, 12, "and fine linen,"),
        (13, 15, "and gold,"),
        (16, 18, "and silver,"),
        (19, 21, "and precious things."),
    ],
    18: [
        (0, 3, "And all manner"),
        (4, 5, "of cattle,"),
        (6, 8, "of oxen,"),
        (9, 11, "and cows,"),
        (12, 13, "and sheep,"),
        (14, 15, "and swine,"),
        (16, 17, "and goats,"),
        (18, 20, "and other kinds"),
        (21, 24, "of many beasts"),
        (25, 27, "which were useful"),
        (28, 30, "for man's food."),
    ],
    19: [
        (0, 4, "And there were also"),
        (5, 8, "unto them"),
        (9, 10, "horses,"),
        (11, 12, "and asses,"),
        (13, 16, "and there were"),
        (17, 17, "elephants"),
        (18, 21, "and cureloms and cumoms;"),
        (22, 25, "all of which"),
        (26, 28, "were useful"),
        (29, 31, "unto man,"),
        (32, 34, "and more especially"),
        (35, 35, "elephants"),
        (36, 39, "and cureloms and cumoms."),
    ],
    20: [
        (0, 2, "And thus"),
        (3, 5, "did pour out"),
        (6, 8, "the Lord"),
        (9, 10, "his blessings"),
        (11, 15, "upon this land,"),
        (16, 20, "which was choice"),
        (21, 23, "above all other"),
        (24, 26, "lands;"),
        (27, 30, "and he commanded"),
        (31, 33, "that whosoever"),
        (34, 36, "should possess"),
        (37, 38, "the land"),
        (39, 43, "should possess it"),
        (44, 46, "unto the Lord,"),
        (47, 48, "or else"),
        (49, 52, "shall be destroyed"),
        (53, 54, "them"),
        (55, 58, "when they are ripe"),
        (59, 61, "in iniquity;"),
        (62, 64, "for upon"),
        (65, 68, "such as these,"),
        (69, 72, "saith"),
        (73, 74, "the Lord:"),
        (75, 80, "I will pour out"),
        (81, 82, "upon them"),
        (83, 84, "the fulness"),
        (85, 87, "of my wrath."),
    ],
    21: [
        (0, 2, "And did execute"),
        (3, 4, "Emer"),
        (5, 5, "judgment"),
        (6, 8, "in righteousness"),
        (9, 12, "all his days,"),
        (13, 17, "and he begat"),
        (18, 22, "many sons and daughters;"),
        (23, 27, "and he begat"),
        (28, 28, "Coriantum,"),
        (29, 32, "and he anointed"),
        (33, 33, "Coriantum"),
        (34, 38, "to reign in his place."),
    ],
    22: [
        (0, 3, "And after that"),
        (4, 7, "he had anointed"),
        (8, 8, "Coriantum"),
        (9, 13, "in his stead,"),
        (14, 17, "he lived"),
        (18, 21, "four years,"),
        (22, 25, "and he beheld"),
        (26, 29, "peace"),
        (30, 32, "in the land;"),
        (33, 33, "yea,"),
        (34, 39, "and he even saw"),
        (40, 42, "the Son"),
        (43, 45, "of Righteousness,"),
        (46, 48, "and did rejoice"),
        (49, 50, "and glory"),
        (51, 55, "in his days;"),
        (56, 61, "and he died in peace."),
    ],
    23: [
        (0, 3, "And it came to pass that"),
        (4, 5, "walked Coriantum"),
        (6, 10, "in the ways of his father,"),
        (11, 13, "and did build"),
        (14, 17, "many great cities,"),
        (18, 19, "and did do"),
        (20, 22, "unto his people"),
        (23, 24, "good"),
        (25, 28, "in all his days."),
        (29, 32, "And it came to pass that"),
        (33, 34, "he had no"),
        (35, 36, "children"),
        (37, 39, "until"),
        (40, 43, "he grew exceeding old."),
    ],
    24: [
        (0, 3, "And it came to pass that"),
        (4, 6, "died his wife,"),
        (7, 9, "being a hundred"),
        (10, 12, "and two"),
        (13, 14, "years old."),
        (15, 18, "And it came to pass that"),
        (19, 21, "took Coriantum"),
        (22, 26, "to be his wife,"),
        (27, 31, "when he had grown old,"),
        (32, 34, "a young damsel,"),
        (35, 37, "and did beget"),
        (38, 41, "sons and daughters;"),
        (42, 45, "wherefore"),
        (46, 50, "he did live"),
        (51, 54, "until he was"),
        (55, 57, "an hundred and forty"),
        (58, 61, "and two years"),
        (62, 64, "of his age."),
    ],
    25: [
        (0, 3, "And it came to pass that"),
        (4, 6, "he begat"),
        (7, 7, "Com,"),
        (8, 11, "and Com reigned"),
        (12, 16, "in his stead;"),
        (17, 21, "and he did reign"),
        (22, 26, "forty years"),
        (27, 29, "and nine,"),
        (30, 35, "and he begat"),
        (36, 36, "Heth;"),
        (37, 41, "and he also begat"),
        (42, 46, "other sons and daughters."),
    ],
    26: [
        (0, 4, "And spread abroad again"),
        (5, 6, "the people"),
        (7, 9, "upon"),
        (10, 12, "all the land,"),
        (13, 17, "and there once more began"),
        (18, 19, "to be"),
        (20, 23, "great wickedness"),
        (24, 28, "upon the land,"),
        (29, 33, "and Heth began"),
        (34, 36, "to embrace again"),
        (37, 39, "the secret plans"),
        (40, 41, "of old,"),
        (42, 44, "to destroy"),
        (45, 46, "his father."),
    ],
    27: [
        (0, 3, "And it came to pass that"),
        (4, 6, "he did remove"),
        (7, 8, "his father"),
        (9, 11, "from the throne,"),
        (12, 15, "for he slew"),
        (16, 18, "him"),
        (19, 22, "with his own sword;"),
        (23, 27, "and he did reign"),
        (28, 32, "in his stead."),
    ],
    28: [
        (0, 3, "And there came"),
        (4, 4, "prophets"),
        (5, 8, "who came again"),
        (9, 11, "into the land,"),
        (12, 14, "and cried"),
        (15, 16, "repentance"),
        (17, 20, "unto them—"),
        (21, 22, "saying that"),
        (23, 27, "they must prepare"),
        (28, 32, "the way of the Lord"),
        (33, 34, "or else"),
        (35, 39, "there should come"),
        (40, 41, "a curse"),
        (42, 46, "upon the land;"),
        (47, 47, "yea,"),
        (48, 53, "there should surely come"),
        (54, 56, "a great famine,"),
        (57, 57, "wherein"),
        (58, 62, "should be destroyed"),
        (63, 64, "them"),
        (65, 67, "if they"),
        (68, 70, "repent not."),
    ],
    29: [
        (0, 3, "But believed not"),
        (4, 4, "the people"),
        (5, 8, "the words of the prophets,"),
        (9, 12, "but they cast"),
        (13, 16, "them out;"),
        (17, 20, "and some others"),
        (21, 23, "of them"),
        (24, 26, "they cast"),
        (27, 30, "into pits"),
        (31, 34, "and left them"),
        (35, 37, "to perish."),
        (38, 41, "And it came to pass that"),
        (42, 43, "they committed"),
        (44, 46, "all these things"),
        (47, 49, "according to"),
        (50, 54, "the commandment of the king,"),
        (55, 56, "Heth."),
    ],
    30: [
        (0, 3, "And it came to pass that"),
        (4, 7, "there began to be"),
        (8, 11, "a great dearth"),
        (12, 16, "upon the land,"),
        (17, 20, "and began"),
        (21, 23, "to perish very fast"),
        (24, 24, "the people"),
        (25, 28, "because of the famine,"),
        (29, 31, "for there was no"),
        (32, 33, "rain"),
        (34, 38, "upon the face of the earth."),
    ],
    31: [
        (0, 4, "And there came also"),
        (5, 6, "venomous serpents"),
        (7, 11, "upon the land,"),
        (12, 15, "and did bite poisonously"),
        (16, 18, "many people."),
        (19, 22, "And it came to pass that"),
        (23, 26, "began to flee away"),
        (27, 29, "their flocks"),
        (30, 32, "from the poisonous serpents,"),
        (33, 35, "toward"),
        (36, 40, "the south country,"),
        (41, 43, "which was called"),
        (44, 46, "by the Nephites"),
        (47, 48, "Zarahemla."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 4, "perished"),
        (5, 9, "the greater part of them"),
        (10, 12, "by the way;"),
        (13, 16, "nevertheless,"),
        (17, 21, "there were some"),
        (22, 24, "who escaped"),
        (25, 29, "into the south country."),
    ],
    33: [
        (0, 3, "And it came to pass that"),
        (4, 4, "caused"),
        (5, 7, "the Lord"),
        (8, 11, "that no longer pursue"),
        (12, 13, "them"),
        (14, 16, "the poisonous serpents,"),
        (17, 20, "but that they block"),
        (21, 22, "the way"),
        (23, 28, "that men could not"),
        (29, 32, "pass through,"),
        (33, 37, "and whosoever"),
        (38, 39, "should try"),
        (40, 43, "to pass through"),
        (44, 47, "might be"),
        (48, 49, "poisoned"),
        (50, 52, "by the poisonous serpents."),
    ],
    34: [
        (0, 3, "And it came to pass that"),
        (4, 6, "followed the people"),
        (7, 11, "the way of the beasts,"),
        (12, 13, "and did eat"),
        (14, 17, "the carcasses of the beasts"),
        (18, 22, "which fell by the way,"),
        (23, 25, "until"),
        (26, 28, "they consumed all"),
        (29, 30, "them."),
        (31, 32, "Now"),
        (33, 36, "when the people saw"),
        (37, 41, "that they should die"),
        (42, 46, "they began to repent"),
        (47, 50, "of their iniquities"),
        (51, 53, "and did cry"),
        (54, 56, "unto the Lord."),
    ],
    35: [
        (0, 4, "And when had"),
        (5, 8, "their humility been enough"),
        (9, 12, "themselves"),
        (13, 17, "before the Lord"),
        (18, 21, "he did send down"),
        (22, 24, "rain"),
        (25, 29, "upon the face of the earth;"),
        (30, 33, "and began"),
        (34, 35, "to revive again"),
        (36, 36, "the people,"),
        (37, 40, "and began"),
        (41, 42, "to be"),
        (43, 45, "fruit"),
        (46, 49, "in the north lands,"),
        (50, 52, "and all the regions"),
        (53, 55, "round about."),
        (56, 59, "And did manifest"),
        (60, 62, "the Lord"),
        (63, 64, "his power"),
        (65, 68, "unto them"),
        (69, 72, "in preserving"),
        (73, 75, "them"),
        (76, 78, "from the famine."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
