"""
Hand-curated TAM-phrase gloss overrides for Helamana (Helaman) 8 — the corrupt
judges of the Gadianton band stir the people against Nephi, but some defend him
as a prophet; Nephi answers, testifying that all the holy prophets from Moses
(who lifted up the brazen serpent) through Abraham, Zenos, Zenock, Ezias,
Isaiah, Jeremiah, Lehi, and his own father witnessed of the coming of Christ;
and he reveals, as a sign, that their chief judge has been murdered by his own
brother.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_helaman8.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "helaman"
CHAPTER_NUM = 8

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 10, "had finished saying"),
        (11, 12, "Nephi"),
        (13, 15, "these words,"),
        (16, 16, "behold,"),
        (17, 20, "there were men"),
        (21, 25, "who were judges,"),
        (26, 31, "who also belonged"),
        (32, 36, "to the secret band of"),
        (37, 37, "Gadianton,"),
        (38, 41, "and they were angry,"),
        (42, 47, "and they cried out against"),
        (48, 50, "him,"),
        (51, 53, "saying"),
        (54, 55, "unto the people:"),
        (56, 56, "Why"),
        (57, 61, "do we not seize"),
        (62, 63, "this man"),
        (64, 67, "and bring him,"),
        (68, 72, "that he be condemned"),
        (73, 75, "according to"),
        (76, 78, "the crime"),
        (79, 81, "which he did?"),
    ],
    2: [
        (0, 0, "Why"),
        (1, 5, "do ye look upon"),
        (6, 8, "this man,"),
        (9, 11, "and hear"),
        (12, 14, "him"),
        (15, 16, "reviling"),
        (17, 19, "against"),
        (20, 21, "this people"),
        (22, 24, "and against"),
        (25, 27, "our law?"),
    ],
    3: [
        (0, 1, "For behold,"),
        (2, 4, "had spoken"),
        (5, 5, "Nephi"),
        (6, 9, "unto them"),
        (10, 12, "concerning"),
        (13, 16, "the unrighteousness of"),
        (17, 19, "their law;"),
        (20, 20, "yea,"),
        (21, 23, "many things"),
        (24, 27, "which spoke"),
        (28, 28, "Nephi"),
        (29, 33, "which cannot"),
        (34, 34, "be written;"),
        (35, 39, "and nothing"),
        (40, 45, "he spoke"),
        (46, 50, "which was contrary to"),
        (51, 52, "the commandments of"),
        (53, 54, "God."),
    ],
    4: [
        (0, 2, "And were angry"),
        (3, 4, "those judges"),
        (5, 7, "with him"),
        (8, 8, "because"),
        (9, 13, "he spoke"),
        (14, 16, "plainly"),
        (17, 20, "unto them"),
        (21, 22, "concerning"),
        (23, 26, "their secret works"),
        (27, 29, "of darkness;"),
        (30, 33, "nevertheless,"),
        (34, 36, "they feared"),
        (37, 39, "to lay"),
        (40, 42, "their hands"),
        (43, 45, "upon him,"),
        (46, 46, "for"),
        (47, 49, "they were afraid"),
        (50, 52, "of the people"),
        (53, 53, "lest"),
        (54, 59, "they cry out against"),
        (60, 63, "them."),
    ],
    5: [
        (0, 1, "Therefore"),
        (2, 6, "they cried out"),
        (7, 8, "unto the people,"),
        (9, 10, "saying:"),
        (11, 11, "Why"),
        (12, 15, "do ye allow"),
        (16, 17, "this man"),
        (18, 21, "to revile against"),
        (22, 24, "us?"),
        (25, 26, "For behold"),
        (27, 30, "he condemns"),
        (31, 33, "all this people,"),
        (34, 37, "even unto"),
        (38, 39, "destruction;"),
        (40, 40, "yea,"),
        (41, 44, "and also"),
        (45, 50, "these our great cities"),
        (51, 54, "shall be taken"),
        (55, 58, "from us,"),
        (59, 66, "and we shall not have"),
        (67, 68, "a place"),
        (69, 73, "in those cities."),
    ],
    6: [
        (0, 2, "And now"),
        (3, 5, "we know"),
        (6, 11, "cannot happen"),
        (12, 14, "this thing,"),
        (15, 16, "for behold,"),
        (17, 19, "we are powerful,"),
        (20, 22, "and are great"),
        (23, 25, "our cities,"),
        (26, 27, "therefore"),
        (28, 32, "cannot"),
        (33, 35, "our enemies"),
        (36, 40, "have any power"),
        (41, 45, "over us."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 5, "thus"),
        (6, 7, "they stirred up"),
        (8, 9, "the people"),
        (10, 11, "to anger"),
        (12, 15, "against Nephi,"),
        (16, 18, "and raised up contentions"),
        (19, 24, "among them;"),
        (25, 25, "for"),
        (26, 30, "there were some"),
        (31, 35, "who cried out:"),
        (36, 39, "Leave alone"),
        (40, 41, "this man,"),
        (42, 44, "for he"),
        (45, 48, "is a good man,"),
        (49, 51, "and the things"),
        (52, 56, "which he said"),
        (57, 61, "will surely come to pass"),
        (62, 63, "except"),
        (64, 66, "we repent;"),
    ],
    8: [
        (0, 0, "Yea,"),
        (1, 1, "behold,"),
        (2, 6, "shall come"),
        (7, 10, "upon us"),
        (11, 12, "all the judgments"),
        (13, 18, "which he testified"),
        (19, 21, "unto us;"),
        (22, 22, "for"),
        (23, 25, "we know"),
        (26, 29, "his testimony is right"),
        (30, 33, "unto us"),
        (34, 38, "concerning our iniquities."),
        (39, 40, "And behold"),
        (41, 44, "they are many,"),
        (45, 49, "and he also knoweth"),
        (50, 51, "all things"),
        (52, 56, "which shall come"),
        (57, 60, "upon us"),
        (61, 65, "as he knoweth"),
        (66, 70, "concerning our iniquities;"),
    ],
    9: [
        (0, 0, "Yea,"),
        (1, 2, "and behold,"),
        (3, 9, "if he were not"),
        (10, 12, "a prophet"),
        (13, 19, "he could not"),
        (20, 21, "testify"),
        (22, 26, "concerning those things."),
    ],
    10: [
        (0, 3, "And it came to pass that"),
        (4, 4, "were compelled"),
        (5, 6, "those"),
        (7, 10, "who sought to destroy"),
        (11, 11, "Nephi"),
        (12, 13, "because of"),
        (14, 16, "their fear,"),
        (17, 22, "they did not lay"),
        (23, 25, "their hands"),
        (26, 28, "on him;"),
        (29, 30, "therefore"),
        (31, 35, "he began again"),
        (36, 38, "he speak"),
        (39, 42, "unto them,"),
        (43, 46, "seeing"),
        (47, 50, "some were pleased"),
        (51, 53, "with him,"),
        (54, 57, "insomuch that"),
        (58, 58, "feared"),
        (59, 65, "the remainder of them."),
    ],
    11: [
        (0, 1, "Therefore"),
        (2, 6, "he was constrained"),
        (7, 10, "to speak further"),
        (11, 14, "unto them"),
        (15, 17, "saying:"),
        (18, 18, "Behold,"),
        (19, 21, "O my brethren,"),
        (22, 26, "have ye not read"),
        (27, 29, "gave"),
        (30, 32, "God"),
        (33, 34, "the power"),
        (35, 39, "unto one man,"),
        (40, 43, "even Moses,"),
        (44, 46, "to smite"),
        (47, 50, "upon the waters of"),
        (51, 54, "the Red Sea,"),
        (55, 57, "and they divided"),
        (58, 61, "to one side"),
        (62, 65, "and the other side,"),
        (66, 68, "insomuch that"),
        (69, 71, "came through"),
        (72, 72, "Israel,"),
        (73, 75, "who were"),
        (76, 78, "our fathers,"),
        (79, 81, "upon"),
        (82, 84, "the dry ground,"),
        (85, 89, "and covered by the waters"),
        (90, 93, "upon the armies of"),
        (94, 94, "Egypt"),
        (95, 97, "and swallowed up"),
        (98, 99, "them?"),
    ],
    12: [
        (0, 3, "And now behold,"),
        (4, 7, "if gave"),
        (8, 10, "God"),
        (11, 13, "unto this man"),
        (14, 16, "such power,"),
        (17, 19, "then why"),
        (20, 23, "do ye dispute"),
        (24, 29, "among yourselves,"),
        (30, 32, "and say"),
        (33, 38, "he has not given"),
        (39, 41, "unto me"),
        (42, 43, "any power"),
        (44, 49, "whereby I may know"),
        (50, 54, "concerning those judgments"),
        (55, 59, "which shall come"),
        (60, 63, "upon you"),
        (64, 65, "except"),
        (66, 68, "ye repent?"),
    ],
    13: [
        (0, 1, "But behold,"),
        (2, 4, "not only"),
        (5, 6, "my words"),
        (7, 9, "ye reject,"),
        (10, 14, "but ye also reject"),
        (15, 16, "all the words"),
        (17, 21, "which were spoken"),
        (22, 24, "by our fathers,"),
        (25, 27, "and also the words"),
        (28, 31, "which spoke"),
        (32, 33, "this man,"),
        (34, 35, "Moses,"),
        (36, 40, "who was given"),
        (41, 43, "unto him"),
        (44, 47, "such great power;"),
        (48, 48, "yea,"),
        (49, 51, "the words"),
        (52, 56, "which he spoke"),
        (57, 59, "concerning"),
        (60, 63, "the coming of"),
        (64, 65, "the Messiah."),
    ],
    14: [
        (0, 0, "Yea,"),
        (1, 6, "did he not bear record"),
        (7, 11, "would come"),
        (12, 14, "the Son of"),
        (15, 16, "God?"),
        (17, 20, "And even as"),
        (21, 26, "he lifted up"),
        (27, 29, "the brazen serpent"),
        (30, 32, "in the wilderness,"),
        (33, 38, "even so shall"),
        (39, 43, "he be lifted up"),
        (44, 45, "who"),
        (46, 50, "should come."),
    ],
    15: [
        (0, 4, "And even as lived"),
        (5, 8, "as many as"),
        (9, 13, "looked up"),
        (14, 16, "upon that serpent,"),
        (17, 22, "even so shall"),
        (23, 25, "be able to live"),
        (26, 30, "as many as"),
        (31, 35, "look up"),
        (36, 38, "with faith"),
        (39, 42, "upon the Son of"),
        (43, 44, "God,"),
        (45, 48, "having"),
        (49, 51, "a contrite spirit,"),
        (52, 55, "unto that very life"),
        (56, 57, "which is eternal."),
    ],
    16: [
        (0, 3, "And now behold,"),
        (4, 7, "not only Moses"),
        (8, 9, "testified"),
        (10, 14, "concerning these things,"),
        (15, 20, "but all the holy prophets also,"),
        (21, 24, "from his days"),
        (25, 28, "even to"),
        (29, 31, "the days of Abraham."),
    ],
    17: [
        (0, 0, "Yea,"),
        (1, 2, "and behold,"),
        (3, 4, "saw"),
        (5, 5, "Abraham"),
        (6, 9, "of his coming,"),
        (10, 14, "and he was filled"),
        (15, 17, "with gladness"),
        (18, 20, "and did rejoice."),
    ],
    18: [
        (0, 0, "Yea,"),
        (1, 2, "and behold,"),
        (3, 6, "I say"),
        (7, 9, "unto you,"),
        (10, 13, "not only"),
        (14, 16, "Abraham knew"),
        (17, 21, "concerning these things,"),
        (22, 27, "but there were many"),
        (28, 31, "before"),
        (32, 34, "the days of Abraham"),
        (35, 38, "who were called"),
        (39, 42, "by the order of"),
        (43, 44, "God;"),
        (45, 45, "yea,"),
        (46, 49, "even according to"),
        (50, 52, "the order of"),
        (53, 54, "his Son,"),
        (55, 57, "which they knew;"),
        (58, 62, "and this was done"),
        (63, 63, "because"),
        (64, 67, "it should be revealed"),
        (68, 70, "those things"),
        (71, 72, "unto the people,"),
        (73, 79, "many thousands of years"),
        (80, 83, "before"),
        (84, 86, "his coming,"),
        (87, 92, "would surely come"),
        (93, 94, "the redemption"),
        (95, 98, "unto them."),
    ],
    19: [
        (0, 2, "And now"),
        (3, 5, "I desire"),
        (6, 9, "that ye know,"),
        (10, 11, "since"),
        (12, 14, "the days of Abraham"),
        (15, 18, "there were indeed"),
        (19, 21, "many prophets"),
        (22, 26, "who testified"),
        (27, 29, "of these things;"),
        (30, 30, "yea,"),
        (31, 31, "behold,"),
        (32, 35, "testified"),
        (36, 38, "boldly"),
        (39, 41, "the prophet"),
        (42, 42, "Zenos;"),
        (43, 45, "for which"),
        (46, 50, "he was slain."),
    ],
    20: [
        (0, 1, "And behold,"),
        (2, 4, "also Zenock,"),
        (5, 7, "and also Ezias,"),
        (8, 10, "and also Isaiah,"),
        (11, 12, "and Jeremiah,"),
        (13, 14, "(Jeremiah"),
        (15, 21, "being that same prophet"),
        (22, 24, "who testified"),
        (25, 27, "concerning"),
        (28, 30, "the destruction of"),
        (31, 31, "Jerusalem)"),
        (32, 34, "and now"),
        (35, 37, "we know"),
        (38, 39, "was destroyed"),
        (40, 40, "Jerusalem"),
        (41, 43, "according to"),
        (44, 46, "the words of Jeremiah."),
        (47, 49, "So then"),
        (50, 50, "why"),
        (51, 57, "would not come"),
        (58, 60, "the Son of"),
        (61, 62, "God,"),
        (63, 65, "according to"),
        (66, 67, "his prophecy?"),
    ],
    21: [
        (0, 2, "And now"),
        (3, 6, "will ye doubt"),
        (7, 8, "was destroyed"),
        (9, 9, "Jerusalem?"),
        (10, 14, "Will ye say"),
        (15, 17, "were not slain"),
        (18, 20, "all the sons of"),
        (21, 21, "Zedekiah,"),
        (22, 26, "all of them"),
        (27, 29, "except Mulek?"),
        (30, 30, "Yea,"),
        (31, 37, "and do ye not see"),
        (38, 39, "are together"),
        (40, 43, "the seed of Zedekiah"),
        (44, 46, "with us,"),
        (47, 52, "and they were driven out"),
        (53, 56, "from the land of"),
        (57, 57, "Jerusalem?"),
        (58, 59, "But behold,"),
        (60, 64, "this is not all—"),
    ],
    22: [
        (0, 2, "Was driven out"),
        (3, 6, "our father"),
        (7, 7, "Lehi"),
        (8, 9, "from Jerusalem"),
        (10, 10, "because"),
        (11, 14, "he testified"),
        (15, 19, "concerning these things."),
        (20, 22, "Also testified"),
        (23, 23, "Nephi"),
        (24, 28, "concerning these things,"),
        (29, 32, "and almost also"),
        (33, 37, "all our fathers,"),
        (38, 41, "even down"),
        (42, 45, "to this time;"),
        (46, 46, "yea,"),
        (47, 50, "they testified"),
        (51, 53, "concerning"),
        (54, 57, "the coming of"),
        (58, 58, "Christ,"),
        (59, 61, "and looked"),
        (62, 63, "forward,"),
        (64, 65, "and rejoiced"),
        (66, 68, "in his day"),
        (69, 73, "which is to come."),
    ],
    23: [
        (0, 1, "And behold,"),
        (2, 6, "he is God,"),
        (7, 11, "and he was together"),
        (12, 14, "with them,"),
        (15, 19, "and he revealed"),
        (20, 22, "himself"),
        (23, 26, "unto them,"),
        (27, 30, "and he redeemed"),
        (31, 32, "them;"),
        (33, 37, "and they gave"),
        (38, 40, "unto him"),
        (41, 42, "the glory,"),
        (43, 44, "because of"),
        (45, 46, "that thing"),
        (47, 51, "which is to come."),
    ],
    24: [
        (0, 2, "And now,"),
        (3, 6, "seeing ye know"),
        (7, 8, "these things"),
        (9, 13, "and cannot"),
        (14, 15, "ye deny"),
        (16, 17, "except"),
        (18, 20, "ye lie,"),
        (21, 22, "therefore"),
        (23, 26, "ye have sinned"),
        (27, 29, "in this thing,"),
        (30, 30, "for"),
        (31, 33, "ye have rejected"),
        (34, 36, "all these things,"),
        (37, 39, "notwithstanding"),
        (40, 43, "the many evidences"),
        (44, 46, "which ye received;"),
        (47, 47, "yea,"),
        (48, 51, "ye have received indeed"),
        (52, 53, "all things,"),
        (54, 57, "things in"),
        (58, 59, "heaven,"),
        (60, 62, "and all things"),
        (63, 66, "which are in"),
        (67, 68, "the earth,"),
        (69, 71, "as a witness"),
        (72, 75, "that they are true."),
    ],
    25: [
        (0, 1, "But behold,"),
        (2, 4, "ye have rejected"),
        (5, 6, "the truth,"),
        (7, 10, "and rebelled against"),
        (11, 14, "your holy God;"),
        (15, 19, "and even at"),
        (20, 21, "this time,"),
        (22, 23, "instead of"),
        (24, 25, "laying up"),
        (26, 28, "for yourselves"),
        (29, 30, "treasures"),
        (31, 33, "in heaven,"),
        (34, 39, "where nothing corrupts,"),
        (40, 43, "and a place"),
        (44, 51, "where cannot come"),
        (52, 54, "anything unclean,"),
        (55, 57, "ye are heaping up"),
        (58, 60, "for yourselves"),
        (61, 62, "the wrath"),
        (63, 67, "before comes"),
        (68, 70, "the day of"),
        (71, 72, "judgment."),
    ],
    26: [
        (0, 0, "Yea,"),
        (1, 4, "even at"),
        (5, 7, "this time"),
        (8, 12, "ye are ripening,"),
        (13, 14, "because of"),
        (15, 18, "your murders,"),
        (19, 22, "and your fornication"),
        (23, 24, "and wickedness,"),
        (25, 28, "for the enduring destruction"),
        (29, 30, "forever;"),
        (31, 31, "yea,"),
        (32, 32, "and"),
        (33, 35, "except"),
        (36, 38, "ye repent,"),
        (39, 45, "it will soon come"),
        (46, 48, "unto you."),
    ],
    27: [
        (0, 0, "Yea,"),
        (1, 1, "behold,"),
        (2, 6, "it is now even"),
        (7, 10, "at your doors;"),
        (11, 11, "yea,"),
        (12, 16, "go ye"),
        (17, 19, "unto the judgment-seat,"),
        (20, 21, "and search;"),
        (22, 23, "and behold,"),
        (24, 25, "is murdered"),
        (26, 28, "your judge,"),
        (29, 34, "and he lies"),
        (35, 37, "in his blood;"),
        (38, 42, "and he was murdered"),
        (43, 45, "by his brother,"),
        (46, 49, "who seeks"),
        (50, 52, "to sit in"),
        (53, 54, "the judgment-seat."),
    ],
    28: [
        (0, 1, "And behold,"),
        (2, 6, "they both belong"),
        (7, 11, "to your secret band,"),
        (12, 15, "whose author is"),
        (16, 16, "Gadianton"),
        (17, 20, "and the evil one"),
        (21, 24, "who seeks"),
        (25, 26, "to destroy"),
        (27, 29, "the souls of men."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
