"""
Hand-curated TAM-phrase gloss overrides for Mamona (Mormon) 5 — Mormon repents of his
oath and again leads the Nephites, though without hope, for they will not repent; the
Lamanites overrun the land, and the Nephites are swept before them. Mormon turns to the
latter-day reader: the record shall come forth by the power of God, the remnant of Jacob
shall be scattered and smitten yet not utterly destroyed, and the Gentiles are called to
repent that the covenants of the Father may be fulfilled and Israel restored.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15). `o le a` stays atomic and is never fused with a
following `se X` NP; cells go past 5 only for rule-2 (absorbed subject) or
rule-7 (`o le a` + verb + directional) clusters.

Em-dash pre-splits applied to bom_books.json before glossing:
    5:14  ai—ina     ->  ai—     +  ina
    5:24  outou—nei  ->  outou—  +  nei

    python3 build_overrides_mormon5.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "mormon"
CHAPTER_NUM = 5

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 6, "I did go forth"),
        (7, 9, "among"),
        (10, 12, "the Nephites,"),
        (13, 16, "and did repent"),
        (17, 19, "of the oath"),
        (20, 22, "which I had made"),
        (23, 27, "that I would no more assist"),
        (28, 31, "them;"),
        (32, 35, "and they again"),
        (36, 37, "gave"),
        (38, 40, "me"),
        (41, 42, "the command"),
        (43, 46, "of their armies,"),
        (47, 47, "for"),
        (48, 51, "they looked"),
        (52, 54, "upon me"),
        (55, 56, "as though"),
        (57, 61, "I could deliver"),
        (62, 63, "them"),
        (64, 65, "out of"),
        (66, 68, "their afflictions."),
    ],
    2: [
        (0, 1, "But behold,"),
        (2, 4, "I was without"),
        (5, 7, "any hope,"),
        (8, 11, "for I knew"),
        (12, 13, "the judgments"),
        (14, 16, "of the Lord"),
        (17, 21, "which should come"),
        (22, 23, "upon"),
        (24, 27, "them;"),
        (28, 28, "for"),
        (29, 32, "they repented not"),
        (33, 35, "of their iniquities,"),
        (36, 39, "but did struggle"),
        (40, 43, "for their lives"),
        (44, 46, "without"),
        (47, 49, "calling upon"),
        (50, 53, "that Being"),
        (54, 57, "who created"),
        (58, 59, "them."),
    ],
    3: [
        (0, 3, "And it came to pass that"),
        (4, 5, "did come"),
        (6, 7, "the Lamanites"),
        (8, 10, "against"),
        (11, 14, "us"),
        (15, 19, "as we had fled"),
        (20, 22, "to the city"),
        (23, 24, "of Jordan;"),
        (25, 26, "but behold,"),
        (27, 30, "they were driven"),
        (31, 32, "back"),
        (33, 37, "that they did not take"),
        (38, 39, "the city"),
        (40, 43, "at that time."),
    ],
    4: [
        (0, 3, "And it came to pass that"),
        (4, 7, "they came again"),
        (8, 10, "against"),
        (11, 14, "us,"),
        (15, 18, "and we did maintain"),
        (19, 20, "the city."),
        (21, 25, "And there were also"),
        (26, 27, "other cities"),
        (28, 29, "which were held"),
        (30, 32, "by the Nephites,"),
        (33, 36, "which strongholds"),
        (37, 41, "which shielded"),
        (42, 43, "them,"),
        (44, 47, "that could not"),
        (48, 51, "they go forth"),
        (52, 55, "into the country which"),
        (56, 57, "which was"),
        (58, 60, "before us,"),
        (61, 63, "to destroy the inhabitants"),
        (64, 67, "of our land."),
    ],
    5: [
        (0, 3, "But it came to pass that"),
        (4, 7, "whatsoever lands"),
        (8, 12, "we had passed by,"),
        (13, 17, "and were not gathered in"),
        (18, 20, "the inhabitants thereof,"),
        (21, 22, "were destroyed"),
        (23, 25, "by the Lamanites,"),
        (26, 29, "and their"),
        (30, 31, "towns,"),
        (32, 33, "and villages,"),
        (34, 35, "and cities"),
        (36, 37, "were burned"),
        (38, 40, "with fire;"),
        (41, 44, "and thus"),
        (45, 46, "passed away"),
        (47, 50, "three hundred"),
        (51, 54, "and seventy and nine"),
        (55, 56, "years."),
    ],
    6: [
        (0, 2, "And it came to pass"),
        (3, 5, "in the year"),
        (6, 8, "three hundred"),
        (9, 11, "and eightieth,"),
        (12, 16, "did come again"),
        (17, 18, "the Lamanites"),
        (19, 21, "against"),
        (22, 25, "us to battle,"),
        (26, 30, "and we did stand against"),
        (31, 34, "them"),
        (35, 37, "boldly;"),
        (38, 38, "but"),
        (39, 43, "it was all in vain,"),
        (44, 44, "for"),
        (45, 48, "were exceedingly many"),
        (49, 51, "their numbers"),
        (52, 54, "that"),
        (55, 58, "they trod down"),
        (59, 62, "their feet"),
        (63, 64, "the people"),
        (65, 66, "of the Nephites."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 6, "we did flee again,"),
        (7, 10, "and they"),
        (11, 12, "who"),
        (13, 15, "were swifter"),
        (16, 18, "their flight"),
        (19, 20, "than"),
        (21, 22, "the Lamanites"),
        (23, 25, "did escape,"),
        (26, 29, "but they"),
        (30, 31, "who"),
        (32, 35, "were not swifter"),
        (36, 38, "their flight"),
        (39, 40, "than"),
        (41, 42, "the Lamanites"),
        (43, 47, "were swept down"),
        (48, 49, "and destroyed."),
    ],
    8: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 5, "I,"),
        (6, 7, "Mormon,"),
        (8, 11, "do not desire"),
        (12, 13, "to harrow up"),
        (14, 14, "the souls"),
        (15, 16, "of men"),
        (17, 20, "in casting before"),
        (21, 24, "before them"),
        (25, 28, "such an awful scene"),
        (29, 31, "of blood"),
        (32, 35, "and carnage"),
        (36, 39, "as was laid"),
        (40, 42, "before"),
        (43, 44, "mine eyes;"),
        (45, 47, "but I,"),
        (48, 50, "knowing"),
        (51, 53, "that these things"),
        (54, 58, "must surely be made known,"),
        (59, 62, "and all things"),
        (63, 64, "which are hid"),
        (65, 69, "must be revealed"),
        (70, 72, "upon"),
        (73, 75, "the tops of houses—"),
    ],
    9: [
        (0, 4, "And also must"),
        (5, 6, "come"),
        (7, 8, "a knowledge"),
        (9, 11, "of"),
        (12, 13, "these things"),
        (14, 16, "unto the portion"),
        (17, 18, "of the remnant"),
        (19, 21, "of these people,"),
        (22, 25, "and also unto the Gentiles,"),
        (26, 27, "who"),
        (28, 30, "hath said"),
        (31, 32, "the Lord"),
        (33, 36, "should be scattered"),
        (37, 38, "this people,"),
        (39, 43, "and should be counted"),
        (44, 45, "this people"),
        (46, 48, "as naught"),
        (49, 51, "among"),
        (52, 53, "them—"),
        (54, 55, "therefore"),
        (56, 59, "I write"),
        (60, 62, "a small abridgment,"),
        (63, 66, "daring not"),
        (67, 69, "to give"),
        (70, 72, "a full account"),
        (73, 74, "of the things"),
        (75, 77, "which I have seen,"),
        (78, 79, "because of"),
        (80, 82, "the commandment which"),
        (83, 85, "I have received,"),
        (86, 88, "and that"),
        (89, 91, "not also come"),
        (92, 94, "unto you"),
        (95, 97, "too great sorrow"),
        (98, 99, "because of"),
        (100, 101, "the wickedness"),
        (102, 104, "of this people."),
    ],
    10: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 7, "this thing"),
        (8, 12, "I speak"),
        (13, 15, "unto their seed,"),
        (16, 18, "and also the Gentiles"),
        (19, 20, "who"),
        (21, 25, "shall have"),
        (26, 27, "care"),
        (28, 30, "for the house"),
        (31, 32, "of Israel,"),
        (33, 36, "who realize"),
        (37, 38, "and know"),
        (39, 43, "from whence come"),
        (44, 46, "their blessings."),
    ],
    11: [
        (0, 3, "For I know"),
        (4, 6, "that such"),
        (7, 10, "will sorrow"),
        (11, 13, "for the calamity"),
        (14, 16, "of the house"),
        (17, 18, "of Israel;"),
        (19, 19, "yea,"),
        (20, 24, "they will sorrow"),
        (25, 27, "for the destruction"),
        (28, 30, "of this people;"),
        (31, 35, "they will sorrow"),
        (36, 36, "that"),
        (37, 39, "had not repented"),
        (40, 41, "this people"),
        (42, 43, "that they might"),
        (44, 47, "have been able to be"),
        (48, 48, "clasped"),
        (49, 50, "them"),
        (51, 52, "in the arms"),
        (53, 54, "of Jesus."),
    ],
    12: [
        (0, 1, "Now"),
        (2, 3, "are written"),
        (4, 5, "these things"),
        (6, 8, "unto the portion"),
        (9, 10, "of the remnant"),
        (11, 13, "of the house"),
        (14, 15, "of Jacob;"),
        (16, 18, "and are written"),
        (19, 20, "these things"),
        (21, 23, "after this manner,"),
        (24, 24, "because"),
        (25, 26, "it is known"),
        (27, 29, "of God"),
        (30, 32, "that wickedness"),
        (33, 37, "will not bring forth"),
        (38, 39, "them"),
        (40, 43, "unto them;"),
        (44, 47, "but they are hid up"),
        (48, 49, "they"),
        (50, 52, "unto the Lord"),
        (53, 56, "that may come forth"),
        (57, 58, "them"),
        (59, 62, "in his own time"),
        (63, 65, "due."),
    ],
    13: [
        (0, 4, "And this is the commandment"),
        (5, 7, "which I have received;"),
        (8, 9, "and behold,"),
        (10, 14, "they shall come forth"),
        (15, 16, "these things"),
        (17, 19, "according to"),
        (20, 21, "the commandment"),
        (22, 24, "of the Lord,"),
        (25, 29, "when he seeth fit"),
        (30, 32, "in his wisdom,"),
        (33, 35, "as is meet."),
    ],
    14: [
        (0, 1, "And behold,"),
        (2, 6, "shall go forth"),
        (7, 8, "these things"),
        (9, 10, "unto them"),
        (11, 13, "who believe not"),
        (14, 16, "of the Jews;"),
        (17, 21, "and for this intent"),
        (22, 28, "shall they go forth—"),
        (29, 32, "that may"),
        (33, 34, "be persuaded"),
        (35, 36, "them"),
        (37, 38, "that Jesus"),
        (39, 41, "is the Christ,"),
        (42, 44, "the Son"),
        (45, 48, "of the living God;"),
        (49, 53, "that may bring about"),
        (54, 56, "the Father,"),
        (57, 59, "through"),
        (60, 62, "his most Beloved,"),
        (63, 65, "his great purpose"),
        (66, 67, "and eternal,"),
        (68, 70, "in restoring"),
        (71, 73, "of the Jews,"),
        (74, 78, "or all the house"),
        (79, 80, "of Israel,"),
        (81, 83, "to the land"),
        (84, 87, "of their inheritance,"),
        (88, 88, "which"),
        (89, 91, "was given"),
        (92, 95, "unto them"),
        (96, 98, "by the Lord"),
        (99, 101, "their God,"),
        (102, 104, "for the fulfilling"),
        (105, 107, "of his covenant."),
    ],
    15: [
        (0, 4, "And also that may"),
        (5, 6, "the seed"),
        (7, 9, "of this people"),
        (10, 12, "more fully believe"),
        (13, 15, "his gospel,"),
        (16, 16, "which"),
        (17, 21, "shall go forth"),
        (22, 25, "unto them"),
        (26, 26, "from"),
        (27, 27, "the Gentiles;"),
        (28, 28, "for"),
        (29, 32, "shall be scattered"),
        (33, 34, "this people,"),
        (35, 39, "and shall become"),
        (40, 42, "a people"),
        (43, 43, "dark,"),
        (44, 44, "filthy,"),
        (45, 46, "and loathsome,"),
        (47, 50, "beyond"),
        (51, 52, "the description"),
        (53, 54, "of that which"),
        (55, 57, "hath been"),
        (58, 60, "among"),
        (61, 62, "us,"),
        (63, 63, "yea,"),
        (64, 67, "even unto"),
        (68, 68, "that which"),
        (69, 71, "hath been"),
        (72, 74, "among"),
        (75, 76, "the Lamanites;"),
        (77, 80, "and the cause"),
        (81, 83, "of this thing"),
        (84, 85, "because of"),
        (86, 89, "their unbelief"),
        (90, 92, "and the bowing"),
        (93, 94, "to idols."),
    ],
    16: [
        (0, 1, "For behold,"),
        (2, 5, "hath already ceased to strive"),
        (6, 7, "the Spirit"),
        (8, 10, "of the Lord"),
        (11, 14, "with their fathers;"),
        (15, 18, "and they are without"),
        (19, 20, "Christ"),
        (21, 23, "and God"),
        (24, 26, "in the world;"),
        (27, 30, "and are driven about"),
        (31, 32, "they"),
        (33, 35, "as"),
        (36, 38, "the chaff of wheat"),
        (39, 41, "before"),
        (42, 43, "the wind."),
    ],
    17: [
        (0, 3, "They were"),
        (4, 4, "once"),
        (5, 8, "a delightsome people,"),
        (9, 12, "and they had"),
        (13, 13, "Christ"),
        (14, 18, "for their shepherd;"),
        (19, 19, "yea,"),
        (20, 24, "they were led"),
        (25, 27, "by God"),
        (28, 29, "the Father."),
    ],
    18: [
        (0, 4, "But at this time,"),
        (5, 5, "behold,"),
        (6, 8, "are led about"),
        (9, 10, "they"),
        (11, 12, "by Satan,"),
        (13, 15, "even as"),
        (16, 18, "the chaff of wheat"),
        (19, 20, "is driven"),
        (21, 23, "before"),
        (24, 25, "the wind,"),
        (26, 30, "or as a vessel"),
        (31, 33, "is tossed about"),
        (34, 37, "upon the waves,"),
        (38, 40, "without"),
        (41, 42, "a sail"),
        (43, 46, "or anchor,"),
        (47, 51, "or without also"),
        (52, 53, "a thing"),
        (54, 56, "whereby to"),
        (57, 60, "steer her;"),
        (61, 65, "and even as"),
        (66, 69, "she is,"),
        (70, 72, "so also are"),
        (73, 74, "they."),
    ],
    19: [
        (0, 1, "And behold,"),
        (2, 3, "hath reserved"),
        (4, 6, "the Lord"),
        (7, 9, "their blessings,"),
        (10, 10, "which"),
        (11, 14, "they might have received"),
        (15, 17, "in the land,"),
        (18, 19, "for the Gentiles"),
        (20, 21, "who"),
        (22, 25, "shall possess"),
        (26, 27, "the land."),
    ],
    20: [
        (0, 1, "But behold,"),
        (2, 6, "it shall come that"),
        (7, 7, "driven"),
        (8, 9, "and scattered"),
        (10, 11, "they"),
        (12, 13, "by the Gentiles;"),
        (14, 18, "and after"),
        (19, 19, "driven"),
        (20, 21, "and scattered"),
        (22, 23, "they"),
        (24, 25, "by the Gentiles,"),
        (26, 26, "behold,"),
        (27, 30, "then will remember"),
        (31, 33, "the Lord"),
        (34, 36, "the covenant which"),
        (37, 39, "he made"),
        (40, 41, "unto Abraham"),
        (42, 45, "and all the house"),
        (46, 47, "of Israel."),
    ],
    21: [
        (0, 0, "And"),
        (1, 5, "will also remember"),
        (6, 8, "the Lord"),
        (9, 9, "the prayers"),
        (10, 12, "of the righteous,"),
        (13, 13, "which"),
        (14, 16, "were offered"),
        (17, 19, "unto him"),
        (20, 22, "for them."),
    ],
    22: [
        (0, 2, "And now,"),
        (3, 5, "O ye Gentiles,"),
        (6, 8, "how can"),
        (9, 12, "ye stand"),
        (13, 15, "before"),
        (16, 17, "the power"),
        (18, 20, "of God,"),
        (21, 22, "except"),
        (23, 25, "ye repent"),
        (26, 28, "and turn"),
        (29, 30, "from"),
        (31, 34, "your evil ways?"),
    ],
    23: [
        (0, 4, "Know ye not"),
        (5, 8, "that ye are"),
        (9, 10, "in the hands"),
        (11, 13, "of God?"),
        (14, 18, "Know ye not"),
        (19, 22, "that he hath"),
        (23, 25, "all power,"),
        (26, 28, "and by his"),
        (29, 30, "great command"),
        (31, 34, "shall be rolled together"),
        (35, 36, "the earth"),
        (37, 41, "as a scroll?"),
    ],
    24: [
        (0, 1, "Therefore,"),
        (2, 4, "repent ye,"),
        (5, 8, "and humble yourselves"),
        (9, 11, "before him,"),
        (12, 16, "lest he come"),
        (17, 19, "in justice"),
        (20, 21, "against"),
        (22, 24, "you—"),
        (25, 27, "lest go forth"),
        (28, 32, "among you"),
        (33, 34, "a portion"),
        (35, 36, "of the remnant"),
        (37, 39, "of the seed"),
        (40, 41, "of Jacob"),
        (42, 46, "as a lion,"),
        (47, 49, "and tear in pieces"),
        (50, 50, "you,"),
        (51, 54, "and there is none"),
        (55, 56, "to deliver."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
