"""Hand-curated TAM-phrase gloss overrides for Iakopo 1 — Nephi commissions Jacob / King-succession."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "jacob"
CHAPTER_NUM = 1
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "For behold,"),
        (2, 6, "had passed"),
        (7, 9, "fifty"),
        (10, 12, "and five"),
        (13, 14, "of years"),
        (15, 17, "since left"),
        (18, 19, "by Lehi"),
        (20, 20, "Jerusalem;"),
        (21, 24, "wherefore,"),
        (25, 28, "did give thereto"),
        (29, 30, "by Nephi"),
        (31, 33, "unto me,"),
        (34, 35, "Jacob,"),
        (36, 37, "a commandment"),
        (38, 40, "concerning"),
        (41, 42, "small plates,"),
        (43, 45, "are engraven thereto"),
        (46, 47, "upon"),
        (48, 49, "these things."),
    ],
    2: [
        (0, 0, "And"),
        (1, 3, "gave"),
        (4, 5, "by him"),
        (6, 8, "unto me,"),
        (9, 10, "Jacob,"),
        (11, 12, "a commandment"),
        (13, 15, "should"),
        (16, 17, "I write"),
        (18, 20, "upon these plates"),
        (21, 23, "a few things"),
        (24, 26, "I thought"),
        (27, 30, "most precious;"),
        (31, 35, "and should not"),
        (36, 37, "I touch"),
        (38, 42, "neither should"),
        (43, 46, "I touch thereto,"),
        (47, 47, "save"),
        (48, 52, "a few things,"),
        (53, 55, "concerning"),
        (56, 57, "the history"),
        (58, 60, "of this people"),
        (61, 62, "called"),
        (63, 65, "the people"),
        (66, 67, "of Nephi."),
    ],
    3: [
        (0, 0, "For"),
        (1, 3, "said"),
        (4, 5, "he"),
        (6, 8, "the history"),
        (9, 11, "of his people"),
        (12, 14, "should"),
        (15, 15, "be written"),
        (16, 19, "on his other plates,"),
        (20, 20, "and"),
        (21, 23, "should"),
        (24, 25, "I preserve"),
        (26, 27, "these plates"),
        (28, 31, "and hand down"),
        (32, 34, "to my seed,"),
        (35, 37, "from generation"),
        (38, 40, "to generation."),
    ],
    4: [
        (0, 0, "And"),
        (1, 4, "if there be"),
        (5, 8, "preachings that are sacred,"),
        (9, 12, "or revelation"),
        (13, 15, "that was great,"),
        (16, 19, "or prophecy,"),
        (20, 22, "should"),
        (23, 24, "I engrave"),
        (25, 27, "their heads"),
        (28, 29, "upon"),
        (30, 32, "of these plates,"),
        (33, 34, "and touch"),
        (35, 37, "concerning thereto"),
        (38, 40, "to the much"),
        (41, 43, "as can be,"),
        (44, 47, "concerning Christ,"),
        (48, 51, "and for the welfare"),
        (52, 55, "of our people."),
    ],
    5: [
        (0, 0, "For"),
        (1, 4, "because of faith"),
        (5, 8, "and great anxiety,"),
        (9, 10, "thereto"),
        (11, 15, "was truly made manifest"),
        (16, 19, "unto us,"),
        (20, 22, "concerning"),
        (23, 25, "our people,"),
        (26, 26, "things"),
        (27, 30, "shall happen"),
        (31, 34, "unto them."),
    ],
    6: [
        (0, 0, "And"),
        (1, 4, "we had also"),
        (5, 7, "revelations many,"),
        (8, 10, "and the spirit"),
        (11, 14, "of prophecy in much;"),
        (15, 18, "wherefore,"),
        (19, 22, "we knew thereto"),
        (23, 26, "concerning Christ"),
        (27, 29, "and his kingdom,"),
        (30, 34, "shall come."),
    ],
    7: [
        (0, 3, "Wherefore"),
        (4, 7, "we did labor thereto"),
        (8, 10, "with diligence"),
        (11, 14, "among our people,"),
        (15, 18, "that may"),
        (19, 20, "we persuade"),
        (21, 22, "them"),
        (23, 25, "to come"),
        (26, 27, "to Christ,"),
        (28, 30, "and partake"),
        (31, 33, "of the goodness"),
        (34, 36, "of the God,"),
        (37, 40, "that may"),
        (41, 43, "they enter"),
        (44, 46, "into his rest,"),
        (47, 49, "lest there be"),
        (50, 51, "a reason"),
        (52, 55, "must thereto"),
        (56, 56, "swear"),
        (57, 58, "he"),
        (59, 61, "in his wrath"),
        (62, 65, "should not"),
        (66, 70, "they enter thereto,"),
        (71, 73, "as"),
        (74, 75, "the provocation"),
        (76, 77, "in the days"),
        (78, 80, "of the temptation"),
        (81, 83, "while were"),
        (84, 85, "the children"),
        (86, 87, "of Israel"),
        (88, 90, "in the wilderness."),
    ],
    8: [
        (0, 3, "Wherefore,"),
        (4, 7, "we pray thereto"),
        (8, 10, "to the God"),
        (11, 13, "that may"),
        (14, 15, "we persuade"),
        (16, 17, "all men"),
        (18, 20, "not to rebel"),
        (21, 24, "against the God,"),
        (25, 27, "to provoke thereto"),
        (28, 29, "his wrath,"),
        (30, 32, "but to believe"),
        (33, 34, "all men"),
        (35, 36, "in Christ,"),
        (37, 38, "and view"),
        (39, 41, "his death,"),
        (42, 43, "and suffer"),
        (44, 46, "his cross"),
        (47, 48, "and bear"),
        (49, 49, "the shame"),
        (50, 52, "of the world;"),
        (53, 56, "wherefore,"),
        (57, 60, "I, Jacob,"),
        (61, 64, "I take thereto"),
        (65, 67, "upon me"),
        (68, 69, "to fulfill"),
        (70, 71, "the commandment"),
        (72, 74, "of my brother"),
        (75, 76, "Nephi."),
    ],
    9: [
        (0, 1, "Now"),
        (2, 5, "began to be old"),
        (6, 7, "Nephi,"),
        (8, 8, "and"),
        (9, 12, "did see by him"),
        (13, 18, "must shortly die;"),
        (19, 22, "wherefore"),
        (23, 25, "did anoint thereto"),
        (26, 27, "by him"),
        (28, 29, "a man"),
        (30, 33, "to be a king"),
        (34, 35, "and ruler"),
        (36, 37, "over"),
        (38, 40, "his people,"),
        (41, 43, "according to"),
        (44, 44, "the reigns"),
        (45, 46, "of kings."),
    ],
    10: [
        (0, 0, "For"),
        (1, 4, "the great love"),
        (5, 7, "of the people"),
        (8, 9, "for Nephi,"),
        (10, 13, "for had been he"),
        (14, 17, "a great protector"),
        (18, 20, "for them,"),
        (21, 23, "in his wielding"),
        (24, 26, "of the sword"),
        (27, 28, "of Laban"),
        (29, 32, "for their defense,"),
        (33, 33, "and"),
        (34, 37, "in his laboring thereto"),
        (38, 41, "all his days"),
        (42, 45, "for their welfare—"),
    ],
    11: [
        (0, 3, "Wherefore,"),
        (4, 8, "did desire thereto the people"),
        (9, 11, "to continue"),
        (12, 13, "remembering still"),
        (14, 16, "his name."),
        (17, 17, "And"),
        (18, 20, "whosoever"),
        (21, 23, "should reign"),
        (24, 25, "to succeed"),
        (26, 28, "in his place"),
        (29, 30, "was called"),
        (31, 33, "by the people,"),
        (34, 36, "Nephi second,"),
        (37, 39, "and Nephi third,"),
        (40, 42, "and so forth,"),
        (43, 45, "according to"),
        (46, 46, "the reigns"),
        (47, 48, "of kings;"),
        (49, 49, "and"),
        (50, 53, "thus were called"),
        (54, 55, "they"),
        (56, 58, "by the people,"),
        (59, 64, "whatsoever"),
        (65, 65, "names"),
        (66, 68, "were called thereto"),
        (69, 70, "them."),
    ],
    12: [
        (0, 0, "And"),
        (1, 4, "died"),
        (5, 5, "Nephi."),
    ],
    13: [
        (0, 1, "Now"),
        (2, 3, "the people"),
        (4, 9, "were not Lamanites,"),
        (10, 13, "were Nephites;"),
        (14, 17, "nevertheless,"),
        (18, 19, "were called"),
        (20, 21, "them"),
        (22, 24, "Nephites,"),
        (25, 27, "Jacobites,"),
        (28, 30, "Josephites,"),
        (31, 33, "Zoramites,"),
        (34, 36, "Lamanites,"),
        (37, 39, "Lemuelites,"),
        (40, 42, "and Ishmaelites."),
    ],
    14: [
        (0, 0, "But"),
        (1, 4, "I, Jacob,"),
        (5, 9, "I no more distinguish"),
        (10, 11, "them"),
        (12, 14, "by these names,"),
        (15, 15, "but"),
        (16, 20, "I will call"),
        (21, 23, "Lamanites"),
        (24, 25, "them"),
        (26, 29, "who seek"),
        (30, 31, "to destroy"),
        (32, 33, "the people"),
        (34, 35, "of Nephi;"),
        (36, 36, "and"),
        (37, 39, "those"),
        (40, 43, "who love"),
        (44, 45, "Nephi"),
        (46, 50, "I will call"),
        (51, 53, "Nephites,"),
        (54, 59, "or the people of Nephi,"),
        (60, 62, "according to"),
        (63, 63, "the reigns"),
        (64, 65, "of kings."),
    ],
    15: [
        (0, 2, "And now"),
        (3, 5, "the people"),
        (6, 7, "of Nephi,"),
        (8, 9, "under"),
        (10, 12, "the reign"),
        (13, 17, "of the second king,"),
        (18, 22, "began to grow hard"),
        (23, 26, "in their hearts,"),
        (27, 29, "and give"),
        (30, 32, "themselves"),
        (33, 34, "to do"),
        (35, 37, "wicked practices,"),
        (38, 42, "as David of old"),
        (43, 44, "desired"),
        (45, 46, "wives"),
        (47, 50, "and many concubines,"),
        (51, 52, "and also"),
        (53, 54, "Solomon,"),
        (55, 56, "his son."),
    ],
    16: [
        (0, 0, "Yea,"),
        (1, 5, "and also began"),
        (6, 7, "they seek"),
        (8, 13, "after gold and silver much,"),
        (14, 16, "and began"),
        (17, 20, "to lift up themselves"),
        (21, 23, "in pride."),
    ],
    17: [
        (0, 3, "Wherefore,"),
        (4, 7, "I, Jacob,"),
        (8, 12, "did declare thereto"),
        (13, 16, "unto them"),
        (17, 18, "these words"),
        (19, 21, "as I taught"),
        (22, 23, "them"),
        (24, 26, "in the temple,"),
        (27, 30, "after"),
        (31, 33, "I had first received"),
        (34, 37, "my errand"),
        (38, 40, "from the Lord."),
    ],
    18: [
        (0, 4, "For I, Jacob,"),
        (5, 9, "and my brother Joseph"),
        (10, 11, "had been consecrated"),
        (12, 14, "priests"),
        (15, 16, "and teachers"),
        (17, 19, "of this people,"),
        (20, 22, "by the hand"),
        (23, 24, "of Nephi."),
    ],
    19: [
        (0, 0, "And"),
        (1, 3, "we did magnify"),
        (4, 6, "our office"),
        (7, 9, "unto the Lord,"),
        (10, 10, "and"),
        (11, 11, "taking"),
        (12, 15, "upon us"),
        (16, 17, "the responsibility,"),
        (18, 19, "to answer"),
        (20, 21, "upon"),
        (22, 26, "our own heads"),
        (27, 27, "the sins"),
        (28, 30, "of the people,"),
        (31, 32, "if"),
        (33, 37, "we did not teach"),
        (38, 41, "unto them"),
        (42, 43, "the word"),
        (44, 46, "of the God"),
        (47, 50, "with all diligence;"),
        (51, 54, "wherefore,"),
        (55, 57, "by laboring"),
        (58, 62, "with all our might,"),
        (63, 68, "shall not come"),
        (69, 69, "thereto"),
        (70, 72, "their blood"),
        (73, 74, "upon"),
        (75, 78, "our garments;"),
        (79, 82, "otherwise"),
        (83, 87, "shall come"),
        (88, 90, "their blood"),
        (91, 92, "upon"),
        (93, 96, "our garments,"),
        (97, 97, "and"),
        (98, 102, "shall not be found"),
        (103, 104, "we"),
        (105, 108, "spotless"),
        (109, 112, "at the last day."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
