"""
Hand-curated TAM-phrase gloss overrides for Helamana (Helaman) 11 — years of war
and Gadianton wickedness lead Nephi to pray for a famine instead of the sword;
the famine grows so grievous the people perish, until they humble themselves and
plead with Nephi to intercede; he prays, the rains return, and the Nephites
honor him; the robbers are subdued and peace is restored for a season, but pride
and iniquity soon creep back and the secret band grows again toward the ninetieth
year.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_helaman11.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "helaman"
CHAPTER_NUM = 11

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 4, "it came to pass"),
        (5, 7, "in the seventieth"),
        (8, 10, "and second"),
        (11, 12, "year"),
        (13, 16, "of the reign of"),
        (17, 17, "the judges"),
        (18, 19, "increased"),
        (20, 20, "the contentions,"),
        (21, 23, "insomuch that"),
        (24, 26, "there were wars"),
        (27, 30, "in all the land"),
        (31, 33, "among"),
        (34, 37, "all the people of Nephi."),
    ],
    2: [
        (0, 4, "And this secret band"),
        (5, 8, "of robbers"),
        (9, 12, "was they"),
        (13, 17, "who carried on"),
        (18, 20, "this work of"),
        (21, 22, "destruction"),
        (23, 25, "and wickedness."),
        (26, 29, "And this war was waged"),
        (30, 34, "all that year;"),
        (35, 38, "and was also waged"),
        (39, 43, "in all the year"),
        (44, 47, "seventy and third."),
    ],
    3: [
        (0, 2, "And it came to pass"),
        (3, 6, "in this year,"),
        (7, 10, "cried out"),
        (11, 11, "Nephi"),
        (12, 14, "unto the Lord,"),
        (15, 17, "saying:"),
    ],
    4: [
        (0, 2, "O Lord,"),
        (3, 6, "do not suffer"),
        (7, 8, "this people"),
        (9, 10, "to be destroyed"),
        (11, 13, "by the sword;"),
        (14, 17, "but O Lord,"),
        (18, 23, "let there be"),
        (24, 25, "a famine"),
        (26, 28, "in the land,"),
        (29, 33, "to stir them up"),
        (34, 35, "to remember"),
        (36, 40, "the Lord their God,"),
        (41, 42, "and perhaps"),
        (43, 48, "they will repent"),
        (49, 51, "and turn"),
        (52, 54, "unto thee."),
    ],
    5: [
        (0, 5, "And so it was done,"),
        (6, 8, "according to"),
        (9, 11, "the words of Nephi."),
        (12, 15, "And there was"),
        (16, 18, "a great famine"),
        (19, 21, "which came"),
        (22, 26, "upon the land,"),
        (27, 29, "among"),
        (30, 33, "all the people of Nephi."),
        (34, 39, "And thus continued"),
        (40, 42, "the famine"),
        (43, 45, "in the seventieth"),
        (46, 48, "and fourth"),
        (49, 50, "year,"),
        (51, 54, "and it came that"),
        (55, 60, "the work of destruction ceased"),
        (61, 65, "by the sword"),
        (66, 68, "but grew grievous"),
        (69, 72, "because of the famine."),
    ],
    6: [
        (0, 4, "And this work of"),
        (5, 6, "destruction"),
        (7, 9, "also continued"),
        (10, 13, "in the year"),
        (14, 17, "seventy and fifth."),
        (18, 18, "For"),
        (19, 22, "the earth was smitten"),
        (23, 26, "insomuch it became dry,"),
        (27, 31, "and yielded not"),
        (32, 32, "grain"),
        (33, 37, "in the season of grain;"),
        (38, 40, "and was smitten"),
        (41, 43, "the whole land,"),
        (44, 48, "even among"),
        (49, 50, "the Lamanites"),
        (51, 56, "as well as among"),
        (57, 58, "the Nephites,"),
        (59, 61, "insomuch that"),
        (62, 64, "they were smitten"),
        (65, 67, "and perished"),
        (68, 74, "thousands of them"),
        (75, 80, "in the more wicked parts of"),
        (81, 82, "the land."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 5, "the people saw"),
        (6, 11, "they would perish"),
        (12, 14, "by the famine,"),
        (15, 18, "and they began to"),
        (19, 20, "they remember"),
        (21, 25, "the Lord their God;"),
        (26, 29, "and they began to"),
        (30, 31, "they remember"),
        (32, 34, "the words of Nephi."),
    ],
    8: [
        (0, 3, "And began to"),
        (4, 6, "the people plead"),
        (7, 11, "with their chief judges"),
        (12, 15, "and their leaders,"),
        (16, 20, "that they say"),
        (21, 22, "unto Nephi:"),
        (23, 23, "Behold,"),
        (24, 26, "we know"),
        (27, 31, "thou art a man of"),
        (32, 34, "God,"),
        (35, 37, "and therefore"),
        (38, 41, "cry thou"),
        (42, 47, "unto the Lord our God"),
        (48, 49, "that he remove"),
        (50, 51, "this famine"),
        (52, 56, "from us,"),
        (57, 58, "lest be fulfilled"),
        (59, 60, "all the words"),
        (61, 65, "which thou spoke"),
        (66, 68, "concerning"),
        (69, 73, "our destruction."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 6, "the judges said"),
        (7, 8, "unto Nephi"),
        (9, 12, "according to the words"),
        (13, 17, "which were desired."),
        (18, 21, "And it came to pass that"),
        (22, 24, "when Nephi saw"),
        (25, 27, "the people had repented"),
        (28, 31, "and they humbled"),
        (32, 34, "themselves"),
        (35, 38, "in sackcloth,"),
        (39, 44, "he cried again"),
        (45, 47, "unto the Lord,"),
        (48, 50, "saying:"),
    ],
    10: [
        (0, 2, "O Lord,"),
        (3, 3, "behold"),
        (4, 7, "this people repents;"),
        (8, 12, "and they swept away"),
        (13, 16, "the band of Gadianton"),
        (17, 22, "from among them"),
        (23, 25, "insomuch that"),
        (26, 31, "they are no more,"),
        (32, 35, "and they concealed"),
        (36, 39, "their secret plans"),
        (40, 42, "in the earth."),
    ],
    11: [
        (0, 1, "Now,"),
        (2, 4, "O Lord,"),
        (5, 6, "because of"),
        (7, 10, "this their humility,"),
        (11, 14, "may thou turn away"),
        (15, 16, "thine anger,"),
        (17, 19, "and let be appeased"),
        (20, 21, "thine anger"),
        (22, 24, "in the destruction of"),
        (25, 27, "the wicked men"),
        (28, 32, "whom already"),
        (33, 34, "thou destroyed."),
    ],
    12: [
        (0, 2, "O Lord,"),
        (3, 6, "may thou turn away"),
        (7, 8, "thine anger,"),
        (9, 9, "yea,"),
        (10, 12, "thy fierce anger,"),
        (13, 14, "and cause"),
        (15, 16, "that cease"),
        (17, 18, "this famine"),
        (19, 21, "in this land."),
    ],
    13: [
        (0, 2, "O Lord,"),
        (3, 6, "may thou hearken"),
        (7, 9, "unto me,"),
        (10, 11, "and cause"),
        (12, 16, "that it be fulfilled"),
        (17, 21, "according to my words,"),
        (22, 24, "and send forth"),
        (25, 26, "the rain"),
        (27, 31, "upon the face of the earth,"),
        (32, 35, "that may"),
        (36, 37, "bring forth"),
        (38, 39, "her fruit,"),
        (40, 42, "and her grain"),
        (43, 47, "in the season of grain."),
    ],
    14: [
        (0, 2, "O Lord,"),
        (3, 6, "thou didst hearken"),
        (7, 9, "unto my words"),
        (10, 14, "when I said,"),
        (15, 17, "Let there be"),
        (18, 19, "a famine,"),
        (20, 22, "that cease"),
        (23, 25, "the calamity of"),
        (26, 27, "the sword;"),
        (28, 31, "and I am sure"),
        (32, 36, "thou wilt be willing"),
        (37, 40, "even at this time,"),
        (41, 43, "to hearken"),
        (44, 46, "unto my words,"),
        (47, 47, "for"),
        (48, 51, "thou saidst"),
        (52, 53, "thus:"),
        (54, 56, "If repent"),
        (57, 58, "this people,"),
        (59, 63, "I will spare"),
        (64, 65, "them."),
    ],
    15: [
        (0, 0, "Yea,"),
        (1, 3, "O Lord,"),
        (4, 8, "and thou seest"),
        (9, 11, "they have repented,"),
        (12, 13, "because of"),
        (14, 15, "the famine"),
        (16, 18, "and the pestilence"),
        (19, 21, "and destruction"),
        (22, 24, "which came"),
        (25, 28, "upon them."),
    ],
    16: [
        (0, 2, "And now,"),
        (3, 5, "O Lord,"),
        (6, 11, "wilt thou turn away"),
        (12, 13, "thine anger,"),
        (14, 18, "and try them again"),
        (19, 25, "whether they will serve"),
        (26, 28, "thee?"),
        (29, 31, "And if so,"),
        (32, 34, "O Lord,"),
        (35, 38, "thou canst"),
        (39, 40, "bless"),
        (41, 42, "them"),
        (43, 45, "according to"),
        (46, 47, "thy words"),
        (48, 53, "which thou didst speak."),
    ],
    17: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the seventieth"),
        (7, 9, "and sixth"),
        (10, 11, "year,"),
        (12, 14, "turned away"),
        (15, 17, "the Lord"),
        (18, 19, "his anger"),
        (20, 22, "from the people,"),
        (23, 25, "and he caused"),
        (26, 28, "that fall"),
        (29, 30, "the rain"),
        (31, 33, "upon the earth,"),
        (34, 36, "insomuch that"),
        (37, 38, "it brought forth"),
        (39, 41, "its fruit"),
        (42, 48, "in its fruiting season."),
        (49, 52, "And it came that"),
        (53, 57, "it brought forth"),
        (58, 59, "its grain"),
        (60, 66, "in its harvest season."),
    ],
    18: [
        (0, 1, "And behold,"),
        (2, 4, "the people rejoiced"),
        (5, 7, "and glorified"),
        (8, 10, "God,"),
        (11, 13, "and was filled"),
        (14, 17, "the face of the land"),
        (18, 20, "with rejoicing;"),
        (21, 26, "and they no more sought"),
        (27, 29, "to destroy Nephi,"),
        (30, 33, "but they honored"),
        (34, 36, "him"),
        (37, 40, "as a great prophet,"),
        (41, 45, "and a man of"),
        (46, 47, "God,"),
        (48, 50, "having"),
        (51, 56, "great power and authority"),
        (57, 59, "given"),
        (60, 62, "unto him"),
        (63, 65, "from God."),
    ],
    19: [
        (0, 1, "And behold,"),
        (2, 3, "Lehi,"),
        (4, 5, "his brother,"),
        (6, 12, "was not at all less"),
        (13, 16, "than him"),
        (17, 19, "pertaining to"),
        (20, 23, "things of righteousness."),
    ],
    20: [
        (0, 5, "And thus it came to pass that"),
        (6, 9, "began again to prosper"),
        (10, 14, "the people of Nephi"),
        (15, 17, "in the land,"),
        (18, 20, "and began to"),
        (21, 23, "they rebuild"),
        (24, 27, "their waste places,"),
        (28, 30, "and began to"),
        (31, 31, "multiply"),
        (32, 34, "and spread,"),
        (35, 37, "even until"),
        (38, 39, "they filled"),
        (40, 44, "the whole face of the land,"),
        (45, 49, "on the northward"),
        (50, 54, "and on the southward,"),
        (55, 59, "from the sea west"),
        (60, 64, "to the sea east."),
    ],
    21: [
        (0, 4, "And ended"),
        (5, 7, "the seventieth"),
        (8, 10, "and sixth"),
        (11, 12, "year"),
        (13, 15, "in peace."),
        (16, 18, "And began"),
        (19, 21, "the seventieth"),
        (22, 24, "and seventh"),
        (25, 26, "year"),
        (27, 29, "in peace;"),
        (30, 33, "and spread"),
        (34, 35, "the church"),
        (36, 41, "over all the land;"),
        (42, 47, "and the greater part of"),
        (48, 48, "the people,"),
        (49, 51, "both the Nephites"),
        (52, 54, "and the Lamanites,"),
        (55, 57, "belonged to"),
        (58, 59, "the church;"),
        (60, 63, "and they had"),
        (64, 66, "great peace"),
        (67, 69, "in the land;"),
        (70, 74, "and thus ended"),
        (75, 77, "the seventieth"),
        (78, 80, "and seventh"),
        (81, 82, "year."),
    ],
    22: [
        (0, 4, "And they also had"),
        (5, 6, "peace"),
        (7, 10, "in the seventieth"),
        (11, 13, "and eighth"),
        (14, 15, "year,"),
        (16, 17, "except"),
        (18, 20, "a few contentions"),
        (21, 23, "concerning"),
        (24, 25, "the points of"),
        (26, 27, "doctrine"),
        (28, 31, "which was laid down"),
        (32, 33, "by the prophets."),
    ],
    23: [
        (0, 4, "And in the year"),
        (5, 8, "seventy and ninth"),
        (9, 13, "there began to be"),
        (14, 17, "much contention."),
        (18, 18, "But"),
        (19, 22, "Nephi and Lehi,"),
        (23, 26, "and many of"),
        (27, 29, "their brethren"),
        (30, 33, "who understood"),
        (34, 36, "concerning"),
        (37, 39, "the true points of"),
        (40, 41, "doctrine,"),
        (42, 42, "for"),
        (43, 45, "they received"),
        (46, 48, "many revelations"),
        (49, 51, "daily,"),
        (52, 54, "insomuch that"),
        (55, 57, "they preached"),
        (58, 60, "unto the people,"),
        (61, 67, "and thus it came that"),
        (68, 69, "they ended"),
        (70, 72, "their contentions"),
        (73, 76, "in that same year."),
    ],
    24: [
        (0, 2, "And it came to pass"),
        (3, 7, "in the eightieth year"),
        (8, 11, "of the reign of"),
        (12, 12, "the judges"),
        (13, 17, "over the people of Nephi,"),
        (18, 22, "there were a number of"),
        (23, 25, "dissenters"),
        (26, 30, "from the people of Nephi,"),
        (31, 35, "who went over"),
        (36, 38, "unto the Lamanites"),
        (39, 43, "some years past,"),
        (44, 46, "and they took"),
        (47, 51, "upon themselves"),
        (52, 56, "the name of the Lamanites,"),
        (57, 60, "and also a number of"),
        (61, 66, "those who truly descended from"),
        (67, 68, "the Lamanites,"),
        (69, 72, "were stirred up"),
        (73, 75, "to anger"),
        (76, 78, "by them,"),
        (79, 83, "or by those dissenters,"),
        (84, 85, "therefore"),
        (86, 89, "they began"),
        (90, 91, "a war"),
        (92, 95, "with their brethren."),
    ],
    25: [
        (0, 3, "And they committed"),
        (4, 6, "murder"),
        (7, 9, "and robbery;"),
        (10, 15, "and then they fled"),
        (16, 19, "back into the mountains,"),
        (20, 23, "and into the wilderness"),
        (24, 26, "and secret places,"),
        (27, 31, "hiding themselves"),
        (32, 36, "that they could not"),
        (37, 39, "be found,"),
        (40, 43, "and receiving an addition"),
        (44, 47, "to their number"),
        (48, 50, "daily,"),
        (51, 54, "inasmuch as"),
        (55, 56, "dissenters"),
        (57, 59, "who went"),
        (60, 63, "unto them."),
    ],
    26: [
        (0, 4, "And thus it came to pass"),
        (5, 7, "in time,"),
        (8, 8, "yea,"),
        (9, 13, "even in the space of"),
        (14, 15, "years"),
        (16, 19, "not very many,"),
        (20, 25, "they became"),
        (26, 28, "a band of robbers"),
        (29, 32, "exceedingly great;"),
        (33, 36, "and they searched out"),
        (37, 40, "all the secret plans of"),
        (41, 41, "Gadianton;"),
        (42, 45, "and thus"),
        (46, 49, "they became"),
        (50, 53, "robbers of Gadianton."),
    ],
    27: [
        (0, 2, "Now behold,"),
        (3, 7, "these robbers made"),
        (8, 10, "great havoc,"),
        (11, 11, "yea,"),
        (12, 16, "even great destruction"),
        (17, 23, "among the people of Nephi,"),
        (24, 28, "and also among"),
        (29, 32, "the people of the Lamanites."),
    ],
    28: [
        (0, 3, "And it came to pass that"),
        (4, 6, "it was needful to stop"),
        (7, 9, "this work of"),
        (10, 11, "destruction;"),
        (12, 13, "therefore"),
        (14, 18, "they sent forth"),
        (19, 21, "an army of"),
        (22, 24, "strong men"),
        (25, 27, "into the wilderness"),
        (28, 31, "and upon the mountains"),
        (32, 33, "to seek out"),
        (34, 37, "this band of robbers,"),
        (38, 41, "and to destroy them."),
    ],
    29: [
        (0, 1, "But behold,"),
        (2, 4, "it came that"),
        (5, 9, "they were driven back"),
        (10, 11, "backward"),
        (12, 16, "into their own lands"),
        (17, 20, "in that same year."),
        (21, 25, "And thus ended"),
        (26, 30, "the eightieth year"),
        (31, 34, "of the reign of"),
        (35, 35, "the judges"),
        (36, 41, "over the people of"),
        (42, 42, "Nephi."),
    ],
    30: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the beginning of"),
        (7, 10, "the eightieth year"),
        (11, 13, "and first"),
        (14, 18, "they went forth again"),
        (19, 21, "against"),
        (22, 25, "this band of robbers,"),
        (26, 29, "and they destroyed"),
        (30, 31, "many;"),
        (32, 36, "and thus also"),
        (37, 39, "they were visited"),
        (40, 43, "with great destruction."),
    ],
    31: [
        (0, 5, "And they were again compelled"),
        (6, 8, "to return"),
        (9, 13, "from the wilderness and mountains"),
        (14, 18, "unto their own lands,"),
        (19, 20, "because of"),
        (21, 24, "the exceeding greatness of"),
        (25, 29, "the number of those robbers"),
        (30, 34, "who filled"),
        (35, 38, "the mountains and the wilderness."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 6, "thus ended"),
        (7, 9, "this year."),
        (10, 13, "And still increased"),
        (14, 16, "the robbers"),
        (17, 19, "and grew strong,"),
        (20, 22, "insomuch that"),
        (23, 24, "they defied"),
        (25, 27, "all the armies of"),
        (28, 29, "the Nephites,"),
        (30, 33, "and also the armies of"),
        (34, 35, "the Lamanites;"),
        (36, 39, "and they caused"),
        (40, 42, "a great fear"),
        (43, 45, "to come"),
        (46, 47, "unto the people"),
        (48, 53, "upon all the land."),
    ],
    33: [
        (0, 0, "Yea,"),
        (1, 1, "insomuch that"),
        (2, 4, "they visited"),
        (5, 9, "many parts of"),
        (10, 11, "the land,"),
        (12, 15, "and made great destruction"),
        (16, 19, "unto them;"),
        (20, 20, "yea,"),
        (21, 23, "they killed"),
        (24, 25, "many,"),
        (26, 28, "and carried away others"),
        (29, 29, "captive"),
        (30, 32, "into the wilderness,"),
        (33, 33, "yea,"),
        (34, 37, "and more especially"),
        (38, 40, "their women"),
        (41, 44, "and their children."),
    ],
    34: [
        (0, 5, "So this great evil,"),
        (6, 9, "which came"),
        (10, 11, "unto the people"),
        (12, 13, "because of"),
        (14, 16, "their iniquity,"),
        (17, 22, "it stirred them up again"),
        (23, 24, "to remember"),
        (25, 29, "the Lord their God."),
    ],
    35: [
        (0, 4, "And thus ended"),
        (5, 9, "the eightieth year"),
        (10, 12, "and first"),
        (13, 16, "of the reign of"),
        (17, 17, "the judges."),
    ],
    36: [
        (0, 4, "And in the year"),
        (5, 8, "eighty and second"),
        (9, 13, "began again also"),
        (14, 18, "was forgotten by them"),
        (19, 23, "the Lord their God."),
        (24, 28, "And in the year"),
        (29, 32, "eighty and third"),
        (33, 35, "they began to"),
        (36, 38, "progressively increase"),
        (39, 41, "their iniquity."),
        (42, 46, "And in the year"),
        (47, 50, "eighty and fourth"),
        (51, 54, "they did not amend"),
        (55, 57, "their ways."),
    ],
    37: [
        (0, 2, "And it came to pass"),
        (3, 7, "in the eightieth year"),
        (8, 10, "and fifth"),
        (11, 17, "they grew stronger and stronger"),
        (18, 21, "in their pride,"),
        (22, 26, "and in their wickedness;"),
        (27, 31, "and thus also"),
        (32, 35, "they ripened again"),
        (36, 38, "for destruction."),
    ],
    38: [
        (0, 4, "And thus ended"),
        (5, 8, "the year"),
        (9, 12, "eighty and fifth."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
