"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 49 — the Lamanites
attack the fortified cities of Ammonihah and Noah and are repulsed with great
loss by Moroni's earthworks and defenses; Amalickiah rages and curses God; the
Nephites give thanks and are strengthened in their faith.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_alma49.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 49

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 4, "it came to pass"),
        (5, 7, "in the month"),
        (8, 12, "eleventh"),
        (13, 19, "of the nineteenth"),
        (20, 21, "year,"),
        (22, 25, "on the tenth day"),
        (26, 28, "of the month,"),
        (29, 31, "were seen"),
        (32, 33, "the armies of"),
        (34, 35, "the Lamanites"),
        (36, 39, "drawing near"),
        (40, 43, "to the land of"),
        (44, 44, "Ammonihah."),
    ],
    2: [
        (0, 1, "And behold,"),
        (2, 6, "had been rebuilt"),
        (7, 9, "the city,"),
        (10, 12, "and had placed"),
        (13, 14, "Moroni"),
        (15, 16, "an army"),
        (17, 19, "by the side of"),
        (20, 23, "the borders of the city,"),
        (24, 29, "and they cast up"),
        (30, 32, "earth round about"),
        (33, 35, "to protect"),
        (36, 37, "them"),
        (38, 40, "from the arrows"),
        (41, 43, "and the stones of"),
        (44, 45, "the Lamanites;"),
        (46, 47, "for behold,"),
        (48, 50, "they fought"),
        (51, 52, "with stones"),
        (53, 54, "and arrows."),
    ],
    3: [
        (0, 0, "Behold,"),
        (1, 4, "I said"),
        (5, 7, "was rebuilt"),
        (8, 10, "the city of"),
        (11, 11, "Ammonihah."),
        (12, 15, "I say"),
        (16, 18, "unto you,"),
        (19, 19, "yea,"),
        (20, 22, "was rebuilt"),
        (23, 24, "a part;"),
        (25, 26, "and because"),
        (27, 28, "was destroyed"),
        (29, 31, "by the Lamanites"),
        (32, 35, "at a former time"),
        (36, 37, "because of"),
        (38, 40, "the iniquity of"),
        (41, 41, "the people,"),
        (42, 43, "therefore"),
        (44, 47, "they thought"),
        (48, 51, "it would be easy"),
        (52, 55, "for them again to take"),
        (56, 58, "for themselves."),
    ],
    4: [
        (0, 1, "But behold,"),
        (2, 5, "how exceedingly great was"),
        (6, 8, "their disappointment;"),
        (9, 10, "for behold,"),
        (11, 12, "had dug"),
        (13, 15, "the Nephites"),
        (16, 19, "a bank of earth"),
        (20, 20, "round about"),
        (21, 23, "them,"),
        (24, 24, "which"),
        (25, 29, "was exceedingly high"),
        (30, 33, "could not"),
        (34, 36, "the Lamanites"),
        (37, 38, "throw"),
        (39, 41, "their stones"),
        (42, 43, "and shoot"),
        (44, 46, "their arrows"),
        (47, 50, "at them"),
        (51, 54, "that they hit,"),
        (55, 60, "nor could they"),
        (61, 62, "come"),
        (63, 67, "upon them"),
        (68, 69, "except"),
        (70, 73, "coming through"),
        (74, 76, "their place"),
        (77, 80, "of entering."),
    ],
    5: [
        (0, 1, "Now"),
        (2, 5, "were greatly astonished"),
        (6, 8, "the chief captains of"),
        (9, 10, "the Lamanites"),
        (11, 14, "at that time,"),
        (15, 16, "because of"),
        (17, 19, "the wisdom of"),
        (20, 21, "the Nephites"),
        (22, 25, "in the preparing of"),
        (26, 29, "their places of"),
        (30, 31, "security."),
    ],
    6: [
        (0, 1, "Now"),
        (2, 3, "had supposed"),
        (4, 5, "the leaders of"),
        (6, 7, "the Lamanites,"),
        (8, 9, "because of"),
        (10, 12, "the greatness of"),
        (13, 15, "their number,"),
        (16, 16, "yea,"),
        (17, 19, "they thought"),
        (20, 24, "that they should gain"),
        (25, 26, "the chance"),
        (27, 31, "for them to come"),
        (32, 34, "upon"),
        (35, 36, "them"),
        (37, 41, "as they had done"),
        (42, 42, "before;"),
        (43, 43, "yea,"),
        (44, 48, "and they also prepared"),
        (49, 51, "themselves"),
        (52, 54, "with shields,"),
        (55, 56, "and breastplates;"),
        (57, 61, "and they also prepared"),
        (62, 64, "themselves"),
        (65, 66, "with"),
        (67, 68, "skin garments,"),
        (69, 69, "yea,"),
        (70, 73, "very thick garments"),
        (74, 76, "to cover"),
        (77, 80, "their nakedness."),
    ],
    7: [
        (0, 1, "And because"),
        (2, 6, "they were thus prepared,"),
        (7, 10, "they thought"),
        (11, 14, "it would be easy"),
        (15, 17, "for them to overpower"),
        (18, 19, "and subject"),
        (20, 22, "their brethren"),
        (23, 26, "to the yoke of"),
        (27, 28, "bondage,"),
        (29, 30, "or slay"),
        (31, 33, "and massacre"),
        (34, 35, "them"),
        (36, 38, "according to"),
        (39, 41, "their will."),
    ],
    8: [
        (0, 1, "But behold,"),
        (2, 4, "in their"),
        (5, 6, "great astonishment,"),
        (7, 10, "they were prepared"),
        (11, 13, "for them,"),
        (14, 16, "in a way"),
        (17, 20, "which was never known"),
        (21, 23, "among"),
        (24, 26, "the children of"),
        (27, 27, "Lehi."),
        (28, 29, "Now"),
        (30, 32, "they were prepared"),
        (33, 35, "for the Lamanites,"),
        (36, 37, "to fight"),
        (38, 41, "according to"),
        (42, 43, "the instructions of"),
        (44, 44, "Moroni."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 6, "were greatly astonished"),
        (7, 8, "the Lamanites,"),
        (9, 10, "or"),
        (11, 12, "the Amalickiahites,"),
        (13, 15, "at the way"),
        (16, 19, "they had prepared"),
        (20, 21, "for war."),
    ],
    10: [
        (0, 1, "Now,"),
        (2, 5, "if had come down"),
        (6, 9, "king Amalickiah"),
        (10, 13, "from the land of"),
        (14, 14, "Nephi,"),
        (15, 16, "leading"),
        (17, 19, "his army,"),
        (20, 20, "perhaps"),
        (21, 23, "he commanded"),
        (24, 25, "the Lamanites"),
        (26, 28, "that they attack"),
        (29, 30, "the Nephites"),
        (31, 34, "at the city of"),
        (35, 35, "Ammonihah;"),
        (36, 37, "for behold,"),
        (38, 42, "he cared not"),
        (43, 46, "for the blood of"),
        (47, 48, "his people."),
    ],
    11: [
        (0, 1, "But behold,"),
        (2, 5, "did not come down"),
        (6, 8, "Amalickiah himself"),
        (9, 11, "to the battle."),
        (12, 13, "And behold,"),
        (14, 15, "feared"),
        (16, 18, "his chief captains"),
        (19, 20, "to attack"),
        (21, 22, "the Nephites"),
        (23, 26, "at the city of"),
        (27, 27, "Ammonihah,"),
        (28, 30, "for had changed"),
        (31, 32, "Moroni"),
        (33, 35, "the management of"),
        (36, 36, "things"),
        (37, 39, "among"),
        (40, 41, "the Nephites,"),
        (42, 45, "insomuch that"),
        (46, 48, "the Lamanites were dismayed"),
        (49, 52, "in their places"),
        (53, 56, "which they retreated to"),
        (57, 63, "and they could not"),
        (64, 68, "come upon them."),
    ],
    12: [
        (0, 1, "Therefore"),
        (2, 6, "they withdrew"),
        (7, 9, "into the wilderness,"),
        (10, 11, "and moved"),
        (12, 14, "their camp"),
        (15, 17, "and marched"),
        (18, 19, "towards"),
        (20, 23, "the land of Noah,"),
        (24, 25, "thinking"),
        (26, 29, "that place"),
        (30, 31, "was next"),
        (32, 35, "the best"),
        (36, 38, "for them"),
        (39, 41, "to attack"),
        (42, 43, "the Nephites."),
    ],
    13: [
        (0, 4, "For they knew not"),
        (5, 8, "had fortified"),
        (9, 10, "Moroni,"),
        (11, 16, "or he had built"),
        (17, 19, "protecting towers,"),
        (20, 22, "for each city"),
        (23, 25, "in the land"),
        (26, 27, "all round about;"),
        (28, 29, "therefore"),
        (30, 34, "they marched forth"),
        (35, 38, "to the land of"),
        (39, 39, "Noah"),
        (40, 43, "with a firm resolve;"),
        (44, 44, "yea,"),
        (45, 47, "came"),
        (48, 49, "forward"),
        (50, 53, "their chief captains"),
        (54, 55, "and made"),
        (56, 57, "an oath"),
        (58, 62, "that they would destroy"),
        (63, 64, "the people of"),
        (65, 66, "that city."),
    ],
    14: [
        (0, 1, "But behold,"),
        (2, 4, "in their"),
        (5, 6, "great astonishment,"),
        (7, 10, "the city of"),
        (11, 11, "Noah,"),
        (12, 15, "which had been"),
        (16, 17, "a weak place"),
        (18, 21, "in past days,"),
        (22, 25, "because of"),
        (26, 26, "Moroni,"),
        (27, 30, "had now become"),
        (31, 32, "a strong city,"),
        (33, 33, "yea,"),
        (34, 36, "even exceeded"),
        (37, 38, "the strength"),
        (39, 41, "than"),
        (42, 45, "the city of Ammonihah."),
    ],
    15: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 7, "this was the wisdom"),
        (8, 10, "which Moroni had;"),
        (11, 15, "for he supposed"),
        (16, 20, "that they would fear"),
        (21, 24, "at the city of"),
        (25, 25, "Ammonihah;"),
        (26, 28, "and because"),
        (29, 32, "the city of Noah"),
        (33, 35, "had been"),
        (36, 40, "the very weakest part"),
        (41, 43, "of the land"),
        (44, 47, "in past days,"),
        (48, 49, "therefore"),
        (50, 56, "they would march"),
        (57, 57, "there"),
        (58, 60, "to fight;"),
        (61, 66, "and thus it happened"),
        (67, 69, "according to"),
        (70, 71, "his desires."),
    ],
    16: [
        (0, 1, "And behold,"),
        (2, 3, "had appointed"),
        (4, 5, "Moroni"),
        (6, 7, "Lehi"),
        (8, 10, "to become"),
        (11, 12, "chief captain"),
        (13, 15, "over"),
        (16, 17, "the men of"),
        (18, 19, "that city;"),
        (20, 24, "and it was that very Lehi"),
        (25, 28, "who fought"),
        (29, 31, "with the Lamanites"),
        (32, 34, "in the valley"),
        (35, 39, "on the east side"),
        (40, 43, "of the river"),
        (44, 44, "Sidon."),
    ],
    17: [
        (0, 2, "And now"),
        (3, 3, "behold"),
        (4, 6, "it came to pass that"),
        (7, 8, "when found"),
        (9, 11, "the Lamanites"),
        (12, 13, "that Lehi"),
        (14, 15, "commanded"),
        (16, 17, "the city"),
        (18, 21, "they were again dismayed,"),
        (22, 26, "for they greatly feared"),
        (27, 28, "Lehi;"),
        (29, 32, "nevertheless"),
        (33, 34, "had made"),
        (35, 39, "their chief captains"),
        (40, 41, "an oath"),
        (42, 43, "to attack"),
        (44, 45, "the city;"),
        (46, 47, "therefore"),
        (48, 52, "they brought up"),
        (53, 55, "their armies."),
    ],
    18: [
        (0, 1, "Now"),
        (2, 2, "behold,"),
        (3, 5, "could not"),
        (6, 8, "the Lamanites"),
        (9, 11, "go"),
        (12, 13, "inside"),
        (14, 18, "their towers of"),
        (19, 21, "safe protection"),
        (22, 26, "by any other way"),
        (27, 28, "except"),
        (29, 31, "by the gate"),
        (32, 35, "of entering,"),
        (36, 37, "because of"),
        (38, 40, "the height of"),
        (41, 42, "the bank"),
        (43, 46, "which was raised up,"),
        (47, 50, "and the depth of"),
        (51, 52, "the ditch"),
        (53, 56, "which was dug round about,"),
        (57, 58, "except"),
        (59, 61, "by the gate"),
        (62, 65, "of entering."),
    ],
    19: [
        (0, 4, "And thus were prepared"),
        (5, 7, "the Nephites"),
        (8, 9, "to destroy"),
        (10, 12, "all of them"),
        (13, 16, "who tried"),
        (17, 19, "to climb"),
        (20, 21, "up"),
        (22, 25, "to enter inside"),
        (26, 28, "into the tower"),
        (29, 34, "by any other way,"),
        (35, 37, "by means of"),
        (38, 43, "the throwing over of"),
        (44, 44, "stones"),
        (45, 48, "and the shooting of"),
        (49, 50, "arrows"),
        (51, 53, "at them."),
    ],
    20: [
        (0, 4, "Thus they were prepared,"),
        (5, 5, "yea,"),
        (6, 9, "a body of"),
        (10, 13, "their strong men,"),
        (14, 18, "they smite down"),
        (19, 22, "with their swords"),
        (23, 26, "and their slings,"),
        (27, 29, "all of them"),
        (30, 33, "who tried"),
        (34, 38, "to come inside"),
        (39, 43, "their place of"),
        (44, 46, "safe protection"),
        (47, 50, "through"),
        (51, 52, "the gate"),
        (53, 56, "of entering;"),
        (57, 62, "and thus they prepared"),
        (63, 64, "to defend"),
        (65, 67, "themselves"),
        (68, 69, "against"),
        (70, 72, "the Lamanites."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 4, "raised"),
        (5, 7, "the captains of"),
        (8, 9, "the Lamanites"),
        (10, 12, "their armies"),
        (13, 15, "before"),
        (16, 17, "the gate"),
        (18, 21, "of entering,"),
        (22, 25, "and began to fight"),
        (26, 28, "with the Nephites,"),
        (29, 34, "that they come inside"),
        (35, 39, "their place of"),
        (40, 42, "safe protection;"),
        (43, 44, "but behold,"),
        (45, 48, "they were driven"),
        (49, 52, "to be turned back"),
        (53, 55, "from time"),
        (56, 58, "to time,"),
        (59, 61, "insomuch that"),
        (62, 64, "they were slain"),
        (65, 68, "with a great slaughter."),
    ],
    22: [
        (0, 1, "Now"),
        (2, 5, "when they found"),
        (6, 11, "they could not gain"),
        (12, 13, "power"),
        (14, 16, "over"),
        (17, 18, "the Nephites"),
        (19, 21, "at the place"),
        (22, 25, "of passing through,"),
        (26, 30, "they began to dig"),
        (31, 32, "down"),
        (33, 36, "their banks of earth"),
        (37, 42, "that they might get"),
        (43, 45, "a way"),
        (46, 49, "for their armies,"),
        (50, 55, "that they might have"),
        (56, 58, "an equal chance"),
        (59, 61, "to fight;"),
        (62, 63, "but behold,"),
        (64, 66, "in those attempts,"),
        (67, 72, "they were swept away"),
        (73, 74, "by stones"),
        (75, 76, "and arrows"),
        (77, 78, "which were hurled"),
        (79, 81, "and shot"),
        (82, 85, "at them;"),
        (86, 88, "and instead of"),
        (89, 91, "the filling of"),
        (92, 94, "their ditches"),
        (95, 100, "by the tearing down of"),
        (101, 102, "the banks of earth,"),
        (103, 104, "were filled"),
        (105, 107, "a part of"),
        (108, 109, "those ditches"),
        (110, 114, "with their dead"),
        (115, 117, "and wounded men."),
    ],
    23: [
        (0, 3, "Thus obtained"),
        (4, 6, "the Nephites"),
        (7, 9, "complete power"),
        (10, 12, "over"),
        (13, 15, "their enemies;"),
        (16, 20, "and thus attempted"),
        (21, 23, "the Lamanites"),
        (24, 25, "to destroy"),
        (26, 27, "the Nephites"),
        (28, 30, "until"),
        (31, 33, "all were slain"),
        (34, 37, "their chief captains;"),
        (38, 38, "yea,"),
        (39, 43, "and more than"),
        (44, 45, "a thousand"),
        (46, 47, "Lamanites"),
        (48, 49, "were slain;"),
        (50, 50, "while,"),
        (51, 54, "on the other side,"),
        (55, 58, "there was no man"),
        (59, 60, "even one"),
        (61, 63, "of the Nephites"),
        (64, 65, "who was slain."),
    ],
    24: [
        (0, 2, "There were"),
        (3, 5, "about"),
        (6, 7, "fifty"),
        (8, 11, "who were wounded,"),
        (12, 16, "who were not protected"),
        (17, 19, "from the arrows of"),
        (20, 21, "the Lamanites"),
        (22, 24, "at the place"),
        (25, 28, "of passing,"),
        (29, 29, "but"),
        (30, 33, "they were protected"),
        (34, 36, "by their shields,"),
        (37, 40, "and their breastplates,"),
        (41, 44, "and their head-plates,"),
        (45, 47, "insomuch that"),
        (48, 49, "were wounded"),
        (50, 52, "their legs,"),
        (53, 55, "the many of"),
        (56, 58, "those wounds"),
        (59, 63, "were exceedingly severe."),
    ],
    25: [
        (0, 3, "And it came to pass that"),
        (4, 5, "when saw"),
        (6, 7, "the Lamanites"),
        (8, 10, "were all slain"),
        (11, 14, "their chief captains,"),
        (15, 18, "they fled"),
        (19, 21, "into the wilderness."),
        (22, 25, "And it came to pass that"),
        (26, 29, "they returned"),
        (30, 33, "to the land of"),
        (34, 34, "Nephi,"),
        (35, 37, "to tell"),
        (38, 40, "their king,"),
        (41, 42, "Amalickiah,"),
        (43, 44, "who"),
        (45, 48, "was a Nephite"),
        (49, 52, "in his birth,"),
        (53, 55, "concerning"),
        (56, 59, "their great destruction."),
    ],
    26: [
        (0, 3, "And it came to pass that"),
        (4, 7, "he was greatly angry"),
        (8, 10, "with his people,"),
        (11, 11, "because"),
        (12, 14, "was not fulfilled"),
        (15, 16, "his desire"),
        (17, 19, "against the Nephites;"),
        (20, 26, "he could not subject"),
        (27, 28, "them"),
        (29, 31, "under"),
        (32, 34, "the yoke of"),
        (35, 36, "bondage."),
    ],
    27: [
        (0, 0, "Yea,"),
        (1, 5, "he was greatly angry,"),
        (6, 10, "and he cursed"),
        (11, 12, "God,"),
        (13, 15, "and Moroni also,"),
        (16, 17, "and swore"),
        (18, 20, "with an oath"),
        (21, 25, "he would drink"),
        (26, 27, "his blood;"),
        (28, 31, "and the cause"),
        (32, 34, "of this thing"),
        (35, 37, "was that kept"),
        (38, 39, "Moroni"),
        (40, 41, "the commandments of"),
        (42, 43, "God"),
        (44, 46, "in the preparing"),
        (47, 49, "for the safety"),
        (50, 52, "of his people."),
    ],
    28: [
        (0, 4, "And it came to pass that"),
        (5, 8, "on the one side,"),
        (9, 11, "gave thanks"),
        (12, 14, "the people of"),
        (15, 15, "Nephi"),
        (16, 18, "to the Lord"),
        (19, 21, "their God,"),
        (22, 23, "because of"),
        (24, 27, "his incomparable power"),
        (28, 31, "in the delivering of"),
        (32, 33, "them"),
        (34, 36, "from the hands of"),
        (37, 39, "their enemies."),
    ],
    29: [
        (0, 4, "And thus ended"),
        (5, 11, "the nineteenth"),
        (12, 13, "year"),
        (14, 18, "of the reign of the judges"),
        (19, 22, "over the people of"),
        (23, 23, "Nephi."),
    ],
    30: [
        (0, 0, "Yea,"),
        (1, 4, "and continued"),
        (5, 10, "the being of peace"),
        (11, 13, "among"),
        (14, 15, "them,"),
        (16, 20, "and very great prosperity"),
        (21, 23, "in the church"),
        (24, 25, "because of"),
        (26, 29, "their heeding"),
        (30, 32, "and diligence"),
        (33, 36, "which they gave"),
        (37, 40, "to the word of"),
        (41, 42, "God,"),
        (43, 46, "which was preached"),
        (47, 50, "unto them"),
        (51, 52, "by Helaman,"),
        (53, 54, "and Shiblon,"),
        (55, 56, "and Corianton,"),
        (57, 58, "and Ammon"),
        (59, 61, "and his brethren,"),
        (62, 62, "yea,"),
        (63, 66, "and all of them"),
        (67, 70, "who were ordained"),
        (71, 74, "in the holy order"),
        (75, 77, "of God,"),
        (78, 79, "being baptized"),
        (80, 82, "unto repentance,"),
        (83, 85, "and sent out"),
        (86, 87, "to preach"),
        (88, 90, "among"),
        (91, 92, "the people."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
