"""Hand-curated TAM-phrase gloss overrides for 2 Nifae 30 — Millennial peace / Knowledge fills the earth."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "2nephi"
CHAPTER_NUM = 30
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And now behold,"),
        (4, 7, "O my beloved brethren,"),
        (8, 12, "I would speak"),
        (13, 15, "unto you;"),
        (16, 18, "for I,"),
        (19, 20, "Nephi,"),
        (21, 24, "I would not leave"),
        (25, 25, "you"),
        (26, 28, "that ye think"),
        (29, 31, "are better"),
        (32, 34, "your righteousness"),
        (35, 38, "than the state"),
        (39, 43, "shall be"),
        (44, 44, "of the Gentiles."),
        (45, 46, "For behold,"),
        (47, 48, "save thereto"),
        (49, 53, "ye shall keep"),
        (54, 54, "the commandments"),
        (55, 57, "of the God"),
        (58, 62, "shall thus also"),
        (63, 63, "that"),
        (64, 66, "ye all perish;"),
        (67, 67, "and"),
        (68, 71, "should not"),
        (72, 73, "ye think"),
        (74, 78, "shall be utterly destroyed"),
        (79, 79, "verily"),
        (80, 80, "the Gentiles"),
        (81, 83, "because of words"),
        (84, 85, "are spoken."),
    ],
    2: [
        (0, 1, "For behold,"),
        (2, 5, "I say"),
        (6, 8, "unto you,"),
        (9, 11, "as many"),
        (12, 13, "of the Gentiles"),
        (14, 17, "who shall repent"),
        (18, 20, "they are"),
        (21, 22, "the people"),
        (23, 25, "of the covenant"),
        (26, 28, "of the Lord;"),
        (29, 29, "and"),
        (30, 32, "as many"),
        (33, 35, "of the Jews"),
        (36, 38, "who will not repent"),
        (39, 43, "shall be cast away"),
        (44, 45, "out;"),
        (46, 46, "for"),
        (47, 49, "doth not covenant"),
        (50, 51, "the Lord"),
        (52, 54, "with any one"),
        (55, 56, "save thereto"),
        (57, 59, "with those"),
        (60, 63, "who repent"),
        (64, 65, "and believe"),
        (66, 68, "in his Son,"),
        (69, 70, "the one who"),
        (71, 75, "is the Holy One"),
        (76, 77, "of Israel."),
    ],
    3: [
        (0, 2, "And now,"),
        (3, 5, "must"),
        (6, 8, "I prophesy"),
        (9, 9, "verily"),
        (10, 12, "concerning"),
        (13, 14, "the Jews"),
        (15, 16, "and Gentiles."),
        (17, 17, "For"),
        (18, 23, "after cometh"),
        (24, 26, "the book"),
        (27, 31, "I have spoken thereto,"),
        (32, 34, "and written"),
        (35, 36, "to the Gentiles,"),
        (37, 40, "and sealed up again"),
        (41, 43, "to the Lord,"),
        (44, 47, "many"),
        (48, 51, "shall believe"),
        (52, 53, "in the words"),
        (54, 55, "which are written;"),
        (56, 56, "and"),
        (57, 62, "they shall give"),
        (63, 64, "these words"),
        (65, 67, "to the remnant"),
        (68, 69, "of the remainder"),
        (70, 73, "of our seed."),
    ],
    4: [
        (0, 0, "And"),
        (1, 4, "then shall know"),
        (5, 7, "by the remnant"),
        (8, 9, "of the remainder"),
        (10, 13, "of our seed"),
        (14, 15, "concerning"),
        (16, 19, "us,"),
        (20, 21, "the way"),
        (22, 26, "we came out thereto"),
        (27, 28, "from Jerusalem,"),
        (29, 29, "and"),
        (30, 32, "they"),
        (33, 35, "descended"),
        (36, 38, "from the Jews."),
    ],
    5: [
        (0, 0, "And"),
        (1, 4, "shall be declared"),
        (5, 6, "in the midst"),
        (7, 9, "of them"),
        (10, 11, "the gospel"),
        (12, 14, "of Jesus Christ;"),
        (15, 18, "wherefore,"),
        (19, 22, "shall be restored"),
        (23, 24, "they"),
        (25, 27, "to the knowledge"),
        (28, 30, "concerning"),
        (31, 33, "their fathers,"),
        (34, 34, "and"),
        (35, 38, "to the knowledge also"),
        (39, 43, "concerning Jesus Christ,"),
        (44, 46, "which was"),
        (47, 48, "in the midst"),
        (49, 52, "of their fathers."),
    ],
    6: [
        (0, 0, "And"),
        (1, 5, "then shall they rejoice thereto;"),
        (6, 6, "for"),
        (7, 11, "they shall know"),
        (12, 15, "is a blessing this"),
        (16, 18, "for them"),
        (19, 21, "from the hand"),
        (22, 24, "of the God;"),
        (25, 25, "and"),
        (26, 30, "shall begin to"),
        (31, 33, "fall off the scales"),
        (34, 36, "of the darkness"),
        (37, 40, "from their eyes;"),
        (41, 41, "and"),
        (42, 45, "shall not pass"),
        (46, 49, "many generations"),
        (50, 51, "from the midst"),
        (52, 55, "of them,"),
        (56, 56, "before"),
        (57, 60, "shall become"),
        (61, 62, "they"),
        (63, 66, "a pure people"),
        (67, 68, "and delightsome."),
    ],
    7: [
        (0, 0, "And"),
        (1, 5, "shall come to pass"),
        (6, 6, "also"),
        (7, 9, "the Jews"),
        (10, 13, "who are scattered,"),
        (14, 18, "shall also begin"),
        (19, 19, "to"),
        (20, 22, "believe in Christ;"),
        (23, 23, "and"),
        (24, 28, "shall begin to"),
        (29, 32, "they gather together"),
        (33, 37, "upon the land;"),
        (38, 38, "and"),
        (39, 41, "as many"),
        (42, 44, "of them"),
        (45, 48, "who believe in Christ,"),
        (49, 53, "shall become also"),
        (54, 57, "a delightsome people."),
    ],
    8: [
        (0, 0, "And"),
        (1, 5, "shall come to pass"),
        (6, 6, "also"),
        (7, 10, "shall begin"),
        (11, 11, "by"),
        (12, 13, "the Lord"),
        (14, 15, "the God"),
        (16, 17, "his work"),
        (18, 19, "in the midst"),
        (20, 22, "of all nations,"),
        (23, 23, "kindreds,"),
        (24, 24, "tongues,"),
        (25, 26, "and peoples,"),
        (27, 29, "to bring to pass thereto"),
        (30, 31, "the restoration"),
        (32, 34, "of his people"),
        (35, 36, "upon"),
        (37, 39, "the world."),
    ],
    9: [
        (0, 0, "And"),
        (1, 4, "shall judge"),
        (5, 5, "by"),
        (6, 7, "the Lord"),
        (8, 9, "the God"),
        (10, 12, "with righteousness"),
        (13, 14, "the poor,"),
        (15, 17, "and reprove"),
        (18, 20, "with equity"),
        (21, 23, "for the meek"),
        (24, 26, "of the world."),
        (27, 27, "And"),
        (28, 31, "shall smite"),
        (32, 33, "by him"),
        (34, 35, "the world"),
        (36, 38, "with the rod"),
        (39, 41, "of his mouth;"),
        (42, 42, "and"),
        (43, 46, "with the breath"),
        (47, 49, "of his lips"),
        (50, 54, "shall slay thereto"),
        (55, 56, "the wicked."),
    ],
    10: [
        (0, 0, "For"),
        (1, 5, "speedily cometh"),
        (6, 8, "the time"),
        (9, 13, "shall do thereto"),
        (14, 14, "by"),
        (15, 16, "the Lord"),
        (17, 18, "the God"),
        (19, 21, "a great separation"),
        (22, 23, "in the midst"),
        (24, 25, "of the people,"),
        (26, 26, "and"),
        (27, 30, "shall be destroyed"),
        (31, 32, "by him"),
        (33, 34, "the wicked;"),
        (35, 35, "and"),
        (36, 39, "shall be spared"),
        (40, 41, "by him"),
        (42, 43, "his people,"),
        (44, 44, "yea,"),
        (45, 49, "even though"),
        (50, 51, "necessary thereto"),
        (52, 54, "must"),
        (55, 55, "destroy"),
        (56, 57, "by him"),
        (58, 59, "the wicked"),
        (60, 62, "by fire."),
    ],
    11: [
        (0, 0, "And"),
        (1, 4, "shall become"),
        (5, 6, "righteousness"),
        (7, 8, "as the girdle"),
        (9, 11, "of his loins,"),
        (12, 12, "and"),
        (13, 14, "the faithfulness"),
        (15, 16, "as the girdle"),
        (17, 19, "of his reins."),
    ],
    12: [
        (0, 0, "And"),
        (1, 5, "shall dwell together thereto"),
        (6, 8, "the wolf"),
        (9, 12, "with the lamb;"),
        (13, 13, "and"),
        (14, 18, "shall lie down together"),
        (19, 20, "the leopard"),
        (21, 24, "with the kid,"),
        (25, 25, "and"),
        (26, 29, "the calf,"),
        (30, 33, "and the young lion,"),
        (34, 37, "and the fatling,"),
        (38, 42, "shall lie down together;"),
        (43, 43, "and"),
        (44, 47, "shall lead"),
        (48, 49, "them"),
        (50, 52, "a little child."),
    ],
    13: [
        (0, 0, "And"),
        (1, 5, "shall feed together"),
        (6, 7, "the cow"),
        (8, 10, "with the bear;"),
        (11, 15, "shall lie down together"),
        (16, 18, "their young;"),
        (19, 19, "and"),
        (20, 23, "shall eat"),
        (24, 26, "by the lion"),
        (27, 29, "straw"),
        (30, 34, "like the ox."),
    ],
    14: [
        (0, 0, "And"),
        (1, 4, "shall play"),
        (5, 6, "the child"),
        (7, 9, "not yet weaned"),
        (10, 12, "with the milk"),
        (13, 15, "on the hole"),
        (16, 18, "of the asp,"),
        (19, 19, "and"),
        (20, 23, "shall put"),
        (24, 26, "by the child"),
        (27, 28, "weaned"),
        (29, 31, "from the milk"),
        (32, 33, "his hand"),
        (34, 36, "on the den"),
        (37, 40, "of the cockatrice."),
    ],
    15: [
        (0, 5, "they shall not hurt"),
        (6, 7, "nor destroy"),
        (8, 10, "in anything"),
        (11, 15, "in all my holy mountain;"),
        (16, 16, "for"),
        (17, 20, "shall be full"),
        (21, 22, "the world"),
        (23, 25, "with the knowledge"),
        (26, 28, "of the Lord"),
        (29, 31, "as"),
        (32, 32, "cover"),
        (33, 34, "the sea"),
        (35, 36, "with waters."),
    ],
    16: [
        (0, 3, "Wherefore,"),
        (4, 8, "shall be made known"),
        (9, 9, "things"),
        (10, 12, "of all nations;"),
        (13, 13, "yea,"),
        (14, 18, "shall be made known"),
        (19, 20, "all things"),
        (21, 23, "unto the children"),
        (24, 25, "of men."),
    ],
    17: [
        (0, 4, "There is no secret"),
        (5, 9, "shall not be revealed;"),
        (10, 13, "there is no work"),
        (14, 16, "of darkness"),
        (17, 21, "shall not be revealed"),
        (22, 24, "in the light;"),
        (25, 25, "and"),
        (26, 29, "there is no thing"),
        (30, 31, "sealed up"),
        (32, 33, "upon"),
        (34, 36, "of the world"),
        (37, 41, "shall not be loosed."),
    ],
    18: [
        (0, 3, "Wherefore,"),
        (4, 6, "all things"),
        (7, 9, "have been revealed"),
        (10, 12, "unto the children"),
        (13, 14, "of men"),
        (15, 19, "shall be revealed"),
        (20, 22, "in that day;"),
        (23, 23, "and"),
        (24, 28, "shall no more"),
        (29, 30, "be"),
        (31, 32, "any power"),
        (33, 34, "of Satan"),
        (35, 36, "upon"),
        (37, 38, "the hearts"),
        (39, 41, "of the children"),
        (42, 43, "of men,"),
        (44, 48, "for a long time."),
        (49, 51, "And now,"),
        (52, 55, "O my beloved brethren,"),
        (56, 58, "I have ended"),
        (59, 60, "my words."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
