"""Hand-curated TAM-phrase gloss overrides for 2 Nifae 33 — Nephi's final testimony."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "2nephi"
CHAPTER_NUM = 33
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now,"),
        (3, 6, "I, Nephi,"),
        (7, 10, "cannot"),
        (11, 12, "I write"),
        (13, 14, "all the things"),
        (15, 16, "were taught"),
        (17, 18, "in the midst"),
        (19, 21, "of my people;"),
        (22, 24, "neither am I"),
        (25, 27, "mighty also"),
        (28, 30, "at writing,"),
        (31, 33, "like as"),
        (34, 35, "the speaking;"),
        (36, 36, "for"),
        (37, 39, "when speaks"),
        (40, 41, "a man"),
        (42, 44, "by way of"),
        (45, 46, "the power"),
        (47, 50, "of the Holy Spirit,"),
        (51, 52, "carrieth"),
        (53, 55, "by the power"),
        (56, 59, "of the Holy Spirit"),
        (60, 61, "to the hearts"),
        (62, 64, "of the children"),
        (65, 66, "of men."),
    ],
    2: [
        (0, 1, "But behold,"),
        (2, 3, "many"),
        (4, 6, "who have hardened"),
        (7, 9, "their hearts"),
        (10, 12, "against"),
        (13, 15, "the Holy Spirit,"),
        (16, 20, "hath no place thereto"),
        (21, 22, "in the midst"),
        (23, 25, "of them;"),
        (26, 29, "wherefore,"),
        (30, 34, "they cast away thereto"),
        (35, 36, "the many"),
        (37, 38, "of things"),
        (39, 40, "are written,"),
        (41, 44, "and esteem thereto"),
        (45, 47, "as things of naught."),
    ],
    3: [
        (0, 0, "But"),
        (1, 4, "I, Nephi,"),
        (5, 7, "have written"),
        (8, 8, "things"),
        (9, 11, "I have written,"),
        (12, 12, "and"),
        (13, 17, "I esteem thereto"),
        (18, 23, "as things of great worth,"),
        (24, 25, "and especially"),
        (26, 28, "to my people."),
        (29, 29, "For"),
        (30, 32, "I pray"),
        (33, 35, "without ceasing"),
        (36, 38, "for them"),
        (39, 41, "by day,"),
        (42, 43, "and wet"),
        (44, 45, "my pillow"),
        (46, 48, "with my tears"),
        (49, 51, "by night,"),
        (52, 55, "for them;"),
        (56, 56, "and"),
        (57, 60, "I cry"),
        (61, 63, "unto my God"),
        (64, 66, "in faith,"),
        (67, 67, "and"),
        (68, 70, "I know"),
        (71, 75, "shall hear"),
        (76, 77, "he"),
        (78, 80, "my cry."),
    ],
    4: [
        (0, 0, "And"),
        (1, 3, "I know"),
        (4, 7, "shall consecrate"),
        (8, 8, "by"),
        (9, 10, "the Lord"),
        (11, 12, "the God"),
        (13, 14, "my prayers"),
        (15, 17, "for the welfare"),
        (18, 20, "of my people."),
        (21, 21, "And"),
        (22, 23, "the words"),
        (24, 26, "I have written"),
        (27, 29, "in weakness,"),
        (30, 33, "shall be made"),
        (34, 35, "strong"),
        (36, 39, "unto them;"),
        (40, 40, "for"),
        (41, 43, "persuadeth"),
        (44, 47, "them"),
        (48, 50, "that they do"),
        (51, 52, "good;"),
        (53, 56, "maketh known thereto"),
        (57, 60, "unto them"),
        (61, 63, "concerning"),
        (64, 66, "their fathers;"),
        (67, 67, "and"),
        (68, 70, "speaketh"),
        (71, 74, "concerning Jesus,"),
        (75, 77, "and persuadeth"),
        (78, 81, "them"),
        (82, 83, "to believe"),
        (84, 86, "in him,"),
        (87, 88, "and endure"),
        (89, 91, "unto"),
        (92, 93, "the end,"),
        (94, 97, "which is the life"),
        (98, 99, "eternal."),
    ],
    5: [
        (0, 0, "And"),
        (1, 4, "speaketh harshly"),
        (5, 7, "against"),
        (8, 9, "sin,"),
        (10, 12, "according to"),
        (13, 14, "the plainness"),
        (15, 17, "of the truth;"),
        (18, 21, "wherefore,"),
        (22, 25, "there is no man"),
        (26, 27, "angry"),
        (28, 29, "at the words"),
        (30, 32, "I have written"),
        (33, 34, "save thereto"),
        (35, 38, "is in him"),
        (39, 40, "the spirit"),
        (41, 43, "of the devil."),
    ],
    6: [
        (0, 2, "I rejoice"),
        (3, 5, "in plainness;"),
        (6, 8, "I rejoice"),
        (9, 11, "in truth;"),
        (12, 14, "I rejoice"),
        (15, 17, "in my Jesus,"),
        (18, 18, "for"),
        (19, 22, "hath redeemed"),
        (23, 24, "my soul"),
        (25, 26, "from hell."),
    ],
    7: [
        (0, 3, "I have"),
        (4, 6, "charity"),
        (7, 9, "for my people,"),
        (10, 13, "and great faith"),
        (14, 15, "in Christ"),
        (16, 20, "that I shall meet"),
        (21, 22, "with souls"),
        (23, 24, "many"),
        (25, 28, "and spotless"),
        (29, 31, "at his judgment-seat."),
    ],
    8: [
        (0, 3, "I have"),
        (4, 6, "charity"),
        (7, 9, "for the Jews—"),
        (10, 12, "I have called"),
        (13, 14, "the Jews,"),
        (15, 17, "because concerneth"),
        (18, 21, "to them"),
        (22, 26, "I descended from."),
    ],
    9: [
        (0, 4, "I have also"),
        (5, 7, "charity"),
        (8, 9, "for the Gentiles."),
        (10, 11, "But behold,"),
        (12, 15, "cannot"),
        (16, 17, "I hope"),
        (18, 20, "for any"),
        (21, 23, "of them"),
        (24, 25, "save thereto"),
        (26, 28, "they shall be reconciled"),
        (29, 30, "with Christ,"),
        (31, 33, "and enter"),
        (34, 37, "into the strait gate,"),
        (38, 39, "and walk"),
        (40, 43, "in the straight way"),
        (44, 46, "which leadeth"),
        (47, 49, "to life,"),
        (50, 51, "and continue"),
        (52, 54, "in the path"),
        (55, 56, "until"),
        (57, 59, "to the end"),
        (60, 62, "of the day"),
        (63, 67, "of probation."),
    ],
    10: [
        (0, 2, "And now,"),
        (3, 6, "O my beloved brethren,"),
        (7, 10, "and Jews also,"),
        (11, 14, "and all ye ends"),
        (15, 17, "of the world,"),
        (18, 20, "hearken ye"),
        (21, 23, "to these words"),
        (24, 25, "and believe"),
        (26, 27, "in Christ;"),
        (28, 29, "and if"),
        (30, 33, "ye believe not"),
        (34, 36, "in these words"),
        (37, 39, "believe ye"),
        (40, 41, "in Christ."),
        (42, 43, "And if"),
        (44, 46, "ye believe"),
        (47, 48, "in Christ"),
        (49, 53, "ye shall believe"),
        (54, 56, "in these words,"),
        (57, 57, "for"),
        (58, 59, "the words"),
        (60, 61, "are"),
        (62, 63, "of Christ,"),
        (64, 64, "and"),
        (65, 69, "were given them"),
        (70, 71, "by him"),
        (72, 74, "unto me;"),
        (75, 75, "and"),
        (76, 79, "they teach"),
        (80, 82, "all men"),
        (83, 85, "that they do"),
        (86, 87, "good."),
    ],
    11: [
        (0, 0, "If"),
        (1, 5, "are not the words"),
        (6, 7, "they"),
        (8, 9, "of Christ,"),
        (10, 11, "judge ye—"),
        (12, 12, "for"),
        (13, 17, "shall show"),
        (18, 19, "by Christ"),
        (20, 22, "unto you,"),
        (23, 25, "with power"),
        (26, 29, "and great glory,"),
        (30, 33, "at the last day,"),
        (34, 36, "they"),
        (37, 39, "are his words;"),
        (40, 40, "and"),
        (41, 44, "thou and I"),
        (45, 48, "we shall"),
        (49, 50, "stand face to face"),
        (51, 52, "before"),
        (53, 56, "his judgment bar;"),
        (57, 57, "and"),
        (58, 62, "ye shall know"),
        (63, 65, "was commanded I"),
        (66, 67, "by him"),
        (68, 69, "to write"),
        (70, 71, "these things,"),
        (72, 76, "notwithstanding my weakness."),
    ],
    12: [
        (0, 0, "And"),
        (1, 3, "I pray"),
        (4, 6, "to the Father"),
        (7, 9, "in the name"),
        (10, 11, "of Christ,"),
        (12, 13, "may be saved"),
        (14, 15, "many"),
        (16, 18, "of us,"),
        (19, 20, "if"),
        (21, 25, "not all of us,"),
        (26, 28, "in his kingdom,"),
        (29, 32, "at that great day"),
        (33, 35, "and last."),
    ],
    13: [
        (0, 2, "And now,"),
        (3, 6, "O my beloved brethren,"),
        (7, 8, "all ye"),
        (9, 11, "those"),
        (12, 14, "of the house"),
        (15, 16, "of Israel,"),
        (17, 20, "and all ye ends"),
        (21, 23, "of the world,"),
        (24, 27, "I speak"),
        (28, 30, "unto you"),
        (31, 35, "as the voice"),
        (36, 38, "of one"),
        (39, 41, "crying"),
        (42, 43, "from the dust:"),
        (44, 45, "Farewell"),
        (46, 50, "until cometh"),
        (51, 53, "that great day."),
    ],
    14: [
        (0, 0, "And"),
        (1, 4, "ye those who"),
        (5, 7, "will not partake"),
        (8, 10, "of the goodness"),
        (11, 13, "of the God,"),
        (14, 15, "and respect"),
        (16, 17, "to the words"),
        (18, 20, "of the Jews,"),
        (21, 22, "also likewise"),
        (23, 25, "to my words,"),
        (26, 27, "and the words"),
        (28, 32, "shall come from"),
        (33, 34, "the mouth"),
        (35, 38, "of the Lamb"),
        (39, 41, "of the God,"),
        (42, 42, "behold,"),
        (43, 46, "I bid farewell forever"),
        (47, 49, "everlasting"),
        (50, 52, "unto you,"),
        (53, 53, "for"),
        (54, 56, "these words"),
        (57, 61, "shall condemn thereto"),
        (62, 62, "you"),
        (63, 66, "at the last day."),
    ],
    15: [
        (0, 0, "For"),
        (1, 2, "the things"),
        (3, 5, "I seal"),
        (6, 8, "on earth,"),
        (9, 13, "shall be brought"),
        (14, 15, "against"),
        (16, 18, "you"),
        (19, 22, "at the judgment bar;"),
        (23, 23, "for"),
        (24, 28, "thus hath commanded thereto"),
        (29, 30, "me"),
        (31, 33, "by the Lord,"),
        (34, 34, "and"),
        (35, 37, "must"),
        (38, 39, "I obey."),
        (40, 40, "Amen."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
