"""Hand-curated TAM-phrase gloss overrides for Upu a Mamona 1 — Mormon abridges the small plates; King Benjamin unifies the people."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "wom"
CHAPTER_NUM = 1
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now,"),
        (3, 6, "I, Mormon,"),
        (7, 9, "being about"),
        (10, 12, "to deliver up"),
        (13, 14, "the record"),
        (15, 17, "which I have made"),
        (18, 19, "into the hands"),
        (20, 24, "of my son Moroni,"),
        (25, 25, "behold,"),
        (26, 28, "I have witnessed"),
        (29, 33, "the almost entire destruction"),
        (34, 36, "of my people,"),
        (37, 39, "the Nephites."),
    ],
    2: [
        (0, 0, "And"),
        (1, 3, "many"),
        (4, 7, "hundreds of years"),
        (8, 10, "after"),
        (11, 15, "the coming of Christ"),
        (16, 20, "I do deliver thereto"),
        (21, 22, "these records"),
        (23, 24, "into the hands"),
        (25, 27, "of my son;"),
        (28, 28, "and"),
        (29, 31, "I suppose"),
        (32, 37, "that will witness by him"),
        (38, 40, "the entire destruction"),
        (41, 43, "of my people."),
        (44, 44, "But"),
        (45, 49, "may God grant"),
        (50, 53, "that he may be spared"),
        (54, 58, "from them,"),
        (59, 62, "that he may"),
        (63, 66, "write myself"),
        (67, 72, "concerning them,"),
        (73, 73, "and"),
        (74, 78, "concerning Christ myself,"),
        (79, 79, "for"),
        (80, 82, "perhaps might profit"),
        (83, 86, "unto them"),
        (87, 89, "in a day."),
    ],
    3: [
        (0, 2, "And now,"),
        (3, 8, "I speak myself"),
        (9, 11, "concerning"),
        (12, 14, "the things I have written;"),
        (15, 15, "for"),
        (16, 21, "after I had made"),
        (22, 24, "an abridgment"),
        (25, 28, "from the plates of Nephi,"),
        (29, 33, "down to"),
        (34, 36, "into the reign"),
        (37, 41, "of this King Benjamin,"),
        (42, 43, "of whom"),
        (44, 48, "spake Amaleki,"),
        (49, 51, "I searched"),
        (52, 52, "the records"),
        (53, 55, "which had been delivered"),
        (56, 58, "into my hands,"),
        (59, 59, "and"),
        (60, 62, "I found thereto"),
        (63, 64, "these plates,"),
        (65, 68, "which contain"),
        (69, 71, "a small account"),
        (72, 75, "concerning prophets,"),
        (76, 78, "from Jacob"),
        (79, 83, "down to"),
        (84, 86, "into the reign"),
        (87, 91, "of this King Benjamin,"),
        (92, 92, "and"),
        (93, 96, "also many"),
        (97, 99, "of the words of Nephi."),
    ],
    4: [
        (0, 0, "And"),
        (1, 4, "the things which are written"),
        (5, 7, "upon these plates"),
        (8, 12, "please me thereto,"),
        (13, 13, "because"),
        (14, 18, "of the prophecies"),
        (19, 25, "of the coming of Christ;"),
        (26, 26, "and"),
        (27, 29, "the knowing"),
        (30, 32, "of my fathers"),
        (33, 39, "have been fulfilled many of them;"),
        (40, 40, "yea,"),
        (41, 45, "and I have known also"),
        (46, 52, "that many of things prophesied"),
        (53, 58, "concerning us"),
        (59, 66, "down to this day,"),
        (67, 70, "have been fulfilled,"),
        (71, 71, "and"),
        (72, 74, "many"),
        (75, 78, "beyond"),
        (79, 82, "of this day,"),
        (83, 87, "shall surely be fulfilled—"),
    ],
    5: [
        (0, 3, "Wherefore,"),
        (4, 7, "I have chosen thereto"),
        (8, 9, "these things"),
        (10, 12, "to finish thereto"),
        (13, 16, "upon them"),
        (17, 18, "my record,"),
        (19, 22, "the remainder"),
        (23, 26, "of my record"),
        (27, 32, "I shall take"),
        (33, 35, "from the plates of Nephi;"),
        (36, 36, "and"),
        (37, 40, "cannot"),
        (41, 42, "I write"),
        (43, 44, "the hundredth part"),
        (45, 46, "of things"),
        (47, 49, "of my people."),
    ],
    6: [
        (0, 1, "But behold,"),
        (2, 7, "I shall take"),
        (8, 8, "these plates,"),
        (9, 15, "which contain these prophesyings and revelations,"),
        (16, 16, "and"),
        (17, 17, "put them together"),
        (18, 25, "with the remainder of my record,"),
        (26, 26, "for"),
        (27, 32, "they are choice unto them"),
        (33, 35, "unto me;"),
        (36, 36, "and"),
        (37, 39, "I know"),
        (40, 42, "shall be"),
        (43, 46, "also choice"),
        (47, 49, "unto my brethren."),
    ],
    7: [
        (0, 0, "And"),
        (1, 3, "I have done"),
        (4, 5, "this thing"),
        (6, 9, "for a wise purpose;"),
        (10, 15, "for thus have been inspired thereto"),
        (16, 17, "me,"),
        (18, 20, "according to"),
        (21, 21, "the workings"),
        (22, 27, "of the Spirit of the Lord"),
        (28, 33, "which is in me."),
        (34, 36, "And now,"),
        (37, 41, "I know not all things;"),
        (42, 42, "but"),
        (43, 48, "the Lord knoweth"),
        (49, 53, "all things which are to come;"),
        (54, 57, "wherefore,"),
        (58, 60, "he worketh thereto"),
        (61, 62, "he"),
        (63, 65, "in me"),
        (66, 68, "to do"),
        (69, 74, "according to his will."),
    ],
    8: [
        (0, 0, "And"),
        (1, 3, "my prayer"),
        (4, 6, "unto the God"),
        (7, 11, "is concerning my brethren,"),
        (12, 14, "that may"),
        (15, 18, "they again come"),
        (19, 24, "to the knowledge of God,"),
        (25, 25, "yea,"),
        (26, 29, "the redemption of Christ;"),
        (30, 33, "that they may"),
        (34, 37, "again become they"),
        (38, 40, "a delightsome people."),
    ],
    9: [
        (0, 2, "And now,"),
        (3, 6, "I, Mormon,"),
        (7, 12, "proceed to finish my record,"),
        (13, 20, "which I take from the plates of Nephi;"),
        (21, 21, "and"),
        (22, 24, "I do it"),
        (25, 28, "according to"),
        (29, 33, "the knowledge and understanding"),
        (34, 39, "which God hath given"),
        (40, 42, "unto me."),
    ],
    10: [
        (0, 3, "Wherefore,"),
        (4, 6, "it came to pass"),
        (7, 9, "after"),
        (10, 13, "delivered Amaleki"),
        (14, 15, "these plates"),
        (16, 22, "into the hands of King Benjamin,"),
        (23, 26, "took he"),
        (27, 28, "them"),
        (29, 29, "and"),
        (30, 30, "put together"),
        (31, 33, "with the other plates,"),
        (34, 37, "which contained"),
        (38, 38, "records"),
        (39, 44, "handed down by the kings,"),
        (45, 50, "from generation to generation,"),
        (51, 53, "until"),
        (54, 60, "in the days of King Benjamin."),
    ],
    11: [
        (0, 0, "And"),
        (1, 4, "they were handed down"),
        (5, 6, "them"),
        (7, 11, "from King Benjamin,"),
        (12, 17, "from generation to generation"),
        (18, 20, "until"),
        (21, 24, "they came"),
        (25, 27, "into my hands."),
        (28, 28, "And"),
        (29, 32, "I, Mormon,"),
        (33, 38, "pray to the God"),
        (39, 41, "that may"),
        (42, 44, "be preserved them"),
        (45, 48, "from this time"),
        (49, 53, "henceforward."),
        (54, 54, "And"),
        (55, 57, "I know"),
        (58, 63, "shall be preserved them;"),
        (64, 64, "for"),
        (65, 69, "there are great things"),
        (70, 76, "which are written upon them,"),
        (77, 83, "out of which shall be judged"),
        (84, 87, "my people and their brethren"),
        (88, 94, "at the great and last day,"),
        (95, 102, "according to the word of God"),
        (103, 104, "which is written."),
    ],
    12: [
        (0, 2, "And now,"),
        (3, 9, "concerning this King Benjamin—"),
        (10, 13, "he had"),
        (14, 16, "unto him"),
        (17, 18, "some contentions"),
        (19, 20, "among"),
        (21, 24, "his own people."),
    ],
    13: [
        (0, 0, "And"),
        (1, 5, "it came to pass also"),
        (6, 10, "came down the armies of the Lamanites"),
        (11, 15, "out of the land of Nephi,"),
        (16, 22, "to battle against his people."),
        (23, 24, "But behold,"),
        (25, 34, "gathered King Benjamin his armies,"),
        (35, 35, "and"),
        (36, 38, "stood he"),
        (39, 45, "against them;"),
        (46, 46, "and"),
        (47, 50, "did fight he"),
        (51, 57, "in the strength of his own arm,"),
        (58, 62, "with the sword of Laban."),
    ],
    14: [
        (0, 0, "And"),
        (1, 6, "in the strength of the Lord"),
        (7, 12, "they did contend thereto"),
        (13, 16, "against their enemies,"),
        (17, 19, "until"),
        (20, 28, "they had slain many thousands of the Lamanites."),
        (29, 29, "And"),
        (30, 32, "it came to pass"),
        (33, 39, "they did contend against the Lamanites"),
        (40, 42, "until"),
        (43, 47, "they had driven them"),
        (48, 54, "out of all the lands of their inheritance."),
    ],
    15: [
        (0, 0, "And"),
        (1, 3, "it came to pass"),
        (4, 11, "after there had been false Christs,"),
        (12, 12, "and"),
        (13, 18, "their mouths were shut,"),
        (19, 19, "and"),
        (20, 23, "they were punished"),
        (24, 28, "according to their crimes;"),
    ],
    16: [
        (0, 0, "And"),
        (1, 6, "after there had been also"),
        (7, 11, "false prophets,"),
        (12, 14, "and false preachers"),
        (15, 17, "and false teachers"),
        (18, 22, "among the people,"),
        (23, 23, "and"),
        (24, 28, "were punished all these"),
        (29, 35, "according to their crimes;"),
        (36, 36, "and"),
        (37, 40, "after there had been"),
        (41, 43, "much contention"),
        (44, 44, "and"),
        (45, 47, "dissensions away"),
        (48, 50, "unto the Lamanites,"),
        (51, 55, "many of dissenters,"),
        (56, 56, "behold,"),
        (57, 59, "it came to pass"),
        (60, 66, "again did establish King Benjamin,"),
        (67, 71, "with the assistance"),
        (72, 78, "of the holy prophets who were"),
        (79, 83, "in his people—"),
    ],
    17: [
        (0, 1, "For behold,"),
        (2, 6, "King Benjamin,"),
        (7, 10, "was a holy man,"),
        (11, 11, "and"),
        (12, 15, "did reign he"),
        (16, 21, "over his people in righteousness;"),
        (22, 22, "and"),
        (23, 26, "there were many holy men"),
        (27, 32, "in the land,"),
        (33, 33, "and"),
        (34, 37, "they did speak"),
        (38, 42, "the word of God"),
        (43, 48, "with power and with authority;"),
        (49, 49, "and"),
        (50, 56, "they used much sharpness"),
        (57, 61, "because of stiffness"),
        (62, 63, "of the people—"),
    ],
    18: [
        (0, 3, "Wherefore,"),
        (4, 8, "with the aid"),
        (9, 11, "of these,"),
        (12, 14, "it came to pass"),
        (15, 21, "did establish again King Benjamin,"),
        (22, 24, "by laboring"),
        (25, 31, "with all the might of his body"),
        (32, 32, "and"),
        (33, 38, "the entire mind of his soul,"),
        (39, 42, "and also the prophets,"),
        (43, 44, "the peace"),
        (45, 47, "in the land."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
