"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 36 — Alma's charge
to his son Helaman: his own account of his conversion, the anguish of his
soul under the memory of his sins, his crying unto Jesus Christ, and the
joy of his deliverance; a testimony that God delivers those who trust in him.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-split done up front against bom_books.json:
  v11 `upu—Afai` -> 85 tokens

    python3 build_overrides_alma36.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 36

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "My son,"),
        (3, 7, "give ear"),
        (8, 10, "to my words;"),
        (11, 11, "for"),
        (12, 15, "I swear"),
        (16, 18, "unto you,"),
        (19, 20, "that"),
        (21, 24, "inasmuch as"),
        (25, 28, "ye shall keep the commandments"),
        (29, 31, "of God,"),
        (32, 36, "ye shall prosper"),
        (37, 39, "in the land."),
    ],
    2: [
        (0, 2, "I would"),
        (3, 6, "that ye should do"),
        (7, 11, "as I have done,"),
        (12, 14, "in remembering"),
        (15, 17, "the captivity"),
        (18, 21, "of our fathers;"),
        (22, 22, "for"),
        (23, 27, "they were"),
        (28, 30, "in bondage,"),
        (31, 35, "and none"),
        (36, 39, "could deliver"),
        (40, 41, "them"),
        (42, 43, "except"),
        (44, 47, "the God of Abraham,"),
        (48, 52, "and the God of Isaac,"),
        (53, 57, "and the God of Jacob;"),
        (58, 62, "and he surely did deliver"),
        (63, 64, "them"),
        (65, 68, "in their afflictions."),
    ],
    3: [
        (0, 2, "And now,"),
        (3, 5, "O my son"),
        (6, 6, "Helaman,"),
        (7, 7, "behold,"),
        (8, 11, "thou art"),
        (12, 14, "in thy youth,"),
        (15, 17, "and therefore,"),
        (18, 22, "I beseech"),
        (23, 25, "of thee,"),
        (26, 29, "that thou wilt hear"),
        (30, 32, "my words"),
        (33, 35, "and learn"),
        (36, 38, "of me;"),
        (39, 39, "for"),
        (40, 42, "I do know"),
        (43, 48, "that whosoever shall put"),
        (49, 51, "their trust"),
        (52, 54, "in God"),
        (55, 58, "shall be supported"),
        (59, 62, "in their trials,"),
        (63, 66, "and their troubles,"),
        (67, 70, "and their afflictions,"),
        (71, 76, "and shall be lifted up"),
        (77, 78, "they"),
        (79, 82, "at the last day."),
    ],
    4: [
        (0, 4, "And I would not"),
        (5, 7, "that ye think"),
        (8, 10, "that I know"),
        (11, 14, "of myself—"),
        (15, 20, "not of the temporal"),
        (21, 25, "but of the spiritual,"),
        (26, 31, "not of the carnal mind"),
        (32, 36, "but of God."),
    ],
    5: [
        (0, 1, "Now,"),
        (2, 2, "behold,"),
        (3, 6, "I say"),
        (7, 9, "unto you,"),
        (10, 14, "if I had not been born"),
        (15, 18, "of God,"),
        (19, 23, "I should not have known"),
        (24, 25, "these things;"),
        (26, 29, "but God"),
        (30, 33, "hath made known"),
        (34, 36, "unto me"),
        (37, 38, "these things,"),
        (39, 43, "by the mouth"),
        (44, 47, "of his holy angel,"),
        (48, 50, "not of"),
        (51, 53, "any worthiness of myself;"),
    ],
    6: [
        (0, 0, "For"),
        (1, 4, "I went about"),
        (5, 6, "with"),
        (7, 9, "the sons of Mosiah,"),
        (10, 11, "seeking"),
        (12, 13, "to destroy"),
        (14, 18, "the church of God;"),
        (19, 20, "but behold,"),
        (21, 26, "God sent"),
        (27, 29, "his holy angel"),
        (30, 33, "to stop us"),
        (34, 36, "by the way."),
    ],
    7: [
        (0, 1, "And behold,"),
        (2, 6, "he spake"),
        (7, 10, "unto us,"),
        (11, 12, "as it were"),
        (13, 16, "the voice of"),
        (17, 18, "thunder,"),
        (19, 22, "and did tremble"),
        (23, 25, "the whole earth"),
        (26, 29, "beneath"),
        (30, 32, "our feet;"),
        (33, 38, "and we all fell"),
        (39, 41, "to the earth,"),
        (42, 42, "for"),
        (43, 45, "came"),
        (46, 49, "upon us"),
        (50, 54, "the fear of the Lord."),
    ],
    8: [
        (0, 1, "But behold,"),
        (2, 6, "the voice said"),
        (7, 9, "unto me:"),
        (10, 11, "Arise."),
        (12, 15, "And I arose"),
        (16, 20, "and stood up,"),
        (21, 23, "and beheld"),
        (24, 26, "the angel."),
    ],
    9: [
        (0, 5, "And he said"),
        (6, 8, "unto me:"),
        (9, 12, "If thou wilt"),
        (13, 14, "be destroyed"),
        (15, 17, "of thyself,"),
        (18, 22, "seek no more"),
        (23, 24, "to destroy"),
        (25, 29, "the church of God."),
    ],
    10: [
        (0, 2, "And it came to pass that"),
        (3, 6, "I fell"),
        (7, 9, "to the earth;"),
        (10, 13, "for the space of"),
        (14, 16, "three days"),
        (17, 20, "and three nights"),
        (21, 27, "that I could not"),
        (28, 28, "open"),
        (29, 30, "my mouth,"),
        (31, 36, "neither had I the use of"),
        (37, 38, "my hands"),
        (39, 41, "and my feet."),
    ],
    11: [
        (0, 6, "And the angel spake"),
        (7, 9, "unto me"),
        (10, 14, "more things,"),
        (15, 17, "which were heard"),
        (18, 20, "by my brethren,"),
        (21, 25, "but I did not hear them;"),
        (26, 26, "for"),
        (27, 31, "when I heard"),
        (32, 34, "the words—"),
        (35, 38, "If thou wilt"),
        (39, 40, "be destroyed"),
        (41, 43, "of thyself,"),
        (44, 48, "seek no more"),
        (49, 50, "to destroy"),
        (51, 55, "the church of God—"),
        (56, 58, "I was struck"),
        (59, 63, "with such great fear"),
        (64, 66, "and amazement"),
        (67, 69, "lest I should be destroyed,"),
        (70, 73, "that I fell"),
        (74, 76, "to the earth"),
        (77, 82, "and I did hear no more"),
        (83, 84, "anything."),
    ],
    12: [
        (0, 3, "But I felt"),
        (4, 5, "the pain"),
        (6, 9, "and eternal torment,"),
        (10, 10, "for"),
        (11, 14, "my soul was harrowed up"),
        (15, 18, "to the greatest degree"),
        (19, 22, "and racked"),
        (23, 26, "with all my sins."),
    ],
    13: [
        (0, 0, "Yea,"),
        (1, 3, "I did remember"),
        (4, 5, "my sins"),
        (6, 8, "and all iniquities,"),
        (9, 13, "for which I was tormented"),
        (14, 17, "with the pains of hell;"),
        (18, 18, "yea,"),
        (19, 21, "I saw"),
        (22, 24, "that I had rebelled"),
        (25, 28, "against my God,"),
        (29, 33, "and that I had not kept"),
        (34, 36, "his holy commandments."),
    ],
    14: [
        (0, 0, "Yea,"),
        (1, 4, "and I had murdered"),
        (5, 9, "many of his children,"),
        (10, 10, "or rather"),
        (11, 16, "I led away"),
        (17, 18, "them"),
        (19, 21, "unto destruction;"),
        (22, 22, "yea,"),
        (23, 26, "and in fine"),
        (27, 30, "so great had been"),
        (31, 32, "my iniquities,"),
        (33, 36, "the very thought"),
        (37, 40, "of my coming"),
        (41, 45, "into the presence of my God"),
        (46, 49, "did rack"),
        (50, 54, "my soul"),
        (55, 58, "with great horror"),
        (59, 61, "inexpressible."),
    ],
    15: [
        (0, 3, "thought I,"),
        (4, 4, "O,"),
        (5, 10, "that could be banished"),
        (11, 12, "I"),
        (13, 14, "and become extinct"),
        (15, 17, "both in soul"),
        (18, 20, "and body,"),
        (21, 26, "that I might not be brought"),
        (27, 28, "to stand"),
        (29, 33, "in the presence of my God,"),
        (34, 35, "to be judged"),
        (36, 38, "of my deeds."),
    ],
    16: [
        (0, 2, "And now,"),
        (3, 6, "for three days"),
        (7, 10, "and three nights"),
        (11, 14, "was I racked,"),
        (15, 16, "even with the pains"),
        (17, 22, "of a damned soul."),
    ],
    17: [
        (0, 2, "And it came to pass that"),
        (3, 8, "as I was thus racked"),
        (9, 10, "with pain"),
        (11, 13, "and torment,"),
        (14, 16, "while I was harrowed up"),
        (17, 19, "by the memory"),
        (20, 24, "of my many sins,"),
        (25, 25, "behold,"),
        (26, 29, "I remembered also"),
        (30, 31, "to have heard"),
        (32, 34, "my father"),
        (35, 37, "prophesy"),
        (38, 39, "unto the people"),
        (40, 42, "concerning"),
        (43, 45, "the coming"),
        (46, 50, "of one Jesus Christ,"),
        (51, 54, "a Son of"),
        (55, 56, "God,"),
        (57, 58, "to atone"),
        (59, 63, "for the sins of the world."),
    ],
    18: [
        (0, 1, "Now,"),
        (2, 7, "as my mind caught hold"),
        (8, 10, "upon this thought,"),
        (11, 14, "I cried"),
        (15, 19, "within my heart:"),
        (20, 20, "O"),
        (21, 22, "Jesus,"),
        (23, 26, "thou Son of"),
        (27, 28, "God,"),
        (29, 33, "have mercy"),
        (34, 36, "on me,"),
        (37, 38, "who"),
        (39, 41, "am"),
        (42, 45, "in the gall of bitterness,"),
        (46, 49, "and am encircled about"),
        (50, 54, "by the everlasting chains"),
        (55, 57, "of death."),
    ],
    19: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 7, "when I thought"),
        (8, 9, "this,"),
        (10, 14, "I could remember no more"),
        (15, 16, "my pains;"),
        (17, 17, "yea,"),
        (18, 22, "I was harrowed up no more"),
        (23, 25, "by the memory"),
        (26, 28, "of my sins."),
    ],
    20: [
        (0, 1, "And oh,"),
        (2, 4, "what joy,"),
        (5, 9, "and what marvelous light"),
        (10, 12, "I did behold;"),
        (13, 13, "yea,"),
        (14, 17, "my soul was filled"),
        (18, 20, "with joy"),
        (21, 25, "as exceeding"),
        (26, 30, "as was my pain!"),
    ],
    21: [
        (0, 0, "Yea,"),
        (1, 4, "I say"),
        (5, 7, "unto you,"),
        (8, 10, "my son,"),
        (11, 14, "there could be nothing"),
        (15, 20, "so exquisite"),
        (21, 26, "and so bitter"),
        (27, 31, "as were my pains."),
        (32, 32, "Yea,"),
        (33, 38, "and again I say"),
        (39, 39, "also"),
        (40, 42, "unto you,"),
        (43, 45, "my son,"),
        (46, 49, "on the other hand,"),
        (50, 53, "there can be nothing"),
        (54, 59, "so exquisite"),
        (60, 61, "and sweet"),
        (62, 66, "as was my joy."),
    ],
    22: [
        (0, 0, "Yea,"),
        (1, 3, "methought"),
        (4, 6, "I saw,"),
        (7, 11, "even as saw"),
        (12, 16, "our father Lehi,"),
        (17, 19, "God"),
        (20, 24, "sitting upon his throne,"),
        (25, 26, "surrounded"),
        (27, 29, "with concourses of angels"),
        (30, 32, "numberless,"),
        (33, 37, "in the attitude of singing"),
        (38, 40, "and praising"),
        (41, 44, "their God;"),
        (45, 45, "yea,"),
        (46, 50, "and my soul did long"),
        (51, 56, "to be there."),
    ],
    23: [
        (0, 1, "But behold,"),
        (2, 4, "did receive again"),
        (5, 7, "my hands"),
        (8, 10, "and my feet"),
        (11, 13, "their strength,"),
        (14, 19, "and I stood up"),
        (20, 22, "upon my feet,"),
        (23, 25, "and did manifest"),
        (26, 27, "unto the people"),
        (28, 30, "that I had been born"),
        (31, 34, "of God."),
    ],
    24: [
        (0, 0, "Yea,"),
        (1, 5, "and from that time"),
        (6, 8, "even until"),
        (9, 12, "now,"),
        (13, 15, "I have labored"),
        (16, 20, "without ceasing,"),
        (21, 26, "that I might bring"),
        (27, 28, "souls"),
        (29, 31, "unto repentance;"),
        (32, 37, "that I might bring"),
        (38, 39, "them"),
        (40, 41, "to taste"),
        (42, 45, "of the exceeding joy"),
        (46, 49, "of which I did taste"),
        (50, 51, "thereof;"),
        (52, 57, "that they might also be born"),
        (58, 59, "they"),
        (60, 63, "of God,"),
        (64, 65, "and be filled"),
        (66, 69, "with the Holy Ghost."),
    ],
    25: [
        (0, 0, "Yea,"),
        (1, 4, "and now behold,"),
        (5, 7, "O my son,"),
        (8, 13, "the Lord doth give"),
        (14, 16, "unto me"),
        (17, 22, "exceedingly great joy"),
        (23, 25, "in the fruit"),
        (26, 28, "of my labors;"),
    ],
    26: [
        (0, 0, "For"),
        (1, 5, "because of the word"),
        (6, 9, "which he hath imparted"),
        (10, 12, "unto me,"),
        (13, 13, "behold,"),
        (14, 17, "many have been born"),
        (18, 21, "of God,"),
        (22, 23, "and have tasted"),
        (24, 28, "as I have tasted,"),
        (29, 30, "and have seen eye to eye"),
        (31, 35, "as I have seen;"),
        (36, 37, "therefore"),
        (38, 41, "they do know"),
        (42, 46, "concerning these things"),
        (47, 51, "of which I have spoken,"),
        (52, 56, "as I do know;"),
        (57, 60, "and the knowledge"),
        (61, 64, "which I have"),
        (65, 67, "is of"),
        (68, 70, "God."),
    ],
    27: [
        (0, 3, "And I have been supported"),
        (4, 7, "while I was"),
        (8, 10, "under"),
        (11, 13, "trials and troubles"),
        (14, 17, "of every kind,"),
        (18, 18, "yea,"),
        (19, 23, "and in all manner of afflictions;"),
        (24, 24, "yea,"),
        (25, 30, "God hath delivered me"),
        (31, 33, "from prison,"),
        (34, 37, "and from bonds,"),
        (38, 42, "and from death;"),
        (43, 43, "yea,"),
        (44, 48, "and I do put"),
        (49, 50, "my trust"),
        (51, 53, "in him;"),
        (54, 60, "and he will deliver"),
        (61, 61, "still"),
        (62, 64, "me."),
    ],
    28: [
        (0, 3, "And I know"),
        (4, 9, "that he will raise"),
        (10, 12, "me up"),
        (13, 16, "at the last day,"),
        (17, 21, "to dwell with him"),
        (22, 24, "in glory;"),
        (25, 25, "yea,"),
        (26, 31, "and I will praise"),
        (32, 33, "him"),
        (34, 35, "forever,"),
        (36, 36, "for"),
        (37, 42, "he hath brought our fathers"),
        (43, 44, "out of Egypt,"),
        (45, 47, "and he swallowed up"),
        (48, 49, "the Egyptians"),
        (50, 53, "in the Red Sea;"),
        (54, 58, "and he led"),
        (59, 60, "them"),
        (61, 63, "by his power"),
        (64, 68, "into the promised land;"),
        (69, 69, "yea,"),
        (70, 75, "and he hath delivered them"),
        (76, 78, "out of bondage"),
        (79, 81, "and captivity,"),
        (82, 87, "from time to time."),
    ],
    29: [
        (0, 0, "Yea,"),
        (1, 5, "and he hath also brought"),
        (6, 8, "our fathers"),
        (9, 13, "out of the land of Jerusalem;"),
        (14, 18, "and he hath also delivered"),
        (19, 20, "them,"),
        (21, 25, "by his power"),
        (26, 28, "everlasting,"),
        (29, 31, "out of bondage"),
        (32, 34, "and captivity,"),
        (35, 40, "from time to time,"),
        (41, 44, "even down"),
        (45, 48, "to the present day;"),
        (49, 53, "and I have retained"),
        (54, 56, "in remembrance"),
        (57, 58, "at all times"),
        (59, 61, "their captivity;"),
        (62, 62, "yea,"),
        (63, 68, "and ye also ought"),
        (69, 69, "to retain"),
        (70, 72, "in remembrance,"),
        (73, 78, "as I have done,"),
        (79, 81, "their captivity."),
    ],
    30: [
        (0, 1, "But behold,"),
        (2, 4, "my son,"),
        (5, 9, "this is not all;"),
        (10, 10, "for"),
        (11, 15, "ye ought to know"),
        (16, 20, "as I do know,"),
        (21, 22, "that"),
        (23, 26, "inasmuch as"),
        (27, 30, "ye keep the commandments"),
        (31, 33, "of God"),
        (34, 38, "ye shall prosper"),
        (39, 41, "in the land;"),
        (42, 47, "and ye ought also"),
        (48, 48, "to know,"),
        (49, 50, "that"),
        (51, 54, "inasmuch as"),
        (55, 59, "ye keep not the commandments"),
        (60, 62, "of God,"),
        (63, 68, "ye shall be cut off"),
        (69, 71, "from his presence."),
        (72, 73, "Now"),
        (74, 77, "this is according to"),
        (78, 79, "his word."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
