"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 31 — Alma leads a
mission to reclaim the apostate Zoramites; the Zoramites' proud, vain
worship upon the Rameumptom; Alma's grief at their wickedness; his prayer
for strength and success for himself and his fellow laborers.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15).

Em-dash token splits in the source per rule 11:
  v5  `tonu—ioe,`    -> `tonu—`    + `ioe,`  (v5  = 77 tokens)
  v28 `mai—matou`    -> `mai—`     + `matou` (v28 = 86 tokens)
  v32 `a’u—ioe,`     -> `a’u—`     + `ioe,`
  v32 `toalua—ioe,`  -> `toalua—`  + `ioe,`  (v32 = 67 tokens)

    python3 build_overrides_alma31.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 31

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 7, "after"),
        (8, 11, "the end of Korihor,"),
        (12, 16, "and Alma received"),
        (17, 18, "tidings"),
        (19, 23, "that were perverting"),
        (24, 25, "the Zoramites"),
        (26, 29, "the ways of the Lord,"),
        (30, 32, "and that"),
        (33, 34, "Zoram,"),
        (35, 39, "who was"),
        (40, 42, "their leader,"),
        (43, 47, "was leading away"),
        (48, 50, "the hearts of the people"),
        (51, 55, "to bow down to"),
        (56, 58, "dumb idols,"),
        (59, 63, "began again to sicken"),
        (64, 66, "his heart"),
        (67, 71, "because of the iniquity of"),
        (72, 73, "the people."),
    ],
    2: [
        (0, 0, "For"),
        (1, 5, "it became the cause of"),
        (6, 10, "Alma's great sorrow"),
        (11, 12, "the knowing"),
        (13, 17, "concerning the iniquity"),
        (18, 20, "among"),
        (21, 22, "his people;"),
        (23, 24, "therefore"),
        (25, 29, "was exceedingly sorrowful"),
        (30, 31, "his heart"),
        (32, 38, "because of the departure of"),
        (39, 40, "the Zoramites"),
        (41, 44, "from the Nephites."),
    ],
    3: [
        (0, 1, "Now"),
        (2, 5, "gathered together"),
        (6, 7, "the Zoramites"),
        (8, 10, "themselves"),
        (11, 13, "in a land"),
        (14, 18, "which they called Antionum,"),
        (19, 23, "which was on the side"),
        (24, 26, "east of"),
        (27, 30, "the land of Zarahemla,"),
        (31, 35, "which lay nearly across"),
        (36, 39, "bordering on the seashore,"),
        (40, 44, "which was on the side"),
        (45, 47, "south of"),
        (48, 51, "the land of Jershon,"),
        (52, 56, "which also bordered upon"),
        (57, 58, "the wilderness"),
        (59, 63, "on the south,"),
        (64, 66, "which wilderness"),
        (67, 69, "was full of"),
        (70, 71, "the Lamanites."),
    ],
    4: [
        (0, 1, "Now"),
        (2, 6, "the Nephites greatly feared"),
        (7, 11, "lest the Zoramites should make"),
        (12, 13, "a correspondence"),
        (14, 16, "with the Lamanites,"),
        (17, 21, "and become the means"),
        (22, 22, "of"),
        (23, 26, "a great loss of"),
        (27, 31, "the portion of the Nephites."),
    ],
    5: [
        (0, 2, "And now,"),
        (3, 6, "as there was"),
        (7, 10, "in the preaching of"),
        (11, 12, "the word"),
        (13, 15, "a great tendency"),
        (16, 20, "to lead the people"),
        (21, 23, "that they do"),
        (24, 26, "that which is right—"),
        (27, 27, "yea,"),
        (28, 32, "there was its effect"),
        (33, 33, "powerful"),
        (34, 38, "greater upon"),
        (39, 41, "the minds of the people"),
        (42, 45, "than the sword,"),
        (46, 49, "or any other"),
        (50, 51, "thing"),
        (52, 53, "which had come"),
        (54, 57, "unto them—"),
        (58, 59, "therefore"),
        (60, 63, "Alma thought"),
        (64, 68, "it was expedient that they should try"),
        (69, 71, "the virtue of"),
        (72, 76, "the word of God."),
    ],
    6: [
        (0, 1, "Therefore"),
        (2, 5, "he took"),
        (6, 6, "Ammon,"),
        (7, 8, "and Aaron,"),
        (9, 10, "and Omner;"),
        (11, 13, "and Himni"),
        (14, 16, "he left"),
        (17, 19, "in the church"),
        (20, 21, "in Zarahemla;"),
        (22, 26, "but the former three"),
        (27, 31, "he took"),
        (32, 34, "and also Amulek"),
        (35, 36, "and Zeezrom,"),
        (37, 41, "who were at Melek;"),
        (42, 46, "and he also took"),
        (47, 51, "two of his sons."),
    ],
    7: [
        (0, 1, "Now"),
        (2, 5, "he took not"),
        (6, 10, "the eldest of his sons"),
        (11, 13, "with him,"),
        (14, 18, "and his name was"),
        (19, 19, "Helaman;"),
        (20, 23, "but the names of"),
        (24, 25, "the two"),
        (26, 30, "whom he took"),
        (31, 33, "with him"),
        (34, 37, "were Shiblon and Corianton;"),
        (38, 42, "and these are the names of"),
        (43, 44, "them"),
        (45, 49, "who went"),
        (50, 52, "with him"),
        (53, 57, "among the Zoramites,"),
        (58, 60, "to preach"),
        (61, 64, "unto them"),
        (65, 66, "the word."),
    ],
    8: [
        (0, 1, "Now"),
        (2, 4, "the Zoramites"),
        (5, 8, "were dissenters"),
        (9, 11, "from the Nephites;"),
        (12, 13, "therefore"),
        (14, 17, "had already"),
        (18, 19, "been preached"),
        (20, 23, "the word of"),
        (24, 25, "God"),
        (26, 29, "unto them."),
    ],
    9: [
        (0, 0, "But"),
        (1, 5, "they had fallen"),
        (6, 9, "into great errors,"),
        (10, 10, "for"),
        (11, 14, "they would not observe"),
        (15, 18, "to keep the commandments of"),
        (19, 20, "God,"),
        (21, 23, "and his statutes,"),
        (24, 26, "according to"),
        (27, 30, "the law of Moses."),
    ],
    10: [
        (0, 5, "Neither would they observe"),
        (6, 9, "the performances of the church,"),
        (10, 14, "to pray and supplicate"),
        (15, 17, "to God"),
        (18, 20, "continually"),
        (21, 23, "daily,"),
        (24, 29, "that they might not enter"),
        (30, 30, "into"),
        (31, 31, "temptation."),
    ],
    11: [
        (0, 0, "Yea,"),
        (1, 3, "in fine,"),
        (4, 6, "they did pervert"),
        (7, 10, "the ways of the Lord"),
        (11, 15, "in many instances;"),
        (16, 17, "therefore,"),
        (18, 21, "for this cause,"),
        (22, 25, "went"),
        (26, 29, "Alma and his brethren"),
        (30, 32, "into the land"),
        (33, 37, "to preach the word"),
        (38, 41, "unto them."),
    ],
    12: [
        (0, 1, "Now,"),
        (2, 6, "when they had come"),
        (7, 9, "into the land,"),
        (10, 10, "behold,"),
        (11, 15, "to their great astonishment"),
        (16, 19, "they found"),
        (20, 24, "that the Zoramites had built"),
        (25, 26, "synagogues,"),
        (27, 31, "and they gathered together"),
        (32, 34, "themselves"),
        (35, 39, "on one day"),
        (40, 42, "of the week,"),
        (43, 46, "which day"),
        (47, 49, "they called"),
        (50, 53, "a day of"),
        (54, 55, "the Lord;"),
        (56, 60, "and they did worship"),
        (61, 63, "after a manner"),
        (64, 68, "which had never been beheld"),
        (69, 70, "before by"),
        (71, 74, "Alma and his brethren;"),
    ],
    13: [
        (0, 0, "For"),
        (1, 5, "they had built a place"),
        (6, 9, "in the center of"),
        (10, 12, "their synagogue,"),
        (13, 15, "a place"),
        (16, 18, "for standing,"),
        (19, 22, "which was high"),
        (23, 27, "above the head;"),
        (28, 31, "and the top thereof"),
        (32, 35, "would only admit"),
        (36, 37, "person"),
        (38, 42, "one could occupy it."),
    ],
    14: [
        (0, 1, "Therefore,"),
        (2, 4, "whosoever"),
        (5, 8, "desired to worship,"),
        (9, 13, "must go forth"),
        (14, 18, "and stand upon"),
        (19, 20, "this place,"),
        (21, 24, "and stretch forth his hands"),
        (25, 28, "towards heaven,"),
        (29, 30, "and cry"),
        (31, 34, "with a loud voice,"),
        (35, 36, "saying:"),
    ],
    15: [
        (0, 1, "O God"),
        (2, 2, "holy,"),
        (3, 4, "holy;"),
        (5, 7, "we believe"),
        (8, 12, "that thou art God,"),
        (13, 16, "and we believe"),
        (17, 19, "that thou art holy;"),
        (20, 23, "and thou wast"),
        (24, 26, "a spirit,"),
        (27, 29, "and thou art"),
        (30, 32, "a spirit,"),
        (33, 39, "and thou wilt be"),
        (40, 42, "a spirit"),
        (43, 44, "forever."),
    ],
    16: [
        (0, 1, "O God"),
        (2, 3, "holy,"),
        (4, 6, "we believe"),
        (7, 11, "that thou hast separated"),
        (12, 13, "us"),
        (14, 18, "from our brethren;"),
        (19, 23, "and we believe not"),
        (24, 26, "in the tradition of"),
        (27, 29, "our brethren,"),
        (30, 33, "which was handed"),
        (34, 36, "down"),
        (37, 40, "to them"),
        (41, 43, "by the childishness"),
        (44, 47, "of their fathers;"),
        (48, 51, "but we believe"),
        (52, 56, "that thou hast elected us"),
        (57, 59, "to be"),
        (60, 62, "thy holy children;"),
        (63, 67, "and thou hast made known"),
        (68, 68, "also"),
        (69, 72, "unto us"),
        (73, 76, "that there shall be no"),
        (77, 78, "Christ."),
    ],
    17: [
        (0, 4, "But thou remainest the same"),
        (5, 6, "yesterday,"),
        (7, 9, "today,"),
        (10, 12, "and forever;"),
        (13, 16, "and thou hast elected"),
        (17, 18, "us,"),
        (19, 22, "that we shall be saved"),
        (23, 24, "us;"),
        (25, 26, "although"),
        (27, 30, "all they"),
        (31, 34, "who surround us"),
        (35, 36, "are elected"),
        (37, 39, "to be cast down"),
        (40, 42, "by thy wrath"),
        (43, 44, "to hell;"),
        (45, 47, "for this holiness,"),
        (48, 50, "O God,"),
        (51, 54, "we thank"),
        (55, 57, "thee;"),
        (58, 63, "and we thank"),
        (64, 64, "also"),
        (65, 67, "thee"),
        (68, 72, "that thou hast elected us,"),
        (73, 77, "that may not"),
        (78, 80, "be led away"),
        (81, 82, "us"),
        (83, 87, "after the foolish traditions"),
        (88, 91, "of our brethren,"),
        (92, 95, "which doth bind"),
        (96, 99, "them down"),
        (100, 102, "to a belief"),
        (103, 104, "of Christ,"),
        (105, 108, "which doth lead"),
        (109, 111, "their hearts"),
        (112, 115, "to wander far away"),
        (116, 119, "from thee,"),
        (120, 122, "our God."),
    ],
    18: [
        (0, 6, "And we again thank"),
        (7, 9, "thee,"),
        (10, 12, "O God,"),
        (13, 17, "for we are become"),
        (18, 21, "a chosen people"),
        (22, 23, "and holy."),
        (24, 24, "Amen."),
    ],
    19: [
        (0, 1, "Now"),
        (2, 3, "it came to pass that"),
        (4, 7, "after"),
        (8, 9, "had heard"),
        (10, 11, "Alma"),
        (12, 14, "and his brethren"),
        (15, 17, "and his sons"),
        (18, 20, "these prayers,"),
        (21, 23, "there was no measuring"),
        (24, 27, "their great astonishment."),
    ],
    20: [
        (0, 0, "For"),
        (1, 1, "behold,"),
        (2, 4, "went forth"),
        (5, 7, "every man"),
        (8, 10, "and offered up"),
        (11, 15, "these same prayers."),
    ],
    21: [
        (0, 1, "Now"),
        (2, 4, "the place"),
        (5, 9, "was called by them"),
        (10, 11, "Rameumptom,"),
        (12, 14, "which,"),
        (15, 16, "being interpreted,"),
        (17, 20, "is the holy stand."),
    ],
    22: [
        (0, 1, "Now,"),
        (2, 4, "from this stand"),
        (5, 8, "they did offer up,"),
        (9, 11, "every man,"),
        (12, 15, "the selfsame prayer"),
        (16, 17, "the one"),
        (18, 20, "unto God,"),
        (21, 24, "thanking"),
        (25, 28, "their God"),
        (29, 33, "that he had chosen them,"),
        (34, 35, "and that"),
        (36, 40, "he did not lead away"),
        (41, 42, "them"),
        (43, 45, "that they should follow"),
        (46, 47, "after the tradition"),
        (48, 51, "of their brethren,"),
        (52, 53, "and that"),
        (54, 57, "were not stolen away"),
        (58, 60, "their hearts"),
        (61, 62, "to believe"),
        (63, 64, "in things"),
        (65, 69, "which are to come,"),
        (70, 72, "which things"),
        (73, 76, "they knew not"),
        (77, 78, "anything"),
        (79, 82, "concerning them."),
    ],
    23: [
        (0, 1, "Now,"),
        (2, 6, "after had offered up"),
        (7, 9, "all the people"),
        (10, 11, "thanks"),
        (12, 14, "after this manner,"),
        (15, 18, "they returned"),
        (19, 22, "to their homes,"),
        (23, 27, "never speaking again"),
        (28, 30, "concerning"),
        (31, 33, "their God"),
        (34, 36, "until"),
        (37, 40, "they assembled together again"),
        (41, 43, "themselves"),
        (44, 47, "to the holy stand,"),
        (48, 51, "to offer up thanks"),
        (52, 54, "according to"),
        (55, 57, "their manner."),
    ],
    24: [
        (0, 1, "Now"),
        (2, 6, "when Alma saw"),
        (7, 9, "this thing,"),
        (10, 12, "was greatly grieved"),
        (13, 14, "his heart;"),
        (15, 15, "for"),
        (16, 18, "he saw"),
        (19, 21, "that they were"),
        (22, 25, "a wicked people"),
        (26, 28, "and perverse;"),
        (29, 29, "yea,"),
        (30, 32, "he saw"),
        (33, 37, "that their hearts were set"),
        (38, 40, "upon gold,"),
        (41, 43, "and upon silver,"),
        (44, 47, "and all manner of fine goods."),
    ],
    25: [
        (0, 0, "Yea,"),
        (1, 7, "and he also saw"),
        (8, 12, "that their hearts were lifted up"),
        (13, 16, "unto great boasting,"),
        (17, 20, "in their pride."),
    ],
    26: [
        (0, 4, "And he lifted up"),
        (5, 6, "his voice"),
        (7, 9, "to heaven,"),
        (10, 11, "and cried,"),
        (12, 14, "saying:"),
        (15, 15, "O,"),
        (16, 19, "how"),
        (20, 21, "long,"),
        (22, 24, "O Lord,"),
        (25, 28, "wilt thou suffer"),
        (29, 30, "thy servants"),
        (31, 32, "that they shall dwell"),
        (33, 35, "here below"),
        (36, 39, "in the flesh,"),
        (40, 41, "to behold"),
        (42, 46, "such great wickedness"),
        (47, 49, "among"),
        (50, 53, "the children of men?"),
    ],
    27: [
        (0, 0, "Behold,"),
        (1, 3, "O God,"),
        (4, 7, "they cry"),
        (8, 10, "unto thee,"),
        (11, 13, "and yet are swallowed up"),
        (14, 16, "their hearts"),
        (17, 20, "in their pride."),
        (21, 21, "Behold,"),
        (22, 24, "O God,"),
        (25, 28, "they cry"),
        (29, 31, "unto thee"),
        (32, 35, "with their mouths,"),
        (36, 40, "while they are puffed up,"),
        (41, 45, "even to greatness,"),
        (46, 49, "with the vain things"),
        (50, 52, "of the world."),
    ],
    28: [
        (0, 0, "Behold,"),
        (1, 3, "O my God,"),
        (4, 8, "their costly apparel,"),
        (9, 12, "and their ringlets,"),
        (13, 16, "and their bracelets,"),
        (17, 19, "and their"),
        (20, 22, "ornaments of gold,"),
        (23, 25, "and all their"),
        (26, 28, "precious things"),
        (29, 33, "wherewith they adorn"),
        (34, 36, "themselves;"),
        (37, 38, "and behold,"),
        (39, 41, "are set"),
        (42, 44, "their hearts"),
        (45, 47, "upon them,"),
        (48, 52, "and yet they cry"),
        (53, 55, "unto thee"),
        (56, 58, "and say—"),
        (59, 62, "We thank"),
        (63, 65, "thee,"),
        (66, 68, "O God,"),
        (69, 72, "for we are"),
        (73, 77, "a chosen people"),
        (78, 79, "unto thee,"),
        (80, 81, "while others"),
        (82, 85, "shall perish."),
    ],
    29: [
        (0, 0, "Yea,"),
        (1, 5, "and they say"),
        (6, 9, "that thou hast made known"),
        (10, 13, "unto them"),
        (14, 15, "that"),
        (16, 19, "there shall be no"),
        (20, 21, "Christ."),
    ],
    30: [
        (0, 2, "O Lord"),
        (3, 4, "God,"),
        (5, 9, "how long"),
        (10, 13, "wilt thou suffer"),
        (14, 17, "that shall remain"),
        (18, 19, "such wickedness"),
        (20, 23, "and infidelity"),
        (24, 28, "among this people?"),
        (29, 31, "O Lord,"),
        (32, 35, "wilt thou give"),
        (36, 38, "me"),
        (39, 40, "strength,"),
        (41, 44, "that I may"),
        (45, 46, "bear"),
        (47, 48, "mine infirmities."),
        (49, 49, "For"),
        (50, 52, "I am infirm,"),
        (53, 56, "and such wickedness"),
        (57, 60, "which is among"),
        (61, 62, "this people"),
        (63, 67, "doth pain my soul."),
    ],
    31: [
        (0, 2, "O Lord,"),
        (3, 5, "is exceedingly sorrowful"),
        (6, 7, "my heart;"),
        (8, 10, "wilt thou comfort"),
        (11, 12, "my soul"),
        (13, 14, "in Christ."),
        (15, 17, "O Lord,"),
        (18, 21, "wilt thou grant"),
        (22, 24, "unto me"),
        (25, 28, "that I may"),
        (29, 30, "have"),
        (31, 32, "strength,"),
        (33, 37, "that I may"),
        (38, 38, "suffer"),
        (39, 41, "with patience"),
        (42, 43, "these afflictions"),
        (44, 48, "which shall come"),
        (49, 51, "upon me,"),
        (52, 53, "because of"),
        (54, 55, "the iniquity"),
        (56, 58, "of this people."),
    ],
    32: [
        (0, 2, "O Lord,"),
        (3, 5, "wilt thou comfort"),
        (6, 7, "my soul,"),
        (8, 10, "and give"),
        (11, 13, "unto me"),
        (14, 15, "success,"),
        (16, 19, "and also my fellow laborers"),
        (20, 23, "who are together"),
        (24, 25, "with me—"),
        (26, 26, "yea,"),
        (27, 28, "Ammon,"),
        (29, 30, "and Aaron,"),
        (31, 32, "and Omner,"),
        (33, 35, "and also Amulek"),
        (36, 37, "and Zeezrom,"),
        (38, 41, "and also my sons"),
        (42, 43, "the two—"),
        (44, 44, "yea,"),
        (45, 47, "even"),
        (48, 51, "all these"),
        (52, 54, "wilt thou comfort,"),
        (55, 57, "O Lord."),
        (58, 58, "Yea,"),
        (59, 61, "wilt thou comfort"),
        (62, 64, "their souls"),
        (65, 66, "in Christ."),
    ],
    33: [
        (0, 3, "Wilt thou grant"),
        (4, 7, "unto them"),
        (8, 12, "that they may have"),
        (13, 14, "strength,"),
        (15, 19, "that they may"),
        (20, 20, "bear"),
        (21, 23, "their afflictions"),
        (24, 27, "which shall"),
        (28, 29, "come"),
        (30, 33, "upon them"),
        (34, 35, "because of"),
        (36, 36, "the iniquities"),
        (37, 39, "of this people."),
    ],
    34: [
        (0, 2, "O Lord,"),
        (3, 6, "wilt thou grant"),
        (7, 10, "unto us"),
        (11, 15, "that we may have"),
        (16, 17, "success"),
        (18, 21, "in bringing again"),
        (22, 24, "them"),
        (25, 27, "unto thee,"),
        (28, 29, "in Christ."),
    ],
    35: [
        (0, 0, "Behold,"),
        (1, 3, "O Lord,"),
        (4, 6, "are precious"),
        (7, 9, "their souls,"),
        (10, 13, "and many"),
        (14, 16, "of them"),
        (17, 20, "are our brethren;"),
        (21, 22, "therefore,"),
        (23, 24, "give"),
        (25, 28, "unto us,"),
        (29, 31, "O Lord,"),
        (32, 33, "power"),
        (34, 36, "and wisdom"),
        (37, 41, "that we may"),
        (42, 43, "bring again"),
        (44, 46, "these,"),
        (47, 50, "our brethren,"),
        (51, 53, "unto thee."),
    ],
    36: [
        (0, 1, "Now"),
        (2, 3, "it came to pass that"),
        (4, 7, "when"),
        (8, 9, "had said"),
        (10, 11, "Alma"),
        (12, 14, "these words,"),
        (15, 18, "he clapped"),
        (19, 20, "his hands"),
        (21, 23, "upon"),
        (24, 26, "all them"),
        (27, 30, "who were together"),
        (31, 32, "with him."),
        (33, 34, "And behold,"),
        (35, 39, "as he clapped"),
        (40, 41, "his hands"),
        (42, 44, "upon"),
        (45, 46, "them,"),
        (47, 50, "they were filled"),
        (51, 54, "with the Holy Spirit."),
    ],
    37: [
        (0, 4, "And after that"),
        (5, 8, "they did separate"),
        (9, 11, "the one"),
        (12, 14, "from the other,"),
        (15, 17, "taking no"),
        (18, 19, "thought"),
        (20, 23, "for themselves,"),
        (24, 27, "what"),
        (28, 31, "they should"),
        (32, 33, "eat,"),
        (34, 37, "or what"),
        (38, 41, "they should"),
        (42, 43, "drink,"),
        (44, 47, "or what"),
        (48, 51, "they should"),
        (52, 53, "put on."),
    ],
    38: [
        (0, 3, "And made"),
        (4, 5, "the Lord"),
        (6, 6, "provision"),
        (7, 9, "for them"),
        (10, 14, "that they should not"),
        (15, 15, "hunger,"),
        (16, 16, "neither"),
        (17, 21, "should they"),
        (22, 22, "thirst;"),
        (23, 23, "yea,"),
        (24, 28, "and he gave"),
        (29, 29, "also"),
        (30, 33, "them"),
        (34, 35, "strength,"),
        (36, 40, "that they should not suffer"),
        (41, 45, "any manner of"),
        (46, 46, "afflictions,"),
        (47, 48, "save"),
        (49, 50, "they were swallowed up"),
        (51, 53, "in the joy"),
        (54, 55, "of Christ."),
        (56, 57, "Now"),
        (58, 62, "this thing was done"),
        (63, 66, "according to"),
        (67, 70, "the prayer of Alma;"),
        (71, 75, "and this was done"),
        (76, 76, "because"),
        (77, 81, "he prayed"),
        (82, 84, "in faith."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
