"""Hand-curated TAM-phrase gloss overrides for Mosaea 19 — Gideon, the Lamanite invasion, and king Noah's death.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
subject `o ia` / agent `e ia` absorbed into the verb cluster, never split as a
bare "he" (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` fillers when a PP/object follows (rule 1), `mafai ona`/`ina ia`/
`ina ua` bound (rules 13/15), vocative `e`/`E …e` folded as "O X" (rule 12),
directional "forth" dropped (rule 12a). No pronoun/TAM word injected into a cell
whose span lacks that token; no content word repeats across adjacent cells
(except authentic Samoan doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah19.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 19
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass"),
        (4, 6, "returned"),
        (7, 8, "the army"),
        (9, 11, "of the king,"),
        (12, 14, "having searched"),
        (15, 17, "for the people"),
        (18, 20, "of the Lord"),
        (21, 21, "but"),
        (22, 23, "found not."),
    ],
    2: [
        (0, 0, "And"),
        (1, 2, "now,"),
        (3, 3, "behold,"),
        (4, 5, "were small"),
        (6, 7, "the forces"),
        (8, 10, "of the king,"),
        (11, 11, "for"),
        (12, 13, "had been reduced,"),
        (14, 14, "and"),
        (15, 17, "began"),
        (18, 19, "to be"),
        (20, 22, "a division"),
        (23, 25, "among"),
        (26, 28, "the remainder"),
        (29, 31, "of the people."),
    ],
    3: [
        (0, 0, "And"),
        (1, 3, "began"),
        (4, 5, "to breathe out"),
        (6, 8, "the part"),
        (9, 9, "lesser"),
        (10, 12, "of the people"),
        (13, 14, "threatenings"),
        (15, 16, "against"),
        (17, 19, "the king,"),
        (20, 20, "and"),
        (21, 23, "began"),
        (24, 25, "to be"),
        (26, 28, "a contention"),
        (29, 29, "great"),
        (30, 32, "among"),
        (33, 34, "them."),
    ],
    4: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "there was"),
        (6, 8, "among"),
        (9, 10, "them"),
        (11, 12, "a man"),
        (13, 14, "whose name was"),
        (15, 16, "Gideon,"),
        (17, 17, "and"),
        (18, 18, "because"),
        (19, 20, "he was"),
        (21, 24, "a mighty man"),
        (25, 25, "and"),
        (26, 28, "an enemy"),
        (29, 29, "also"),
        (30, 32, "to the king,"),
        (33, 34, "therefore"),
        (35, 39, "he drew"),
        (40, 41, "his sword,"),
        (42, 43, "and swore"),
        (44, 46, "in his wrath,"),
        (47, 51, "that he would slay"),
        (52, 54, "the king."),
    ],
    5: [
        (0, 3, "And it came to pass"),
        (4, 6, "he fought"),
        (7, 9, "with the king;"),
        (10, 10, "and"),
        (11, 12, "when"),
        (13, 14, "saw"),
        (15, 16, "the king"),
        (17, 22, "he would be overpowered"),
        (23, 25, "by him,"),
        (26, 29, "he fled"),
        (30, 31, "and ran"),
        (32, 34, "and got up"),
        (35, 37, "upon"),
        (38, 39, "the tower"),
        (40, 42, "which was near"),
        (43, 45, "the temple."),
    ],
    6: [
        (0, 0, "And"),
        (1, 2, "pursued"),
        (3, 4, "him"),
        (5, 6, "Gideon"),
        (7, 7, "and"),
        (8, 9, "was about to"),
        (10, 11, "get up"),
        (12, 14, "upon"),
        (15, 16, "the tower"),
        (17, 18, "to slay"),
        (19, 20, "the king,"),
        (21, 21, "and"),
        (22, 23, "cast his eyes"),
        (24, 25, "the king"),
        (26, 27, "round about towards"),
        (28, 30, "the land"),
        (31, 32, "of Shemlon,"),
        (33, 33, "and"),
        (34, 34, "behold,"),
        (35, 37, "there were"),
        (38, 39, "the army"),
        (40, 42, "of the Lamanites"),
        (43, 45, "within"),
        (46, 46, "the borders"),
        (47, 49, "of the land."),
    ],
    7: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "it came to pass"),
        (6, 7, "cried out"),
        (8, 9, "the king"),
        (10, 12, "in the anguish"),
        (13, 15, "of his soul,"),
        (16, 17, "saying:"),
        (18, 19, "O Gideon,"),
        (20, 21, "spare"),
        (22, 24, "me,"),
        (25, 25, "for"),
        (26, 28, "have come"),
        (29, 30, "the Lamanites"),
        (31, 34, "upon us,"),
        (35, 35, "and"),
        (36, 40, "they will destroy"),
        (41, 42, "us;"),
        (43, 43, "yea,"),
        (44, 48, "they will destroy"),
        (49, 50, "my people."),
    ],
    8: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 6, "was not so much concerned"),
        (7, 8, "the king"),
        (9, 11, "about"),
        (12, 13, "his people"),
        (14, 15, "than"),
        (16, 17, "his concern"),
        (18, 20, "about"),
        (21, 23, "his own life;"),
        (24, 27, "nevertheless,"),
        (28, 29, "did spare"),
        (30, 31, "Gideon"),
        (32, 33, "his life."),
    ],
    9: [
        (0, 0, "And"),
        (1, 2, "commanded"),
        (3, 5, "the king"),
        (6, 7, "the people"),
        (8, 9, "that they"),
        (10, 11, "should flee"),
        (12, 14, "before"),
        (15, 16, "came"),
        (17, 18, "the Lamanites,"),
        (19, 19, "and"),
        (20, 22, "went before"),
        (23, 25, "himself"),
        (26, 29, "before them,"),
        (30, 32, "and they did flee"),
        (33, 35, "into the wilderness,"),
        (36, 37, "together with"),
        (38, 40, "their women"),
        (41, 41, "and"),
        (42, 44, "their children."),
    ],
    10: [
        (0, 3, "And it came to pass"),
        (4, 4, "did pursue"),
        (5, 6, "them"),
        (7, 9, "the Lamanites,"),
        (10, 10, "and"),
        (11, 13, "did overtake"),
        (14, 15, "them,"),
        (16, 17, "and began"),
        (18, 19, "to slay"),
        (20, 21, "them."),
    ],
    11: [
        (0, 1, "Now"),
        (2, 4, "it came to pass"),
        (5, 6, "commanded"),
        (7, 8, "the king"),
        (9, 12, "them"),
        (13, 14, "that should leave"),
        (15, 17, "all the men"),
        (18, 20, "their wives"),
        (21, 21, "and"),
        (22, 24, "their children,"),
        (25, 27, "and flee"),
        (28, 30, "before"),
        (31, 32, "the Lamanites."),
    ],
    12: [
        (0, 1, "Now"),
        (2, 3, "there were many"),
        (4, 4, "that"),
        (5, 8, "would not leave"),
        (9, 10, "them,"),
        (11, 11, "but"),
        (12, 13, "had rather"),
        (14, 15, "stay"),
        (16, 18, "and perish together"),
        (19, 21, "with them."),
        (22, 22, "And"),
        (23, 25, "the rest"),
        (26, 27, "which remained"),
        (28, 29, "left"),
        (30, 32, "their wives"),
        (33, 33, "and"),
        (34, 36, "their children"),
        (37, 37, "and"),
        (38, 39, "fled."),
    ],
    13: [
        (0, 3, "And it came to pass"),
        (4, 6, "those"),
        (7, 9, "who"),
        (10, 11, "tarried"),
        (12, 12, "with"),
        (13, 15, "their wives"),
        (16, 16, "and"),
        (17, 19, "their children"),
        (20, 21, "caused"),
        (22, 24, "that should stand forth"),
        (25, 27, "their daughters"),
        (28, 28, "fair"),
        (29, 31, "and plead"),
        (32, 35, "with the Lamanites"),
        (36, 38, "that they would not"),
        (39, 41, "slay"),
        (42, 43, "them."),
    ],
    14: [
        (0, 3, "And it came to pass"),
        (4, 4, "had compassion"),
        (5, 6, "the Lamanites"),
        (7, 10, "on them,"),
        (11, 11, "for"),
        (12, 13, "were charmed"),
        (14, 15, "they"),
        (16, 18, "with the beauty"),
        (19, 22, "of their women."),
    ],
    15: [
        (0, 1, "Therefore"),
        (2, 4, "did spare"),
        (5, 7, "the Lamanites"),
        (8, 10, "their lives,"),
        (11, 12, "and took"),
        (13, 14, "them"),
        (15, 15, "captive"),
        (16, 18, "and carried back"),
        (19, 20, "them"),
        (21, 23, "to the land"),
        (24, 25, "of Nephi,"),
        (26, 28, "and granted"),
        (29, 32, "unto them"),
        (33, 34, "that they might possess"),
        (35, 37, "for themselves"),
        (38, 39, "the land,"),
        (40, 42, "under"),
        (43, 43, "the conditions"),
        (44, 47, "that they would deliver up"),
        (48, 49, "king"),
        (50, 51, "Noah"),
        (52, 54, "into the hands of"),
        (55, 56, "the Lamanites,"),
        (57, 59, "and deliver up"),
        (60, 62, "their property,"),
        (63, 64, "even"),
        (65, 66, "the half"),
        (67, 69, "of all things"),
        (70, 72, "they possessed,"),
        (73, 75, "the half"),
        (76, 79, "of their gold,"),
        (80, 80, "and"),
        (81, 83, "their silver,"),
        (84, 84, "and"),
        (85, 88, "their precious things"),
        (89, 89, "all,"),
        (90, 90, "and"),
        (91, 92, "thus"),
        (93, 94, "should"),
        (95, 97, "they pay"),
        (98, 99, "tribute"),
        (100, 102, "to the king"),
        (103, 105, "of the Lamanites"),
        (106, 108, "from year"),
        (109, 111, "to year."),
    ],
    16: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "there was"),
        (6, 7, "one"),
        (8, 9, "of the sons"),
        (10, 12, "of the king"),
        (13, 15, "who was among"),
        (16, 18, "those who were taken"),
        (19, 19, "captive,"),
        (20, 22, "whose name"),
        (23, 24, "was Limhi."),
    ],
    17: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "did not desire"),
        (6, 6, "Limhi"),
        (7, 8, "that be destroyed"),
        (9, 10, "his father;"),
        (11, 14, "nevertheless,"),
        (15, 17, "was not ignorant"),
        (18, 18, "Limhi"),
        (19, 20, "of the iniquities"),
        (21, 23, "of his father,"),
        (24, 27, "he himself"),
        (28, 31, "being a just man."),
    ],
    18: [
        (0, 3, "And it came to pass"),
        (4, 5, "sent"),
        (6, 6, "secretly"),
        (7, 8, "Gideon"),
        (9, 10, "men"),
        (11, 13, "into the wilderness,"),
        (14, 15, "to search for"),
        (16, 17, "the king"),
        (18, 18, "and"),
        (19, 20, "those"),
        (21, 23, "who were"),
        (24, 26, "with him."),
        (27, 27, "And"),
        (28, 30, "it came to pass"),
        (31, 32, "they met"),
        (33, 33, "with"),
        (34, 35, "all the people"),
        (36, 38, "in the wilderness,"),
        (39, 40, "save"),
        (41, 42, "the king"),
        (43, 43, "and"),
        (44, 45, "his priests."),
    ],
    19: [
        (0, 1, "Now"),
        (2, 4, "they had sworn"),
        (5, 8, "in their hearts"),
        (9, 12, "that they would return"),
        (13, 15, "to the land"),
        (16, 17, "of Nephi,"),
        (18, 19, "and if"),
        (20, 21, "were slain"),
        (22, 24, "their wives"),
        (25, 25, "and"),
        (26, 28, "their children,"),
        (29, 29, "and"),
        (30, 31, "those"),
        (32, 32, "also"),
        (33, 34, "who"),
        (35, 37, "had tarried"),
        (38, 40, "with them,"),
        (41, 45, "that they would seek"),
        (46, 47, "revenge,"),
        (48, 49, "and perish"),
        (50, 50, "also"),
        (51, 51, "together"),
        (52, 54, "with them."),
    ],
    20: [
        (0, 0, "But"),
        (1, 3, "commanded"),
        (4, 5, "the king"),
        (6, 9, "them"),
        (10, 12, "that should not"),
        (13, 17, "they return;"),
        (18, 18, "and"),
        (19, 21, "they were angry"),
        (22, 24, "with the king,"),
        (25, 26, "and caused"),
        (27, 30, "that he should suffer,"),
        (31, 33, "unto death"),
        (34, 36, "by fire."),
    ],
    21: [
        (0, 0, "And"),
        (1, 2, "were about to"),
        (3, 5, "they take"),
        (6, 6, "also"),
        (7, 8, "the priests"),
        (9, 10, "and slay"),
        (11, 14, "them,"),
        (15, 15, "but"),
        (16, 20, "they fled away"),
        (21, 24, "from before them."),
    ],
    22: [
        (0, 3, "And it came to pass"),
        (4, 10, "they were about to return"),
        (11, 13, "to the land"),
        (14, 15, "of Nephi,"),
        (16, 16, "and"),
        (17, 19, "they met"),
        (20, 21, "the men"),
        (22, 23, "of Gideon."),
        (24, 24, "And"),
        (25, 27, "told"),
        (28, 29, "the men"),
        (30, 31, "of Gideon"),
        (32, 35, "them"),
        (36, 37, "all that"),
        (38, 39, "had happened"),
        (40, 42, "to their wives"),
        (43, 43, "and"),
        (44, 46, "their children;"),
        (47, 47, "and"),
        (48, 50, "had granted"),
        (51, 53, "the Lamanites"),
        (54, 57, "unto them"),
        (58, 60, "that they might"),
        (61, 62, "possess"),
        (63, 65, "for themselves"),
        (66, 67, "the land"),
        (68, 70, "by"),
        (71, 73, "the payment"),
        (74, 76, "a tribute"),
        (77, 79, "to the Lamanites"),
        (80, 82, "the half"),
        (83, 85, "of all things"),
        (86, 88, "they possessed."),
    ],
    23: [
        (0, 0, "And"),
        (1, 3, "told"),
        (4, 6, "the people"),
        (7, 8, "the men"),
        (9, 10, "of Gideon"),
        (11, 13, "they had slain"),
        (14, 15, "the king,"),
        (16, 16, "and"),
        (17, 18, "had fled"),
        (19, 20, "his priests"),
        (21, 25, "from them"),
        (26, 29, "gone far off"),
        (30, 32, "into"),
        (33, 34, "the wilderness."),
    ],
    24: [
        (0, 3, "And it came to pass"),
        (4, 6, "after had finished"),
        (7, 8, "they concluding"),
        (9, 12, "the ceremony,"),
        (13, 17, "they returned"),
        (18, 20, "to the land"),
        (21, 22, "of Nephi,"),
        (23, 24, "rejoicing,"),
        (25, 25, "because"),
        (26, 28, "were not slain"),
        (29, 31, "their wives"),
        (32, 32, "and"),
        (33, 35, "their children;"),
        (36, 36, "and"),
        (37, 40, "they told"),
        (41, 42, "Gideon"),
        (43, 44, "what"),
        (45, 47, "they had done"),
        (48, 50, "to the king."),
    ],
    25: [
        (0, 3, "And it came to pass"),
        (4, 4, "made"),
        (5, 7, "the king"),
        (8, 10, "of the Lamanites"),
        (11, 12, "an oath"),
        (13, 16, "unto them,"),
        (17, 21, "should not slay"),
        (22, 23, "them"),
        (24, 26, "by his people."),
    ],
    26: [
        (0, 0, "And"),
        (1, 2, "made"),
        (3, 3, "also"),
        (4, 5, "Limhi,"),
        (6, 6, "because"),
        (7, 8, "he was"),
        (9, 11, "the son"),
        (12, 14, "of the king,"),
        (15, 15, "and"),
        (16, 16, "because"),
        (17, 18, "had conferred"),
        (19, 21, "by the people"),
        (22, 24, "upon him"),
        (25, 26, "the kingdom,"),
        (27, 28, "an oath"),
        (29, 31, "to the king"),
        (32, 34, "of the Lamanites,"),
        (35, 39, "should pay"),
        (40, 42, "his people"),
        (43, 44, "tribute"),
        (45, 47, "unto him,"),
        (48, 51, "the half"),
        (52, 53, "one"),
        (54, 56, "of all things"),
        (57, 59, "they possessed."),
    ],
    27: [
        (0, 3, "And it came to pass"),
        (4, 4, "began"),
        (5, 6, "Limhi"),
        (7, 8, "to establish"),
        (9, 10, "the kingdom"),
        (11, 12, "and to establish"),
        (13, 14, "peace"),
        (15, 17, "among"),
        (18, 19, "his people."),
    ],
    28: [
        (0, 0, "And"),
        (1, 2, "set"),
        (3, 3, "round about"),
        (4, 6, "the king"),
        (7, 9, "of the Lamanites"),
        (10, 10, "guards"),
        (11, 13, "the land,"),
        (14, 15, "that"),
        (16, 17, "might"),
        (18, 21, "he keep"),
        (22, 23, "the people"),
        (24, 25, "of Limhi"),
        (26, 28, "within"),
        (29, 30, "the land,"),
        (31, 32, "that"),
        (33, 34, "they not"),
        (35, 37, "depart"),
        (38, 40, "into the wilderness;"),
        (41, 41, "and"),
        (42, 45, "he did support"),
        (46, 47, "his guards"),
        (48, 50, "out of the tribute"),
        (51, 51, "which"),
        (52, 55, "he received"),
        (56, 59, "from the Nephites."),
    ],
    29: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 4, "did have"),
        (5, 7, "continual"),
        (8, 10, "the king"),
        (11, 12, "Limhi"),
        (13, 14, "peace"),
        (15, 17, "in his kingdom"),
        (18, 21, "for the space of"),
        (22, 24, "two years,"),
        (25, 28, "did not molest"),
        (29, 30, "the Lamanites"),
        (31, 34, "them,"),
        (35, 36, "nor seek"),
        (37, 38, "to destroy"),
        (39, 40, "them."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
