"""
Hand-curated TAM-phrase gloss overrides for Eteru (Ether) 13 — Ether prophesies of a New
Jerusalem to be built upon this land, and of the old Jerusalem whence Lehi came; he cries
repentance to Coriantumr and all the people, but is cast out and hides in the cavity of a
rock by day, writing the remainder of his record; the people reject his words, war breaks
out, and the mighty man Shared rises against Coriantumr in the beginning of the end.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15, vocative 12). `o le a` stays atomic and is never
fused with a following `se X` NP; cells go past 5 only for rule-2 (absorbed
subject) or rule-7 (`o le a` + verb + directional) clusters.

    python3 build_overrides_ether13.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "ether"
CHAPTER_NUM = 13

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 4, "I,"),
        (5, 6, "Moroni,"),
        (7, 9, "I do proceed"),
        (10, 11, "to finish"),
        (12, 13, "my record"),
        (14, 15, "concerning"),
        (16, 18, "the destruction"),
        (19, 21, "of the people"),
        (22, 23, "of whom"),
        (24, 26, "I have written."),
    ],
    2: [
        (0, 1, "For behold,"),
        (2, 4, "they did reject"),
        (5, 8, "all the words of Ether;"),
        (9, 9, "for"),
        (10, 15, "he did declare plainly"),
        (16, 19, "unto them"),
        (20, 21, "concerning"),
        (22, 24, "all things,"),
        (25, 27, "from the beginning"),
        (28, 29, "of man;"),
        (30, 32, "and thus"),
        (33, 36, "after that"),
        (37, 41, "the waters receded"),
        (42, 44, "from off"),
        (45, 46, "this land"),
        (47, 50, "it became a land"),
        (51, 53, "the most choice"),
        (54, 58, "above all other lands,"),
        (59, 62, "a chosen land"),
        (63, 65, "of the Lord;"),
        (66, 69, "wherefore"),
        (70, 72, "doth desire"),
        (73, 74, "the Lord"),
        (75, 77, "that shall serve"),
        (78, 80, "him"),
        (81, 82, "all men"),
        (83, 84, "who"),
        (85, 87, "do dwell upon it;"),
    ],
    3: [
        (0, 0, "And"),
        (1, 4, "this is the place"),
        (5, 8, "of the New Jerusalem,"),
        (9, 9, "which"),
        (10, 15, "should come down from"),
        (16, 17, "heaven,"),
        (18, 18, "and"),
        (19, 23, "this is the holy place"),
        (24, 26, "of the Lord."),
    ],
    4: [
        (0, 0, "Behold,"),
        (1, 3, "Ether did behold"),
        (4, 7, "the days of Christ,"),
        (8, 11, "and he spake"),
        (12, 13, "concerning"),
        (14, 17, "a New Jerusalem"),
        (18, 22, "upon this land."),
    ],
    5: [
        (0, 4, "And he spake also"),
        (5, 6, "concerning"),
        (7, 11, "the house of Israel,"),
        (12, 14, "and the Jerusalem"),
        (15, 20, "from whence should come"),
        (21, 21, "Lehi—"),
        (22, 23, "so that"),
        (24, 27, "after it is destroyed"),
        (28, 32, "shall be rebuilt,"),
        (33, 34, "to become"),
        (35, 38, "a holy city"),
        (39, 41, "unto the Lord;"),
        (42, 45, "wherefore,"),
        (46, 49, "it could not"),
        (50, 51, "be made"),
        (52, 55, "a new Jerusalem"),
        (56, 59, "for it had been"),
        (60, 63, "in a former time;"),
        (64, 64, "but"),
        (65, 69, "shall be built again,"),
        (70, 71, "and be made"),
        (72, 75, "a holy city"),
        (76, 78, "unto the Lord;"),
        (79, 83, "and shall be built"),
        (84, 88, "for the house of Israel—"),
    ],
    6: [
        (0, 2, "And thus"),
        (3, 6, "shall be built"),
        (7, 9, "a New Jerusalem"),
        (10, 13, "upon"),
        (14, 15, "this land,"),
        (16, 20, "for the remnant"),
        (21, 25, "of the seed of Joseph,"),
        (26, 28, "of which things"),
        (29, 31, "there hath been"),
        (32, 33, "a type."),
    ],
    7: [
        (0, 3, "For even as"),
        (4, 6, "brought Joseph"),
        (7, 8, "his father"),
        (9, 13, "into the land of Egypt,"),
        (14, 17, "even so did"),
        (18, 21, "he pass away"),
        (22, 22, "there;"),
        (23, 26, "wherefore"),
        (27, 29, "brought"),
        (30, 32, "the Lord"),
        (33, 37, "out of the land of Jerusalem"),
        (38, 41, "a remnant"),
        (42, 46, "of the seed of Joseph,"),
        (47, 52, "that he be merciful"),
        (53, 57, "unto the seed of Joseph"),
        (58, 60, "that they"),
        (61, 62, "should not perish,"),
        (63, 68, "even as he was merciful"),
        (69, 73, "unto the father of Joseph"),
        (74, 75, "that"),
        (76, 79, "he perish not."),
    ],
    8: [
        (0, 3, "Wherefore,"),
        (4, 7, "shall be built"),
        (8, 11, "upon"),
        (12, 13, "this land"),
        (14, 17, "the remnant"),
        (18, 22, "of the house of Joseph;"),
        (23, 27, "and shall become"),
        (28, 30, "a land"),
        (31, 34, "of their inheritance;"),
        (35, 40, "and they shall build"),
        (41, 43, "a holy city"),
        (44, 46, "unto the Lord,"),
        (47, 49, "like unto"),
        (50, 52, "the old Jerusalem;"),
        (53, 59, "and shall no more be confounded"),
        (60, 61, "they,"),
        (62, 64, "until cometh"),
        (65, 66, "the end"),
        (67, 70, "when shall pass"),
        (71, 72, "the world."),
    ],
    9: [
        (0, 5, "And there shall be"),
        (6, 8, "a new heaven"),
        (9, 12, "and a new earth;"),
        (13, 17, "and shall be as"),
        (18, 21, "the former heaven"),
        (22, 25, "and the former earth"),
        (26, 27, "except"),
        (28, 30, "the old things"),
        (31, 33, "have passed away,"),
        (34, 36, "and have been renewed"),
        (37, 38, "all things."),
    ],
    10: [
        (0, 0, "And"),
        (1, 5, "then there cometh"),
        (6, 9, "the New Jerusalem;"),
        (10, 14, "and blessed are they"),
        (15, 16, "who"),
        (17, 19, "dwell therein,"),
        (20, 20, "for"),
        (21, 24, "they are the ones"),
        (25, 26, "whose"),
        (27, 31, "garments are made white"),
        (32, 34, "through the blood"),
        (35, 38, "of the Lamb;"),
        (39, 39, "and"),
        (40, 43, "they are the ones"),
        (44, 47, "who are counted"),
        (48, 50, "among"),
        (51, 54, "the remnant"),
        (55, 59, "of the seed of Joseph,"),
        (60, 61, "who are"),
        (62, 66, "of the house of Israel."),
    ],
    11: [
        (0, 4, "And then cometh"),
        (5, 6, "also"),
        (7, 10, "the old Jerusalem;"),
        (11, 13, "and its inhabitants,"),
        (14, 17, "blessed are they,"),
        (18, 22, "for they are made clean"),
        (23, 25, "in the blood"),
        (26, 29, "of the Lamb;"),
        (30, 30, "and"),
        (31, 34, "they are the ones"),
        (35, 38, "who were dispersed"),
        (39, 42, "and were gathered"),
        (43, 46, "from the four quarters"),
        (47, 49, "of the earth,"),
        (50, 52, "and from the countries"),
        (53, 54, "of the north,"),
        (55, 59, "and who partake"),
        (60, 62, "of the fulfilment"),
        (63, 65, "of the covenant"),
        (66, 68, "which made"),
        (69, 71, "God"),
        (72, 75, "with their father,"),
        (76, 77, "even Abraham."),
    ],
    12: [
        (0, 4, "And when come"),
        (5, 6, "these things,"),
        (7, 10, "then is fulfilled"),
        (11, 13, "the scripture"),
        (14, 16, "which saith,"),
        (17, 21, "there are those"),
        (22, 25, "who were first,"),
        (26, 27, "who"),
        (28, 33, "shall become last;"),
        (34, 34, "and"),
        (35, 39, "there are those"),
        (40, 43, "who were last,"),
        (44, 45, "who"),
        (46, 51, "shall become first."),
    ],
    13: [
        (0, 2, "And so it was"),
        (3, 7, "I should write"),
        (8, 12, "many more things,"),
        (13, 13, "nevertheless"),
        (14, 15, "was forbidden"),
        (16, 16, "I;"),
        (17, 17, "but"),
        (18, 22, "great and marvelous were"),
        (23, 25, "the prophecies of Ether;"),
        (26, 29, "but they regarded"),
        (30, 32, "him"),
        (33, 35, "as nought,"),
        (36, 38, "and drove out"),
        (39, 40, "him"),
        (41, 42, "outside;"),
        (43, 47, "and he hid"),
        (48, 50, "in the cavity"),
        (51, 53, "of a rock"),
        (54, 56, "by day,"),
        (57, 60, "and in the night"),
        (61, 65, "he did go forth"),
        (66, 67, "and viewed"),
        (68, 69, "the things"),
        (70, 74, "that should come"),
        (75, 78, "upon the people."),
    ],
    14: [
        (0, 4, "And while he dwelt"),
        (5, 7, "in the cavity"),
        (8, 10, "of a rock"),
        (11, 13, "he did finish"),
        (14, 17, "the remainder"),
        (18, 20, "of this record,"),
        (21, 22, "and beheld"),
        (23, 25, "the destructions"),
        (26, 28, "which came"),
        (29, 32, "upon the people,"),
        (33, 35, "by night."),
    ],
    15: [
        (0, 2, "And it came to pass"),
        (3, 7, "in that same year"),
        (8, 11, "that was cast out"),
        (12, 13, "he"),
        (14, 18, "from among the people,"),
        (19, 22, "there began to be fought"),
        (23, 26, "a great war"),
        (27, 31, "among the people,"),
        (32, 35, "for there were"),
        (36, 39, "many who"),
        (40, 42, "arose,"),
        (43, 44, "who"),
        (45, 48, "were mighty men,"),
        (49, 50, "and sought"),
        (51, 52, "to destroy"),
        (53, 53, "Coriantumr,"),
        (54, 56, "by way of"),
        (57, 60, "their secret designs"),
        (61, 63, "of wickedness,"),
        (64, 66, "which had been"),
        (67, 69, "spoken of."),
    ],
    16: [
        (0, 2, "And now"),
        (3, 4, "Coriantumr,"),
        (5, 6, "was instructed"),
        (7, 8, "himself,"),
        (9, 11, "in all arts"),
        (12, 15, "of warfare"),
        (16, 19, "and all the wisdom"),
        (20, 22, "of the world,"),
        (23, 26, "wherefore"),
        (27, 30, "he did fight"),
        (31, 33, "against them"),
        (34, 37, "who did seek"),
        (38, 41, "to destroy him."),
    ],
    17: [
        (0, 0, "Nevertheless,"),
        (1, 5, "he did not repent,"),
        (6, 10, "nor his goodly sons"),
        (11, 14, "nor his daughters;"),
        (15, 16, "nor"),
        (17, 21, "the fair sons and daughters"),
        (22, 23, "of Cohor;"),
        (24, 25, "nor"),
        (26, 30, "the fair sons and daughters"),
        (31, 32, "of Corihor;"),
        (33, 37, "and in a word,"),
        (38, 39, "there was not"),
        (40, 42, "any sons and"),
        (43, 45, "fair daughters"),
        (46, 49, "upon"),
        (50, 51, "all the land"),
        (52, 55, "who did repent"),
        (56, 59, "of their sins."),
    ],
    18: [
        (0, 3, "Wherefore,"),
        (4, 5, "it happened"),
        (6, 9, "in the first year"),
        (10, 13, "that Ether dwelt"),
        (14, 16, "in the cavity"),
        (17, 19, "of a rock,"),
        (20, 22, "there were"),
        (23, 26, "many people"),
        (27, 28, "who were slain"),
        (29, 31, "by the sword"),
        (32, 34, "of those"),
        (35, 37, "secret combinations,"),
        (38, 41, "who did battle"),
        (42, 45, "against Coriantumr"),
        (46, 49, "that they might obtain"),
        (50, 51, "the kingdom."),
    ],
    19: [
        (0, 3, "And it came to pass that"),
        (4, 6, "greatly did fight"),
        (7, 10, "the sons of Coriantumr"),
        (11, 13, "and much also"),
        (14, 16, "of their blood"),
        (17, 18, "was spilt."),
    ],
    20: [
        (0, 0, "And"),
        (1, 5, "in the second year"),
        (6, 9, "came"),
        (10, 14, "the word of the Lord"),
        (15, 16, "unto Ether,"),
        (17, 19, "that he must"),
        (20, 23, "go forth"),
        (24, 26, "and prophesy"),
        (27, 28, "unto Coriantumr,"),
        (29, 30, "saying,"),
        (31, 35, "if he repent,"),
        (36, 39, "and all his household,"),
        (40, 44, "would grant"),
        (45, 47, "the Lord"),
        (48, 50, "unto him"),
        (51, 52, "his kingdom"),
        (53, 54, "and would spare"),
        (55, 56, "the people—"),
    ],
    21: [
        (0, 1, "But if not,"),
        (2, 5, "should be destroyed"),
        (6, 7, "they,"),
        (8, 11, "and all his household,"),
        (12, 13, "save"),
        (14, 16, "he himself."),
        (17, 17, "And"),
        (18, 23, "he only shall"),
        (24, 25, "live"),
        (26, 27, "to behold"),
        (28, 30, "the fulfilment"),
        (31, 32, "of the prophecies"),
        (33, 39, "which had been declared"),
        (40, 41, "concerning"),
        (42, 45, "another people"),
        (46, 50, "who shall obtain"),
        (51, 52, "the land"),
        (53, 56, "for their inheritance;"),
        (57, 61, "and should be buried"),
        (62, 62, "Coriantumr"),
        (63, 65, "by them;"),
        (66, 70, "and should be destroyed"),
        (71, 72, "all men"),
        (73, 74, "except"),
        (75, 75, "Coriantumr."),
    ],
    22: [
        (0, 3, "And it came to pass that"),
        (4, 5, "repented not"),
        (6, 6, "Coriantumr,"),
        (7, 10, "nor his house,"),
        (11, 14, "nor the people;"),
        (15, 18, "and ceased not"),
        (19, 19, "the wars;"),
        (20, 23, "and they sought"),
        (24, 25, "to kill"),
        (26, 26, "Ether,"),
        (27, 27, "but"),
        (28, 32, "he escaped"),
        (33, 36, "from before them"),
        (37, 39, "and hid again"),
        (40, 42, "in the cavity"),
        (43, 45, "of the rock."),
    ],
    23: [
        (0, 3, "And it came to pass that"),
        (4, 6, "there arose Shared,"),
        (7, 12, "and he also gave battle"),
        (13, 14, "unto Coriantumr;"),
        (15, 18, "and he did defeat"),
        (19, 20, "him,"),
        (21, 23, "so that"),
        (24, 27, "he carried him"),
        (28, 28, "into captivity"),
        (29, 33, "in the third year."),
    ],
    24: [
        (0, 0, "And"),
        (1, 5, "in the fourth year,"),
        (6, 9, "was defeated Shared"),
        (10, 13, "by the sons of Coriantumr,"),
        (14, 17, "and got back"),
        (18, 19, "the kingdom"),
        (20, 23, "for their father."),
    ],
    25: [
        (0, 1, "Now"),
        (2, 5, "there began to be fought"),
        (6, 7, "a war"),
        (8, 11, "upon"),
        (12, 13, "all the land,"),
        (14, 16, "each man"),
        (17, 19, "with his band"),
        (20, 21, "fighting"),
        (22, 23, "for the thing"),
        (24, 28, "which he desired."),
    ],
    26: [
        (0, 3, "And there were"),
        (4, 4, "robbers,"),
        (5, 8, "and in short,"),
        (9, 11, "there existed"),
        (12, 15, "all manner of iniquity"),
        (16, 19, "upon"),
        (20, 21, "all the land."),
    ],
    27: [
        (0, 3, "And it came to pass that"),
        (4, 6, "was exceeding angry"),
        (7, 7, "Coriantumr"),
        (8, 9, "with Shared,"),
        (10, 14, "and he went out"),
        (15, 18, "against him"),
        (19, 21, "with his hosts"),
        (22, 25, "to war with him;"),
        (26, 29, "and they encountered"),
        (30, 33, "with great wrath,"),
        (34, 37, "and they met"),
        (38, 42, "in the valley of Gilgal;"),
        (43, 47, "and was exceeding fierce"),
        (48, 49, "the war."),
    ],
    28: [
        (0, 3, "And it came to pass that"),
        (4, 5, "fought Shared"),
        (6, 7, "against him"),
        (8, 11, "for the space of"),
        (12, 14, "three days."),
        (15, 18, "And it came to pass that"),
        (19, 21, "was defeated he"),
        (22, 23, "by Coriantumr,"),
        (24, 27, "and pursued him"),
        (28, 30, "until came"),
        (31, 35, "to the plains of Heshlon."),
    ],
    29: [
        (0, 3, "And it came to pass that"),
        (4, 6, "again fought Shared"),
        (7, 8, "against him"),
        (9, 11, "upon"),
        (12, 13, "the plains;"),
        (14, 15, "and behold,"),
        (16, 18, "he did defeat"),
        (19, 19, "Coriantumr,"),
        (20, 23, "and again drove"),
        (24, 25, "him"),
        (26, 27, "backward"),
        (28, 32, "to the valley of Gilgal."),
    ],
    30: [
        (0, 3, "And again fought"),
        (4, 4, "Coriantumr"),
        (5, 6, "with Shared"),
        (7, 11, "in the valley of Gilgal,"),
        (12, 16, "wherein he overthrew"),
        (17, 17, "Shared"),
        (18, 21, "and killed him."),
    ],
    31: [
        (0, 4, "And Shared wounded"),
        (5, 6, "Coriantumr"),
        (7, 9, "in his thigh,"),
        (10, 10, "wherefore"),
        (11, 16, "went no more forth"),
        (17, 18, "he"),
        (19, 20, "to fight"),
        (21, 24, "for the space of"),
        (25, 27, "two years,"),
        (28, 31, "during which time"),
        (32, 34, "did commit"),
        (35, 37, "by all men"),
        (38, 39, "who were"),
        (40, 43, "upon the land"),
        (44, 45, "the shedding"),
        (46, 48, "of blood,"),
        (49, 53, "and there was no one"),
        (54, 55, "to stop"),
        (56, 57, "them."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
