"""
Hand-curated TAM-phrase gloss overrides for 3 Nifae (3 Nephi) 3 — Giddianhi, the
governor of the Gadianton robbers, sends a proud, flattering epistle to Lachoneus
demanding the Nephites yield up their lands or be destroyed; Lachoneus, a just
man, is not frightened but appoints Gidgiddoni chief captain, gathers the people
and their flocks into one place, fortifies with breastworks, and calls the people
to repentance and to trust in God for deliverance rather than to go out against
the robbers.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-split applied to bom_books.json before glossing:
    3:3  upu—O  ->  upu—  +  O

    python3 build_overrides_3nephi3.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "3nephi"
CHAPTER_NUM = 3

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 4, "it came to pass"),
        (5, 8, "in the year"),
        (9, 12, "sixteenth"),
        (13, 16, "from the time of"),
        (17, 21, "the coming of Christ,"),
        (22, 24, "received"),
        (25, 26, "Lachoneus,"),
        (27, 31, "the governor of the land,"),
        (32, 33, "an epistle"),
        (34, 36, "from the leader"),
        (37, 39, "and the governor of"),
        (40, 44, "this band of robbers;"),
        (45, 48, "and these are the words"),
        (49, 50, "which were written,"),
        (51, 52, "saying:"),
    ],
    2: [
        (0, 3, "Your noble excellency"),
        (4, 4, "Lachoneus,"),
        (5, 9, "and chief governor of"),
        (10, 11, "the land,"),
        (12, 12, "behold,"),
        (13, 16, "I write"),
        (17, 18, "this epistle"),
        (19, 21, "unto you,"),
        (22, 23, "and give"),
        (24, 26, "unto you"),
        (27, 29, "great praise"),
        (30, 31, "because of"),
        (32, 33, "your firmness,"),
        (34, 38, "and also the firmness of"),
        (39, 40, "your people,"),
        (41, 45, "in your keeping"),
        (46, 48, "the thing"),
        (49, 51, "which ye suppose"),
        (52, 55, "to be your right"),
        (56, 59, "and your liberty;"),
        (60, 60, "yea,"),
        (61, 64, "ye do stand well,"),
        (65, 66, "as if"),
        (67, 69, "ye were supported"),
        (70, 72, "by the hand of"),
        (73, 75, "a god,"),
        (76, 79, "in the defence of"),
        (80, 82, "your liberty,"),
        (83, 86, "and your property,"),
        (87, 90, "and your country,"),
        (91, 93, "or the things"),
        (94, 98, "which ye so call."),
    ],
    3: [
        (0, 3, "And it appears"),
        (4, 10, "a thing I pity,"),
        (11, 13, "your noble excellency"),
        (14, 15, "O Lachoneus,"),
        (16, 16, "for"),
        (17, 21, "ye are exceedingly foolish"),
        (22, 23, "and vain"),
        (24, 26, "in your thinking"),
        (27, 31, "ye can stand"),
        (32, 34, "against"),
        (35, 40, "the very many brave men"),
        (41, 45, "who are"),
        (46, 48, "at my command,"),
        (49, 54, "who now stand"),
        (55, 58, "at this time"),
        (59, 62, "with their weapons,"),
        (63, 66, "and await"),
        (67, 70, "with great eagerness"),
        (71, 73, "for the word—"),
        (74, 79, "Go down upon"),
        (80, 81, "the Nephites"),
        (82, 85, "and destroy them."),
    ],
    4: [
        (0, 2, "And I,"),
        (3, 6, "in my knowing of"),
        (7, 11, "their unconquerable spirit,"),
        (12, 17, "for I have proved them"),
        (18, 22, "in the field of battle,"),
        (23, 27, "and in my knowing of"),
        (28, 32, "their everlasting anger"),
        (33, 35, "towards you"),
        (36, 37, "because of"),
        (38, 41, "the many wrongs"),
        (42, 44, "which ye did"),
        (45, 48, "unto them,"),
        (49, 50, "therefore"),
        (51, 55, "if they come down"),
        (56, 60, "against you,"),
        (61, 66, "they would visit you"),
        (67, 70, "with utter destruction."),
    ],
    5: [
        (0, 1, "Therefore"),
        (2, 5, "I have written"),
        (6, 7, "this epistle,"),
        (8, 9, "and sealing it"),
        (10, 13, "with mine own hand,"),
        (14, 16, "and caring"),
        (17, 20, "for your welfare,"),
        (21, 22, "because of"),
        (23, 25, "your steadfastness"),
        (26, 28, "in the thing"),
        (29, 33, "which ye believe is right,"),
        (34, 38, "and your brave spirit"),
        (39, 43, "in the field of battle."),
    ],
    6: [
        (0, 1, "Therefore"),
        (2, 6, "I write"),
        (7, 9, "unto you,"),
        (10, 12, "I desire"),
        (13, 16, "that ye yield up"),
        (17, 20, "unto this my people,"),
        (21, 23, "your cities,"),
        (24, 27, "and your lands,"),
        (28, 31, "and your possessions,"),
        (32, 35, "otherwise"),
        (36, 41, "they would visit"),
        (42, 44, "you"),
        (45, 47, "with the sword"),
        (48, 55, "and thus would come"),
        (56, 57, "destruction"),
        (58, 61, "upon you."),
    ],
    7: [
        (0, 3, "Like another wording,"),
        (4, 9, "yield up yourselves"),
        (10, 13, "unto us,"),
        (14, 15, "and unite"),
        (16, 18, "with us"),
        (19, 20, "and be acquainted"),
        (21, 25, "with our secret works,"),
        (26, 28, "and become"),
        (29, 31, "our brethren"),
        (32, 37, "that ye may become"),
        (38, 41, "like unto us—"),
        (42, 48, "not our slaves,"),
        (49, 53, "but our brethren"),
        (54, 55, "and partners"),
        (56, 59, "in all our things."),
    ],
    8: [
        (0, 1, "And behold,"),
        (2, 5, "I swear"),
        (6, 8, "unto you,"),
        (9, 12, "if ye do"),
        (13, 14, "this thing,"),
        (15, 17, "with an oath,"),
        (18, 23, "ye shall not be destroyed;"),
        (24, 29, "but if ye do not"),
        (30, 31, "this thing,"),
        (32, 35, "I swear"),
        (36, 37, "unto you"),
        (38, 40, "with an oath,"),
        (41, 45, "the coming month"),
        (46, 51, "I will command"),
        (52, 56, "that go down"),
        (57, 58, "my armies"),
        (59, 63, "against you,"),
        (64, 70, "and they shall not withhold"),
        (71, 73, "their hand"),
        (74, 80, "and there shall be none"),
        (81, 83, "of you"),
        (84, 85, "to be spared,"),
        (86, 92, "but they shall slay you,"),
        (93, 98, "and they shall let fall"),
        (99, 100, "the sword"),
        (101, 106, "upon you"),
        (107, 111, "until ye be wiped out."),
    ],
    9: [
        (0, 1, "And behold,"),
        (2, 5, "I am Giddianhi,"),
        (6, 11, "and I am the governor of"),
        (12, 16, "this secret society of"),
        (17, 17, "Gadianton;"),
        (18, 21, "which society"),
        (22, 24, "and its works"),
        (25, 29, "I know are good;"),
        (30, 33, "and these things"),
        (34, 36, "are from of old"),
        (37, 41, "and were handed down"),
        (42, 45, "unto us."),
    ],
    10: [
        (0, 4, "And I write"),
        (5, 6, "this epistle"),
        (7, 9, "unto you,"),
        (10, 10, "Lachoneus,"),
        (11, 14, "and I hope"),
        (15, 20, "ye will yield up"),
        (21, 23, "your lands"),
        (24, 28, "and things ye possess,"),
        (29, 31, "without"),
        (32, 36, "the shedding of blood,"),
        (37, 40, "that may"),
        (41, 44, "this my people,"),
        (45, 49, "who dissented away"),
        (50, 52, "from you"),
        (53, 54, "because of"),
        (55, 57, "your wickedness"),
        (58, 65, "in withholding from them"),
        (66, 72, "their rights of government,"),
        (73, 75, "may recover"),
        (76, 81, "their rights and the government,"),
        (82, 82, "and"),
        (83, 85, "except"),
        (86, 90, "ye do this thing,"),
        (91, 95, "I will avenge"),
        (96, 99, "the wrongs ye did"),
        (100, 103, "unto them."),
        (104, 107, "I am Giddianhi."),
    ],
    11: [
        (0, 2, "Now"),
        (3, 5, "it came to pass that"),
        (6, 9, "when Lachoneus received"),
        (10, 11, "this epistle"),
        (12, 17, "he was exceedingly astonished,"),
        (18, 19, "because of"),
        (20, 23, "the boldness of Giddianhi"),
        (24, 27, "in demanding"),
        (28, 33, "that be given to him"),
        (34, 35, "the rule"),
        (36, 41, "over the land of the Nephites,"),
        (42, 47, "and also in threatening"),
        (48, 50, "the people"),
        (51, 55, "and avenging the wrongs of"),
        (56, 59, "those who"),
        (60, 67, "had no wrong done to them,"),
        (68, 69, "except"),
        (70, 73, "their own wrong"),
        (74, 77, "in their dissenting"),
        (78, 82, "and went to unite"),
        (83, 86, "with those wicked robbers"),
        (87, 90, "and doing abominations."),
    ],
    12: [
        (0, 2, "Now behold,"),
        (3, 5, "this Lachoneus,"),
        (6, 8, "the governor,"),
        (9, 14, "was a righteous man,"),
        (15, 20, "and could not be frightened"),
        (21, 23, "by demands"),
        (24, 27, "and threatenings of"),
        (28, 29, "a robber;"),
        (30, 31, "therefore"),
        (32, 37, "he did not hearken"),
        (38, 42, "to the epistle of Giddianhi,"),
        (43, 48, "the governor of the robbers,"),
        (49, 53, "but he commanded"),
        (54, 56, "his people"),
        (57, 61, "that they cry"),
        (62, 64, "unto the Lord"),
        (65, 67, "for strength"),
        (68, 70, "against the time"),
        (71, 74, "when should come down"),
        (75, 77, "the robbers"),
        (78, 81, "to attack them."),
    ],
    13: [
        (0, 0, "Yea,"),
        (1, 4, "he sent forth"),
        (5, 6, "a proclamation"),
        (7, 9, "among all the people,"),
        (10, 15, "that they gather together"),
        (16, 18, "their women,"),
        (19, 22, "and their children,"),
        (23, 26, "and their flocks"),
        (27, 30, "and their herds,"),
        (31, 35, "and all their substance,"),
        (36, 37, "except"),
        (38, 40, "their land,"),
        (41, 45, "unto one place."),
    ],
    14: [
        (0, 4, "And he commanded"),
        (5, 8, "that be built"),
        (9, 11, "fortifications round about"),
        (12, 15, "them,"),
        (16, 20, "and be exceedingly strong"),
        (21, 22, "those forts."),
        (23, 27, "And he commanded"),
        (28, 30, "that be placed round about"),
        (31, 31, "armies,"),
        (32, 34, "both the Nephites"),
        (35, 38, "and all the Lamanites,"),
        (39, 45, "or all their armies"),
        (46, 50, "who were numbered together"),
        (51, 56, "among the Nephite people,"),
        (57, 59, "as guards"),
        (60, 63, "to watch them,"),
        (64, 67, "and to protect them"),
        (68, 71, "from the robbers"),
        (72, 77, "in the day and the night."),
    ],
    15: [
        (0, 0, "Yea,"),
        (1, 4, "he said"),
        (5, 8, "unto them:"),
        (9, 12, "As liveth"),
        (13, 14, "the Lord,"),
        (15, 16, "except"),
        (17, 19, "ye repent"),
        (20, 23, "of all your iniquities,"),
        (24, 26, "and cry"),
        (27, 29, "unto the Lord,"),
        (30, 33, "there is no way"),
        (34, 41, "ye can be delivered"),
        (42, 44, "out of the hands of"),
        (45, 48, "those robbers of Gadianton."),
    ],
    16: [
        (0, 3, "And so exceedingly great"),
        (4, 5, "and marvelous"),
        (6, 9, "the words and prophecies of"),
        (10, 10, "Lachoneus"),
        (11, 13, "insomuch that"),
        (14, 18, "fear came"),
        (19, 23, "upon all the people;"),
        (24, 27, "and they strove"),
        (28, 31, "with their might"),
        (32, 33, "to do"),
        (34, 36, "according to"),
        (37, 39, "the words of Lachoneus."),
    ],
    17: [
        (0, 3, "And it came to pass that"),
        (4, 6, "Lachoneus appointed"),
        (7, 9, "chief captains"),
        (10, 15, "over all the armies of"),
        (16, 17, "the Nephites,"),
        (18, 21, "to command them"),
        (22, 24, "at the time"),
        (25, 28, "when should come down"),
        (29, 31, "out of the wilderness"),
        (32, 34, "the robbers"),
        (35, 41, "against them."),
    ],
    18: [
        (0, 1, "Now"),
        (2, 4, "was appointed"),
        (5, 7, "a chiefest captain"),
        (8, 12, "and a great commander"),
        (13, 15, "from among"),
        (16, 19, "all the chief captains of"),
        (20, 24, "all the armies of the Nephites,"),
        (25, 30, "and his name was Gidgiddoni."),
    ],
    19: [
        (0, 1, "Now"),
        (2, 8, "it was a custom"),
        (9, 15, "among all the Nephite people"),
        (16, 19, "to appoint to be"),
        (20, 24, "for their chief captains"),
        (25, 26, "(except"),
        (27, 31, "in their times of wickedness)"),
        (32, 33, "someone"),
        (34, 36, "who had"),
        (37, 40, "the spirit of revelation"),
        (41, 45, "and the spirit of prophecy;"),
        (46, 47, "therefore,"),
        (48, 52, "this man Gidgiddoni"),
        (53, 58, "was a great prophet"),
        (59, 64, "among them,"),
        (65, 69, "and was also"),
        (70, 71, "the chief judge."),
    ],
    20: [
        (0, 1, "Now"),
        (2, 6, "the people said"),
        (7, 8, "unto Gidgiddoni:"),
        (9, 12, "Pray"),
        (13, 15, "unto the Lord,"),
        (16, 21, "and let us go up"),
        (22, 25, "upon the mountains"),
        (26, 30, "and into the wilderness,"),
        (31, 36, "that we may attack"),
        (37, 40, "the robbers"),
        (41, 44, "and destroy them"),
        (45, 49, "in their own lands."),
    ],
    21: [
        (0, 0, "But"),
        (1, 4, "Gidgiddoni said"),
        (5, 8, "unto them:"),
        (9, 13, "The Lord hath forbidden"),
        (14, 15, "this thing;"),
        (16, 16, "for"),
        (17, 21, "if we go up"),
        (22, 23, "to battle"),
        (24, 27, "against them,"),
        (28, 34, "would deliver us"),
        (35, 37, "the Lord"),
        (38, 41, "into their hands;"),
        (42, 43, "therefore"),
        (44, 49, "we will prepare"),
        (50, 52, "ourselves"),
        (53, 56, "in the centre of"),
        (57, 59, "our lands,"),
        (60, 66, "and we will gather together"),
        (67, 70, "all our armies,"),
        (71, 78, "and we will not go"),
        (79, 80, "to battle"),
        (81, 84, "against them,"),
        (85, 90, "but we will wait"),
        (91, 94, "until they come"),
        (95, 101, "against us;"),
        (102, 103, "therefore"),
        (104, 107, "as liveth"),
        (108, 109, "the Lord,"),
        (110, 113, "if we do"),
        (114, 115, "this thing,"),
        (116, 123, "he will deliver them"),
        (124, 127, "into our hands."),
    ],
    22: [
        (0, 2, "And it came to pass"),
        (3, 9, "in the seventeenth"),
        (10, 11, "year,"),
        (12, 15, "in the latter end of"),
        (16, 17, "the year,"),
        (18, 21, "had gone forth"),
        (22, 25, "the proclamation of Lachoneus"),
        (26, 31, "throughout all the land,"),
        (32, 35, "and they took"),
        (36, 38, "their horses,"),
        (39, 42, "and their chariots,"),
        (43, 46, "and their cattle,"),
        (47, 51, "and all their flocks,"),
        (52, 55, "and their herds,"),
        (56, 59, "and their grain,"),
        (60, 64, "and all their substance,"),
        (65, 67, "and marched forth"),
        (68, 68, "by thousands"),
        (69, 71, "and by tens of thousands,"),
        (72, 74, "until"),
        (75, 78, "they all went forth"),
        (79, 82, "to that place"),
        (83, 84, "which was appointed"),
        (85, 92, "that they gather together"),
        (93, 95, "themselves,"),
        (96, 101, "to defend themselves"),
        (102, 105, "from their enemies."),
    ],
    23: [
        (0, 3, "And the land"),
        (4, 5, "which was appointed"),
        (6, 11, "was the land of Zarahemla,"),
        (12, 15, "and the land which"),
        (16, 20, "was between"),
        (21, 24, "the land of Zarahemla"),
        (25, 29, "and the land of Bountiful,"),
        (30, 30, "yea,"),
        (31, 34, "reaching to"),
        (35, 37, "the boundary line"),
        (38, 42, "which was between"),
        (43, 46, "the land of Bountiful"),
        (47, 51, "and the land of Desolation."),
    ],
    24: [
        (0, 3, "And there were"),
        (4, 9, "a great many thousand people"),
        (10, 15, "who were called"),
        (16, 18, "Nephites,"),
        (19, 24, "who gathered together"),
        (25, 27, "themselves"),
        (28, 30, "in this land."),
        (31, 32, "Now"),
        (33, 36, "Lachoneus commanded"),
        (37, 42, "that they gather together"),
        (43, 45, "themselves"),
        (46, 50, "in the land southward,"),
        (51, 52, "because of"),
        (53, 56, "the great curse which"),
        (57, 59, "was"),
        (60, 64, "upon the land northward."),
    ],
    25: [
        (0, 4, "And they fortified strongly"),
        (5, 7, "themselves"),
        (8, 10, "to resist"),
        (11, 14, "against their enemies;"),
        (15, 18, "and they dwelt"),
        (19, 23, "in one land,"),
        (24, 29, "and in one body,"),
        (30, 33, "and they feared"),
        (34, 35, "the words"),
        (36, 39, "spoken by Lachoneus,"),
        (40, 42, "insomuch that"),
        (43, 44, "they repented"),
        (45, 48, "of all their sins;"),
        (49, 53, "and they offered up"),
        (54, 56, "their prayers"),
        (57, 62, "unto the Lord their God,"),
        (63, 68, "that he would deliver them"),
        (69, 71, "in the time"),
        (72, 75, "when should come down"),
        (76, 78, "their enemies"),
        (79, 85, "against them"),
        (86, 88, "to battle."),
    ],
    26: [
        (0, 5, "And they were exceedingly sorrowful"),
        (6, 7, "because of"),
        (8, 10, "their enemies."),
        (11, 15, "And Gidgiddoni commanded"),
        (16, 20, "that they make"),
        (21, 25, "weapons of every kind of war,"),
        (26, 30, "and that they be strengthened"),
        (31, 32, "with armor,"),
        (33, 34, "and with shields,"),
        (35, 36, "and with bucklers,"),
        (37, 39, "according to"),
        (40, 41, "his instructions."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
