"""Hand-curated TAM-phrase gloss overrides for 1 Nifae 8 — Lehi's vision of the Tree of Life."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "1nephi"
CHAPTER_NUM = 8
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass"),
        (4, 6, "we had gathered together"),
        (7, 11, "all manner of seeds of every kind,"),
        (12, 16, "both grain and seed of every kind,"),
        (17, 22, "and also seeds of fruit"),
        (23, 25, "of every kind."),
    ],
    2: [
        (0, 3, "And it came to pass"),
        (4, 7, "as dwelt my father"),
        (8, 10, "in the wilderness,"),
        (11, 15, "he spake"),
        (16, 19, "unto us,"),
        (20, 21, "saying:"),
        (22, 22, "Behold,"),
        (23, 27, "I have dreamed a dream;"),
        (28, 28, "or,"),
        (29, 32, "in other words,"),
        (33, 38, "I have seen a vision."),
    ],
    3: [
        (0, 1, "And behold,"),
        (2, 5, "because of the thing"),
        (6, 10, "which I have seen,"),
        (11, 14, "I have"),
        (15, 16, "reason"),
        (17, 20, "to rejoice"),
        (21, 23, "in the Lord"),
        (24, 26, "because of Nephi"),
        (27, 29, "and also Sam;"),
        (30, 30, "because"),
        (31, 34, "I have"),
        (35, 36, "reason"),
        (37, 40, "to suppose"),
        (41, 43, "that they,"),
        (44, 46, "and many"),
        (47, 50, "of their seed,"),
        (51, 54, "will be saved."),
    ],
    4: [
        (0, 1, "But behold,"),
        (2, 4, "Laman and Lemuel,"),
        (5, 8, "I fear exceedingly"),
        (9, 11, "because of you;"),
        (12, 13, "for behold,"),
        (14, 16, "I have remembered"),
        (17, 19, "I beheld"),
        (20, 22, "in my dream,"),
        (23, 25, "a dark and dreary wilderness"),
        (26, 28, "and dreary."),
    ],
    5: [
        (0, 3, "And it came to pass"),
        (4, 5, "I saw"),
        (6, 8, "a man,"),
        (9, 13, "and he was dressed"),
        (14, 18, "in a white robe;"),
        (19, 24, "and he came"),
        (25, 26, "and stood"),
        (27, 29, "before me."),
    ],
    6: [
        (0, 3, "And it came to pass"),
        (4, 7, "he spake"),
        (8, 10, "unto me,"),
        (11, 12, "and bade"),
        (13, 16, "me follow"),
        (17, 19, "him."),
    ],
    7: [
        (0, 3, "And it came to pass"),
        (4, 7, "as I followed"),
        (8, 10, "him"),
        (11, 13, "I beheld"),
        (14, 17, "myself"),
        (18, 21, "I was in"),
        (22, 25, "the midst of"),
        (26, 27, "a dark waste"),
        (28, 29, "and dreary."),
    ],
    8: [
        (0, 4, "And after"),
        (5, 7, "I had traveled"),
        (8, 9, "for"),
        (10, 11, "many hours"),
        (12, 14, "in darkness,"),
        (15, 17, "I began"),
        (18, 20, "to pray"),
        (21, 23, "unto the Lord"),
        (24, 27, "that he would have mercy"),
        (28, 30, "on me,"),
        (31, 34, "according to"),
        (35, 36, "the multitude"),
        (37, 38, "of his"),
        (39, 40, "tender mercies."),
    ],
    9: [
        (0, 3, "And it came to pass"),
        (4, 6, "after"),
        (7, 9, "I had prayed"),
        (10, 12, "unto the Lord,"),
        (13, 15, "I beheld"),
        (16, 17, "a field"),
        (18, 21, "a large and spacious one."),
    ],
    10: [
        (0, 3, "And it came to pass"),
        (4, 5, "I beheld"),
        (6, 7, "a tree,"),
        (8, 10, "whose fruit"),
        (11, 13, "was desirable"),
        (14, 16, "to make"),
        (17, 19, "one"),
        (20, 21, "happy."),
    ],
    11: [
        (0, 3, "And it came to pass"),
        (4, 8, "I went and partook"),
        (9, 11, "of the fruit thereof;"),
        (12, 15, "and I beheld"),
        (16, 19, "was most sweet"),
        (20, 24, "above all"),
        (25, 30, "I had ever before tasted."),
        (31, 31, "Yea,"),
        (32, 35, "and I beheld"),
        (36, 41, "the fruit of the tree"),
        (42, 43, "was white,"),
        (44, 46, "and did exceed"),
        (47, 51, "all the whiteness"),
        (52, 56, "I had ever seen."),
    ],
    12: [
        (0, 3, "And as I did partake of"),
        (4, 5, "the fruit"),
        (6, 8, "of the tree,"),
        (9, 12, "it filled my soul"),
        (13, 16, "with exceedingly great joy;"),
        (17, 20, "wherefore,"),
        (21, 26, "I began to be desirous"),
        (27, 30, "should partake of it also"),
        (31, 32, "my family;"),
        (33, 36, "for I knew"),
        (37, 41, "was desirable"),
        (42, 46, "above all other fruits."),
    ],
    13: [
        (0, 2, "And as I"),
        (3, 5, "cast my eyes round about,"),
        (6, 7, "perhaps"),
        (8, 11, "I might"),
        (12, 14, "discover also"),
        (15, 16, "my family,"),
        (17, 21, "I beheld a river"),
        (22, 25, "and it ran along,"),
        (26, 28, "and it was near"),
        (29, 31, "the tree"),
        (32, 35, "of which I was partaking"),
        (36, 37, "the fruit thereof."),
    ],
    14: [
        (0, 3, "And I looked"),
        (4, 6, "to see"),
        (7, 9, "from whence"),
        (10, 13, "it flowed;"),
        (14, 17, "and I beheld"),
        (18, 20, "the head thereof"),
        (21, 24, "a little way off;"),
        (25, 28, "and at the head thereof"),
        (29, 32, "I beheld"),
        (33, 35, "your mother,"),
        (36, 37, "Sariah,"),
        (38, 39, "and Sam,"),
        (40, 41, "and Nephi;"),
        (42, 46, "and they stood"),
        (47, 48, "as if"),
        (49, 52, "they knew not"),
        (53, 54, "the place"),
        (55, 61, "whither they should go."),
    ],
    15: [
        (0, 3, "And it came to pass"),
        (4, 6, "I beckoned"),
        (7, 10, "unto them;"),
        (11, 16, "and I also said"),
        (17, 20, "unto them"),
        (21, 24, "with a loud voice"),
        (25, 28, "that they should come"),
        (29, 31, "unto me,"),
        (32, 33, "and partake"),
        (34, 36, "of the fruit,"),
        (37, 40, "which was desirable"),
        (41, 46, "above all other fruit."),
    ],
    16: [
        (0, 3, "And it came to pass"),
        (4, 6, "they did come"),
        (7, 9, "unto me"),
        (10, 12, "and partake also"),
        (13, 15, "of the fruit."),
    ],
    17: [
        (0, 3, "And it came to pass"),
        (4, 5, "I was desirous"),
        (6, 9, "that Laman and Lemuel"),
        (10, 15, "should come and partake also"),
        (16, 18, "of the fruit;"),
        (19, 22, "wherefore,"),
        (23, 27, "I cast my eyes"),
        (28, 33, "towards the head of the river,"),
        (34, 36, "that perhaps"),
        (37, 40, "I might see"),
        (41, 42, "them."),
    ],
    18: [
        (0, 3, "And it came to pass"),
        (4, 6, "I saw"),
        (7, 10, "them,"),
        (11, 17, "but they would not come"),
        (18, 20, "unto me"),
        (21, 22, "and partake"),
        (23, 25, "of the fruit."),
    ],
    19: [
        (0, 3, "And I beheld"),
        (4, 7, "a rod of iron,"),
        (8, 12, "and it extended along"),
        (13, 18, "the bank of the river,"),
        (19, 22, "and led"),
        (23, 25, "to the tree"),
        (26, 29, "by which I stood"),
        (30, 33, "beside it."),
    ],
    20: [
        (0, 4, "And I also beheld"),
        (5, 8, "a strait"),
        (9, 11, "and narrow path,"),
        (12, 14, "which came along"),
        (15, 19, "by the rod of iron,"),
        (20, 23, "even unto"),
        (24, 26, "the tree"),
        (27, 30, "by which I stood"),
        (31, 34, "beside it;"),
        (35, 39, "and it also led"),
        (40, 47, "by the head of the fountain,"),
        (48, 54, "unto a large and spacious field,"),
        (55, 59, "as if it had been a world."),
    ],
    21: [
        (0, 3, "And I saw"),
        (4, 10, "numberless concourses of people,"),
        (11, 16, "many of whom"),
        (17, 21, "were pressing forward,"),
        (22, 25, "that they might obtain"),
        (26, 27, "the path"),
        (28, 33, "which led unto the tree"),
        (34, 37, "by which I stood"),
        (38, 41, "beside it."),
    ],
    22: [
        (0, 3, "And it came to pass"),
        (4, 8, "they did come"),
        (9, 12, "and commence walking"),
        (13, 15, "in the path"),
        (16, 21, "which led to the tree."),
    ],
    23: [
        (0, 3, "And it came to pass"),
        (4, 5, "arose"),
        (6, 10, "a mist of darkness;"),
        (11, 11, "yea,"),
        (12, 19, "even an exceedingly great mist of darkness,"),
        (20, 28, "insomuch that they were lost"),
        (29, 34, "they who had commenced walking"),
        (35, 37, "in the path,"),
        (38, 40, "their way,"),
        (41, 44, "and they did wander off"),
        (45, 47, "and were lost."),
    ],
    24: [
        (0, 3, "And it came to pass"),
        (4, 5, "I beheld"),
        (6, 12, "others pressing forward,"),
        (13, 19, "and they came and caught hold"),
        (20, 26, "of the end of the rod of iron;"),
        (27, 33, "and they did press forward"),
        (34, 36, "through"),
        (37, 39, "the mist"),
        (40, 42, "of darkness,"),
        (43, 48, "clinging to the rod of iron,"),
        (49, 55, "even until they came"),
        (56, 60, "and partook of the fruit"),
        (61, 63, "of the tree."),
    ],
    25: [
        (0, 4, "And after"),
        (5, 6, "they had partaken"),
        (7, 12, "of the fruit of the tree"),
        (13, 18, "they did cast their eyes about"),
        (19, 20, "as if"),
        (21, 23, "they were ashamed."),
    ],
    26: [
        (0, 4, "And I also cast"),
        (5, 6, "my eyes,"),
        (7, 10, "and saw,"),
        (11, 14, "on the other side"),
        (15, 17, "of the river,"),
        (18, 23, "a great and spacious building;"),
        (24, 27, "and it stood"),
        (28, 29, "as if"),
        (30, 34, "it stood in the air,"),
        (35, 41, "high above the earth."),
    ],
    27: [
        (0, 4, "And it was filled with people,"),
        (5, 7, "both old"),
        (8, 10, "and young,"),
        (11, 15, "both male and female;"),
        (16, 21, "and their manner of dress"),
        (22, 25, "was exceedingly fine;"),
        (26, 31, "and they were in the attitude of mocking"),
        (32, 37, "and pointing their fingers"),
        (38, 42, "towards those who"),
        (43, 47, "had come and partook of the fruit."),
    ],
    28: [
        (0, 4, "And after"),
        (5, 9, "they had tasted of the fruit"),
        (10, 12, "they were ashamed,"),
        (13, 14, "because of"),
        (15, 16, "those"),
        (17, 21, "who were scoffing"),
        (22, 25, "at them;"),
        (26, 32, "and they fell away"),
        (33, 35, "into forbidden paths"),
        (36, 38, "and were lost."),
    ],
    29: [
        (0, 2, "And now,"),
        (3, 4, "I"),
        (5, 6, "Nephi,"),
        (7, 11, "do not speak"),
        (12, 13, "all the words"),
        (14, 16, "of my father."),
    ],
    30: [
        (0, 0, "But,"),
        (1, 4, "to be short in writing,"),
        (5, 5, "behold,"),
        (6, 9, "he saw"),
        (10, 14, "other multitudes of people"),
        (15, 19, "pressing forward;"),
        (20, 24, "and they came"),
        (25, 26, "and caught hold"),
        (27, 33, "of the end of the rod of iron;"),
        (34, 40, "and they did press forward"),
        (41, 44, "in their path,"),
        (45, 47, "and pressed on"),
        (48, 51, "the rod of iron,"),
        (52, 59, "until they came"),
        (60, 63, "and fell down"),
        (64, 65, "and partook"),
        (66, 68, "of the fruit"),
        (69, 71, "of the tree."),
    ],
    31: [
        (0, 5, "And he also saw"),
        (6, 10, "other multitudes of people"),
        (11, 16, "feeling their way"),
        (17, 18, "towards"),
        (19, 24, "that great and spacious building."),
    ],
    32: [
        (0, 3, "And it came to pass"),
        (4, 6, "were drowned many"),
        (7, 12, "in the depths of the fountain;"),
        (13, 15, "and many were"),
        (16, 22, "lost from his view,"),
        (23, 24, "wandering"),
        (25, 27, "in strange roads."),
    ],
    33: [
        (0, 6, "And there were many multitudes of people"),
        (7, 9, "who did enter"),
        (10, 14, "into that"),
        (15, 16, "strange building."),
        (17, 21, "And after"),
        (22, 24, "they did enter"),
        (25, 29, "into that building"),
        (30, 33, "they did point"),
        (34, 38, "the finger of mocking"),
        (39, 41, "at me"),
        (42, 49, "and also those who were partaking"),
        (50, 55, "of the fruit of the tree;"),
        (56, 60, "but we heeded not"),
        (61, 62, "them."),
    ],
    34: [
        (0, 5, "These are the words of my father:"),
        (6, 11, "For as many as"),
        (12, 15, "heeded them,"),
        (16, 18, "fell away."),
    ],
    35: [
        (0, 1, "And"),
        (2, 4, "Laman and Lemuel,"),
        (5, 7, "partook not"),
        (8, 10, "of the fruit,"),
        (11, 14, "said"),
        (15, 16, "my father."),
    ],
    36: [
        (0, 3, "And it came to pass"),
        (4, 6, "after had spoken"),
        (7, 11, "my father"),
        (12, 16, "all the words of his dream"),
        (17, 21, "or, in other words, vision,"),
        (22, 26, "which were many,"),
        (27, 31, "he said"),
        (32, 35, "unto us,"),
        (36, 39, "because of these things"),
        (40, 45, "which he saw"),
        (46, 49, "in a vision,"),
        (50, 55, "he greatly feared"),
        (56, 58, "concerning"),
        (59, 61, "Laman and Lemuel;"),
        (62, 62, "yea,"),
        (63, 66, "he feared"),
        (67, 71, "lest they should be cast off"),
        (72, 76, "from the presence of the Lord."),
    ],
    37: [
        (0, 5, "And he did exhort"),
        (6, 9, "them"),
        (10, 13, "at that time"),
        (14, 20, "with all the feeling of a tender parent,"),
        (21, 24, "that they would hearken"),
        (25, 27, "to his words,"),
        (28, 28, "perhaps"),
        (29, 34, "would be merciful the Lord"),
        (35, 38, "unto them,"),
        (39, 43, "and not cast off"),
        (44, 45, "them;"),
        (46, 46, "yea,"),
        (47, 51, "did exhort my father"),
        (52, 55, "them."),
    ],
    38: [
        (0, 4, "And after"),
        (5, 8, "had preached"),
        (9, 12, "unto them,"),
        (13, 16, "and prophesied also"),
        (17, 20, "unto them"),
        (21, 24, "many things,"),
        (25, 29, "he commanded them"),
        (30, 31, "that they should obey"),
        (32, 36, "the commandments of the Lord;"),
        (37, 41, "and finished he"),
        (42, 44, "speaking"),
        (45, 48, "unto them."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
