"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 57 — the continuation
of Helaman's epistle to Moroni: the taking of Antiparah, Cumeni, and Manti; the
night victories, the surrender of Lamanite prisoners, and again the miraculous
preservation of the two thousand and sixty stripling warriors, not one of whom
is slain though all are wounded.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_alma57.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 57

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now,"),
        (3, 5, "it came to pass that"),
        (6, 7, "I received"),
        (8, 9, "an epistle"),
        (10, 12, "from Ammoron,"),
        (13, 14, "the king,"),
        (15, 16, "saying"),
        (17, 18, "thus"),
        (19, 19, "if"),
        (20, 23, "I deliver up"),
        (24, 25, "those prisoners"),
        (26, 28, "of war"),
        (29, 33, "whom we had taken,"),
        (34, 39, "he would deliver up"),
        (40, 42, "the city of"),
        (43, 43, "Antiparah"),
        (44, 47, "unto us."),
    ],
    2: [
        (0, 0, "But"),
        (1, 4, "I sent"),
        (5, 6, "an epistle"),
        (7, 9, "unto the king,"),
        (10, 12, "that we were sure"),
        (13, 14, "were enough"),
        (15, 17, "our armies"),
        (18, 21, "to take by force"),
        (22, 24, "the city of"),
        (25, 25, "Antiparah;"),
        (26, 31, "and the delivering up of"),
        (32, 32, "prisoners"),
        (33, 35, "for that city"),
        (36, 38, "we would think"),
        (39, 42, "ourselves"),
        (43, 48, "it is not a wise thing,"),
        (49, 51, "and only"),
        (52, 54, "the exchange of"),
        (55, 55, "prisoners"),
        (56, 60, "would we deliver up"),
        (61, 63, "our prisoners."),
    ],
    3: [
        (0, 3, "And rejected"),
        (4, 5, "Ammoron"),
        (6, 7, "my epistle,"),
        (8, 8, "for"),
        (9, 12, "he refused"),
        (13, 14, "to exchange"),
        (15, 15, "prisoners;"),
        (16, 17, "therefore"),
        (18, 21, "we began"),
        (22, 25, "to make preparations"),
        (26, 30, "to go"),
        (31, 33, "against"),
        (34, 36, "the city of"),
        (37, 37, "Antiparah."),
    ],
    4: [
        (0, 0, "But"),
        (1, 2, "left"),
        (3, 5, "the people of"),
        (6, 6, "Antiparah"),
        (7, 8, "the city,"),
        (9, 12, "and fled"),
        (13, 17, "to their other cities,"),
        (18, 21, "which they had possession of,"),
        (22, 23, "to fortify"),
        (24, 25, "them;"),
        (26, 28, "and thus"),
        (29, 32, "fell"),
        (33, 36, "the city of"),
        (37, 37, "Antiparah"),
        (38, 41, "into our hands."),
    ],
    5: [
        (0, 2, "And thus"),
        (3, 4, "ended"),
        (5, 7, "the year"),
        (8, 12, "twenty and eight"),
        (13, 16, "of the reign of"),
        (17, 17, "the judges."),
    ],
    6: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the commencement of"),
        (7, 8, "the year"),
        (9, 13, "twenty and nine,"),
        (14, 17, "we received"),
        (18, 20, "a supply of"),
        (21, 22, "provisions,"),
        (23, 26, "and also an addition"),
        (27, 30, "to our army,"),
        (31, 34, "from the land of"),
        (35, 35, "Zarahemla,"),
        (36, 38, "and from"),
        (39, 41, "the land round about,"),
        (42, 45, "to the number of"),
        (46, 49, "six thousand men,"),
        (50, 53, "besides"),
        (54, 55, "the sixty"),
        (56, 58, "of the sons of"),
        (59, 60, "the Ammonites,"),
        (61, 65, "who had come"),
        (66, 68, "to join with"),
        (69, 71, "their brethren,"),
        (72, 76, "my little band"),
        (77, 79, "of two thousand."),
        (80, 82, "And now"),
        (83, 83, "behold,"),
        (84, 86, "we were strong,"),
        (87, 87, "yea,"),
        (88, 92, "and we had also"),
        (93, 95, "much of"),
        (96, 97, "provisions"),
        (98, 99, "brought"),
        (100, 103, "unto us."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 5, "we were desirous"),
        (6, 7, "to fight"),
        (8, 9, "a battle"),
        (10, 13, "with the army"),
        (14, 15, "which was set"),
        (16, 17, "to defend"),
        (18, 20, "the city of"),
        (21, 21, "Cumeni."),
    ],
    8: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 9, "I will show"),
        (10, 12, "unto you"),
        (13, 16, "it was not long before"),
        (17, 18, "we fulfilled"),
        (19, 21, "our desire;"),
        (22, 22, "yea,"),
        (23, 24, "together with"),
        (25, 28, "our strong army,"),
        (29, 31, "or with"),
        (32, 34, "a part of"),
        (35, 38, "our strong army,"),
        (39, 42, "we did surround,"),
        (43, 45, "by night,"),
        (46, 48, "the city of"),
        (49, 49, "Cumeni,"),
        (50, 53, "a short time"),
        (54, 56, "before came"),
        (57, 59, "the time"),
        (60, 61, "that"),
        (62, 67, "they would receive"),
        (68, 70, "a supply of"),
        (71, 72, "provisions."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 6, "we did camp round about"),
        (7, 9, "the city"),
        (10, 13, "for many of"),
        (14, 14, "nights;"),
        (15, 18, "but we slept"),
        (19, 22, "with our swords,"),
        (23, 24, "and set up"),
        (25, 26, "guards,"),
        (27, 31, "that could not"),
        (32, 33, "come"),
        (34, 35, "the Lamanites"),
        (36, 38, "upon"),
        (39, 40, "us"),
        (41, 43, "by night"),
        (44, 45, "and slay"),
        (46, 47, "us,"),
        (48, 50, "which thing"),
        (51, 53, "they attempted"),
        (54, 57, "at many of"),
        (58, 58, "times;"),
        (59, 59, "but"),
        (60, 64, "as many times"),
        (65, 68, "as they attempted"),
        (69, 70, "this thing"),
        (71, 73, "was shed"),
        (74, 76, "their blood."),
    ],
    10: [
        (0, 2, "when had passed"),
        (3, 4, "some time,"),
        (5, 7, "it came to pass that"),
        (8, 9, "arrived"),
        (10, 12, "their provisions,"),
        (13, 15, "and they nearly"),
        (16, 19, "entered"),
        (20, 22, "into the city"),
        (23, 25, "by night."),
        (26, 26, "But"),
        (27, 29, "we,"),
        (30, 32, "were not"),
        (33, 35, "Lamanites,"),
        (36, 37, "but"),
        (38, 40, "Nephites;"),
        (41, 42, "therefore,"),
        (43, 46, "we took"),
        (47, 48, "them"),
        (49, 52, "and their provisions."),
    ],
    11: [
        (0, 3, "And notwithstanding"),
        (4, 5, "cut off"),
        (6, 7, "the Lamanites"),
        (8, 12, "from what supported"),
        (13, 14, "them"),
        (15, 17, "after this manner,"),
        (18, 21, "they were still determined"),
        (22, 23, "to hold"),
        (24, 25, "the city;"),
        (26, 27, "therefore"),
        (28, 30, "it was necessary"),
        (31, 33, "that we take"),
        (34, 36, "those provisions"),
        (37, 39, "and send"),
        (40, 41, "to Judea,"),
        (42, 45, "and our prisoners"),
        (46, 49, "to the land of"),
        (50, 50, "Zarahemla."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 6, "were not many"),
        (7, 8, "days"),
        (9, 10, "that passed,"),
        (11, 13, "before began to"),
        (14, 14, "be taken away"),
        (15, 18, "all the hopes of"),
        (19, 20, "the Lamanites"),
        (21, 23, "of succor;"),
        (24, 25, "therefore"),
        (26, 30, "they surrendered"),
        (31, 32, "the city"),
        (33, 36, "unto our hands;"),
        (37, 39, "and thus"),
        (40, 42, "we accomplished"),
        (43, 46, "our designs"),
        (47, 50, "in obtaining"),
        (51, 53, "the city of"),
        (54, 54, "Cumeni."),
    ],
    13: [
        (0, 0, "But"),
        (1, 3, "it came to pass that"),
        (4, 6, "were exceedingly many"),
        (7, 9, "our prisoners,"),
        (10, 12, "notwithstanding"),
        (13, 15, "the greatness of"),
        (16, 18, "our number,"),
        (19, 20, "it was necessary"),
        (21, 23, "for us"),
        (24, 25, "to employ"),
        (26, 29, "our whole army"),
        (30, 31, "to guard"),
        (32, 33, "them,"),
        (34, 35, "or"),
        (36, 38, "the slaying of"),
        (39, 40, "them."),
    ],
    14: [
        (0, 1, "For behold,"),
        (2, 5, "they would break out"),
        (6, 10, "in great numbers,"),
        (11, 12, "and would fight"),
        (13, 14, "with stones,"),
        (15, 16, "and with clubs,"),
        (17, 21, "or whatsoever thing"),
        (22, 24, "they could"),
        (25, 26, "get"),
        (27, 30, "into their hands,"),
        (31, 33, "insomuch that"),
        (34, 36, "we did slay"),
        (37, 40, "upwards of"),
        (41, 43, "two thousand"),
        (44, 46, "of them"),
        (47, 49, "after had finished"),
        (50, 53, "they surrendered"),
        (54, 57, "themselves"),
        (58, 61, "as prisoners of"),
        (62, 62, "war."),
    ],
    15: [
        (0, 1, "Therefore"),
        (2, 4, "it became expedient"),
        (5, 7, "for us,"),
        (8, 10, "to put an end to"),
        (11, 13, "their lives,"),
        (14, 15, "or to guard"),
        (16, 17, "them,"),
        (18, 20, "sword"),
        (21, 23, "in hand,"),
        (24, 26, "down to"),
        (27, 29, "the land of"),
        (30, 30, "Zarahemla;"),
        (31, 36, "and also our provisions"),
        (37, 40, "were no more"),
        (41, 44, "than what was enough"),
        (45, 49, "for our own people,"),
        (50, 52, "notwithstanding"),
        (53, 54, "the food"),
        (55, 58, "which we had taken"),
        (59, 61, "from the Lamanites."),
    ],
    16: [
        (0, 2, "And now,"),
        (3, 6, "in these critical circumstances,"),
        (7, 10, "it became"),
        (11, 13, "a very weighty matter"),
        (14, 18, "the deciding of a thing"),
        (19, 22, "what should be done"),
        (23, 25, "concerning"),
        (26, 28, "these prisoners of"),
        (29, 30, "war;"),
        (31, 34, "nevertheless,"),
        (35, 36, "it was decided"),
        (37, 39, "by us"),
        (40, 42, "to send"),
        (43, 44, "them"),
        (45, 47, "down to"),
        (48, 50, "the land of"),
        (51, 51, "Zarahemla;"),
        (52, 53, "therefore"),
        (54, 57, "we chose"),
        (58, 60, "a part of"),
        (61, 63, "our men,"),
        (64, 66, "and gave"),
        (67, 69, "to them"),
        (70, 72, "the charge of"),
        (73, 75, "our prisoners"),
        (76, 78, "to go down"),
        (79, 82, "to the land of"),
        (83, 83, "Zarahemla."),
    ],
    17: [
        (0, 2, "But it came to pass"),
        (3, 8, "on the next day,"),
        (9, 13, "they did return."),
        (14, 16, "And now"),
        (17, 17, "behold,"),
        (18, 22, "we did not inquire"),
        (23, 25, "of them"),
        (26, 28, "concerning"),
        (29, 29, "prisoners;"),
        (30, 31, "for behold,"),
        (32, 34, "came"),
        (35, 36, "the Lamanites"),
        (37, 40, "upon us,"),
        (41, 47, "and they also came exactly"),
        (48, 50, "in the time"),
        (51, 53, "to save"),
        (54, 55, "us"),
        (56, 59, "from falling"),
        (60, 63, "into their hands."),
        (64, 65, "For behold,"),
        (66, 68, "had sent"),
        (69, 70, "Ammoron"),
        (71, 74, "to their support"),
        (75, 78, "a new supply of"),
        (79, 80, "provisions"),
        (81, 85, "and also a numerous army"),
        (86, 87, "of men."),
    ],
    18: [
        (0, 3, "And it came to pass that"),
        (4, 5, "arrived"),
        (6, 7, "those men"),
        (8, 13, "whom we sent"),
        (14, 15, "together with"),
        (16, 16, "the prisoners"),
        (17, 21, "at the exact time"),
        (22, 24, "to stop"),
        (25, 26, "them,"),
        (27, 28, "as nearly"),
        (29, 31, "they overpowered"),
        (32, 33, "us."),
    ],
    19: [
        (0, 1, "For behold,"),
        (2, 3, "fought"),
        (4, 6, "without"),
        (7, 12, "a thought of death"),
        (13, 16, "my little band"),
        (17, 20, "of two thousand and sixty;"),
        (21, 21, "yea,"),
        (22, 24, "they were firm"),
        (25, 27, "before"),
        (28, 29, "the Lamanites,"),
        (30, 32, "and brought"),
        (33, 34, "death"),
        (35, 39, "unto all"),
        (40, 44, "those who opposed"),
        (45, 48, "them."),
    ],
    20: [
        (0, 1, "And as"),
        (2, 5, "were about to retreat"),
        (6, 10, "the remaining part of"),
        (11, 13, "our army"),
        (14, 16, "from before"),
        (17, 18, "the Lamanites,"),
        (19, 19, "behold,"),
        (20, 23, "those two thousand"),
        (24, 26, "and sixty"),
        (27, 28, "were firm"),
        (29, 32, "and undaunted."),
    ],
    21: [
        (0, 0, "Yea,"),
        (1, 4, "and they did obey"),
        (5, 6, "and observe"),
        (7, 8, "to do"),
        (9, 11, "every word of"),
        (12, 12, "command"),
        (13, 16, "with exactness;"),
        (17, 17, "yea,"),
        (18, 20, "and it was done"),
        (21, 24, "unto them"),
        (25, 27, "according to"),
        (28, 30, "their faith;"),
        (31, 34, "and I remembered"),
        (35, 35, "the words"),
        (36, 39, "which they said"),
        (40, 42, "unto me"),
        (43, 45, "that had taught"),
        (46, 47, "them"),
        (48, 51, "by their mothers."),
    ],
    22: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 7, "it was these my sons,"),
        (8, 10, "and those men"),
        (11, 14, "who had been selected"),
        (15, 16, "to convey"),
        (17, 17, "the prisoners,"),
        (18, 21, "to whom"),
        (22, 27, "we are indebted"),
        (28, 29, "for this"),
        (30, 31, "great victory;"),
        (32, 32, "for"),
        (33, 36, "it was they"),
        (37, 40, "who defeated"),
        (41, 42, "the Lamanites;"),
        (43, 44, "therefore"),
        (45, 48, "were driven back"),
        (49, 50, "them"),
        (51, 52, "backward"),
        (53, 56, "to the city of"),
        (57, 57, "Manti."),
    ],
    23: [
        (0, 3, "And thus we did retain"),
        (4, 7, "our city of"),
        (8, 8, "Cumeni,"),
        (9, 13, "and were not all destroyed"),
        (14, 15, "us"),
        (16, 18, "by the sword;"),
        (19, 22, "nevertheless,"),
        (23, 25, "we had suffered"),
        (26, 29, "in the many of"),
        (30, 32, "those slain."),
    ],
    24: [
        (0, 3, "And it came to pass that"),
        (4, 8, "after had fled"),
        (9, 11, "the Lamanites,"),
        (12, 17, "I quickly gave"),
        (18, 20, "orders"),
        (21, 22, "that be removed"),
        (23, 25, "from among"),
        (26, 27, "the dead"),
        (28, 29, "my men"),
        (30, 33, "who were wounded,"),
        (34, 36, "and commanded"),
        (37, 38, "that be bound"),
        (39, 41, "their wounds."),
    ],
    25: [
        (0, 3, "And it came to pass that"),
        (4, 6, "there were"),
        (7, 9, "the two hundred,"),
        (10, 13, "of my two thousand"),
        (14, 16, "and sixty,"),
        (17, 20, "who had fainted"),
        (21, 22, "because of"),
        (23, 25, "the much of"),
        (26, 28, "the shed blood;"),
        (29, 32, "nevertheless,"),
        (33, 35, "according to"),
        (36, 38, "the goodness of"),
        (39, 40, "God,"),
        (41, 43, "and our"),
        (44, 45, "great astonishment,"),
        (46, 50, "and also the joy of"),
        (51, 54, "our whole army,"),
        (55, 60, "there was not one person"),
        (61, 63, "of them"),
        (64, 65, "who did perish;"),
        (66, 66, "yea,"),
        (67, 71, "nor was there"),
        (72, 75, "a single person"),
        (76, 80, "among them"),
        (81, 85, "who had not received"),
        (86, 87, "wounds"),
        (88, 89, "many."),
    ],
    26: [
        (0, 2, "And now,"),
        (3, 6, "their preservation,"),
        (7, 9, "was a thing"),
        (10, 12, "greatly marveled"),
        (13, 17, "to our whole army,"),
        (18, 18, "yea,"),
        (19, 22, "in the sparing of"),
        (23, 24, "them"),
        (25, 28, "while there was"),
        (29, 31, "a thousand of"),
        (32, 34, "our brethren"),
        (35, 38, "who were slain."),
        (39, 44, "And we rightly attribute"),
        (45, 46, "this thing"),
        (47, 51, "to the miraculous power of"),
        (52, 53, "God,"),
        (54, 55, "because of"),
        (56, 59, "their great faith"),
        (60, 62, "in those things"),
        (63, 66, "they were taught"),
        (67, 70, "to believe—"),
        (71, 72, "that"),
        (73, 76, "there is"),
        (77, 79, "a just God,"),
        (80, 84, "and whosoever"),
        (85, 87, "did not doubt,"),
        (88, 91, "would be preserved"),
        (92, 93, "them"),
        (94, 95, "by his"),
        (96, 97, "marvelous power."),
    ],
    27: [
        (0, 1, "Now"),
        (2, 5, "this is the faith"),
        (6, 9, "of these"),
        (10, 11, "whom"),
        (12, 16, "I have spoken;"),
        (17, 20, "they are young,"),
        (21, 23, "and are firm"),
        (24, 26, "their minds,"),
        (27, 31, "and they place"),
        (32, 34, "their trust"),
        (35, 37, "in God"),
        (38, 40, "continually."),
    ],
    28: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 7, "when had finished"),
        (8, 9, "thus"),
        (10, 12, "we tended"),
        (13, 16, "our men"),
        (17, 18, "who were wounded,"),
        (19, 20, "and buried"),
        (21, 24, "our dead"),
        (25, 29, "and also the dead of"),
        (30, 31, "the Lamanites,"),
        (32, 36, "who were many,"),
        (37, 37, "behold,"),
        (38, 41, "we inquired"),
        (42, 43, "of Gid"),
        (44, 46, "concerning"),
        (47, 47, "the prisoners"),
        (48, 52, "whom they began to"),
        (53, 56, "go down together"),
        (57, 59, "down to"),
        (60, 62, "the land of"),
        (63, 63, "Zarahemla."),
    ],
    29: [
        (0, 1, "Now"),
        (2, 3, "Gid"),
        (4, 8, "was the chief captain"),
        (9, 11, "over"),
        (12, 13, "the band"),
        (14, 15, "which was appointed"),
        (16, 17, "to guard"),
        (18, 19, "them"),
        (20, 22, "to go"),
        (23, 26, "to the land of"),
        (27, 27, "Zarahemla."),
    ],
    30: [
        (0, 2, "And now,"),
        (3, 5, "these are the words"),
        (6, 9, "which said"),
        (10, 10, "Gid"),
        (11, 13, "unto me:"),
        (14, 14, "Behold,"),
        (15, 17, "we began to"),
        (18, 20, "go down"),
        (21, 24, "to the land of"),
        (25, 25, "Zarahemla"),
        (26, 27, "together with"),
        (28, 30, "our prisoners."),
        (31, 34, "And it came to pass that"),
        (35, 37, "we met with"),
        (38, 39, "the spies of"),
        (40, 42, "our armies,"),
        (43, 47, "who had been sent out"),
        (48, 49, "to watch"),
        (50, 52, "the camp of"),
        (53, 54, "the Lamanites."),
    ],
    31: [
        (0, 4, "And they cried"),
        (5, 8, "unto us,"),
        (9, 10, "saying:"),
        (11, 11, "Behold,"),
        (12, 16, "are now marching"),
        (17, 19, "the army of"),
        (20, 21, "the Lamanites"),
        (22, 24, "toward"),
        (25, 27, "the city of"),
        (28, 28, "Cumeni;"),
        (29, 30, "and behold,"),
        (31, 35, "they will attack"),
        (36, 37, "them,"),
        (38, 38, "yea,"),
        (39, 43, "and will destroy"),
        (44, 46, "our people."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 5, "heard"),
        (6, 9, "by our prisoners"),
        (10, 13, "their cries,"),
        (14, 18, "which made them bold;"),
        (19, 22, "and they did rise up"),
        (23, 24, "to rebel"),
        (25, 26, "against"),
        (27, 30, "us."),
    ],
    33: [
        (0, 2, "And because of"),
        (3, 5, "their rebellion,"),
        (6, 7, "therefore"),
        (8, 11, "we caused"),
        (12, 14, "that fell"),
        (15, 17, "our swords"),
        (18, 20, "upon"),
        (21, 22, "them."),
        (23, 26, "And it came to pass that"),
        (27, 29, "they rushed"),
        (30, 34, "as one body"),
        (35, 38, "upon our swords,"),
        (39, 41, "whereby"),
        (42, 44, "were slain"),
        (45, 49, "the many of them;"),
        (50, 54, "and those who remained"),
        (55, 57, "of them,"),
        (58, 60, "broke through"),
        (61, 64, "and fled"),
        (65, 68, "from us."),
    ],
    34: [
        (0, 1, "And behold,"),
        (2, 5, "when they had fled,"),
        (6, 9, "and could not"),
        (10, 11, "we catch"),
        (12, 14, "them,"),
        (15, 16, "therefore"),
        (17, 19, "hastened"),
        (20, 25, "the coming of our march"),
        (26, 28, "toward"),
        (29, 31, "the city of"),
        (32, 32, "Cumeni;"),
        (33, 34, "and behold,"),
        (35, 40, "we arrived exactly"),
        (41, 43, "in time"),
        (44, 47, "that we could"),
        (48, 49, "assist"),
        (50, 53, "our brethren"),
        (54, 57, "in the preserving of"),
        (58, 59, "the city."),
    ],
    35: [
        (0, 1, "And behold,"),
        (2, 5, "are again delivered"),
        (6, 7, "we"),
        (8, 10, "from the hands of"),
        (11, 13, "our enemies."),
        (14, 17, "And blessed be"),
        (18, 20, "the name of"),
        (21, 23, "our God;"),
        (24, 25, "for behold,"),
        (26, 28, "it is he himself"),
        (29, 30, "who delivered"),
        (31, 32, "us;"),
        (33, 33, "yea,"),
        (34, 36, "he himself"),
        (37, 39, "who did"),
        (40, 42, "this great thing"),
        (43, 45, "for us."),
    ],
    36: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 9, "after had heard"),
        (10, 11, "I,"),
        (12, 13, "Helaman,"),
        (14, 17, "these words of"),
        (18, 18, "Gid,"),
        (19, 21, "I was filled"),
        (22, 25, "with exceeding joy"),
        (26, 27, "because of"),
        (28, 30, "the goodness of"),
        (31, 32, "God"),
        (33, 36, "in the preserving of"),
        (37, 38, "us,"),
        (39, 43, "that not all perish"),
        (44, 45, "us;"),
        (46, 46, "yea,"),
        (47, 50, "and I trust"),
        (51, 53, "the souls of"),
        (54, 55, "them"),
        (56, 59, "who have been slain"),
        (60, 62, "have entered"),
        (63, 66, "into the rest of"),
        (67, 69, "their God."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
