"""Hand-curated TAM-phrase gloss overrides for Mosaea 11 — wicked King Noah, his priests, and the prophet Abinadi.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
subject `o ia` / agent `e ia` absorbed into the verb cluster, never split as a
bare "he" (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` fillers when a PP/object follows (rule 1), `mafai ona`/`ina ia`/
`ina ua` bound (rules 13/15), vocative `e`/`E …e` folded as "O X" (rule 12),
directional "forth" dropped (rule 12a). No pronoun/TAM word injected into a cell
whose span lacks that token; no content word repeats across adjacent cells
(except authentic Samoan doublings and correlatives). Em-dash source token
`Alii—Oi` (v20) split per rule 11.

To rebuild after editing:
    python3 build_overrides_mosiah11.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 11
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 4, "it came to pass"),
        (5, 6, "that conferred"),
        (7, 8, "Zeniff"),
        (9, 10, "the kingdom"),
        (11, 14, "upon Noah,"),
        (15, 17, "one"),
        (18, 20, "of his sons;"),
        (21, 22, "therefore"),
        (23, 25, "began"),
        (26, 27, "to reign"),
        (28, 29, "Noah"),
        (30, 32, "in his stead;"),
        (33, 38, "and he walked not"),
        (39, 43, "in the ways of his father."),
    ],
    2: [
        (0, 1, "For behold,"),
        (2, 6, "he did not keep"),
        (7, 10, "the commandments of God,"),
        (11, 11, "but"),
        (12, 15, "he did walk"),
        (16, 19, "according to the desires"),
        (20, 23, "of his own heart."),
        (24, 27, "And there was"),
        (28, 30, "unto him"),
        (31, 34, "many wives"),
        (35, 36, "and concubines."),
        (37, 41, "And he did cause"),
        (42, 43, "that commit"),
        (44, 46, "his people"),
        (47, 48, "sin,"),
        (49, 51, "and do things"),
        (52, 53, "which was abominable"),
        (54, 56, "in the sight"),
        (57, 59, "of the Lord."),
        (60, 60, "Yea,"),
        (61, 64, "and they did commit"),
        (65, 66, "whoredoms"),
        (67, 68, "and manner"),
        (69, 72, "of all wickedness."),
    ],
    3: [
        (0, 4, "And he laid"),
        (5, 6, "a tax"),
        (7, 10, "of one fifth part"),
        (11, 13, "of all things"),
        (14, 16, "they possessed,"),
        (17, 20, "a fifth part"),
        (21, 24, "of their gold"),
        (25, 28, "and of their silver,"),
        (29, 32, "and a fifth part"),
        (33, 36, "of their ziff,"),
        (37, 40, "and of their copper,"),
        (41, 44, "and of their brass,"),
        (45, 48, "and their iron;"),
        (49, 52, "and a fifth part"),
        (53, 57, "of their fatlings;"),
        (58, 62, "and also a fifth part"),
        (63, 67, "of all their grain."),
    ],
    4: [
        (0, 4, "And he took"),
        (5, 7, "all these things"),
        (8, 10, "to support"),
        (11, 13, "himself,"),
        (14, 16, "and his wives"),
        (17, 19, "and his concubines;"),
        (20, 23, "and also his priests,"),
        (24, 27, "and their wives"),
        (28, 31, "and their concubines;"),
        (32, 34, "thus"),
        (35, 38, "he changed"),
        (39, 42, "the affairs of the kingdom."),
    ],
    5: [
        (0, 3, "For he put down"),
        (4, 5, "all the priests"),
        (6, 7, "that were consecrated"),
        (8, 10, "by his father,"),
        (11, 14, "and he consecrated"),
        (15, 17, "new priests"),
        (18, 19, "to replace"),
        (20, 22, "them,"),
        (23, 27, "such as were"),
        (28, 29, "lifted up"),
        (30, 32, "in the pride"),
        (33, 36, "of their hearts."),
    ],
    6: [
        (0, 0, "Yea,"),
        (1, 3, "and thus"),
        (4, 5, "were supported"),
        (6, 7, "they"),
        (8, 11, "in their laziness,"),
        (12, 14, "and in their"),
        (15, 17, "worship of idols,"),
        (18, 21, "and in their whoredoms,"),
        (22, 23, "by the taxes"),
        (24, 25, "which had put"),
        (26, 30, "king Noah"),
        (31, 35, "upon his people;"),
        (36, 37, "thus"),
        (38, 41, "did labor exceedingly"),
        (42, 44, "the people"),
        (45, 46, "to support"),
        (47, 48, "iniquity."),
    ],
    7: [
        (0, 0, "Yea,"),
        (1, 4, "and it also came to pass"),
        (5, 6, "that became"),
        (7, 8, "they"),
        (9, 13, "worshippers of idols,"),
        (14, 16, "because were deceived"),
        (17, 18, "they"),
        (19, 22, "by the vain words"),
        (23, 24, "and flattering"),
        (25, 27, "of the king"),
        (28, 30, "and his priests;"),
        (31, 35, "for they did speak"),
        (36, 37, "flattering things"),
        (38, 41, "unto them."),
    ],
    8: [
        (0, 2, "And it came to pass"),
        (3, 4, "that built"),
        (5, 9, "king Noah"),
        (10, 12, "elegant buildings"),
        (13, 16, "and spacious many;"),
        (17, 20, "and he ornamented"),
        (21, 24, "with fine workmanship"),
        (25, 26, "of wood,"),
        (27, 29, "and all manner"),
        (30, 32, "of precious things,"),
        (33, 35, "of gold,"),
        (36, 38, "and of silver,"),
        (39, 41, "and of iron,"),
        (42, 44, "and of brass,"),
        (45, 47, "and of ziff,"),
        (48, 50, "and of copper."),
    ],
    9: [
        (0, 4, "And he also built"),
        (5, 7, "a spacious palace"),
        (8, 10, "for himself,"),
        (11, 13, "and a throne"),
        (14, 16, "in the midst thereof,"),
        (17, 20, "all these things"),
        (21, 23, "was made"),
        (24, 26, "of fine wood"),
        (27, 29, "and was ornamented"),
        (30, 32, "with gold"),
        (33, 35, "and silver"),
        (36, 38, "and with precious things."),
    ],
    10: [
        (0, 5, "And he also caused"),
        (6, 7, "that should work"),
        (8, 11, "his workmen"),
        (12, 13, "all manner"),
        (14, 17, "of fine work"),
        (18, 21, "within the walls"),
        (22, 24, "of the temple,"),
        (25, 27, "of fine wood,"),
        (28, 31, "and of copper,"),
        (32, 35, "and of brass."),
    ],
    11: [
        (0, 2, "And the seats"),
        (3, 4, "which were set apart"),
        (5, 7, "for the high priests,"),
        (8, 11, "which were higher"),
        (12, 17, "than all the other seats,"),
        (18, 21, "he did ornament"),
        (22, 25, "with pure gold;"),
        (26, 28, "and he caused"),
        (29, 30, "a breastwork"),
        (31, 34, "before them,"),
        (35, 36, "that"),
        (37, 38, "might"),
        (39, 41, "they lean thereon"),
        (42, 46, "upon their bodies"),
        (47, 50, "and their arms"),
        (51, 54, "while they should speak"),
        (55, 57, "lying words"),
        (58, 60, "and vain"),
        (61, 63, "to his people."),
    ],
    12: [
        (0, 2, "And it came to pass"),
        (3, 6, "that he built"),
        (7, 8, "a tower"),
        (9, 12, "near the temple;"),
        (13, 13, "yea,"),
        (14, 18, "a very high tower,"),
        (19, 23, "it was exceeding high,"),
        (24, 26, "that could"),
        (27, 30, "he stand thereon"),
        (31, 32, "above"),
        (33, 35, "and look out"),
        (36, 40, "the land of Shilom,"),
        (41, 44, "and also the land"),
        (45, 46, "of Shemlon,"),
        (47, 49, "which was held"),
        (50, 52, "by the Lamanites;"),
        (53, 57, "and could also"),
        (58, 62, "he look out"),
        (63, 66, "over all the land"),
        (67, 69, "round about."),
    ],
    13: [
        (0, 2, "And it came to pass"),
        (3, 6, "that he caused"),
        (7, 8, "to be built"),
        (9, 12, "many buildings"),
        (13, 17, "in the land of Shilom;"),
        (18, 22, "and he caused"),
        (23, 24, "to be built"),
        (25, 27, "a great tower"),
        (28, 32, "on the hill"),
        (33, 34, "on the north"),
        (35, 39, "of the land of Shilom,"),
        (40, 42, "which had been"),
        (43, 44, "a resort"),
        (45, 49, "for the children of Nephi"),
        (50, 52, "at the time"),
        (53, 57, "they fled"),
        (58, 60, "out of the land;"),
        (61, 63, "and thus"),
        (64, 67, "he did do"),
        (68, 69, "with the riches"),
        (70, 73, "which he obtained"),
        (74, 75, "by the taxes"),
        (76, 78, "of his people."),
    ],
    14: [
        (0, 2, "And it came to pass"),
        (3, 7, "that he set"),
        (8, 9, "his heart"),
        (10, 12, "upon his riches,"),
        (13, 15, "and he spent"),
        (16, 17, "his time"),
        (18, 21, "in riotous living"),
        (22, 25, "with his wives"),
        (26, 28, "and his concubines;"),
        (29, 32, "and so also"),
        (33, 34, "did spend"),
        (35, 37, "his priests"),
        (38, 40, "their time"),
        (41, 43, "with harlots."),
    ],
    15: [
        (0, 2, "And it came to pass"),
        (3, 6, "that he planted"),
        (7, 8, "vineyards round about"),
        (9, 11, "in the land;"),
        (12, 16, "and he built"),
        (17, 17, "wine-presses,"),
        (18, 19, "and made"),
        (20, 22, "wine in abundance;"),
        (23, 25, "and therefore"),
        (26, 30, "he became"),
        (31, 33, "a man"),
        (34, 36, "drinking much wine,"),
        (37, 40, "and so also"),
        (41, 42, "his people."),
    ],
    16: [
        (0, 2, "And it came to pass"),
        (3, 5, "that began"),
        (6, 7, "to come"),
        (8, 10, "the Lamanites"),
        (11, 15, "upon his people,"),
        (16, 20, "upon small numbers"),
        (21, 22, "of people,"),
        (23, 24, "and to slay"),
        (25, 26, "them"),
        (27, 30, "in their fields,"),
        (31, 33, "while they were tending"),
        (34, 36, "their flocks."),
    ],
    17: [
        (0, 3, "And sent"),
        (4, 8, "king Noah"),
        (9, 10, "guards round about"),
        (11, 13, "the land"),
        (14, 16, "to drive off"),
        (17, 18, "them;"),
        (19, 22, "but was not enough"),
        (23, 24, "the number"),
        (25, 31, "of those whom he sent,"),
        (32, 35, "and came"),
        (36, 37, "the Lamanites"),
        (38, 41, "upon them"),
        (42, 43, "and killed"),
        (44, 45, "them,"),
        (46, 47, "and drove"),
        (48, 49, "the many"),
        (50, 53, "of their flocks"),
        (54, 56, "out of the land;"),
        (57, 60, "thus began"),
        (61, 63, "the Lamanites"),
        (64, 65, "to destroy"),
        (66, 68, "them,"),
        (69, 70, "and to exercise"),
        (71, 73, "their hatred"),
        (74, 77, "upon them."),
    ],
    18: [
        (0, 2, "And it came to pass"),
        (3, 5, "that sent"),
        (6, 10, "king Noah"),
        (11, 12, "his armies"),
        (13, 14, "to battle against"),
        (15, 18, "them,"),
        (19, 22, "and they retreated,"),
        (23, 26, "or they drove"),
        (27, 28, "them"),
        (29, 30, "back"),
        (31, 33, "for a time;"),
        (34, 35, "therefore,"),
        (36, 40, "they returned"),
        (41, 43, "with joy"),
        (44, 45, "in the things"),
        (46, 48, "they had taken."),
    ],
    19: [
        (0, 2, "And now,"),
        (3, 7, "because of this great victory"),
        (8, 10, "were lifted up"),
        (11, 12, "they"),
        (13, 15, "in the pride"),
        (16, 19, "of their hearts;"),
        (20, 22, "they did boast"),
        (23, 27, "in their own strength,"),
        (28, 29, "saying"),
        (30, 31, "that could"),
        (32, 35, "their fifty"),
        (36, 39, "stand against"),
        (40, 44, "thousands and thousands"),
        (45, 47, "of the Lamanites;"),
        (48, 50, "and thus"),
        (51, 53, "they did boast,"),
        (54, 55, "and delighted"),
        (56, 58, "in blood,"),
        (59, 61, "and the shedding"),
        (62, 64, "of the blood"),
        (65, 68, "of their brethren,"),
        (69, 73, "and this because of"),
        (74, 75, "the wickedness"),
        (76, 79, "of their king"),
        (80, 83, "and their priests."),
    ],
    20: [
        (0, 2, "And it came to pass"),
        (3, 6, "that there was"),
        (7, 10, "among them"),
        (11, 12, "a man"),
        (13, 15, "whose name"),
        (16, 17, "was Abinadi;"),
        (18, 23, "and he went forth"),
        (24, 28, "among them,"),
        (29, 32, "and began to prophesy,"),
        (33, 34, "saying:"),
        (35, 35, "Behold,"),
        (36, 40, "thus saith"),
        (41, 43, "the Lord,"),
        (44, 46, "and thus"),
        (47, 49, "hath he commanded"),
        (50, 51, "me,"),
        (52, 53, "saying,"),
        (54, 56, "Go,"),
        (57, 59, "and say"),
        (60, 62, "unto this people,"),
        (63, 67, "thus saith"),
        (68, 70, "the Lord—"),
        (71, 72, "O wo"),
        (73, 75, "unto this people,"),
        (76, 79, "for I have seen"),
        (80, 83, "their abominations,"),
        (84, 87, "and their wickedness,"),
        (88, 91, "and their whoredoms;"),
        (92, 92, "and"),
        (93, 98, "I will visit"),
        (99, 102, "them"),
        (103, 105, "in mine anger,"),
        (106, 107, "except"),
        (108, 110, "they repent."),
    ],
    21: [
        (0, 3, "And except"),
        (4, 6, "they repent"),
        (7, 9, "and turn"),
        (10, 12, "to the Lord"),
        (13, 15, "their God,"),
        (16, 16, "behold,"),
        (17, 22, "I will deliver"),
        (23, 24, "them"),
        (25, 26, "into the hands"),
        (27, 30, "of their enemies;"),
        (31, 31, "yea,"),
        (32, 36, "and shall be brought"),
        (37, 38, "them"),
        (39, 41, "into bondage;"),
        (42, 46, "and shall be afflicted"),
        (47, 48, "them"),
        (49, 50, "by the hand"),
        (51, 54, "of their enemies."),
    ],
    22: [
        (0, 0, "And"),
        (1, 5, "it shall come to pass,"),
        (6, 10, "that they shall know"),
        (11, 15, "that I am the Lord"),
        (16, 18, "their God,"),
        (19, 21, "and I am"),
        (22, 25, "a jealous God,"),
        (26, 28, "visiting"),
        (29, 31, "my people"),
        (32, 35, "in their iniquities."),
    ],
    23: [
        (0, 0, "And"),
        (1, 5, "it shall come to pass,"),
        (6, 7, "that except"),
        (8, 9, "repent"),
        (10, 11, "this people"),
        (12, 14, "and turn"),
        (15, 17, "unto the Lord"),
        (18, 20, "their God,"),
        (21, 24, "shall be brought"),
        (25, 26, "them"),
        (27, 29, "into bondage;"),
        (30, 34, "and there shall be no"),
        (35, 36, "one"),
        (37, 38, "to deliver"),
        (39, 41, "them,"),
        (42, 44, "save only"),
        (45, 46, "the Lord"),
        (47, 49, "the Most High God."),
    ],
    24: [
        (0, 0, "Yea,"),
        (1, 5, "and it shall come to pass"),
        (6, 10, "when they cry"),
        (11, 13, "unto me"),
        (14, 17, "I will be slow"),
        (18, 21, "I hear"),
        (22, 24, "their cries;"),
        (25, 25, "yea,"),
        (26, 26, "and"),
        (27, 31, "I will suffer"),
        (32, 33, "them"),
        (34, 35, "that"),
        (36, 38, "they be smitten"),
        (39, 42, "by their enemies."),
    ],
    25: [
        (0, 2, "And except"),
        (3, 5, "they repent"),
        (6, 8, "in the clothing"),
        (9, 12, "of sackcloth"),
        (13, 15, "and ashes,"),
        (16, 19, "and cry mightily"),
        (20, 22, "to the Lord"),
        (23, 25, "their God,"),
        (26, 31, "I will not hear"),
        (32, 34, "their prayers,"),
        (35, 38, "neither will I deliver"),
        (39, 40, "them"),
        (41, 44, "out of their afflictions;"),
        (45, 50, "and thus saith"),
        (51, 53, "the Lord,"),
        (54, 56, "and thus"),
        (57, 59, "hath he commanded"),
        (60, 61, "me."),
    ],
    26: [
        (0, 1, "And now"),
        (2, 3, "it came to pass"),
        (4, 7, "after had made an end"),
        (8, 9, "of speaking"),
        (10, 10, "Abinadi"),
        (11, 13, "these words"),
        (14, 17, "unto them"),
        (18, 20, "they were wroth"),
        (21, 23, "with him,"),
        (24, 25, "and sought"),
        (26, 27, "to take away"),
        (28, 29, "his life;"),
        (30, 30, "but"),
        (31, 34, "he was delivered"),
        (35, 37, "by the Lord"),
        (38, 41, "out of their hands."),
    ],
    27: [
        (0, 1, "Now"),
        (2, 4, "when had heard"),
        (5, 8, "king Noah"),
        (9, 10, "of the words"),
        (11, 13, "which had spoken"),
        (14, 15, "Abinadi"),
        (16, 18, "unto the people,"),
        (19, 23, "he was also wroth,"),
        (24, 28, "and he said:"),
        (29, 31, "Who is Abinadi,"),
        (32, 35, "that he should judge"),
        (36, 36, "me"),
        (37, 39, "and my people,"),
        (40, 43, "or who is"),
        (44, 45, "the Lord,"),
        (46, 49, "that shall bring"),
        (50, 54, "upon my people"),
        (55, 58, "such great affliction?"),
    ],
    28: [
        (0, 3, "I command"),
        (4, 6, "you"),
        (7, 9, "to bring Abinadi"),
        (10, 10, "hither,"),
        (11, 12, "that"),
        (13, 14, "might"),
        (15, 16, "I slay"),
        (17, 19, "him,"),
        (20, 20, "for"),
        (21, 25, "he hath said"),
        (26, 27, "these things"),
        (28, 30, "that might"),
        (31, 34, "he stir up"),
        (35, 36, "my people"),
        (37, 40, "to be angry one"),
        (41, 43, "with another,"),
        (44, 46, "and to raise"),
        (47, 47, "contentions"),
        (48, 52, "among my people;"),
        (53, 54, "therefore"),
        (55, 60, "I will slay"),
        (61, 62, "him."),
    ],
    29: [
        (0, 1, "Now"),
        (2, 3, "were blinded"),
        (4, 4, "the eyes"),
        (5, 7, "of the people;"),
        (8, 9, "therefore"),
        (10, 13, "they hardened"),
        (14, 16, "their hearts"),
        (17, 20, "against the words"),
        (21, 22, "of Abinadi,"),
        (23, 26, "and they sought"),
        (27, 29, "from that time"),
        (30, 31, "to take"),
        (32, 33, "him."),
        (34, 36, "And hardened"),
        (37, 41, "king Noah"),
        (42, 43, "his heart"),
        (44, 45, "against"),
        (46, 48, "the word"),
        (49, 51, "of the Lord,"),
        (52, 57, "and he did not repent"),
        (58, 61, "of his evil doings."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
