"""
Hand-curated TAM-phrase gloss overrides for Helamana (Helaman) 13 — Samuel the
Lamanite, cast out of Zarahemla, returns at the voice of the Lord and prophesies
from the city wall: the sword of justice hangs over the wicked Nephites; only
the righteous and the prophets are keeping the people from destruction; their
riches will become slippery and cursed because they set their hearts on wealth
and reject the prophets; a lament of wo and coming desolation unless they repent.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-split applied to bom_books.json before glossing:
    13:27  loto—ma  ->  loto—  +  ma

    python3 build_overrides_helaman13.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "helaman"
CHAPTER_NUM = 13

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "And now"),
        (2, 3, "it came to pass"),
        (4, 7, "in the year"),
        (8, 11, "eighty and sixth,"),
        (12, 14, "still remained"),
        (15, 16, "the Nephites"),
        (17, 19, "in wickedness,"),
        (20, 20, "yea,"),
        (21, 24, "in great wickedness,"),
        (25, 28, "while the Lamanites"),
        (29, 32, "they observed strictly"),
        (33, 34, "to keep"),
        (35, 36, "the commandments of"),
        (37, 38, "God,"),
        (39, 41, "according to"),
        (42, 44, "the law of"),
        (45, 45, "Moses."),
    ],
    2: [
        (0, 2, "And it came to pass"),
        (3, 6, "in this year,"),
        (7, 11, "there was one"),
        (12, 15, "named Samuel,"),
        (16, 19, "a Lamanite,"),
        (20, 21, "who came"),
        (22, 25, "into the land of"),
        (26, 26, "Zarahemla,"),
        (27, 29, "and began to"),
        (30, 31, "preach"),
        (32, 33, "unto the people."),
        (34, 37, "And it came that"),
        (38, 41, "he preached,"),
        (42, 45, "for many days"),
        (46, 47, "repentance"),
        (48, 50, "unto the people,"),
        (51, 57, "and they cast him out"),
        (58, 59, "away,"),
        (60, 62, "and so it was"),
        (63, 70, "he was about to return"),
        (71, 74, "to his own land."),
    ],
    3: [
        (0, 1, "But behold,"),
        (2, 4, "came"),
        (5, 7, "the voice of"),
        (8, 9, "the Lord"),
        (10, 12, "unto him,"),
        (13, 15, "that he should"),
        (16, 18, "he return again,"),
        (19, 21, "and prophesy"),
        (22, 24, "unto the people"),
        (25, 28, "whatsoever things"),
        (29, 31, "should come"),
        (32, 34, "into his heart."),
    ],
    4: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they would not"),
        (7, 9, "suffer"),
        (10, 14, "that he enter"),
        (15, 17, "into the city;"),
        (18, 19, "therefore"),
        (20, 25, "he went"),
        (26, 29, "and climbed up"),
        (30, 34, "upon the wall of"),
        (35, 37, "the city,"),
        (38, 41, "and stretched forth"),
        (42, 43, "his hand,"),
        (44, 47, "and cried out"),
        (48, 51, "with a loud voice,"),
        (52, 55, "and prophesied"),
        (56, 58, "unto the people"),
        (59, 63, "whatsoever things"),
        (64, 66, "which put"),
        (67, 69, "the Lord"),
        (70, 72, "into his heart."),
    ],
    5: [
        (0, 4, "And he said"),
        (5, 8, "unto them:"),
        (9, 9, "Behold,"),
        (10, 13, "I am Samuel,"),
        (14, 17, "a Lamanite,"),
        (18, 21, "I speak"),
        (22, 24, "the words of"),
        (25, 26, "the Lord"),
        (27, 30, "which he puts"),
        (31, 33, "into my heart;"),
        (34, 35, "and behold,"),
        (36, 39, "he hath put"),
        (40, 42, "into my heart"),
        (43, 45, "to say"),
        (46, 48, "unto this people"),
        (49, 51, "hangeth over"),
        (52, 54, "the sword of"),
        (55, 56, "justice"),
        (57, 61, "upon this people;"),
        (62, 66, "and shall not pass away"),
        (67, 70, "four hundred years"),
        (71, 73, "but shall fall"),
        (74, 76, "the sword of"),
        (77, 78, "justice"),
        (79, 83, "upon this people."),
    ],
    6: [
        (0, 0, "Yea,"),
        (1, 3, "awaiteth"),
        (4, 5, "heavy destruction"),
        (6, 8, "this people,"),
        (9, 14, "and shall surely"),
        (15, 16, "come"),
        (17, 19, "unto this people,"),
        (20, 26, "and nothing"),
        (27, 31, "can save"),
        (32, 33, "this people"),
        (34, 35, "except"),
        (36, 37, "repentance"),
        (38, 40, "and faith"),
        (41, 46, "on the Lord Jesus Christ,"),
        (47, 50, "who surely"),
        (51, 55, "shall come"),
        (56, 58, "into the world,"),
        (59, 63, "and shall suffer"),
        (64, 67, "many things"),
        (68, 72, "and shall be slain"),
        (73, 75, "for his people."),
    ],
    7: [
        (0, 1, "And behold,"),
        (2, 5, "an angel of"),
        (6, 7, "the Lord"),
        (8, 11, "hath declared"),
        (12, 13, "these things"),
        (14, 16, "unto me,"),
        (17, 20, "and he brought"),
        (21, 22, "glad tidings"),
        (23, 25, "to my soul."),
        (26, 27, "And behold,"),
        (28, 31, "I was sent"),
        (32, 35, "to declare also"),
        (36, 37, "these things"),
        (38, 40, "unto you,"),
        (41, 44, "that ye might have"),
        (45, 46, "glad tidings;"),
        (47, 48, "but behold,"),
        (49, 53, "ye received me not."),
    ],
    8: [
        (0, 1, "Therefore,"),
        (2, 6, "thus saith"),
        (7, 9, "the Lord:"),
        (10, 11, "Because of"),
        (12, 14, "the hardness of"),
        (15, 16, "the hearts of"),
        (17, 19, "the Nephite people,"),
        (20, 21, "except"),
        (22, 24, "they repent,"),
        (25, 29, "I will take away"),
        (30, 31, "my word"),
        (32, 36, "from them,"),
        (37, 42, "and I will withdraw"),
        (43, 44, "my Spirit"),
        (45, 49, "from them,"),
        (50, 57, "and I will no longer suffer"),
        (58, 59, "them,"),
        (60, 66, "and I will turn"),
        (67, 68, "the hearts of"),
        (69, 71, "their brethren"),
        (72, 77, "against them."),
    ],
    9: [
        (0, 6, "And shall not pass away"),
        (7, 11, "four hundred years"),
        (12, 17, "but I will cause"),
        (18, 21, "that they be smitten;"),
        (22, 22, "yea,"),
        (23, 28, "I will visit"),
        (29, 32, "them"),
        (33, 35, "with the sword"),
        (36, 38, "and with famine"),
        (39, 41, "and with pestilence."),
    ],
    10: [
        (0, 0, "Yea,"),
        (1, 6, "I will visit"),
        (7, 10, "them"),
        (11, 14, "in my great anger,"),
        (15, 22, "and there shall be those"),
        (23, 27, "of the fourth generation,"),
        (28, 31, "of your enemies,"),
        (32, 36, "who shall live,"),
        (37, 39, "to behold"),
        (40, 43, "your utter destruction;"),
        (44, 46, "and surely"),
        (47, 51, "shall come"),
        (52, 53, "this thing,"),
        (54, 55, "except"),
        (56, 58, "ye repent,"),
        (59, 62, "saith"),
        (63, 64, "the Lord;"),
        (65, 68, "and those"),
        (69, 73, "of the fourth generation"),
        (74, 77, "shall bring"),
        (78, 80, "your destruction."),
    ],
    11: [
        (0, 4, "But if ye repent"),
        (5, 7, "and return"),
        (8, 13, "unto the Lord your God,"),
        (14, 19, "I will turn away"),
        (20, 21, "mine anger,"),
        (22, 25, "saith"),
        (26, 27, "the Lord;"),
        (28, 28, "yea,"),
        (29, 33, "thus saith"),
        (34, 36, "the Lord,"),
        (37, 40, "blessed are they"),
        (41, 44, "who repent"),
        (45, 47, "and turn"),
        (48, 50, "unto me,"),
        (51, 52, "but wo"),
        (53, 55, "unto him"),
        (56, 60, "that repents not."),
    ],
    12: [
        (0, 0, "Yea,"),
        (1, 3, "wo unto"),
        (4, 7, "this great city of"),
        (8, 8, "Zarahemla;"),
        (9, 10, "for behold,"),
        (11, 12, "it is saved"),
        (13, 14, "because of"),
        (15, 18, "those who"),
        (19, 20, "are righteous;"),
        (21, 21, "yea,"),
        (22, 24, "wo unto"),
        (25, 27, "this great city,"),
        (28, 31, "saith"),
        (32, 33, "the Lord,"),
        (34, 34, "for"),
        (35, 37, "I perceive"),
        (38, 42, "there are many,"),
        (43, 43, "yea,"),
        (44, 48, "the more part of"),
        (49, 51, "this great city,"),
        (52, 56, "who will harden"),
        (57, 59, "their hearts"),
        (60, 64, "against me,"),
        (65, 68, "saith"),
        (69, 70, "the Lord."),
    ],
    13: [
        (0, 4, "But blessed are they"),
        (5, 10, "who will repent,"),
        (11, 15, "for them"),
        (16, 20, "I will spare."),
        (21, 22, "But behold,"),
        (23, 25, "if there were not"),
        (26, 27, "the righteous"),
        (28, 34, "who are within"),
        (35, 37, "this great city,"),
        (38, 38, "behold,"),
        (39, 42, "I would cause"),
        (43, 46, "that fire come"),
        (47, 49, "from heaven"),
        (50, 53, "and destroy it."),
    ],
    14: [
        (0, 1, "But behold,"),
        (2, 3, "it is spared"),
        (4, 5, "because of"),
        (6, 8, "those who are righteous."),
        (9, 10, "But behold,"),
        (11, 15, "the time cometh,"),
        (16, 19, "saith"),
        (20, 21, "the Lord,"),
        (22, 26, "when ye cast out"),
        (27, 29, "the righteous"),
        (30, 34, "from among you,"),
        (35, 38, "then shall come"),
        (39, 41, "upon you"),
        (42, 43, "the destruction;"),
        (44, 44, "yea,"),
        (45, 47, "wo unto"),
        (48, 50, "this great city,"),
        (51, 52, "because of"),
        (53, 54, "the wickedness"),
        (55, 57, "and abominations"),
        (58, 63, "which are in it."),
    ],
    15: [
        (0, 0, "Yea,"),
        (1, 4, "and wo unto"),
        (5, 7, "the city of"),
        (8, 8, "Gideon,"),
        (9, 10, "because of"),
        (11, 12, "the wickedness"),
        (13, 15, "and abominations"),
        (16, 21, "which are in her."),
    ],
    16: [
        (0, 0, "Yea,"),
        (1, 4, "and wo unto"),
        (5, 6, "all the cities"),
        (7, 10, "which are"),
        (11, 14, "in the land round about,"),
        (15, 18, "which are held"),
        (19, 21, "by the Nephites,"),
        (22, 23, "because of"),
        (24, 25, "the wickedness"),
        (26, 28, "and abominations"),
        (29, 35, "which are in them."),
    ],
    17: [
        (0, 1, "And behold,"),
        (2, 6, "shall come"),
        (7, 8, "a curse"),
        (9, 13, "upon the land,"),
        (14, 17, "saith"),
        (18, 21, "the Lord of Hosts,"),
        (22, 23, "because of"),
        (24, 24, "the people"),
        (25, 27, "who are"),
        (28, 32, "upon the land,"),
        (33, 33, "yea,"),
        (34, 35, "because of"),
        (36, 38, "their wickedness"),
        (39, 43, "and their abominations."),
    ],
    18: [
        (0, 5, "And it shall come to pass,"),
        (6, 9, "saith"),
        (10, 13, "the Lord of Hosts,"),
        (14, 14, "yea,"),
        (15, 18, "our supreme God"),
        (19, 20, "and true,"),
        (21, 23, "whoso"),
        (24, 26, "shall hide"),
        (27, 27, "treasures"),
        (28, 30, "in the earth"),
        (31, 36, "he shall find no more,"),
        (37, 38, "because of"),
        (39, 42, "the great curse of"),
        (43, 44, "the land,"),
        (45, 46, "except"),
        (47, 52, "he be a righteous man"),
        (53, 58, "and he hide it up"),
        (59, 61, "unto the Lord."),
    ],
    19: [
        (0, 0, "For"),
        (1, 3, "I desire,"),
        (4, 7, "saith"),
        (8, 9, "the Lord,"),
        (10, 12, "that they hide"),
        (13, 15, "their treasures"),
        (16, 17, "unto me;"),
        (18, 23, "and cursed be they"),
        (24, 28, "who hide not"),
        (29, 31, "their treasures"),
        (32, 33, "unto me;"),
        (34, 34, "for"),
        (35, 38, "none"),
        (39, 40, "hideth up"),
        (41, 43, "their treasures"),
        (44, 45, "unto me,"),
        (46, 47, "except"),
        (48, 53, "those who are righteous;"),
        (54, 60, "and he who hides not"),
        (61, 62, "his treasures"),
        (63, 64, "unto me,"),
        (65, 69, "cursed is he,"),
        (70, 73, "and also the treasure,"),
        (74, 80, "and none"),
        (81, 84, "shall recover it"),
        (85, 86, "because of"),
        (87, 89, "the curse of"),
        (90, 91, "the land."),
    ],
    20: [
        (0, 5, "And shall come"),
        (6, 7, "the day"),
        (8, 13, "when they shall hide"),
        (14, 16, "their treasures,"),
        (17, 17, "because"),
        (18, 23, "they have set"),
        (24, 26, "their hearts"),
        (27, 28, "upon riches;"),
        (29, 30, "and because"),
        (31, 34, "they have set"),
        (35, 37, "their hearts"),
        (38, 40, "upon their riches,"),
        (41, 47, "and they will hide"),
        (48, 50, "their treasures"),
        (51, 54, "when they flee"),
        (55, 60, "before their enemies;"),
        (61, 61, "because"),
        (62, 68, "they will not hide"),
        (69, 70, "those treasures"),
        (71, 72, "unto me,"),
        (73, 77, "cursed be they all"),
        (78, 81, "and their treasures;"),
        (82, 85, "and in that day"),
        (86, 92, "they shall be smitten,"),
        (93, 96, "saith"),
        (97, 98, "the Lord."),
    ],
    21: [
        (0, 3, "Behold ye,"),
        (4, 6, "the people of"),
        (7, 9, "this great city,"),
        (10, 12, "and hearken"),
        (13, 15, "unto my words;"),
        (16, 16, "yea,"),
        (17, 18, "hearken"),
        (19, 21, "unto the words"),
        (22, 25, "which saith"),
        (26, 27, "the Lord;"),
        (28, 29, "for behold,"),
        (30, 34, "he saith"),
        (35, 37, "ye are cursed"),
        (38, 39, "because of"),
        (40, 42, "your riches,"),
        (43, 46, "and also are cursed"),
        (47, 49, "your riches"),
        (50, 50, "because"),
        (51, 54, "ye have set"),
        (55, 57, "your hearts"),
        (58, 62, "upon those things,"),
        (63, 67, "and ye have not hearkened"),
        (68, 70, "unto the words of"),
        (71, 74, "him who gave"),
        (75, 76, "those riches"),
        (77, 79, "unto you."),
    ],
    22: [
        (0, 3, "Ye remember not"),
        (4, 8, "the Lord your God"),
        (9, 10, "in the things"),
        (11, 14, "with which he blessed"),
        (15, 15, "you,"),
        (16, 20, "but ye always remember"),
        (21, 23, "your riches,"),
        (24, 28, "but ye thank not"),
        (29, 34, "the Lord your God"),
        (35, 37, "for those riches;"),
        (38, 38, "yea,"),
        (39, 42, "are not drawn out"),
        (43, 45, "your hearts"),
        (46, 48, "unto the Lord,"),
        (49, 53, "but they swell"),
        (54, 57, "with great pride,"),
        (58, 60, "unto"),
        (61, 62, "boasting,"),
        (63, 65, "and unto"),
        (66, 68, "great swelling,"),
        (69, 69, "envyings,"),
        (70, 70, "strifes,"),
        (71, 71, "contentions,"),
        (72, 72, "malice,"),
        (73, 73, "persecutions,"),
        (74, 77, "and murders,"),
        (78, 82, "and all manner of iniquities."),
    ],
    23: [
        (0, 3, "For this cause"),
        (4, 6, "caused"),
        (7, 11, "the Lord God"),
        (12, 14, "that come"),
        (15, 16, "a curse"),
        (17, 21, "upon the land,"),
        (22, 25, "and also upon"),
        (26, 28, "your riches,"),
        (29, 33, "and this is caused"),
        (34, 35, "because of"),
        (36, 38, "your iniquities."),
    ],
    24: [
        (0, 0, "Yea,"),
        (1, 3, "wo unto"),
        (4, 5, "this people,"),
        (6, 7, "because of"),
        (8, 9, "this time"),
        (10, 12, "which has come,"),
        (13, 17, "ye cast out"),
        (18, 20, "the prophets,"),
        (21, 22, "and mock"),
        (23, 26, "them,"),
        (27, 30, "and stone them"),
        (31, 32, "with stones,"),
        (33, 36, "and slay them,"),
        (37, 42, "and do all manner of iniquity"),
        (43, 46, "unto them,"),
        (47, 51, "even as did"),
        (52, 55, "they of old."),
    ],
    25: [
        (0, 2, "And now"),
        (3, 6, "when ye speak,"),
        (7, 10, "ye say:"),
        (11, 17, "If our days had been"),
        (18, 20, "in the days of"),
        (21, 24, "our fathers of old,"),
        (25, 29, "we would not have slain"),
        (30, 30, "the prophets;"),
        (31, 35, "we would not have stoned"),
        (36, 39, "them with stones,"),
        (40, 46, "and cast them out."),
    ],
    26: [
        (0, 0, "Behold"),
        (1, 5, "your wickedness is greater"),
        (6, 9, "than theirs;"),
        (10, 10, "for"),
        (11, 14, "as liveth"),
        (15, 16, "the Lord,"),
        (17, 19, "if come"),
        (20, 21, "a prophet"),
        (22, 24, "among you"),
        (25, 27, "and declares"),
        (28, 30, "unto you"),
        (31, 35, "the word of the Lord,"),
        (36, 38, "which testifies"),
        (39, 41, "concerning"),
        (42, 43, "your sins"),
        (44, 45, "and iniquities,"),
        (46, 48, "ye are angry"),
        (49, 51, "with him,"),
        (52, 58, "and cast him out"),
        (59, 63, "and seek all manner of ways"),
        (64, 68, "to destroy him;"),
        (69, 69, "yea,"),
        (70, 75, "ye will say he is"),
        (76, 79, "a false prophet,"),
        (80, 86, "and he is a sinner,"),
        (87, 91, "and is from the devil,"),
        (92, 92, "because"),
        (93, 97, "he testifies"),
        (98, 99, "are evil"),
        (100, 102, "your works."),
    ],
    27: [
        (0, 1, "But behold,"),
        (2, 6, "if a man come"),
        (7, 11, "among you"),
        (12, 14, "and say:"),
        (15, 18, "Do this thing,"),
        (19, 23, "and there is no iniquity"),
        (24, 26, "in it;"),
        (27, 30, "do that thing"),
        (31, 38, "and ye shall not suffer;"),
        (39, 39, "yea,"),
        (40, 46, "he will say:"),
        (47, 47, "Walk"),
        (48, 50, "after"),
        (51, 53, "the pride of"),
        (54, 57, "your own hearts;"),
        (58, 58, "yea,"),
        (59, 59, "walk"),
        (60, 64, "after the pride"),
        (65, 68, "as seen"),
        (69, 73, "in your own eyes,"),
        (74, 78, "and do whatsoever"),
        (79, 82, "desireth"),
        (83, 85, "your hearts—"),
        (86, 91, "and if a man come"),
        (92, 96, "among you"),
        (97, 101, "and say these things,"),
        (102, 106, "ye will receive him,"),
        (107, 114, "and say he is a prophet."),
    ],
    28: [
        (0, 0, "Yea,"),
        (1, 7, "ye will lift him up,"),
        (8, 10, "and ye will give"),
        (11, 13, "unto him"),
        (14, 17, "of your substance;"),
        (18, 20, "ye will give"),
        (21, 23, "unto him"),
        (24, 27, "of your gold,"),
        (28, 31, "and of your silver,"),
        (32, 36, "and ye will clothe him"),
        (37, 39, "with costly apparel;"),
        (40, 41, "and because"),
        (42, 46, "he speaks"),
        (47, 49, "unto you"),
        (50, 52, "flattering words,"),
        (53, 56, "and he says"),
        (57, 61, "all things are well,"),
        (62, 68, "then ye seek no fault"),
        (69, 71, "with him."),
    ],
    29: [
        (0, 0, "O,"),
        (1, 2, "O ye"),
        (3, 5, "wicked generation"),
        (6, 7, "and perverse;"),
        (8, 9, "ye"),
        (10, 11, "stubborn people"),
        (12, 14, "and hardened,"),
        (15, 20, "how long"),
        (21, 23, "will ye suppose"),
        (24, 29, "will suffer you"),
        (30, 32, "the Lord?"),
        (33, 33, "Yea,"),
        (34, 39, "how long"),
        (40, 45, "will ye allow yourselves"),
        (46, 47, "to be led"),
        (48, 52, "by foolish and blind guides?"),
        (53, 53, "Yea,"),
        (54, 59, "how long"),
        (60, 63, "will ye choose"),
        (64, 65, "the darkness"),
        (66, 69, "rather than the light?"),
    ],
    30: [
        (0, 0, "Yea,"),
        (1, 1, "behold,"),
        (2, 7, "is already kindled"),
        (8, 10, "the anger of"),
        (11, 13, "the Lord"),
        (14, 18, "against you;"),
        (19, 19, "behold,"),
        (20, 22, "he hath cursed"),
        (23, 24, "the land"),
        (25, 26, "because of"),
        (27, 29, "your iniquity."),
    ],
    31: [
        (0, 1, "And behold,"),
        (2, 6, "the time comes"),
        (7, 12, "when he shall curse"),
        (13, 15, "your riches,"),
        (16, 18, "that they be slippery,"),
        (19, 22, "that ye cannot"),
        (23, 24, "hold"),
        (25, 26, "them;"),
        (27, 33, "and ye shall not be able"),
        (34, 35, "to retain"),
        (36, 37, "them"),
        (38, 43, "in the days of your poverty."),
    ],
    32: [
        (0, 3, "And in the days of"),
        (4, 6, "your poverty"),
        (7, 13, "ye shall cry"),
        (14, 16, "unto the Lord;"),
        (17, 22, "and shall be in vain"),
        (23, 26, "your crying,"),
        (27, 27, "for"),
        (28, 30, "has come"),
        (31, 34, "upon you"),
        (35, 37, "your desolation,"),
        (38, 40, "and is made sure"),
        (41, 43, "your destruction;"),
        (44, 47, "and then ye shall weep"),
        (48, 51, "and howl"),
        (52, 54, "in that day,"),
        (55, 58, "saith"),
        (59, 62, "the Lord of Hosts."),
        (63, 67, "And then ye shall lament,"),
        (68, 70, "and say:"),
    ],
    33: [
        (0, 0, "O,"),
        (1, 5, "would that I had repented,"),
        (6, 9, "and had not slain"),
        (10, 10, "the prophets,"),
        (11, 14, "and stoned them"),
        (15, 16, "with stones,"),
        (17, 23, "and cast them out."),
        (24, 24, "Yea,"),
        (25, 27, "in that day"),
        (28, 34, "ye shall say:"),
        (35, 40, "O had we remembered"),
        (41, 45, "the Lord our God"),
        (46, 48, "in the day"),
        (49, 53, "that he gave"),
        (54, 57, "unto us"),
        (58, 60, "our riches,"),
        (61, 64, "then would not be slippery"),
        (65, 69, "and slip away"),
        (70, 74, "from us;"),
        (75, 76, "for behold,"),
        (77, 80, "have departed"),
        (81, 83, "our riches"),
        (84, 88, "from us."),
    ],
    34: [
        (0, 0, "Behold,"),
        (1, 3, "we lay"),
        (4, 5, "a tool"),
        (6, 6, "here"),
        (7, 11, "but when dawns the morning"),
        (12, 13, "it is gone;"),
        (14, 15, "and behold,"),
        (16, 17, "are taken away"),
        (18, 20, "our swords"),
        (21, 25, "from us"),
        (26, 28, "in the day"),
        (29, 32, "we sought"),
        (33, 34, "them"),
        (35, 37, "for battle."),
    ],
    35: [
        (0, 0, "Yea,"),
        (1, 3, "we hid"),
        (4, 6, "our treasures"),
        (7, 11, "and they slipped away"),
        (12, 16, "from us,"),
        (17, 18, "because of"),
        (19, 21, "the curse of"),
        (22, 23, "the land."),
    ],
    36: [
        (0, 0, "O,"),
        (1, 5, "would that we had repented"),
        (6, 8, "in the day"),
        (9, 12, "that came"),
        (13, 17, "the word of the Lord"),
        (18, 21, "unto us;"),
        (22, 23, "for behold,"),
        (24, 25, "is cursed"),
        (26, 27, "the land,"),
        (28, 30, "and are slippery"),
        (31, 32, "all things,"),
        (33, 37, "and we cannot"),
        (38, 39, "hold"),
        (40, 43, "them."),
    ],
    37: [
        (0, 0, "Behold,"),
        (1, 4, "we are surrounded"),
        (5, 6, "by demons,"),
        (7, 7, "yea,"),
        (8, 11, "we are encircled"),
        (12, 14, "by the angels of"),
        (15, 17, "him who has sought"),
        (18, 19, "to destroy"),
        (20, 22, "our souls."),
        (23, 23, "Behold,"),
        (24, 26, "are exceedingly great"),
        (27, 29, "our iniquities."),
        (30, 32, "O Lord,"),
        (33, 37, "canst thou not"),
        (38, 40, "turn away"),
        (41, 42, "thine anger"),
        (43, 47, "from us?"),
        (48, 53, "And this shall be your language"),
        (54, 56, "which is fitting"),
        (57, 59, "in those days."),
    ],
    38: [
        (0, 1, "But behold,"),
        (2, 3, "are past"),
        (4, 5, "the days of"),
        (6, 9, "your probation;"),
        (10, 12, "ye have delayed"),
        (13, 15, "the day of"),
        (16, 18, "your salvation"),
        (19, 21, "until"),
        (22, 24, "exceedingly too late"),
        (25, 28, "enduring forever,"),
        (29, 31, "and is made sure"),
        (32, 34, "your destruction;"),
        (35, 35, "yea,"),
        (36, 36, "for"),
        (37, 39, "ye sought"),
        (40, 43, "all the days of"),
        (44, 46, "your lives"),
        (47, 49, "for the thing"),
        (50, 55, "which ye could not obtain;"),
        (56, 59, "and ye sought"),
        (60, 62, "for happiness"),
        (63, 66, "in the doing of"),
        (67, 68, "iniquity,"),
        (69, 72, "which thing"),
        (73, 77, "is contrary to"),
        (78, 80, "the nature of"),
        (81, 82, "that righteousness"),
        (83, 86, "which is in"),
        (87, 90, "our supreme Head"),
        (91, 92, "and Eternal."),
    ],
    39: [
        (0, 0, "O,"),
        (1, 2, "O ye"),
        (3, 6, "people of the land,"),
        (7, 12, "would that ye would hear"),
        (13, 15, "my words!"),
        (16, 19, "And I pray"),
        (20, 23, "that be turned away"),
        (24, 26, "the anger of"),
        (27, 28, "the Lord"),
        (29, 32, "from you,"),
        (33, 37, "and that ye repent"),
        (38, 40, "and be saved."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
