"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 40 — Alma's teaching
to his son Corianton concerning the resurrection of the dead: the appointed
time, the state of the soul between death and resurrection (paradise and
outer darkness), the reuniting of body and spirit, and the restoration.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits done up front against bom_books.json:
  v2  `toetutū—pe,` and `atoatoa—seia`  -> 52 tokens
  v11 `mai—Faauta,`                     -> 79 tokens
  v13 `leaga—auā` and `fale—ma`         -> 125 tokens

    python3 build_overrides_alma40.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 40

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "Now,"),
        (2, 4, "my son,"),
        (5, 9, "here are yet some"),
        (10, 13, "more things"),
        (14, 19, "I would say"),
        (20, 22, "unto thee;"),
        (23, 23, "for"),
        (24, 26, "I perceive"),
        (27, 30, "that thy mind is worried"),
        (31, 33, "concerning"),
        (34, 36, "the resurrection"),
        (37, 40, "of the dead."),
    ],
    2: [
        (0, 0, "Behold,"),
        (1, 4, "I say"),
        (5, 7, "unto you,"),
        (8, 11, "that there is no resurrection—"),
        (12, 12, "or,"),
        (13, 16, "I would say,"),
        (17, 20, "in other words,"),
        (21, 24, "this mortal"),
        (25, 27, "putteth not on"),
        (28, 32, "immortality,"),
        (33, 37, "this corruption"),
        (38, 40, "putteth not on"),
        (41, 44, "incorruption—"),
        (45, 46, "until after"),
        (47, 51, "the coming of Christ."),
    ],
    3: [
        (0, 0, "Behold,"),
        (1, 4, "he bringeth to pass"),
        (5, 7, "the resurrection"),
        (8, 11, "of the dead."),
        (12, 13, "But behold,"),
        (14, 16, "my son,"),
        (17, 20, "is not yet"),
        (21, 22, "the resurrection."),
        (23, 24, "Now,"),
        (25, 28, "I unfold"),
        (29, 31, "unto you"),
        (32, 33, "a mystery;"),
        (34, 37, "nevertheless,"),
        (38, 42, "there are many mysteries kept"),
        (43, 46, "that no one"),
        (47, 49, "knoweth them"),
        (50, 51, "save"),
        (52, 55, "God himself."),
        (56, 60, "But I show"),
        (61, 63, "unto you"),
        (64, 67, "one thing"),
        (68, 72, "which I have inquired"),
        (73, 75, "diligently"),
        (76, 78, "of God"),
        (79, 83, "that I might"),
        (84, 84, "know—"),
        (85, 87, "that thing"),
        (88, 90, "concerning"),
        (91, 92, "the resurrection."),
    ],
    4: [
        (0, 0, "Behold,"),
        (1, 5, "there is a time"),
        (6, 7, "appointed"),
        (8, 13, "that shall come forth"),
        (14, 15, "all men"),
        (16, 18, "from the dead."),
        (19, 20, "Now"),
        (21, 26, "when cometh"),
        (27, 28, "this time"),
        (29, 32, "no one"),
        (33, 35, "knoweth;"),
        (36, 36, "but"),
        (37, 41, "God knoweth"),
        (42, 45, "the time appointed."),
    ],
    5: [
        (0, 1, "Now,"),
        (2, 5, "whether there"),
        (6, 7, "shall be"),
        (8, 11, "one time,"),
        (12, 15, "or a time"),
        (16, 17, "the second,"),
        (18, 21, "or a time"),
        (22, 23, "the third,"),
        (24, 29, "that shall come forth"),
        (30, 30, "men"),
        (31, 33, "from the dead,"),
        (34, 36, "it mattereth not;"),
        (37, 37, "for"),
        (38, 42, "God knoweth"),
        (43, 45, "all these things;"),
        (46, 51, "and it sufficeth me"),
        (52, 53, "to know"),
        (54, 57, "that this is the state"),
        (58, 60, "which existeth—"),
        (61, 65, "there is a time"),
        (66, 67, "appointed"),
        (68, 71, "that shall rise"),
        (72, 73, "all men"),
        (74, 76, "from the dead."),
    ],
    6: [
        (0, 1, "Now,"),
        (2, 6, "there must needs be"),
        (7, 8, "a space"),
        (9, 12, "betwixt"),
        (13, 17, "the time of death"),
        (18, 21, "and the time of"),
        (22, 24, "the resurrection."),
    ],
    7: [
        (0, 2, "And now"),
        (3, 6, "I would inquire"),
        (7, 11, "what"),
        (12, 13, "becometh"),
        (14, 17, "of the souls of men"),
        (18, 23, "from this time of death"),
        (24, 28, "to the time"),
        (29, 30, "appointed"),
        (31, 34, "for the resurrection?"),
    ],
    8: [
        (0, 1, "Now"),
        (2, 5, "whether more than"),
        (6, 7, "one"),
        (8, 11, "the time appointed"),
        (12, 17, "for men to rise"),
        (18, 21, "it mattereth not;"),
        (22, 22, "for"),
        (23, 27, "all do not die"),
        (28, 32, "at once,"),
        (33, 37, "and this mattereth not;"),
        (38, 40, "all things"),
        (41, 45, "are as a day"),
        (46, 47, "one"),
        (48, 50, "with God,"),
        (51, 55, "and time only"),
        (56, 59, "is measured unto men."),
    ],
    9: [
        (0, 1, "Therefore,"),
        (2, 6, "there is a time"),
        (7, 8, "appointed"),
        (9, 10, "unto men"),
        (11, 14, "that they shall rise"),
        (15, 17, "from the dead;"),
        (18, 23, "and there is a space"),
        (24, 27, "between"),
        (28, 32, "the time of death"),
        (33, 36, "and the resurrection."),
        (37, 39, "And now,"),
        (40, 42, "concerning"),
        (43, 46, "this space of"),
        (47, 48, "time,"),
        (49, 53, "what"),
        (54, 55, "becometh"),
        (56, 59, "of the souls of men"),
        (60, 63, "is the thing"),
        (64, 68, "which I have inquired"),
        (69, 71, "of the Lord"),
        (72, 74, "diligently"),
        (75, 77, "to know;"),
        (78, 82, "and this is the thing"),
        (83, 85, "which I do know."),
    ],
    10: [
        (0, 4, "and when cometh"),
        (5, 6, "the time"),
        (7, 11, "when shall rise"),
        (12, 13, "all men,"),
        (14, 17, "then shall they know"),
        (18, 22, "that God knoweth"),
        (23, 26, "all the times appointed"),
        (27, 29, "unto man."),
    ],
    11: [
        (0, 1, "Now,"),
        (2, 4, "concerning"),
        (5, 9, "the state of the soul"),
        (10, 13, "between"),
        (14, 15, "death"),
        (16, 19, "and the resurrection—"),
        (20, 20, "Behold,"),
        (21, 23, "it hath been made known"),
        (24, 26, "unto me"),
        (27, 29, "by an angel,"),
        (30, 31, "that"),
        (32, 36, "the spirits of all men,"),
        (37, 40, "as soon"),
        (41, 44, "as they depart"),
        (45, 48, "from this mortal body,"),
        (49, 49, "yea,"),
        (50, 54, "the spirits of all men,"),
        (55, 58, "whether they be good"),
        (59, 61, "or evil,"),
        (62, 64, "are taken home"),
        (65, 67, "to that God"),
        (68, 72, "who gave"),
        (73, 76, "them"),
        (77, 78, "life."),
    ],
    12: [
        (0, 3, "And then shall it come to pass,"),
        (4, 8, "the spirits of them"),
        (9, 12, "who are righteous"),
        (13, 14, "are received"),
        (15, 18, "into a state of"),
        (19, 20, "happiness,"),
        (21, 23, "which is called"),
        (24, 26, "paradise,"),
        (27, 29, "a state"),
        (30, 32, "of rest,"),
        (33, 36, "a state of"),
        (37, 38, "peace,"),
        (39, 44, "where they shall rest"),
        (45, 50, "from all their troubles"),
        (51, 55, "and from all care,"),
        (56, 58, "and sorrow."),
    ],
    13: [
        (0, 4, "And then shall it come to pass,"),
        (5, 8, "the spirits of those"),
        (9, 10, "who are wicked,"),
        (11, 11, "yea,"),
        (12, 15, "who are evil—"),
        (16, 17, "for behold,"),
        (18, 21, "they have no"),
        (22, 23, "part"),
        (24, 28, "nor portion"),
        (29, 32, "of the Spirit of"),
        (33, 34, "the Lord;"),
        (35, 36, "for behold,"),
        (37, 39, "they chose"),
        (40, 41, "evil works"),
        (42, 45, "rather than good;"),
        (46, 47, "therefore"),
        (48, 50, "did enter"),
        (51, 55, "the spirit of the devil"),
        (56, 60, "into them,"),
        (61, 63, "and take possession"),
        (64, 66, "of their house—"),
        (67, 71, "and these"),
        (72, 76, "shall be cast"),
        (77, 77, "out"),
        (78, 82, "into outer darkness;"),
        (83, 84, "there"),
        (85, 89, "shall be"),
        (90, 91, "weeping,"),
        (92, 94, "and wailing,"),
        (95, 99, "and gnashing of teeth;"),
        (100, 104, "and the cause of"),
        (105, 106, "this thing"),
        (107, 108, "because of"),
        (109, 112, "their own iniquity,"),
        (113, 116, "being led captive"),
        (117, 118, "them"),
        (119, 122, "by the will of"),
        (123, 124, "the devil."),
    ],
    14: [
        (0, 1, "Now,"),
        (2, 5, "this is the state"),
        (6, 9, "of the souls of those"),
        (10, 11, "who are wicked,"),
        (12, 12, "yea,"),
        (13, 15, "in darkness,"),
        (16, 19, "and a state"),
        (20, 24, "of awful dreadfulness"),
        (25, 27, "of the looking"),
        (28, 30, "and fear"),
        (31, 34, "for the indignation of"),
        (35, 36, "God"),
        (37, 41, "like a burning fire"),
        (42, 46, "which shall come"),
        (47, 51, "upon them;"),
        (52, 56, "thus they"),
        (57, 58, "remain"),
        (59, 61, "in this state,"),
        (62, 63, "as well as"),
        (64, 66, "the righteous"),
        (67, 69, "in paradise,"),
        (70, 74, "until the time"),
        (75, 79, "of their resurrection."),
    ],
    15: [
        (0, 1, "Now,"),
        (2, 6, "there are some"),
        (7, 8, "that have understood"),
        (9, 10, "that"),
        (11, 14, "this state of"),
        (15, 16, "happiness"),
        (17, 20, "and this state of"),
        (21, 22, "misery"),
        (23, 25, "of the soul,"),
        (26, 31, "before the resurrection,"),
        (32, 36, "was a first resurrection."),
        (37, 37, "Yea,"),
        (38, 40, "I admit"),
        (41, 45, "it may be termed"),
        (46, 48, "a resurrection,"),
        (49, 52, "the raising"),
        (53, 55, "of the spirit"),
        (56, 59, "or the soul"),
        (60, 63, "and their consignation"),
        (64, 66, "to happiness"),
        (67, 70, "or misery,"),
        (71, 73, "according to"),
        (74, 78, "the words which have been spoken."),
    ],
    16: [
        (0, 1, "And behold,"),
        (2, 5, "again it hath been spoken,"),
        (6, 7, "that"),
        (8, 10, "there is"),
        (11, 13, "a first resurrection;"),
        (14, 18, "a resurrection"),
        (19, 22, "of all them"),
        (23, 27, "who have been,"),
        (28, 30, "or those"),
        (31, 33, "who are,"),
        (34, 36, "or those"),
        (37, 41, "who shall be,"),
        (42, 46, "even down to"),
        (47, 51, "the resurrection of Christ"),
        (52, 54, "from the dead."),
    ],
    17: [
        (0, 1, "Now,"),
        (2, 6, "we do not suppose that"),
        (7, 10, "this first resurrection,"),
        (11, 14, "which is spoken of"),
        (15, 17, "in this manner,"),
        (18, 22, "is the resurrection"),
        (23, 24, "of men"),
        (25, 28, "and their consignation"),
        (29, 31, "to happiness"),
        (32, 35, "or misery."),
        (36, 41, "Ye cannot suppose"),
        (42, 42, "that"),
        (43, 46, "is the meaning"),
        (47, 49, "of this thing."),
    ],
    18: [
        (0, 0, "Behold,"),
        (1, 4, "I say"),
        (5, 7, "unto you,"),
        (8, 9, "Nay;"),
        (10, 13, "but it meaneth"),
        (14, 17, "the reuniting"),
        (18, 20, "of the soul"),
        (21, 23, "with the body"),
        (24, 26, "of those"),
        (27, 32, "from the days of Adam"),
        (33, 37, "down to"),
        (38, 41, "the resurrection of Christ."),
    ],
    19: [
        (0, 1, "Now,"),
        (2, 3, "whether be reunited"),
        (4, 8, "at once"),
        (9, 11, "the souls and bodies"),
        (12, 16, "of those"),
        (17, 18, "who are spoken of,"),
        (19, 22, "the wicked"),
        (23, 25, "as well as"),
        (26, 28, "the righteous,"),
        (29, 33, "I do not say;"),
        (34, 37, "but let it suffice"),
        (38, 40, "that I say"),
        (41, 46, "they shall all rise"),
        (47, 47, "forth;"),
        (48, 50, "or in"),
        (51, 53, "other words,"),
        (54, 58, "cometh to pass"),
        (59, 61, "their resurrection"),
        (62, 65, "before cometh"),
        (66, 67, "the resurrection"),
        (68, 72, "of those"),
        (73, 74, "who die"),
        (75, 77, "after there is past"),
        (78, 82, "the resurrection of Christ."),
    ],
    20: [
        (0, 1, "Now,"),
        (2, 4, "my son,"),
        (5, 9, "I do not say"),
        (10, 12, "cometh"),
        (13, 15, "their resurrection"),
        (16, 21, "at the resurrection of Christ;"),
        (22, 23, "but behold,"),
        (24, 27, "I give"),
        (28, 30, "my opinion,"),
        (31, 34, "are reunited"),
        (35, 37, "the souls and bodies,"),
        (38, 41, "of the righteous,"),
        (42, 47, "at the resurrection of Christ,"),
        (48, 51, "and his ascension"),
        (52, 54, "into heaven."),
    ],
    21: [
        (0, 2, "But whether at"),
        (3, 5, "his resurrection"),
        (6, 10, "or after,"),
        (11, 15, "I do not say;"),
        (16, 20, "but this much"),
        (21, 23, "a thing"),
        (24, 27, "I say,"),
        (28, 29, "that"),
        (30, 34, "there is a space"),
        (35, 38, "between"),
        (39, 40, "death"),
        (41, 45, "and the resurrection of"),
        (46, 47, "the body,"),
        (48, 51, "and a state of"),
        (52, 53, "the soul"),
        (54, 56, "in happiness"),
        (57, 60, "or in misery"),
        (61, 65, "until the time"),
        (66, 70, "which is appointed of God"),
        (71, 74, "that shall come forth"),
        (75, 77, "the dead,"),
        (78, 79, "and be reunited,"),
        (80, 83, "both soul"),
        (84, 86, "and body,"),
        (87, 88, "and be brought"),
        (89, 90, "to stand"),
        (91, 95, "before God,"),
        (96, 97, "and be judged"),
        (98, 100, "according to"),
        (101, 103, "their works."),
    ],
    22: [
        (0, 0, "Yea,"),
        (1, 3, "this"),
        (4, 6, "bringeth about"),
        (7, 8, "the restoration"),
        (9, 10, "of the things"),
        (11, 14, "which have been spoken"),
        (15, 17, "by the mouths of the prophets."),
    ],
    23: [
        (0, 2, "The soul"),
        (3, 6, "shall be restored"),
        (7, 9, "to the body,"),
        (10, 12, "and the body"),
        (13, 15, "to the soul;"),
        (16, 16, "yea,"),
        (17, 21, "and shall be restored"),
        (22, 24, "every limb"),
        (25, 27, "and joint"),
        (28, 30, "to its body;"),
        (31, 31, "yea,"),
        (32, 36, "even a hair"),
        (37, 39, "of the head"),
        (40, 44, "shall not be lost"),
        (45, 45, "at all;"),
        (46, 50, "but shall be restored"),
        (51, 52, "all things"),
        (53, 56, "to their frame"),
        (57, 61, "proper and perfect."),
    ],
    24: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 9, "this is the restoration"),
        (10, 14, "of which hath been spoken"),
        (15, 17, "by the mouths of the prophets—"),
    ],
    25: [
        (0, 4, "And then shall shine forth"),
        (5, 7, "the righteous"),
        (8, 11, "in the kingdom of"),
        (12, 13, "God."),
    ],
    26: [
        (0, 1, "But behold,"),
        (2, 4, "cometh"),
        (5, 8, "an awful death"),
        (9, 12, "upon those"),
        (13, 14, "who are wicked;"),
        (15, 15, "for"),
        (16, 19, "they die"),
        (20, 23, "as to things"),
        (24, 27, "pertaining to righteousness;"),
        (28, 28, "for"),
        (29, 32, "they are unclean,"),
        (33, 37, "and no thing"),
        (38, 39, "unclean"),
        (40, 43, "can inherit"),
        (44, 47, "the kingdom of"),
        (48, 49, "God;"),
        (50, 55, "but they are cast"),
        (56, 57, "out,"),
        (58, 59, "and consigned"),
        (60, 63, "to partake of the fruits"),
        (64, 69, "of their doings"),
        (70, 74, "or their works,"),
        (75, 77, "which have been evil;"),
        (78, 80, "and they drink"),
        (81, 81, "the dregs"),
        (82, 85, "of a bitter cup."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
