"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 32 — Alma preaches
to the poor among the Zoramites, who are cast out of their synagogues; his
great discourse on faith, likening the word unto a seed planted in the heart.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits done up front against bom_books.json:
  v9  `faia?—ona`         -> 39 tokens
  v15 `faamanuiaina—ioe,` -> 53 tokens
  v28 `lava—Ua`           -> 134 tokens

    python3 build_overrides_alma32.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 32

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And it came to pass that"),
        (3, 6, "they went forth,"),
        (7, 11, "and began to preach"),
        (12, 15, "the word of"),
        (16, 17, "God"),
        (18, 20, "unto the people,"),
        (21, 24, "by entering"),
        (25, 28, "into their synagogues,"),
        (29, 32, "and into their houses;"),
        (33, 33, "yea,"),
        (34, 38, "and even"),
        (39, 42, "they did preach"),
        (43, 44, "the word"),
        (45, 48, "in their streets."),
    ],
    2: [
        (0, 2, "And it came to pass that"),
        (3, 5, "after"),
        (6, 8, "much labor"),
        (9, 13, "among them,"),
        (14, 18, "they began to have"),
        (19, 21, "success"),
        (22, 24, "among"),
        (25, 27, "the class of"),
        (28, 29, "poor people;"),
        (30, 31, "for behold,"),
        (32, 35, "they were cast"),
        (36, 37, "out"),
        (38, 39, "from the synagogues"),
        (40, 43, "because of the coarseness"),
        (44, 47, "of their apparel—"),
    ],
    3: [
        (0, 1, "Therefore"),
        (2, 6, "they were not permitted"),
        (7, 9, "to enter"),
        (10, 13, "into their synagogues"),
        (14, 18, "to worship God,"),
        (19, 19, "for"),
        (20, 24, "their brethren supposed"),
        (25, 26, "that"),
        (27, 29, "they were filthy;"),
        (30, 31, "therefore"),
        (32, 34, "they were poor;"),
        (35, 35, "yea,"),
        (36, 40, "their brethren esteemed"),
        (41, 44, "them"),
        (45, 47, "as dross;"),
        (48, 49, "therefore"),
        (50, 52, "they were poor"),
        (53, 55, "as to"),
        (56, 59, "things of the world;"),
        (60, 64, "and they were also poor"),
        (65, 67, "in heart."),
    ],
    4: [
        (0, 1, "Now,"),
        (2, 6, "as was teaching and speaking"),
        (7, 7, "Alma"),
        (8, 9, "unto the people"),
        (10, 12, "upon"),
        (13, 16, "the hill Onidah,"),
        (17, 19, "there came"),
        (20, 22, "unto him"),
        (23, 25, "a great multitude"),
        (26, 27, "of people,"),
        (28, 31, "those"),
        (32, 33, "of whom"),
        (34, 38, "we have been speaking,"),
        (39, 40, "who"),
        (41, 42, "were poor"),
        (43, 45, "in heart,"),
        (46, 50, "because of their poverty"),
        (51, 53, "as to"),
        (54, 57, "the things of the world."),
    ],
    5: [
        (0, 4, "And they came"),
        (5, 6, "unto Alma;"),
        (7, 10, "and said"),
        (11, 13, "unto him"),
        (14, 16, "the foremost one"),
        (17, 19, "among them:"),
        (20, 20, "Behold,"),
        (21, 25, "what"),
        (26, 27, "shall do"),
        (28, 31, "these my brethren,"),
        (32, 32, "for"),
        (33, 36, "they are despised"),
        (37, 39, "of all men"),
        (40, 44, "because of their poverty,"),
        (45, 45, "yea,"),
        (46, 48, "and more especially"),
        (49, 52, "by our priests;"),
        (53, 53, "for"),
        (54, 58, "they have cast us"),
        (59, 60, "out"),
        (61, 65, "from our synagogues"),
        (66, 70, "which we labored abundantly"),
        (71, 72, "to build"),
        (73, 77, "with our own hands;"),
        (78, 83, "and they have cast us"),
        (84, 85, "out"),
        (86, 87, "because of"),
        (88, 91, "our exceeding poverty;"),
        (92, 96, "and we have no place"),
        (97, 100, "wherein to worship"),
        (101, 104, "our God;"),
        (105, 106, "and behold,"),
        (107, 111, "what"),
        (112, 114, "shall we do?"),
    ],
    6: [
        (0, 2, "And now"),
        (3, 7, "when Alma heard"),
        (8, 10, "these words,"),
        (11, 15, "he turned about,"),
        (16, 19, "with set directly"),
        (20, 21, "his face"),
        (22, 24, "towards him,"),
        (25, 29, "and he beheld"),
        (30, 33, "with great joy;"),
        (34, 34, "for"),
        (35, 38, "he beheld"),
        (39, 43, "that they were truly humbled"),
        (44, 47, "by their afflictions,"),
        (48, 51, "and they were prepared"),
        (52, 53, "to hear"),
        (54, 56, "the word."),
    ],
    7: [
        (0, 1, "Therefore"),
        (2, 7, "he said no more"),
        (8, 8, "thereof"),
        (9, 11, "any other thing"),
        (12, 14, "to the other"),
        (15, 17, "multitude;"),
        (18, 22, "but he stretched forth"),
        (23, 24, "his hand,"),
        (25, 27, "and cried"),
        (28, 31, "unto them"),
        (32, 37, "whom he beheld"),
        (38, 39, "them,"),
        (40, 41, "who"),
        (42, 44, "were truly penitent,"),
        (45, 47, "and said"),
        (48, 51, "unto them:"),
    ],
    8: [
        (0, 3, "I behold"),
        (4, 7, "that ye are lowly in heart;"),
        (8, 11, "and if so,"),
        (12, 13, "blessed are ye."),
    ],
    9: [
        (0, 0, "Behold"),
        (1, 3, "hath said"),
        (4, 6, "your brother,"),
        (7, 11, "What"),
        (12, 14, "shall we do?—"),
        (15, 15, "for"),
        (16, 19, "we are cast"),
        (20, 21, "out"),
        (22, 26, "from our synagogues,"),
        (27, 32, "that we cannot"),
        (33, 34, "worship"),
        (35, 38, "our God."),
    ],
    10: [
        (0, 0, "Behold"),
        (1, 4, "I say"),
        (5, 7, "unto you,"),
        (8, 11, "do ye suppose"),
        (12, 16, "that ye cannot"),
        (17, 18, "worship"),
        (19, 21, "God"),
        (22, 24, "save it be"),
        (25, 26, "only"),
        (27, 28, "within"),
        (29, 31, "your synagogues?"),
    ],
    11: [
        (0, 5, "And moreover,"),
        (6, 9, "I would ask,"),
        (10, 13, "do ye suppose"),
        (14, 18, "that ye ought not"),
        (19, 20, "to worship"),
        (21, 23, "God"),
        (24, 25, "but only"),
        (26, 27, "once"),
        (28, 30, "in a week?"),
    ],
    12: [
        (0, 3, "I say"),
        (4, 6, "unto you,"),
        (7, 10, "it is well"),
        (11, 14, "that ye are cast"),
        (15, 16, "out"),
        (17, 21, "from your synagogues,"),
        (22, 26, "that ye may"),
        (27, 28, "be humble,"),
        (29, 34, "and that ye may"),
        (35, 36, "learn"),
        (37, 38, "wisdom;"),
        (39, 39, "for"),
        (40, 44, "it is needful that ye learn"),
        (45, 46, "wisdom;"),
        (47, 48, "for because of"),
        (49, 52, "ye being cast"),
        (53, 54, "out"),
        (55, 59, "in being despised"),
        (60, 63, "by your brethren"),
        (64, 65, "because of"),
        (66, 69, "your exceeding poverty,"),
        (70, 73, "ye are brought"),
        (74, 77, "to the lowliness of"),
        (78, 79, "heart;"),
        (80, 80, "for"),
        (81, 85, "necessarily are brought"),
        (86, 87, "ye"),
        (88, 89, "to be humbled."),
    ],
    13: [
        (0, 2, "And now,"),
        (3, 6, "because ye are compelled"),
        (7, 9, "to be humble"),
        (10, 11, "blessed are ye;"),
        (12, 15, "for a man"),
        (16, 19, "sometimes,"),
        (20, 24, "if he is compelled"),
        (25, 26, "to be humble,"),
        (27, 30, "he seeketh"),
        (31, 32, "repentance;"),
        (33, 35, "and now"),
        (36, 38, "surely,"),
        (39, 42, "whosoever repenteth"),
        (43, 46, "shall find"),
        (47, 49, "mercy;"),
        (50, 55, "and he that findeth"),
        (56, 58, "mercy"),
        (59, 60, "and endureth"),
        (61, 65, "to the end,"),
        (66, 69, "the same"),
        (70, 73, "shall be saved."),
    ],
    14: [
        (0, 2, "And now,"),
        (3, 6, "as I"),
        (7, 8, "said"),
        (9, 11, "unto you,"),
        (12, 14, "because"),
        (15, 17, "ye were compelled"),
        (18, 20, "to be humble"),
        (21, 24, "ye were blessed,"),
        (25, 30, "do ye not suppose"),
        (31, 35, "that more blessed are"),
        (36, 38, "they"),
        (39, 43, "who humble"),
        (44, 46, "themselves"),
        (47, 50, "because of the word?"),
    ],
    15: [
        (0, 0, "Yea,"),
        (1, 4, "he that"),
        (5, 7, "humbleth"),
        (8, 10, "himself,"),
        (11, 12, "and repenteth"),
        (13, 15, "of his sins,"),
        (16, 17, "and endureth"),
        (18, 22, "to the end,"),
        (23, 26, "the same"),
        (27, 30, "shall be blessed—"),
        (31, 31, "yea,"),
        (32, 36, "much more blessed"),
        (37, 40, "than they"),
        (41, 44, "who are compelled"),
        (45, 46, "to be humble"),
        (47, 48, "because of"),
        (49, 52, "their exceeding poverty."),
    ],
    16: [
        (0, 1, "Therefore,"),
        (2, 4, "blessed are they"),
        (5, 9, "who humble"),
        (10, 12, "themselves"),
        (13, 17, "without being compelled"),
        (18, 19, "to be humble;"),
        (20, 21, "or rather,"),
        (22, 25, "in other words,"),
        (26, 30, "blessed is he that"),
        (31, 32, "believeth"),
        (33, 36, "in the word of"),
        (37, 38, "God,"),
        (39, 41, "and is baptized"),
        (42, 46, "without stubbornness"),
        (47, 49, "of heart,"),
        (50, 50, "yea,"),
        (51, 55, "without being"),
        (56, 56, "brought"),
        (57, 59, "to know"),
        (60, 61, "the word,"),
        (62, 63, "or even compelled"),
        (64, 66, "to know,"),
        (67, 71, "before they will believe."),
    ],
    17: [
        (0, 0, "Yea,"),
        (1, 5, "there are many"),
        (6, 10, "who do say:"),
        (11, 15, "If thou wilt show"),
        (16, 19, "unto us"),
        (20, 21, "a sign"),
        (22, 24, "from heaven,"),
        (25, 29, "then we shall know"),
        (30, 32, "of a surety;"),
        (33, 37, "then we shall believe."),
    ],
    18: [
        (0, 1, "Now"),
        (2, 5, "I ask,"),
        (6, 10, "is this faith?"),
        (11, 11, "Behold,"),
        (12, 15, "I say"),
        (16, 18, "unto you,"),
        (19, 20, "Nay;"),
        (21, 21, "for"),
        (22, 25, "if knoweth"),
        (26, 27, "a man"),
        (28, 29, "a thing,"),
        (30, 33, "he hath no cause"),
        (34, 36, "for him"),
        (37, 39, "to believe,"),
        (40, 40, "for"),
        (41, 43, "he knoweth it."),
    ],
    19: [
        (0, 2, "And now,"),
        (3, 7, "how much more"),
        (8, 11, "cursed is he"),
        (12, 16, "that knoweth"),
        (17, 21, "the will of God"),
        (22, 26, "and doeth it not,"),
        (27, 30, "than he"),
        (31, 36, "that only"),
        (37, 37, "believeth,"),
        (38, 43, "or only hath"),
        (44, 45, "cause"),
        (46, 48, "to believe,"),
        (49, 51, "and falleth"),
        (52, 54, "into transgression?"),
    ],
    20: [
        (0, 1, "Now"),
        (2, 6, "ye must judge"),
        (7, 9, "concerning"),
        (10, 11, "this thing."),
        (12, 12, "Behold,"),
        (13, 16, "I say"),
        (17, 19, "unto you,"),
        (20, 24, "even as it is"),
        (25, 28, "on the one hand"),
        (29, 33, "so also is it"),
        (34, 37, "on the other hand;"),
        (38, 42, "and it shall be done"),
        (43, 45, "unto every man"),
        (46, 48, "according to"),
        (49, 50, "his work."),
    ],
    21: [
        (0, 2, "And now,"),
        (3, 6, "as I"),
        (7, 8, "said"),
        (9, 13, "concerning faith—"),
        (14, 16, "faith"),
        (17, 20, "is not"),
        (21, 22, "the having of"),
        (23, 26, "a perfect knowledge"),
        (27, 28, "of things;"),
        (29, 30, "therefore"),
        (31, 35, "if ye have"),
        (36, 37, "faith"),
        (38, 40, "ye hope"),
        (41, 42, "for things"),
        (43, 45, "which are not seen,"),
        (46, 48, "which are true."),
    ],
    22: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 7, "I say"),
        (8, 10, "unto you,"),
        (11, 14, "and I would"),
        (15, 17, "that ye should remember,"),
        (18, 22, "that God is merciful"),
        (23, 25, "unto all"),
        (26, 29, "who believe"),
        (30, 32, "on his name;"),
        (33, 34, "therefore"),
        (35, 38, "he desireth"),
        (39, 43, "in the first place,"),
        (44, 46, "that ye should believe,"),
        (47, 47, "yea,"),
        (48, 51, "even on his word."),
    ],
    23: [
        (0, 2, "And now,"),
        (3, 7, "he imparteth"),
        (8, 9, "his word"),
        (10, 11, "unto men"),
        (12, 16, "by angels,"),
        (17, 17, "yea,"),
        (18, 22, "not only"),
        (23, 23, "men"),
        (24, 27, "but women also."),
        (28, 29, "Now"),
        (30, 34, "this is not all;"),
        (35, 37, "little children"),
        (38, 41, "do have words"),
        (42, 44, "given"),
        (45, 48, "unto them"),
        (49, 53, "many times,"),
        (54, 56, "which confound"),
        (57, 58, "the wise"),
        (59, 62, "and the learned."),
    ],
    24: [
        (0, 2, "And now,"),
        (3, 6, "my beloved brethren,"),
        (7, 7, "as"),
        (8, 12, "ye have desired to know"),
        (13, 15, "of me"),
        (16, 20, "what ye should do,"),
        (21, 21, "because"),
        (22, 24, "ye are afflicted"),
        (25, 28, "and cast out—"),
        (29, 30, "now"),
        (31, 34, "I do not desire"),
        (35, 37, "that ye should suppose"),
        (38, 39, "that"),
        (40, 42, "I judge"),
        (43, 45, "you"),
        (46, 46, "save"),
        (47, 50, "according to"),
        (51, 53, "that which is true—"),
    ],
    25: [
        (0, 0, "For"),
        (1, 5, "I do not mean"),
        (6, 9, "that ye all were compelled"),
        (10, 12, "to humble"),
        (13, 14, "yourselves;"),
        (15, 15, "for"),
        (16, 20, "I verily believe"),
        (21, 25, "that there are some"),
        (26, 29, "among you"),
        (30, 34, "who would humble"),
        (35, 37, "themselves,"),
        (38, 40, "no matter"),
        (41, 44, "what circumstances"),
        (45, 49, "they might be in."),
    ],
    26: [
        (0, 1, "Now,"),
        (2, 5, "as I"),
        (6, 7, "said"),
        (8, 12, "concerning faith—"),
        (13, 14, "that"),
        (15, 19, "it is not a knowledge"),
        (20, 21, "perfect—"),
        (22, 24, "even so is it also"),
        (25, 27, "with my words."),
        (28, 33, "Ye cannot know"),
        (34, 36, "at first"),
        (37, 39, "their surety"),
        (40, 42, "unto perfection,"),
        (43, 47, "any more than"),
        (48, 49, "to say"),
        (50, 52, "that faith"),
        (53, 57, "is a perfect knowledge."),
    ],
    27: [
        (0, 1, "But behold,"),
        (2, 6, "if ye will awake"),
        (7, 8, "and arouse"),
        (9, 11, "your faculties,"),
        (12, 16, "even to an experiment"),
        (17, 19, "upon my words,"),
        (20, 21, "and exercise"),
        (22, 24, "a particle"),
        (25, 27, "of faith,"),
        (28, 28, "yea,"),
        (29, 31, "even if"),
        (32, 36, "ye can"),
        (37, 37, "do"),
        (38, 42, "no other thing"),
        (43, 47, "than to desire to believe,"),
        (48, 49, "let"),
        (50, 51, "this desire"),
        (52, 53, "work"),
        (54, 58, "within you,"),
        (59, 62, "even until"),
        (63, 66, "ye believe"),
        (67, 69, "in a manner"),
        (70, 74, "that ye can"),
        (75, 76, "give"),
        (77, 79, "a place"),
        (80, 83, "for a portion of"),
        (84, 85, "my words."),
    ],
    28: [
        (0, 1, "Now,"),
        (2, 6, "we will compare"),
        (7, 8, "the word"),
        (9, 11, "unto a seed."),
        (12, 13, "Now,"),
        (14, 18, "if ye give"),
        (19, 20, "place,"),
        (21, 25, "that may be planted"),
        (26, 28, "a seed"),
        (29, 31, "in your heart,"),
        (32, 32, "behold,"),
        (33, 37, "if it be a true seed,"),
        (38, 42, "or a good seed,"),
        (43, 47, "if ye cast it not"),
        (48, 49, "out"),
        (50, 53, "by your unbelief,"),
        (54, 57, "that ye will resist"),
        (58, 62, "the Spirit of the Lord,"),
        (63, 63, "behold,"),
        (64, 68, "it will begin"),
        (69, 70, "to swell"),
        (71, 75, "within your breasts;"),
        (76, 80, "and when ye feel"),
        (81, 82, "these motions"),
        (83, 86, "of the swelling,"),
        (87, 92, "ye will begin"),
        (93, 94, "to say"),
        (95, 98, "within yourself—"),
        (99, 102, "It must needs be good"),
        (103, 104, "this seed,"),
        (105, 109, "or the word is good,"),
        (110, 110, "for"),
        (111, 115, "it beginneth to enlarge"),
        (116, 117, "my soul;"),
        (118, 118, "yea,"),
        (119, 123, "it beginneth to enlighten"),
        (124, 125, "my understanding,"),
        (126, 126, "yea,"),
        (127, 130, "it beginneth to be delicious"),
        (131, 133, "to me."),
    ],
    29: [
        (0, 2, "Now behold,"),
        (3, 6, "would not be increased"),
        (7, 9, "by this"),
        (10, 11, "your faith?"),
        (12, 15, "I say"),
        (16, 18, "unto you,"),
        (19, 19, "Yea;"),
        (20, 23, "nevertheless"),
        (24, 27, "it hath not grown up"),
        (28, 32, "to a perfect knowledge."),
    ],
    30: [
        (0, 1, "But behold,"),
        (2, 6, "as the seed swelleth,"),
        (7, 9, "and sprouteth,"),
        (10, 13, "and beginneth to grow,"),
        (14, 16, "then must needs"),
        (17, 20, "ye say"),
        (21, 24, "the seed is good;"),
        (25, 26, "for behold"),
        (27, 29, "it swelleth,"),
        (30, 32, "and sprouteth,"),
        (33, 37, "and beginneth to grow."),
        (38, 40, "And now,"),
        (41, 41, "behold,"),
        (42, 45, "will not be strengthened"),
        (46, 48, "by this"),
        (49, 50, "your faith?"),
        (51, 51, "Yea,"),
        (52, 56, "it will strengthen"),
        (57, 58, "your faith:"),
        (59, 59, "for"),
        (60, 64, "ye will"),
        (65, 65, "say"),
        (66, 68, "I know"),
        (69, 73, "this is a good seed;"),
        (74, 75, "for behold"),
        (76, 78, "it sprouteth"),
        (79, 82, "and beginneth to grow."),
    ],
    31: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 7, "are ye sure"),
        (8, 10, "that this seed"),
        (11, 15, "is a good seed?"),
        (16, 19, "I say"),
        (20, 22, "unto you,"),
        (23, 23, "Yea;"),
        (24, 24, "for"),
        (25, 27, "bringeth forth"),
        (28, 29, "every seed"),
        (30, 33, "unto its own likeness."),
    ],
    32: [
        (0, 1, "Therefore,"),
        (2, 6, "if a seed groweth,"),
        (7, 10, "it is a good seed;"),
        (11, 15, "but if it groweth not,"),
        (16, 16, "behold"),
        (17, 19, "it is not good,"),
        (20, 21, "therefore"),
        (22, 25, "it is cast away."),
    ],
    33: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 4, "because"),
        (5, 9, "ye have tried the experiment,"),
        (10, 13, "and planted the seed,"),
        (14, 17, "and it swelleth"),
        (18, 20, "and sprouteth,"),
        (21, 25, "and beginneth to grow,"),
        (26, 30, "ye must needs"),
        (31, 31, "know"),
        (32, 35, "the seed is good."),
    ],
    34: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 7, "is perfect"),
        (8, 9, "your knowledge?"),
        (10, 10, "Yea,"),
        (11, 14, "your knowledge is perfect"),
        (15, 17, "in that thing,"),
        (18, 22, "and your faith is dormant;"),
        (23, 26, "and this because"),
        (27, 30, "ye know,"),
        (31, 34, "for ye know"),
        (35, 39, "the word hath swelled"),
        (40, 43, "your souls,"),
        (44, 48, "and ye also know"),
        (49, 51, "it hath sprouted up,"),
        (52, 56, "that beginneth to be enlightened"),
        (57, 59, "your understanding,"),
        (60, 64, "and beginneth to expand"),
        (65, 67, "your mind."),
    ],
    35: [
        (0, 2, "O then,"),
        (3, 7, "is not real"),
        (8, 9, "this thing?"),
        (10, 13, "I say"),
        (14, 16, "unto you,"),
        (17, 17, "Yea,"),
        (18, 18, "because"),
        (19, 22, "it is light;"),
        (23, 27, "and whatsoever"),
        (28, 29, "is light,"),
        (30, 31, "is good,"),
        (32, 34, "because it is discernible,"),
        (35, 36, "therefore"),
        (37, 41, "ye must know"),
        (42, 42, "thereby"),
        (43, 44, "it is good;"),
        (45, 48, "and now behold,"),
        (49, 54, "after ye have tasted"),
        (55, 57, "this light"),
        (58, 61, "is perfect"),
        (62, 63, "your knowledge?"),
    ],
    36: [
        (0, 0, "Behold"),
        (1, 4, "I say"),
        (5, 7, "unto you,"),
        (8, 9, "Nay;"),
        (10, 14, "neither must ye"),
        (15, 16, "lay aside"),
        (17, 18, "your faith,"),
        (19, 19, "for"),
        (20, 24, "ye have only exercised"),
        (25, 27, "your faith"),
        (28, 32, "to plant the seed"),
        (33, 38, "that ye might try"),
        (39, 40, "the experiment"),
        (41, 43, "to know"),
        (44, 48, "if the seed was good."),
    ],
    37: [
        (0, 1, "And behold,"),
        (2, 6, "as beginneth to grow"),
        (7, 9, "the tree,"),
        (10, 14, "ye will"),
        (15, 15, "say:"),
        (16, 19, "Let us nourish it"),
        (20, 23, "with great care,"),
        (24, 28, "that it may get root,"),
        (29, 32, "that it may"),
        (33, 34, "grow up,"),
        (35, 39, "and bring forth fruit"),
        (40, 42, "unto us."),
        (43, 46, "And now behold,"),
        (47, 52, "if ye nourish it"),
        (53, 56, "with much care"),
        (57, 60, "it will get root,"),
        (61, 63, "and grow up,"),
        (64, 66, "and bring forth fruit."),
    ],
    38: [
        (0, 4, "But if ye neglect"),
        (5, 7, "the tree,"),
        (8, 12, "and take no thought"),
        (13, 15, "for its nourishment,"),
        (16, 16, "behold"),
        (17, 21, "it will not get root"),
        (22, 23, "thereof;"),
        (24, 28, "and when cometh"),
        (29, 33, "the heat of the sun"),
        (34, 36, "and scorcheth it,"),
        (37, 39, "because"),
        (40, 44, "it hath no root,"),
        (45, 48, "it withers away,"),
        (49, 54, "and ye pluck"),
        (55, 56, "it up"),
        (57, 60, "and cast it out."),
    ],
    39: [
        (0, 1, "Now,"),
        (2, 7, "this did not come to pass"),
        (8, 10, "because"),
        (11, 15, "the seed was not good,"),
        (16, 18, "neither is it because"),
        (19, 22, "would not be desirable"),
        (23, 24, "the fruit thereof;"),
        (25, 28, "but it is"),
        (29, 29, "because"),
        (30, 33, "your ground is barren,"),
        (34, 39, "and ye would not nourish"),
        (40, 41, "the tree,"),
        (42, 43, "therefore"),
        (44, 49, "ye cannot"),
        (50, 50, "have"),
        (51, 53, "the fruit thereof."),
    ],
    40: [
        (0, 2, "And thus,"),
        (3, 7, "if ye will not nourish"),
        (8, 9, "the word,"),
        (10, 14, "looking forward"),
        (15, 18, "with an eye of"),
        (19, 20, "faith"),
        (21, 23, "to the fruit thereof,"),
        (24, 29, "ye can never"),
        (30, 30, "pluck"),
        (31, 35, "the fruit of the tree"),
        (36, 38, "of life."),
    ],
    41: [
        (0, 4, "But if ye will nourish"),
        (5, 6, "the word,"),
        (7, 7, "yea,"),
        (8, 10, "nourish the tree"),
        (11, 16, "as it beginneth to grow,"),
        (17, 20, "by your faith"),
        (21, 24, "with great diligence,"),
        (25, 27, "and with patience,"),
        (28, 32, "looking forward"),
        (33, 36, "to the fruit thereof,"),
        (37, 40, "it shall take root;"),
        (41, 42, "and behold"),
        (43, 47, "it shall be"),
        (48, 48, "a tree"),
        (49, 51, "springing up"),
        (52, 55, "unto everlasting"),
        (56, 57, "life."),
    ],
    42: [
        (0, 4, "And because of your diligence"),
        (5, 7, "and your faith"),
        (8, 10, "and your patience"),
        (11, 13, "with the word"),
        (14, 16, "in nourishing it,"),
        (17, 21, "that it may take root"),
        (22, 26, "within you,"),
        (27, 27, "behold,"),
        (28, 30, "by and by"),
        (31, 36, "ye shall pluck"),
        (37, 38, "the fruit thereof,"),
        (39, 43, "which is most precious,"),
        (44, 48, "which is sweet above"),
        (49, 53, "all that is sweet,"),
        (54, 59, "and which is white above"),
        (60, 65, "all that is white,"),
        (66, 66, "yea,"),
        (67, 68, "and pure above"),
        (69, 74, "all that is pure;"),
        (75, 80, "and ye shall feast"),
        (81, 81, "with joy"),
        (82, 84, "upon this fruit"),
        (85, 88, "even until"),
        (89, 90, "ye are filled,"),
        (91, 96, "that ye shall not"),
        (97, 97, "hunger,"),
        (98, 101, "neither shall ye thirst."),
    ],
    43: [
        (0, 3, "Then,"),
        (4, 6, "my brethren,"),
        (7, 12, "ye shall reap"),
        (13, 13, "the rewards"),
        (14, 17, "of your faith,"),
        (18, 21, "and your diligence,"),
        (22, 24, "and patience,"),
        (25, 27, "and long-suffering,"),
        (28, 29, "waiting"),
        (30, 32, "for the tree"),
        (33, 36, "to bring forth fruit"),
        (37, 38, "unto you."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
