"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 30 — Korihor,
the anti-Christ, preaches against the coming of Christ and the prophecies;
he contends with Alma; he demands a sign and is struck dumb; he confesses
that the devil deceived him; he is trodden down and dies among the
Zoramites.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15).

Em-dash token splits in the source per rule 11:
  v2  `Nifaē—ae`  -> `Nifaē—`  + `ae`  (v2  = 90 tokens)
  v59 `Sorama—ma` -> `Sorama—` + `ma`  (v59 = 80 tokens)

    python3 build_overrides_alma30.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 30

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "Behold,"),
        (1, 2, "now"),
        (3, 5, "it came to pass that"),
        (6, 9, "after was established"),
        (10, 13, "the people of Ammon"),
        (14, 18, "in the land of Jershon,"),
        (19, 19, "yea,"),
        (20, 25, "and after also"),
        (26, 27, "were driven out"),
        (28, 30, "the Lamanites"),
        (31, 33, "out of the land,"),
        (34, 36, "and were buried"),
        (37, 40, "their dead"),
        (41, 45, "by the people of the land—"),
    ],
    2: [
        (0, 1, "Now"),
        (2, 4, "were not numbered"),
        (5, 8, "their dead"),
        (9, 14, "because of the greatness of"),
        (15, 17, "their number;"),
        (18, 21, "neither were numbered"),
        (22, 26, "the dead of the Nephites—"),
        (27, 30, "but it came to pass"),
        (31, 35, "after they had buried"),
        (36, 40, "their dead,"),
        (41, 46, "and after also had passed"),
        (47, 50, "the days of fasting,"),
        (51, 53, "and mourning,"),
        (54, 56, "and prayer,"),
        (57, 61, "(and this happened"),
        (62, 65, "in the sixteenth"),
        (66, 67, "year"),
        (68, 72, "of the reign of the judges"),
        (73, 77, "over the people of Nephi)"),
        (78, 82, "there began to prevail"),
        (83, 83, "continually"),
        (84, 85, "the peace"),
        (86, 89, "throughout all the land."),
    ],
    3: [
        (0, 0, "Yea,"),
        (1, 4, "and the people observed"),
        (5, 7, "to keep"),
        (8, 11, "the commandments of the Lord;"),
        (12, 16, "and they were strict in"),
        (17, 20, "the keeping of the ordinances"),
        (21, 23, "of God,"),
        (24, 26, "according to"),
        (27, 30, "the law of Moses;"),
        (31, 31, "for"),
        (32, 35, "they were taught"),
        (36, 38, "to keep"),
        (39, 42, "the law of Moses"),
        (43, 46, "until it should be fulfilled."),
    ],
    4: [
        (0, 4, "And thus there was no"),
        (5, 7, "disturbance"),
        (8, 10, "among the people"),
        (11, 14, "in all the year"),
        (15, 16, "sixteenth"),
        (17, 21, "of the reign of the judges"),
        (22, 26, "over the people of Nephi."),
    ],
    5: [
        (0, 3, "And it came to pass in"),
        (4, 6, "the beginning of"),
        (7, 11, "the seventeenth year"),
        (12, 16, "of the reign of the judges,"),
        (17, 20, "there was continual"),
        (21, 22, "peace."),
    ],
    6: [
        (0, 0, "But"),
        (1, 3, "it came to pass in"),
        (4, 6, "the latter end of"),
        (7, 11, "the seventeenth year,"),
        (12, 16, "there came a man"),
        (17, 21, "into the land of Zarahemla,"),
        (22, 24, "and he was"),
        (25, 27, "an Anti-Christ,"),
        (28, 28, "for"),
        (29, 32, "he began to"),
        (33, 34, "preach"),
        (35, 36, "unto the people"),
        (37, 40, "against the prophecies"),
        (41, 45, "which were spoken by the prophets,"),
        (46, 48, "concerning"),
        (49, 53, "the coming of Christ."),
    ],
    7: [
        (0, 1, "Now"),
        (2, 5, "there was no law"),
        (6, 8, "against"),
        (9, 12, "the belief of a man;"),
        (13, 13, "for"),
        (14, 18, "it was strictly contrary"),
        (19, 23, "to the commands of God"),
        (24, 27, "the being of"),
        (28, 29, "a law"),
        (30, 34, "which should bring"),
        (35, 35, "men"),
        (36, 40, "to unequal grounds."),
    ],
    8: [
        (0, 0, "For"),
        (1, 5, "thus saith"),
        (6, 8, "the scriptures:"),
        (9, 12, "Choose ye"),
        (13, 16, "this day,"),
        (17, 19, "whom"),
        (20, 24, "ye will serve."),
    ],
    9: [
        (0, 1, "Now"),
        (2, 6, "if a man desired"),
        (7, 11, "to serve God,"),
        (12, 15, "it was his privilege;"),
        (16, 16, "or,"),
        (17, 21, "if he believed"),
        (22, 24, "in God"),
        (25, 29, "it was his own privilege"),
        (30, 33, "to serve"),
        (34, 36, "him;"),
        (37, 43, "but if he did not believe"),
        (44, 46, "in him"),
        (47, 50, "there was no law"),
        (51, 55, "to punish him."),
    ],
    10: [
        (0, 0, "But"),
        (1, 5, "if he murdered"),
        (6, 9, "he was punished"),
        (10, 12, "unto death;"),
        (13, 17, "and if he robbed"),
        (18, 22, "he was also punished;"),
        (23, 28, "and if he stole"),
        (29, 33, "he was also punished;"),
        (34, 39, "and if he committed adultery"),
        (40, 44, "he was also punished;"),
        (45, 45, "yea,"),
        (46, 49, "they were punished"),
        (50, 53, "for all these wickednesses."),
    ],
    11: [
        (0, 0, "For"),
        (1, 5, "there was a law"),
        (6, 9, "that men should be judged"),
        (10, 12, "according to"),
        (13, 15, "their crimes."),
        (16, 19, "Nevertheless,"),
        (20, 23, "there was no law"),
        (24, 26, "against"),
        (27, 30, "the belief of a man;"),
        (31, 32, "therefore,"),
        (33, 37, "a man was punished"),
        (38, 40, "only for the crimes"),
        (41, 43, "which he had done;"),
        (44, 45, "therefore"),
        (46, 49, "were on equal ground"),
        (50, 51, "all men."),
    ],
    12: [
        (0, 3, "And this Anti-Christ,"),
        (4, 7, "whose name was"),
        (8, 8, "Korihor,"),
        (9, 12, "(and could not"),
        (13, 15, "the law"),
        (16, 19, "hold him)"),
        (20, 23, "he began to"),
        (24, 25, "preach"),
        (26, 28, "unto the people"),
        (29, 34, "that there should be no"),
        (35, 36, "a Christ."),
        (37, 40, "and after this manner"),
        (41, 44, "he preached"),
        (45, 46, "saying:"),
    ],
    13: [
        (0, 0, "O,"),
        (1, 3, "ye who"),
        (4, 7, "are bound down"),
        (8, 11, "under a foolish hope"),
        (12, 14, "and a vain one,"),
        (15, 16, "why"),
        (17, 20, "do ye yoke"),
        (21, 22, "yourselves"),
        (23, 26, "with such foolish things?"),
        (27, 27, "Why"),
        (28, 32, "do ye look"),
        (33, 35, "for a Christ?"),
        (36, 36, "For"),
        (37, 40, "there is no man"),
        (41, 45, "who can know"),
        (46, 47, "anything"),
        (48, 52, "which is to come."),
    ],
    14: [
        (0, 0, "Behold,"),
        (1, 3, "these things"),
        (4, 8, "which ye call prophecies,"),
        (9, 13, "which ye say"),
        (14, 17, "were handed down"),
        (18, 19, "below"),
        (20, 22, "by holy prophets,"),
        (23, 23, "behold,"),
        (24, 27, "foolish traditions"),
        (28, 29, "are they"),
        (30, 33, "of your fathers."),
    ],
    15: [
        (0, 4, "How do ye know"),
        (5, 7, "of their surety?"),
        (8, 8, "Behold,"),
        (9, 13, "ye cannot"),
        (14, 14, "know"),
        (15, 19, "concerning things"),
        (20, 24, "which ye do not see"),
        (25, 26, "them;"),
        (27, 28, "therefore"),
        (29, 33, "ye cannot"),
        (34, 34, "know"),
        (35, 39, "that there shall be"),
        (40, 41, "a Christ."),
    ],
    16: [
        (0, 4, "Ye look forward"),
        (5, 7, "and say"),
        (8, 11, "that ye see"),
        (12, 14, "a remission of"),
        (15, 17, "your sins."),
        (18, 19, "But behold,"),
        (20, 24, "it is the effect of"),
        (25, 27, "a frenzied mind;"),
        (28, 32, "and this derangement of"),
        (33, 35, "your minds"),
        (36, 38, "cometh"),
        (39, 42, "because of the traditions of"),
        (43, 45, "your fathers,"),
        (46, 51, "which lead away"),
        (52, 52, "you"),
        (53, 55, "into a belief"),
        (56, 60, "of things which are not true."),
    ],
    17: [
        (0, 4, "And many other"),
        (5, 6, "such things"),
        (7, 11, "he said"),
        (12, 15, "unto them,"),
        (16, 19, "telling"),
        (20, 23, "them"),
        (24, 28, "that there could not be made"),
        (29, 31, "an atonement"),
        (32, 35, "for the sins of men,"),
        (36, 39, "but doeth"),
        (40, 41, "every man"),
        (42, 44, "in this life"),
        (45, 47, "according to"),
        (48, 50, "the management of"),
        (51, 54, "the creature;"),
        (55, 56, "therefore"),
        (57, 60, "every man prospereth"),
        (61, 63, "according to"),
        (64, 66, "his own genius,"),
        (67, 71, "and every man conquereth"),
        (72, 74, "according to"),
        (75, 77, "his own strength;"),
        (78, 82, "and whatsoever thing"),
        (83, 87, "a man did"),
        (88, 92, "was no crime."),
    ],
    18: [
        (0, 4, "And thus he"),
        (5, 6, "did preach"),
        (7, 10, "unto them,"),
        (11, 15, "leading away"),
        (16, 19, "the hearts of many"),
        (20, 24, "and causing them"),
        (25, 26, "to be lifted up"),
        (27, 30, "in their wickedness,"),
        (31, 31, "yea,"),
        (32, 36, "leading away"),
        (37, 39, "many women"),
        (40, 42, "and men also,"),
        (43, 46, "to commit whoredoms—"),
        (47, 49, "telling"),
        (50, 53, "them"),
        (54, 57, "when a man is dead,"),
        (58, 61, "that is his end."),
    ],
    19: [
        (0, 1, "Now"),
        (2, 5, "went also"),
        (6, 7, "this man"),
        (8, 12, "to the land of Jershon,"),
        (13, 15, "to preach"),
        (16, 17, "these things"),
        (18, 22, "among the people of Ammon,"),
        (23, 27, "who were formerly"),
        (28, 32, "the people of the Lamanites."),
    ],
    20: [
        (0, 1, "But behold,"),
        (2, 4, "greater was"),
        (5, 7, "their wisdom"),
        (8, 12, "than the many of"),
        (13, 14, "the Nephites;"),
        (15, 15, "for"),
        (16, 20, "they took him,"),
        (21, 24, "and bound him,"),
        (25, 28, "and carried him"),
        (29, 32, "before Ammon,"),
        (33, 37, "who was"),
        (38, 40, "a high priest"),
        (41, 45, "over that people."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 6, "he caused"),
        (7, 10, "that be carried away"),
        (11, 12, "him"),
        (13, 15, "out of the land."),
        (16, 20, "And he came"),
        (21, 25, "into the land of Gideon,"),
        (26, 31, "and began also to preach"),
        (32, 35, "unto them;"),
        (36, 40, "and he did not obtain"),
        (41, 43, "great success"),
        (44, 44, "here,"),
        (45, 45, "for"),
        (46, 49, "he was taken"),
        (50, 51, "and bound"),
        (52, 53, "and carried"),
        (54, 56, "before"),
        (57, 59, "the high priest,"),
        (60, 64, "and the chief judge"),
        (65, 65, "also"),
        (66, 70, "over the land."),
    ],
    22: [
        (0, 3, "And it came to pass that"),
        (4, 8, "the high priest said"),
        (9, 11, "unto him:"),
        (12, 12, "Why"),
        (13, 16, "dost thou go about"),
        (17, 18, "to pervert"),
        (19, 22, "the ways of the Lord?"),
        (23, 23, "Why"),
        (24, 28, "dost thou teach"),
        (29, 31, "this people"),
        (32, 35, "that there shall be no"),
        (36, 37, "Christ,"),
        (38, 40, "to stop"),
        (41, 43, "their rejoicings?"),
        (44, 44, "Why"),
        (45, 49, "dost thou speak against"),
        (50, 53, "all the prophecies of"),
        (54, 55, "the holy prophets?"),
    ],
    23: [
        (0, 1, "Now"),
        (2, 5, "the name of"),
        (6, 8, "the high priest"),
        (9, 10, "was Giddonah."),
        (11, 14, "And said"),
        (15, 15, "Korihor"),
        (16, 18, "unto him:"),
        (19, 19, "Because"),
        (20, 24, "I do not teach"),
        (25, 27, "the foolish traditions of"),
        (28, 30, "your fathers,"),
        (31, 35, "and because I not"),
        (36, 37, "teach"),
        (38, 40, "this people"),
        (41, 46, "to bind themselves"),
        (47, 48, "down"),
        (49, 51, "under the ordinances and"),
        (52, 53, "foolish performances"),
        (54, 57, "which were laid down by"),
        (58, 59, "ancient priests,"),
        (60, 64, "they seize by force"),
        (65, 69, "the power and authority"),
        (70, 73, "over them,"),
        (74, 78, "to keep them"),
        (79, 81, "in ignorance,"),
        (82, 87, "that they may not"),
        (88, 88, "lift up"),
        (89, 93, "upon their heads,"),
        (94, 95, "but be brought low"),
        (96, 99, "according to"),
        (100, 101, "thy words."),
    ],
    24: [
        (0, 3, "Ye say"),
        (4, 6, "this people"),
        (7, 10, "is a free people."),
        (11, 11, "Behold,"),
        (12, 15, "I say"),
        (16, 19, "they are in bondage."),
        (20, 23, "Ye say"),
        (24, 27, "that those prophecies are true"),
        (28, 29, "of old."),
        (30, 30, "Behold,"),
        (31, 34, "I say"),
        (35, 38, "ye do not know"),
        (39, 43, "whether those things are true."),
    ],
    25: [
        (0, 3, "Ye say"),
        (4, 6, "this people"),
        (7, 10, "is a guilty people"),
        (11, 15, "and a fallen people,"),
        (16, 20, "because of the transgression of"),
        (21, 22, "a parent."),
        (23, 23, "Behold,"),
        (24, 27, "I say"),
        (28, 32, "a child is not guilty"),
        (33, 36, "because of its parents."),
    ],
    26: [
        (0, 5, "And ye also say"),
        (6, 10, "that shall come"),
        (11, 11, "Christ."),
        (12, 13, "But behold,"),
        (14, 17, "I say"),
        (18, 21, "ye do not know"),
        (22, 27, "whether there shall be"),
        (28, 29, "a Christ."),
        (30, 35, "And ye also say"),
        (36, 41, "that he shall be slain"),
        (42, 44, "for the sins of"),
        (45, 46, "the world—"),
    ],
    27: [
        (0, 4, "and thus thou"),
        (5, 6, "leadest away"),
        (7, 8, "this people"),
        (9, 11, "to follow"),
        (12, 14, "the foolish traditions of"),
        (15, 17, "your fathers,"),
        (18, 22, "and according to"),
        (23, 25, "thine own desires;"),
        (26, 29, "and thou bindest"),
        (30, 31, "them"),
        (32, 36, "as if in bondage,"),
        (37, 40, "that ye may glut"),
        (41, 42, "yourselves"),
        (43, 45, "with the labors of"),
        (46, 48, "their hands,"),
        (49, 52, "that they durst not"),
        (53, 57, "look up"),
        (58, 60, "with boldness,"),
        (61, 65, "and that they durst not"),
        (66, 68, "enjoy"),
        (69, 71, "their rights"),
        (72, 74, "and privileges."),
    ],
    28: [
        (0, 0, "Yea,"),
        (1, 3, "they durst not"),
        (4, 5, "make use of"),
        (6, 10, "that which is their own,"),
        (11, 14, "lest they offend"),
        (15, 18, "their priests,"),
        (19, 23, "who do enslave"),
        (24, 25, "them"),
        (26, 28, "according to"),
        (29, 31, "their desires,"),
        (32, 35, "and have brought them"),
        (36, 37, "to believe"),
        (38, 42, "by their traditions"),
        (43, 46, "and their dreams"),
        (47, 51, "and their whims"),
        (52, 55, "and their visions"),
        (56, 60, "and their pretended mysteries,"),
        (61, 63, "that they should"),
        (64, 67, "if they"),
        (68, 69, "do not"),
        (70, 72, "according to"),
        (73, 75, "their words,"),
        (76, 79, "offend a being"),
        (80, 82, "unknown,"),
        (83, 88, "whom they say"),
        (89, 91, "is God—"),
        (92, 94, "a being"),
        (95, 98, "who never has been seen"),
        (99, 102, "or known by"),
        (103, 104, "any one,"),
        (105, 110, "who never was"),
        (111, 116, "nor ever will be"),
        (117, 117, "at all."),
    ],
    29: [
        (0, 1, "Now"),
        (2, 5, "when saw"),
        (6, 8, "the high priest"),
        (9, 12, "and the chief judge"),
        (13, 16, "the hardness of"),
        (17, 18, "his heart,"),
        (19, 19, "yea,"),
        (20, 24, "when they saw"),
        (25, 28, "even unto"),
        (29, 30, "God"),
        (31, 37, "he did revile against him,"),
        (38, 42, "they would not make"),
        (43, 44, "a reply"),
        (45, 47, "to his words;"),
        (48, 51, "but they commanded"),
        (52, 55, "that he be bound;"),
        (56, 62, "and they delivered him up"),
        (63, 67, "into the hands of the officers,"),
        (68, 72, "and sent him"),
        (73, 77, "to the land of Zarahemla,"),
        (78, 84, "that he might be brought"),
        (85, 88, "before Alma,"),
        (89, 92, "and the chief judge"),
        (93, 96, "who was governor"),
        (97, 99, "over"),
        (100, 102, "all the land."),
    ],
    30: [
        (0, 3, "And it came to pass that"),
        (4, 7, "when he was brought"),
        (8, 11, "before Alma"),
        (12, 15, "and the chief judge,"),
        (16, 21, "he continued still"),
        (22, 26, "in the same manner"),
        (27, 31, "as he had done"),
        (32, 36, "in the land of Gideon;"),
        (37, 37, "yea,"),
        (38, 42, "at last"),
        (43, 45, "he blasphemed."),
    ],
    31: [
        (0, 5, "And he rose up"),
        (6, 9, "with great swelling words"),
        (10, 13, "before Alma,"),
        (14, 17, "and reviled against"),
        (18, 20, "the priests and teachers,"),
        (21, 24, "accusing them"),
        (25, 29, "of their leading away"),
        (30, 31, "the people"),
        (32, 34, "to follow"),
        (35, 37, "the silly traditions of"),
        (38, 40, "their fathers,"),
        (41, 44, "that they may live"),
        (45, 46, "glutting"),
        (47, 51, "upon the labors of"),
        (52, 52, "the people."),
    ],
    32: [
        (0, 1, "Now"),
        (2, 4, "said"),
        (5, 5, "Alma"),
        (6, 8, "unto him:"),
        (9, 11, "Thou knowest"),
        (12, 15, "that we do not"),
        (16, 17, "glut ourselves"),
        (18, 22, "upon the labors of"),
        (23, 24, "this people;"),
        (25, 26, "for behold"),
        (27, 31, "I have labored even"),
        (32, 35, "from the beginning of"),
        (36, 39, "the reign of the judges"),
        (40, 43, "until"),
        (44, 46, "the present time,"),
        (47, 50, "with mine own hands"),
        (51, 54, "for mine own support,"),
        (55, 59, "notwithstanding my travels"),
        (60, 61, "many"),
        (62, 65, "round about the land"),
        (66, 68, "to declare"),
        (69, 73, "the word of God"),
        (74, 76, "unto my people."),
    ],
    33: [
        (0, 6, "and notwithstanding the many"),
        (7, 7, "labors"),
        (8, 10, "which I did"),
        (11, 13, "in the church,"),
        (14, 18, "I have never received"),
        (19, 23, "even so much as"),
        (24, 27, "one senine"),
        (28, 30, "for my labor;"),
        (31, 34, "neither has received"),
        (35, 39, "any of"),
        (40, 41, "my brethren,"),
        (42, 43, "save it be"),
        (44, 46, "in the judgment-seat;"),
        (47, 51, "and in that case"),
        (52, 55, "we received"),
        (56, 57, "a wage"),
        (58, 62, "only for our time"),
        (63, 66, "according to"),
        (67, 68, "the law."),
    ],
    34: [
        (0, 2, "And now,"),
        (3, 7, "if we receive not"),
        (8, 9, "anything"),
        (10, 13, "for our labors"),
        (14, 16, "in the church,"),
        (17, 21, "what profit is it"),
        (22, 25, "that we labor"),
        (26, 28, "in the church"),
        (29, 31, "save it were"),
        (32, 36, "our declaring of"),
        (37, 38, "the truth,"),
        (39, 43, "that we may"),
        (44, 45, "obtain"),
        (46, 46, "rejoicings"),
        (47, 50, "in the joy of"),
        (51, 53, "our brethren?"),
    ],
    35: [
        (0, 2, "Why then"),
        (3, 7, "sayest thou"),
        (8, 11, "that we preach"),
        (12, 14, "unto this people"),
        (15, 19, "that we may obtain"),
        (20, 20, "gain,"),
        (21, 24, "when thou knowest"),
        (25, 28, "of thine own self"),
        (29, 33, "that we do not receive"),
        (34, 35, "any gain?"),
        (36, 38, "And now,"),
        (39, 42, "believest thou"),
        (43, 47, "that we deceive"),
        (48, 49, "this people,"),
        (50, 53, "which causeth"),
        (54, 57, "such great joy"),
        (58, 61, "in their hearts?"),
    ],
    36: [
        (0, 3, "And answered"),
        (4, 4, "Korihor"),
        (5, 7, "him,"),
        (8, 8, "Yea."),
    ],
    37: [
        (0, 4, "And then said"),
        (5, 6, "Alma"),
        (7, 9, "unto him:"),
        (10, 12, "Believest thou"),
        (13, 16, "that there is"),
        (17, 18, "a God?"),
    ],
    38: [
        (0, 5, "And he answered,"),
        (6, 7, "Nay."),
    ],
    39: [
        (0, 1, "Now"),
        (2, 4, "said"),
        (5, 5, "Alma"),
        (6, 8, "unto him:"),
        (9, 13, "Wilt thou deny again"),
        (14, 17, "that there is"),
        (18, 19, "a God,"),
        (20, 22, "and also deny"),
        (23, 24, "the Christ?"),
        (25, 26, "For behold,"),
        (27, 30, "I say"),
        (31, 33, "unto thee,"),
        (34, 36, "I know"),
        (37, 40, "that there is"),
        (41, 42, "a God,"),
        (43, 49, "and also shall come"),
        (50, 50, "Christ."),
    ],
    40: [
        (0, 2, "And now"),
        (3, 7, "what evidence"),
        (8, 11, "hast thou"),
        (12, 15, "that there is no God,"),
        (16, 23, "or that shall not come"),
        (24, 24, "Christ?"),
        (25, 28, "I say"),
        (29, 31, "unto thee"),
        (32, 35, "there is no evidence"),
        (36, 39, "with thee,"),
        (40, 41, "save it be"),
        (42, 44, "thine own word."),
    ],
    41: [
        (0, 1, "But behold,"),
        (2, 5, "I have"),
        (6, 7, "all things"),
        (8, 10, "as a testimony"),
        (11, 14, "that these things are true;"),
        (15, 20, "and thou also hast"),
        (21, 22, "all things"),
        (23, 25, "as a testimony"),
        (26, 28, "unto thee"),
        (29, 32, "that they are true;"),
        (33, 37, "and wilt thou deny"),
        (38, 39, "them?"),
        (40, 43, "Believest thou"),
        (44, 47, "that these things are true?"),
    ],
    42: [
        (0, 0, "Behold,"),
        (1, 3, "I know"),
        (4, 6, "that thou believest,"),
        (7, 9, "but hath entered"),
        (10, 12, "into thee"),
        (13, 15, "a lying spirit,"),
        (16, 20, "and thou hast put off"),
        (21, 25, "the Spirit of God"),
        (26, 31, "that it may not find"),
        (32, 33, "a place"),
        (34, 35, "within"),
        (36, 38, "thee;"),
        (39, 43, "but there is"),
        (44, 45, "in the devil"),
        (46, 47, "the power"),
        (48, 50, "over thee,"),
        (51, 55, "and he carrieth about"),
        (56, 56, "thee"),
        (57, 59, "working devices"),
        (60, 65, "that he may destroy"),
        (66, 69, "the children of God."),
    ],
    43: [
        (0, 2, "And now"),
        (3, 5, "said"),
        (6, 6, "Korihor"),
        (7, 8, "unto Alma:"),
        (9, 13, "If thou wilt show"),
        (14, 16, "me"),
        (17, 18, "a sign,"),
        (19, 24, "that I may be convinced"),
        (25, 28, "that there is"),
        (29, 30, "a God,"),
        (31, 31, "yea,"),
        (32, 36, "show unto me"),
        (37, 40, "that he hath"),
        (41, 42, "power,"),
        (43, 47, "then will I be convinced"),
        (48, 51, "of the truth of"),
        (52, 53, "thy words."),
    ],
    44: [
        (0, 0, "But"),
        (1, 3, "said"),
        (4, 4, "Alma"),
        (5, 7, "unto him:"),
        (8, 10, "signs enough"),
        (11, 14, "hast thou;"),
        (15, 18, "wilt thou tempt"),
        (19, 21, "thy God?"),
        (22, 26, "Wilt thou say,"),
        (27, 31, "Show unto me"),
        (32, 33, "a sign,"),
        (34, 38, "when thou hast"),
        (39, 41, "the testimony of"),
        (42, 45, "all these my brethren,"),
        (46, 49, "and all the holy prophets"),
        (50, 50, "also?"),
        (51, 52, "Are laid open"),
        (53, 55, "before thee"),
        (56, 57, "the scriptures,"),
        (58, 58, "yea,"),
        (59, 63, "and denote by"),
        (64, 65, "all things"),
        (66, 69, "that there is"),
        (70, 71, "a God;"),
        (72, 72, "yea,"),
        (73, 77, "even the earth,"),
        (78, 80, "and all things"),
        (81, 84, "that are upon it,"),
        (85, 85, "yea,"),
        (86, 88, "and its motion,"),
        (89, 89, "yea,"),
        (90, 93, "and also all the planets"),
        (94, 99, "which move in their course"),
        (100, 101, "regular"),
        (102, 104, "do witness"),
        (105, 108, "that there is"),
        (109, 111, "a Supreme Creator."),
    ],
    45: [
        (0, 4, "And yet"),
        (5, 9, "dost thou go about"),
        (10, 12, "leading away"),
        (13, 16, "the hearts of this people"),
        (17, 19, "testifying"),
        (20, 23, "unto them"),
        (24, 27, "there is no God?"),
        (28, 32, "And yet"),
        (33, 36, "wilt thou deny"),
        (37, 39, "against"),
        (40, 42, "all these witnesses?"),
        (43, 48, "And he said:"),
        (49, 49, "Yea,"),
        (50, 52, "I will deny,"),
        (53, 55, "except"),
        (56, 59, "thou show"),
        (60, 62, "me"),
        (63, 64, "a sign."),
    ],
    46: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 8, "Alma said"),
        (9, 11, "unto him:"),
        (12, 12, "Behold,"),
        (13, 15, "I am grieved"),
        (16, 20, "because of the hardness of"),
        (21, 22, "your heart,"),
        (23, 23, "yea,"),
        (24, 27, "in thy still resisting"),
        (28, 31, "the spirit of"),
        (32, 33, "the truth,"),
        (34, 37, "that may"),
        (38, 40, "be destroyed"),
        (41, 42, "thy soul."),
    ],
    47: [
        (0, 1, "But behold,"),
        (2, 5, "it is better"),
        (6, 10, "the loss of thy soul"),
        (11, 16, "than that thou become"),
        (17, 18, "a means"),
        (19, 24, "of bringing many"),
        (25, 25, "souls"),
        (26, 30, "down to destruction,"),
        (31, 35, "by thy lying"),
        (36, 39, "and thy flattering words;"),
        (40, 41, "therefore"),
        (42, 46, "if thou deny again,"),
        (47, 47, "behold"),
        (48, 52, "shall smite thee"),
        (53, 55, "God,"),
        (56, 59, "that thou be dumb,"),
        (60, 65, "that thou canst not"),
        (66, 67, "again open"),
        (68, 70, "thy mouth,"),
        (71, 75, "that thou no more"),
        (76, 76, "deceive"),
        (77, 78, "this people."),
    ],
    48: [
        (0, 1, "Now"),
        (2, 4, "said"),
        (5, 5, "Korihor"),
        (6, 8, "unto him:"),
        (9, 12, "I do not deny"),
        (13, 16, "the existence of"),
        (17, 18, "a God,"),
        (19, 23, "but I do not believe"),
        (24, 27, "that there is"),
        (28, 29, "a God;"),
        (30, 34, "and I say"),
        (35, 35, "also"),
        (36, 39, "ye do not know"),
        (40, 43, "that there is"),
        (44, 45, "a God;"),
        (46, 49, "and except"),
        (50, 53, "thou show"),
        (54, 56, "me"),
        (57, 58, "a sign,"),
        (59, 62, "I will not believe."),
    ],
    49: [
        (0, 1, "Now"),
        (2, 4, "said"),
        (5, 5, "Alma"),
        (6, 8, "unto him:"),
        (9, 12, "This thing"),
        (13, 16, "I will"),
        (17, 18, "give"),
        (19, 21, "unto thee"),
        (22, 24, "for a sign,"),
        (25, 29, "thou shalt be smitten"),
        (30, 32, "to be dumb,"),
        (33, 35, "according to"),
        (36, 37, "my words;"),
        (38, 42, "and I say"),
        (43, 46, "in the name of"),
        (47, 48, "God,"),
        (49, 51, "that thou be smitten"),
        (52, 54, "to be dumb,"),
        (55, 60, "that thou canst no more"),
        (61, 62, "speak."),
    ],
    50: [
        (0, 1, "Now"),
        (2, 7, "when had said"),
        (8, 9, "Alma"),
        (10, 12, "these words,"),
        (13, 15, "Korihor was smitten"),
        (16, 18, "with dumbness,"),
        (19, 25, "that he could not speak,"),
        (26, 29, "according to"),
        (30, 32, "the words of Alma."),
    ],
    51: [
        (0, 2, "And now"),
        (3, 6, "when saw"),
        (7, 9, "the chief judge"),
        (10, 12, "this,"),
        (13, 16, "he put forth"),
        (17, 18, "his hand"),
        (19, 22, "and wrote"),
        (23, 24, "unto Korihor,"),
        (25, 26, "saying:"),
        (27, 31, "Art thou convinced"),
        (32, 35, "of the power of"),
        (36, 37, "God?"),
        (38, 39, "In whom"),
        (40, 42, "didst thou desire"),
        (43, 47, "that should show forth"),
        (48, 49, "Alma"),
        (50, 51, "his sign?"),
        (52, 55, "Wouldst thou desire"),
        (56, 60, "that he afflict others,"),
        (61, 64, "to show"),
        (65, 67, "unto thee"),
        (68, 69, "a sign?"),
        (70, 70, "Behold,"),
        (71, 74, "he hath showed"),
        (75, 77, "unto thee"),
        (78, 79, "a sign;"),
        (80, 82, "and now"),
        (83, 87, "wilt thou still dispute"),
        (88, 89, "more?"),
    ],
    52: [
        (0, 5, "And Korihor put forth"),
        (6, 7, "his hand"),
        (8, 9, "forth"),
        (10, 12, "and wrote,"),
        (13, 14, "saying:"),
        (15, 17, "I know"),
        (18, 20, "that I am dumb,"),
        (21, 26, "for I cannot"),
        (27, 27, "speak;"),
        (28, 31, "and I know"),
        (32, 35, "that nothing"),
        (36, 37, "save it were"),
        (38, 42, "the power of God"),
        (43, 46, "could bring"),
        (47, 48, "this thing"),
        (49, 51, "upon me;"),
        (52, 52, "yea,"),
        (53, 56, "and I knew"),
        (57, 60, "always"),
        (61, 64, "that there is"),
        (65, 66, "a God."),
    ],
    53: [
        (0, 1, "But behold,"),
        (2, 4, "I have been deceived"),
        (5, 7, "by the devil;"),
        (8, 8, "for"),
        (9, 12, "he came"),
        (13, 15, "unto me"),
        (16, 19, "in the likeness of"),
        (20, 21, "an angel,"),
        (22, 24, "and said"),
        (25, 27, "unto me:"),
        (28, 32, "Go and reclaim"),
        (33, 34, "this people,"),
        (35, 40, "for they have gone astray"),
        (41, 41, "all"),
        (42, 44, "following after"),
        (45, 46, "a God"),
        (47, 49, "unknown."),
        (50, 55, "and he said"),
        (56, 58, "unto me:"),
        (59, 62, "There is no God;"),
        (63, 63, "yea,"),
        (64, 68, "and he taught"),
        (69, 71, "me"),
        (72, 76, "that which I should"),
        (77, 79, "say."),
        (80, 84, "And I taught"),
        (85, 86, "his words;"),
        (87, 91, "and I taught"),
        (92, 93, "them"),
        (94, 98, "because they were pleasing"),
        (99, 102, "unto the carnal mind;"),
        (103, 107, "and I taught"),
        (108, 109, "them"),
        (110, 115, "even until I obtained"),
        (116, 118, "great success,"),
        (119, 123, "insomuch that I believed"),
        (124, 126, "verily"),
        (127, 130, "that they were true;"),
        (131, 135, "and for this cause"),
        (136, 139, "I withstood"),
        (140, 141, "the truth,"),
        (142, 147, "even until I brought"),
        (148, 150, "this great curse"),
        (151, 153, "upon me."),
    ],
    54: [
        (0, 1, "Now"),
        (2, 6, "when he had"),
        (7, 8, "said"),
        (9, 11, "these words,"),
        (12, 15, "he besought"),
        (16, 19, "that Alma should pray"),
        (20, 22, "unto God,"),
        (23, 27, "that might be taken away"),
        (28, 30, "the curse"),
        (31, 34, "from him."),
    ],
    55: [
        (0, 0, "But"),
        (1, 3, "said"),
        (4, 4, "Alma"),
        (5, 7, "unto him:"),
        (8, 12, "If this curse be taken"),
        (13, 16, "from thee,"),
        (17, 21, "thou wouldst again"),
        (22, 24, "lead away"),
        (25, 28, "the hearts of this people;"),
        (29, 30, "therefore,"),
        (31, 35, "be it done unto thee"),
        (36, 41, "even as willeth"),
        (42, 43, "the Lord."),
    ],
    56: [
        (0, 3, "And it came to pass that"),
        (4, 6, "was not taken away"),
        (7, 8, "the curse"),
        (9, 11, "from Korihor;"),
        (12, 17, "but he was cast out,"),
        (18, 21, "and went"),
        (22, 24, "from house"),
        (25, 27, "to house"),
        (28, 32, "begging for his food."),
    ],
    57: [
        (0, 1, "Now"),
        (2, 5, "the report of"),
        (6, 9, "what happened"),
        (10, 11, "unto Korihor"),
        (12, 16, "was speedily published"),
        (17, 20, "throughout all the land;"),
        (21, 21, "yea,"),
        (22, 25, "was sent by"),
        (26, 28, "the chief judge"),
        (29, 30, "the proclamation"),
        (31, 33, "to all the people"),
        (34, 36, "in the land,"),
        (37, 40, "declaring"),
        (41, 45, "unto those who"),
        (46, 48, "had believed in"),
        (49, 51, "the words of Korihor,"),
        (52, 56, "that they must repent"),
        (57, 57, "speedily,"),
        (58, 60, "lest come"),
        (61, 63, "the same judgments"),
        (64, 67, "upon them."),
    ],
    58: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they were all convinced"),
        (7, 11, "of the wickedness of Korihor;"),
        (12, 13, "therefore"),
        (14, 19, "they were all converted again"),
        (20, 22, "unto the Lord;"),
        (23, 26, "and this thing"),
        (27, 31, "put an end to the iniquity"),
        (32, 36, "after the manner"),
        (37, 40, "which Korihor did."),
        (41, 45, "And Korihor went about"),
        (46, 48, "from house"),
        (49, 51, "to house,"),
        (52, 54, "begging food"),
        (55, 57, "for his support."),
    ],
    59: [
        (0, 3, "And it came to pass that"),
        (4, 8, "as he went forth"),
        (9, 13, "among the people,"),
        (14, 14, "yea,"),
        (15, 19, "among a people"),
        (20, 21, "who"),
        (22, 25, "had separated"),
        (26, 28, "themselves"),
        (29, 32, "from the Nephites"),
        (33, 35, "and called"),
        (36, 38, "themselves"),
        (39, 41, "Zoramites,"),
        (42, 46, "for they were led"),
        (47, 49, "by a man"),
        (50, 53, "whose name was Zoram—"),
        (54, 59, "and as he went forth"),
        (60, 64, "among them,"),
        (65, 65, "behold,"),
        (66, 69, "he was run upon"),
        (70, 73, "and trodden down,"),
        (74, 79, "even until he was dead."),
    ],
    60: [
        (0, 4, "and thus we"),
        (5, 6, "see"),
        (7, 11, "the end of him"),
        (12, 16, "who perverteth"),
        (17, 20, "the ways of the Lord;"),
        (21, 25, "and thus we"),
        (26, 27, "see"),
        (28, 31, "that will not support"),
        (32, 33, "the devil"),
        (34, 35, "his children"),
        (36, 39, "at the last day,"),
        (40, 44, "but doth speedily drag"),
        (45, 46, "down"),
        (47, 48, "them"),
        (49, 50, "to hell."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
