"""Hand-curated TAM-phrase gloss overrides for Mosaea 24 — Amulon persecutes Alma's people, and the Lord delivers them from bondage.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
subject `o ia` / agent `e ia` absorbed into the verb cluster, never split as a
bare "he" (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` fillers when a PP/object follows (rule 1), `mafai ona`/`ina ia`/
`ina ua` bound (rules 13/15), vocative `e`/`E …e` folded as "O X" (rule 12),
directional "forth" dropped (rule 12a). No pronoun/TAM word injected into a cell
whose span lacks that token; no content word repeats across adjacent cells
(except authentic Samoan doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah24.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 24
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass"),
        (4, 4, "did gain favor"),
        (5, 5, "Amulon"),
        (6, 8, "of the king"),
        (9, 11, "of the Lamanites;"),
        (12, 13, "therefore"),
        (14, 17, "granted"),
        (18, 20, "the king"),
        (21, 23, "of the Lamanites"),
        (24, 26, "unto him"),
        (27, 27, "and"),
        (28, 29, "his brethren"),
        (30, 31, "that be appointed"),
        (32, 33, "they"),
        (34, 37, "to be teachers"),
        (38, 40, "over his people,"),
        (41, 41, "yea,"),
        (42, 45, "even over"),
        (46, 46, "the people"),
        (47, 50, "who were in the land"),
        (51, 52, "of Shemlon,"),
        (53, 53, "and"),
        (54, 56, "in the land"),
        (57, 58, "of Shilom,"),
        (59, 59, "and"),
        (60, 62, "in the land"),
        (63, 64, "of Amulon."),
    ],
    2: [
        (0, 0, "For"),
        (1, 3, "had taken all"),
        (4, 6, "the Lamanites"),
        (7, 8, "these lands"),
        (9, 11, "for themselves;"),
        (12, 13, "therefore"),
        (14, 16, "had appointed"),
        (17, 19, "the king"),
        (20, 22, "of the Lamanites"),
        (23, 24, "kings"),
        (25, 26, "to rule"),
        (27, 30, "over all these lands."),
    ],
    3: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "the name"),
        (6, 8, "of the king"),
        (9, 11, "of the Lamanites"),
        (12, 13, "was Laman,"),
        (14, 17, "being called"),
        (18, 21, "after the name of"),
        (22, 23, "his father;"),
        (24, 25, "therefore"),
        (26, 30, "he was called"),
        (31, 32, "Laman"),
        (33, 34, "the king."),
        (35, 35, "And"),
        (36, 39, "he was king"),
        (40, 42, "over"),
        (43, 46, "a numerous people."),
    ],
    4: [
        (0, 0, "And"),
        (1, 4, "he appointed"),
        (5, 6, "teachers"),
        (7, 7, "from"),
        (8, 8, "the brethren"),
        (9, 10, "of Amulon"),
        (11, 13, "in every land"),
        (14, 16, "which dwelt in by"),
        (17, 18, "his people;"),
        (19, 19, "and"),
        (20, 22, "thus"),
        (23, 24, "began"),
        (25, 27, "to be taught"),
        (28, 30, "the language"),
        (31, 32, "of Nephi"),
        (33, 35, "among"),
        (36, 37, "all the people"),
        (38, 40, "of the Lamanites."),
    ],
    5: [
        (0, 0, "And"),
        (1, 3, "they were"),
        (4, 6, "a people"),
        (7, 8, "friendly"),
        (9, 10, "one"),
        (11, 13, "with another;"),
        (14, 17, "nevertheless"),
        (18, 21, "they knew not"),
        (22, 23, "God;"),
        (24, 28, "neither did teach"),
        (29, 30, "the brethren"),
        (31, 32, "of Amulon"),
        (33, 36, "them"),
        (37, 38, "anything"),
        (39, 41, "concerning"),
        (42, 43, "the Lord"),
        (44, 46, "their God,"),
        (47, 48, "nor"),
        (49, 50, "the law"),
        (51, 52, "of Moses;"),
        (53, 53, "nor"),
        (54, 58, "did they teach"),
        (59, 62, "them"),
        (63, 63, "the words"),
        (64, 65, "of Abinadi;"),
    ],
    6: [
        (0, 0, "But"),
        (1, 4, "they did teach"),
        (5, 8, "them"),
        (9, 11, "that they should keep"),
        (12, 14, "their record,"),
        (15, 15, "and"),
        (16, 18, "that might"),
        (19, 20, "they write"),
        (21, 23, "one"),
        (24, 26, "to another."),
    ],
    7: [
        (0, 0, "And"),
        (1, 3, "thus"),
        (4, 5, "began"),
        (6, 6, "to increase"),
        (7, 8, "the riches"),
        (9, 11, "of the Lamanites,"),
        (12, 13, "and began"),
        (14, 15, "to trade"),
        (16, 18, "one"),
        (19, 21, "with another"),
        (22, 26, "and wax great,"),
        (27, 28, "and began"),
        (29, 31, "to be"),
        (32, 35, "a cunning people"),
        (36, 37, "and wise,"),
        (38, 40, "as to"),
        (41, 43, "the wisdom of"),
        (44, 45, "the world,"),
        (46, 46, "yea,"),
        (47, 49, "a people"),
        (50, 51, "very cunning,"),
        (52, 53, "delighting"),
        (54, 56, "in all manner of"),
        (57, 59, "wickedness"),
        (60, 62, "and plunder,"),
        (63, 64, "except"),
        (65, 67, "among"),
        (68, 71, "their own brethren."),
    ],
    8: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "it came to pass"),
        (6, 7, "began"),
        (8, 8, "to exercise"),
        (9, 10, "Amulon"),
        (11, 12, "authority"),
        (13, 15, "over"),
        (16, 16, "Alma"),
        (17, 17, "and"),
        (18, 19, "his brethren,"),
        (20, 21, "and began"),
        (22, 23, "to persecute"),
        (24, 25, "him,"),
        (26, 27, "and cause"),
        (28, 29, "that should persecute"),
        (30, 32, "his children"),
        (33, 35, "their children."),
    ],
    9: [
        (0, 0, "For"),
        (1, 2, "knew"),
        (3, 4, "Amulon"),
        (5, 6, "Alma,"),
        (7, 8, "that he was"),
        (9, 13, "one of the priests"),
        (14, 16, "of the king,"),
        (17, 17, "and"),
        (18, 20, "it was he"),
        (21, 22, "that believed"),
        (23, 24, "the words"),
        (25, 26, "of Abinadi"),
        (27, 27, "and"),
        (28, 30, "was driven forth"),
        (31, 33, "from before"),
        (34, 35, "the king,"),
        (36, 36, "and"),
        (37, 38, "therefore"),
        (39, 43, "he was wroth"),
        (44, 46, "with him;"),
        (47, 47, "for"),
        (48, 49, "ruled"),
        (50, 53, "king Laman"),
        (54, 56, "over him,"),
        (57, 57, "yet"),
        (58, 60, "he exercised"),
        (61, 62, "authority"),
        (63, 65, "over"),
        (66, 67, "them,"),
        (68, 69, "and put"),
        (70, 71, "heavy tasks"),
        (72, 75, "upon them,"),
        (76, 77, "and put"),
        (78, 81, "taskmasters"),
        (82, 85, "over them."),
    ],
    10: [
        (0, 3, "And it came to pass"),
        (4, 6, "so great were"),
        (7, 9, "their afflictions"),
        (10, 12, "began"),
        (13, 14, "they to cry"),
        (15, 16, "mightily"),
        (17, 19, "to God."),
    ],
    11: [
        (0, 0, "And"),
        (1, 2, "commanded"),
        (3, 4, "them"),
        (5, 6, "Amulon"),
        (7, 8, "that should stop"),
        (9, 11, "their cries;"),
        (12, 12, "and"),
        (13, 16, "he put"),
        (17, 17, "guards"),
        (18, 20, "over"),
        (21, 22, "them"),
        (23, 24, "to watch"),
        (25, 26, "them,"),
        (27, 27, "that"),
        (28, 31, "whosoever"),
        (32, 33, "should be found"),
        (34, 36, "calling"),
        (37, 39, "upon God,"),
        (40, 43, "should be put to death."),
    ],
    12: [
        (0, 0, "And"),
        (1, 4, "did not raise"),
        (5, 6, "Alma"),
        (7, 7, "and"),
        (8, 9, "his people"),
        (10, 12, "their voices"),
        (13, 15, "to the Lord"),
        (16, 18, "their God,"),
        (19, 19, "but"),
        (20, 23, "did pour out"),
        (24, 24, "wholly"),
        (25, 27, "their hearts"),
        (28, 30, "to him;"),
        (31, 31, "and"),
        (32, 35, "he did know"),
        (36, 37, "the thoughts of"),
        (38, 40, "their hearts."),
    ],
    13: [
        (0, 3, "And it came to pass"),
        (4, 5, "came"),
        (6, 8, "the voice of"),
        (9, 10, "the Lord"),
        (11, 14, "to them"),
        (15, 18, "in their afflictions,"),
        (19, 21, "saying:"),
        (22, 24, "Lift ye up"),
        (25, 27, "your heads"),
        (28, 30, "and be comforted"),
        (31, 31, "ye;"),
        (32, 32, "for"),
        (33, 35, "I know"),
        (36, 37, "the covenant"),
        (38, 40, "which ye have made"),
        (41, 44, "unto me;"),
        (45, 45, "and"),
        (46, 50, "I will covenant"),
        (51, 53, "with my people"),
        (54, 55, "and deliver"),
        (56, 57, "them"),
        (58, 60, "out of bondage."),
    ],
    14: [
        (0, 0, "And"),
        (1, 5, "I will ease"),
        (6, 6, "also"),
        (7, 7, "the burdens"),
        (8, 9, "which are put"),
        (10, 13, "upon your shoulders,"),
        (14, 15, "even"),
        (16, 18, "you"),
        (19, 22, "cannot feel"),
        (23, 24, "them"),
        (25, 27, "upon"),
        (28, 30, "your backs,"),
        (31, 35, "even while ye are"),
        (36, 38, "in bondage;"),
        (39, 39, "and"),
        (40, 44, "I will do"),
        (45, 46, "this"),
        (47, 48, "that"),
        (49, 50, "may"),
        (51, 53, "ye stand"),
        (54, 58, "as witnesses"),
        (59, 60, "for me"),
        (61, 63, "hereafter,"),
        (64, 64, "and"),
        (65, 66, "that"),
        (67, 68, "may"),
        (69, 70, "ye know"),
        (71, 73, "of a surety"),
        (74, 75, "that I,"),
        (76, 78, "the Lord"),
        (79, 80, "God,"),
        (81, 83, "do visit"),
        (84, 86, "my people"),
        (87, 90, "in their afflictions."),
    ],
    15: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "it came to pass"),
        (6, 6, "were made light"),
        (7, 7, "the burdens"),
        (8, 9, "which were laid"),
        (10, 12, "upon"),
        (13, 13, "Alma"),
        (14, 14, "and"),
        (15, 16, "his brethren;"),
        (17, 17, "yea,"),
        (18, 19, "did strengthen"),
        (20, 21, "them"),
        (22, 24, "the Lord"),
        (25, 26, "that"),
        (27, 28, "could"),
        (29, 30, "they bear up"),
        (31, 33, "with ease"),
        (34, 36, "their burdens,"),
        (37, 37, "and"),
        (38, 41, "they did submit"),
        (42, 44, "cheerfully"),
        (45, 47, "and with patience"),
        (48, 51, "to all the will of"),
        (52, 54, "the Lord."),
    ],
    16: [
        (0, 3, "And it came to pass"),
        (4, 6, "so great was"),
        (7, 9, "their faith"),
        (10, 10, "and"),
        (11, 13, "their patience"),
        (14, 16, "that"),
        (17, 19, "came again"),
        (20, 22, "the voice of"),
        (23, 24, "the Lord"),
        (25, 28, "unto them,"),
        (29, 31, "saying:"),
        (32, 33, "Be comforted"),
        (34, 34, "ye,"),
        (35, 36, "for on"),
        (37, 40, "the morrow"),
        (41, 46, "I will deliver"),
        (47, 47, "you"),
        (48, 50, "out of bondage."),
    ],
    17: [
        (0, 0, "And"),
        (1, 5, "he said"),
        (6, 7, "unto Alma:"),
        (8, 11, "Thou shalt go before"),
        (12, 14, "before"),
        (15, 16, "this people,"),
        (17, 17, "and"),
        (18, 23, "I will go"),
        (24, 26, "with thee"),
        (27, 28, "and deliver"),
        (29, 30, "this people"),
        (31, 33, "out of bondage."),
    ],
    18: [
        (0, 1, "Now"),
        (2, 4, "it came to pass"),
        (5, 6, "gathered together"),
        (7, 8, "Alma"),
        (9, 11, "and his people"),
        (12, 14, "their flocks"),
        (15, 17, "in the night,"),
        (18, 18, "and"),
        (19, 21, "their grain"),
        (22, 22, "also;"),
        (23, 23, "yea,"),
        (24, 27, "were they gathering together"),
        (28, 30, "their flocks"),
        (31, 34, "all the night."),
    ],
    19: [
        (0, 0, "And"),
        (1, 3, "in the morning"),
        (4, 5, "caused"),
        (6, 8, "the Lord"),
        (9, 11, "to come"),
        (12, 14, "a deep sleep"),
        (15, 17, "upon"),
        (18, 19, "the Lamanites,"),
        (20, 20, "yea,"),
        (21, 21, "and"),
        (22, 29, "all their taskmasters,"),
        (30, 34, "were in a profound sleep."),
    ],
    20: [
        (0, 0, "And"),
        (1, 4, "departed"),
        (5, 5, "Alma"),
        (6, 6, "and"),
        (7, 8, "his people"),
        (9, 11, "into the wilderness;"),
        (12, 12, "and"),
        (13, 15, "when had passed"),
        (16, 18, "they had traveled"),
        (19, 22, "all day"),
        (23, 25, "they pitched"),
        (26, 28, "their tents"),
        (29, 31, "in a valley,"),
        (32, 32, "and"),
        (33, 35, "they called"),
        (36, 37, "the valley"),
        (38, 39, "Alma,"),
        (40, 40, "because"),
        (41, 44, "he led"),
        (45, 47, "their way"),
        (48, 50, "in the wilderness."),
    ],
    21: [
        (0, 0, "Yea,"),
        (1, 1, "and"),
        (2, 4, "in the valley"),
        (5, 6, "of Alma"),
        (7, 11, "they poured out"),
        (12, 14, "their thanks"),
        (15, 17, "to God"),
        (18, 18, "because"),
        (19, 24, "he was merciful"),
        (25, 28, "unto them,"),
        (29, 32, "and eased"),
        (33, 35, "their burdens,"),
        (36, 36, "and"),
        (37, 40, "had delivered"),
        (41, 42, "them"),
        (43, 45, "out of bondage;"),
        (46, 46, "for"),
        (47, 50, "they were"),
        (51, 53, "in bondage,"),
        (54, 54, "and"),
        (55, 58, "none"),
        (59, 61, "could"),
        (62, 62, "deliver"),
        (63, 64, "them"),
        (65, 66, "except"),
        (67, 68, "the Lord"),
        (69, 71, "their God."),
    ],
    22: [
        (0, 0, "And"),
        (1, 3, "they gave"),
        (4, 5, "thanks"),
        (6, 8, "to God,"),
        (9, 9, "yea,"),
        (10, 14, "all their men"),
        (15, 15, "and"),
        (16, 19, "all their women"),
        (20, 20, "and"),
        (21, 24, "all their children"),
        (25, 26, "that"),
        (27, 29, "could"),
        (30, 30, "speak,"),
        (31, 33, "lifted up"),
        (34, 36, "their voices"),
        (37, 39, "in the praises of"),
        (40, 42, "their God."),
    ],
    23: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "said"),
        (6, 7, "the Lord"),
        (8, 9, "unto Alma:"),
        (10, 12, "Haste thee"),
        (13, 15, "and get"),
        (16, 16, "thou"),
        (17, 19, "and this people"),
        (20, 22, "out of this land,"),
        (23, 23, "for"),
        (24, 25, "have awakened"),
        (26, 27, "the Lamanites"),
        (28, 28, "and"),
        (29, 32, "do pursue"),
        (33, 33, "thee;"),
        (34, 35, "therefore"),
        (36, 40, "get thee out"),
        (41, 43, "of this land,"),
        (44, 44, "and"),
        (45, 49, "I will stop"),
        (50, 51, "the Lamanites"),
        (52, 55, "in this valley,"),
        (56, 57, "that"),
        (58, 62, "they come no further"),
        (63, 64, "in pursuit of"),
        (65, 66, "this people."),
    ],
    24: [
        (0, 3, "And it came to pass"),
        (4, 7, "they departed out of"),
        (8, 9, "the valley,"),
        (10, 12, "and took"),
        (13, 15, "their journey"),
        (16, 18, "into the wilderness."),
    ],
    25: [
        (0, 0, "And"),
        (1, 3, "after had passed"),
        (4, 4, "days"),
        (5, 7, "twelve"),
        (8, 11, "they had been"),
        (12, 14, "in the wilderness,"),
        (15, 17, "they arrived"),
        (18, 20, "in the land"),
        (21, 22, "of Zarahemla;"),
        (23, 23, "and"),
        (24, 26, "did also receive"),
        (27, 28, "them"),
        (29, 31, "with joy"),
        (32, 34, "the king"),
        (35, 36, "Mosiah."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
