"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 27 — the
Lamanites again seek to destroy the Anti-Nephi-Lehies; Ammon proposes they
flee to the Nephites; the Lord directs it; the people covenant and depart;
Ammon meets Alma; the Nephites give them the land of Jershon; they are
called the people of Ammon.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15).

Em-dash token split in the source per rule 11: `latou,—ona` (v4) — so
v4 = 110 tokens.

    python3 build_overrides_alma27.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 27

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 9, "when they had found"),
        (10, 12, "the Lamanites"),
        (13, 17, "who had gone"),
        (18, 20, "to war against"),
        (21, 23, "the Nephites,"),
        (24, 26, "after"),
        (27, 31, "their many struggles"),
        (32, 35, "to destroy them,"),
        (36, 38, "that it was in vain"),
        (39, 41, "their seeking"),
        (42, 45, "to destroy them,"),
        (46, 50, "they returned again to"),
        (51, 54, "the land of Nephi."),
    ],
    2: [
        (0, 3, "And it came to pass that"),
        (4, 6, "were exceedingly angry"),
        (7, 8, "the Amalekites,"),
        (9, 13, "because of the many of"),
        (14, 15, "them"),
        (16, 17, "had died."),
        (18, 22, "And when they saw"),
        (23, 28, "that they could not obtain"),
        (29, 32, "revenge"),
        (33, 36, "from the Nephites,"),
        (37, 41, "they began to stir up"),
        (42, 42, "the people"),
        (43, 44, "to anger"),
        (45, 47, "against"),
        (48, 50, "their brethren,"),
        (51, 55, "the people of Anti-Nephi-Lehi;"),
        (56, 57, "therefore"),
        (58, 62, "they began again"),
        (63, 64, "to destroy"),
        (65, 67, "them."),
    ],
    3: [
        (0, 1, "Now"),
        (2, 6, "this people again refused"),
        (7, 9, "to take up"),
        (10, 14, "their weapons of war,"),
        (15, 19, "and they suffered"),
        (20, 22, "themselves"),
        (23, 24, "to be slain"),
        (25, 29, "according to the desires of"),
        (30, 32, "their enemies."),
    ],
    4: [
        (0, 1, "Now"),
        (2, 5, "when saw"),
        (6, 9, "Ammon and his brethren"),
        (10, 13, "this work of"),
        (14, 15, "destruction"),
        (16, 20, "among them"),
        (21, 22, "who"),
        (23, 26, "were so beloved"),
        (27, 30, "unto them,"),
        (31, 36, "and among them"),
        (37, 38, "who"),
        (39, 42, "so dearly loved"),
        (43, 46, "them—"),
        (47, 50, "for they treated"),
        (51, 54, "them"),
        (55, 58, "as though they were"),
        (59, 61, "angels"),
        (62, 65, "sent by"),
        (66, 67, "God"),
        (68, 71, "to save them"),
        (72, 76, "from everlasting destruction—"),
        (77, 78, "therefore,"),
        (79, 82, "when saw"),
        (83, 86, "Ammon and his brethren"),
        (87, 90, "this work of"),
        (91, 93, "great destruction,"),
        (94, 97, "they were moved"),
        (98, 101, "with compassion,"),
        (102, 106, "and they said"),
        (107, 109, "unto the king:"),
    ],
    5: [
        (0, 3, "Let us gather together"),
        (4, 8, "this people of the Lord,"),
        (9, 13, "and let us go down"),
        (14, 14, "to"),
        (15, 18, "the land of Zarahemla"),
        (19, 22, "to our brethren"),
        (23, 25, "the Nephites,"),
        (26, 29, "and let us flee"),
        (30, 32, "out of the hands of"),
        (33, 35, "our enemies,"),
        (36, 39, "that be not destroyed"),
        (40, 41, "we."),
    ],
    6: [
        (0, 0, "But"),
        (1, 3, "said"),
        (4, 5, "the king"),
        (6, 9, "unto them:"),
        (10, 10, "Behold,"),
        (11, 14, "will destroy"),
        (15, 16, "us"),
        (17, 19, "the Nephites,"),
        (20, 24, "because of the murders"),
        (25, 28, "and many sins"),
        (29, 31, "we have committed"),
        (32, 35, "against them."),
    ],
    7: [
        (0, 3, "And said"),
        (4, 4, "Ammon:"),
        (5, 9, "I will go"),
        (10, 13, "and inquire of"),
        (14, 15, "the Lord,"),
        (16, 22, "and if he say"),
        (23, 26, "unto us,"),
        (27, 30, "let us go down"),
        (31, 34, "unto our brethren,"),
        (35, 39, "will ye go?"),
    ],
    8: [
        (0, 3, "And said"),
        (4, 5, "the king"),
        (6, 8, "unto him:"),
        (9, 9, "Yea,"),
        (10, 13, "if say"),
        (14, 15, "the Lord"),
        (16, 19, "unto us"),
        (20, 21, "go,"),
        (22, 25, "we will"),
        (26, 27, "go down"),
        (28, 31, "unto our brethren,"),
        (32, 36, "and we will become"),
        (37, 38, "we"),
        (39, 42, "their slaves"),
        (43, 46, "until we"),
        (47, 49, "make amends"),
        (50, 53, "unto them"),
        (54, 57, "for the murders"),
        (58, 61, "and many sins"),
        (62, 64, "which we have committed"),
        (65, 68, "against them."),
    ],
    9: [
        (0, 0, "But"),
        (1, 3, "said"),
        (4, 4, "Ammon"),
        (5, 7, "unto him:"),
        (8, 10, "It is against"),
        (11, 13, "the law of"),
        (14, 16, "our brethren,"),
        (17, 19, "which was established"),
        (20, 22, "by my father,"),
        (23, 24, "that"),
        (25, 28, "it is not right"),
        (29, 30, "to be"),
        (31, 32, "any slaves"),
        (33, 34, "among"),
        (35, 38, "them;"),
        (39, 40, "therefore"),
        (41, 44, "let us go down"),
        (45, 47, "and rely upon"),
        (48, 51, "the mercies of"),
        (52, 54, "our brethren."),
    ],
    10: [
        (0, 0, "But"),
        (1, 3, "said"),
        (4, 5, "the king"),
        (6, 8, "unto him:"),
        (9, 11, "Inquire of"),
        (12, 13, "the Lord,"),
        (14, 20, "and if he say"),
        (21, 24, "unto us"),
        (25, 26, "go,"),
        (27, 31, "we will go;"),
        (32, 33, "otherwise"),
        (34, 37, "we will"),
        (38, 39, "perish"),
        (40, 42, "in the land."),
    ],
    11: [
        (0, 3, "And it came to pass that"),
        (4, 6, "Ammon went"),
        (7, 9, "and inquired of"),
        (10, 11, "the Lord,"),
        (12, 15, "and said"),
        (16, 17, "the Lord"),
        (18, 20, "unto him:"),
    ],
    12: [
        (0, 3, "Get out"),
        (4, 5, "this people"),
        (6, 8, "from this land,"),
        (9, 12, "that perish not"),
        (13, 14, "they;"),
        (15, 18, "for great is the strength"),
        (19, 22, "of Satan's hold"),
        (23, 27, "on the hearts of the Amalekites,"),
        (28, 31, "who do stir up"),
        (32, 33, "the Lamanites"),
        (34, 35, "to anger"),
        (36, 39, "against their brethren,"),
        (40, 41, "to slay"),
        (42, 45, "them;"),
        (46, 47, "therefore"),
        (48, 53, "get thee out"),
        (54, 56, "from this land;"),
        (57, 61, "and blessed is this people"),
        (62, 64, "in this generation,"),
        (65, 65, "for"),
        (66, 70, "I will preserve"),
        (71, 72, "them."),
    ],
    13: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 8, "Ammon went"),
        (9, 11, "and told"),
        (12, 14, "the king"),
        (15, 16, "all the words"),
        (17, 20, "which had said"),
        (21, 22, "the Lord"),
        (23, 25, "unto him."),
    ],
    14: [
        (0, 4, "And they gathered together"),
        (5, 8, "all their people,"),
        (9, 9, "yea,"),
        (10, 12, "all the people of"),
        (13, 14, "the Lord,"),
        (15, 17, "and gathered together"),
        (18, 20, "their flocks"),
        (21, 23, "and all herds,"),
        (24, 27, "and departed"),
        (28, 30, "out of the land,"),
        (31, 34, "and came into"),
        (35, 36, "the wilderness"),
        (37, 40, "which divided"),
        (41, 44, "the land of Nephi"),
        (45, 49, "from the land of Zarahemla,"),
        (50, 54, "and came up near"),
        (55, 58, "the borders of the land."),
    ],
    15: [
        (0, 3, "And it came to pass that"),
        (4, 6, "Ammon said"),
        (7, 10, "unto them:"),
        (11, 11, "Behold,"),
        (12, 16, "I and my brethren"),
        (17, 20, "we will"),
        (21, 22, "go forth"),
        (23, 27, "into the land of Zarahemla,"),
        (28, 32, "and ye shall"),
        (33, 34, "wait"),
        (35, 35, "here"),
        (36, 39, "until we return;"),
        (40, 44, "and we will"),
        (45, 45, "try"),
        (46, 50, "the hearts of our brethren,"),
        (51, 54, "whether they will"),
        (55, 58, "that ye come"),
        (59, 62, "into their land."),
    ],
    16: [
        (0, 3, "And it came to pass that"),
        (4, 7, "as Ammon was going"),
        (8, 10, "into the land,"),
        (11, 14, "he met"),
        (15, 17, "and his brethren"),
        (18, 19, "Alma,"),
        (20, 23, "in the place which"),
        (24, 25, "was mentioned;"),
        (26, 27, "and behold,"),
        (28, 33, "this was a very joyful meeting."),
    ],
    17: [
        (0, 1, "Now"),
        (2, 5, "was exceedingly great"),
        (6, 9, "the joy of Ammon,"),
        (10, 12, "insomuch that"),
        (13, 15, "he was full;"),
        (16, 16, "yea,"),
        (17, 20, "he was swallowed up"),
        (21, 23, "in the joy"),
        (24, 26, "of his God,"),
        (27, 30, "insomuch that failed"),
        (31, 32, "his strength;"),
        (33, 40, "and he fell again"),
        (41, 43, "to the earth."),
    ],
    18: [
        (0, 1, "Now"),
        (2, 4, "was not"),
        (5, 7, "exceeding joy"),
        (8, 9, "this?"),
        (10, 10, "Behold,"),
        (11, 14, "this is the joy"),
        (15, 17, "which receiveth not"),
        (18, 20, "any one,"),
        (21, 22, "save it be"),
        (23, 26, "the truly penitent"),
        (27, 30, "and the seeker"),
        (31, 33, "for happiness"),
        (34, 36, "and the humble."),
    ],
    19: [
        (0, 1, "Now"),
        (2, 6, "was truly exceeding great"),
        (7, 10, "the joy of Alma"),
        (11, 13, "in the meeting"),
        (14, 16, "with his brethren,"),
        (17, 21, "and also the joy of"),
        (22, 22, "Aaron,"),
        (23, 24, "and Omner,"),
        (25, 26, "and Himni;"),
        (27, 28, "but behold,"),
        (29, 32, "did not exceed"),
        (33, 35, "their joy"),
        (36, 39, "beyond their strength."),
    ],
    20: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 10, "Alma led back"),
        (11, 12, "his brethren"),
        (13, 14, "back"),
        (15, 19, "to the land of Zarahemla;"),
        (20, 23, "even to his own house."),
        (24, 28, "And they went"),
        (29, 31, "and told"),
        (32, 35, "the chief judge"),
        (36, 39, "all the things that happened"),
        (40, 43, "unto them"),
        (44, 48, "in the land of Nephi,"),
        (49, 51, "among"),
        (52, 54, "their brethren,"),
        (55, 57, "the Lamanites."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 6, "was sent by"),
        (7, 9, "the chief judge"),
        (10, 11, "a proclamation"),
        (12, 15, "throughout all the land,"),
        (16, 18, "desiring to know"),
        (19, 23, "the voice of the people"),
        (24, 28, "concerning the admitting"),
        (29, 29, "of"),
        (30, 32, "their brethren,"),
        (33, 37, "who were the people of"),
        (38, 38, "Anti-Nephi-Lehi."),
    ],
    22: [
        (0, 3, "And it came to pass that"),
        (4, 5, "there came"),
        (6, 10, "the voice of the people,"),
        (11, 12, "saying:"),
        (13, 13, "Behold,"),
        (14, 17, "we will"),
        (18, 19, "give up"),
        (20, 23, "the land of Jershon,"),
        (24, 29, "which is on the side"),
        (30, 31, "east"),
        (32, 34, "by the sea,"),
        (35, 38, "which joins"),
        (39, 42, "the land Bountiful,"),
        (43, 48, "which is on the side"),
        (49, 51, "south of"),
        (52, 55, "the land Bountiful;"),
        (56, 60, "and this land"),
        (61, 62, "of Jershon"),
        (63, 66, "is the land which"),
        (67, 70, "we will"),
        (71, 72, "give"),
        (73, 76, "unto our brethren"),
        (77, 80, "for their inheritance."),
    ],
    23: [
        (0, 1, "And behold,"),
        (2, 6, "we will place"),
        (7, 9, "our armies"),
        (10, 13, "between"),
        (14, 17, "the land of Jershon"),
        (18, 22, "and the land of Nephi,"),
        (23, 27, "that we may"),
        (28, 28, "protect"),
        (29, 31, "our brethren"),
        (32, 36, "in the land of Jershon;"),
        (37, 42, "and we will do"),
        (43, 44, "this thing"),
        (45, 48, "for our brethren,"),
        (49, 53, "because of their fear"),
        (54, 58, "to use weapons of war"),
        (59, 61, "against"),
        (62, 64, "their brethren"),
        (65, 68, "lest they commit"),
        (69, 70, "sin;"),
        (71, 74, "and there came"),
        (75, 78, "upon them"),
        (79, 81, "this great fear"),
        (82, 85, "because of their"),
        (86, 88, "sore repentance"),
        (89, 91, "which came"),
        (92, 95, "upon them,"),
        (96, 100, "because of the many of"),
        (101, 104, "their murders"),
        (105, 107, "and their"),
        (108, 110, "awful wickedness."),
    ],
    24: [
        (0, 3, "And now behold,"),
        (4, 8, "we will do"),
        (9, 10, "this thing"),
        (11, 14, "for our brethren,"),
        (15, 19, "that may become"),
        (20, 23, "for their inheritance"),
        (24, 27, "the land of Jershon;"),
        (28, 32, "and we will"),
        (33, 33, "guard"),
        (34, 35, "them"),
        (36, 40, "from their enemies"),
        (41, 44, "with our armies,"),
        (45, 50, "on condition that they give"),
        (51, 54, "unto us"),
        (55, 57, "a portion of"),
        (58, 60, "their substance"),
        (61, 62, "to assist"),
        (63, 66, "us"),
        (67, 72, "that we may maintain"),
        (73, 75, "our armies."),
    ],
    25: [
        (0, 1, "Now,"),
        (2, 4, "it came to pass that"),
        (5, 8, "when Ammon had heard"),
        (9, 11, "this,"),
        (12, 16, "he returned"),
        (17, 21, "to the people of Anti-Nephi-Lehi,"),
        (22, 24, "and Alma also"),
        (25, 27, "with him,"),
        (28, 30, "into the wilderness,"),
        (31, 33, "in the place where"),
        (34, 36, "had been pitched"),
        (37, 39, "their tents,"),
        (40, 42, "and made known"),
        (43, 46, "unto them"),
        (47, 49, "all these things."),
        (50, 54, "and also related"),
        (55, 56, "Alma"),
        (57, 60, "unto them"),
        (61, 65, "concerning his conversion,"),
        (66, 68, "with Ammon"),
        (69, 70, "and Aaron,"),
        (71, 73, "and his brethren."),
    ],
    26: [
        (0, 3, "And it came to pass that"),
        (4, 6, "this thing"),
        (7, 10, "brought"),
        (11, 13, "great joy"),
        (14, 18, "among them."),
        (19, 23, "And they went"),
        (24, 24, "into"),
        (25, 28, "the land of Jershon"),
        (29, 30, "and became"),
        (31, 34, "the land of Jershon"),
        (35, 39, "for them;"),
        (40, 44, "and they were called"),
        (45, 47, "by the Nephites"),
        (48, 52, "the people of Ammon;"),
        (53, 54, "therefore"),
        (55, 59, "they were distinguished"),
        (60, 62, "by that name"),
        (63, 66, "from that very time."),
    ],
    27: [
        (0, 3, "And were"),
        (4, 5, "they"),
        (6, 8, "among"),
        (9, 12, "the people of Nephi,"),
        (13, 15, "and also numbered"),
        (16, 19, "among the people"),
        (20, 24, "who belonged to"),
        (25, 29, "the church of God."),
        (30, 33, "And were also distinguished"),
        (34, 35, "they"),
        (36, 39, "for their zeal"),
        (40, 42, "towards God,"),
        (43, 46, "and also towards men;"),
        (47, 47, "for"),
        (48, 51, "they were perfectly honest"),
        (52, 53, "and upright"),
        (54, 56, "in all things;"),
        (57, 60, "and they were firm"),
        (61, 64, "in their faith"),
        (65, 66, "in Christ,"),
        (67, 71, "even unto the end."),
    ],
    28: [
        (0, 4, "And they did look upon"),
        (5, 7, "the shedding of"),
        (8, 10, "the blood of"),
        (11, 13, "their brethren"),
        (14, 17, "with the greatest abhorrence;"),
        (18, 23, "and never could be"),
        (24, 24, "persuaded"),
        (25, 26, "them"),
        (27, 29, "to take up"),
        (30, 32, "weapons of war"),
        (33, 35, "against"),
        (36, 38, "their brethren;"),
        (39, 43, "and they did not look"),
        (44, 44, "at all"),
        (45, 47, "upon death"),
        (48, 50, "with any terror,"),
        (51, 55, "because of their hope"),
        (56, 57, "and views"),
        (58, 61, "concerning Christ"),
        (62, 64, "and the resurrection;"),
        (65, 66, "therefore,"),
        (67, 71, "unto them"),
        (72, 75, "death was swallowed up"),
        (76, 80, "by the victory of"),
        (81, 81, "Christ"),
        (82, 84, "over it."),
    ],
    29: [
        (0, 1, "Therefore,"),
        (2, 5, "they suffered"),
        (6, 7, "death"),
        (8, 10, "to come"),
        (11, 14, "upon them"),
        (15, 19, "in the most"),
        (20, 22, "grievous and painful way"),
        (23, 26, "which could be done"),
        (27, 30, "by their brethren,"),
        (31, 35, "before they would take"),
        (36, 37, "the sword"),
        (38, 41, "or the cimeter"),
        (42, 46, "to smite them."),
    ],
    30: [
        (0, 4, "And thus became"),
        (5, 7, "they"),
        (8, 10, "a zealous people"),
        (11, 12, "and beloved,"),
        (13, 15, "a people"),
        (16, 18, "highly favored"),
        (19, 21, "of the Lord."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
