"""
Hand-curated TAM-phrase gloss overrides for 3 Nifae (3 Nephi) 21 — Jesus gives the
sign by which the covenant people shall know that the work of the Father has begun:
when the record of the Book of Mormon comes forth among the Gentiles, the gathering
of scattered Israel and the building of the New Jerusalem are at hand. He warns the
Gentiles that if they will not repent the covenant people of Jacob shall go through
them as a lion, and prophesies of the marred servant and the great and marvelous
work — the establishment of Zion and the fulfilment of the Father's covenant.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-split applied to bom_books.json before glossing:
    21:2  faailoga—aua  ->  faailoga—  +  aua

    python3 build_overrides_3nephi21.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "3nephi"
CHAPTER_NUM = 21

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And verily"),
        (3, 6, "I say"),
        (7, 9, "unto you,"),
        (10, 13, "I give"),
        (14, 16, "unto you"),
        (17, 18, "a sign,"),
        (19, 22, "that ye may know"),
        (23, 24, "the time"),
        (25, 29, "when shall be near"),
        (30, 31, "to take place"),
        (32, 33, "these things—"),
        (34, 40, "that I shall gather in"),
        (41, 42, "my people,"),
        (43, 44, "O house"),
        (45, 46, "of Israel,"),
        (47, 49, "from the length"),
        (50, 53, "of their scattering,"),
        (54, 56, "and shall establish again"),
        (57, 60, "among them"),
        (61, 62, "my Zion;"),
    ],
    2: [
        (0, 1, "And behold,"),
        (2, 5, "this is the thing"),
        (6, 11, "which I will give"),
        (12, 14, "unto you"),
        (15, 17, "for a sign—"),
        (18, 20, "for verily"),
        (21, 24, "I say"),
        (25, 27, "unto you,"),
        (28, 30, "that when it shall come to pass that"),
        (31, 32, "shall be manifested"),
        (33, 34, "these things"),
        (35, 38, "which I declare"),
        (39, 41, "unto you,"),
        (42, 43, "and which"),
        (44, 48, "I shall declare"),
        (49, 51, "unto you"),
        (52, 54, "at a time"),
        (55, 57, "that followeth after"),
        (58, 61, "of myself,"),
        (62, 65, "and by the power"),
        (66, 69, "of the Holy Ghost"),
        (70, 75, "which shall be given"),
        (76, 78, "unto you"),
        (79, 81, "of the Father,"),
        (82, 83, "unto the Gentiles,"),
        (84, 87, "that they may know"),
        (88, 90, "concerning"),
        (91, 92, "this people"),
        (93, 95, "a portion"),
        (96, 97, "of the remnant"),
        (98, 100, "of the house"),
        (101, 102, "of Jacob,"),
        (103, 106, "and concerning"),
        (107, 109, "this my people"),
        (110, 111, "who"),
        (112, 116, "shall be scattered;"),
    ],
    3: [
        (0, 1, "Verily,"),
        (2, 3, "verily,"),
        (4, 7, "I say"),
        (8, 10, "unto you,"),
        (11, 14, "when shall be made known"),
        (15, 16, "these things"),
        (17, 20, "unto them"),
        (21, 23, "of the Father,"),
        (24, 29, "and shall come forth"),
        (30, 30, "from"),
        (31, 32, "the Father,"),
        (33, 33, "from"),
        (34, 37, "them"),
        (38, 40, "unto you;"),
    ],
    4: [
        (0, 3, "For the wisdom"),
        (4, 6, "that is"),
        (7, 9, "in the Father"),
        (10, 13, "that should be established"),
        (14, 15, "them"),
        (16, 18, "in this land,"),
        (19, 20, "and be set up"),
        (21, 24, "as a free people"),
        (25, 27, "by the power"),
        (28, 30, "of the Father,"),
        (31, 34, "that might"),
        (35, 36, "come forth"),
        (37, 39, "these things"),
        (40, 40, "from"),
        (41, 44, "them"),
        (45, 47, "unto a portion"),
        (48, 49, "of the remnant"),
        (50, 53, "of your seed,"),
        (54, 57, "that may"),
        (58, 58, "be fulfilled"),
        (59, 61, "the covenant"),
        (62, 64, "of the Father"),
        (65, 65, "which"),
        (66, 69, "he hath covenanted"),
        (70, 72, "with his people,"),
        (73, 75, "O house"),
        (76, 77, "of Israel;"),
    ],
    5: [
        (0, 1, "Therefore,"),
        (2, 4, "when shall come forth"),
        (5, 6, "these works"),
        (7, 8, "and the works"),
        (9, 12, "which shall be wrought"),
        (13, 14, "among"),
        (15, 16, "you"),
        (17, 19, "at a time"),
        (20, 22, "that followeth after"),
        (23, 23, "from"),
        (24, 24, "the Gentiles,"),
        (25, 27, "unto your seed"),
        (28, 29, "which"),
        (30, 33, "shall dwindle"),
        (34, 37, "in unbelief"),
        (38, 39, "because of"),
        (40, 40, "iniquity;"),
    ],
    6: [
        (0, 0, "For"),
        (1, 4, "thus it is the will"),
        (5, 6, "of the Father"),
        (7, 11, "that should come forth"),
        (12, 13, "these things"),
        (14, 14, "from"),
        (15, 15, "the Gentiles,"),
        (16, 22, "that he may show forth"),
        (23, 24, "his power"),
        (25, 26, "unto the Gentiles,"),
        (27, 30, "for this cause,"),
        (31, 34, "that they may repent"),
        (35, 37, "and come"),
        (38, 40, "unto me"),
        (41, 42, "and be baptized"),
        (43, 45, "in my name"),
        (46, 47, "and know"),
        (48, 50, "of"),
        (51, 52, "the true points"),
        (53, 56, "of my doctrine,"),
        (57, 61, "that they may be numbered"),
        (62, 63, "them"),
        (64, 65, "among"),
        (66, 68, "my people,"),
        (69, 71, "O house"),
        (72, 73, "of Israel,"),
        (74, 79, "if they will not harden"),
        (80, 82, "their hearts;"),
    ],
    7: [
        (0, 3, "And when shall come to pass"),
        (4, 5, "these things"),
        (6, 11, "shall begin to know"),
        (12, 14, "thy seed"),
        (15, 16, "these things—"),
        (17, 20, "it shall become"),
        (21, 23, "a sign"),
        (24, 27, "unto them,"),
        (28, 34, "that they may know"),
        (35, 38, "hath already commenced"),
        (39, 41, "the work"),
        (42, 44, "of the Father"),
        (45, 47, "unto the fulfilling"),
        (48, 51, "of the covenant which"),
        (52, 54, "he hath made"),
        (55, 57, "unto the people"),
        (58, 59, "who are"),
        (60, 62, "of the house"),
        (63, 64, "of Israel."),
    ],
    8: [
        (0, 4, "And when shall come"),
        (5, 6, "that day,"),
        (7, 11, "it shall come to pass"),
        (12, 15, "shall shut"),
        (16, 17, "kings"),
        (18, 21, "their mouths;"),
        (22, 22, "for"),
        (23, 27, "they shall see"),
        (28, 29, "that which"),
        (30, 33, "had not been told"),
        (34, 37, "them;"),
        (38, 43, "and they shall consider"),
        (44, 45, "that which"),
        (46, 51, "they had not heard."),
    ],
    9: [
        (0, 0, "For"),
        (1, 3, "in that day,"),
        (4, 5, "for"),
        (6, 7, "my own sake,"),
        (8, 12, "shall work"),
        (13, 15, "the Father"),
        (16, 17, "a work,"),
        (18, 22, "which shall become"),
        (23, 26, "a great work"),
        (27, 29, "and a marvelous one"),
        (30, 31, "among"),
        (32, 35, "them;"),
        (36, 41, "and there shall be"),
        (42, 43, "among"),
        (44, 47, "them"),
        (48, 49, "some"),
        (50, 51, "who"),
        (52, 58, "will not believe it,"),
        (59, 61, "although"),
        (62, 66, "shall declare it"),
        (67, 69, "a man"),
        (70, 73, "unto them."),
    ],
    10: [
        (0, 1, "But behold,"),
        (2, 6, "shall be"),
        (7, 9, "in my hand"),
        (10, 11, "the life"),
        (12, 14, "of my servant;"),
        (15, 16, "therefore"),
        (17, 25, "they shall not hurt him,"),
        (26, 29, "although"),
        (30, 35, "he shall be marred"),
        (36, 37, "because of"),
        (38, 39, "them."),
        (40, 40, "Yet"),
        (41, 47, "I will heal him,"),
        (48, 48, "for"),
        (49, 54, "I will show"),
        (55, 58, "unto them"),
        (59, 61, "is greater"),
        (62, 66, "the greatness of my wisdom"),
        (67, 68, "than"),
        (69, 69, "the cunning"),
        (70, 72, "of the devil."),
    ],
    11: [
        (0, 1, "Therefore,"),
        (2, 7, "it shall come to pass"),
        (8, 11, "that whosoever"),
        (12, 14, "will not believe"),
        (15, 17, "in my words,"),
        (18, 20, "who am"),
        (21, 22, "Jesus Christ,"),
        (23, 24, "whom"),
        (25, 30, "shall be commanded"),
        (31, 33, "by the Father"),
        (34, 35, "to bring forth"),
        (36, 37, "unto the Gentiles,"),
        (38, 44, "and he shall give"),
        (45, 47, "unto him"),
        (48, 49, "the power"),
        (50, 55, "that he shall bring forth"),
        (56, 57, "them"),
        (58, 59, "unto the Gentiles,"),
        (60, 63, "(it shall be done"),
        (64, 71, "even as Moses said)"),
        (72, 76, "shall be cut off"),
        (77, 78, "from among"),
        (79, 81, "my people"),
        (82, 83, "they"),
        (84, 86, "of the covenant."),
    ],
    12: [
        (0, 3, "And my people"),
        (4, 8, "who are a portion"),
        (9, 10, "of the remnant"),
        (11, 12, "of Jacob"),
        (13, 17, "shall be"),
        (18, 19, "among"),
        (20, 21, "the Gentiles,"),
        (22, 22, "yea,"),
        (23, 24, "in the midst"),
        (25, 27, "of them"),
        (28, 32, "as a lion"),
        (33, 36, "among the beasts"),
        (37, 39, "of the forest,"),
        (40, 41, "as"),
        (42, 45, "a young lion"),
        (46, 49, "among the flocks"),
        (50, 50, "of sheep,"),
        (51, 52, "who,"),
        (53, 53, "if"),
        (54, 59, "he go through,"),
        (60, 66, "he treadeth down"),
        (67, 68, "them"),
        (69, 70, "and teareth"),
        (71, 71, "in pieces,"),
        (72, 75, "and none"),
        (76, 79, "can deliver."),
    ],
    13: [
        (0, 4, "Shall be lifted up"),
        (5, 7, "their hand"),
        (8, 10, "upon"),
        (11, 13, "their adversaries,"),
        (14, 19, "and shall be cut off"),
        (20, 23, "all their enemies."),
    ],
    14: [
        (0, 0, "Yea,"),
        (1, 2, "wo be"),
        (3, 4, "unto the Gentiles"),
        (5, 6, "except"),
        (7, 9, "they repent;"),
        (10, 10, "for"),
        (11, 15, "it shall come to pass"),
        (16, 18, "in that day,"),
        (19, 22, "saith"),
        (23, 24, "the Father,"),
        (25, 30, "I will cut off"),
        (31, 32, "thy horses"),
        (33, 33, "out of the midst of"),
        (34, 36, "thee,"),
        (37, 42, "and I will destroy"),
        (43, 44, "thy chariots;"),
    ],
    15: [
        (0, 6, "And I will cut off"),
        (7, 7, "the cities"),
        (8, 10, "of thy land,"),
        (11, 14, "and throw down"),
        (15, 18, "all thy strongholds;"),
    ],
    16: [
        (0, 6, "And I will cut off"),
        (7, 7, "witchcrafts"),
        (8, 8, "out of"),
        (9, 10, "thy land,"),
        (11, 18, "and there shall no more be"),
        (19, 21, "unto thee"),
        (22, 24, "soothsayers;"),
    ],
    17: [
        (0, 6, "I will also cut off"),
        (7, 8, "thy images"),
        (9, 10, "that are carved,"),
        (11, 14, "and thy standing images"),
        (15, 15, "out of"),
        (16, 18, "the midst of thee,"),
        (19, 27, "and thou shalt no more worship"),
        (28, 29, "the works"),
        (30, 32, "of thy hands;"),
    ],
    18: [
        (0, 6, "And I will pluck up"),
        (7, 8, "thy groves"),
        (9, 10, "out of the midst"),
        (11, 13, "of thee;"),
        (14, 16, "so shall it be"),
        (17, 20, "I will destroy"),
        (21, 23, "thy cities."),
    ],
    19: [
        (0, 5, "And it shall come to pass"),
        (6, 7, "that all lyings,"),
        (8, 9, "and deceivings,"),
        (10, 11, "and envyings,"),
        (12, 13, "and strifes,"),
        (14, 16, "and priestcrafts,"),
        (17, 19, "and all whoredoms,"),
        (20, 23, "shall be done away."),
    ],
    20: [
        (0, 0, "For"),
        (1, 5, "it shall come to pass,"),
        (6, 9, "saith"),
        (10, 11, "the Father,"),
        (12, 14, "at that day,"),
        (15, 18, "whosoever"),
        (19, 21, "will not repent"),
        (22, 23, "and come"),
        (24, 27, "unto my Beloved Son,"),
        (28, 31, "them"),
        (32, 37, "will I cut off"),
        (38, 39, "from among"),
        (40, 42, "my people,"),
        (43, 44, "O house"),
        (45, 46, "of Israel;"),
    ],
    21: [
        (0, 5, "And I will execute"),
        (6, 7, "vengeance"),
        (8, 11, "and fury"),
        (12, 14, "upon"),
        (15, 16, "them,"),
        (17, 21, "even as is done"),
        (22, 24, "upon"),
        (25, 27, "the heathen,"),
        (28, 30, "in a manner"),
        (31, 36, "they have not heard."),
    ],
    22: [
        (0, 4, "But if they will repent"),
        (5, 7, "and hearken"),
        (8, 10, "unto my words,"),
        (11, 13, "and harden not"),
        (14, 16, "their hearts,"),
        (17, 21, "I will establish"),
        (22, 23, "my church"),
        (24, 25, "among"),
        (26, 28, "them,"),
        (29, 35, "and they shall come in"),
        (36, 38, "into"),
        (39, 40, "the covenant,"),
        (41, 42, "and be numbered"),
        (43, 45, "among"),
        (46, 48, "this remnant"),
        (49, 52, "of the seed of Jacob,"),
        (53, 54, "unto whom"),
        (55, 60, "I have given"),
        (61, 63, "this land"),
        (64, 67, "for their inheritance;"),
    ],
    23: [
        (0, 5, "And they shall assist"),
        (6, 8, "my people,"),
        (9, 12, "the remnant"),
        (13, 14, "of Jacob,"),
        (15, 18, "and also as many"),
        (19, 21, "of the house"),
        (22, 23, "of Israel"),
        (24, 28, "as shall come,"),
        (29, 34, "that they may build"),
        (35, 37, "a city,"),
        (38, 38, "which"),
        (39, 43, "they shall call"),
        (44, 47, "the New Jerusalem."),
    ],
    24: [
        (0, 5, "And then shall they assist"),
        (6, 8, "my people"),
        (9, 12, "that they may be gathered in,"),
        (13, 14, "them,"),
        (15, 18, "who are scattered"),
        (19, 21, "upon"),
        (22, 24, "all the land,"),
        (25, 27, "in unto"),
        (28, 30, "the New Jerusalem."),
    ],
    25: [
        (0, 5, "And then shall come"),
        (6, 7, "down"),
        (8, 10, "the power"),
        (11, 13, "of heaven"),
        (14, 16, "among them;"),
        (17, 24, "and I also will be"),
        (25, 27, "in the midst."),
    ],
    26: [
        (0, 4, "And then shall commence"),
        (5, 7, "the work"),
        (8, 10, "of the Father"),
        (11, 13, "at that day,"),
        (14, 17, "even when"),
        (18, 23, "shall be preached"),
        (24, 25, "this gospel"),
        (26, 28, "among"),
        (29, 32, "the remnant"),
        (33, 35, "of this people."),
        (36, 37, "Verily"),
        (38, 41, "I say"),
        (42, 44, "unto you,"),
        (45, 47, "at that day"),
        (48, 52, "shall commence"),
        (53, 54, "the work"),
        (55, 57, "of the Father"),
        (58, 60, "among"),
        (61, 62, "all"),
        (63, 65, "of my people"),
        (66, 67, "who are scattered,"),
        (68, 68, "yea,"),
        (69, 72, "even unto"),
        (73, 75, "the tribes that were lost,"),
        (76, 76, "which"),
        (77, 80, "were led away"),
        (81, 83, "by the Father"),
        (84, 84, "out of"),
        (85, 85, "Jerusalem."),
    ],
    27: [
        (0, 0, "Yea,"),
        (1, 4, "shall commence,"),
        (5, 7, "by the Father,"),
        (8, 9, "the work"),
        (10, 12, "among"),
        (13, 14, "all"),
        (15, 17, "of my people"),
        (18, 19, "who are scattered,"),
        (20, 21, "to prepare"),
        (22, 23, "the way"),
        (24, 28, "whereby they may"),
        (29, 30, "come"),
        (31, 33, "unto me,"),
        (34, 40, "that they may call"),
        (41, 43, "on the Father"),
        (44, 46, "in my name."),
    ],
    28: [
        (0, 0, "Yea,"),
        (1, 5, "and then shall commence,"),
        (6, 8, "by the Father,"),
        (9, 10, "the work"),
        (11, 13, "among"),
        (14, 15, "all nations,"),
        (16, 18, "in the preparing"),
        (19, 21, "of the way"),
        (22, 27, "whereby may be gathered"),
        (28, 29, "his people"),
        (30, 32, "home"),
        (33, 35, "to the land"),
        (36, 39, "of their inheritance."),
    ],
    29: [
        (0, 6, "And they shall go out"),
        (7, 7, "from"),
        (8, 9, "all nations;"),
        (10, 18, "and they shall not go out"),
        (19, 19, "in haste,"),
        (20, 22, "nor go"),
        (23, 23, "by flight,"),
        (24, 24, "for"),
        (25, 29, "I will go before"),
        (30, 33, "them,"),
        (34, 37, "saith"),
        (38, 39, "the Father,"),
        (40, 46, "and I will be the rearward"),
        (47, 50, "for them."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
