"""
Hand-curated TAM-phrase gloss overrides for Eteru (Ether) 12 — Ether the prophet cries
repentance in the days of Coriantumr, is cast out, and hides by day and prophesies by
night. Moroni then delivers the great discourse on faith: faith is things hoped for and
not seen; by faith all things were done; miracles come only after the trial of faith; the
brother of Jared's mighty faith; charity as the highest gift; and the Lord's promise that
he gives weakness that men may be humble, and grace that makes weak things strong.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15, vocative 12). `o le a` stays atomic and is never
fused with a following `se X` NP; cells go past 5 only for rule-2 (absorbed
subject) or rule-7 (`o le a` + verb + directional) clusters.

    python3 build_overrides_ether12.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "ether"
CHAPTER_NUM = 12

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 6, "there were"),
        (7, 9, "the days of Ether"),
        (10, 14, "in the days of Coriantumr;"),
        (15, 17, "and Coriantumr"),
        (18, 19, "did reign"),
        (20, 23, "over all the land."),
    ],
    2: [
        (0, 2, "And was"),
        (3, 3, "Ether"),
        (4, 6, "a prophet"),
        (7, 9, "of the Lord;"),
        (10, 13, "wherefore"),
        (14, 17, "went forth"),
        (18, 18, "Ether"),
        (19, 23, "in the days of Coriantumr,"),
        (24, 28, "and began to prophesy"),
        (29, 30, "unto the people,"),
        (31, 34, "for was not able"),
        (35, 38, "to hinder him"),
        (39, 42, "because of the Spirit"),
        (43, 45, "of the Lord"),
        (46, 49, "which dwelt within"),
        (50, 52, "him."),
    ],
    3: [
        (0, 4, "For he did cry"),
        (5, 5, "from"),
        (6, 7, "the morning,"),
        (8, 10, "even until"),
        (11, 14, "the going down"),
        (15, 17, "of the sun,"),
        (18, 20, "exhorting"),
        (21, 22, "the people"),
        (23, 24, "to believe"),
        (25, 27, "in God"),
        (28, 29, "unto repentance"),
        (30, 33, "lest they be destroyed,"),
        (34, 36, "and saying"),
        (37, 40, "unto them"),
        (41, 43, "that by faith"),
        (44, 46, "are fulfilled"),
        (47, 48, "all things—"),
    ],
    4: [
        (0, 3, "Wherefore,"),
        (4, 6, "whosoever"),
        (7, 8, "believeth"),
        (9, 11, "in God"),
        (12, 16, "might surely hope"),
        (17, 19, "for a world"),
        (20, 23, "far better,"),
        (24, 24, "yea,"),
        (25, 27, "even a place"),
        (28, 31, "at the right hand"),
        (32, 34, "of God,"),
        (35, 38, "which hope"),
        (39, 41, "cometh from"),
        (42, 43, "faith,"),
        (44, 47, "maketh an anchor"),
        (48, 51, "to the souls of men,"),
        (52, 52, "whereby"),
        (53, 57, "they should be sure"),
        (58, 60, "and steadfast,"),
        (61, 64, "and always abounding"),
        (65, 67, "in good works"),
        (68, 70, "without ceasing,"),
        (71, 73, "and led"),
        (74, 75, "to glorify"),
        (76, 77, "God."),
    ],
    5: [
        (0, 3, "And it came to pass that"),
        (4, 6, "prophesied Ether"),
        (7, 10, "great and marvelous things"),
        (11, 12, "unto the people,"),
        (13, 17, "which they believed not"),
        (18, 19, "therein,"),
        (20, 20, "because"),
        (21, 25, "they saw not"),
        (26, 27, "them."),
    ],
    6: [
        (0, 2, "And now,"),
        (3, 4, "I,"),
        (5, 6, "Moroni,"),
        (7, 11, "I would speak"),
        (12, 12, "somewhat"),
        (13, 14, "concerning"),
        (15, 17, "these things;"),
        (18, 22, "I would show forth"),
        (23, 25, "unto the world"),
        (26, 28, "that faith is"),
        (29, 31, "things which"),
        (32, 35, "are hoped for"),
        (36, 39, "and are not seen;"),
        (40, 43, "wherefore,"),
        (44, 47, "dispute not"),
        (48, 52, "because ye see not,"),
        (53, 57, "for ye receive not"),
        (58, 59, "a witness"),
        (60, 63, "until after the trial"),
        (64, 67, "of your faith."),
    ],
    7: [
        (0, 3, "For by faith"),
        (4, 7, "did show"),
        (8, 9, "Christ"),
        (10, 12, "himself"),
        (13, 16, "unto our fathers,"),
        (17, 20, "after"),
        (21, 24, "he had risen"),
        (25, 27, "from the dead;"),
        (28, 33, "and he showed not"),
        (34, 36, "himself"),
        (37, 40, "unto them"),
        (41, 42, "until after"),
        (43, 46, "they first believed"),
        (47, 49, "in him;"),
        (50, 53, "wherefore,"),
        (54, 56, "it behooved"),
        (57, 59, "there be"),
        (60, 62, "in some"),
        (63, 64, "faith"),
        (65, 67, "in him,"),
        (68, 73, "for he showed not"),
        (74, 76, "himself"),
        (77, 79, "unto the world."),
    ],
    8: [
        (0, 2, "But because of"),
        (3, 6, "the faith of men"),
        (7, 8, "therefore"),
        (9, 13, "he did show"),
        (14, 16, "himself"),
        (17, 19, "unto the world,"),
        (20, 21, "and glorified"),
        (22, 26, "the name of the Father,"),
        (27, 30, "and prepared a way"),
        (31, 35, "whereby others might"),
        (36, 37, "partake"),
        (38, 41, "of the heavenly gift,"),
        (42, 47, "that they might hope"),
        (48, 50, "for those things"),
        (51, 54, "which they saw not"),
        (55, 56, "them."),
    ],
    9: [
        (0, 3, "Wherefore,"),
        (4, 8, "ye may also"),
        (9, 10, "obtain"),
        (11, 13, "the hope,"),
        (14, 17, "and become they"),
        (18, 18, "who receive"),
        (19, 20, "the gift,"),
        (21, 25, "if ye will only"),
        (26, 27, "believe."),
    ],
    10: [
        (0, 0, "Behold,"),
        (1, 3, "by faith"),
        (4, 6, "were called"),
        (7, 9, "they of old,"),
        (10, 13, "after the holy order"),
        (14, 16, "of God."),
    ],
    11: [
        (0, 3, "Wherefore,"),
        (4, 6, "by faith"),
        (7, 10, "was given"),
        (11, 14, "the law of Moses."),
        (15, 17, "But prepared"),
        (18, 20, "God"),
        (21, 22, "through"),
        (23, 25, "the gift"),
        (26, 28, "of his Son"),
        (29, 30, "a way"),
        (31, 34, "more excellent;"),
        (35, 38, "and by faith"),
        (39, 41, "is it fulfilled."),
    ],
    12: [
        (0, 1, "For if"),
        (2, 5, "there be no faith"),
        (6, 8, "among"),
        (9, 12, "the children of men"),
        (13, 18, "God cannot"),
        (19, 20, "do"),
        (21, 22, "a miracle"),
        (23, 27, "among them;"),
        (28, 31, "wherefore,"),
        (32, 36, "he showed not"),
        (37, 39, "himself"),
        (40, 42, "until after"),
        (43, 45, "they first believed."),
    ],
    13: [
        (0, 0, "Behold,"),
        (1, 3, "it was by faith"),
        (4, 7, "of Alma and Amulek"),
        (8, 10, "that caused"),
        (11, 12, "to fall"),
        (13, 14, "the prison"),
        (15, 17, "to the earth."),
    ],
    14: [
        (0, 0, "Behold,"),
        (1, 3, "it was the faith"),
        (4, 7, "of Nephi and Lehi"),
        (8, 10, "that brought about"),
        (11, 12, "the change"),
        (13, 17, "upon the Lamanites,"),
        (18, 20, "that were baptized"),
        (21, 22, "them"),
        (23, 25, "with fire"),
        (26, 29, "and the Holy Ghost."),
    ],
    15: [
        (0, 0, "Behold,"),
        (1, 3, "it was the faith"),
        (4, 8, "of Ammon and his brethren"),
        (9, 11, "which wrought"),
        (12, 15, "so great a miracle"),
        (16, 20, "among the Lamanites."),
    ],
    16: [
        (0, 0, "Yea,"),
        (1, 3, "and even"),
        (4, 7, "unto all them"),
        (8, 10, "who"),
        (11, 12, "wrought miracles"),
        (13, 15, "they did do"),
        (16, 18, "by faith,"),
        (19, 23, "even unto them"),
        (24, 28, "who came before"),
        (29, 30, "Christ"),
        (31, 34, "and also them"),
        (35, 39, "who came after"),
        (40, 42, "him."),
    ],
    17: [
        (0, 3, "And by faith"),
        (4, 6, "did obtain"),
        (7, 10, "the three disciples"),
        (11, 12, "a promise"),
        (13, 17, "that they should not taste"),
        (18, 19, "they"),
        (20, 22, "of death;"),
        (23, 26, "and obtained not"),
        (27, 29, "they"),
        (30, 31, "the promise"),
        (32, 34, "until after"),
        (35, 37, "their first faith."),
    ],
    18: [
        (0, 3, "And neither ever"),
        (4, 8, "at any time whatsoever"),
        (9, 11, "did do"),
        (12, 14, "any one"),
        (15, 16, "miracles"),
        (17, 19, "until after"),
        (20, 21, "they believed;"),
        (22, 25, "wherefore"),
        (26, 30, "first they believed"),
        (31, 33, "in the Son"),
        (34, 36, "of God."),
    ],
    19: [
        (0, 3, "And there were"),
        (4, 5, "many"),
        (6, 7, "whose"),
        (8, 12, "was so very strong"),
        (13, 15, "their faith,"),
        (16, 18, "in the time"),
        (19, 22, "before came"),
        (23, 23, "Christ,"),
        (24, 28, "who were not able"),
        (29, 30, "to be withheld"),
        (31, 35, "from within the veil,"),
        (36, 40, "but they saw indeed"),
        (41, 43, "with their own eyes"),
        (44, 46, "the things which"),
        (47, 51, "they did see"),
        (52, 54, "with an eye"),
        (55, 57, "of faith,"),
        (58, 61, "and they did rejoice."),
    ],
    20: [
        (0, 1, "And behold,"),
        (2, 4, "we have seen"),
        (5, 7, "in this record,"),
        (8, 10, "that one"),
        (11, 13, "of them"),
        (14, 18, "was this brother"),
        (19, 20, "of Jared;"),
        (21, 25, "for was so great"),
        (26, 27, "his faith"),
        (28, 30, "in God,"),
        (31, 34, "that when stretched forth"),
        (35, 37, "God"),
        (38, 39, "his finger"),
        (40, 45, "he could not hide"),
        (46, 48, "from the sight"),
        (49, 53, "of the brother of Jared,"),
        (54, 57, "because of his word"),
        (58, 62, "which he had spoken"),
        (63, 65, "unto him,"),
        (66, 69, "which word"),
        (70, 72, "he obtained"),
        (73, 75, "by faith."),
    ],
    21: [
        (0, 3, "And after"),
        (4, 5, "had beheld"),
        (6, 10, "the brother of Jared"),
        (11, 13, "the finger"),
        (14, 16, "of the Lord,"),
        (17, 21, "because of the promise"),
        (22, 24, "which obtained"),
        (25, 28, "the brother of Jared"),
        (29, 31, "through faith,"),
        (32, 37, "the Lord could not"),
        (38, 41, "withhold anything"),
        (42, 44, "from his sight;"),
        (45, 48, "wherefore"),
        (49, 53, "he did show"),
        (54, 56, "unto him"),
        (57, 58, "all things,"),
        (59, 63, "for could no longer"),
        (64, 67, "be kept back he"),
        (68, 72, "without the veil."),
    ],
    22: [
        (0, 3, "And by faith"),
        (4, 6, "did receive"),
        (7, 9, "my fathers"),
        (10, 11, "the promise"),
        (12, 16, "should come forth"),
        (17, 18, "these things"),
        (19, 22, "unto their brethren"),
        (23, 26, "through the Gentiles;"),
        (27, 30, "wherefore"),
        (31, 33, "hath commanded"),
        (34, 34, "me"),
        (35, 37, "the Lord,"),
        (38, 38, "yea,"),
        (39, 41, "even Jesus Christ"),
        (42, 43, "himself."),
    ],
    23: [
        (0, 4, "And I said"),
        (5, 7, "unto him:"),
        (8, 10, "O Lord,"),
        (11, 14, "will mock"),
        (15, 15, "the Gentiles"),
        (16, 18, "at these things,"),
        (19, 23, "because of our weakness"),
        (24, 26, "in writing;"),
        (27, 27, "for"),
        (28, 30, "O Lord,"),
        (31, 33, "thou hast made mighty"),
        (34, 35, "us"),
        (36, 38, "in word"),
        (39, 42, "through faith,"),
        (43, 47, "but thou hast not made"),
        (48, 49, "us"),
        (50, 52, "strong in writing;"),
        (53, 56, "for thou hast made"),
        (57, 59, "all this people"),
        (60, 64, "that they might"),
        (65, 67, "speak abundantly,"),
        (68, 69, "because of"),
        (70, 72, "the Holy Ghost"),
        (73, 77, "which thou gavest"),
        (78, 81, "unto them;"),
    ],
    24: [
        (0, 3, "And thou hast made"),
        (4, 5, "us"),
        (6, 6, "so that"),
        (7, 11, "that we could"),
        (12, 13, "write little,"),
        (14, 17, "because of the clumsiness"),
        (18, 21, "of our hands."),
        (22, 22, "Behold,"),
        (23, 26, "thou hast not made"),
        (27, 28, "us"),
        (29, 31, "that we be strong"),
        (32, 34, "in writing"),
        (35, 37, "even as"),
        (38, 41, "the brother of Jared,"),
        (42, 45, "for thou madest"),
        (46, 47, "him"),
        (48, 50, "that mighty"),
        (51, 54, "the things he wrote"),
        (55, 57, "even as"),
        (58, 59, "thee,"),
        (60, 64, "until is overpowered"),
        (65, 66, "the man"),
        (67, 70, "who readeth them."),
    ],
    25: [
        (0, 3, "Thou hast also made"),
        (4, 6, "our words"),
        (7, 8, "to be mighty"),
        (9, 10, "and great,"),
        (11, 14, "even that"),
        (15, 19, "we cannot write"),
        (20, 21, "them;"),
        (22, 25, "wherefore"),
        (26, 28, "when we write"),
        (29, 31, "we do behold"),
        (32, 35, "our weakness,"),
        (36, 37, "and stumble"),
        (38, 41, "because of the placing"),
        (42, 45, "of our words;"),
        (46, 49, "and I fear"),
        (50, 52, "lest mock the Gentiles"),
        (53, 56, "at our words."),
    ],
    26: [
        (0, 3, "And after"),
        (4, 7, "I had spoken"),
        (8, 10, "these words,"),
        (11, 13, "spake"),
        (14, 15, "the Lord"),
        (16, 18, "unto me,"),
        (19, 21, "saying:"),
        (22, 23, "shall deride"),
        (24, 26, "they who are foolish,"),
        (27, 27, "but"),
        (28, 31, "shall mourn"),
        (32, 33, "they;"),
        (34, 36, "and is sufficient"),
        (37, 39, "my grace"),
        (40, 43, "for the meek,"),
        (44, 50, "they shall not exploit"),
        (51, 54, "unto themselves"),
        (55, 57, "your weakness;"),
    ],
    27: [
        (0, 1, "And if"),
        (2, 5, "men come"),
        (6, 8, "unto me"),
        (9, 14, "I will show forth"),
        (15, 18, "unto them"),
        (19, 21, "their weakness."),
        (22, 24, "I give"),
        (25, 26, "unto men"),
        (27, 28, "weakness"),
        (29, 32, "that they may be humble"),
        (33, 34, "them;"),
        (35, 37, "and is sufficient"),
        (38, 40, "my grace"),
        (41, 43, "for all men"),
        (44, 46, "who"),
        (47, 49, "humble"),
        (50, 52, "themselves"),
        (53, 55, "before me;"),
        (56, 57, "for if"),
        (58, 60, "they abase"),
        (61, 63, "themselves"),
        (64, 66, "before me,"),
        (67, 69, "and have faith"),
        (70, 72, "in me,"),
        (73, 76, "then will I make"),
        (77, 79, "weak things"),
        (80, 84, "become strong things"),
        (85, 88, "unto them."),
    ],
    28: [
        (0, 0, "Behold,"),
        (1, 6, "I will show forth"),
        (7, 8, "unto the Gentiles"),
        (9, 11, "their weakness,"),
        (12, 12, "and"),
        (13, 18, "I will show forth"),
        (19, 22, "unto them"),
        (23, 25, "that faith,"),
        (26, 26, "hope,"),
        (27, 30, "and charity"),
        (31, 33, "bringeth"),
        (34, 35, "them"),
        (36, 38, "unto me—"),
        (39, 41, "the fountain"),
        (42, 45, "of all righteousness."),
    ],
    29: [
        (0, 2, "And I,"),
        (3, 4, "Moroni,"),
        (5, 8, "after"),
        (9, 10, "I had heard"),
        (11, 13, "these words,"),
        (14, 15, "was comforted"),
        (16, 16, "I,"),
        (17, 20, "and I said:"),
        (21, 23, "O Lord,"),
        (24, 25, "let be done"),
        (26, 28, "thy righteous will,"),
        (29, 32, "for I know"),
        (33, 35, "thou dost work"),
        (36, 40, "unto the children of men"),
        (41, 43, "according to"),
        (44, 46, "their faith;"),
    ],
    30: [
        (0, 3, "For said"),
        (4, 7, "the brother of Jared"),
        (8, 10, "unto the mount"),
        (11, 12, "Zerin,"),
        (13, 14, "Remove—"),
        (15, 16, "and was"),
        (17, 19, "removed indeed."),
        (20, 21, "And if"),
        (22, 25, "had not"),
        (26, 28, "he"),
        (29, 30, "the faith"),
        (31, 33, "it had not"),
        (34, 35, "moved away;"),
        (36, 39, "wherefore"),
        (40, 43, "thou doest"),
        (44, 44, "works"),
        (45, 48, "after that"),
        (49, 51, "there be first"),
        (52, 53, "in men"),
        (54, 55, "the faith."),
    ],
    31: [
        (0, 3, "For even so"),
        (4, 6, "thou didst reveal"),
        (7, 9, "thyself"),
        (10, 12, "unto thy disciples;"),
        (13, 13, "for"),
        (14, 17, "after that"),
        (18, 20, "there was first"),
        (21, 24, "in them"),
        (25, 26, "faith,"),
        (27, 29, "and they spake"),
        (30, 32, "in thy name,"),
        (33, 36, "thou didst show"),
        (37, 38, "thyself"),
        (39, 42, "unto them"),
        (43, 46, "in great power."),
    ],
    32: [
        (0, 4, "And I also remember"),
        (5, 8, "that thou spakest"),
        (9, 13, "that thou hadst prepared"),
        (14, 17, "a place for man,"),
        (18, 18, "yea,"),
        (19, 22, "even within"),
        (23, 26, "the mansions of thy Father,"),
        (27, 33, "whereby man is able"),
        (34, 35, "to receive"),
        (36, 40, "a more excellent hope;"),
        (41, 44, "wherefore"),
        (45, 49, "man ought"),
        (50, 51, "to hope;"),
        (52, 55, "or is not able"),
        (56, 58, "for him to obtain"),
        (59, 60, "an inheritance"),
        (61, 63, "in the place"),
        (64, 66, "which thou preparedst."),
    ],
    33: [
        (0, 2, "And now also,"),
        (3, 5, "I remember"),
        (6, 9, "that thou spakest"),
        (10, 12, "thou hast loved"),
        (13, 15, "the world,"),
        (16, 18, "even unto"),
        (19, 22, "the laying down"),
        (23, 25, "of thy life"),
        (26, 28, "for the world,"),
        (29, 32, "that thou mightest"),
        (33, 35, "take it again"),
        (36, 38, "to prepare"),
        (39, 40, "a place"),
        (41, 45, "for the children of men."),
    ],
    34: [
        (0, 2, "And now"),
        (3, 5, "I know"),
        (6, 8, "that this love"),
        (9, 12, "which is in thee"),
        (13, 17, "for the children of men"),
        (18, 22, "is this charity;"),
        (23, 26, "wherefore,"),
        (27, 28, "except"),
        (29, 31, "there be"),
        (32, 33, "in men"),
        (34, 36, "the pure love"),
        (37, 42, "they cannot inherit"),
        (43, 45, "that place"),
        (46, 48, "which thou preparedst"),
        (49, 50, "in the mansions"),
        (51, 53, "of thy Father."),
    ],
    35: [
        (0, 3, "Wherefore,"),
        (4, 7, "I do know"),
        (8, 10, "by this thing"),
        (11, 15, "which thou hast spoken,"),
        (16, 18, "that if"),
        (19, 22, "there be not"),
        (23, 24, "in the Gentiles"),
        (25, 27, "the pure love,"),
        (28, 29, "because of"),
        (30, 32, "our weaknesses,"),
        (33, 37, "thou shalt prove"),
        (38, 39, "them,"),
        (40, 41, "and take away"),
        (42, 44, "their talent,"),
        (45, 45, "yea,"),
        (46, 49, "even the things which"),
        (50, 52, "they have gained,"),
        (53, 54, "and give"),
        (55, 58, "unto them"),
        (59, 60, "those who"),
        (61, 65, "shall receive"),
        (66, 66, "more abundantly."),
    ],
    36: [
        (0, 3, "And it came to pass that"),
        (4, 6, "I did pray"),
        (7, 9, "unto the Lord"),
        (10, 12, "that he grant"),
        (13, 14, "unto the Gentiles"),
        (15, 17, "grace,"),
        (18, 21, "that they might have"),
        (22, 24, "the pure love."),
    ],
    37: [
        (0, 3, "And it came to pass that"),
        (4, 5, "said"),
        (6, 7, "the Lord"),
        (8, 10, "unto me:"),
        (11, 11, "If"),
        (12, 15, "there be not"),
        (16, 18, "in them"),
        (19, 21, "the pure love"),
        (22, 24, "it matters not"),
        (25, 26, "that matter"),
        (27, 29, "unto thee,"),
        (30, 32, "thou hast been faithful;"),
        (33, 36, "wherefore,"),
        (37, 40, "shall be made clean"),
        (41, 42, "thy garments."),
        (43, 47, "And because thou hast seen"),
        (48, 50, "thy weakness"),
        (51, 54, "thou shalt be made strong"),
        (55, 55, "thou,"),
        (56, 58, "even until"),
        (59, 60, "the sitting"),
        (61, 63, "in the place"),
        (64, 66, "which I have prepared"),
        (67, 71, "in the mansions of my Father."),
    ],
    38: [
        (0, 2, "And now"),
        (3, 4, "I,"),
        (5, 6, "Moroni,"),
        (7, 10, "I bid farewell"),
        (11, 12, "unto the Gentiles,"),
        (13, 13, "yea,"),
        (14, 18, "and also to my brethren"),
        (19, 20, "whom"),
        (21, 25, "I have loved,"),
        (26, 28, "until"),
        (29, 30, "we shall meet"),
        (31, 35, "before the judgment-seat"),
        (36, 37, "of Christ,"),
        (38, 38, "where"),
        (39, 43, "shall know"),
        (44, 46, "all men"),
        (47, 49, "are not spotted"),
        (50, 51, "my garments"),
        (52, 55, "with your blood."),
    ],
    39: [
        (0, 5, "And that ye may know"),
        (6, 6, "this,"),
        (7, 9, "I have seen"),
        (10, 11, "Jesus,"),
        (12, 16, "and he spake"),
        (17, 19, "unto me"),
        (20, 21, "face to face,"),
        (22, 26, "and he did tell"),
        (27, 29, "unto me"),
        (30, 32, "in plain words"),
        (33, 35, "as is meet,"),
        (36, 38, "even as"),
        (39, 41, "telleth"),
        (42, 44, "one man"),
        (45, 48, "to another man"),
        (49, 52, "in thine own language,"),
        (53, 54, "concerning"),
        (55, 57, "these things;"),
    ],
    40: [
        (0, 2, "And but"),
        (3, 5, "a few things"),
        (6, 8, "have I written,"),
        (9, 12, "because of my weakness"),
        (13, 15, "in writing."),
    ],
    41: [
        (0, 2, "And now,"),
        (3, 6, "I do exhort"),
        (7, 9, "you"),
        (10, 11, "to seek"),
        (12, 13, "this Jesus"),
        (14, 15, "of whom"),
        (16, 19, "have written"),
        (20, 22, "the prophets"),
        (23, 24, "and apostles,"),
        (25, 28, "that there may be"),
        (29, 30, "and abide"),
        (31, 33, "in you"),
        (34, 35, "for ever"),
        (36, 38, "the grace"),
        (39, 43, "of God the Father,"),
        (44, 46, "and the Lord"),
        (47, 49, "Jesus Christ,"),
        (50, 53, "and the Holy Ghost,"),
        (54, 57, "which beareth witness"),
        (58, 61, "of them both."),
        (62, 62, "Amen."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
