"""Hand-curated TAM-phrase gloss overrides for 1 Nifae 11 — Nephi's vision of the Tree of Life."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "1nephi"
CHAPTER_NUM = 11
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "For it came to pass"),
        (4, 6, "after"),
        (7, 9, "I desired to know"),
        (10, 11, "the things"),
        (12, 15, "which was seen"),
        (16, 17, "my father,"),
        (18, 20, "and believing"),
        (21, 22, "could"),
        (23, 25, "the Lord"),
        (26, 26, "that"),
        (27, 28, "make known"),
        (29, 31, "unto me,"),
        (32, 34, "as I sat"),
        (35, 37, "pondering"),
        (38, 40, "in mine heart,"),
        (41, 44, "I was caught away"),
        (45, 50, "in the Spirit of the Lord,"),
        (51, 51, "yea,"),
        (52, 56, "into an exceedingly high mountain,"),
        (57, 60, "I had not seen"),
        (61, 63, "before,"),
        (64, 70, "and upon which I never had before"),
        (71, 74, "set my foot."),
    ],
    2: [
        (0, 3, "And spake"),
        (4, 5, "the Spirit"),
        (6, 8, "unto me:"),
        (9, 9, "Behold,"),
        (10, 14, "what"),
        (15, 19, "is desirest thou?"),
    ],
    3: [
        (0, 4, "And I said:"),
        (5, 8, "I desire to behold"),
        (9, 14, "the things which saw"),
        (15, 16, "my father."),
    ],
    4: [
        (0, 3, "And spake"),
        (4, 5, "the Spirit"),
        (6, 8, "unto me:"),
        (9, 12, "Believest thou?"),
        (13, 16, "saw thy father"),
        (17, 19, "the tree"),
        (20, 26, "of which he spake?"),
    ],
    5: [
        (0, 4, "And I said:"),
        (5, 5, "Yea,"),
        (6, 8, "thou knowest"),
        (9, 11, "I believe"),
        (12, 14, "all the words"),
        (15, 17, "of my father."),
    ],
    6: [
        (0, 4, "And when"),
        (5, 7, "I had spoken"),
        (8, 10, "these words,"),
        (11, 14, "cried the Spirit"),
        (15, 18, "with a loud voice,"),
        (19, 20, "saying:"),
        (21, 25, "Hosanna to the Lord,"),
        (26, 29, "the most high God;"),
        (30, 32, "for he"),
        (33, 35, "is God"),
        (36, 37, "over"),
        (38, 41, "all the earth,"),
        (42, 42, "yea,"),
        (43, 44, "above"),
        (45, 48, "all things even."),
        (49, 53, "And blessed art thou, Nephi,"),
        (54, 57, "because thou believest"),
        (58, 65, "in the Son of the most high God;"),
        (66, 69, "wherefore,"),
        (70, 75, "thou shalt behold"),
        (76, 82, "the things which thou hast desired."),
    ],
    7: [
        (0, 1, "And behold"),
        (2, 6, "shall be given"),
        (7, 9, "unto thee"),
        (10, 11, "this thing"),
        (12, 14, "for a sign,"),
        (15, 19, "that after"),
        (20, 21, "thou hast beheld"),
        (22, 24, "the tree"),
        (25, 28, "that bore"),
        (29, 30, "the fruit"),
        (31, 34, "which tasted"),
        (35, 36, "thy father,"),
        (37, 41, "thou shalt also behold"),
        (42, 45, "a man"),
        (46, 49, "descending from"),
        (50, 51, "heaven,"),
        (52, 54, "and him"),
        (55, 60, "shall ye behold;"),
        (61, 64, "and after"),
        (65, 70, "ye have beheld him"),
        (71, 75, "ye shall bear record"),
        (76, 77, "that he"),
        (78, 83, "is the Son of God."),
    ],
    8: [
        (0, 3, "And it came to pass"),
        (4, 7, "spake the Spirit"),
        (8, 10, "unto me:"),
        (11, 12, "Look!"),
        (13, 19, "And I looked and beheld"),
        (20, 21, "a tree;"),
        (22, 27, "and it was like the tree"),
        (28, 31, "which had seen"),
        (32, 33, "my father;"),
        (34, 37, "and the beauty thereof"),
        (38, 41, "was far exceeding,"),
        (42, 42, "yea,"),
        (43, 47, "exceeding all beauty;"),
        (48, 51, "and the whiteness thereof"),
        (52, 54, "did exceed"),
        (55, 57, "the whiteness"),
        (58, 60, "of the snow"),
        (61, 64, "driven in the wind."),
    ],
    9: [
        (0, 3, "And it came to pass"),
        (4, 6, "after"),
        (7, 8, "I beheld"),
        (9, 11, "the tree,"),
        (12, 15, "I said"),
        (16, 18, "unto the Spirit:"),
        (19, 21, "I behold"),
        (22, 28, "thou hast shown unto me"),
        (29, 30, "the tree"),
        (31, 32, "which is precious"),
        (33, 35, "above all."),
    ],
    10: [
        (0, 5, "And said he"),
        (6, 8, "unto me:"),
        (9, 13, "What"),
        (14, 18, "is desirest thou?"),
    ],
    11: [
        (0, 4, "And I said"),
        (5, 7, "unto him:"),
        (8, 10, "to know"),
        (11, 12, "the interpretation—for"),
        (13, 19, "I had spoken unto him"),
        (20, 25, "as a man speaketh;"),
        (26, 30, "for I beheld"),
        (31, 38, "he was in the form of a man;"),
        (39, 43, "yet nevertheless,"),
        (44, 48, "I knew that he"),
        (49, 54, "was the Spirit of the Lord;"),
        (55, 60, "and he spake"),
        (61, 63, "unto me"),
        (64, 66, "as"),
        (67, 70, "speaketh a man"),
        (71, 73, "to another."),
    ],
    12: [
        (0, 3, "And it came to pass"),
        (4, 7, "spake he"),
        (8, 10, "unto me:"),
        (11, 12, "Look!"),
        (13, 17, "And I looked"),
        (18, 19, "as if"),
        (20, 23, "I would behold"),
        (24, 26, "him,"),
        (27, 34, "but I saw him not;"),
        (35, 36, "for"),
        (37, 41, "had departed he"),
        (42, 44, "from my presence."),
    ],
    13: [
        (0, 3, "And it came to pass"),
        (4, 8, "I beheld"),
        (9, 13, "the great city of Jerusalem,"),
        (14, 17, "and also other cities."),
        (18, 22, "And I beheld"),
        (23, 24, "the city"),
        (25, 26, "of Nazareth;"),
        (27, 29, "and within"),
        (30, 32, "the city"),
        (33, 34, "of Nazareth"),
        (35, 40, "I beheld a virgin,"),
        (41, 44, "and she was exceeding"),
        (45, 50, "fair and white."),
    ],
    14: [
        (0, 3, "And it came to pass"),
        (4, 6, "I beheld"),
        (7, 10, "the heavens open;"),
        (11, 16, "and came down an angel"),
        (17, 22, "and stood before me;"),
        (23, 28, "and he spake"),
        (29, 31, "unto me:"),
        (32, 32, "Nephi,"),
        (33, 37, "what"),
        (38, 41, "beholdest thou?"),
    ],
    15: [
        (0, 4, "And I said"),
        (5, 7, "unto him:"),
        (8, 10, "A virgin,"),
        (11, 13, "most beautiful"),
        (14, 16, "and fair"),
        (17, 20, "above all other virgins."),
    ],
    16: [
        (0, 5, "And said he"),
        (6, 8, "unto me:"),
        (9, 13, "Knowest thou"),
        (14, 15, "the condescension"),
        (16, 18, "of God?"),
    ],
    17: [
        (0, 4, "And I said"),
        (5, 7, "unto him:"),
        (8, 10, "I know"),
        (11, 14, "he loveth"),
        (15, 17, "his children;"),
        (18, 21, "nevertheless,"),
        (22, 25, "I do not know"),
        (26, 27, "the meaning"),
        (28, 30, "of all things."),
    ],
    18: [
        (0, 5, "And said he"),
        (6, 8, "unto me:"),
        (9, 9, "Behold,"),
        (10, 12, "the virgin"),
        (13, 18, "whom thou seest"),
        (19, 22, "is the mother"),
        (23, 28, "of the Son of God,"),
        (29, 34, "after the manner of the flesh."),
    ],
    19: [
        (0, 3, "And it came to pass"),
        (4, 6, "I beheld"),
        (7, 12, "she was carried away"),
        (13, 15, "by the Spirit;"),
        (16, 19, "and after"),
        (20, 24, "she was carried away"),
        (25, 27, "by the Spirit"),
        (28, 33, "for the space of a time,"),
        (34, 38, "spake the angel"),
        (39, 41, "unto me,"),
        (42, 43, "saying:"),
        (44, 45, "Look!"),
    ],
    20: [
        (0, 7, "And I looked and beheld again"),
        (8, 9, "the virgin,"),
        (10, 13, "bearing"),
        (14, 15, "a child"),
        (16, 18, "in her arms."),
    ],
    21: [
        (0, 5, "And said the angel"),
        (6, 8, "unto me:"),
        (9, 9, "Behold"),
        (10, 16, "the Lamb of God,"),
        (17, 17, "yea,"),
        (18, 25, "even the Son of the Eternal Father!"),
        (26, 29, "knowest thou"),
        (30, 31, "the meaning"),
        (32, 34, "of the tree"),
        (35, 38, "which saw"),
        (39, 40, "thy father?"),
    ],
    22: [
        (0, 4, "And I answered"),
        (5, 7, "him,"),
        (8, 10, "saying:"),
        (11, 11, "Yea,"),
        (12, 18, "it is the love of God,"),
        (19, 25, "which sheddeth itself abroad"),
        (26, 32, "in the hearts of the children of men;"),
        (33, 34, "therefore,"),
        (35, 38, "wherefore"),
        (39, 41, "is the most"),
        (42, 43, "desirable"),
        (44, 46, "above all things."),
    ],
    23: [
        (0, 5, "And said he"),
        (6, 8, "unto me,"),
        (9, 10, "saying:"),
        (11, 11, "Yea,"),
        (12, 16, "and the most joyous"),
        (17, 19, "to the soul."),
    ],
    24: [
        (0, 4, "And after"),
        (5, 8, "had spoken he"),
        (9, 11, "these words,"),
        (12, 16, "said he"),
        (17, 19, "unto me:"),
        (20, 21, "Look!"),
        (22, 25, "And I looked,"),
        (26, 30, "and I beheld"),
        (31, 35, "the Son of God"),
        (36, 37, "going"),
        (38, 44, "among the children of men;"),
        (45, 48, "and I beheld"),
        (49, 51, "many"),
        (52, 57, "fell down at his feet"),
        (58, 60, "and worshipped"),
        (61, 63, "him."),
    ],
    25: [
        (0, 3, "And it came to pass"),
        (4, 5, "I beheld"),
        (6, 9, "the rod of iron,"),
        (10, 14, "which had seen"),
        (15, 16, "my father,"),
        (17, 23, "was the word of God,"),
        (24, 28, "which led"),
        (29, 33, "to the fountain of living waters,"),
        (34, 41, "or to the tree of life;"),
        (42, 47, "which waters are a representation"),
        (48, 53, "of the love of God;"),
        (54, 57, "and I knew"),
        (58, 58, "also"),
        (59, 64, "the tree of life"),
        (65, 67, "is a representation"),
        (68, 73, "of the love of God."),
    ],
    26: [
        (0, 6, "And again spake the angel"),
        (7, 9, "unto me:"),
        (10, 13, "Look and behold"),
        (14, 16, "the condescension"),
        (17, 19, "of God!"),
    ],
    27: [
        (0, 6, "And I looked and beheld"),
        (7, 11, "the Redeemer of the world,"),
        (12, 17, "of whom had spoken"),
        (18, 19, "my father;"),
        (20, 24, "and I beheld also"),
        (25, 27, "the prophet"),
        (28, 35, "who should prepare the way"),
        (36, 38, "before him."),
        (39, 42, "And went"),
        (43, 48, "the Lamb of God"),
        (49, 53, "and was baptized by him;"),
        (54, 58, "and after"),
        (59, 61, "he was baptized,"),
        (62, 65, "I beheld"),
        (66, 69, "were opened the heavens,"),
        (70, 76, "and came down the Holy Ghost"),
        (77, 79, "from heaven"),
        (80, 86, "and abide upon him"),
        (87, 88, "as if"),
        (89, 90, "a"),
        (91, 91, "dove."),
    ],
    28: [
        (0, 4, "And I beheld"),
        (5, 9, "he went"),
        (10, 14, "and ministered unto the people,"),
        (15, 21, "in power and great glory;"),
        (22, 27, "and were gathered together multitudes"),
        (28, 32, "to hear him;"),
        (33, 37, "and I beheld"),
        (38, 43, "they cast him out"),
        (44, 45, "out"),
        (46, 50, "from among them."),
    ],
    29: [
        (0, 5, "And I beheld also"),
        (6, 8, "twelve others"),
        (9, 11, "following"),
        (12, 14, "him."),
        (15, 18, "And it came to pass"),
        (19, 23, "they were carried away"),
        (24, 26, "in the Spirit"),
        (27, 31, "from before my face,"),
        (32, 37, "and I saw not"),
        (38, 41, "them."),
    ],
    30: [
        (0, 3, "And it came to pass"),
        (4, 8, "again spake the angel"),
        (9, 11, "unto me,"),
        (12, 13, "saying:"),
        (14, 15, "Look!"),
        (16, 19, "And I looked,"),
        (20, 23, "and I beheld"),
        (24, 28, "were opened again the heavens,"),
        (29, 33, "and I beheld"),
        (34, 37, "came down angels"),
        (38, 44, "upon the children of men;"),
        (45, 49, "and they did minister"),
        (50, 53, "unto them."),
    ],
    31: [
        (0, 6, "And again spake he"),
        (7, 9, "unto me,"),
        (10, 11, "saying:"),
        (12, 13, "Look!"),
        (14, 17, "And I looked,"),
        (18, 22, "and I beheld"),
        (23, 28, "the Lamb of God"),
        (29, 31, "went"),
        (32, 38, "among the children of men."),
        (39, 43, "And I beheld"),
        (44, 47, "multitudes of people"),
        (48, 51, "who were sick,"),
        (52, 55, "and were afflicted"),
        (56, 61, "with all manner of diseases,"),
        (62, 67, "and with devils and unclean spirits;"),
        (68, 76, "and showed the angel"),
        (77, 79, "all these things"),
        (80, 82, "unto me."),
        (83, 87, "And they were healed"),
        (88, 97, "by the power of the Lamb of God;"),
        (98, 100, "and were cast out"),
        (101, 106, "devils and unclean spirits."),
    ],
    32: [
        (0, 3, "And it came to pass"),
        (4, 8, "again spake the angel"),
        (9, 11, "unto me,"),
        (12, 13, "saying:"),
        (14, 15, "Look!"),
        (16, 23, "And I looked and beheld"),
        (24, 29, "the Lamb of God,"),
        (30, 33, "was taken he"),
        (34, 36, "by the people;"),
        (37, 37, "yea,"),
        (38, 46, "the Son of the everlasting God"),
        (47, 51, "was judged of the world;"),
        (52, 57, "and I saw and bear record."),
    ],
    33: [
        (0, 2, "And I,"),
        (3, 4, "Nephi,"),
        (5, 7, "saw"),
        (8, 12, "was lifted up he"),
        (13, 17, "upon the cross"),
        (18, 19, "and slain"),
        (20, 21, "for the sins"),
        (22, 24, "of the world."),
    ],
    34: [
        (0, 4, "And after"),
        (5, 7, "he was slain"),
        (8, 10, "I beheld"),
        (11, 16, "the multitudes of the world,"),
        (17, 20, "were gathered together"),
        (21, 22, "to fight"),
        (23, 28, "against the apostles of the Lamb;"),
        (29, 31, "for thus were"),
        (32, 36, "called the twelve"),
        (37, 42, "by the angel of the Lord."),
    ],
    35: [
        (0, 3, "And were gathered together"),
        (4, 10, "the multitudes of the world;"),
        (11, 14, "and I beheld"),
        (15, 18, "they were"),
        (19, 27, "in a large and spacious building,"),
        (28, 32, "like the building"),
        (33, 36, "which saw"),
        (37, 38, "my father."),
        (39, 48, "And again spake the angel of the Lord"),
        (49, 51, "unto me,"),
        (52, 53, "saying:"),
        (54, 57, "Behold the world"),
        (58, 60, "and its wisdom;"),
        (61, 61, "yea,"),
        (62, 62, "behold"),
        (63, 69, "is gathered together the house of Israel"),
        (70, 71, "to fight"),
        (72, 75, "against the twelve apostles"),
        (76, 79, "of the Lamb."),
    ],
    36: [
        (0, 3, "And it came to pass"),
        (4, 7, "I beheld and bear record,"),
        (8, 14, "the great and spacious building"),
        (15, 21, "was the pride of the world;"),
        (22, 24, "and it fell,"),
        (25, 32, "and the fall thereof was exceedingly great."),
        (33, 42, "And again spake the angel of the Lord"),
        (43, 45, "unto me,"),
        (46, 47, "saying:"),
        (48, 54, "thus shall be the destruction"),
        (55, 57, "of all nations,"),
        (58, 58, "kindreds,"),
        (59, 59, "tongues,"),
        (60, 61, "and people,"),
        (62, 65, "that shall fight"),
        (66, 69, "against the twelve apostles"),
        (70, 73, "of the Lamb."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
