"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 2 — Amlici seeks
to be king; the Amlicites; war at the hill Amnihu and the river Sidon.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona`/`e ao ina` bound (rules 13/15).

    python3 build_overrides_alma2.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 2

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And it came to pass"),
        (3, 5, "in the commencement"),
        (6, 9, "of the fifth"),
        (10, 11, "year"),
        (12, 15, "of their reign"),
        (16, 18, "there began"),
        (19, 21, "to be"),
        (22, 24, "a contention"),
        (25, 27, "among"),
        (28, 29, "the people;"),
        (30, 30, "for"),
        (31, 33, "there was"),
        (34, 36, "a certain man,"),
        (37, 39, "being called"),
        (40, 40, "Amlici,"),
        (41, 42, "he being"),
        (43, 47, "a very cunning man,"),
        (48, 48, "yea,"),
        (49, 53, "a very wise man"),
        (54, 57, "as to"),
        (58, 60, "the wisdom of"),
        (61, 62, "the world,"),
        (63, 63, "and"),
        (64, 65, "he being"),
        (66, 67, "one"),
        (68, 71, "of the order of"),
        (72, 73, "the man"),
        (74, 76, "that slew"),
        (77, 77, "Gideon"),
        (78, 80, "by the sword,"),
        (81, 83, "who was executed"),
        (84, 87, "according to"),
        (88, 89, "the law—"),
    ],
    2: [
        (0, 1, "Now"),
        (2, 5, "this Amlici"),
        (6, 9, "had drawn away,"),
        (10, 12, "by his cunning,"),
        (13, 15, "much"),
        (16, 16, "people,"),
        (17, 19, "to follow"),
        (20, 22, "after him;"),
        (23, 26, "even so much"),
        (27, 28, "of them"),
        (29, 31, "began to"),
        (32, 34, "they be very powerful;"),
        (35, 35, "and"),
        (36, 38, "began to"),
        (39, 40, "they endeavor"),
        (41, 42, "to establish"),
        (43, 43, "Amlici"),
        (44, 47, "to be a king"),
        (48, 50, "over the people."),
    ],
    3: [
        (0, 1, "Now"),
        (2, 3, "were alarmed"),
        (4, 4, "the people"),
        (5, 7, "of the church"),
        (8, 10, "at this,"),
        (11, 13, "and also"),
        (14, 16, "to all those"),
        (17, 18, "who"),
        (19, 21, "had not been drawn away"),
        (22, 24, "after the persuasions of"),
        (25, 25, "Amlici;"),
        (26, 26, "for"),
        (27, 29, "they knew,"),
        (30, 32, "according to"),
        (33, 35, "their law,"),
        (36, 38, "that such things"),
        (39, 41, "must"),
        (42, 42, "be established"),
        (43, 45, "by the voice"),
        (46, 48, "of the people."),
    ],
    4: [
        (0, 1, "Therefore,"),
        (2, 2, "if"),
        (3, 5, "it were possible that"),
        (6, 6, "should gain"),
        (7, 8, "Amlici"),
        (9, 11, "the voice of"),
        (12, 13, "the people,"),
        (14, 15, "he,"),
        (16, 19, "being a wicked man,"),
        (20, 25, "would deprive"),
        (26, 30, "them of"),
        (31, 33, "their rights"),
        (34, 35, "and privileges"),
        (36, 38, "of the church;"),
        (39, 40, "for"),
        (41, 42, "his intent"),
        (43, 44, "to destroy"),
        (45, 46, "the church"),
        (47, 49, "of God."),
    ],
    5: [
        (0, 3, "And it came to pass that"),
        (4, 5, "assembled together"),
        (6, 7, "the people"),
        (8, 10, "themselves"),
        (11, 14, "throughout all the land,"),
        (15, 17, "in separate bodies,"),
        (18, 21, "having much dispute"),
        (22, 24, "and wonderful contentions"),
        (25, 30, "one with another,"),
        (31, 34, "every man"),
        (35, 37, "according to"),
        (38, 39, "his mind,"),
        (40, 40, "whether"),
        (41, 42, "for Amlici"),
        (43, 44, "or against"),
        (45, 47, "him."),
    ],
    6: [
        (0, 0, "And"),
        (1, 3, "thus"),
        (4, 6, "they gathered together"),
        (7, 9, "themselves"),
        (10, 12, "to cast in"),
        (13, 15, "their voices"),
        (16, 18, "concerning"),
        (19, 20, "the matter;"),
        (21, 21, "and"),
        (22, 24, "were laid"),
        (25, 27, "their voices"),
        (28, 30, "before"),
        (31, 31, "the judges."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 5, "came against"),
        (6, 7, "the voice of"),
        (8, 10, "the people"),
        (11, 12, "Amlici,"),
        (13, 18, "that he was not made"),
        (19, 20, "king"),
        (21, 23, "over the people."),
    ],
    8: [
        (0, 1, "Now"),
        (2, 3, "was"),
        (4, 5, "this"),
        (6, 7, "the cause"),
        (8, 11, "of much joy"),
        (12, 14, "in the hearts of"),
        (15, 16, "those"),
        (17, 18, "who"),
        (19, 20, "were against"),
        (21, 23, "him;"),
        (24, 24, "but"),
        (25, 26, "did stir up"),
        (27, 28, "Amlici"),
        (29, 30, "those"),
        (31, 34, "who were in favor"),
        (35, 37, "of him,"),
        (38, 39, "to anger"),
        (40, 43, "against"),
        (44, 45, "who"),
        (46, 48, "were not in favor"),
        (49, 51, "of him."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they gathered together"),
        (7, 9, "themselves,"),
        (10, 11, "and did consecrate"),
        (12, 12, "Amlici"),
        (13, 15, "to be"),
        (16, 18, "their king."),
    ],
    10: [
        (0, 1, "Now"),
        (2, 4, "when was made"),
        (5, 5, "Amlici"),
        (6, 7, "king"),
        (8, 12, "over them,"),
        (13, 15, "he commanded"),
        (16, 17, "them"),
        (18, 21, "that they should take up"),
        (22, 24, "arms"),
        (25, 27, "against"),
        (28, 30, "their brethren;"),
        (31, 31, "and"),
        (32, 35, "he did"),
        (36, 37, "this,"),
        (38, 42, "that he might"),
        (43, 45, "subject"),
        (46, 49, "them to him."),
    ],
    11: [
        (0, 1, "Now"),
        (2, 4, "were distinguished"),
        (5, 5, "the people"),
        (6, 7, "of Amlici"),
        (8, 11, "by the name of"),
        (12, 12, "Amlici,"),
        (13, 14, "being called"),
        (15, 17, "Amlicites;"),
        (18, 18, "and"),
        (19, 22, "the remainder"),
        (23, 24, "were called"),
        (25, 27, "Nephites,"),
        (28, 29, "or"),
        (30, 30, "the people"),
        (31, 33, "of God."),
    ],
    12: [
        (0, 1, "Therefore,"),
        (2, 3, "were aware"),
        (4, 5, "the people"),
        (6, 8, "of the Nephites"),
        (9, 11, "of the intent"),
        (12, 13, "of the Amlicites,"),
        (14, 14, "and"),
        (15, 16, "therefore"),
        (17, 20, "they did prepare"),
        (21, 23, "to meet"),
        (24, 25, "them;"),
        (26, 26, "yea,"),
        (27, 30, "they did arm"),
        (31, 33, "themselves"),
        (34, 35, "with swords,"),
        (36, 37, "and with cimeters,"),
        (38, 39, "and with bows,"),
        (40, 41, "and with arrows,"),
        (42, 43, "and with stones,"),
        (44, 45, "and with slings,"),
        (46, 49, "and with all manner of"),
        (50, 51, "weapons,"),
        (52, 53, "of war."),
    ],
    13: [
        (0, 0, "And"),
        (1, 3, "thus"),
        (4, 5, "they were prepared"),
        (6, 8, "to meet"),
        (9, 10, "the Amlicites"),
        (11, 13, "at the time"),
        (14, 18, "of their coming."),
        (19, 19, "And"),
        (20, 21, "there were appointed"),
        (22, 23, "captains,"),
        (24, 26, "and higher captains,"),
        (27, 29, "and chief captains,"),
        (30, 33, "according to"),
        (34, 37, "their numbers."),
    ],
    14: [
        (0, 3, "And it came to pass that"),
        (4, 4, "did arm"),
        (5, 6, "Amlici"),
        (7, 8, "his men"),
        (9, 12, "with all manner of"),
        (13, 14, "weapons"),
        (15, 16, "of war;"),
        (17, 17, "and"),
        (18, 21, "he also appointed"),
        (22, 23, "rulers"),
        (24, 26, "and leaders"),
        (27, 29, "over"),
        (30, 31, "his people,"),
        (32, 33, "to lead"),
        (34, 35, "them"),
        (36, 38, "to war"),
        (39, 41, "against"),
        (42, 44, "their brethren."),
    ],
    15: [
        (0, 3, "And it came to pass that"),
        (4, 5, "came up"),
        (6, 7, "the Amlicites"),
        (8, 11, "upon the hill"),
        (12, 12, "Amnihu,"),
        (13, 18, "which was east"),
        (19, 22, "of the river"),
        (23, 23, "Sidon,"),
        (24, 26, "which ran"),
        (27, 30, "by"),
        (31, 32, "the land"),
        (33, 34, "of Zarahemla,"),
        (35, 35, "and"),
        (36, 37, "there"),
        (38, 41, "they began to"),
        (42, 43, "make war"),
        (44, 46, "with the Nephites."),
    ],
    16: [
        (0, 1, "Now"),
        (2, 3, "Alma,"),
        (4, 6, "being"),
        (7, 10, "the chief judge"),
        (11, 13, "and the governor of"),
        (14, 16, "the people"),
        (17, 18, "of Nephi,"),
        (19, 20, "therefore"),
        (21, 26, "he went up"),
        (27, 29, "with"),
        (30, 30, "his people,"),
        (31, 31, "yea,"),
        (32, 33, "with"),
        (34, 35, "his captains,"),
        (36, 38, "and chief captains,"),
        (39, 39, "yea,"),
        (40, 42, "at the head of"),
        (43, 45, "his armies,"),
        (46, 48, "against"),
        (49, 50, "the Amlicites"),
        (51, 53, "to battle."),
    ],
    17: [
        (0, 0, "And"),
        (1, 3, "began to"),
        (4, 5, "they slay"),
        (6, 8, "the Amlicites"),
        (9, 11, "upon"),
        (12, 13, "the hill"),
        (14, 19, "east of"),
        (20, 20, "Sidon."),
        (21, 21, "And"),
        (22, 23, "did contend"),
        (24, 25, "the Amlicites"),
        (26, 28, "with the Nephites"),
        (29, 32, "with great strength,"),
        (33, 35, "insomuch that"),
        (36, 36, "did fall"),
        (37, 39, "many"),
        (40, 41, "of the Nephites"),
        (42, 44, "before"),
        (45, 46, "the Amlicites."),
    ],
    18: [
        (0, 3, "Nevertheless"),
        (4, 5, "did strengthen"),
        (6, 8, "the Lord"),
        (9, 11, "the hand of"),
        (12, 13, "the Nephites,"),
        (14, 16, "that"),
        (17, 18, "they slew"),
        (19, 20, "the Amlicites"),
        (21, 24, "with great slaughter,"),
        (25, 27, "that"),
        (28, 29, "began to"),
        (30, 32, "they flee"),
        (33, 37, "before them."),
    ],
    19: [
        (0, 3, "And it came to pass that"),
        (4, 4, "did pursue"),
        (5, 7, "the Nephites"),
        (8, 9, "the Amlicites"),
        (10, 14, "all that day,"),
        (15, 16, "and did slay"),
        (17, 18, "them"),
        (19, 22, "with much slaughter,"),
        (23, 25, "insomuch that"),
        (26, 27, "there were slain"),
        (28, 29, "of the Amlicites"),
        (30, 33, "twelve thousand"),
        (34, 35, "five hundred"),
        (36, 40, "thirty and two;"),
        (41, 41, "and"),
        (42, 44, "of the Nephites"),
        (45, 46, "there were slain"),
        (47, 49, "six thousand"),
        (50, 51, "five hundred"),
        (52, 56, "sixty and two"),
        (57, 57, "souls."),
    ],
    20: [
        (0, 3, "And it came to pass that"),
        (4, 6, "could no longer"),
        (7, 8, "Alma"),
        (9, 11, "pursue"),
        (12, 14, "the Amlicites,"),
        (15, 18, "he caused"),
        (19, 21, "that should pitch"),
        (22, 24, "his people"),
        (25, 27, "their tents"),
        (28, 31, "in the valley of"),
        (32, 32, "Gideon,"),
        (33, 35, "the valley"),
        (36, 37, "being called"),
        (38, 41, "after the name of"),
        (42, 42, "Gideon,"),
        (43, 44, "who"),
        (45, 46, "was slain"),
        (47, 49, "with the sword"),
        (50, 53, "by the hand of"),
        (54, 54, "Nehor;"),
        (55, 55, "and"),
        (56, 59, "in this valley"),
        (60, 62, "did pitch"),
        (63, 65, "the Nephites"),
        (66, 68, "their tents"),
        (69, 71, "for the night."),
    ],
    21: [
        (0, 0, "And"),
        (1, 3, "sent"),
        (4, 5, "Alma"),
        (6, 7, "spies"),
        (8, 9, "to follow"),
        (10, 13, "the remnant"),
        (14, 16, "of the Amlicites,"),
        (17, 20, "that he might"),
        (21, 23, "know"),
        (24, 26, "of"),
        (27, 29, "their plans"),
        (30, 33, "and their plots,"),
        (34, 37, "that he might"),
        (38, 39, "guard"),
        (40, 42, "himself"),
        (43, 44, "against"),
        (45, 48, "them,"),
        (49, 52, "that he might"),
        (53, 54, "preserve"),
        (55, 56, "his people"),
        (57, 59, "from being destroyed."),
    ],
    22: [
        (0, 1, "Now"),
        (2, 4, "those"),
        (5, 6, "whom"),
        (7, 10, "he had sent out"),
        (11, 12, "to watch"),
        (13, 15, "the camp of"),
        (16, 17, "the Amlicites,"),
        (18, 20, "were called"),
        (21, 21, "Zeram,"),
        (22, 23, "and Amnor,"),
        (24, 25, "and Manti,"),
        (26, 27, "and Limher;"),
        (28, 31, "these were they"),
        (32, 33, "who"),
        (34, 37, "went out"),
        (38, 41, "with their men"),
        (42, 43, "to watch"),
        (44, 46, "the camp of"),
        (47, 48, "the Amlicites."),
    ],
    23: [
        (0, 2, "And it came to pass"),
        (3, 8, "on the morrow"),
        (9, 14, "they returned"),
        (15, 17, "into the camp of"),
        (18, 20, "the Nephites"),
        (21, 24, "in great haste,"),
        (25, 28, "being greatly astonished,"),
        (29, 29, "and"),
        (30, 31, "struck"),
        (32, 35, "with much fear,"),
        (36, 37, "saying:"),
    ],
    24: [
        (0, 0, "Behold,"),
        (1, 3, "we followed"),
        (4, 6, "the camp of"),
        (7, 9, "the Amlicites,"),
        (10, 10, "and"),
        (11, 15, "to our great astonishment,"),
        (16, 19, "as we beheld,"),
        (20, 23, "in the land of"),
        (24, 24, "Minon,"),
        (25, 28, "above"),
        (29, 30, "the land"),
        (31, 32, "of Zarahemla,"),
        (33, 35, "in the course of"),
        (36, 38, "the land"),
        (39, 40, "of Nephi,"),
        (41, 44, "a numerous host"),
        (45, 47, "of the Lamanites;"),
        (48, 48, "and"),
        (49, 49, "behold,"),
        (50, 52, "have joined"),
        (53, 54, "the Amlicites"),
        (55, 58, "them;"),
    ],
    25: [
        (0, 0, "And"),
        (1, 4, "are now"),
        (5, 6, "they"),
        (7, 9, "upon"),
        (10, 12, "our brethren"),
        (13, 16, "in that land;"),
        (17, 17, "and"),
        (18, 21, "they are fleeing"),
        (22, 25, "before them"),
        (26, 29, "with their flocks,"),
        (30, 33, "and their wives,"),
        (34, 37, "and their children,"),
        (38, 40, "towards"),
        (41, 43, "our city;"),
        (44, 44, "and"),
        (45, 46, "except"),
        (47, 50, "we make haste,"),
        (51, 55, "they obtain"),
        (56, 58, "our city"),
        (59, 60, "to be"),
        (61, 63, "for them,"),
        (64, 64, "and"),
        (65, 68, "shall be slain"),
        (69, 71, "our fathers,"),
        (72, 75, "and our wives,"),
        (76, 79, "and our children."),
    ],
    26: [
        (0, 3, "And it came to pass that"),
        (4, 4, "took"),
        (5, 6, "the people"),
        (7, 8, "of Nephi"),
        (9, 11, "their tents,"),
        (12, 15, "and departed"),
        (16, 19, "out of the valley of"),
        (20, 20, "Gideon"),
        (21, 23, "towards"),
        (24, 26, "their city,"),
        (27, 29, "which was the city"),
        (30, 31, "of Zarahemla."),
    ],
    27: [
        (0, 0, "And"),
        (1, 1, "behold,"),
        (2, 4, "as they were crossing"),
        (5, 7, "the river"),
        (8, 8, "Sidon,"),
        (9, 11, "came"),
        (12, 15, "upon them"),
        (16, 17, "the Lamanites"),
        (18, 20, "and the Amlicites,"),
        (21, 24, "almost as numerous"),
        (25, 27, "in number,"),
        (28, 32, "as it were"),
        (33, 35, "the sands of"),
        (36, 37, "the sea,"),
        (38, 39, "to destroy"),
        (40, 41, "them."),
    ],
    28: [
        (0, 3, "Nevertheless,"),
        (4, 4, "for"),
        (5, 6, "being strengthened"),
        (7, 8, "the Nephites"),
        (9, 11, "by the hand of"),
        (12, 14, "the Lord,"),
        (15, 15, "having"),
        (16, 20, "prayed mightily"),
        (21, 23, "to him,"),
        (24, 27, "that he would deliver"),
        (28, 29, "them"),
        (30, 32, "out of the hands of"),
        (33, 35, "their enemies,"),
        (36, 37, "therefore"),
        (38, 41, "did hear"),
        (42, 43, "the Lord"),
        (44, 47, "their cries,"),
        (48, 49, "and did strengthen"),
        (50, 51, "them,"),
        (52, 52, "and"),
        (53, 55, "did fall"),
        (56, 57, "the Lamanites"),
        (58, 60, "and the Amlicites"),
        (61, 64, "before them."),
    ],
    29: [
        (0, 3, "And it came to pass that"),
        (4, 4, "fought"),
        (5, 5, "Alma"),
        (6, 7, "with Amlici"),
        (8, 10, "with the sword,"),
        (11, 12, "face to face;"),
        (13, 13, "and"),
        (14, 18, "they did contend mightily,"),
        (19, 24, "one with another."),
    ],
    30: [
        (0, 2, "And it came to pass"),
        (3, 3, "because"),
        (4, 5, "Alma,"),
        (6, 7, "he being"),
        (8, 10, "a man"),
        (11, 13, "of God,"),
        (14, 15, "and because"),
        (16, 19, "being exercised"),
        (20, 23, "with much faith,"),
        (24, 25, "therefore"),
        (26, 31, "he cried,"),
        (32, 33, "saying:"),
        (34, 36, "O Lord,"),
        (37, 41, "have mercy"),
        (42, 43, "and spare"),
        (44, 45, "my life,"),
        (46, 49, "that may"),
        (50, 50, "be"),
        (51, 51, "I"),
        (52, 53, "an instrument"),
        (54, 56, "in thy hands"),
        (57, 58, "to save"),
        (59, 60, "and preserve"),
        (61, 62, "this people."),
    ],
    31: [
        (0, 1, "Now"),
        (2, 5, "when had"),
        (6, 7, "said"),
        (8, 9, "Alma"),
        (10, 12, "these words,"),
        (13, 17, "he contended again"),
        (18, 19, "with Amlici;"),
        (20, 20, "and"),
        (21, 24, "he was strengthened,"),
        (25, 28, "insomuch that"),
        (29, 31, "he slew"),
        (32, 32, "Amlici"),
        (33, 35, "with the sword."),
    ],
    32: [
        (0, 0, "And"),
        (1, 5, "he also fought"),
        (6, 8, "with the king of"),
        (9, 11, "the Lamanites;"),
        (12, 12, "but"),
        (13, 15, "fled back"),
        (16, 17, "the king"),
        (18, 20, "of the Lamanites"),
        (21, 23, "from before"),
        (24, 24, "Alma,"),
        (25, 28, "and he sent"),
        (29, 30, "his guards"),
        (31, 32, "to contend"),
        (33, 34, "with Alma."),
    ],
    33: [
        (0, 0, "But,"),
        (1, 2, "contended"),
        (3, 3, "Alma"),
        (4, 6, "with his guards"),
        (7, 9, "with the guards of"),
        (10, 11, "the king"),
        (12, 14, "of the Lamanites,"),
        (15, 17, "until"),
        (18, 19, "he slew"),
        (20, 21, "and drove"),
        (22, 23, "them"),
        (24, 25, "back."),
    ],
    34: [
        (0, 0, "And"),
        (1, 3, "thus"),
        (4, 5, "he cleared"),
        (6, 8, "the ground,"),
        (9, 10, "or rather"),
        (11, 12, "the bank,"),
        (13, 18, "which was on the west"),
        (19, 22, "of the river"),
        (23, 23, "Sidon,"),
        (24, 27, "throwing"),
        (28, 29, "the bodies of"),
        (30, 31, "the Lamanites"),
        (32, 33, "who had been slain,"),
        (34, 36, "into the waters of"),
        (37, 37, "Sidon,"),
        (38, 41, "that might"),
        (42, 42, "have"),
        (43, 45, "his people"),
        (46, 47, "room"),
        (48, 51, "to cross"),
        (52, 54, "and contend with"),
        (55, 56, "the Lamanites"),
        (57, 59, "and the Amlicites,"),
        (60, 64, "on the west side"),
        (65, 68, "of the river"),
        (69, 69, "Sidon."),
    ],
    35: [
        (0, 3, "And it came to pass that"),
        (4, 7, "when they had all crossed"),
        (8, 10, "the river"),
        (11, 11, "Sidon,"),
        (12, 14, "that"),
        (15, 16, "began to"),
        (17, 17, "flee"),
        (18, 20, "the Lamanites"),
        (21, 23, "and the Amlicites"),
        (24, 27, "before them,"),
        (28, 30, "notwithstanding"),
        (31, 34, "they were so numerous"),
        (35, 36, "they"),
        (37, 40, "that could not"),
        (41, 41, "be numbered"),
        (42, 43, "them."),
    ],
    36: [
        (0, 0, "And"),
        (1, 3, "they fled"),
        (4, 6, "before"),
        (7, 8, "the Nephites"),
        (9, 10, "towards"),
        (11, 12, "the wilderness"),
        (13, 18, "which was west"),
        (19, 20, "and north,"),
        (21, 26, "away beyond"),
        (27, 27, "the borders"),
        (28, 30, "of the land,"),
        (31, 31, "and"),
        (32, 33, "did pursue"),
        (34, 35, "them"),
        (36, 38, "the Nephites"),
        (39, 42, "with their might,"),
        (43, 44, "and did slay"),
        (45, 46, "them."),
    ],
    37: [
        (0, 0, "Yea,"),
        (1, 2, "were met"),
        (3, 4, "they"),
        (5, 7, "on every hand,"),
        (8, 9, "and slain"),
        (10, 11, "and driven,"),
        (12, 14, "until"),
        (15, 15, "were scattered"),
        (16, 17, "they"),
        (18, 22, "on the west,"),
        (23, 27, "and on the north,"),
        (28, 30, "until"),
        (31, 33, "they had reached"),
        (34, 36, "the wilderness,"),
        (37, 40, "which was called"),
        (41, 41, "Hermounts;"),
        (42, 42, "and"),
        (43, 46, "it was that part"),
        (47, 49, "of the wilderness"),
        (50, 52, "which was infested by"),
        (53, 54, "wild beasts"),
        (55, 56, "and ravenous."),
    ],
    38: [
        (0, 3, "And it came to pass that"),
        (4, 4, "many"),
        (5, 6, "died"),
        (7, 9, "in the wilderness"),
        (10, 13, "of their wounds,"),
        (14, 15, "and were devoured"),
        (16, 19, "by those beasts"),
        (20, 22, "and also the vultures"),
        (23, 25, "of the air;"),
        (26, 26, "and"),
        (27, 28, "have been found"),
        (29, 31, "their bones,"),
        (32, 33, "have been heaped up"),
        (34, 36, "on"),
        (37, 38, "the earth."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
