"""Hand-curated TAM-phrase gloss overrides for 1 Nifae 13 — the great and abominable church, the Bible coming forth, America, the Book of Mormon."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "1nephi"
CHAPTER_NUM = 13
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass"),
        (4, 5, "spake"),
        (6, 7, "the angel"),
        (8, 10, "unto me,"),
        (11, 12, "saying:"),
        (13, 14, "Look!"),
        (15, 18, "And I looked"),
        (19, 21, "and beheld"),
        (22, 22, "nations"),
        (23, 24, "and kingdoms"),
        (25, 26, "many."),
    ],
    2: [
        (0, 3, "And spake"),
        (4, 5, "the angel"),
        (6, 8, "unto me:"),
        (9, 13, "what"),
        (14, 17, "beholdest thou?"),
        (18, 22, "And I said:"),
        (23, 26, "I behold"),
        (27, 27, "nations"),
        (28, 29, "and kingdoms"),
        (30, 31, "many."),
    ],
    3: [
        (0, 5, "And said he"),
        (6, 8, "unto me:"),
        (9, 10, "the nations"),
        (11, 13, "and kingdoms"),
        (14, 15, "of the Gentiles."),
    ],
    4: [
        (0, 3, "And it came to pass"),
        (4, 5, "I beheld"),
        (6, 8, "among"),
        (9, 11, "the nations of the Gentiles"),
        (12, 13, "the formation"),
        (14, 17, "of a great church."),
    ],
    5: [
        (0, 5, "And spake the angel"),
        (6, 8, "unto me:"),
        (9, 9, "Behold"),
        (10, 12, "the formation"),
        (13, 15, "of a church"),
        (16, 19, "most abominable"),
        (20, 23, "above all other churches,"),
        (24, 26, "which slayeth"),
        (27, 32, "the saints of God,"),
        (33, 33, "yea,"),
        (34, 35, "and tortureth"),
        (36, 39, "them"),
        (40, 41, "and bindeth"),
        (42, 45, "them down,"),
        (46, 47, "and yoketh"),
        (48, 49, "them"),
        (50, 53, "with an iron yoke,"),
        (54, 55, "and bringeth them down"),
        (56, 57, "them"),
        (58, 58, "into captivity."),
    ],
    6: [
        (0, 3, "And it came to pass"),
        (4, 6, "I beheld"),
        (7, 12, "this great and abominable church;"),
        (13, 16, "and I saw"),
        (17, 21, "the devil"),
        (22, 24, "that he was the founder of it."),
    ],
    7: [
        (0, 4, "And I saw also"),
        (5, 6, "gold,"),
        (7, 8, "and silver,"),
        (9, 10, "and silks,"),
        (11, 13, "and scarlets,"),
        (14, 18, "and fine-twined linen,"),
        (19, 24, "and all manner of precious clothing;"),
        (25, 28, "and I saw"),
        (29, 33, "many harlots."),
    ],
    8: [
        (0, 5, "And spake the angel"),
        (6, 8, "unto me,"),
        (9, 10, "saying:"),
        (11, 11, "Behold"),
        (12, 14, "the gold,"),
        (15, 17, "and the silver,"),
        (18, 19, "and the silks,"),
        (20, 22, "and the scarlets,"),
        (23, 27, "and the fine linen,"),
        (28, 30, "and the precious clothing,"),
        (31, 33, "and the harlots,"),
        (34, 36, "are the desires"),
        (37, 43, "of this great and abominable church."),
    ],
    9: [
        (0, 6, "And also for the praise of the world"),
        (7, 10, "do they destroy"),
        (11, 16, "the saints of God,"),
        (17, 18, "and bring them down"),
        (19, 20, "them"),
        (21, 21, "into captivity."),
    ],
    10: [
        (0, 3, "And it came to pass"),
        (4, 8, "I beheld"),
        (9, 11, "many waters;"),
        (12, 15, "and they divided"),
        (16, 16, "the Gentiles"),
        (17, 21, "from the seed of my brothers."),
    ],
    11: [
        (0, 3, "And it came to pass"),
        (4, 5, "spake"),
        (6, 7, "the angel"),
        (8, 10, "unto me:"),
        (11, 11, "Behold"),
        (12, 14, "is upon"),
        (15, 19, "the seed of thy brothers"),
        (20, 21, "the wrath"),
        (22, 24, "of God."),
    ],
    12: [
        (0, 6, "And I looked and beheld"),
        (7, 8, "a man"),
        (9, 12, "among the Gentiles,"),
        (13, 16, "who was separated"),
        (17, 22, "from the seed of my brothers"),
        (23, 26, "by many waters;"),
        (27, 30, "and I beheld"),
        (31, 36, "the Spirit of God,"),
        (37, 39, "came down"),
        (40, 42, "and wrought"),
        (43, 47, "upon the man;"),
        (48, 53, "and he went"),
        (54, 56, "upon"),
        (57, 59, "many waters,"),
        (60, 64, "even unto"),
        (65, 69, "the seed of my brothers,"),
        (70, 75, "who were in the land"),
        (76, 77, "of promise."),
    ],
    13: [
        (0, 3, "And it came to pass"),
        (4, 5, "I beheld"),
        (6, 11, "the Spirit of God,"),
        (12, 15, "it wrought"),
        (16, 22, "upon other Gentiles;"),
        (23, 28, "and they went out"),
        (29, 30, "of captivity,"),
        (31, 33, "upon"),
        (34, 36, "many waters."),
    ],
    14: [
        (0, 3, "And it came to pass"),
        (4, 5, "I beheld"),
        (6, 8, "multitudes"),
        (9, 12, "of the Gentiles"),
        (13, 17, "upon the land"),
        (18, 20, "of promise;"),
        (21, 24, "and I beheld"),
        (25, 29, "the wrath of God,"),
        (30, 33, "was upon"),
        (34, 38, "the seed of my brothers;"),
        (39, 41, "and they were scattered"),
        (42, 43, "them"),
        (44, 47, "before the Gentiles"),
        (48, 50, "and were smitten."),
    ],
    15: [
        (0, 3, "And I beheld"),
        (4, 9, "the Spirit of the Lord,"),
        (10, 14, "was upon the Gentiles;"),
        (15, 18, "and they did prosper"),
        (19, 23, "and obtained the land"),
        (24, 27, "for their inheritance;"),
        (28, 31, "and I beheld"),
        (32, 35, "they were white,"),
        (36, 42, "and exceedingly fair and beautiful,"),
        (43, 48, "like unto my people"),
        (49, 53, "before they were slain."),
    ],
    16: [
        (0, 3, "And it came to pass"),
        (4, 6, "beheld I,"),
        (7, 8, "Nephi,"),
        (9, 9, "the Gentiles"),
        (10, 15, "who had gone out"),
        (16, 17, "of captivity,"),
        (18, 23, "did humble themselves"),
        (24, 28, "before the Lord;"),
        (29, 31, "and was with them"),
        (32, 36, "the power of the Lord"),
        (37, 39, "with them."),
    ],
    17: [
        (0, 3, "And I beheld"),
        (4, 6, "were gathered together"),
        (7, 11, "their mother Gentiles"),
        (12, 15, "upon the waters,"),
        (16, 21, "and also upon the land,"),
        (22, 24, "to battle"),
        (25, 28, "against them."),
    ],
    18: [
        (0, 3, "And I beheld"),
        (4, 5, "was with"),
        (6, 10, "the power of God"),
        (11, 13, "with them,"),
        (14, 22, "and also upon them all"),
        (23, 27, "who were gathered together"),
        (28, 34, "to battle against them,"),
        (35, 39, "the wrath of God."),
    ],
    19: [
        (0, 2, "And I,"),
        (3, 4, "Nephi,"),
        (5, 8, "beheld"),
        (9, 10, "the Gentiles"),
        (11, 16, "who had gone out of captivity,"),
        (17, 19, "were delivered"),
        (20, 25, "by the power of God"),
        (26, 28, "out of the hands"),
        (29, 31, "of all other nations."),
    ],
    20: [
        (0, 3, "And it came to pass"),
        (4, 6, "beheld I,"),
        (7, 8, "Nephi,"),
        (9, 11, "they did prosper"),
        (12, 14, "in the land;"),
        (15, 18, "and I beheld"),
        (19, 20, "a book,"),
        (21, 24, "and it was carried"),
        (25, 30, "among them."),
    ],
    21: [
        (0, 5, "And spake the angel"),
        (6, 8, "unto me:"),
        (9, 11, "Knowest thou"),
        (12, 13, "the meaning"),
        (14, 16, "of the book?"),
    ],
    22: [
        (0, 4, "And I said"),
        (5, 7, "unto him:"),
        (8, 11, "I know not."),
    ],
    23: [
        (0, 5, "And said he:"),
        (6, 10, "Behold proceedeth the book"),
        (11, 13, "from the mouth"),
        (14, 17, "of a Jew."),
        (18, 20, "And I,"),
        (21, 22, "Nephi,"),
        (23, 27, "beheld it;"),
        (28, 33, "and said he"),
        (34, 36, "unto me:"),
        (37, 39, "the book"),
        (40, 45, "that thou beholdest"),
        (46, 48, "is a record"),
        (49, 52, "of the Jews,"),
        (53, 57, "which contains"),
        (58, 61, "the covenants of the Lord,"),
        (62, 64, "which he hath made"),
        (65, 69, "unto the house of Israel;"),
        (70, 76, "and it also containeth"),
        (77, 79, "many"),
        (80, 83, "of the prophecies of the holy prophets;"),
        (84, 87, "and it is a record"),
        (88, 91, "like unto the engravings"),
        (92, 99, "which are upon the plates of brass,"),
        (100, 104, "save not so many;"),
        (105, 108, "nevertheless,"),
        (109, 116, "they contain"),
        (117, 120, "the covenants of the Lord,"),
        (121, 124, "which he hath made"),
        (125, 129, "unto the house of Israel;"),
        (130, 133, "wherefore,"),
        (134, 137, "they are of great worth"),
        (138, 139, "unto"),
        (140, 141, "the Gentiles."),
    ],
    24: [
        (0, 8, "And spake the angel of the Lord"),
        (9, 11, "unto me:"),
        (12, 14, "thou hast beheld"),
        (15, 17, "that book"),
        (18, 20, "proceeded"),
        (21, 22, "from the mouth"),
        (23, 26, "of a Jew;"),
        (27, 31, "and when proceeded"),
        (32, 33, "from the mouth"),
        (34, 37, "of a Jew,"),
        (38, 42, "it contained the fulness"),
        (43, 48, "of the gospel of the Lord,"),
        (49, 54, "of whom have testified"),
        (55, 59, "the twelve apostles;"),
        (60, 63, "and they bear record"),
        (64, 68, "according to the truth"),
        (69, 72, "which is"),
        (73, 76, "in the Lamb"),
        (77, 79, "of God."),
    ],
    25: [
        (0, 3, "Wherefore,"),
        (4, 7, "do go"),
        (8, 9, "these things"),
        (10, 12, "from the Jews"),
        (13, 17, "in purity unto the Gentiles,"),
        (18, 22, "according to the truth"),
        (23, 27, "which is in God."),
    ],
    26: [
        (0, 4, "And after"),
        (5, 9, "they had gone"),
        (10, 14, "by the hand"),
        (15, 20, "of the twelve apostles"),
        (21, 24, "of the Lamb,"),
        (25, 27, "from the Jews"),
        (28, 29, "unto the Gentiles,"),
        (30, 32, "thou beheld"),
        (33, 35, "the formation"),
        (36, 42, "of that great and abominable church,"),
        (43, 47, "which is most abominable"),
        (48, 52, "above all other churches;"),
        (53, 54, "for behold,"),
        (55, 58, "they have taken away"),
        (59, 64, "from the gospel of the Lamb"),
        (65, 69, "many parts"),
        (70, 75, "which are plain and most precious;"),
        (76, 79, "and also many"),
        (80, 83, "covenants of the Lord"),
        (84, 86, "have they taken away."),
    ],
    27: [
        (0, 3, "And they have done"),
        (4, 6, "all these things"),
        (7, 11, "that they might pervert"),
        (12, 16, "the right ways of the Lord,"),
        (17, 22, "that they might blind the eyes,"),
        (23, 26, "and harden the hearts"),
        (27, 31, "of the children of men."),
    ],
    28: [
        (0, 3, "Wherefore,"),
        (4, 6, "thou seest"),
        (7, 10, "after"),
        (11, 14, "had been given the book"),
        (15, 17, "by the way"),
        (18, 26, "into the hands of the great and abominable church,"),
        (27, 32, "many plain and precious things"),
        (33, 37, "were taken away from the book,"),
        (38, 41, "which is the book"),
        (42, 44, "which is of"),
        (45, 47, "the Lamb"),
        (48, 50, "of God."),
    ],
    29: [
        (0, 4, "And after"),
        (5, 11, "had been taken away these plain and precious things"),
        (12, 16, "went the book"),
        (17, 21, "to all the nations of the Gentiles;"),
        (22, 26, "and after"),
        (27, 31, "had gone the book"),
        (32, 36, "to all the nations of the Gentiles,"),
        (37, 37, "yea,"),
        (38, 47, "even across the many waters"),
        (48, 52, "thou hast beheld"),
        (53, 55, "with the Gentiles"),
        (56, 64, "who had gone out of captivity,"),
        (65, 67, "thou seest—because of"),
        (68, 75, "the many plain and precious things"),
        (76, 80, "which have been taken from the book,"),
        (81, 86, "which were plain unto the understanding"),
        (87, 91, "of the children of men,"),
        (92, 96, "according to the plainness"),
        (97, 101, "which is in"),
        (102, 106, "the Lamb of God—because"),
        (107, 111, "of these things which have been taken away"),
        (112, 118, "from the gospel of the Lamb,"),
        (119, 124, "an exceedingly great many do stumble,"),
        (125, 125, "yea,"),
        (126, 130, "insomuch that have power"),
        (131, 135, "Satan great power"),
        (136, 140, "over them."),
    ],
    30: [
        (0, 3, "Nevertheless,"),
        (4, 8, "thou beheld the Gentiles"),
        (9, 17, "who had gone out of captivity,"),
        (18, 21, "and were lifted up"),
        (22, 27, "by the power of God"),
        (28, 33, "above all other nations,"),
        (34, 38, "upon the face of the land"),
        (39, 47, "which is choice above all other lands,"),
        (48, 51, "the land"),
        (52, 56, "covenanted the Lord"),
        (57, 58, "God"),
        (59, 61, "with thy father,"),
        (62, 65, "that should have it"),
        (66, 70, "his seed for the land"),
        (71, 74, "of their inheritance;"),
        (75, 78, "wherefore,"),
        (79, 81, "thou seest"),
        (82, 89, "will not suffer the Lord God"),
        (90, 93, "to utterly destroy"),
        (94, 95, "the Gentiles"),
        (96, 98, "thy mixed seed,"),
        (99, 101, "which are"),
        (102, 104, "among"),
        (105, 106, "thy brothers."),
    ],
    31: [
        (0, 5, "Neither will he suffer"),
        (6, 7, "to be destroyed"),
        (8, 9, "by the Gentiles"),
        (10, 14, "the seed of thy brothers."),
    ],
    32: [
        (0, 8, "Neither will the Lord God suffer"),
        (9, 13, "to remain forever"),
        (14, 14, "the Gentiles"),
        (15, 22, "in that awful state of blindness,"),
        (23, 26, "which thou beholdest"),
        (27, 30, "they are in,"),
        (31, 38, "because of the plain and most precious parts"),
        (39, 45, "of the gospel of the Lamb"),
        (46, 49, "which have been kept back"),
        (50, 53, "by that abominable church,"),
        (54, 56, "whose formation"),
        (57, 61, "thou hast seen."),
    ],
    33: [
        (0, 3, "wherefore"),
        (4, 7, "saith"),
        (8, 13, "the Lamb of God:"),
        (14, 19, "I will be merciful"),
        (20, 21, "unto the Gentiles,"),
        (22, 24, "in the visiting"),
        (25, 29, "of the remnant"),
        (30, 34, "of the house of Israel"),
        (35, 38, "in great judgment."),
    ],
    34: [
        (0, 3, "And it came to pass"),
        (4, 10, "spake the angel of the Lord"),
        (11, 13, "unto me,"),
        (14, 15, "saying:"),
        (16, 16, "Behold,"),
        (17, 19, "saith"),
        (20, 22, "the Lamb"),
        (23, 25, "of God,"),
        (26, 28, "after"),
        (29, 31, "I have visited"),
        (32, 36, "the remnant"),
        (37, 41, "of the house of Israel—and"),
        (42, 44, "and this remnant"),
        (45, 51, "of whom I speak"),
        (52, 57, "is the seed of thy father"),
        (58, 62, "—wherefore,"),
        (63, 65, "after"),
        (66, 68, "I have visited"),
        (69, 72, "them"),
        (73, 75, "with judgment,"),
        (76, 79, "and smitten them"),
        (80, 84, "by the hand of the Gentiles,"),
        (85, 88, "and after"),
        (89, 92, "great stumbling of the Gentiles,"),
        (93, 100, "because of the most plain and precious parts"),
        (101, 107, "of the gospel of the Lamb"),
        (108, 111, "which have been kept back"),
        (112, 115, "by that abominable church,"),
        (116, 118, "the mother"),
        (119, 121, "of harlots,"),
        (122, 128, "saith the Lamb—I"),
        (129, 134, "will be merciful"),
        (135, 139, "unto the Gentiles in that day,"),
        (140, 146, "insomuch that"),
        (147, 152, "I will bring unto them,"),
        (153, 156, "in mine own power,"),
        (157, 161, "much of my gospel,"),
        (162, 168, "which shall be plain and precious,"),
        (169, 175, "saith the Lamb."),
    ],
    35: [
        (0, 1, "For behold,"),
        (2, 4, "saith"),
        (5, 7, "the Lamb:"),
        (8, 15, "I will manifest myself"),
        (16, 18, "unto thy seed,"),
        (19, 24, "and they shall write"),
        (25, 28, "many things"),
        (29, 34, "which I shall minister"),
        (35, 38, "unto them,"),
        (39, 43, "which shall be plain"),
        (44, 45, "and precious;"),
        (46, 49, "and after"),
        (50, 53, "has been destroyed thy seed,"),
        (54, 59, "and dwindled in unbelief,"),
        (60, 65, "and the seed also of thy brothers,"),
        (66, 66, "behold,"),
        (67, 72, "shall be hid these things,"),
        (73, 77, "that may come unto the Gentiles,"),
        (78, 86, "by the gift and power"),
        (87, 90, "of the Lamb."),
    ],
    36: [
        (0, 4, "And shall be written"),
        (5, 9, "in them"),
        (10, 11, "my gospel,"),
        (12, 15, "saith"),
        (16, 18, "the Lamb,"),
        (19, 21, "and my rock"),
        (22, 24, "and my salvation."),
    ],
    37: [
        (0, 4, "And blessed are they"),
        (5, 9, "who shall seek"),
        (10, 12, "to bring my Zion"),
        (13, 15, "in that day,"),
        (16, 21, "for they shall have"),
        (22, 23, "the gift"),
        (24, 30, "and power of the Holy Ghost;"),
        (31, 35, "and if they endure"),
        (36, 40, "unto the end"),
        (41, 47, "shall be lifted up"),
        (48, 53, "at the last day,"),
        (54, 58, "and shall be saved"),
        (59, 64, "in the everlasting kingdom"),
        (65, 68, "of the Lamb;"),
        (69, 71, "and whoso"),
        (72, 73, "any"),
        (74, 78, "shall publish"),
        (79, 80, "peace,"),
        (81, 81, "yea,"),
        (82, 87, "tidings of great joy,"),
        (88, 92, "how beautiful"),
        (93, 94, "upon them"),
        (95, 98, "upon the mountains."),
    ],
    38: [
        (0, 3, "And it came to pass"),
        (4, 5, "I beheld"),
        (6, 10, "the remnant"),
        (11, 16, "of the seed of my brothers,"),
        (17, 22, "and also the book"),
        (23, 29, "of the Lamb of God,"),
        (30, 33, "which had come"),
        (34, 38, "from the mouth of the Jew,"),
        (39, 41, "came from"),
        (42, 42, "the Gentiles"),
        (43, 47, "unto the remnant"),
        (48, 53, "of the seed of my brothers."),
    ],
    39: [
        (0, 4, "And after"),
        (5, 9, "had come the book"),
        (10, 13, "unto them"),
        (14, 16, "I beheld"),
        (17, 18, "other books,"),
        (19, 21, "which came"),
        (22, 24, "by"),
        (25, 31, "the power of the Lamb,"),
        (32, 37, "from the Gentiles unto them,"),
        (38, 42, "for the persuading of the Gentiles"),
        (43, 53, "and the remnant of the seed of my brothers,"),
        (54, 57, "and also the Jews"),
        (58, 66, "who were scattered upon the face of the earth,"),
        (67, 70, "that are true"),
        (71, 73, "the records of the prophets"),
        (74, 77, "and the twelve apostles"),
        (78, 81, "of the Lamb."),
    ],
    40: [
        (0, 5, "And spake the angel"),
        (6, 8, "unto me,"),
        (9, 10, "saying:"),
        (11, 14, "these last records,"),
        (15, 20, "which thou hast seen"),
        (21, 24, "among the Gentiles,"),
        (25, 29, "shall establish"),
        (30, 34, "the truth of the first,"),
        (35, 37, "which are from"),
        (38, 44, "the twelve apostles of the Lamb,"),
        (45, 51, "and shall make known"),
        (52, 55, "the plain and precious things"),
        (56, 61, "which have been taken away from them;"),
        (62, 68, "and shall make known"),
        (69, 74, "to all kindreds, tongues, and people,"),
        (75, 81, "that the Lamb of God"),
        (82, 84, "is the Son"),
        (85, 89, "of the Eternal Father,"),
        (90, 96, "and the Savior of the world;"),
        (97, 102, "and that must all men"),
        (103, 108, "come unto him,"),
        (109, 116, "or they cannot be saved."),
    ],
    41: [
        (0, 6, "And they must come"),
        (7, 14, "according to the words which shall be established"),
        (15, 21, "by the mouth of the Lamb;"),
        (22, 28, "and the words of the Lamb"),
        (29, 33, "shall be made known"),
        (34, 38, "in the records of thy seed,"),
        (39, 41, "as also in"),
        (42, 50, "the records of the twelve apostles of the Lamb;"),
        (51, 54, "wherefore"),
        (55, 58, "shall be established"),
        (59, 63, "they both shall be one;"),
        (64, 68, "for there is one God"),
        (69, 74, "and one Shepherd"),
        (75, 76, "over"),
        (77, 80, "all the earth."),
    ],
    42: [
        (0, 5, "And cometh the time"),
        (6, 13, "that he shall manifest himself"),
        (14, 16, "himself"),
        (17, 19, "unto all nations,"),
        (20, 21, "to the Jews"),
        (22, 25, "and also to the Gentiles;"),
        (26, 31, "and after he hath manifested"),
        (32, 36, "himself"),
        (37, 42, "unto the Jews and also unto the Gentiles,"),
        (43, 46, "then shall he manifest"),
        (47, 50, "himself"),
        (51, 56, "unto the Gentiles and also unto the Jews,"),
        (57, 60, "and the last"),
        (61, 65, "shall be first,"),
        (66, 70, "and the first"),
        (71, 74, "shall be last."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
