"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 47 — Amalickiah's
treachery: he rises among the Lamanites, betrays and poisons Lehonti, murders
the king by his servants, frames the servants, and by cunning marries the queen
and is made king over the Lamanites.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits done up front against bom_books.json:
  v32 `tupu—auā`

    python3 build_overrides_alma47.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 47

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "Now"),
        (2, 8, "we will return"),
        (9, 12, "in our record"),
        (13, 14, "to Amalickiah"),
        (15, 17, "and those"),
        (18, 21, "who fled"),
        (22, 24, "together with him"),
        (25, 27, "into the wilderness;"),
        (28, 28, "for,"),
        (29, 29, "behold,"),
        (30, 32, "he took"),
        (33, 34, "them"),
        (35, 38, "who went"),
        (39, 41, "together with him,"),
        (42, 44, "and went up"),
        (45, 48, "in the land of"),
        (49, 49, "Nephi"),
        (50, 52, "among"),
        (53, 54, "the Lamanites,"),
        (55, 56, "and stirred up"),
        (57, 58, "the Lamanites"),
        (59, 60, "to anger"),
        (61, 63, "against"),
        (64, 67, "the people of Nephi"),
        (68, 70, "insomuch that"),
        (71, 73, "was sent"),
        (74, 77, "by the king of"),
        (78, 79, "the Lamanites"),
        (80, 81, "a proclamation"),
        (82, 85, "in his whole land,"),
        (86, 88, "among"),
        (89, 91, "all his people,"),
        (92, 96, "that they gather together again"),
        (97, 99, "themselves"),
        (100, 102, "to go"),
        (103, 105, "to fight against"),
        (106, 108, "the Nephites."),
    ],
    2: [
        (0, 4, "And when had come"),
        (5, 6, "the proclamation"),
        (7, 9, "unto them,"),
        (10, 14, "they were exceedingly afraid;"),
        (15, 15, "yea,"),
        (16, 18, "they feared"),
        (19, 21, "to anger"),
        (22, 23, "the king,"),
        (24, 28, "and they also feared"),
        (29, 30, "to go"),
        (31, 33, "to fight with"),
        (34, 35, "the Nephites"),
        (36, 37, "lest be lost"),
        (38, 40, "their lives."),
        (41, 44, "And it came to pass that"),
        (45, 47, "they refused,"),
        (48, 51, "or the greater part"),
        (52, 54, "of them"),
        (55, 56, "refused,"),
        (57, 59, "to obey"),
        (60, 61, "the commandments of"),
        (62, 63, "the king."),
    ],
    3: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 8, "the king was angry"),
        (9, 10, "because of"),
        (11, 14, "their disobedience;"),
        (15, 16, "therefore"),
        (17, 21, "he gave"),
        (22, 23, "to Amalickiah"),
        (24, 25, "the command"),
        (26, 30, "of that part of"),
        (31, 32, "his army"),
        (33, 35, "which obeyed"),
        (36, 38, "his commands,"),
        (39, 40, "and commanded"),
        (41, 42, "him"),
        (43, 45, "to go forth"),
        (46, 47, "and compel"),
        (48, 49, "them"),
        (50, 52, "to go"),
        (53, 54, "to fight."),
    ],
    4: [
        (0, 1, "Now"),
        (2, 2, "behold,"),
        (3, 6, "this is the thing"),
        (7, 10, "which was desired"),
        (11, 11, "by Amalickiah;"),
        (12, 14, "for he"),
        (15, 17, "was a man"),
        (18, 20, "very cunning and deceitful"),
        (21, 22, "therefore"),
        (23, 26, "he devised"),
        (27, 28, "a plan"),
        (29, 31, "in his heart"),
        (32, 34, "to remove"),
        (35, 36, "the king"),
        (37, 39, "of the Lamanites"),
        (40, 42, "from the throne."),
    ],
    5: [
        (0, 2, "And now"),
        (3, 5, "he obtained"),
        (6, 7, "the command"),
        (8, 11, "of those parts of"),
        (12, 13, "the Lamanites"),
        (14, 18, "who favored"),
        (19, 20, "the king;"),
        (21, 24, "and he sought"),
        (25, 26, "to gain"),
        (27, 28, "the favor"),
        (29, 32, "from those"),
        (33, 34, "who"),
        (35, 37, "were disobedient;"),
        (38, 39, "therefore"),
        (40, 44, "he went forth"),
        (45, 47, "to the place"),
        (48, 51, "which was called Onidah,"),
        (52, 54, "for there"),
        (55, 59, "had fled"),
        (60, 62, "all the Lamanites;"),
        (63, 66, "for they knew"),
        (67, 69, "had come"),
        (70, 71, "the army,"),
        (72, 72, "and,"),
        (73, 75, "in thinking"),
        (76, 79, "they had come"),
        (80, 81, "to destroy"),
        (82, 83, "them,"),
        (84, 85, "therefore"),
        (86, 89, "they fled"),
        (90, 91, "to Onidah,"),
        (92, 95, "to the place of"),
        (96, 98, "weapons of war."),
    ],
    6: [
        (0, 3, "And they appointed"),
        (4, 5, "a man"),
        (6, 8, "to become"),
        (9, 9, "a king"),
        (10, 11, "and a leader"),
        (12, 14, "over them,"),
        (15, 17, "for were fixed"),
        (18, 21, "in their minds"),
        (22, 25, "with a determined resolve"),
        (26, 32, "that they would not be compelled"),
        (33, 35, "to go"),
        (36, 37, "against"),
        (38, 40, "the Nephites."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they gathered together"),
        (7, 9, "themselves"),
        (10, 12, "upon"),
        (13, 14, "the top"),
        (15, 17, "of the mountain"),
        (18, 18, "which"),
        (19, 21, "was called"),
        (22, 22, "Antipas,"),
        (23, 25, "in preparation"),
        (26, 27, "to fight."),
    ],
    8: [
        (0, 1, "Now"),
        (2, 4, "it was not"),
        (5, 8, "the intention of Amalickiah"),
        (9, 11, "to fight with"),
        (12, 13, "them"),
        (14, 16, "according to"),
        (17, 18, "the commandments of"),
        (19, 20, "the king;"),
        (21, 22, "but behold,"),
        (23, 25, "his intention"),
        (26, 30, "was to obtain"),
        (31, 33, "the favor"),
        (34, 36, "with the armies of"),
        (37, 38, "the Lamanites,"),
        (39, 44, "that he might place"),
        (45, 47, "himself"),
        (48, 51, "to be a head"),
        (52, 54, "over them"),
        (55, 56, "and remove"),
        (57, 58, "the king"),
        (59, 61, "from the throne"),
        (62, 66, "and he rule over"),
        (67, 68, "the kingdom."),
    ],
    9: [
        (0, 1, "And behold,"),
        (2, 4, "it came to pass that"),
        (5, 6, "he commanded"),
        (7, 8, "his army"),
        (9, 10, "to set up"),
        (11, 13, "their tents"),
        (14, 16, "in the valley"),
        (17, 17, "which"),
        (18, 20, "was near"),
        (21, 24, "the mount of Antipas."),
    ],
    10: [
        (0, 3, "And it came to pass that"),
        (4, 5, "when it was night,"),
        (6, 9, "he sent"),
        (10, 12, "a secret messenger"),
        (13, 16, "into the mount of"),
        (17, 17, "Antipas,"),
        (18, 20, "desiring"),
        (21, 22, "the leader"),
        (23, 24, "of those"),
        (25, 28, "who were upon"),
        (29, 30, "the mount,"),
        (31, 33, "his name"),
        (34, 35, "was Lehonti,"),
        (36, 40, "that he come"),
        (41, 42, "down"),
        (43, 46, "to the foot of the mountain,"),
        (47, 50, "for he desired"),
        (51, 52, "to talk"),
        (53, 54, "with him."),
    ],
    11: [
        (0, 3, "And it came to pass that"),
        (4, 5, "when received"),
        (6, 7, "Lehonti"),
        (8, 9, "the message,"),
        (10, 13, "he feared"),
        (14, 16, "to go down"),
        (17, 18, "below"),
        (19, 22, "to the foot of the mountain."),
        (23, 26, "And it came to pass that"),
        (27, 29, "sent again"),
        (30, 30, "a second time"),
        (31, 32, "Amalickiah"),
        (33, 34, "the message,"),
        (35, 36, "desiring"),
        (37, 39, "him"),
        (40, 41, "to come"),
        (42, 43, "down."),
        (44, 46, "And refused"),
        (47, 47, "Lehonti;"),
        (48, 53, "and he sent again"),
        (54, 55, "the message"),
        (56, 56, "a third time."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 5, "when knew"),
        (6, 7, "Amalickiah"),
        (8, 13, "he could not cause"),
        (14, 16, "that come down"),
        (17, 17, "Lehonti"),
        (18, 20, "from the mount,"),
        (21, 24, "he went up"),
        (25, 27, "onto"),
        (28, 29, "the mount,"),
        (30, 33, "almost reaching"),
        (34, 37, "to the camp of"),
        (38, 38, "Lehonti;"),
        (39, 45, "and he again sent also"),
        (46, 47, "his message"),
        (48, 48, "a fourth time"),
        (49, 50, "unto Lehonti,"),
        (51, 52, "desiring"),
        (53, 56, "that he come"),
        (57, 58, "down,"),
        (59, 61, "and that bring"),
        (62, 63, "his guards"),
        (64, 66, "together with him."),
    ],
    13: [
        (0, 3, "And it came to pass that"),
        (4, 6, "Lehonti came down"),
        (7, 8, "below"),
        (9, 10, "together with"),
        (11, 12, "his guards"),
        (13, 14, "to Amalickiah,"),
        (15, 17, "Amalickiah desired"),
        (18, 20, "of him"),
        (21, 23, "that come down"),
        (24, 27, "together with his army"),
        (28, 30, "in the night,"),
        (31, 32, "and surround"),
        (33, 33, "the men"),
        (34, 38, "who were in their camps"),
        (39, 40, "whom"),
        (41, 45, "was given"),
        (46, 48, "by the king"),
        (49, 52, "for him to command,"),
        (53, 59, "and he would deliver up"),
        (60, 62, "them"),
        (63, 65, "into the hands of"),
        (66, 66, "Lehonti,"),
        (67, 68, "if"),
        (69, 72, "he would make"),
        (73, 73, "(Amalickiah)"),
        (74, 77, "the second leader"),
        (78, 81, "over the whole army."),
    ],
    14: [
        (0, 3, "And it came to pass that"),
        (4, 7, "came down"),
        (8, 8, "Lehonti"),
        (9, 10, "together with"),
        (11, 12, "his men"),
        (13, 14, "and surrounded"),
        (15, 17, "the men of Amalickiah,"),
        (18, 19, "so that"),
        (20, 24, "before they awoke"),
        (25, 28, "at the breaking of"),
        (29, 29, "dawn"),
        (30, 33, "they were surrounded"),
        (34, 36, "by the armies of"),
        (37, 37, "Lehonti."),
    ],
    15: [
        (0, 3, "And it came to pass that"),
        (4, 7, "when they saw"),
        (8, 11, "they were surrounded,"),
        (12, 15, "they pleaded"),
        (16, 17, "unto Amalickiah"),
        (18, 22, "that he allow"),
        (23, 24, "them"),
        (25, 27, "to join with"),
        (28, 30, "their brethren,"),
        (31, 36, "that they be not destroyed."),
        (37, 38, "Now"),
        (39, 43, "the very thing"),
        (44, 44, "this"),
        (45, 48, "which was desired"),
        (49, 49, "by Amalickiah."),
    ],
    16: [
        (0, 3, "And it came to pass that"),
        (4, 6, "he saved"),
        (7, 8, "his men,"),
        (9, 13, "which was not according to"),
        (14, 15, "the commands of"),
        (16, 17, "the king."),
        (18, 19, "Now"),
        (20, 23, "this is the thing"),
        (24, 27, "which was desired"),
        (28, 28, "by Amalickiah,"),
        (29, 35, "that he might accomplish"),
        (36, 37, "his designs"),
        (38, 41, "in the removing of"),
        (42, 43, "the king"),
        (44, 46, "from the throne."),
    ],
    17: [
        (0, 1, "Now"),
        (2, 5, "it was the custom"),
        (6, 8, "among"),
        (9, 10, "the Lamanites,"),
        (11, 13, "if was slain"),
        (14, 17, "their chief leader,"),
        (18, 19, "to appoint"),
        (20, 23, "the second leader"),
        (24, 26, "to become"),
        (27, 30, "their chief leader."),
    ],
    18: [
        (0, 3, "And it came to pass that"),
        (4, 4, "commanded"),
        (5, 6, "Amalickiah"),
        (7, 9, "one of"),
        (10, 11, "his servants"),
        (12, 13, "gradually"),
        (14, 16, "should give"),
        (17, 19, "the poison"),
        (20, 21, "to Lehonti,"),
        (22, 27, "that he should die."),
    ],
    19: [
        (0, 1, "Now,"),
        (2, 4, "when died"),
        (5, 5, "Lehonti,"),
        (6, 7, "was appointed"),
        (8, 8, "Amalickiah"),
        (9, 11, "by the Lamanites"),
        (12, 14, "to become"),
        (15, 17, "their leader"),
        (18, 20, "and their"),
        (21, 22, "chief commander."),
    ],
    20: [
        (0, 3, "And it came to pass that"),
        (4, 5, "marched forth"),
        (6, 6, "Amalickiah"),
        (7, 9, "with his armies"),
        (10, 13, "(for he had accomplished"),
        (14, 15, "his desires)"),
        (16, 19, "to the land of"),
        (20, 20, "Nephi,"),
        (21, 24, "to the city of"),
        (25, 25, "Nephi,"),
        (26, 29, "the chief city"),
        (30, 30, "it was."),
    ],
    21: [
        (0, 4, "And came forth"),
        (5, 6, "the king"),
        (7, 9, "with his guards"),
        (10, 11, "to meet"),
        (12, 13, "with him,"),
        (14, 18, "for he thought"),
        (19, 22, "had accomplished"),
        (23, 24, "Amalickiah"),
        (25, 26, "his commands,"),
        (27, 30, "and had gathered together"),
        (31, 32, "Amalickiah"),
        (33, 36, "an exceedingly great army"),
        (37, 39, "to go"),
        (40, 41, "to fight against"),
        (42, 44, "the Nephites."),
    ],
    22: [
        (0, 1, "But behold,"),
        (2, 3, "as came"),
        (4, 5, "the king"),
        (6, 7, "forth"),
        (8, 9, "to meet"),
        (10, 11, "with him,"),
        (12, 13, "commanded"),
        (14, 15, "Amalickiah"),
        (16, 17, "his servants"),
        (18, 20, "that go"),
        (21, 22, "forward"),
        (23, 24, "to greet"),
        (25, 26, "the king."),
        (27, 31, "And they went"),
        (32, 34, "and they bowed"),
        (35, 37, "before"),
        (38, 39, "the king,"),
        (40, 41, "as if"),
        (42, 44, "to show"),
        (45, 46, "reverence"),
        (47, 49, "to him"),
        (50, 51, "because of"),
        (52, 53, "his greatness."),
    ],
    23: [
        (0, 3, "And it came to pass that"),
        (4, 5, "put forth"),
        (6, 8, "the king"),
        (9, 10, "his hand"),
        (11, 12, "to raise up"),
        (13, 16, "them,"),
        (17, 19, "as"),
        (20, 22, "the custom"),
        (23, 25, "of the Lamanites,"),
        (26, 29, "which was a sign"),
        (30, 32, "of peace,"),
        (33, 36, "a custom which"),
        (37, 39, "they took"),
        (40, 41, "from"),
        (42, 43, "the Nephites."),
    ],
    24: [
        (0, 3, "And it came to pass that"),
        (4, 9, "when he had raised up"),
        (10, 13, "the first man"),
        (14, 16, "from the ground,"),
        (17, 17, "behold"),
        (18, 20, "he stabbed"),
        (21, 22, "the king"),
        (23, 25, "in his heart;"),
        (26, 31, "and he fell down"),
        (32, 34, "to the ground."),
    ],
    25: [
        (0, 1, "Now"),
        (2, 3, "fled"),
        (4, 5, "the servants of"),
        (6, 7, "the king;"),
        (8, 10, "and raised"),
        (11, 14, "by the servants of Amalickiah"),
        (15, 16, "a cry,"),
        (17, 19, "saying:"),
    ],
    26: [
        (0, 0, "Behold,"),
        (1, 2, "have stabbed"),
        (3, 5, "by the servants of"),
        (6, 7, "the king"),
        (8, 9, "him"),
        (10, 12, "in the heart,"),
        (13, 17, "and he has fallen,"),
        (18, 22, "and they have fled;"),
        (23, 23, "behold,"),
        (24, 25, "come"),
        (26, 29, "and see it."),
    ],
    27: [
        (0, 3, "And it came to pass that"),
        (4, 4, "commanded"),
        (5, 6, "Amalickiah"),
        (7, 9, "that march"),
        (10, 11, "forth"),
        (12, 13, "his armies"),
        (14, 15, "and see"),
        (16, 21, "what was the thing"),
        (22, 23, "that happened"),
        (24, 26, "to the king;"),
        (27, 32, "and when they arrived"),
        (33, 35, "at the place"),
        (36, 40, "where the king was,"),
        (41, 44, "and they found"),
        (45, 46, "the king"),
        (47, 48, "lying"),
        (49, 51, "in his blood,"),
        (52, 54, "pretended to be angry"),
        (55, 55, "Amalickiah,"),
        (56, 58, "and said:"),
        (59, 61, "Whosoever"),
        (62, 64, "loved"),
        (65, 66, "the king,"),
        (67, 71, "let him go forth,"),
        (72, 73, "and pursue"),
        (74, 75, "his servants"),
        (76, 80, "that they be slain."),
    ],
    28: [
        (0, 3, "And it came to pass that"),
        (4, 5, "when heard"),
        (6, 8, "all of them"),
        (9, 13, "who loved"),
        (14, 15, "the king"),
        (16, 18, "these words,"),
        (19, 22, "they came"),
        (23, 24, "forth"),
        (25, 26, "and pursued"),
        (27, 28, "the servants of"),
        (29, 30, "the king."),
    ],
    29: [
        (0, 1, "Now"),
        (2, 5, "when saw"),
        (6, 7, "the servants of"),
        (8, 9, "the king"),
        (10, 14, "they were pursued"),
        (15, 17, "by an army,"),
        (18, 21, "they feared again,"),
        (22, 23, "and fled"),
        (24, 26, "into the wilderness,"),
        (27, 29, "and came"),
        (30, 33, "to the land of"),
        (34, 34, "Zarahemla"),
        (35, 37, "and joined with"),
        (38, 41, "the people of Ammon."),
    ],
    30: [
        (0, 0, "And"),
        (1, 4, "the army which"),
        (5, 7, "pursued"),
        (8, 9, "them"),
        (10, 12, "returned,"),
        (13, 15, "for grew weary"),
        (16, 20, "in pursuing them"),
        (21, 23, "but did not find them;"),
        (24, 28, "and thus obtained"),
        (29, 30, "Amalickiah,"),
        (31, 33, "by means of"),
        (34, 35, "his deceit,"),
        (36, 39, "won over"),
        (40, 40, "the hearts"),
        (41, 43, "of the people."),
    ],
    31: [
        (0, 2, "And it came to pass"),
        (3, 5, "on the day"),
        (6, 8, "that followed,"),
        (9, 14, "he entered"),
        (15, 18, "into the city of"),
        (19, 19, "Nephi"),
        (20, 22, "with his armies,"),
        (23, 26, "and took for himself"),
        (27, 28, "the city."),
    ],
    32: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 7, "when heard"),
        (8, 9, "the queen"),
        (10, 11, "was slain"),
        (12, 13, "the king—"),
        (14, 14, "for"),
        (15, 17, "had sent"),
        (18, 19, "Amalickiah"),
        (20, 21, "a messenger"),
        (22, 24, "to the queen"),
        (25, 27, "to tell"),
        (28, 30, "her"),
        (31, 32, "was slain"),
        (33, 34, "the king"),
        (35, 37, "by his servants,"),
        (38, 41, "and he pursued"),
        (42, 43, "them"),
        (44, 46, "with his army,"),
        (47, 50, "but did not catch them,"),
        (51, 55, "and they had fled—"),
    ],
    33: [
        (0, 1, "Now,"),
        (2, 4, "when received"),
        (5, 7, "the queen"),
        (8, 9, "this message,"),
        (10, 13, "she sent"),
        (14, 15, "a request"),
        (16, 17, "unto Amalickiah,"),
        (18, 19, "desiring"),
        (20, 22, "him,"),
        (23, 27, "that he spare"),
        (28, 29, "the people of"),
        (30, 31, "the city;"),
        (32, 36, "and she also desired"),
        (37, 39, "of him"),
        (40, 43, "to come in"),
        (44, 46, "unto her;"),
        (47, 51, "and she also desired"),
        (52, 54, "of him"),
        (55, 59, "that he bring"),
        (60, 62, "some witnesses"),
        (63, 65, "together with him"),
        (66, 67, "to testify"),
        (68, 70, "concerning"),
        (71, 73, "the death of"),
        (74, 75, "the king."),
    ],
    34: [
        (0, 3, "And it came to pass that"),
        (4, 4, "took"),
        (5, 6, "Amalickiah"),
        (7, 10, "that very servant"),
        (11, 12, "who slew"),
        (13, 14, "the king,"),
        (15, 18, "and all of them"),
        (19, 22, "who were together"),
        (23, 24, "with him,"),
        (25, 27, "and went"),
        (28, 30, "unto the queen,"),
        (31, 33, "to the place"),
        (34, 38, "where she sat;"),
        (39, 44, "and they all testified"),
        (45, 47, "unto her"),
        (48, 50, "the king"),
        (51, 52, "was slain"),
        (53, 56, "by his own servants;"),
        (57, 62, "and they also said:"),
        (63, 66, "They have fled;"),
        (67, 71, "does not testify"),
        (72, 73, "this thing"),
        (74, 75, "against"),
        (76, 79, "them?"),
        (80, 84, "And thus they"),
        (85, 86, "satisfied"),
        (87, 88, "the queen"),
        (89, 91, "concerning"),
        (92, 94, "the death of"),
        (95, 96, "the king."),
    ],
    35: [
        (0, 3, "And it came to pass that"),
        (4, 4, "sought"),
        (5, 6, "Amalickiah"),
        (7, 9, "the favor of"),
        (10, 11, "the queen,"),
        (12, 15, "and took her"),
        (16, 20, "to be his wife;"),
        (21, 23, "and thus"),
        (24, 26, "by his deceit,"),
        (27, 31, "and by the help of"),
        (32, 35, "his wickedly cunning servants,"),
        (36, 39, "he obtained"),
        (40, 41, "the kingdom;"),
        (42, 42, "yea,"),
        (43, 46, "he was acknowledged"),
        (47, 49, "as king"),
        (50, 53, "in the whole land,"),
        (54, 56, "among"),
        (57, 58, "all the people"),
        (59, 61, "of the Lamanites,"),
        (62, 66, "who consisted"),
        (67, 68, "the Lamanites"),
        (69, 71, "and the Lemuelites"),
        (72, 74, "and the Ishmaelites,"),
        (75, 78, "and all the dissenters"),
        (79, 81, "of the Nephites,"),
        (82, 86, "from the reign of"),
        (87, 87, "Nephi"),
        (88, 91, "even until reaching"),
        (92, 95, "the present time."),
    ],
    36: [
        (0, 1, "Now"),
        (2, 5, "these dissenters,"),
        (6, 9, "because had"),
        (10, 13, "one same teaching"),
        (14, 18, "and one same account"),
        (19, 21, "of the Nephites;"),
        (22, 22, "yea,"),
        (23, 27, "for had been taught"),
        (28, 30, "in the knowledge"),
        (31, 32, "same"),
        (33, 35, "of the Lord,"),
        (36, 39, "nevertheless,"),
        (40, 44, "it is a strange thing"),
        (45, 47, "to tell,"),
        (48, 50, "it was not long"),
        (51, 53, "after passed"),
        (54, 56, "their dissensions"),
        (57, 60, "but they became"),
        (61, 62, "as people"),
        (63, 66, "more hardened"),
        (67, 70, "and unrepentant,"),
        (71, 74, "and more"),
        (75, 75, "wild,"),
        (76, 76, "wicked"),
        (77, 78, "and fierce"),
        (79, 80, "than"),
        (81, 82, "the Lamanites—"),
        (83, 86, "joining together with"),
        (87, 88, "the traditions of"),
        (89, 90, "the Lamanites;"),
        (91, 93, "yielding to"),
        (94, 95, "idleness,"),
        (96, 99, "and all manner of"),
        (100, 102, "impure conduct;"),
        (103, 103, "yea,"),
        (104, 106, "wholly forgetting"),
        (107, 108, "the Lord"),
        (109, 111, "their God."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
