"""Hand-curated TAM-phrase gloss overrides for 1 Nifae 7."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "1nephi"
CHAPTER_NUM = 7
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 5, "I would that"),
        (6, 8, "ye should know,"),
        (9, 12, "after"),
        (13, 13, "had finished"),
        (14, 16, "my father,"),
        (17, 18, "Lehi,"),
        (19, 21, "prophesying"),
        (22, 26, "concerning his seed,"),
        (27, 29, "it came to pass"),
        (30, 32, "again spake"),
        (33, 34, "the Lord"),
        (35, 37, "unto him,"),
        (38, 40, "saying"),
        (41, 43, "was not meet"),
        (44, 46, "for him,"),
        (47, 48, "Lehi,"),
        (49, 51, "that he should take"),
        (52, 55, "his family alone"),
        (56, 58, "into the wilderness;"),
        (59, 59, "but"),
        (60, 61, "should"),
        (62, 64, "his sons"),
        (65, 66, "take"),
        (67, 68, "daughters"),
        (69, 72, "to wife,"),
        (73, 75, "that may"),
        (76, 78, "they raise up"),
        (79, 80, "seed"),
        (81, 83, "unto the Lord"),
        (84, 86, "in the land"),
        (87, 89, "of promise."),
    ],
    2: [
        (0, 3, "And it came to pass"),
        (4, 6, "commanded he"),
        (7, 9, "the Lord"),
        (10, 14, "that I should"),
        (15, 16, "Nephi,"),
        (17, 19, "and my brothers,"),
        (20, 23, "should return"),
        (24, 26, "to the land"),
        (27, 28, "of Jerusalem"),
        (29, 31, "and bring Ishmael"),
        (32, 34, "and his family"),
        (35, 37, "into the wilderness."),
    ],
    3: [
        (0, 3, "And it came to pass"),
        (4, 5, "I,"),
        (6, 7, "Nephi,"),
        (8, 11, "did return,"),
        (12, 15, "with my brothers,"),
        (16, 18, "into the wilderness"),
        (19, 22, "to go up"),
        (23, 24, "to Jerusalem."),
    ],
    4: [
        (0, 3, "And it came to pass"),
        (4, 6, "we went up"),
        (7, 11, "to the house of Ishmael,"),
        (12, 16, "and we obtained favor"),
        (17, 20, "in the sight of Ishmael,"),
        (21, 24, "insomuch that"),
        (25, 29, "we did speak"),
        (30, 32, "unto him"),
        (33, 36, "the words of the Lord."),
    ],
    5: [
        (0, 3, "And it came to pass"),
        (4, 7, "softened the Lord"),
        (8, 11, "the heart of Ishmael,"),
        (12, 15, "and also his household,"),
        (16, 19, "insomuch that"),
        (20, 24, "they did take their journey"),
        (25, 28, "with us"),
        (29, 31, "in the wilderness"),
        (32, 34, "to the tent"),
        (35, 38, "of our father."),
    ],
    6: [
        (0, 3, "And it came to pass"),
        (4, 7, "as we journeyed"),
        (8, 10, "in the wilderness,"),
        (11, 11, "behold"),
        (12, 15, "Laman and Lemuel,"),
        (16, 21, "and two of the daughters of Ishmael,"),
        (22, 27, "and the two sons of Ishmael"),
        (28, 31, "and their families,"),
        (32, 37, "did rebel against us;"),
        (38, 38, "yea,"),
        (39, 41, "against me,"),
        (42, 43, "Nephi,"),
        (44, 45, "and Sam,"),
        (46, 49, "and their father,"),
        (50, 51, "Ishmael,"),
        (52, 54, "and his wife,"),
        (55, 60, "and his other three daughters."),
    ],
    7: [
        (0, 2, "And it came to pass"),
        (3, 5, "in this rebellion,"),
        (6, 9, "they were desirous"),
        (10, 13, "to return"),
        (14, 16, "to the land"),
        (17, 18, "of Jerusalem."),
    ],
    8: [
        (0, 2, "And now,"),
        (3, 4, "I,"),
        (5, 6, "Nephi,"),
        (7, 10, "being grieved"),
        (11, 12, "therefore"),
        (13, 14, "the hardness"),
        (15, 18, "of their hearts,"),
        (19, 20, "therefore"),
        (21, 25, "I did speak"),
        (26, 29, "unto them,"),
        (30, 31, "saying,"),
        (32, 32, "yea,"),
        (33, 35, "even"),
        (36, 37, "unto Laman"),
        (38, 40, "and unto Lemuel:"),
        (41, 41, "Behold,"),
        (42, 47, "ye are mine elder brothers,"),
        (48, 50, "and how is it"),
        (51, 52, "that ye"),
        (53, 54, "are so hard"),
        (55, 58, "in your hearts,"),
        (59, 61, "and so blind"),
        (62, 65, "in your minds,"),
        (66, 70, "that ye have need of me,"),
        (71, 74, "your younger brother,"),
        (75, 79, "to speak"),
        (80, 82, "unto you,"),
        (83, 83, "yea,"),
        (84, 89, "and to set an example for you?"),
    ],
    9: [
        (0, 4, "How is it"),
        (5, 7, "ye have not hearkened"),
        (8, 10, "unto the word"),
        (11, 13, "of the Lord?"),
    ],
    10: [
        (0, 4, "How is it"),
        (5, 8, "ye have forgotten"),
        (9, 11, "ye have seen"),
        (12, 14, "an angel"),
        (15, 17, "of the Lord?"),
    ],
    11: [
        (0, 0, "Yea,"),
        (1, 5, "and how is it"),
        (6, 9, "ye have forgotten"),
        (10, 11, "great things"),
        (12, 16, "hath done the Lord"),
        (17, 19, "for us,"),
        (20, 25, "in delivering us"),
        (26, 29, "out of the hands of Laban,"),
        (30, 37, "and also that we should obtain the records?"),
    ],
    12: [
        (0, 0, "Yea,"),
        (1, 4, "and how is it"),
        (5, 8, "ye have forgotten"),
        (9, 13, "can the Lord"),
        (14, 17, "do all things"),
        (18, 23, "according to his will,"),
        (24, 28, "for the children of men,"),
        (29, 30, "if"),
        (31, 35, "they exercise faith"),
        (36, 38, "in him?"),
        (39, 42, "Wherefore,"),
        (43, 45, "let us be faithful"),
        (46, 48, "unto him."),
    ],
    13: [
        (0, 7, "And if we are faithful unto him,"),
        (8, 11, "we shall obtain"),
        (12, 15, "the land of promise;"),
        (16, 21, "and ye shall know"),
        (22, 27, "at some future time"),
        (28, 32, "shall be fulfilled"),
        (33, 37, "the word of the Lord"),
        (38, 44, "concerning the destruction of Jerusalem;"),
        (45, 49, "for must all be fulfilled"),
        (50, 51, "things"),
        (52, 57, "which hath spoken the Lord"),
        (58, 64, "concerning the destruction of Jerusalem."),
    ],
    14: [
        (0, 1, "For behold,"),
        (2, 7, "is about no longer to strive"),
        (8, 12, "the Spirit of the Lord"),
        (13, 15, "with them;"),
        (16, 17, "for behold,"),
        (18, 21, "they have rejected the prophets,"),
        (22, 29, "and Jeremiah have they cast into prison."),
        (30, 33, "And they have sought"),
        (34, 35, "to take away"),
        (36, 37, "the life"),
        (38, 40, "of my father,"),
        (41, 43, "insomuch"),
        (44, 49, "that they have driven him out"),
        (50, 52, "of the land."),
    ],
    15: [
        (0, 2, "Now behold,"),
        (3, 9, "I say unto you"),
        (10, 14, "if ye will return"),
        (15, 16, "to Jerusalem"),
        (17, 22, "ye shall also perish"),
        (23, 26, "with them."),
        (27, 29, "And now,"),
        (30, 35, "if ye have choice,"),
        (36, 40, "go up to the land,"),
        (41, 43, "and remember"),
        (44, 52, "the words which I speak unto you,"),
        (53, 57, "that if ye go,"),
        (58, 63, "ye shall also perish;"),
        (64, 67, "for thus"),
        (68, 70, "constraineth me"),
        (71, 76, "the Spirit of the Lord"),
        (77, 83, "that I must speak."),
    ],
    16: [
        (0, 3, "And it came to pass"),
        (4, 6, "when had finished"),
        (7, 10, "I had spoken"),
        (11, 12, "Nephi,"),
        (13, 15, "these words,"),
        (16, 18, "to my brothers,"),
        (19, 24, "they were angry with me."),
        (25, 28, "And it came to pass"),
        (29, 33, "they laid their hands"),
        (34, 36, "upon me,"),
        (37, 38, "for behold,"),
        (39, 43, "they were exceedingly angry,"),
        (44, 47, "and they did bind me"),
        (48, 49, "with cords,"),
        (50, 53, "for they sought"),
        (54, 55, "to take away"),
        (56, 57, "my life,"),
        (58, 65, "that they might leave me in the wilderness"),
        (66, 67, "to be devoured"),
        (68, 70, "by wild beasts."),
    ],
    17: [
        (0, 0, "Nevertheless"),
        (1, 3, "it came to pass"),
        (4, 6, "I prayed"),
        (7, 9, "unto the Lord,"),
        (10, 13, "saying:"),
        (14, 16, "O Lord,"),
        (17, 21, "according to my faith"),
        (22, 24, "in thee,"),
        (25, 28, "wilt thou deliver me"),
        (29, 33, "from the hands of my brothers;"),
        (34, 34, "yea,"),
        (35, 39, "give unto me"),
        (40, 41, "strength"),
        (42, 47, "that I may break"),
        (48, 50, "these cords"),
        (51, 54, "wherewith I am bound."),
    ],
    18: [
        (0, 3, "And it came to pass"),
        (4, 7, "when I had said"),
        (8, 9, "these words,"),
        (10, 10, "behold,"),
        (11, 14, "the cords loosed"),
        (15, 17, "from my hands"),
        (18, 20, "and from my feet,"),
        (21, 24, "and I stood"),
        (25, 29, "before my brothers,"),
        (30, 34, "and I spake again"),
        (35, 37, "unto them."),
    ],
    19: [
        (0, 3, "And it came to pass"),
        (4, 8, "they were angry again"),
        (9, 11, "with me,"),
        (12, 13, "and sought"),
        (14, 19, "to lay their hands"),
        (20, 22, "upon me;"),
        (23, 24, "but behold"),
        (25, 27, "one"),
        (28, 31, "of the daughters of Ishmael,"),
        (32, 32, "yea,"),
        (33, 36, "and also her mother,"),
        (37, 43, "and one of the sons of Ishmael,"),
        (44, 49, "did plead with my brothers"),
        (50, 53, "insomuch that"),
        (54, 58, "they did soften their hearts;"),
        (59, 63, "and they did cease"),
        (64, 66, "their striving"),
        (67, 68, "to seek"),
        (69, 70, "my life."),
    ],
    20: [
        (0, 3, "And it came to pass"),
        (4, 5, "they did sorrow"),
        (6, 10, "because of their wickedness,"),
        (11, 13, "insomuch that"),
        (14, 19, "they did bow down before me,"),
        (20, 25, "and did plead with me"),
        (26, 29, "that I would forgive"),
        (30, 33, "them"),
        (34, 35, "for the thing"),
        (36, 38, "they had done"),
        (39, 44, "against me."),
    ],
    21: [
        (0, 3, "And it came to pass"),
        (4, 8, "I did frankly forgive"),
        (9, 12, "them"),
        (13, 15, "for all things"),
        (16, 18, "they had done,"),
        (19, 23, "and I did exhort"),
        (24, 27, "them"),
        (28, 31, "that they would pray"),
        (32, 34, "unto the Lord"),
        (35, 37, "their God"),
        (38, 40, "for forgiveness."),
        (41, 44, "And it came to pass"),
        (45, 48, "that they did so."),
        (49, 53, "And after"),
        (54, 56, "they had prayed"),
        (57, 59, "unto the Lord"),
        (60, 65, "we did continue our journey"),
        (66, 69, "toward the tent"),
        (70, 74, "of our father."),
    ],
    22: [
        (0, 3, "And it came to pass"),
        (4, 6, "we did go down"),
        (7, 9, "to the tent"),
        (10, 13, "of our father."),
        (14, 17, "And after had"),
        (18, 20, "gone down"),
        (21, 22, "I"),
        (23, 25, "and my brothers"),
        (26, 31, "and all the household of Ishmael"),
        (32, 37, "to the tent of my father,"),
        (38, 40, "they did give"),
        (41, 42, "thanks"),
        (43, 45, "unto the Lord"),
        (46, 48, "their God;"),
        (49, 53, "and they did offer"),
        (54, 54, "sacrifice"),
        (55, 57, "and burnt offerings"),
        (58, 60, "unto him."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
