"""
Hand-curated TAM-phrase gloss overrides for Helamana (Helaman) 9 — five men run
to the judgment-seat and find the chief judge slain in his blood as Nephi said;
they are cast into prison, then released, and both they and Nephi are accused of
the murder; Nephi answers the crowd, is charged with being party to the deed,
but reveals a further sign — the murderer Seantum's guilt, confessed word for
word as Nephi foretells — and some begin to believe he is a prophet, even a god.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits applied to bom_books.json before glossing:
    9:6  faamasino—ona        ->  faamasino—        +  ona
    9:7  nofoa-faamasino—ma   ->  nofoa-faamasino—  +  ma

    python3 build_overrides_helaman9.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "helaman"
CHAPTER_NUM = 9

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "Behold,"),
        (1, 2, "now"),
        (3, 5, "it came to pass that"),
        (6, 10, "had finished speaking"),
        (11, 12, "Nephi"),
        (13, 15, "these words,"),
        (16, 20, "there were certain men"),
        (21, 29, "who were among them"),
        (30, 32, "who ran"),
        (33, 35, "to the judgment-seat;"),
        (36, 36, "yea,"),
        (37, 40, "they were five"),
        (41, 45, "who went,"),
        (46, 50, "and they said"),
        (51, 57, "among themselves,"),
        (58, 61, "as they went:"),
    ],
    2: [
        (0, 0, "Behold,"),
        (1, 7, "now we will know of a surety"),
        (8, 11, "whether this man"),
        (12, 14, "is a prophet"),
        (15, 20, "and whether he was commanded"),
        (21, 23, "by God"),
        (24, 26, "to prophesy"),
        (27, 30, "such marvelous things"),
        (31, 34, "unto us."),
        (35, 35, "Behold,"),
        (36, 39, "we do not believe"),
        (40, 44, "he commanded him;"),
        (45, 45, "yea,"),
        (46, 49, "we do not believe"),
        (50, 54, "he is a prophet;"),
        (55, 58, "nevertheless,"),
        (59, 61, "if be true"),
        (62, 63, "this thing"),
        (64, 68, "which he said"),
        (69, 71, "concerning"),
        (72, 74, "the chief judge,"),
        (75, 76, "that"),
        (77, 80, "he is dead,"),
        (81, 85, "then will we believe"),
        (86, 87, "are true"),
        (88, 89, "the other words"),
        (90, 94, "which he said."),
    ],
    3: [
        (0, 4, "And it came to pass that"),
        (5, 7, "they ran"),
        (8, 11, "with their strength,"),
        (12, 16, "and came"),
        (17, 19, "unto the judgment-seat;"),
        (20, 21, "and behold,"),
        (22, 24, "had fallen"),
        (25, 26, "the judge"),
        (27, 29, "to the earth,"),
        (30, 32, "and lay"),
        (33, 35, "in his blood."),
    ],
    4: [
        (0, 3, "And now behold,"),
        (4, 7, "when they saw"),
        (8, 10, "this thing,"),
        (11, 14, "they were astonished exceedingly,"),
        (15, 17, "insomuch that"),
        (18, 20, "they fell"),
        (21, 23, "to the earth;"),
        (24, 24, "for"),
        (25, 28, "they had not believed"),
        (29, 30, "the words"),
        (31, 34, "which spoke"),
        (35, 35, "Nephi"),
        (36, 38, "concerning"),
        (39, 41, "the chief judge."),
    ],
    5: [
        (0, 2, "But now,"),
        (3, 6, "when they saw,"),
        (7, 9, "they believed,"),
        (10, 13, "and came"),
        (14, 15, "the fear"),
        (16, 20, "upon them"),
        (21, 23, "lest come"),
        (24, 28, "upon the people"),
        (29, 30, "all the judgments"),
        (31, 34, "which spoke"),
        (35, 35, "Nephi;"),
        (36, 37, "therefore"),
        (38, 41, "they trembled,"),
        (42, 44, "and fell"),
        (45, 47, "to the earth."),
    ],
    6: [
        (0, 1, "Now,"),
        (2, 6, "at the very time when"),
        (7, 10, "had been murdered"),
        (11, 13, "the judge—"),
        (14, 14, "for"),
        (15, 18, "he was stabbed"),
        (19, 21, "by his brother"),
        (22, 24, "clothed in secrecy,"),
        (25, 29, "and he fled,"),
        (30, 33, "and ran"),
        (34, 34, "the servants"),
        (35, 37, "and told"),
        (38, 39, "the people,"),
        (40, 42, "and cried out"),
        (43, 48, "there was a murderer"),
        (49, 54, "among them;"),
    ],
    7: [
        (0, 1, "And behold"),
        (2, 5, "gathered together"),
        (6, 7, "the people"),
        (8, 10, "themselves"),
        (11, 16, "unto the place where was"),
        (17, 18, "the judgment-seat—"),
        (19, 20, "and behold,"),
        (21, 25, "to their astonishment,"),
        (26, 29, "they saw"),
        (30, 32, "those men"),
        (33, 34, "five,"),
        (35, 39, "who had fallen"),
        (40, 42, "to the earth."),
    ],
    8: [
        (0, 3, "And now behold,"),
        (4, 8, "the people knew not"),
        (9, 10, "anything"),
        (11, 13, "concerning"),
        (14, 17, "the multitude"),
        (18, 22, "who had gathered together"),
        (23, 26, "at the garden of"),
        (27, 27, "Nephi;"),
        (28, 29, "therefore"),
        (30, 34, "they said"),
        (35, 41, "among themselves:"),
        (42, 44, "These men"),
        (45, 48, "are they"),
        (49, 52, "who murdered"),
        (53, 54, "the judge,"),
        (55, 59, "and were smitten they"),
        (60, 62, "by God"),
        (63, 67, "that they could not"),
        (68, 70, "flee away"),
        (71, 75, "from us."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 7, "they seized them,"),
        (8, 11, "and bound them"),
        (12, 15, "and cast them"),
        (16, 18, "into prison."),
        (19, 22, "And there was"),
        (23, 24, "a proclamation"),
        (25, 28, "sent abroad"),
        (29, 30, "that"),
        (31, 32, "was slain"),
        (33, 34, "the judge,"),
        (35, 37, "and were taken"),
        (38, 42, "those who slew him"),
        (43, 44, "and cast"),
        (45, 47, "into prison."),
    ],
    10: [
        (0, 2, "And it came to pass"),
        (3, 8, "on the following day"),
        (9, 11, "assembled together"),
        (12, 14, "the people"),
        (15, 17, "themselves"),
        (18, 19, "to mourn"),
        (20, 21, "and to fast,"),
        (22, 25, "at the burial of"),
        (26, 29, "the great chief judge"),
        (30, 33, "who had been slain."),
    ],
    11: [
        (0, 4, "And thus also"),
        (5, 7, "gathered together"),
        (8, 8, "the judges"),
        (9, 13, "who were"),
        (14, 17, "at the garden of"),
        (18, 18, "Nephi,"),
        (19, 20, "and heard"),
        (21, 23, "his words,"),
        (24, 26, "at the burial."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 5, "they questioned"),
        (6, 7, "the people,"),
        (8, 9, "saying:"),
        (10, 14, "Where are"),
        (15, 16, "the five"),
        (17, 21, "who were sent"),
        (22, 23, "to inquire"),
        (24, 26, "concerning"),
        (27, 29, "the chief judge"),
        (30, 34, "whether he was dead?"),
        (35, 39, "And they answered"),
        (40, 42, "and said:"),
        (43, 45, "Concerning"),
        (46, 47, "this five"),
        (48, 53, "whom ye say"),
        (54, 57, "ye sent,"),
        (58, 61, "we know not;"),
        (62, 67, "but there are five"),
        (68, 73, "who slew him,"),
        (74, 76, "whom we have cast"),
        (77, 79, "into prison."),
    ],
    13: [
        (0, 3, "And it came to pass that"),
        (4, 5, "the judges desired"),
        (6, 9, "that they be brought;"),
        (10, 14, "and they were brought,"),
        (15, 16, "and behold"),
        (17, 20, "they were"),
        (21, 23, "the five"),
        (24, 28, "who were sent;"),
        (29, 30, "and behold"),
        (31, 34, "they were questioned"),
        (35, 36, "by the judges"),
        (37, 40, "that they might know"),
        (41, 43, "concerning"),
        (44, 45, "the matter,"),
        (46, 50, "and they related"),
        (51, 54, "unto them"),
        (55, 59, "all that they did,"),
        (60, 61, "saying:"),
    ],
    14: [
        (0, 2, "We ran"),
        (3, 5, "and came"),
        (6, 11, "to the place where was"),
        (12, 13, "the judgment-seat,"),
        (14, 19, "and when we saw"),
        (20, 22, "all things"),
        (23, 29, "even as testified"),
        (30, 30, "Nephi,"),
        (31, 34, "we were astonished"),
        (35, 38, "insomuch that"),
        (39, 41, "we fell"),
        (42, 44, "to the earth;"),
        (45, 50, "and when we recovered from"),
        (51, 53, "our astonishment,"),
        (54, 54, "behold,"),
        (55, 59, "they cast us"),
        (60, 62, "into prison."),
    ],
    15: [
        (0, 1, "Now,"),
        (2, 4, "concerning"),
        (5, 7, "the murder of"),
        (8, 9, "this man,"),
        (10, 13, "we know not"),
        (14, 16, "who"),
        (17, 18, "did it;"),
        (19, 24, "and this is only"),
        (25, 27, "the thing"),
        (28, 30, "we know,"),
        (31, 33, "we ran"),
        (34, 36, "and came"),
        (37, 39, "according to"),
        (40, 42, "your desire,"),
        (43, 44, "and behold,"),
        (45, 48, "he was dead,"),
        (49, 51, "according to"),
        (52, 54, "the words of Nephi."),
    ],
    16: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 7, "expounded"),
        (8, 9, "the matter"),
        (10, 11, "the judges"),
        (12, 13, "unto the people,"),
        (14, 15, "and cried out"),
        (16, 19, "against Nephi,"),
        (20, 22, "saying:"),
        (23, 23, "Behold,"),
        (24, 26, "we know"),
        (27, 29, "perhaps made"),
        (30, 32, "this Nephi"),
        (33, 34, "an agreement"),
        (35, 38, "together with someone"),
        (39, 42, "to slay the judge,"),
        (43, 46, "and afterward"),
        (47, 50, "he declare it"),
        (51, 54, "unto us,"),
        (55, 60, "that he might"),
        (61, 64, "convert us"),
        (65, 67, "unto his faith,"),
        (68, 74, "that he might raise up"),
        (75, 77, "himself"),
        (78, 81, "as a great man,"),
        (82, 83, "chosen"),
        (84, 86, "by God,"),
        (87, 90, "and a prophet."),
    ],
    17: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 8, "we will expose"),
        (9, 10, "this man,"),
        (11, 17, "and he shall declare"),
        (18, 19, "his fault"),
        (20, 22, "and make known"),
        (23, 26, "unto us"),
        (27, 29, "the true man"),
        (30, 33, "who slew this judge."),
    ],
    18: [
        (0, 3, "And it came to pass that"),
        (4, 4, "were freed"),
        (5, 6, "the five"),
        (7, 10, "on the day of"),
        (11, 12, "the burial."),
        (13, 16, "Nevertheless,"),
        (17, 19, "they rebuked"),
        (20, 20, "the judges"),
        (21, 22, "in the words"),
        (23, 27, "which they spoke"),
        (28, 31, "against Nephi,"),
        (32, 34, "and they contended"),
        (35, 38, "with them each one,"),
        (39, 43, "insomuch that"),
        (44, 46, "they confounded them."),
    ],
    19: [
        (0, 3, "Nevertheless,"),
        (4, 7, "they commanded"),
        (8, 10, "that Nephi be taken"),
        (11, 12, "and bound"),
        (13, 14, "and brought"),
        (15, 17, "before"),
        (18, 21, "the multitude,"),
        (22, 25, "and they began to"),
        (26, 29, "they question him"),
        (30, 32, "in various ways"),
        (33, 36, "that they might"),
        (37, 40, "entrap him,"),
        (41, 44, "that they might"),
        (45, 48, "condemn him"),
        (49, 51, "to death—"),
    ],
    20: [
        (0, 2, "Saying"),
        (3, 5, "unto him:"),
        (6, 10, "Thou art a conspirator;"),
        (11, 14, "who is this man"),
        (15, 18, "that slew him?"),
        (19, 20, "Now"),
        (21, 23, "tell"),
        (24, 27, "us,"),
        (28, 30, "and acknowledge"),
        (31, 32, "thy fault;"),
        (33, 34, "saying:"),
        (35, 35, "Behold"),
        (36, 38, "here is money;"),
        (39, 46, "and we will also grant"),
        (47, 49, "unto thee"),
        (50, 51, "thy life"),
        (52, 57, "if thou tell"),
        (58, 61, "us,"),
        (62, 64, "and acknowledge"),
        (65, 67, "the agreement"),
        (68, 70, "which thou made"),
        (71, 73, "together with him."),
    ],
    21: [
        (0, 0, "But"),
        (1, 3, "said"),
        (4, 4, "Nephi"),
        (5, 8, "unto them:"),
        (9, 9, "O,"),
        (10, 12, "ye fools,"),
        (13, 17, "ye who are uncircumcised"),
        (18, 20, "in the heart,"),
        (21, 23, "ye blind,"),
        (24, 28, "and ye hardened people,"),
        (29, 32, "do ye know"),
        (33, 37, "how long"),
        (38, 43, "will suffer you"),
        (44, 46, "the Lord"),
        (47, 49, "your God"),
        (50, 54, "that ye continue"),
        (55, 57, "in this way"),
        (58, 61, "of your sin?"),
    ],
    22: [
        (0, 0, "O,"),
        (1, 7, "ye ought"),
        (8, 9, "to begin"),
        (10, 11, "ye howl"),
        (12, 13, "and mourn,"),
        (14, 15, "because of"),
        (16, 18, "the great destruction"),
        (19, 22, "which awaits"),
        (23, 26, "at this time"),
        (27, 29, "you,"),
        (30, 31, "except"),
        (32, 34, "ye repent."),
    ],
    23: [
        (0, 0, "Behold"),
        (1, 4, "ye say"),
        (5, 7, "I agreed"),
        (8, 11, "with a man"),
        (12, 15, "that he should murder"),
        (16, 16, "Seezoram,"),
        (17, 20, "our chief judge."),
        (21, 22, "But behold,"),
        (23, 26, "I say"),
        (27, 29, "unto you,"),
        (30, 34, "ye say thus"),
        (35, 39, "because I testified"),
        (40, 42, "unto you"),
        (43, 48, "that ye might know"),
        (49, 53, "concerning this thing;"),
        (54, 54, "yea,"),
        (55, 59, "I told"),
        (60, 61, "this thing"),
        (62, 64, "as a witness"),
        (65, 67, "unto you,"),
        (68, 70, "I know"),
        (71, 73, "concerning"),
        (74, 75, "the wickedness"),
        (76, 79, "and abominations"),
        (80, 84, "which are among"),
        (85, 87, "you."),
    ],
    24: [
        (0, 1, "And because"),
        (2, 5, "I have made known"),
        (6, 7, "this thing,"),
        (8, 11, "ye say"),
        (12, 14, "I agreed"),
        (15, 18, "with a man"),
        (19, 21, "that he do"),
        (22, 23, "this thing;"),
        (24, 24, "yea,"),
        (25, 25, "because"),
        (26, 29, "I showed"),
        (30, 32, "unto you"),
        (33, 34, "this sign"),
        (35, 39, "ye are angry"),
        (40, 42, "with me,"),
        (43, 44, "and seek"),
        (45, 46, "to destroy"),
        (47, 48, "my life."),
    ],
    25: [
        (0, 3, "And now behold,"),
        (4, 9, "I will show"),
        (10, 12, "unto you"),
        (13, 15, "another sign,"),
        (16, 17, "and see"),
        (18, 24, "whether ye will seek"),
        (25, 27, "to destroy me"),
        (28, 30, "in this thing."),
    ],
    26: [
        (0, 0, "Behold"),
        (1, 4, "I say"),
        (5, 7, "unto you:"),
        (8, 9, "Go to"),
        (10, 12, "the house of"),
        (13, 13, "Seantum,"),
        (14, 18, "who is the brother of"),
        (19, 19, "Seezoram,"),
        (20, 22, "and say"),
        (23, 25, "unto him—"),
    ],
    27: [
        (0, 3, "Did agree"),
        (4, 4, "Nephi,"),
        (5, 7, "the false prophet,"),
        (8, 13, "who prophesies"),
        (14, 17, "so much evil"),
        (18, 20, "concerning this people,"),
        (21, 23, "with thee,"),
        (24, 26, "in an agreement"),
        (27, 30, "wherein thou slew"),
        (31, 31, "Seezoram,"),
        (32, 34, "thy brother?"),
    ],
    28: [
        (0, 1, "And behold,"),
        (2, 8, "he shall say"),
        (9, 11, "unto you,"),
        (12, 13, "Nay."),
    ],
    29: [
        (0, 4, "And say ye"),
        (5, 7, "unto him:"),
        (8, 10, "Didst thou murder"),
        (11, 12, "thy brother?"),
    ],
    30: [
        (0, 6, "And he shall stand"),
        (7, 9, "with fear,"),
        (10, 12, "and not knowing"),
        (13, 17, "what word to say."),
        (18, 19, "And behold,"),
        (20, 26, "he shall deny"),
        (27, 29, "unto you;"),
        (30, 36, "and he shall act"),
        (37, 40, "as if astonished;"),
        (41, 44, "nevertheless,"),
        (45, 50, "he shall declare"),
        (51, 53, "unto you"),
        (54, 57, "that he is clean."),
    ],
    31: [
        (0, 1, "But behold,"),
        (2, 6, "ye examine him,"),
        (7, 12, "and ye shall find"),
        (13, 14, "the blood"),
        (15, 20, "upon the lower part of"),
        (21, 23, "his cloak."),
    ],
    32: [
        (0, 3, "And when"),
        (4, 5, "ye have seen"),
        (6, 8, "this thing,"),
        (9, 12, "ye shall say:"),
        (13, 15, "From whence"),
        (16, 17, "this blood?"),
        (18, 22, "Do we not know"),
        (23, 26, "this is the blood"),
        (27, 29, "of thy brother?"),
    ],
    33: [
        (0, 2, "And then"),
        (3, 9, "he shall tremble,"),
        (10, 12, "and appear"),
        (13, 14, "pale,"),
        (15, 17, "even as if"),
        (18, 21, "death had come"),
        (22, 25, "upon him."),
    ],
    34: [
        (0, 3, "And then"),
        (4, 7, "ye shall say"),
        (8, 10, "unto him:"),
        (11, 12, "Because of"),
        (13, 14, "this fear"),
        (15, 17, "and this paleness"),
        (18, 21, "which has come"),
        (22, 24, "upon thy face,"),
        (25, 25, "behold,"),
        (26, 28, "we know"),
        (29, 31, "thou art guilty."),
    ],
    35: [
        (0, 2, "And then"),
        (3, 7, "shall come"),
        (8, 11, "a greater fear"),
        (12, 14, "upon him;"),
        (15, 21, "and then he shall confess"),
        (22, 24, "unto you,"),
        (25, 29, "and deny no more"),
        (30, 34, "that he himself did"),
        (35, 37, "this murder."),
    ],
    36: [
        (0, 2, "And then"),
        (3, 9, "he shall say"),
        (10, 12, "unto you,"),
        (13, 14, "that I,"),
        (15, 16, "Nephi,"),
        (17, 20, "know nothing"),
        (21, 22, "anything"),
        (23, 25, "concerning"),
        (26, 27, "the matter"),
        (28, 29, "except"),
        (30, 32, "was given"),
        (33, 35, "unto me"),
        (36, 39, "by the power of"),
        (40, 41, "God."),
        (42, 48, "And then ye shall know"),
        (49, 54, "that I am an honest man,"),
        (55, 59, "and I was sent"),
        (60, 62, "unto you"),
        (63, 65, "from God."),
    ],
    37: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they went"),
        (7, 8, "and did,"),
        (9, 14, "even according as"),
        (15, 17, "said"),
        (18, 18, "Nephi"),
        (19, 22, "unto them."),
        (23, 24, "And behold,"),
        (25, 26, "were true"),
        (27, 27, "the words"),
        (28, 32, "which he said;"),
        (33, 33, "for"),
        (34, 37, "according to the words"),
        (38, 41, "he denied;"),
        (42, 47, "and also according to the words"),
        (48, 52, "he confessed."),
    ],
    38: [
        (0, 4, "And he was brought"),
        (5, 6, "to prove"),
        (7, 9, "that he himself"),
        (10, 14, "was that murderer,"),
        (15, 17, "insomuch that"),
        (18, 19, "were set free"),
        (20, 21, "the five,"),
        (22, 25, "and also Nephi."),
    ],
    39: [
        (0, 5, "And there were some"),
        (6, 8, "of the Nephites"),
        (9, 12, "who believed"),
        (13, 16, "on the words of Nephi;"),
        (17, 23, "and there were also some,"),
        (24, 27, "who believed"),
        (28, 29, "because of"),
        (30, 32, "the testimony of"),
        (33, 34, "the five,"),
        (35, 35, "for"),
        (36, 39, "they were converted"),
        (40, 43, "while they were"),
        (44, 46, "in prison."),
    ],
    40: [
        (0, 2, "And now"),
        (3, 7, "there were some"),
        (8, 12, "among the people,"),
        (13, 17, "who said"),
        (18, 22, "Nephi is a prophet."),
    ],
    41: [
        (0, 5, "And there were others"),
        (6, 10, "who said:"),
        (11, 11, "Behold,"),
        (12, 16, "he is a god,"),
        (17, 17, "for"),
        (18, 19, "except"),
        (20, 24, "he were a god"),
        (25, 31, "he could not know"),
        (32, 33, "all things."),
        (34, 35, "For behold,"),
        (36, 39, "he told"),
        (40, 43, "us"),
        (44, 45, "the thoughts of"),
        (46, 48, "our hearts,"),
        (49, 54, "and he also told"),
        (55, 55, "things"),
        (56, 59, "us;"),
        (60, 65, "and he even made known"),
        (66, 68, "unto us"),
        (69, 71, "the true man"),
        (72, 73, "who murdered"),
        (74, 77, "our chief judge."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
