"""Hand-curated TAM-phrase gloss overrides for Mosaea 25 — the people gather at Zarahemla; the church of God is established through the land.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
subject `o ia` / agent `e ia` absorbed into the verb cluster, never split as a
bare "he" (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` fillers when a PP/object follows (rule 1), `mafai ona`/`ina ia`/
`ina ua` bound (rules 13/15), vocative `e`/`E …e` folded as "O X" (rule 12),
directional "forth" dropped (rule 12a). No pronoun/TAM word injected into a cell
whose span lacks that token; no content word repeats across adjacent cells
(except authentic Samoan doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah25.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 25
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 4, "caused"),
        (5, 7, "the king"),
        (8, 9, "Mosiah"),
        (10, 12, "that should be gathered together"),
        (13, 14, "the people."),
    ],
    2: [
        (0, 1, "Now"),
        (2, 5, "there were not so many"),
        (6, 6, "of the children"),
        (7, 8, "of Nephi,"),
        (9, 9, "or"),
        (10, 12, "so many"),
        (13, 14, "of them"),
        (15, 16, "who"),
        (17, 18, "descended"),
        (19, 21, "from Nephi,"),
        (22, 24, "as"),
        (25, 25, "the people"),
        (26, 28, "who were"),
        (29, 30, "of Zarahemla,"),
        (31, 32, "who"),
        (33, 34, "descended"),
        (35, 37, "from Mulek,"),
        (38, 38, "and"),
        (39, 40, "those"),
        (41, 42, "who"),
        (43, 45, "came"),
        (46, 48, "with him"),
        (49, 51, "into the wilderness."),
    ],
    3: [
        (0, 0, "And"),
        (1, 4, "there were not so many"),
        (5, 5, "of the people"),
        (6, 7, "of Nephi"),
        (8, 9, "and of the people"),
        (10, 11, "of Zarahemla"),
        (12, 14, "as"),
        (15, 17, "the Lamanites"),
        (18, 20, "who were;"),
        (21, 21, "yea,"),
        (22, 25, "were not equal to"),
        (26, 27, "half"),
        (28, 30, "of the Lamanites"),
        (31, 33, "their number."),
    ],
    4: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "were assembled together"),
        (6, 7, "all the people"),
        (8, 9, "of Nephi,"),
        (10, 10, "and"),
        (11, 13, "all the people also"),
        (14, 15, "of Zarahemla,"),
        (16, 16, "and"),
        (17, 20, "they were gathered together"),
        (21, 23, "in bodies"),
        (24, 25, "two."),
    ],
    5: [
        (0, 3, "And it came to pass"),
        (4, 5, "did read"),
        (6, 7, "Mosiah,"),
        (8, 10, "and caused"),
        (11, 13, "to be read"),
        (14, 16, "to his people,"),
        (17, 17, "the records"),
        (18, 19, "of Zeniff;"),
        (20, 20, "yea,"),
        (21, 25, "he read"),
        (26, 27, "the records of"),
        (28, 29, "the people"),
        (30, 31, "of Zeniff,"),
        (32, 34, "from the time"),
        (35, 38, "they left"),
        (39, 40, "the land"),
        (41, 42, "of Zarahemla"),
        (43, 45, "until"),
        (46, 49, "they returned again."),
    ],
    6: [
        (0, 0, "And"),
        (1, 6, "he also read"),
        (7, 8, "the account"),
        (9, 10, "of Alma"),
        (11, 13, "and his brethren,"),
        (14, 14, "and"),
        (15, 18, "all their afflictions,"),
        (19, 21, "from the time"),
        (22, 25, "they left"),
        (26, 27, "the land"),
        (28, 29, "of Zarahemla"),
        (30, 31, "until"),
        (32, 34, "the time"),
        (35, 40, "they returned again."),
    ],
    7: [
        (0, 0, "And"),
        (1, 2, "now,"),
        (3, 6, "when had made an end"),
        (7, 8, "of reading"),
        (9, 10, "Mosiah"),
        (11, 11, "the records,"),
        (12, 13, "were struck"),
        (14, 15, "his people"),
        (16, 17, "who"),
        (18, 20, "tarried"),
        (21, 23, "in the land"),
        (24, 26, "with wonder"),
        (27, 29, "and amazement."),
    ],
    8: [
        (0, 0, "For"),
        (1, 4, "they knew not"),
        (5, 6, "what"),
        (7, 10, "to think;"),
        (11, 11, "for"),
        (12, 13, "when"),
        (14, 16, "they beheld"),
        (17, 19, "those"),
        (20, 21, "that"),
        (22, 23, "had been delivered"),
        (24, 26, "out of bondage"),
        (27, 28, "were filled"),
        (29, 30, "they"),
        (31, 35, "with exceedingly great joy."),
    ],
    9: [
        (0, 2, "And again,"),
        (3, 4, "when"),
        (5, 7, "they thought"),
        (8, 11, "of their brethren"),
        (12, 13, "who"),
        (14, 15, "had been slain"),
        (16, 18, "by the Lamanites"),
        (19, 20, "were filled"),
        (21, 22, "they"),
        (23, 25, "with sorrow,"),
        (26, 29, "and even shed"),
        (30, 32, "their tears"),
        (33, 34, "many"),
        (35, 37, "of sorrow."),
    ],
    10: [
        (0, 2, "And again,"),
        (3, 4, "when"),
        (5, 7, "they thought"),
        (8, 10, "of the immediate"),
        (11, 13, "goodness"),
        (14, 16, "of God,"),
        (17, 17, "and"),
        (18, 19, "his power"),
        (20, 22, "in delivering"),
        (23, 24, "Alma"),
        (25, 25, "and"),
        (26, 27, "his brethren"),
        (28, 30, "out of the hands of"),
        (31, 32, "the Lamanites"),
        (33, 35, "and of bondage,"),
        (36, 38, "they did raise"),
        (39, 41, "their voices"),
        (42, 44, "and give"),
        (45, 46, "thanks"),
        (47, 49, "to God."),
    ],
    11: [
        (0, 2, "And again,"),
        (3, 4, "when"),
        (5, 7, "they thought"),
        (8, 10, "upon the Lamanites,"),
        (11, 12, "who"),
        (13, 16, "were their brethren,"),
        (17, 19, "concerning"),
        (20, 22, "their state"),
        (23, 23, "sinful"),
        (24, 26, "and polluted,"),
        (27, 28, "were filled"),
        (29, 30, "they"),
        (31, 33, "with pain"),
        (34, 36, "and anguish"),
        (37, 39, "for the welfare"),
        (40, 43, "of their souls."),
    ],
    12: [
        (0, 3, "And it came to pass"),
        (4, 6, "those"),
        (7, 8, "who"),
        (9, 10, "were the children"),
        (11, 12, "of Amulon"),
        (13, 15, "and his brethren,"),
        (16, 17, "who"),
        (18, 20, "had taken"),
        (21, 21, "the daughters"),
        (22, 24, "of the Lamanites"),
        (25, 27, "to be"),
        (28, 30, "their wives,"),
        (31, 33, "were displeased"),
        (34, 36, "with the conduct of"),
        (37, 39, "their fathers,"),
        (40, 40, "and"),
        (41, 44, "they would no longer"),
        (45, 47, "be called"),
        (48, 49, "they"),
        (50, 52, "by the names of"),
        (53, 55, "their fathers;"),
        (56, 57, "therefore"),
        (58, 61, "they took"),
        (62, 66, "upon themselves"),
        (67, 69, "the name of"),
        (70, 70, "Nephi,"),
        (71, 72, "that"),
        (73, 74, "might"),
        (75, 77, "they be called"),
        (78, 79, "the children"),
        (80, 81, "of Nephi"),
        (82, 83, "and be numbered"),
        (84, 85, "they"),
        (86, 88, "among"),
        (89, 91, "those who are called"),
        (92, 94, "Nephites."),
    ],
    13: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 4, "were numbered"),
        (5, 6, "all the people"),
        (7, 8, "of Zarahemla"),
        (9, 10, "with"),
        (11, 12, "the Nephites,"),
        (13, 13, "and"),
        (14, 15, "was done"),
        (16, 17, "this"),
        (18, 18, "because"),
        (19, 22, "had not been conferred"),
        (23, 24, "the kingdom"),
        (25, 27, "upon"),
        (28, 29, "any"),
        (30, 31, "but only"),
        (32, 33, "those"),
        (34, 35, "who"),
        (36, 37, "descended"),
        (38, 40, "from Nephi."),
    ],
    14: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "it came to pass"),
        (6, 9, "when had made an end"),
        (10, 11, "Mosiah"),
        (12, 14, "of speaking"),
        (15, 17, "and reading"),
        (18, 20, "to the people,"),
        (21, 24, "he desired"),
        (25, 28, "that should also speak"),
        (29, 29, "Alma"),
        (30, 32, "to the people."),
    ],
    15: [
        (0, 0, "And"),
        (1, 3, "did speak"),
        (4, 4, "Alma"),
        (5, 8, "unto them,"),
        (9, 10, "when they"),
        (11, 12, "were assembled together"),
        (13, 15, "in bodies"),
        (16, 16, "large,"),
        (17, 17, "and"),
        (18, 22, "he went"),
        (23, 26, "from one body"),
        (27, 29, "to another,"),
        (30, 32, "preaching"),
        (33, 34, "unto the people"),
        (35, 36, "repentance"),
        (37, 37, "and"),
        (38, 39, "faith"),
        (40, 42, "on the Lord."),
    ],
    16: [
        (0, 0, "And"),
        (1, 5, "he did exhort"),
        (6, 7, "the people"),
        (8, 9, "of Limhi"),
        (10, 10, "and"),
        (11, 12, "his brethren,"),
        (13, 15, "all those"),
        (16, 18, "that had been delivered"),
        (19, 21, "out of bondage,"),
        (22, 23, "that"),
        (24, 25, "they should remember"),
        (26, 29, "that it was the Lord"),
        (30, 31, "that did deliver"),
        (32, 33, "them."),
    ],
    17: [
        (0, 3, "And it came to pass"),
        (4, 6, "after had finished"),
        (7, 8, "teaching"),
        (9, 10, "Alma"),
        (11, 12, "the people"),
        (13, 14, "things"),
        (15, 16, "many,"),
        (17, 20, "and had made an end"),
        (21, 23, "of speaking"),
        (24, 27, "to them,"),
        (28, 30, "that"),
        (31, 31, "was desirous"),
        (32, 33, "the king"),
        (34, 35, "Limhi"),
        (36, 39, "that he might be baptized;"),
        (40, 40, "and"),
        (41, 43, "were desirous also"),
        (44, 46, "all his people"),
        (47, 48, "that be baptized"),
        (49, 50, "they."),
    ],
    18: [
        (0, 1, "Therefore"),
        (2, 5, "did go forth"),
        (6, 6, "Alma"),
        (7, 9, "into"),
        (10, 11, "the water"),
        (12, 13, "and did baptize"),
        (14, 15, "them;"),
        (16, 16, "yea,"),
        (17, 20, "he did baptize"),
        (21, 22, "them"),
        (23, 25, "after the manner"),
        (26, 30, "he did baptize"),
        (31, 32, "his brethren"),
        (33, 34, "in the waters"),
        (35, 36, "of Mormon;"),
        (37, 37, "yea,"),
        (38, 38, "and"),
        (39, 41, "as many"),
        (42, 43, "as"),
        (44, 47, "he did baptize"),
        (48, 49, "did belong"),
        (50, 52, "to the church"),
        (53, 55, "of God;"),
        (56, 56, "and"),
        (57, 59, "they did"),
        (60, 61, "this"),
        (62, 63, "because of"),
        (64, 66, "their belief"),
        (67, 68, "on the words"),
        (69, 70, "of Alma."),
    ],
    19: [
        (0, 3, "And it came to pass"),
        (4, 5, "granted"),
        (6, 8, "the king"),
        (9, 10, "Mosiah"),
        (11, 12, "unto Alma"),
        (13, 16, "that he might establish"),
        (17, 18, "churches"),
        (19, 22, "throughout all the land"),
        (23, 24, "of Zarahemla;"),
        (25, 27, "and gave"),
        (28, 30, "him"),
        (31, 32, "power"),
        (33, 35, "to ordain"),
        (36, 36, "priests"),
        (37, 38, "and teachers"),
        (39, 41, "over"),
        (42, 43, "every church."),
    ],
    20: [
        (0, 1, "Now"),
        (2, 3, "was done"),
        (4, 5, "this"),
        (6, 7, "because of"),
        (8, 10, "the great number"),
        (11, 12, "of people"),
        (13, 15, "could not"),
        (16, 17, "be governed"),
        (18, 20, "all"),
        (21, 23, "by a teacher"),
        (24, 25, "single;"),
        (26, 28, "neither could"),
        (29, 32, "they all"),
        (33, 34, "hear"),
        (35, 36, "the word"),
        (37, 39, "of God"),
        (40, 42, "in an assembly"),
        (43, 44, "one;"),
    ],
    21: [
        (0, 1, "Therefore"),
        (2, 6, "they did assemble together"),
        (7, 9, "themselves"),
        (10, 12, "in bodies"),
        (13, 13, "different,"),
        (14, 15, "being called"),
        (16, 17, "churches;"),
        (18, 19, "had"),
        (20, 21, "every church"),
        (22, 22, "with"),
        (23, 25, "their priests"),
        (26, 26, "and"),
        (27, 29, "their teachers,"),
        (30, 30, "and"),
        (31, 32, "every"),
        (33, 34, "priest"),
        (35, 37, "preaching"),
        (38, 39, "the word"),
        (40, 42, "according as"),
        (43, 44, "was delivered"),
        (45, 47, "to him"),
        (48, 50, "by the mouth"),
        (51, 52, "of Alma."),
    ],
    22: [
        (0, 0, "And"),
        (1, 2, "thus,"),
        (3, 5, "notwithstanding"),
        (6, 7, "were many"),
        (8, 8, "churches"),
        (9, 11, "there were"),
        (12, 12, "yet"),
        (13, 16, "they all"),
        (17, 19, "the church"),
        (20, 21, "one;"),
        (22, 22, "yea,"),
        (23, 26, "even the church"),
        (27, 29, "of God;"),
        (30, 30, "for"),
        (31, 34, "there was nothing"),
        (35, 36, "preached"),
        (37, 39, "in all the churches"),
        (40, 41, "except"),
        (42, 43, "repentance"),
        (44, 44, "and"),
        (45, 46, "faith"),
        (47, 49, "in God."),
    ],
    23: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 4, "seven"),
        (5, 5, "churches"),
        (6, 8, "there were"),
        (9, 11, "in the land"),
        (12, 13, "of Zarahemla."),
        (14, 14, "And"),
        (15, 17, "it came to pass"),
        (18, 21, "whosoever"),
        (22, 23, "were desirous"),
        (24, 26, "to take"),
        (27, 30, "upon them"),
        (31, 33, "the name of"),
        (34, 34, "Christ,"),
        (35, 36, "or of"),
        (37, 38, "God,"),
        (39, 41, "they did join"),
        (42, 43, "the churches"),
        (44, 46, "of God."),
    ],
    24: [
        (0, 0, "And"),
        (1, 2, "were called"),
        (3, 4, "they"),
        (5, 7, "the people"),
        (8, 10, "of God."),
        (11, 11, "And"),
        (12, 14, "did pour out"),
        (15, 17, "the Lord"),
        (18, 19, "his Spirit"),
        (20, 22, "upon"),
        (23, 24, "them,"),
        (25, 25, "and"),
        (26, 27, "were blessed"),
        (28, 29, "they,"),
        (30, 31, "and prospered"),
        (32, 34, "in the land."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
