"""
Hand-curated TAM-phrase gloss overrides for Helamana (Helaman) 7 — Nephi
returns from the land northward to find the Gadianton robbers in the
judgment-seats and the Nephites ripening in wickedness; in the anguish of his
soul he pours out his heart in prayer upon his garden tower by the highway, and
the gathering multitude hears his lamentation over their fallen state and his
call to repentance.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-split applied to bom_books.json before glossing:
    7:4  nofoa-faamasino—ona  ->  nofoa-faamasino—  +  ona

    python3 build_overrides_helaman7.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "helaman"
CHAPTER_NUM = 7

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "Behold,"),
        (1, 2, "now"),
        (3, 5, "it came to pass that"),
        (6, 9, "in the year"),
        (10, 13, "sixty and ninth"),
        (14, 17, "of the reign of"),
        (18, 18, "the judges"),
        (19, 21, "over the Nephites,"),
        (22, 26, "returned"),
        (27, 27, "Nephi,"),
        (28, 30, "the son of"),
        (31, 31, "Helaman,"),
        (32, 35, "to the land of"),
        (36, 36, "Zarahemla"),
        (37, 41, "from the land northward."),
    ],
    2: [
        (0, 0, "For"),
        (1, 5, "he had gone"),
        (6, 7, "abroad"),
        (8, 11, "among the people"),
        (12, 15, "who were in"),
        (16, 19, "the land northward,"),
        (20, 23, "and he preached"),
        (24, 26, "the word of"),
        (27, 28, "God"),
        (29, 32, "unto them,"),
        (33, 37, "and he prophesied"),
        (38, 40, "many things"),
        (41, 44, "unto them;"),
    ],
    3: [
        (0, 3, "And they rejected"),
        (4, 6, "all his words,"),
        (7, 9, "insomuch that"),
        (10, 15, "he could not remain"),
        (16, 21, "among them,"),
        (22, 28, "but he returned again"),
        (29, 31, "unto the land"),
        (32, 36, "of his birth."),
    ],
    4: [
        (0, 4, "And when he saw"),
        (5, 8, "the people were"),
        (9, 12, "in a state of"),
        (13, 16, "such awful wickedness,"),
        (17, 19, "and were occupied"),
        (20, 23, "by those robbers"),
        (24, 25, "of Gadianton"),
        (26, 26, "the judgment-seats—"),
        (27, 27, "for"),
        (28, 31, "they had seized by force"),
        (32, 37, "the power and authority of"),
        (38, 39, "the land;"),
        (40, 42, "and laid aside"),
        (43, 44, "the commandments of"),
        (45, 46, "God,"),
        (47, 52, "and not in the least"),
        (53, 57, "was this thing right"),
        (58, 60, "before him;"),
        (61, 64, "they did not do"),
        (65, 67, "any justice"),
        (68, 72, "unto the children of men;"),
    ],
    5: [
        (0, 2, "They condemned"),
        (3, 4, "the righteous"),
        (5, 6, "because of"),
        (7, 9, "their righteousness;"),
        (10, 12, "they let"),
        (13, 15, "the guilty"),
        (16, 19, "and the wicked"),
        (20, 22, "go unpunished"),
        (23, 24, "because of"),
        (25, 27, "their money;"),
        (28, 30, "and moreover"),
        (31, 34, "that they hold"),
        (35, 35, "office"),
        (36, 41, "at the head of government,"),
        (42, 44, "they rule"),
        (45, 47, "and do"),
        (48, 50, "according to"),
        (51, 53, "their wills,"),
        (54, 57, "that they might obtain"),
        (58, 59, "the riches"),
        (60, 62, "and glory of"),
        (63, 65, "the world,"),
        (66, 66, "and,"),
        (67, 69, "moreover,"),
        (70, 75, "that it be more easy"),
        (76, 79, "for them"),
        (80, 81, "to commit"),
        (82, 83, "adultery,"),
        (84, 85, "and steal,"),
        (86, 87, "and kill,"),
        (88, 89, "and do"),
        (90, 92, "according to"),
        (93, 96, "their own wills—"),
    ],
    6: [
        (0, 1, "Now,"),
        (2, 5, "this great iniquity"),
        (6, 8, "had come"),
        (9, 11, "upon"),
        (12, 13, "the Nephites,"),
        (14, 17, "in the space of"),
        (18, 19, "years"),
        (20, 23, "not very many;"),
        (24, 30, "and when saw it"),
        (31, 31, "Nephi,"),
        (32, 34, "there grew up"),
        (35, 37, "in his heart"),
        (38, 39, "sorrow"),
        (40, 44, "within his breast;"),
        (45, 49, "and he cried out"),
        (50, 53, "in the agony of"),
        (54, 55, "his soul:"),
    ],
    7: [
        (0, 0, "Oh,"),
        (1, 3, "would that"),
        (4, 9, "I could have lived"),
        (10, 11, "in the days"),
        (12, 16, "when first came out"),
        (17, 19, "my father"),
        (20, 20, "Nephi"),
        (21, 24, "from the land of"),
        (25, 25, "Jerusalem,"),
        (26, 31, "that I might have rejoiced"),
        (32, 34, "together with him"),
        (35, 39, "in the promised land;"),
        (40, 42, "in those days"),
        (43, 47, "were easy to be entreated"),
        (48, 49, "his people,"),
        (50, 51, "steadfast"),
        (52, 53, "to keep"),
        (54, 55, "the commandments of"),
        (56, 57, "God,"),
        (58, 61, "and slow to be led"),
        (62, 63, "to do"),
        (64, 65, "iniquity;"),
        (66, 69, "and they were quick to"),
        (70, 72, "they hearken"),
        (73, 75, "unto the words of"),
        (76, 77, "the Lord—"),
    ],
    8: [
        (0, 0, "Yea,"),
        (1, 4, "if could"),
        (5, 6, "my days"),
        (7, 9, "have been like"),
        (10, 11, "those days,"),
        (12, 14, "then would rejoice"),
        (15, 16, "my soul"),
        (17, 19, "in the righteousness of"),
        (20, 22, "my brethren."),
    ],
    9: [
        (0, 1, "But behold,"),
        (2, 4, "I am appointed"),
        (5, 6, "that"),
        (7, 10, "these are my days,"),
        (11, 15, "and shall be filled"),
        (16, 17, "my soul"),
        (18, 20, "with sorrow"),
        (21, 22, "because of"),
        (23, 25, "this wickedness of"),
        (26, 27, "my brethren."),
    ],
    10: [
        (0, 1, "And behold,"),
        (2, 3, "now"),
        (4, 6, "it came to pass that"),
        (7, 7, "it was"),
        (8, 10, "upon"),
        (11, 12, "a tower,"),
        (13, 15, "which was in"),
        (16, 18, "the garden of"),
        (19, 19, "Nephi,"),
        (20, 23, "which was beside"),
        (24, 25, "the highway"),
        (26, 30, "which led to"),
        (31, 33, "the chief market,"),
        (34, 35, "which was in"),
        (36, 38, "the city of"),
        (39, 39, "Zarahemla;"),
        (40, 41, "therefore,"),
        (42, 44, "had bowed down"),
        (45, 45, "Nephi"),
        (46, 50, "upon the tower"),
        (51, 53, "which was in"),
        (54, 55, "his garden,"),
        (56, 59, "which tower"),
        (60, 63, "stood also near"),
        (64, 67, "unto the gate of"),
        (68, 69, "the garden"),
        (70, 74, "by which passed"),
        (75, 76, "the highway."),
    ],
    11: [
        (0, 3, "And it came to pass that"),
        (4, 6, "there were"),
        (7, 9, "certain men"),
        (10, 12, "passing by"),
        (13, 15, "and saw"),
        (16, 17, "Nephi"),
        (18, 22, "as he poured out"),
        (23, 24, "his soul"),
        (25, 27, "unto God"),
        (28, 32, "upon the tower;"),
        (33, 36, "and they ran"),
        (37, 39, "and told"),
        (40, 41, "the people"),
        (42, 46, "what they had seen,"),
        (47, 51, "and came together"),
        (52, 54, "multitudes of people"),
        (55, 58, "that they might know"),
        (59, 61, "the cause of"),
        (62, 64, "such great mourning"),
        (65, 68, "for the wickedness of"),
        (69, 70, "the people."),
    ],
    12: [
        (0, 2, "And now,"),
        (3, 5, "when arose"),
        (6, 6, "Nephi"),
        (7, 10, "he beheld"),
        (11, 14, "the multitudes of people"),
        (15, 20, "who had gathered together."),
    ],
    13: [
        (0, 3, "And it came to pass that"),
        (4, 6, "he opened"),
        (7, 8, "his mouth"),
        (9, 11, "and said"),
        (12, 15, "unto them:"),
        (16, 16, "Behold,"),
        (17, 17, "why"),
        (18, 22, "have ye gathered together"),
        (23, 24, "yourselves?"),
        (25, 30, "That I may tell"),
        (31, 33, "you"),
        (34, 36, "your iniquities?"),
    ],
    14: [
        (0, 0, "Yea,"),
        (1, 1, "because"),
        (2, 5, "I have gone up"),
        (6, 10, "upon my tower"),
        (11, 15, "that I might"),
        (16, 17, "pour out"),
        (18, 20, "my soul"),
        (21, 23, "unto my God,"),
        (24, 25, "because of"),
        (26, 29, "the great sorrow of"),
        (30, 31, "my heart,"),
        (32, 33, "because of"),
        (34, 36, "your iniquities!"),
    ],
    15: [
        (0, 2, "And because of"),
        (3, 4, "my mourning"),
        (5, 7, "and my lamentation"),
        (8, 12, "ye have gathered together"),
        (13, 14, "yourselves,"),
        (15, 18, "and do marvel;"),
        (19, 19, "yea,"),
        (20, 26, "and ye have"),
        (27, 29, "great need"),
        (30, 32, "to marvel;"),
        (33, 33, "yea,"),
        (34, 36, "ye ought"),
        (37, 38, "to marvel"),
        (39, 39, "because"),
        (40, 42, "ye have yielded"),
        (43, 44, "so that"),
        (45, 47, "has laid strong hold"),
        (48, 50, "the devil"),
        (51, 54, "upon your hearts."),
    ],
    16: [
        (0, 0, "Yea,"),
        (1, 6, "how could"),
        (7, 8, "ye give in"),
        (9, 12, "to the enticing of him"),
        (13, 16, "who seeks"),
        (17, 19, "to cast away"),
        (20, 22, "your souls"),
        (23, 24, "down"),
        (25, 28, "to the enduring misery"),
        (29, 30, "forever"),
        (31, 33, "and the woe"),
        (34, 36, "without end?"),
    ],
    17: [
        (0, 0, "O,"),
        (1, 3, "repent ye,"),
        (4, 6, "repent ye!"),
        (7, 8, "Why"),
        (9, 14, "will ye die?"),
        (15, 19, "Turn ye,"),
        (20, 24, "turn ye"),
        (25, 27, "unto the Lord"),
        (28, 30, "your God."),
        (31, 32, "Why"),
        (33, 36, "has he forsaken"),
        (37, 37, "you?"),
    ],
    18: [
        (0, 0, "Because"),
        (1, 3, "ye have hardened"),
        (4, 6, "your hearts;"),
        (7, 7, "yea,"),
        (8, 12, "ye are unwilling to hearken"),
        (13, 16, "unto the voice of"),
        (17, 20, "the good shepherd;"),
        (21, 21, "yea,"),
        (22, 24, "ye have provoked"),
        (25, 27, "him"),
        (28, 30, "to be angry"),
        (31, 33, "against"),
        (34, 36, "you."),
    ],
    19: [
        (0, 1, "And behold,"),
        (2, 3, "instead of"),
        (4, 7, "gathering you,"),
        (8, 9, "except"),
        (10, 14, "ye will repent,"),
        (15, 15, "behold,"),
        (16, 20, "he shall scatter"),
        (21, 21, "you"),
        (22, 28, "that ye shall become"),
        (29, 30, "meat for"),
        (31, 34, "dogs and wild beasts."),
    ],
    20: [
        (0, 0, "O,"),
        (1, 5, "how could"),
        (6, 7, "ye forget"),
        (8, 10, "your God"),
        (11, 14, "in the very day"),
        (15, 18, "that he delivered"),
        (19, 19, "you?"),
    ],
    21: [
        (0, 1, "But behold,"),
        (2, 4, "ye have done"),
        (5, 6, "this thing"),
        (7, 10, "to obtain riches,"),
        (11, 15, "that ye be praised"),
        (16, 17, "by men,"),
        (18, 18, "yea,"),
        (19, 23, "and that ye might"),
        (24, 26, "ye obtain"),
        (27, 29, "gold and silver."),
        (30, 33, "And ye have fixed"),
        (34, 36, "your hearts"),
        (37, 40, "upon the riches"),
        (41, 45, "and the vain things of"),
        (46, 47, "this world,"),
        (48, 48, "for which"),
        (49, 53, "ye murder,"),
        (54, 55, "and plunder,"),
        (56, 57, "and steal,"),
        (58, 61, "and bear false witness"),
        (62, 64, "against"),
        (65, 67, "your neighbor,"),
        (68, 69, "and do"),
        (70, 73, "all manner of iniquity."),
    ],
    22: [
        (0, 4, "And this is the cause"),
        (5, 10, "for which shall come"),
        (11, 12, "the calamity"),
        (13, 15, "upon you"),
        (16, 17, "except"),
        (18, 20, "ye repent."),
        (21, 21, "For"),
        (22, 26, "if ye will not repent,"),
        (27, 27, "behold,"),
        (28, 32, "this great city,"),
        (33, 37, "and also all the great cities"),
        (38, 40, "round about,"),
        (41, 45, "which are"),
        (46, 48, "in the land"),
        (49, 51, "we possess,"),
        (52, 55, "shall be taken away"),
        (56, 63, "and ye shall not have"),
        (64, 65, "a place"),
        (66, 68, "in those cities;"),
        (69, 70, "for behold,"),
        (71, 76, "will not grant"),
        (77, 79, "the Lord"),
        (80, 82, "unto you"),
        (83, 84, "strength,"),
        (85, 89, "as he has done"),
        (90, 96, "up to this time,"),
        (97, 102, "ye withstand"),
        (103, 106, "against your enemies."),
    ],
    23: [
        (0, 1, "For behold,"),
        (2, 6, "thus saith"),
        (7, 9, "the Lord:"),
        (10, 16, "I will not show"),
        (17, 18, "my strength"),
        (19, 21, "unto the wicked,"),
        (22, 26, "one more"),
        (27, 30, "than the other,"),
        (31, 32, "except"),
        (33, 36, "unto those"),
        (37, 39, "who repent"),
        (40, 43, "of their sins,"),
        (44, 46, "and hearken"),
        (47, 49, "unto my words."),
        (50, 53, "Now therefore,"),
        (54, 56, "O my brethren,"),
        (57, 59, "I desire"),
        (60, 62, "that ye know,"),
        (63, 69, "it shall be better"),
        (70, 72, "for the Lamanites"),
        (73, 75, "than for you"),
        (76, 77, "except"),
        (78, 80, "ye repent."),
    ],
    24: [
        (0, 1, "For behold,"),
        (2, 5, "are more"),
        (6, 7, "righteous"),
        (8, 10, "than you,"),
        (11, 11, "for"),
        (12, 15, "they have not sinned"),
        (16, 18, "against"),
        (19, 22, "that great knowledge"),
        (23, 25, "which ye received;"),
        (26, 27, "therefore"),
        (28, 34, "will be greatly merciful"),
        (35, 36, "the Lord"),
        (37, 40, "unto them;"),
        (41, 41, "yea,"),
        (42, 46, "he will lengthen"),
        (47, 49, "their days"),
        (50, 51, "and increase"),
        (52, 54, "their seed,"),
        (55, 59, "even when"),
        (60, 61, "shalt be utterly destroyed"),
        (62, 62, "thou"),
        (63, 64, "except"),
        (65, 67, "thou repent."),
    ],
    25: [
        (0, 0, "Yea,"),
        (1, 2, "wo"),
        (3, 5, "unto you"),
        (6, 7, "because of"),
        (8, 11, "that great abomination"),
        (12, 14, "which has come"),
        (15, 19, "among you;"),
        (20, 26, "and ye have joined unto it"),
        (27, 28, "yourselves,"),
        (29, 29, "yea,"),
        (30, 33, "to that secret band"),
        (34, 36, "which was established"),
        (37, 38, "by Gadianton!"),
    ],
    26: [
        (0, 0, "Yea,"),
        (1, 5, "shall come"),
        (6, 7, "the calamity"),
        (8, 10, "unto you"),
        (11, 12, "because of"),
        (13, 14, "that pride"),
        (15, 17, "which ye have allowed"),
        (18, 20, "to enter"),
        (21, 24, "into your hearts,"),
        (25, 29, "which has puffed you up"),
        (30, 31, "on high"),
        (32, 36, "beyond"),
        (37, 40, "that which is good"),
        (41, 42, "because of"),
        (43, 45, "your riches"),
        (46, 49, "exceedingly great!"),
    ],
    27: [
        (0, 0, "Yea,"),
        (1, 2, "wo"),
        (3, 5, "unto you"),
        (6, 7, "because of"),
        (8, 10, "your wickedness"),
        (11, 15, "and your abominations!"),
    ],
    28: [
        (0, 0, "And"),
        (1, 3, "except"),
        (4, 6, "ye repent"),
        (7, 11, "ye shall perish;"),
        (12, 12, "yea,"),
        (13, 16, "even"),
        (17, 19, "your lands"),
        (20, 23, "shall be taken"),
        (24, 27, "from you,"),
        (28, 33, "and shall be destroyed"),
        (34, 34, "ye"),
        (35, 39, "from off the face of the earth."),
    ],
    29: [
        (0, 2, "Behold now,"),
        (3, 7, "I do not say"),
        (8, 10, "of myself,"),
        (11, 15, "shall come"),
        (16, 17, "these things,"),
        (18, 18, "because"),
        (19, 22, "it is not of myself"),
        (23, 26, "that I know"),
        (27, 28, "these things;"),
        (29, 30, "but behold,"),
        (31, 33, "I know"),
        (34, 37, "these things are true,"),
        (38, 39, "because"),
        (40, 43, "the Lord God"),
        (44, 47, "has revealed"),
        (48, 49, "these things"),
        (50, 52, "unto me,"),
        (53, 54, "therefore"),
        (55, 59, "I testify"),
        (60, 64, "it shall surely come to pass."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
