"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 4 — growth and
then pride in the church; Alma gives up the judgment-seat to Nephihah to
preach; the reign of the judges, years six through nine.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15).

    python3 build_overrides_alma4.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 4

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "Now"),
        (2, 3, "it came to pass"),
        (4, 7, "in the sixth"),
        (8, 9, "year"),
        (10, 12, "of the reign"),
        (13, 14, "of the judges"),
        (15, 18, "over the people of"),
        (19, 19, "Nephi,"),
        (20, 23, "there were no"),
        (24, 25, "contentions"),
        (26, 27, "nor"),
        (28, 29, "wars"),
        (30, 33, "in the land of"),
        (34, 34, "Zarahemla."),
    ],
    2: [
        (0, 0, "But"),
        (1, 2, "were afflicted"),
        (3, 4, "the people,"),
        (5, 5, "yea,"),
        (6, 8, "greatly afflicted"),
        (9, 12, "for the loss of"),
        (13, 15, "their brethren,"),
        (16, 20, "and also for the loss of"),
        (21, 23, "their flocks"),
        (24, 25, "and herds,"),
        (26, 30, "and also for the loss of"),
        (31, 34, "their fields of grain,"),
        (35, 37, "which were trodden"),
        (38, 41, "under foot"),
        (42, 43, "and destroyed"),
        (44, 46, "by the Lamanites."),
    ],
    3: [
        (0, 0, "And"),
        (1, 5, "so great were"),
        (6, 8, "their afflictions"),
        (9, 10, "that"),
        (11, 13, "had"),
        (14, 16, "every soul"),
        (17, 18, "cause"),
        (19, 21, "to mourn;"),
        (22, 22, "and"),
        (23, 25, "they believed"),
        (26, 28, "that it was"),
        (29, 31, "the judgments"),
        (32, 34, "of God"),
        (35, 37, "sent"),
        (38, 41, "upon them"),
        (42, 43, "because of"),
        (44, 46, "their wickedness"),
        (47, 51, "and their abominations;"),
        (52, 53, "therefore"),
        (54, 56, "were awakened"),
        (57, 58, "they"),
        (59, 61, "to a remembrance of"),
        (62, 65, "their duty."),
    ],
    4: [
        (0, 0, "And"),
        (1, 3, "began to"),
        (4, 5, "they establish"),
        (6, 6, "more fully"),
        (7, 8, "the church;"),
        (9, 9, "yea,"),
        (10, 10, "and"),
        (11, 12, "many"),
        (13, 14, "were baptized"),
        (15, 17, "in the waters of"),
        (18, 18, "Sidon"),
        (19, 20, "and were joined"),
        (21, 23, "to the church"),
        (24, 26, "of God;"),
        (27, 27, "yea,"),
        (28, 29, "were baptized"),
        (30, 31, "they"),
        (32, 35, "by the hand of"),
        (36, 36, "Alma,"),
        (37, 38, "who"),
        (39, 40, "had been consecrated"),
        (41, 44, "the high priest"),
        (45, 47, "over"),
        (48, 48, "the people"),
        (49, 51, "of the church,"),
        (52, 55, "by the hand of"),
        (56, 57, "his father"),
        (58, 59, "Alma."),
    ],
    5: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the seventh"),
        (7, 8, "year"),
        (9, 11, "of the reign"),
        (12, 13, "of the judges,"),
        (14, 16, "there were"),
        (17, 19, "about"),
        (20, 22, "three thousand"),
        (23, 24, "five hundred"),
        (25, 25, "souls"),
        (26, 28, "that united"),
        (29, 31, "themselves"),
        (32, 34, "to the church"),
        (35, 37, "of God"),
        (38, 39, "and were baptized."),
        (40, 40, "And"),
        (41, 43, "thus"),
        (44, 44, "ended"),
        (45, 48, "the seventh"),
        (49, 50, "year"),
        (51, 53, "of the reign"),
        (54, 55, "of the judges"),
        (56, 59, "over the people of"),
        (60, 60, "Nephi,"),
        (61, 61, "and"),
        (62, 67, "there was continual"),
        (68, 70, "peace"),
        (71, 74, "in all that time."),
    ],
    6: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the eighth"),
        (7, 8, "year"),
        (9, 11, "of the reign"),
        (12, 13, "of the judges,"),
        (14, 16, "began to"),
        (17, 17, "wax proud"),
        (18, 18, "the people"),
        (19, 21, "of the church,"),
        (22, 23, "because of"),
        (24, 27, "their exceeding riches,"),
        (28, 32, "and their fine silks,"),
        (33, 39, "and their fine-twined linen,"),
        (40, 40, "and"),
        (41, 42, "because of"),
        (43, 45, "the many of"),
        (46, 48, "their flocks"),
        (49, 50, "and herds,"),
        (51, 54, "and their gold"),
        (55, 58, "and their silver,"),
        (59, 62, "and all manner of"),
        (63, 65, "precious things,"),
        (66, 69, "which they had obtained"),
        (70, 72, "by"),
        (73, 76, "their industry;"),
        (77, 77, "and"),
        (78, 81, "in all these things"),
        (82, 84, "were lifted up"),
        (85, 86, "they"),
        (87, 89, "in the pride"),
        (90, 93, "as seen"),
        (94, 97, "in their eyes,"),
        (98, 98, "for"),
        (99, 101, "began to"),
        (102, 103, "they wear"),
        (104, 107, "very costly apparel."),
    ],
    7: [
        (0, 1, "Now"),
        (2, 3, "was"),
        (4, 5, "this"),
        (6, 7, "the cause"),
        (8, 11, "of much affliction"),
        (12, 13, "to Alma,"),
        (14, 14, "yea,"),
        (15, 18, "and to many of"),
        (19, 19, "the people"),
        (20, 21, "whom"),
        (22, 23, "had consecrated"),
        (24, 25, "Alma"),
        (26, 28, "to be"),
        (29, 29, "teachers,"),
        (30, 31, "and priests,"),
        (32, 33, "and elders"),
        (34, 36, "over"),
        (37, 38, "the church;"),
        (39, 39, "yea,"),
        (40, 43, "many of"),
        (44, 45, "them"),
        (46, 48, "were sorely grieved"),
        (49, 51, "for the wickedness"),
        (52, 54, "which they saw"),
        (55, 57, "had begun"),
        (58, 59, "to be"),
        (60, 62, "among"),
        (63, 65, "their people."),
    ],
    8: [
        (0, 0, "For"),
        (1, 3, "they saw"),
        (4, 6, "and beheld"),
        (7, 10, "with great sorrow"),
        (11, 13, "that began"),
        (14, 15, "the people"),
        (16, 18, "of the church"),
        (19, 21, "to be lifted up"),
        (22, 24, "in the pride"),
        (25, 28, "of their eyes,"),
        (29, 31, "and to set"),
        (32, 34, "their hearts"),
        (35, 38, "upon riches"),
        (39, 41, "and upon"),
        (42, 45, "the vain things of"),
        (46, 47, "the world,"),
        (48, 53, "that began to"),
        (54, 55, "be scornful,"),
        (56, 61, "one towards another,"),
        (62, 64, "and began to"),
        (65, 67, "persecute"),
        (68, 69, "those"),
        (70, 71, "that"),
        (72, 74, "did not believe"),
        (75, 77, "according to"),
        (78, 81, "their own will"),
        (82, 83, "and pleasure."),
    ],
    9: [
        (0, 0, "And"),
        (1, 2, "thus,"),
        (3, 6, "in this eighth"),
        (7, 8, "year"),
        (9, 11, "of the reign"),
        (12, 13, "of the judges,"),
        (14, 16, "there began to"),
        (17, 18, "be"),
        (19, 21, "great contentions"),
        (22, 24, "among"),
        (25, 25, "the people"),
        (26, 28, "of the church;"),
        (29, 29, "yea,"),
        (30, 32, "there were"),
        (33, 33, "envyings,"),
        (34, 35, "and strife,"),
        (36, 38, "and malice,"),
        (39, 40, "and persecutions,"),
        (41, 43, "and pride,"),
        (44, 47, "even to exceed"),
        (48, 49, "the pride"),
        (50, 52, "of those"),
        (53, 54, "who"),
        (55, 57, "did not belong"),
        (58, 60, "to the church"),
        (61, 63, "of God."),
    ],
    10: [
        (0, 0, "And"),
        (1, 3, "thus"),
        (4, 4, "ended"),
        (5, 8, "the eighth"),
        (9, 10, "year"),
        (11, 13, "of the reign"),
        (14, 15, "of the judges;"),
        (16, 16, "and"),
        (17, 19, "the wickedness of"),
        (20, 22, "the church,"),
        (23, 24, "was"),
        (25, 29, "a great stumbling-block"),
        (30, 33, "to those"),
        (34, 35, "who"),
        (36, 38, "did not belong"),
        (39, 41, "to the church;"),
        (42, 42, "and"),
        (43, 45, "thus"),
        (46, 48, "began to fail"),
        (49, 50, "the church"),
        (51, 55, "in its progress."),
    ],
    11: [
        (0, 2, "And it came to pass"),
        (3, 5, "in the commencement"),
        (6, 9, "of the ninth"),
        (10, 11, "year,"),
        (12, 14, "saw"),
        (15, 16, "Alma"),
        (17, 19, "the wickedness of"),
        (20, 21, "the church,"),
        (22, 22, "and"),
        (23, 26, "he saw also"),
        (27, 29, "began to"),
        (30, 31, "lead"),
        (32, 34, "the example of"),
        (35, 35, "the people"),
        (36, 38, "of the church,"),
        (39, 40, "those"),
        (41, 42, "who"),
        (43, 45, "were unbelievers,"),
        (46, 49, "from one iniquity"),
        (50, 53, "to another,"),
        (54, 56, "thus"),
        (57, 58, "bringing on"),
        (59, 61, "the destruction of"),
        (62, 64, "the people."),
    ],
    12: [
        (0, 0, "Yea,"),
        (1, 3, "he saw"),
        (4, 8, "great inequality"),
        (9, 11, "among"),
        (12, 12, "the people,"),
        (13, 15, "some"),
        (16, 19, "lifting up"),
        (20, 22, "themselves"),
        (23, 26, "with their pride,"),
        (27, 28, "despising"),
        (29, 30, "others,"),
        (31, 33, "turning"),
        (34, 36, "their backs"),
        (37, 38, "upon"),
        (39, 41, "the needy"),
        (42, 43, "and"),
        (44, 46, "the naked,"),
        (47, 49, "and those"),
        (50, 54, "who were hungry,"),
        (55, 57, "and those"),
        (58, 62, "who were athirst,"),
        (63, 65, "and those"),
        (66, 69, "who were sick"),
        (70, 71, "and afflicted."),
    ],
    13: [
        (0, 1, "Now"),
        (2, 3, "was"),
        (4, 5, "this"),
        (6, 7, "a cause"),
        (8, 9, "for lamentations"),
        (10, 12, "among"),
        (13, 14, "the people,"),
        (15, 16, "while others"),
        (17, 19, "were abasing"),
        (20, 22, "themselves,"),
        (23, 27, "succoring"),
        (28, 31, "those"),
        (32, 33, "who"),
        (34, 35, "stood in need of"),
        (36, 38, "their succor,"),
        (39, 41, "such as"),
        (42, 44, "imparting"),
        (45, 48, "their substance"),
        (49, 52, "to the poor"),
        (53, 57, "and the needy,"),
        (58, 59, "feeding"),
        (60, 64, "the hungry,"),
        (65, 66, "and suffering"),
        (67, 71, "all manner of afflictions,"),
        (72, 73, "for Christ's sake,"),
        (74, 75, "who"),
        (76, 80, "should come"),
        (81, 83, "according to"),
        (84, 85, "the spirit"),
        (86, 87, "of prophecy;"),
    ],
    14: [
        (0, 2, "looking forward"),
        (3, 5, "to that day,"),
        (6, 8, "thus"),
        (9, 10, "retaining"),
        (11, 13, "a remission of"),
        (14, 16, "their sins;"),
        (17, 18, "being filled"),
        (19, 22, "with great joy"),
        (23, 24, "because of"),
        (25, 28, "the resurrection of"),
        (29, 31, "the dead,"),
        (32, 34, "according to"),
        (35, 36, "the will"),
        (37, 39, "and power"),
        (40, 43, "and deliverance of"),
        (44, 45, "Jesus Christ"),
        (46, 48, "from the bands of"),
        (49, 50, "death."),
    ],
    15: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "it came to pass that"),
        (6, 8, "having seen"),
        (9, 9, "Alma"),
        (10, 12, "the afflictions of"),
        (13, 14, "the humble"),
        (15, 16, "followers"),
        (17, 19, "of God,"),
        (20, 21, "and the persecutions"),
        (22, 24, "which were heaped"),
        (25, 28, "upon them"),
        (29, 33, "by the remainder of"),
        (34, 36, "his people,"),
        (37, 38, "and seeing"),
        (39, 45, "all their inequality,"),
        (46, 48, "began to"),
        (49, 52, "be very sorrowful;"),
        (53, 56, "nevertheless"),
        (57, 59, "did not fail"),
        (60, 61, "him"),
        (62, 64, "the Spirit of"),
        (65, 67, "the Lord."),
    ],
    16: [
        (0, 0, "And"),
        (1, 3, "he selected"),
        (4, 6, "a wise man"),
        (7, 9, "who was"),
        (10, 12, "among"),
        (13, 13, "the elders"),
        (14, 16, "of the church,"),
        (17, 19, "and gave"),
        (20, 22, "him"),
        (23, 24, "power"),
        (25, 27, "according to"),
        (28, 30, "the voice of"),
        (31, 32, "the people,"),
        (33, 38, "that he might"),
        (39, 39, "have"),
        (40, 41, "power"),
        (42, 44, "to enact"),
        (45, 45, "laws"),
        (46, 48, "according to"),
        (49, 49, "the laws"),
        (50, 52, "which had been given,"),
        (53, 54, "and to put in force"),
        (55, 56, "those laws"),
        (57, 59, "according to"),
        (60, 60, "the wickedness"),
        (61, 63, "and the crimes of"),
        (64, 64, "the people."),
    ],
    17: [
        (0, 1, "Now"),
        (2, 5, "the name of"),
        (6, 7, "this man"),
        (8, 9, "was Nephihah,"),
        (10, 10, "and"),
        (11, 14, "he was appointed"),
        (15, 17, "to be"),
        (18, 19, "chief judge;"),
        (20, 20, "and"),
        (21, 24, "he sat"),
        (25, 27, "in the judgment-seat"),
        (28, 29, "to judge"),
        (30, 31, "and to govern"),
        (32, 33, "the people."),
    ],
    18: [
        (0, 1, "Now"),
        (2, 5, "did not grant"),
        (6, 7, "Alma"),
        (8, 10, "unto him"),
        (11, 13, "the office of"),
        (14, 16, "being"),
        (17, 18, "high priest"),
        (19, 21, "over the church,"),
        (22, 22, "but"),
        (23, 26, "he retained"),
        (27, 29, "the office of"),
        (30, 32, "high priest"),
        (33, 36, "unto himself;"),
        (37, 37, "but"),
        (38, 41, "he delivered"),
        (42, 43, "the judgment-seat"),
        (44, 45, "unto Nephihah."),
    ],
    19: [
        (0, 0, "And"),
        (1, 3, "he did"),
        (4, 5, "this"),
        (6, 12, "that he himself might"),
        (13, 14, "go forth"),
        (15, 17, "among his people,"),
        (18, 19, "or among"),
        (20, 20, "the people"),
        (21, 22, "of Nephi,"),
        (23, 26, "that he might"),
        (27, 29, "preach"),
        (30, 31, "the word"),
        (32, 34, "of God"),
        (35, 38, "unto them,"),
        (39, 40, "to stir up"),
        (41, 42, "them,"),
        (43, 44, "in remembrance of"),
        (45, 47, "their duty,"),
        (48, 48, "and"),
        (49, 52, "that he might"),
        (53, 54, "pull down,"),
        (55, 57, "by"),
        (58, 59, "the word"),
        (60, 62, "of God,"),
        (63, 65, "all the pride"),
        (66, 68, "and craftiness"),
        (69, 71, "and all the contentions"),
        (72, 74, "which were"),
        (75, 77, "among his people,"),
        (78, 81, "seeing"),
        (82, 85, "no way"),
        (86, 89, "that he might"),
        (90, 92, "reclaim"),
        (93, 95, "them,"),
        (96, 97, "save it were"),
        (98, 100, "in bearing down"),
        (101, 103, "in"),
        (104, 106, "pure testimony"),
        (107, 108, "against"),
        (109, 112, "them."),
    ],
    20: [
        (0, 0, "And"),
        (1, 2, "thus"),
        (3, 5, "in the commencement"),
        (6, 9, "of the ninth"),
        (10, 11, "year"),
        (12, 14, "of the reign"),
        (15, 16, "of the judges"),
        (17, 20, "over the people of"),
        (21, 21, "Nephi,"),
        (22, 24, "delivered up"),
        (25, 26, "Alma"),
        (27, 29, "the judgment-seat"),
        (30, 31, "to Nephihah,"),
        (32, 35, "and confined wholly"),
        (36, 38, "himself"),
        (39, 42, "to the high priesthood"),
        (43, 46, "of the holy order"),
        (47, 49, "of God,"),
        (50, 52, "to the testimony"),
        (53, 55, "of the word"),
        (56, 58, "of God,"),
        (59, 62, "according to"),
        (63, 64, "the spirit"),
        (65, 66, "of revelation"),
        (67, 68, "and prophecy."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
