"""
Hand-curated TAM-phrase gloss overrides for Helamana (Helaman) 3 — years of peace
and dissension; the great northward migrations of the people (into a land of many
waters, building with cement for want of timber), the shipping of records; the
prosperity and pride cycle; the deaths of Helaman's contemporaries; Nephi and
Lehi, sons of Helaman, and the church's growth amid Gadianton's spreading secret
band; Helaman's death and Nephi succeeding to the judgment-seat.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_helaman3.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "helaman"
CHAPTER_NUM = 3

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now,"),
        (3, 4, "it came to pass"),
        (5, 8, "in the fortieth"),
        (9, 13, "and third year"),
        (14, 17, "of the reign of"),
        (18, 18, "the judges,"),
        (19, 20, "there was no"),
        (21, 22, "contentions"),
        (23, 25, "among"),
        (26, 29, "the people of Nephi"),
        (30, 31, "except"),
        (32, 34, "a little pride"),
        (35, 37, "that was"),
        (38, 40, "in"),
        (41, 42, "the church,"),
        (43, 47, "which caused"),
        (48, 50, "some small dissensions"),
        (51, 53, "among"),
        (54, 55, "the people,"),
        (56, 58, "which matters"),
        (59, 60, "were settled"),
        (61, 64, "in the ending of"),
        (65, 67, "the fortieth"),
        (68, 72, "and third year."),
    ],
    2: [
        (0, 2, "And there was no"),
        (3, 4, "contention"),
        (5, 7, "among"),
        (8, 9, "the people"),
        (10, 13, "in the fortieth"),
        (14, 18, "and fourth year;"),
        (19, 23, "neither was there"),
        (24, 26, "much contention"),
        (27, 30, "in the fortieth"),
        (31, 35, "and fifth year."),
    ],
    3: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the fortieth"),
        (7, 11, "and sixth year,"),
        (12, 12, "yea,"),
        (13, 15, "there was"),
        (16, 18, "much contention"),
        (19, 22, "and many dissensions;"),
        (23, 27, "wherein were exceedingly many"),
        (28, 32, "who departed from"),
        (33, 35, "the land of"),
        (36, 36, "Zarahemla,"),
        (37, 39, "and went"),
        (40, 44, "to the land northward"),
        (45, 50, "to make their inheritance"),
        (51, 52, "the land."),
    ],
    4: [
        (0, 4, "And they did travel"),
        (5, 8, "to a distance"),
        (9, 10, "very great,"),
        (11, 13, "insomuch that"),
        (14, 16, "they reached"),
        (17, 19, "large bodies of water"),
        (20, 23, "and many rivers."),
    ],
    5: [
        (0, 0, "Yea,"),
        (1, 3, "and even"),
        (4, 6, "they spread out"),
        (7, 10, "into all parts of"),
        (11, 12, "the land,"),
        (13, 16, "into whatsoever parts"),
        (17, 19, "it had not been made desolate"),
        (20, 22, "and without"),
        (23, 24, "old trees,"),
        (25, 26, "because of"),
        (27, 30, "the many people"),
        (31, 35, "who dwelt before"),
        (36, 40, "and made their inheritance"),
        (41, 42, "the land."),
    ],
    6: [
        (0, 2, "And now,"),
        (3, 7, "there was no part of"),
        (8, 9, "the land"),
        (10, 11, "that was made bare,"),
        (12, 13, "except"),
        (14, 15, "old trees;"),
        (16, 18, "but because of"),
        (19, 21, "the greatness of"),
        (22, 24, "the destruction of"),
        (25, 25, "the people"),
        (26, 30, "who dwelt before"),
        (31, 32, "the land"),
        (33, 34, "therefore"),
        (35, 37, "it was called"),
        (38, 39, "desolate."),
    ],
    7: [
        (0, 1, "And because"),
        (2, 3, "was little"),
        (4, 5, "timber"),
        (6, 8, "that was"),
        (9, 11, "upon"),
        (12, 13, "the land,"),
        (14, 17, "nevertheless"),
        (18, 19, "the people"),
        (20, 26, "who went there"),
        (27, 29, "became"),
        (30, 31, "very skilled"),
        (32, 34, "in the use of"),
        (35, 37, "cement;"),
        (38, 39, "therefore"),
        (40, 43, "they built"),
        (44, 44, "houses"),
        (45, 47, "of cement,"),
        (48, 52, "wherein they dwelt."),
    ],
    8: [
        (0, 3, "And it came to pass that"),
        (4, 5, "they multiplied"),
        (6, 8, "and spread out,"),
        (9, 11, "and went"),
        (12, 16, "from the land southward"),
        (17, 21, "to the land northward,"),
        (22, 24, "and did spread"),
        (25, 27, "insomuch that"),
        (28, 30, "began to cover"),
        (31, 34, "them"),
        (35, 36, "upon"),
        (37, 39, "the whole earth,"),
        (40, 44, "from the south sea"),
        (45, 49, "to the north sea,"),
        (50, 54, "from the west sea"),
        (55, 59, "to the east sea."),
    ],
    9: [
        (0, 2, "And the people"),
        (3, 6, "who were in"),
        (7, 10, "the land northward,"),
        (11, 12, "dwelt"),
        (13, 14, "in tents,"),
        (15, 18, "and in houses of cement,"),
        (19, 22, "and they preserved"),
        (23, 25, "whatever tree"),
        (26, 28, "that sprang up"),
        (29, 31, "upon"),
        (32, 33, "the land"),
        (34, 37, "that it should grow up,"),
        (38, 42, "that they may obtain"),
        (43, 45, "in time"),
        (46, 46, "timber"),
        (47, 49, "to build"),
        (50, 52, "their houses,"),
        (53, 53, "yea,"),
        (54, 57, "their cities,"),
        (58, 61, "and their temples,"),
        (62, 65, "and their synagogues,"),
        (66, 69, "and their sanctuaries,"),
        (70, 74, "and their buildings of"),
        (75, 77, "all diverse kinds."),
    ],
    10: [
        (0, 2, "And it came to pass"),
        (3, 4, "because"),
        (5, 10, "was very hard to find"),
        (11, 12, "timber"),
        (13, 17, "in the land northward,"),
        (18, 19, "therefore"),
        (20, 24, "they sent"),
        (25, 26, "much"),
        (27, 29, "by way of"),
        (30, 30, "ships."),
    ],
    11: [
        (0, 2, "And thus"),
        (3, 5, "they did"),
        (6, 8, "that could"),
        (9, 10, "the people"),
        (11, 15, "in the land northward"),
        (16, 18, "they build"),
        (19, 22, "many cities,"),
        (23, 24, "of wood"),
        (25, 28, "and of cement."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 6, "there were"),
        (7, 9, "many of"),
        (10, 11, "the people of"),
        (12, 15, "the people of Ammon,"),
        (16, 18, "who were"),
        (19, 21, "Lamanites"),
        (22, 26, "in their birth,"),
        (27, 30, "also went"),
        (31, 33, "into this land."),
    ],
    13: [
        (0, 2, "And now"),
        (3, 5, "many records"),
        (6, 7, "that were kept"),
        (8, 10, "concerning"),
        (11, 13, "the proceedings of"),
        (14, 15, "this people,"),
        (16, 19, "by many of"),
        (20, 21, "them,"),
        (22, 24, "which are detailed"),
        (25, 27, "and exceedingly large,"),
        (28, 29, "concerning"),
        (30, 33, "them."),
    ],
    14: [
        (0, 1, "But behold,"),
        (2, 6, "a hundredth part of"),
        (7, 8, "the proceedings of"),
        (9, 10, "this people,"),
        (11, 11, "yea,"),
        (12, 14, "the account"),
        (15, 17, "concerning"),
        (18, 19, "the Lamanites"),
        (20, 22, "and the Nephites,"),
        (23, 26, "and their wars,"),
        (27, 28, "and contentions,"),
        (29, 30, "and dissensions,"),
        (31, 34, "and their preaching,"),
        (35, 38, "and their prophecies,"),
        (39, 42, "and their voyaging"),
        (43, 44, "in ships"),
        (45, 49, "and their building of"),
        (50, 50, "ships,"),
        (51, 55, "and their building of"),
        (56, 56, "temples,"),
        (57, 58, "and synagogues"),
        (59, 62, "and their sanctuaries;"),
        (63, 66, "and their righteousness,"),
        (67, 70, "and their wickedness,"),
        (71, 75, "and their murders,"),
        (76, 79, "and their robbings,"),
        (80, 83, "and their plundering,"),
        (84, 86, "and abominations"),
        (87, 90, "and all diverse whoredoms,"),
        (91, 94, "cannot"),
        (95, 95, "be recorded"),
        (96, 98, "in this work."),
    ],
    15: [
        (0, 1, "But behold,"),
        (2, 4, "many books"),
        (5, 7, "there are"),
        (8, 12, "and many records of"),
        (13, 14, "diverse kinds,"),
        (15, 18, "and were kept mainly"),
        (19, 20, "them"),
        (21, 24, "by the Nephites."),
    ],
    16: [
        (0, 4, "And were handed down"),
        (5, 6, "these records"),
        (7, 10, "from one generation"),
        (11, 14, "to another generation"),
        (15, 18, "by the Nephites,"),
        (19, 21, "even until"),
        (22, 24, "they fell"),
        (25, 27, "into transgression"),
        (28, 30, "and have been murdered,"),
        (31, 31, "plundered,"),
        (32, 33, "and hunted,"),
        (34, 35, "and driven forth,"),
        (36, 37, "and slain,"),
        (38, 39, "and scattered"),
        (40, 42, "upon"),
        (43, 44, "the earth,"),
        (45, 47, "and mingled with"),
        (48, 49, "the Lamanites"),
        (50, 52, "until"),
        (53, 57, "they were no longer called"),
        (58, 61, "Nephites,"),
        (62, 62, "for"),
        (63, 64, "they were wicked,"),
        (65, 66, "and wild,"),
        (67, 68, "and ferocious,"),
        (69, 69, "yea,"),
        (70, 73, "even became"),
        (74, 77, "Lamanites."),
    ],
    17: [
        (0, 2, "And now"),
        (3, 7, "I return again"),
        (8, 10, "to my account;"),
        (11, 12, "therefore,"),
        (13, 14, "the things"),
        (15, 19, "which I said"),
        (20, 22, "had passed"),
        (23, 26, "after"),
        (27, 29, "there were"),
        (30, 32, "great contentions,"),
        (33, 34, "and disturbances,"),
        (35, 36, "and wars,"),
        (37, 38, "and dissensions,"),
        (39, 41, "among"),
        (42, 45, "the people of Nephi."),
    ],
    18: [
        (0, 1, "ended"),
        (2, 4, "the fortieth"),
        (5, 9, "and sixth year"),
        (10, 13, "of the reign of"),
        (14, 14, "the judges;"),
    ],
    19: [
        (0, 3, "And it came to pass that"),
        (4, 7, "there remained"),
        (8, 9, "great contention"),
        (10, 12, "in the land,"),
        (13, 13, "yea,"),
        (14, 17, "even in"),
        (18, 20, "the fortieth"),
        (21, 25, "and seventh year,"),
        (26, 29, "and the fortieth"),
        (30, 35, "and eighth year also."),
    ],
    20: [
        (0, 3, "Nevertheless"),
        (4, 5, "sat"),
        (6, 6, "Helaman"),
        (7, 9, "in the judgment-seat"),
        (10, 12, "with justice"),
        (13, 16, "and impartiality;"),
        (17, 17, "yea,"),
        (18, 20, "he was diligent"),
        (21, 22, "to keep"),
        (23, 23, "the statutes,"),
        (24, 25, "and the judgments,"),
        (26, 28, "and the commandments of"),
        (29, 30, "God;"),
        (31, 34, "and he did"),
        (35, 37, "continually"),
        (38, 40, "the right thing"),
        (41, 44, "in the sight of"),
        (45, 46, "God;"),
        (47, 50, "and he walked"),
        (51, 53, "in the ways of"),
        (54, 55, "his father,"),
        (56, 58, "insomuch that"),
        (59, 61, "he prospered"),
        (62, 64, "in the land."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 8, "there were to him"),
        (9, 12, "two sons."),
        (13, 16, "He gave"),
        (17, 19, "unto the eldest"),
        (20, 22, "the name of"),
        (23, 23, "Nephi,"),
        (24, 27, "and unto the youngest,"),
        (28, 30, "the name of"),
        (31, 31, "Lehi."),
        (32, 35, "And began to"),
        (36, 38, "they two grow up"),
        (39, 41, "unto the Lord."),
    ],
    22: [
        (0, 3, "Now it came to pass that"),
        (4, 6, "began to cease"),
        (7, 8, "the wars"),
        (9, 10, "and contentions,"),
        (11, 14, "in a small degree,"),
        (15, 17, "among"),
        (18, 20, "the Nephite people,"),
        (21, 24, "in the latter end of"),
        (25, 27, "the fortieth"),
        (28, 32, "and eighth year"),
        (33, 36, "of the reign of"),
        (37, 37, "the judges"),
        (38, 41, "over the people of"),
        (42, 42, "Nephi."),
    ],
    23: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the fortieth"),
        (7, 11, "and ninth year"),
        (12, 15, "of the reign of"),
        (16, 16, "the judges,"),
        (17, 22, "there continued to be"),
        (23, 24, "the peace"),
        (25, 26, "that was established"),
        (27, 29, "in the land,"),
        (30, 32, "in all things,"),
        (33, 34, "except"),
        (35, 37, "those secret combinations"),
        (38, 39, "which were founded"),
        (40, 41, "by Gadianton"),
        (42, 43, "the robber"),
        (44, 49, "in the most inhabited parts of"),
        (50, 51, "the land,"),
        (52, 55, "which were not known"),
        (56, 59, "at that time"),
        (60, 62, "to those"),
        (63, 67, "who headed"),
        (68, 69, "the government;"),
        (70, 71, "therefore"),
        (72, 75, "were not destroyed"),
        (76, 77, "they"),
        (78, 80, "from the land."),
    ],
    24: [
        (0, 2, "And it came to pass"),
        (3, 6, "in this same year"),
        (7, 9, "there was"),
        (10, 13, "exceeding great prosperity"),
        (14, 16, "in the church,"),
        (17, 19, "insomuch that"),
        (20, 21, "there were"),
        (22, 25, "thousands"),
        (26, 30, "who joined"),
        (31, 33, "themselves"),
        (34, 36, "to the church,"),
        (37, 39, "and were baptized"),
        (40, 42, "unto repentance."),
    ],
    25: [
        (0, 4, "And so exceedingly great was"),
        (5, 7, "the prosperity of"),
        (8, 9, "the church,"),
        (10, 13, "and so exceedingly many"),
        (14, 14, "blessings"),
        (15, 17, "which were poured out"),
        (18, 20, "upon"),
        (21, 21, "the people,"),
        (22, 24, "even unto"),
        (25, 26, "the high priests"),
        (27, 28, "and teachers"),
        (29, 31, "could not contain"),
        (32, 35, "their great astonishment."),
    ],
    26: [
        (0, 3, "And it came to pass that"),
        (4, 5, "prospered greatly"),
        (6, 8, "the work of"),
        (9, 10, "the Lord"),
        (11, 13, "unto the baptizing"),
        (14, 16, "and joining"),
        (17, 20, "to the church of"),
        (21, 22, "God,"),
        (23, 26, "many souls,"),
        (27, 27, "yea,"),
        (28, 31, "even unto"),
        (32, 36, "the tens of thousands."),
    ],
    27: [
        (0, 1, "Thus"),
        (2, 4, "we may"),
        (5, 7, "we see"),
        (8, 10, "is tenderly merciful"),
        (11, 12, "the Lord"),
        (13, 17, "unto all"),
        (18, 22, "who call"),
        (23, 26, "upon his holy name,"),
        (27, 30, "with the sincerity of"),
        (31, 33, "their hearts."),
    ],
    28: [
        (0, 0, "Yea,"),
        (1, 2, "thus"),
        (3, 6, "we see"),
        (7, 8, "is opened"),
        (9, 11, "the gate of"),
        (12, 13, "heaven"),
        (14, 16, "to all people,"),
        (17, 17, "yea"),
        (18, 21, "even to them"),
        (22, 25, "who believe"),
        (26, 29, "on the name of"),
        (30, 31, "Jesus Christ,"),
        (32, 37, "who is the Son of"),
        (38, 39, "God."),
    ],
    29: [
        (0, 0, "Yea,"),
        (1, 3, "we see"),
        (4, 5, "that can"),
        (6, 9, "whosoever"),
        (10, 13, "who so desires"),
        (14, 15, "hold fast"),
        (16, 19, "to the word of"),
        (20, 21, "God,"),
        (22, 24, "which is quick"),
        (25, 26, "and powerful,"),
        (27, 32, "which shall break apart"),
        (33, 35, "the evil cunning"),
        (36, 37, "and the snares"),
        (38, 41, "and all the schemes of"),
        (42, 43, "the devil,"),
        (44, 47, "and lead"),
        (48, 51, "the man of Christ"),
        (52, 55, "in the strait path"),
        (56, 57, "and narrow,"),
        (58, 61, "over"),
        (62, 64, "the gulf of misery"),
        (65, 67, "everlasting"),
        (68, 70, "which is prepared"),
        (71, 73, "to destroy"),
        (74, 76, "the wicked—"),
    ],
    30: [
        (0, 2, "And place"),
        (3, 5, "their souls,"),
        (6, 6, "yea,"),
        (7, 9, "their souls"),
        (10, 11, "ever-living,"),
        (12, 16, "at the right hand of"),
        (17, 18, "God"),
        (19, 21, "in the kingdom of"),
        (22, 24, "heaven,"),
        (25, 28, "to dwell with"),
        (29, 29, "Abraham,"),
        (30, 31, "and Isaac,"),
        (32, 33, "and Jacob,"),
        (34, 36, "and with"),
        (37, 41, "all our holy fathers,"),
        (42, 46, "to go out no more"),
        (47, 48, "outside."),
    ],
    31: [
        (0, 3, "And there was"),
        (4, 6, "in this year"),
        (7, 9, "continual rejoicing"),
        (10, 13, "in the land of"),
        (14, 14, "Zarahemla,"),
        (15, 17, "and all the places"),
        (18, 20, "round about,"),
        (21, 24, "even in"),
        (25, 27, "all the land"),
        (28, 30, "which was held"),
        (31, 33, "by the Nephites."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 5, "there was"),
        (6, 7, "the peace"),
        (8, 12, "and exceeding great joy"),
        (13, 18, "in the remaining part of"),
        (19, 21, "the fortieth"),
        (22, 26, "and ninth year;"),
        (27, 27, "yea,"),
        (28, 32, "and there was also"),
        (33, 34, "peace"),
        (35, 40, "and continual great joy"),
        (41, 46, "in the fiftieth year"),
        (47, 50, "of the reign of"),
        (51, 51, "the judges."),
    ],
    33: [
        (0, 4, "And there was also"),
        (5, 6, "peace"),
        (7, 10, "in the fiftieth"),
        (11, 15, "and first year"),
        (16, 19, "of the reign of"),
        (20, 20, "the judges,"),
        (21, 22, "except"),
        (23, 25, "the pride"),
        (26, 30, "which began to enter"),
        (31, 33, "into"),
        (34, 35, "the church—"),
        (36, 38, "not"),
        (39, 41, "the church of"),
        (42, 43, "God,"),
        (44, 47, "but into"),
        (48, 50, "the hearts of the people"),
        (51, 55, "who claimed"),
        (56, 58, "they belonged"),
        (59, 62, "to the church of"),
        (63, 64, "God—"),
    ],
    34: [
        (0, 2, "And were puffed up"),
        (3, 4, "they"),
        (5, 7, "in pride,"),
        (8, 11, "even unto"),
        (12, 15, "their persecuting of"),
        (16, 18, "many of"),
        (19, 21, "their brethren."),
        (22, 23, "Now"),
        (24, 28, "this was a great evil"),
        (29, 30, "this thing,"),
        (31, 34, "which caused"),
        (35, 36, "to suffer"),
        (37, 40, "the many of"),
        (41, 46, "the most humble part of"),
        (47, 47, "the people"),
        (48, 50, "great persecutions,"),
        (51, 55, "and they waded"),
        (56, 59, "through much affliction."),
    ],
    35: [
        (0, 3, "Nevertheless,"),
        (4, 6, "they fasted"),
        (7, 11, "and prayed continually,"),
        (12, 15, "and grew stronger"),
        (16, 19, "and increased still"),
        (20, 23, "in their humility,"),
        (24, 25, "and firm"),
        (26, 29, "and more firm"),
        (30, 32, "in the faith"),
        (33, 34, "in Christ,"),
        (35, 37, "until"),
        (38, 38, "were filled"),
        (39, 41, "their souls"),
        (42, 44, "with joy"),
        (45, 47, "and comfort,"),
        (48, 48, "yea,"),
        (49, 51, "even until"),
        (52, 52, "were purified"),
        (53, 54, "and sanctified"),
        (55, 57, "their hearts,"),
        (58, 61, "which sanctification"),
        (62, 64, "comes"),
        (65, 66, "because of"),
        (67, 71, "their yielding of"),
        (72, 74, "their hearts"),
        (75, 77, "unto God."),
    ],
    36: [
        (0, 3, "And it came to pass that"),
        (4, 5, "also ended"),
        (6, 8, "the fiftieth"),
        (9, 13, "and second year"),
        (14, 16, "in peace,"),
        (17, 18, "except"),
        (19, 22, "the very great pride"),
        (23, 27, "which entered into"),
        (28, 30, "the hearts of the people;"),
        (31, 34, "and the cause was"),
        (35, 36, "because of"),
        (37, 39, "their riches"),
        (40, 42, "being very great"),
        (43, 46, "and their prosperity"),
        (47, 49, "in"),
        (50, 51, "the land;"),
        (52, 55, "and grew"),
        (56, 58, "upon"),
        (59, 60, "them"),
        (61, 63, "from that day"),
        (64, 66, "to that day."),
    ],
    37: [
        (0, 2, "And it came to pass"),
        (3, 6, "in the fiftieth"),
        (7, 10, "and third year"),
        (11, 14, "of the reign of"),
        (15, 15, "the judges,"),
        (16, 17, "died"),
        (18, 18, "Helaman,"),
        (19, 23, "and began to reign"),
        (24, 28, "his eldest son"),
        (29, 29, "Nephi"),
        (30, 31, "in place"),
        (32, 34, "of him."),
        (35, 38, "And it came to pass that"),
        (39, 41, "he bore"),
        (42, 43, "the judgment-seat"),
        (44, 46, "with justice"),
        (47, 50, "and impartiality;"),
        (51, 51, "yea,"),
        (52, 54, "he kept"),
        (55, 56, "the commandments of"),
        (57, 58, "God,"),
        (59, 63, "and he walked"),
        (64, 66, "in the ways of"),
        (67, 68, "his father."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
