"""Hand-curated TAM-phrase gloss overrides for Iakopo 4 — Atonement / Look beyond the mark."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "jacob"
CHAPTER_NUM = 4
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "Now behold,"),
        (3, 5, "it came to pass"),
        (6, 9, "I, Jacob,"),
        (10, 13, "after"),
        (14, 16, "I taught"),
        (17, 19, "many things"),
        (20, 22, "unto my people"),
        (23, 25, "in word,"),
        (26, 26, "(and"),
        (27, 30, "cannot"),
        (31, 32, "I write"),
        (33, 34, "save"),
        (35, 37, "a small part"),
        (38, 40, "of my words,"),
        (41, 44, "because of the difficulty"),
        (45, 47, "of engraving"),
        (48, 51, "of our words"),
        (52, 53, "upon"),
        (54, 55, "of the plates)"),
        (56, 59, "and we know"),
        (60, 61, "the things"),
        (62, 64, "we have written"),
        (65, 66, "upon"),
        (67, 68, "of the plates"),
        (69, 72, "must be preserved;"),
    ],
    2: [
        (0, 0, "But"),
        (1, 4, "whatsoever thing"),
        (5, 7, "we write"),
        (8, 9, "upon"),
        (10, 14, "of any other thing"),
        (15, 16, "save"),
        (17, 17, "upon"),
        (18, 19, "of the plates,"),
        (20, 23, "shall perish"),
        (24, 26, "and vanish;"),
        (27, 27, "but"),
        (28, 30, "may"),
        (31, 32, "we write"),
        (33, 36, "a few words"),
        (37, 38, "upon"),
        (39, 40, "of the plates,"),
        (41, 44, "to give thereto"),
        (45, 47, "to our children,"),
        (48, 49, "and also"),
        (50, 54, "and to our beloved brethren,"),
        (55, 57, "a small degree"),
        (58, 60, "of knowledge"),
        (61, 62, "concerning"),
        (63, 66, "us,"),
        (67, 70, "or concerning"),
        (71, 73, "their fathers—"),
    ],
    3: [
        (0, 1, "Now"),
        (2, 4, "we rejoice"),
        (5, 7, "in this;"),
        (8, 8, "and"),
        (9, 11, "we labor"),
        (12, 14, "diligently"),
        (15, 16, "to engrave"),
        (17, 18, "these words"),
        (19, 20, "upon"),
        (21, 22, "of the plates,"),
        (23, 25, "in the hope"),
        (26, 29, "shall receive"),
        (30, 34, "by our beloved brethren"),
        (35, 38, "and our children"),
        (39, 40, "these words"),
        (41, 44, "with thankful hearts,"),
        (45, 48, "and look thereto"),
        (49, 52, "that may"),
        (53, 54, "they learn"),
        (55, 57, "with joy"),
        (58, 62, "and not with sorrow,"),
        (63, 67, "neither with contempt,"),
        (68, 69, "concerning"),
        (70, 74, "their first parents."),
    ],
    4: [
        (0, 0, "For,"),
        (1, 4, "this intent"),
        (5, 8, "we have written"),
        (9, 10, "these things,"),
        (11, 14, "that may"),
        (15, 16, "they know"),
        (17, 19, "we knew"),
        (20, 23, "concerning Christ,"),
        (24, 27, "and had"),
        (28, 31, "we"),
        (32, 33, "a hope"),
        (34, 36, "in his glory"),
        (37, 39, "many"),
        (40, 41, "of hundreds"),
        (42, 43, "of years"),
        (44, 49, "before came"),
        (50, 51, "of him;"),
        (52, 55, "and not only"),
        (56, 58, "us"),
        (59, 61, "had"),
        (62, 63, "a hope"),
        (64, 66, "in his glory,"),
        (67, 70, "but also"),
        (71, 73, "all the holy prophets"),
        (74, 78, "who were before"),
        (79, 81, "us."),
    ],
    5: [
        (0, 0, "Behold,"),
        (1, 3, "they believed"),
        (4, 5, "in Christ"),
        (6, 7, "and worshipped"),
        (8, 10, "the Father"),
        (11, 13, "in his name,"),
        (14, 18, "and we also worship"),
        (19, 21, "the Father"),
        (22, 24, "in his name."),
        (25, 25, "And"),
        (26, 29, "for this intent"),
        (30, 33, "we keep thereto"),
        (34, 35, "the law"),
        (36, 37, "of Moses,"),
        (38, 39, "doth point"),
        (40, 42, "our souls"),
        (43, 45, "to him;"),
        (46, 50, "for this reason"),
        (51, 53, "is sanctified thereto"),
        (54, 57, "unto us"),
        (58, 61, "for righteousness,"),
        (62, 65, "even as"),
        (66, 67, "was given"),
        (68, 69, "unto Abraham"),
        (70, 72, "in the wilderness"),
        (73, 74, "to obey"),
        (75, 76, "the commandments"),
        (77, 79, "of the God"),
        (80, 83, "in the offering"),
        (84, 86, "of his son"),
        (87, 88, "Isaac,"),
        (89, 91, "a similitude"),
        (92, 94, "of the God"),
        (95, 100, "and his Only Begotten Son."),
    ],
    6: [
        (0, 3, "Wherefore,"),
        (4, 7, "we search thereto"),
        (8, 9, "the prophets,"),
        (10, 13, "and we have"),
        (14, 16, "many revelations"),
        (17, 19, "and the spirit"),
        (20, 21, "of prophecy;"),
        (22, 22, "and"),
        (23, 26, "having"),
        (27, 30, "all these witnesses"),
        (31, 34, "we obtain thereto"),
        (35, 36, "a hope,"),
        (37, 40, "and unshaken thereto"),
        (41, 43, "our faith,"),
        (44, 49, "until indeed may"),
        (50, 52, "we command"),
        (53, 55, "in the name"),
        (56, 57, "of Jesus"),
        (58, 61, "and the trees obey thereto"),
        (62, 65, "us,"),
        (66, 68, "or the mountains,"),
        (69, 71, "or the waves"),
        (72, 74, "of the sea."),
    ],
    7: [
        (0, 3, "Nevertheless,"),
        (4, 6, "showeth"),
        (7, 10, "unto us"),
        (11, 15, "by the Lord God"),
        (16, 18, "our weakness,"),
        (19, 23, "that may"),
        (24, 25, "we know,"),
        (26, 29, "his grace,"),
        (30, 33, "and his great condescension"),
        (34, 36, "unto the children"),
        (37, 38, "of men,"),
        (39, 42, "we obtain thereto"),
        (43, 44, "the power"),
        (45, 49, "to do these things."),
    ],
    8: [
        (0, 0, "Behold,"),
        (1, 2, "are great"),
        (3, 4, "and marvelous"),
        (5, 5, "the works"),
        (6, 8, "of the Lord."),
        (9, 12, "are unsearchable"),
        (13, 14, "the depths"),
        (15, 17, "of his mysteries;"),
        (18, 21, "and cannot"),
        (22, 24, "by man"),
        (25, 26, "know"),
        (27, 29, "his ways all."),
        (30, 30, "And"),
        (31, 34, "no one"),
        (35, 37, "doth know"),
        (38, 39, "his ways"),
        (40, 41, "save thereto"),
        (42, 43, "is revealed"),
        (44, 46, "unto him;"),
        (47, 50, "wherefore,"),
        (51, 52, "brethren,"),
        (53, 55, "despise not"),
        (56, 57, "the revelations"),
        (58, 60, "of the God."),
    ],
    9: [
        (0, 1, "For behold,"),
        (2, 4, "by the power"),
        (5, 7, "of his word"),
        (8, 11, "came thereto"),
        (12, 13, "man"),
        (14, 15, "upon"),
        (16, 18, "the face of the earth,"),
        (19, 21, "which earth"),
        (22, 23, "was created"),
        (24, 26, "by the power"),
        (27, 29, "of his word."),
        (30, 33, "Wherefore,"),
        (34, 36, "if could"),
        (37, 39, "by the God"),
        (40, 42, "speak"),
        (43, 47, "and so be"),
        (48, 50, "the world,"),
        (51, 53, "and speak"),
        (54, 58, "and so create thereto"),
        (59, 61, "man,"),
        (62, 64, "wherefore,"),
        (65, 70, "why cannot thereto"),
        (71, 72, "command"),
        (73, 75, "the world,"),
        (76, 78, "or the workings"),
        (79, 81, "of his hands"),
        (82, 84, "upon the world,"),
        (85, 89, "according to his will"),
        (90, 92, "and his pleasure?"),
    ],
    10: [
        (0, 3, "Wherefore,"),
        (4, 5, "brethren,"),
        (6, 9, "seek ye not"),
        (10, 11, "to counsel"),
        (12, 13, "the Lord,"),
        (14, 17, "but take"),
        (18, 18, "counsel"),
        (19, 21, "from his hand."),
        (22, 23, "For behold,"),
        (24, 27, "ye yourselves know"),
        (28, 30, "he counsels"),
        (31, 32, "he"),
        (33, 35, "in wisdom,"),
        (36, 38, "and in justice,"),
        (39, 43, "and in great tender mercy,"),
        (44, 47, "in all his works."),
    ],
    11: [
        (0, 3, "Wherefore,"),
        (4, 6, "beloved brethren,"),
        (7, 9, "be ye reconciled"),
        (10, 16, "through the atonement"),
        (17, 18, "of Christ,"),
        (19, 23, "his Only Begotten Son,"),
        (24, 29, "and thus may"),
        (30, 31, "ye obtain"),
        (32, 34, "a resurrection,"),
        (35, 39, "according to the power"),
        (40, 42, "of the resurrection"),
        (43, 45, "which is in Christ,"),
        (46, 50, "and presented"),
        (51, 53, "to the God"),
        (54, 56, "as the first-fruits"),
        (57, 58, "of Christ,"),
        (59, 60, "having faith,"),
        (61, 63, "and having obtained"),
        (64, 66, "a good hope"),
        (67, 69, "of glory"),
        (70, 72, "in him"),
        (73, 76, "before he manifest"),
        (77, 81, "himself"),
        (82, 84, "in the flesh."),
    ],
    12: [
        (0, 2, "And now,"),
        (3, 6, "beloved,"),
        (7, 10, "marvel ye not"),
        (11, 14, "that I tell"),
        (15, 17, "these things"),
        (18, 20, "unto you;"),
        (21, 21, "for"),
        (22, 27, "why should we not speak thereto"),
        (28, 29, "concerning"),
        (30, 32, "of the atonement"),
        (33, 34, "of Christ,"),
        (35, 36, "and seek"),
        (37, 38, "to obtain"),
        (39, 41, "a perfect knowledge"),
        (42, 46, "of him,"),
        (47, 51, "as well as"),
        (52, 53, "we should seek"),
        (54, 55, "to obtain"),
        (56, 57, "a knowledge"),
        (58, 60, "of"),
        (61, 62, "a resurrection"),
        (63, 65, "and the world"),
        (66, 67, "to come?"),
    ],
    13: [
        (0, 0, "Behold,"),
        (1, 3, "my brethren,"),
        (4, 9, "he that prophesieth,"),
        (10, 12, "let"),
        (13, 15, "him"),
        (16, 17, "prophesy"),
        (18, 20, "to the understanding"),
        (21, 22, "of men;"),
        (23, 23, "for"),
        (24, 26, "speaketh"),
        (27, 29, "by the Spirit"),
        (30, 31, "the truth"),
        (32, 36, "and lieth not."),
        (37, 40, "Wherefore,"),
        (41, 45, "speaketh he"),
        (46, 48, "concerning"),
        (49, 49, "things"),
        (50, 56, "as they really are,"),
        (57, 60, "and concerning"),
        (61, 61, "things"),
        (62, 70, "as they really will be;"),
        (71, 74, "wherefore,"),
        (75, 78, "are made manifest"),
        (79, 80, "these things"),
        (81, 84, "unto us,"),
        (85, 87, "for the salvation"),
        (88, 91, "of our souls."),
        (92, 93, "But behold,"),
        (94, 98, "not only us"),
        (99, 100, "witness"),
        (101, 103, "of these things;"),
        (104, 104, "for"),
        (105, 108, "spake also"),
        (109, 111, "by the God"),
        (112, 113, "these things"),
        (114, 116, "unto prophets of old."),
    ],
    14: [
        (0, 1, "But behold,"),
        (2, 4, "were stiffnecked"),
        (5, 6, "the Jews;"),
        (7, 7, "and"),
        (8, 10, "they despised"),
        (11, 13, "the plain words,"),
        (14, 16, "and killed"),
        (17, 17, "the prophets,"),
        (18, 21, "and sought for things"),
        (22, 25, "could not"),
        (26, 29, "they understand."),
        (30, 33, "Wherefore,"),
        (34, 38, "because of their blindness,"),
        (39, 41, "blindness"),
        (42, 44, "came"),
        (45, 48, "by looking"),
        (49, 51, "beyond"),
        (52, 55, "the mark,"),
        (56, 57, "therefore"),
        (58, 63, "they shall fall thereto;"),
        (64, 66, "for hath taken away"),
        (67, 69, "by the God"),
        (70, 71, "his plainness"),
        (72, 76, "from them,"),
        (77, 79, "and delivered"),
        (80, 83, "unto them"),
        (84, 87, "many things"),
        (88, 91, "they cannot"),
        (92, 95, "understand,"),
        (96, 101, "because they desired."),
        (102, 105, "And because"),
        (106, 110, "they desired,"),
        (111, 115, "thereto did"),
        (116, 118, "by the God"),
        (119, 121, "they should stumble."),
    ],
    15: [
        (0, 2, "And now,"),
        (3, 6, "I, Jacob,"),
        (7, 9, "am led"),
        (10, 12, "by the Spirit"),
        (13, 16, "to prophesy;"),
        (17, 17, "for"),
        (18, 20, "I perceive"),
        (21, 24, "by way of the workings"),
        (25, 27, "of the Spirit"),
        (28, 31, "in me,"),
        (32, 34, "by stumbling"),
        (35, 37, "of the Jews"),
        (38, 43, "they shall reject thereto"),
        (44, 45, "the stone"),
        (46, 48, "may"),
        (49, 51, "they build thereto"),
        (52, 53, "upon"),
        (54, 56, "and have thereto"),
        (57, 59, "a safe foundation."),
    ],
    16: [
        (0, 1, "But behold,"),
        (2, 4, "according to"),
        (5, 6, "the scriptures,"),
        (7, 9, "this stone"),
        (10, 16, "shall become a great foundation,"),
        (17, 18, "and the last,"),
        (19, 23, "and the only sure,"),
        (24, 26, "may"),
        (27, 28, "build thereto"),
        (29, 30, "upon"),
        (31, 32, "the Jews."),
    ],
    17: [
        (0, 2, "And now,"),
        (3, 5, "my beloved,"),
        (6, 8, "how can"),
        (9, 12, "they"),
        (13, 16, "after"),
        (17, 18, "they reject"),
        (19, 22, "the sure foundation,"),
        (23, 25, "be able"),
        (26, 27, "to build thereto"),
        (28, 30, "upon it,"),
        (31, 36, "that may become"),
        (37, 39, "their head"),
        (40, 40, "of the corner?"),
    ],
    18: [
        (0, 0, "Behold,"),
        (1, 4, "my beloved brethren,"),
        (5, 10, "I will unfold"),
        (11, 12, "this mystery"),
        (13, 15, "unto you;"),
        (16, 17, "if"),
        (18, 22, "I am not shaken,"),
        (23, 25, "in any way,"),
        (26, 28, "from my firmness"),
        (29, 31, "in the Spirit,"),
        (32, 35, "and stumble thereto"),
        (36, 40, "because of my over-anxiety"),
        (41, 42, "for you."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
