"""
Hand-curated TAM-phrase gloss overrides for 3 Nifae (3 Nephi) 28 — Jesus asks the twelve
disciples what they desire; nine ask to come speedily into his kingdom after they are
seventy-two, and are promised rest. The three who dared not speak desired, like the
beloved John, to tarry and never taste death until he comes again in glory; Jesus grants
it, and they are changed so that they have power over the things of the earth, feel no
pain nor sorrow save for the sins of the world, and are ministered to as translated
beings. Mormon testifies of their continued ministry and forbids further account.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15). `o le a` stays atomic and is never fused with a
following `se X` NP. A handful of cells remain at 6-7 tokens only where a
split would break rule 2 (absorbed subject) or rule 7 (`o le a` + verb +
directional) — those are the mandated irreducible clusters.

    python3 build_overrides_3nephi28.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "3nephi"
CHAPTER_NUM = 28

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 7, "when had spoken"),
        (8, 9, "Jesus"),
        (10, 12, "these words,"),
        (13, 16, "he spake"),
        (17, 19, "unto his disciples"),
        (20, 20, "one by one,"),
        (21, 23, "saying"),
        (24, 27, "unto them:"),
        (28, 30, "What"),
        (31, 32, "the thing"),
        (33, 37, "that ye desire"),
        (38, 38, "of"),
        (39, 41, "me,"),
        (42, 45, "after"),
        (46, 48, "I am gone up"),
        (49, 51, "to the Father."),
    ],
    2: [
        (0, 4, "And they spake"),
        (5, 5, "all,"),
        (6, 7, "save it be"),
        (8, 9, "the three,"),
        (10, 12, "saying:"),
        (13, 15, "We desire"),
        (16, 18, "that may"),
        (19, 21, "we come"),
        (22, 22, "speedily"),
        (23, 25, "unto thee"),
        (26, 28, "in thy kingdom,"),
        (29, 31, "after"),
        (32, 34, "we have lived"),
        (35, 38, "unto the age"),
        (39, 41, "of man,"),
        (42, 44, "that may end"),
        (45, 47, "our ministry,"),
        (48, 48, "wherein"),
        (49, 53, "thou hast called"),
        (54, 55, "us."),
    ],
    3: [
        (0, 4, "And he said"),
        (5, 8, "unto them:"),
        (9, 10, "Blessed are ye"),
        (11, 11, "because"),
        (12, 14, "ye desired"),
        (15, 17, "this thing"),
        (18, 18, "of"),
        (19, 21, "me;"),
        (22, 23, "therefore,"),
        (24, 25, "after"),
        (26, 27, "the seventy"),
        (28, 31, "and two years"),
        (32, 35, "of your life"),
        (36, 41, "ye shall come"),
        (42, 44, "unto me"),
        (45, 47, "in my kingdom;"),
        (48, 48, "and"),
        (49, 53, "ye shall find"),
        (54, 55, "rest"),
        (56, 58, "together with me."),
    ],
    4: [
        (0, 4, "And when had"),
        (5, 7, "he spake"),
        (8, 11, "unto them,"),
        (12, 16, "he turned himself"),
        (17, 19, "unto the three,"),
        (20, 22, "and said"),
        (23, 26, "unto them:"),
        (27, 29, "What"),
        (30, 31, "the thing"),
        (32, 34, "that ye desire"),
        (35, 37, "I should do"),
        (38, 39, "for you"),
        (40, 44, "when I am gone"),
        (45, 47, "unto the Father?"),
    ],
    5: [
        (0, 4, "And they sorrowed"),
        (5, 8, "in their hearts,"),
        (9, 9, "for"),
        (10, 12, "they feared"),
        (13, 15, "to tell"),
        (16, 18, "him"),
        (19, 20, "the thing"),
        (21, 25, "which they desired."),
    ],
    6: [
        (0, 4, "And he said"),
        (5, 8, "unto them:"),
        (9, 9, "Behold,"),
        (10, 12, "I know"),
        (13, 15, "your thoughts,"),
        (16, 19, "and ye have desired"),
        (20, 22, "the thing"),
        (23, 26, "which desired"),
        (27, 27, "John,"),
        (28, 29, "my beloved,"),
        (30, 30, "of"),
        (31, 33, "me,"),
        (34, 37, "who was together"),
        (38, 39, "with me"),
        (40, 42, "in my ministry,"),
        (43, 47, "before I was lifted up"),
        (48, 49, "on high"),
        (50, 52, "by the Jews."),
    ],
    7: [
        (0, 3, "Therefore,"),
        (4, 7, "more blessed are"),
        (8, 9, "ye,"),
        (10, 10, "for"),
        (11, 14, "ye shall"),
        (15, 17, "never taste"),
        (18, 20, "of death;"),
        (21, 21, "but"),
        (22, 26, "ye shall live"),
        (27, 28, "to behold"),
        (29, 31, "all the things"),
        (32, 36, "which the Father doeth"),
        (37, 41, "unto the children of men,"),
        (42, 45, "even until"),
        (46, 48, "all things be fulfilled"),
        (49, 51, "according to"),
        (52, 53, "the will"),
        (54, 56, "of the Father,"),
        (57, 60, "when I shall come"),
        (61, 63, "in my glory"),
        (64, 65, "with"),
        (66, 66, "the powers"),
        (67, 69, "of heaven."),
    ],
    8: [
        (0, 0, "And"),
        (1, 5, "shall never come"),
        (6, 6, "ever"),
        (7, 9, "upon you"),
        (10, 10, "pain"),
        (11, 13, "of death;"),
        (14, 17, "but when I come"),
        (18, 20, "in my glory"),
        (21, 25, "ye shall be changed"),
        (26, 30, "as the twinkling"),
        (31, 33, "of the eye"),
        (34, 37, "from the mortal body"),
        (38, 42, "to the immortal body;"),
        (43, 46, "and then shall be blessed"),
        (47, 48, "ye"),
        (49, 51, "in the kingdom"),
        (52, 54, "of my Father."),
    ],
    9: [
        (0, 0, "And"),
        (1, 5, "I say again,"),
        (6, 10, "there shall not come"),
        (11, 13, "upon you"),
        (14, 15, "pain"),
        (16, 20, "while ye live"),
        (21, 24, "in the flesh,"),
        (25, 28, "nor sorrow,"),
        (29, 30, "save it be"),
        (31, 32, "for"),
        (33, 36, "the sins of the world;"),
        (37, 41, "and all these things"),
        (42, 46, "will I do"),
        (47, 50, "because of the thing"),
        (51, 55, "which ye have desired"),
        (56, 59, "of me,"),
        (60, 63, "for ye have desired"),
        (64, 68, "that ye might bring"),
        (69, 72, "the souls of men"),
        (73, 75, "unto me,"),
        (76, 80, "while yet standeth"),
        (81, 82, "the world."),
    ],
    10: [
        (0, 2, "And because of"),
        (3, 4, "this cause"),
        (5, 10, "ye shall have"),
        (11, 12, "the fulness"),
        (13, 15, "of joy;"),
        (16, 16, "and"),
        (17, 22, "ye shall sit down"),
        (23, 24, "below"),
        (25, 27, "in the kingdom"),
        (28, 30, "of my Father;"),
        (31, 31, "yea,"),
        (32, 35, "shall be full"),
        (36, 38, "your joy,"),
        (39, 41, "even as"),
        (42, 44, "the fulness"),
        (45, 47, "of joy"),
        (48, 50, "hath given"),
        (51, 53, "the Father"),
        (54, 56, "unto me;"),
        (57, 57, "and"),
        (58, 62, "ye shall become"),
        (63, 67, "even as I am,"),
        (68, 72, "and I am even as"),
        (73, 75, "the Father;"),
        (76, 79, "and the Father"),
        (80, 81, "and I"),
        (82, 83, "are one;"),
    ],
    11: [
        (0, 4, "And the Holy Ghost"),
        (5, 6, "beareth record of"),
        (7, 8, "the Father"),
        (9, 10, "and me;"),
        (11, 14, "and giveth"),
        (15, 17, "the Father"),
        (18, 20, "the Holy Ghost"),
        (21, 25, "unto the children of men,"),
        (26, 27, "because of"),
        (28, 28, "me."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 7, "when had spoken"),
        (8, 9, "Jesus"),
        (10, 12, "these words,"),
        (13, 16, "he touched"),
        (17, 20, "them"),
        (21, 22, "every one,"),
        (23, 25, "with his finger"),
        (26, 27, "save it be"),
        (28, 29, "the three"),
        (30, 31, "who"),
        (32, 36, "should tarry,"),
        (37, 43, "and then he departed."),
    ],
    13: [
        (0, 1, "And behold,"),
        (2, 3, "were opened"),
        (4, 5, "the heavens,"),
        (6, 6, "and"),
        (7, 11, "they were caught up"),
        (12, 14, "into heaven,"),
        (15, 16, "and saw"),
        (17, 18, "and heard"),
        (19, 20, "things"),
        (21, 23, "unspeakable."),
    ],
    14: [
        (0, 4, "And they were forbidden"),
        (5, 8, "that they should not utter;"),
        (9, 13, "neither was there given"),
        (14, 17, "unto them"),
        (18, 19, "power"),
        (20, 23, "that they could utter"),
        (24, 25, "the things"),
        (26, 28, "which they saw"),
        (29, 32, "and heard;"),
    ],
    15: [
        (0, 0, "And"),
        (1, 4, "whether they were"),
        (5, 6, "they"),
        (7, 9, "in the body"),
        (10, 14, "or out of the body,"),
        (15, 18, "they could not tell;"),
        (19, 19, "for"),
        (20, 22, "it did seem"),
        (23, 26, "unto them"),
        (27, 31, "like a transfiguration"),
        (32, 34, "of them,"),
        (35, 35, "that"),
        (36, 40, "they were changed"),
        (41, 45, "from this body of flesh"),
        (46, 50, "into an immortal state,"),
        (51, 54, "that could"),
        (55, 56, "they behold"),
        (57, 61, "the things of God."),
    ],
    16: [
        (0, 3, "But it came to pass that"),
        (4, 6, "they did again minister"),
        (7, 11, "upon the face of the earth;"),
        (12, 15, "nevertheless"),
        (16, 20, "they did not teach"),
        (21, 23, "concerning"),
        (24, 25, "the things"),
        (26, 28, "which they heard"),
        (29, 32, "and saw,"),
        (33, 34, "because of"),
        (35, 36, "the commandment"),
        (37, 39, "which was given"),
        (40, 43, "unto them"),
        (44, 46, "in heaven."),
    ],
    17: [
        (0, 2, "And now,"),
        (3, 7, "whether they were"),
        (8, 10, "mortal men"),
        (11, 12, "or"),
        (13, 16, "immortal men,"),
        (17, 19, "from the day"),
        (20, 23, "of their transfiguration,"),
        (24, 27, "I know not;"),
    ],
    18: [
        (0, 4, "But this much"),
        (5, 7, "the thing"),
        (8, 10, "which I know,"),
        (11, 13, "according to"),
        (14, 15, "the record"),
        (16, 18, "which was given—"),
        (19, 22, "they did go forth"),
        (23, 27, "upon the face of the land,"),
        (28, 30, "and did minister"),
        (31, 33, "unto all the people,"),
        (34, 36, "and uniting"),
        (37, 39, "to the church"),
        (40, 43, "as many as"),
        (44, 45, "would believe"),
        (46, 49, "in their preaching;"),
        (50, 51, "and baptizing"),
        (52, 53, "them,"),
        (54, 56, "and as many"),
        (57, 60, "of them"),
        (61, 62, "as were baptized"),
        (63, 65, "did receive"),
        (66, 68, "the Holy Ghost."),
    ],
    19: [
        (0, 4, "And they were cast"),
        (5, 9, "into prison"),
        (10, 14, "by them who"),
        (15, 17, "belonged not"),
        (18, 20, "to the church."),
        (21, 24, "And could not"),
        (25, 26, "the prisons"),
        (27, 28, "hold"),
        (29, 30, "them,"),
        (31, 31, "for"),
        (32, 35, "they were rent in twain."),
    ],
    20: [
        (0, 4, "And they were cast down"),
        (5, 9, "into the earth;"),
        (10, 13, "but they did smite"),
        (14, 15, "the earth"),
        (16, 18, "with the word"),
        (19, 21, "of God,"),
        (22, 24, "insomuch that"),
        (25, 27, "they were delivered"),
        (28, 30, "out of the depths"),
        (31, 33, "of the earth"),
        (34, 36, "by his power;"),
        (37, 39, "and therefore"),
        (40, 44, "could not"),
        (45, 46, "they dig"),
        (47, 48, "pits"),
        (49, 53, "able to hold"),
        (54, 55, "them."),
    ],
    21: [
        (0, 4, "And thrice were cast"),
        (5, 6, "they"),
        (7, 9, "into a furnace"),
        (10, 13, "and were not harmed"),
        (14, 15, "at all."),
    ],
    22: [
        (0, 4, "And twice were cast"),
        (5, 6, "they"),
        (7, 9, "into a den"),
        (10, 12, "of wild beasts;"),
        (13, 14, "and behold"),
        (15, 17, "they did play"),
        (18, 20, "with the wild beasts"),
        (21, 24, "as playeth"),
        (25, 27, "a child"),
        (28, 31, "with a young lamb"),
        (32, 34, "not yet weaned"),
        (35, 37, "from the milk,"),
        (38, 41, "and were not harmed."),
    ],
    23: [
        (0, 4, "And it came to pass that"),
        (5, 8, "they did go forth"),
        (9, 11, "among"),
        (12, 14, "all the people"),
        (15, 16, "of Nephi,"),
        (17, 19, "and did preach"),
        (20, 23, "the gospel of Christ"),
        (24, 26, "unto all people"),
        (27, 31, "upon the face of the land;"),
        (32, 32, "and"),
        (33, 37, "they were converted"),
        (38, 40, "unto the Lord,"),
        (41, 42, "and were united"),
        (43, 47, "unto the church of Christ,"),
        (48, 52, "and thus were blessed"),
        (53, 54, "the people"),
        (55, 57, "of that generation,"),
        (58, 61, "according to"),
        (62, 63, "the word"),
        (64, 65, "of Jesus."),
    ],
    24: [
        (0, 2, "And now,"),
        (3, 4, "I,"),
        (5, 6, "Mormon,"),
        (7, 9, "make an end of"),
        (10, 12, "speaking"),
        (13, 15, "concerning"),
        (16, 17, "these things"),
        (18, 20, "for a time."),
    ],
    25: [
        (0, 0, "Behold,"),
        (1, 2, "I was about"),
        (3, 7, "to write"),
        (8, 8, "the names"),
        (9, 11, "of those"),
        (12, 13, "who"),
        (14, 18, "should never come"),
        (19, 20, "upon"),
        (21, 22, "death,"),
        (23, 23, "but"),
        (24, 25, "it was forbidden"),
        (26, 28, "by the Lord;"),
        (29, 30, "therefore"),
        (31, 35, "I write not"),
        (36, 37, "them,"),
        (38, 38, "for"),
        (39, 42, "they are hid"),
        (43, 45, "from the world."),
    ],
    26: [
        (0, 1, "But behold,"),
        (2, 4, "I have seen"),
        (5, 8, "them,"),
        (9, 13, "and they have ministered"),
        (14, 16, "unto me."),
    ],
    27: [
        (0, 1, "And behold"),
        (2, 6, "shall be"),
        (7, 8, "they"),
        (9, 12, "among the Gentiles,"),
        (13, 13, "and"),
        (14, 18, "shall not know"),
        (19, 20, "them"),
        (21, 22, "the Gentiles."),
    ],
    28: [
        (0, 4, "shall be"),
        (5, 5, "also"),
        (6, 7, "they"),
        (8, 12, "among the Jews,"),
        (13, 13, "and"),
        (14, 18, "shall not know"),
        (19, 20, "them"),
        (21, 23, "the Jews."),
    ],
    29: [
        (0, 0, "And"),
        (1, 5, "shall come to pass"),
        (6, 6, "also,"),
        (7, 9, "when seeth fit"),
        (10, 12, "the Lord"),
        (13, 15, "in his wisdom"),
        (16, 19, "that they shall minister"),
        (20, 22, "unto all the tribes"),
        (23, 24, "of Israel"),
        (25, 26, "which are scattered,"),
        (27, 30, "and unto all nations,"),
        (31, 31, "kindreds,"),
        (32, 32, "tongues"),
        (33, 34, "and people,"),
        (35, 37, "and shall bring"),
        (38, 42, "out of them"),
        (43, 46, "many souls"),
        (47, 48, "unto Jesus,"),
        (49, 51, "that may be fulfilled"),
        (52, 54, "their desire,"),
        (55, 57, "and also because of"),
        (58, 61, "the convincing power also"),
        (62, 64, "of God"),
        (65, 68, "which is within"),
        (69, 70, "them."),
    ],
    30: [
        (0, 4, "And they are like"),
        (5, 9, "the angels of God,"),
        (10, 11, "and if"),
        (12, 15, "they pray"),
        (16, 18, "unto the Father"),
        (19, 23, "in the name of Jesus"),
        (24, 26, "they can"),
        (27, 29, "show forth"),
        (30, 33, "themselves"),
        (34, 37, "unto whatsoever man"),
        (38, 41, "they think good"),
        (42, 45, "unto them."),
    ],
    31: [
        (0, 1, "Therefore,"),
        (2, 6, "they shall work"),
        (7, 8, "great works"),
        (9, 11, "and marvelous,"),
        (12, 15, "before cometh"),
        (16, 18, "the great day"),
        (19, 22, "and drawing nigh"),
        (23, 27, "when shall stand"),
        (28, 30, "all people"),
        (31, 33, "before"),
        (34, 35, "the judgment-seat"),
        (36, 37, "of Christ;"),
    ],
    32: [
        (0, 0, "Yea,"),
        (1, 5, "shall be wrought"),
        (6, 8, "by them"),
        (9, 12, "among the Gentiles"),
        (13, 15, "a great work"),
        (16, 18, "and marvelous,"),
        (19, 22, "before cometh"),
        (23, 25, "that judgment day."),
    ],
    33: [
        (0, 3, "And if it were"),
        (4, 6, "that ye had"),
        (7, 9, "all the scriptures"),
        (10, 14, "which give"),
        (15, 16, "an account"),
        (17, 20, "of all the marvelous works"),
        (21, 22, "of Christ,"),
        (23, 27, "ye would know,"),
        (28, 31, "according to"),
        (32, 32, "the words"),
        (33, 34, "of Christ,"),
        (35, 37, "that these things"),
        (38, 40, "must surely"),
        (41, 43, "come to pass."),
    ],
    34: [
        (0, 2, "And wo be"),
        (3, 5, "unto him"),
        (6, 9, "will not"),
        (10, 11, "hearken"),
        (12, 15, "unto the words of Jesus,"),
        (16, 20, "and also to them"),
        (21, 25, "whom he hath chosen"),
        (26, 28, "and sent"),
        (29, 30, "among"),
        (31, 34, "them;"),
        (35, 39, "for whosoever"),
        (40, 42, "receiveth not"),
        (43, 45, "the words of Jesus"),
        (46, 50, "and the words of those"),
        (51, 54, "whom he hath sent,"),
        (55, 58, "they receive not"),
        (59, 60, "him;"),
        (61, 63, "and therefore"),
        (64, 68, "will not receive"),
        (69, 71, "by him"),
        (72, 73, "them"),
        (74, 77, "at the last day;"),
    ],
    35: [
        (0, 4, "And it were better"),
        (5, 7, "for them"),
        (8, 11, "if it were"),
        (12, 16, "they were not born."),
        (17, 17, "For"),
        (18, 22, "do ye suppose"),
        (23, 27, "that ye can put away"),
        (28, 30, "the justice"),
        (31, 35, "of an offended God,"),
        (36, 39, "who hath been trodden"),
        (40, 41, "down"),
        (42, 45, "under the feet of men,"),
        (46, 49, "that might"),
        (50, 51, "come"),
        (52, 54, "salvation?"),
    ],
    36: [
        (0, 2, "And now"),
        (3, 3, "behold,"),
        (4, 6, "as"),
        (7, 9, "I spake"),
        (10, 11, "concerning"),
        (12, 15, "them"),
        (16, 19, "whom hath chosen"),
        (20, 22, "the Lord,"),
        (23, 23, "yea,"),
        (24, 28, "even the three"),
        (29, 30, "who"),
        (31, 35, "were caught up"),
        (36, 38, "into heaven,"),
        (39, 40, "namely,"),
        (41, 44, "I knew not"),
        (45, 49, "whether they were cleansed"),
        (50, 52, "from mortality"),
        (53, 56, "to immortality—"),
    ],
    37: [
        (0, 1, "But behold,"),
        (2, 4, "from the time"),
        (5, 8, "that I wrote,"),
        (9, 12, "I have inquired"),
        (13, 15, "of the Lord,"),
        (16, 20, "and he hath made manifest"),
        (21, 23, "unto me"),
        (24, 28, "that there must needs be"),
        (29, 30, "a change"),
        (31, 32, "wrought"),
        (33, 36, "upon their bodies,"),
        (37, 38, "or else"),
        (39, 43, "they must taste"),
        (44, 46, "of death;"),
    ],
    38: [
        (0, 1, "Therefore,"),
        (2, 5, "that they might not taste"),
        (6, 7, "they"),
        (8, 10, "of death,"),
        (11, 15, "there was wrought"),
        (16, 17, "a change"),
        (18, 21, "upon their bodies,"),
        (22, 26, "that they might not suffer"),
        (27, 29, "pain"),
        (30, 33, "nor sorrow"),
        (34, 35, "save it be"),
        (36, 37, "for the sins"),
        (38, 40, "of the world."),
    ],
    39: [
        (0, 1, "Now"),
        (2, 4, "this change"),
        (5, 9, "was not equal to that"),
        (10, 14, "which shall come"),
        (15, 18, "at the last day;"),
        (19, 23, "but there was a change"),
        (24, 26, "wrought"),
        (27, 31, "upon them,"),
        (32, 34, "insomuch that"),
        (35, 38, "Satan could not"),
        (39, 43, "have any power"),
        (44, 47, "over them,"),
        (48, 52, "that could not"),
        (53, 54, "he tempt"),
        (55, 56, "them;"),
        (57, 61, "and they were sanctified"),
        (62, 64, "in the flesh,"),
        (65, 69, "they were made holy,"),
        (70, 73, "and could not"),
        (74, 78, "the powers of the earth"),
        (79, 80, "hold"),
        (81, 82, "them."),
    ],
    40: [
        (0, 0, "And"),
        (1, 5, "they were to remain"),
        (6, 8, "in this state"),
        (9, 11, "until"),
        (12, 14, "the judgment day"),
        (15, 16, "of Christ;"),
        (17, 20, "and at that day"),
        (21, 22, "there"),
        (23, 27, "shall come"),
        (28, 32, "upon them"),
        (33, 36, "a greater change,"),
        (37, 38, "and to be received"),
        (39, 43, "into the kingdom"),
        (44, 46, "of the Father"),
        (47, 49, "no more"),
        (50, 52, "to go out,"),
        (53, 55, "but to dwell"),
        (56, 58, "with God"),
        (59, 60, "eternally"),
        (61, 63, "in the heavens."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
