"""
Hand-curated TAM-phrase gloss overrides for 1 Nifae (Nephi) 4.

Same mechanism as the prior chapter scripts. Run AFTER
build_phrase_overrides.py so the hand-curation overlays the auto-glossed
entries for this chapter.

    python3 build_overrides_1nephi4.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "1nephi"
CHAPTER_NUM = 4

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass"),
        (4, 6, "I spake"),
        (7, 9, "unto my brothers,"),
        (10, 11, "saying:"),
        (12, 17, "Let us go up again"),
        (18, 19, "to Jerusalem,"),
        (20, 23, "let us be faithful"),
        (24, 26, "in keeping"),
        (27, 28, "the commandments"),
        (29, 31, "of the Lord;"),
        (32, 33, "for behold"),
        (34, 36, "is greater"),
        (37, 38, "his strength"),
        (39, 42, "than the whole earth,"),
        (43, 47, "then why not greater than"),
        (48, 51, "His strength"),
        (52, 55, "than Laban"),
        (56, 58, "and his fifty,"),
        (59, 59, "yea,"),
        (60, 62, "or his"),
        (63, 65, "tens of thousands?"),
    ],
    2: [
        (0, 5, "Therefore let us go up;"),
        (6, 8, "let us be strong"),
        (9, 12, "like unto Moses;"),
        (13, 15, "for truly"),
        (16, 20, "he spake"),
        (21, 26, "to the waters of the Red Sea"),
        (27, 30, "and they divided"),
        (31, 34, "hither"),
        (35, 38, "and thither,"),
        (39, 42, "and came"),
        (43, 45, "our fathers"),
        (46, 47, "out,"),
        (48, 50, "out of captivity,"),
        (51, 54, "on dry ground,"),
        (55, 58, "and following after"),
        (59, 61, "the armies of Pharaoh,"),
        (62, 64, "and were drowned"),
        (65, 70, "in the waters of the Red Sea."),
    ],
    3: [
        (0, 2, "Now behold"),
        (3, 5, "ye know"),
        (6, 9, "this thing is true;"),
        (10, 14, "and ye also know"),
        (15, 17, "had spoken"),
        (18, 19, "an angel"),
        (20, 22, "unto you;"),
        (23, 26, "wherefore"),
        (27, 30, "how can it be"),
        (31, 33, "ye doubt?"),
        (34, 38, "Let us go up;"),
        (39, 40, "is able"),
        (41, 43, "the Lord"),
        (44, 47, "to deliver us,"),
        (48, 51, "even as"),
        (52, 54, "our fathers,"),
        (55, 57, "and destroy Laban,"),
        (58, 61, "even as"),
        (62, 63, "the Egyptians."),
    ],
    4: [
        (0, 1, "Now"),
        (2, 5, "when had finished"),
        (6, 8, "I had spoken"),
        (9, 11, "these words,"),
        (12, 15, "they were still angry,"),
        (16, 19, "and they still murmured;"),
        (20, 23, "nevertheless"),
        (24, 27, "they did follow"),
        (28, 30, "me"),
        (31, 33, "until"),
        (34, 35, "we came"),
        (36, 39, "to the walls of Jerusalem."),
    ],
    5: [
        (0, 3, "And by night"),
        (4, 6, "was done;"),
        (7, 11, "and I caused"),
        (12, 14, "them to hide"),
        (15, 16, "without the walls."),
        (17, 21, "And after"),
        (22, 23, "they had hid,"),
        (24, 25, "I,"),
        (26, 27, "Nephi,"),
        (28, 31, "did creep into"),
        (32, 34, "the city"),
        (35, 38, "and I went"),
        (39, 39, "toward"),
        (40, 44, "the house of Laban."),
    ],
    6: [
        (0, 3, "And I was led"),
        (4, 6, "by the Spirit,"),
        (7, 11, "knowing not"),
        (12, 12, "beforehand"),
        (13, 13, "things"),
        (14, 18, "I should do."),
    ],
    7: [
        (0, 3, "Nevertheless"),
        (4, 7, "I went,"),
        (8, 13, "and as I came near"),
        (14, 18, "to the house of Laban"),
        (19, 21, "I beheld"),
        (22, 23, "a man,"),
        (24, 28, "and he had fallen"),
        (29, 31, "to the earth"),
        (32, 34, "before me,"),
        (35, 39, "for he was drunken"),
        (40, 42, "with wine."),
    ],
    8: [
        (0, 5, "And when I came"),
        (6, 8, "to him"),
        (9, 13, "I knew he was"),
        (14, 15, "Laban."),
    ],
    9: [
        (0, 4, "And I beheld"),
        (5, 7, "his sword,"),
        (8, 11, "and I drew it"),
        (12, 16, "from out of its sheath;"),
        (17, 20, "and the hilt of it"),
        (21, 26, "was made of pure gold,"),
        (27, 30, "and the workmanship of it"),
        (31, 34, "was exceedingly fine;"),
        (35, 38, "and I saw"),
        (39, 44, "that its blade was of steel"),
        (45, 48, "of the most precious."),
    ],
    10: [
        (0, 3, "And it came to pass"),
        (4, 5, "I was constrained"),
        (6, 8, "by the Spirit"),
        (9, 11, "that I should kill"),
        (12, 13, "Laban;"),
        (14, 16, "but I"),
        (17, 21, "said in my heart:"),
        (22, 28, "Never at any time"),
        (29, 32, "have I shed"),
        (33, 34, "the blood"),
        (35, 37, "of a man."),
        (38, 41, "And I shrunk"),
        (42, 43, "and would"),
        (44, 47, "that I might not slay"),
        (48, 50, "him."),
    ],
    11: [
        (0, 4, "And again spoke"),
        (5, 6, "the Spirit"),
        (7, 9, "unto me:"),
        (10, 10, "Behold"),
        (11, 15, "hath delivered him"),
        (16, 18, "the Lord"),
        (19, 21, "into thy hands."),
        (22, 22, "Yea,"),
        (23, 27, "and I also knew"),
        (28, 31, "he had sought"),
        (32, 33, "to take away"),
        (34, 36, "mine own life;"),
        (37, 37, "yea,"),
        (38, 44, "and he would not hearken"),
        (45, 49, "unto the commandments of the Lord;"),
        (50, 55, "and he had also taken"),
        (56, 58, "our property."),
    ],
    12: [
        (0, 3, "And it came to pass"),
        (4, 6, "again spoke"),
        (7, 8, "the Spirit"),
        (9, 11, "unto me:"),
        (12, 12, "Slay"),
        (13, 15, "him,"),
        (16, 21, "for hath delivered him"),
        (22, 24, "the Lord"),
        (25, 27, "into thy hands;"),
    ],
    13: [
        (0, 0, "Behold"),
        (1, 2, "slayeth"),
        (3, 5, "the Lord"),
        (6, 7, "the wicked"),
        (8, 10, "to bring about"),
        (11, 13, "his righteous purposes."),
        (14, 17, "It is better that perish"),
        (18, 22, "one man"),
        (23, 25, "than that"),
        (26, 28, "dwindle and perish"),
        (29, 30, "a nation"),
        (31, 34, "in unbelief."),
    ],
    14: [
        (0, 2, "And now,"),
        (3, 6, "after"),
        (7, 8, "had heard"),
        (9, 10, "I,"),
        (11, 12, "Nephi,"),
        (13, 15, "these words,"),
        (16, 18, "I remembered"),
        (19, 22, "the words of the Lord"),
        (23, 28, "which he had spoken"),
        (29, 31, "unto me"),
        (32, 34, "in the wilderness,"),
        (35, 36, "saying:"),
        (37, 40, "Inasmuch as"),
        (41, 42, "the keeping"),
        (43, 45, "by thy seed"),
        (46, 48, "of my commandments,"),
        (49, 53, "they shall prosper"),
        (54, 56, "in the land"),
        (57, 59, "of promise."),
    ],
    15: [
        (0, 0, "Yea,"),
        (1, 5, "and I also thought"),
        (6, 11, "that they could not keep"),
        (12, 12, "the commandments"),
        (13, 15, "of the Lord"),
        (16, 18, "according to"),
        (19, 22, "the law of Moses,"),
        (23, 23, "save"),
        (24, 28, "they should have"),
        (29, 30, "the law."),
    ],
    16: [
        (0, 4, "And I also knew"),
        (5, 6, "was engraven"),
        (7, 8, "the law"),
        (9, 11, "upon"),
        (12, 13, "plates of brass."),
    ],
    17: [
        (0, 3, "And again,"),
        (4, 6, "I knew"),
        (7, 10, "had delivered Laban"),
        (11, 13, "the Lord"),
        (14, 16, "into my hands"),
        (17, 20, "for this cause—"),
        (21, 23, "that I might obtain"),
        (24, 24, "the records"),
        (25, 29, "according to his commandments."),
    ],
    18: [
        (0, 5, "Therefore I did obey"),
        (6, 8, "unto the voice"),
        (9, 11, "of the Spirit,"),
        (12, 14, "and took"),
        (15, 16, "Laban"),
        (17, 21, "by the hair of his head,"),
        (22, 25, "and I smote off"),
        (26, 27, "his head"),
        (28, 31, "with his own sword."),
    ],
    19: [
        (0, 4, "And after"),
        (5, 7, "I had smitten off"),
        (8, 10, "his head"),
        (11, 14, "with his own sword,"),
        (15, 17, "I took"),
        (18, 20, "the garments of Laban"),
        (21, 23, "and put them on"),
        (24, 27, "upon mine own body;"),
        (28, 28, "yea,"),
        (29, 32, "every whit;"),
        (33, 36, "and I did gird on"),
        (37, 38, "his armor"),
        (39, 41, "about my loins."),
    ],
    20: [
        (0, 4, "And after"),
        (5, 6, "I had done"),
        (7, 9, "this thing,"),
        (10, 13, "I went"),
        (14, 15, "before"),
        (16, 18, "unto the place"),
        (19, 22, "where were kept the treasures"),
        (23, 24, "of Laban."),
        (25, 28, "And as I went"),
        (29, 31, "forth before"),
        (32, 32, "toward"),
        (33, 35, "the place"),
        (36, 39, "where the treasures were kept"),
        (40, 41, "of Laban,"),
        (42, 42, "behold,"),
        (43, 46, "I saw"),
        (47, 51, "the servant of Laban"),
        (52, 56, "who had"),
        (57, 57, "the keys"),
        (58, 60, "of the place"),
        (61, 64, "where the treasures were kept."),
        (65, 70, "And I commanded him"),
        (71, 75, "in the voice of Laban,"),
        (76, 81, "that he should go"),
        (82, 84, "with me"),
        (85, 87, "to the place"),
        (88, 91, "where were kept the treasures."),
    ],
    21: [
        (0, 4, "And he thought"),
        (5, 6, "I"),
        (7, 9, "was his master,"),
        (10, 11, "Laban,"),
        (12, 17, "for he saw"),
        (18, 19, "the garments"),
        (20, 23, "and also the sword"),
        (24, 25, "girded"),
        (26, 28, "about my loins."),
    ],
    22: [
        (0, 5, "And he spake"),
        (6, 8, "unto me"),
        (9, 11, "concerning"),
        (12, 14, "the elders of the Jews,"),
        (15, 17, "knowing"),
        (18, 20, "that his master,"),
        (21, 22, "Laban,"),
        (23, 25, "was"),
        (26, 28, "out with"),
        (29, 31, "them"),
        (32, 34, "by night."),
    ],
    23: [
        (0, 4, "And I spake"),
        (5, 7, "unto him"),
        (8, 9, "as if"),
        (10, 11, "Laban."),
    ],
    24: [
        (0, 5, "And I also said"),
        (6, 8, "unto him"),
        (9, 13, "that I should take"),
        (14, 14, "the engravings"),
        (15, 17, "which were upon"),
        (18, 20, "plates of brass,"),
        (21, 24, "to my elder brothers,"),
        (25, 29, "who were without"),
        (30, 32, "the walls."),
    ],
    25: [
        (0, 6, "And I also commanded him"),
        (7, 9, "to follow"),
        (10, 12, "me."),
    ],
    26: [
        (0, 2, "And he,"),
        (3, 5, "supposing"),
        (6, 9, "I had spoken"),
        (10, 11, "concerning"),
        (12, 16, "the brothers of the church,"),
        (17, 19, "and that I"),
        (20, 22, "was truly Laban"),
        (23, 23, "that"),
        (24, 28, "whom I had slain,"),
        (29, 32, "wherefore"),
        (33, 38, "he did follow"),
        (39, 41, "me."),
    ],
    27: [
        (0, 5, "And he spake"),
        (6, 8, "unto me"),
        (9, 12, "many times"),
        (13, 14, "concerning"),
        (15, 18, "the elders of the Jews,"),
        (19, 22, "as I went"),
        (23, 25, "to my brothers,"),
        (26, 30, "who were without the walls."),
    ],
    28: [
        (0, 3, "And it came to pass"),
        (4, 7, "when Laman saw"),
        (8, 10, "me"),
        (11, 15, "he was exceedingly frightened,"),
        (16, 21, "and likewise Lemuel and Sam."),
        (22, 28, "And they fled from my presence;"),
        (29, 34, "for they supposed it was Laban,"),
        (35, 39, "and had slain me"),
        (40, 43, "and had sought also"),
        (44, 45, "to take away"),
        (46, 48, "their lives."),
    ],
    29: [
        (0, 3, "And it came to pass"),
        (4, 6, "I called"),
        (7, 10, "unto them,"),
        (11, 16, "and they heard me;"),
        (17, 20, "wherefore"),
        (21, 26, "they did cease to flee"),
        (27, 29, "from my presence."),
    ],
    30: [
        (0, 3, "And it came to pass"),
        (4, 6, "when saw"),
        (7, 10, "the servant of Laban"),
        (11, 13, "my brothers"),
        (14, 19, "he began to tremble,"),
        (20, 26, "and was about to flee"),
        (27, 30, "away from my presence"),
        (31, 33, "and return"),
        (34, 38, "into the city of Jerusalem."),
    ],
    31: [
        (0, 2, "And now,"),
        (3, 4, "I,"),
        (5, 6, "Nephi,"),
        (7, 9, "being"),
        (10, 14, "a man large in stature,"),
        (15, 19, "and had also obtained"),
        (20, 22, "much strength"),
        (23, 25, "from the Lord,"),
        (26, 32, "therefore I did seize upon"),
        (33, 37, "the servant of Laban,"),
        (38, 41, "and held him,"),
        (42, 47, "that he should not flee."),
    ],
    32: [
        (0, 3, "And it came to pass"),
        (4, 6, "I said"),
        (7, 9, "unto him,"),
        (10, 15, "if he would hearken"),
        (16, 18, "unto my words,"),
        (19, 24, "as liveth the Lord,"),
        (25, 31, "and as also I live,"),
        (32, 34, "thus"),
        (35, 36, "if"),
        (37, 41, "he would hearken"),
        (42, 44, "unto our words,"),
        (45, 47, "we would spare"),
        (48, 49, "his life."),
    ],
    33: [
        (0, 4, "And I spake"),
        (5, 7, "unto him,"),
        (8, 11, "with an oath,"),
        (12, 18, "that he need not fear;"),
        (19, 22, "should be he"),
        (23, 25, "a free man"),
        (26, 30, "like unto us"),
        (31, 32, "if"),
        (33, 37, "he would go down"),
        (38, 40, "into the wilderness"),
        (41, 44, "with us."),
    ],
    34: [
        (0, 5, "And I also said"),
        (6, 8, "unto him,"),
        (9, 11, "saying:"),
        (12, 14, "Surely"),
        (15, 16, "hath commanded"),
        (17, 18, "us"),
        (19, 21, "the Lord"),
        (22, 25, "to do this thing;"),
        (26, 30, "and shall not we"),
        (31, 33, "be diligent"),
        (34, 36, "in keeping"),
        (37, 38, "the commandments"),
        (39, 41, "of the Lord?"),
        (42, 43, "Therefore,"),
        (44, 47, "if thou wilt go down"),
        (48, 51, "into the wilderness"),
        (52, 54, "to my father"),
        (55, 60, "thou shalt have a place"),
        (61, 64, "with us."),
    ],
    35: [
        (0, 3, "And it came to pass"),
        (4, 5, "Zoram took courage"),
        (6, 8, "at the words"),
        (9, 12, "I had spoken."),
        (13, 15, "Now Zoram"),
        (16, 18, "was the name"),
        (19, 23, "of the servant;"),
        (24, 28, "and he promised"),
        (29, 35, "that he would go down"),
        (36, 38, "into the wilderness"),
        (39, 42, "unto our father."),
        (43, 43, "Yea,"),
        (44, 49, "and he also swore"),
        (50, 51, "an oath"),
        (52, 55, "unto us"),
        (56, 61, "that he would tarry"),
        (62, 65, "with us"),
        (66, 69, "from that time"),
        (70, 75, "henceforth."),
    ],
    36: [
        (0, 4, "Now we were desirous"),
        (5, 8, "that he should tarry"),
        (9, 12, "with us"),
        (13, 16, "for this cause,"),
        (17, 20, "that not know"),
        (21, 23, "the Jews"),
        (24, 26, "concerning"),
        (27, 29, "our flight"),
        (30, 32, "into the wilderness,"),
        (33, 35, "lest they pursue"),
        (36, 38, "after us"),
        (39, 42, "and destroy us."),
    ],
    37: [
        (0, 3, "And it came to pass"),
        (4, 6, "when had given"),
        (7, 10, "Zoram"),
        (11, 12, "an oath"),
        (13, 16, "unto us,"),
        (17, 21, "our fears did cease"),
        (22, 23, "concerning"),
        (24, 26, "him."),
    ],
    38: [
        (0, 3, "And it came to pass"),
        (4, 5, "we took"),
        (6, 7, "the plates of brass"),
        (8, 12, "and the servant of Laban,"),
        (13, 15, "and departed"),
        (16, 18, "into the wilderness,"),
        (19, 21, "and we journeyed"),
        (22, 24, "to the tent"),
        (25, 28, "of our father."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
