"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 48 — Amalickiah stirs
the Lamanites to war and seeks to reign over all the land; Moroni prepares the
Nephites with fortifications and faith; the character of Moroni is extolled;
the Nephites' aim is only to defend, not to gain power.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_alma48.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 48

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 10, "as soon as had gained"),
        (11, 12, "Amalickiah"),
        (13, 15, "the kingdom,"),
        (16, 20, "he began"),
        (21, 22, "to stir up"),
        (23, 24, "the hearts of"),
        (25, 26, "the Lamanites"),
        (27, 29, "against"),
        (30, 32, "the people of Nephi;"),
        (33, 33, "yea,"),
        (34, 36, "he appointed"),
        (37, 37, "men"),
        (38, 40, "to speak"),
        (41, 43, "to the Lamanites"),
        (44, 45, "from"),
        (46, 48, "their towers,"),
        (49, 50, "against"),
        (51, 53, "the Nephites."),
    ],
    2: [
        (0, 5, "And thus he stirred up"),
        (6, 8, "their hearts"),
        (9, 10, "against"),
        (11, 13, "the Nephites,"),
        (14, 16, "insomuch that"),
        (17, 19, "he also sought"),
        (20, 22, "in the latter end"),
        (23, 29, "of the nineteenth"),
        (30, 31, "year"),
        (32, 36, "of the reign of the judges,"),
        (37, 41, "when he had accomplished"),
        (42, 44, "his designs"),
        (45, 48, "up to"),
        (49, 51, "that time,"),
        (52, 52, "yea,"),
        (53, 57, "when he became"),
        (58, 59, "a king"),
        (60, 62, "of the Lamanites,"),
        (63, 66, "he also endeavored"),
        (67, 68, "to reign"),
        (69, 71, "over"),
        (72, 74, "the whole land,"),
        (75, 75, "yea,"),
        (76, 79, "and all the people"),
        (80, 82, "who were"),
        (83, 85, "in the land,"),
        (86, 88, "the Nephites"),
        (89, 90, "as well"),
        (91, 93, "and the Lamanites."),
    ],
    3: [
        (0, 1, "Therefore"),
        (2, 5, "he accomplished"),
        (6, 7, "his design,"),
        (8, 11, "for he hardened"),
        (12, 13, "the hearts of"),
        (14, 15, "the Lamanites"),
        (16, 17, "and blinded"),
        (18, 20, "their minds,"),
        (21, 24, "and stirred up anger"),
        (25, 28, "in them,"),
        (29, 31, "insomuch that"),
        (32, 33, "he gathered"),
        (34, 37, "a great army"),
        (38, 40, "to go"),
        (41, 43, "to fight against"),
        (44, 46, "the Nephites."),
    ],
    4: [
        (0, 4, "For he was determined,"),
        (5, 6, "because of"),
        (7, 9, "the greatness of"),
        (10, 12, "the number of"),
        (13, 14, "his people,"),
        (15, 16, "to overpower"),
        (17, 18, "the Nephites"),
        (19, 20, "and to bring"),
        (21, 22, "them"),
        (23, 25, "into bondage."),
    ],
    5: [
        (0, 5, "And thus he appointed"),
        (6, 8, "chief captains"),
        (9, 12, "of the Zoramites,"),
        (13, 19, "for they best knew"),
        (20, 22, "the strength of"),
        (23, 24, "the Nephites,"),
        (25, 27, "and their"),
        (28, 30, "fortified refuges,"),
        (31, 32, "and the parts"),
        (33, 35, "weakest"),
        (36, 39, "of their cities;"),
        (40, 41, "therefore"),
        (42, 45, "he appointed"),
        (46, 47, "them"),
        (48, 50, "to become"),
        (51, 52, "chief captains"),
        (53, 55, "over his armies."),
    ],
    6: [
        (0, 3, "And it came to pass that"),
        (4, 5, "they took"),
        (6, 8, "their camp,"),
        (9, 11, "and headed"),
        (12, 15, "to the land of"),
        (16, 16, "Zarahemla"),
        (17, 19, "in the wilderness."),
    ],
    7: [
        (0, 1, "Now"),
        (2, 5, "it came to pass that"),
        (6, 8, "while was gaining"),
        (9, 10, "Amalickiah"),
        (11, 12, "power"),
        (13, 15, "by means of"),
        (16, 17, "lying"),
        (18, 20, "and deceit,"),
        (21, 22, "Moroni,"),
        (23, 26, "on the other side,"),
        (27, 28, "was preparing"),
        (29, 30, "the minds of"),
        (31, 31, "the people"),
        (32, 33, "to be faithful"),
        (34, 36, "to the Lord"),
        (37, 39, "their God."),
    ],
    8: [
        (0, 0, "Yea,"),
        (1, 3, "he strengthened"),
        (4, 5, "the armies of"),
        (6, 7, "the Nephites,"),
        (8, 9, "and building"),
        (10, 12, "small towers,"),
        (13, 14, "or"),
        (15, 18, "fortified refuges;"),
        (19, 22, "and raising up"),
        (23, 24, "banks of earth"),
        (25, 25, "round about"),
        (26, 28, "to protect"),
        (29, 30, "within"),
        (31, 32, "his armies,"),
        (33, 35, "and also building"),
        (36, 37, "stone walls"),
        (38, 41, "to surround round about"),
        (42, 43, "them,"),
        (44, 46, "round about"),
        (47, 49, "their cities"),
        (50, 52, "and the borders of"),
        (53, 55, "their lands;"),
        (56, 56, "yea,"),
        (57, 59, "round about"),
        (60, 62, "the whole land."),
    ],
    9: [
        (0, 1, "And in"),
        (2, 4, "their strongholds"),
        (5, 8, "which were weakest"),
        (9, 12, "he placed"),
        (13, 15, "the greater number of"),
        (16, 16, "men;"),
        (17, 22, "and thus he fortified"),
        (23, 24, "and strengthened"),
        (25, 26, "the land"),
        (27, 27, "which"),
        (28, 29, "was held"),
        (30, 32, "by the Nephites."),
    ],
    10: [
        (0, 5, "And thus he prepared"),
        (6, 7, "to support"),
        (8, 10, "their liberty,"),
        (11, 13, "their lands,"),
        (14, 16, "their wives,"),
        (17, 20, "and their children,"),
        (21, 24, "and their peace,"),
        (25, 31, "and that they might live"),
        (32, 34, "for the Lord"),
        (35, 37, "their God,"),
        (38, 44, "and that they might maintain"),
        (45, 47, "the thing"),
        (48, 49, "was called"),
        (50, 53, "by their enemies"),
        (54, 57, "the cause of"),
        (58, 60, "the Christians."),
    ],
    11: [
        (0, 2, "And Moroni"),
        (3, 5, "was a man"),
        (6, 6, "strong"),
        (7, 9, "and very mighty;"),
        (10, 14, "he was a man"),
        (15, 16, "having complete"),
        (17, 18, "understanding;"),
        (19, 19, "yea,"),
        (20, 22, "a man"),
        (23, 25, "who did not delight"),
        (26, 29, "in the shedding of blood;"),
        (30, 32, "a man"),
        (33, 34, "whose rejoiced"),
        (35, 36, "soul"),
        (37, 40, "in the free choice"),
        (41, 44, "and the freedom of"),
        (45, 46, "his country,"),
        (47, 49, "and his brethren"),
        (50, 51, "from"),
        (52, 53, "bondage"),
        (54, 56, "and enslavement;"),
    ],
    12: [
        (0, 0, "Yea,"),
        (1, 3, "a man"),
        (4, 5, "whose was filled"),
        (6, 7, "heart"),
        (8, 10, "with thanks"),
        (11, 13, "to his God,"),
        (14, 15, "for privileges"),
        (16, 19, "and many blessings"),
        (20, 23, "which he laid"),
        (24, 26, "upon"),
        (27, 28, "his people;"),
        (29, 31, "a man"),
        (32, 35, "who labored greatly"),
        (36, 38, "for the welfare"),
        (39, 41, "and the safety"),
        (42, 44, "of his people."),
    ],
    13: [
        (0, 0, "Yea,"),
        (1, 3, "and he"),
        (4, 6, "was a man"),
        (7, 8, "who was steadfast"),
        (9, 11, "in the faith"),
        (12, 13, "in Christ,"),
        (14, 18, "and he swore"),
        (19, 21, "with an oath"),
        (22, 24, "to defend"),
        (25, 26, "his people,"),
        (27, 28, "his rights,"),
        (29, 31, "and his country,"),
        (32, 34, "and his worship,"),
        (35, 38, "even unto"),
        (39, 42, "the shedding of"),
        (43, 44, "his blood."),
    ],
    14: [
        (0, 1, "Now"),
        (2, 3, "were taught"),
        (4, 5, "the Nephites"),
        (6, 7, "to defend"),
        (8, 10, "themselves"),
        (11, 13, "against"),
        (14, 16, "their enemies,"),
        (17, 20, "even unto"),
        (21, 23, "the shedding of"),
        (24, 25, "blood"),
        (26, 30, "if it were necessary;"),
        (31, 31, "yea,"),
        (32, 37, "and they were also taught"),
        (38, 41, "never to"),
        (42, 45, "cause a disturbance,"),
        (46, 46, "yea,"),
        (47, 50, "and never to"),
        (51, 53, "raise the sword"),
        (54, 55, "except"),
        (56, 60, "to withstand against"),
        (61, 63, "an enemy,"),
        (64, 65, "except"),
        (66, 70, "it be for the preserving of"),
        (71, 73, "their lives."),
    ],
    15: [
        (0, 0, "And"),
        (1, 5, "this is their faith,"),
        (6, 7, "that is"),
        (8, 12, "by their so doing"),
        (13, 17, "would bless"),
        (18, 19, "them"),
        (20, 22, "God"),
        (23, 25, "in the land,"),
        (26, 27, "or thus,"),
        (28, 31, "if they are faithful"),
        (32, 35, "in the keeping of"),
        (36, 37, "the commandments of"),
        (38, 39, "God"),
        (40, 44, "he would bless"),
        (45, 46, "them"),
        (47, 49, "in the land;"),
        (50, 50, "yea,"),
        (51, 51, "warn"),
        (52, 53, "them"),
        (54, 56, "to flee away,"),
        (57, 59, "or to prepare"),
        (60, 62, "for war,"),
        (63, 65, "according to"),
        (66, 68, "their protection;"),
    ],
    16: [
        (0, 2, "And also,"),
        (3, 7, "would make known"),
        (8, 10, "God"),
        (11, 14, "unto them"),
        (15, 16, "the place"),
        (17, 21, "they should go"),
        (22, 24, "to defend"),
        (25, 26, "themselves"),
        (27, 29, "against"),
        (30, 32, "their enemies,"),
        (33, 36, "and by their"),
        (37, 38, "so doing,"),
        (39, 43, "would deliver"),
        (44, 45, "them"),
        (46, 48, "the Lord;"),
        (49, 53, "and this is the faith"),
        (54, 55, "of Moroni,"),
        (56, 60, "and rejoiced in it"),
        (61, 62, "his heart"),
        (63, 65, "in that thing;"),
        (66, 68, "not in"),
        (69, 71, "the shedding of"),
        (72, 73, "blood"),
        (74, 75, "but in"),
        (76, 78, "the doing of"),
        (79, 80, "good things,"),
        (81, 84, "in the preserving of"),
        (85, 86, "his people,"),
        (87, 87, "yea,"),
        (88, 91, "in the keeping of"),
        (92, 93, "the commandments of"),
        (94, 95, "God,"),
        (96, 96, "yea,"),
        (97, 101, "and resisting"),
        (102, 103, "iniquity."),
    ],
    17: [
        (0, 0, "Yea,"),
        (1, 2, "verily,"),
        (3, 4, "verily,"),
        (5, 8, "I say"),
        (9, 11, "unto you,"),
        (12, 14, "if had been like"),
        (15, 16, "all men"),
        (17, 19, "who were,"),
        (20, 23, "and who"),
        (24, 25, "are,"),
        (26, 31, "and would be"),
        (32, 32, "always,"),
        (33, 35, "like"),
        (36, 36, "Moroni,"),
        (37, 37, "behold,"),
        (38, 41, "would have been shaken"),
        (42, 44, "the powers of hell"),
        (45, 46, "for ever;"),
        (47, 47, "yea,"),
        (48, 53, "there would be no power"),
        (54, 56, "of the devil"),
        (57, 59, "over"),
        (60, 60, "the hearts"),
        (61, 64, "of the children of"),
        (65, 65, "men."),
    ],
    18: [
        (0, 0, "Behold,"),
        (1, 5, "he was a man"),
        (6, 8, "like"),
        (9, 9, "Ammon,"),
        (10, 12, "the son of"),
        (13, 13, "Mosiah,"),
        (14, 14, "yea,"),
        (15, 18, "and also the other sons"),
        (19, 20, "of Mosiah,"),
        (21, 21, "yea,"),
        (22, 24, "and also Alma"),
        (25, 27, "and his sons,"),
        (28, 32, "for all of them were"),
        (33, 36, "men of"),
        (37, 38, "God."),
    ],
    19: [
        (0, 1, "Now"),
        (2, 2, "behold,"),
        (3, 6, "was not less"),
        (7, 8, "the service"),
        (9, 10, "of Helaman"),
        (11, 13, "and his brethren"),
        (14, 16, "to the people"),
        (17, 18, "than"),
        (19, 19, "Moroni;"),
        (20, 24, "for they preached"),
        (25, 27, "the word of"),
        (28, 29, "God,"),
        (30, 33, "and they baptized"),
        (34, 36, "unto repentance"),
        (37, 38, "all men"),
        (39, 42, "whosoever"),
        (43, 45, "wished to listen"),
        (46, 48, "to their words."),
    ],
    20: [
        (0, 4, "And thus they"),
        (5, 6, "went forth,"),
        (7, 9, "and humbled"),
        (10, 11, "the people"),
        (12, 14, "themselves"),
        (15, 16, "because of"),
        (17, 19, "their words,"),
        (20, 22, "insomuch that"),
        (23, 25, "were greatly favored"),
        (26, 27, "they"),
        (28, 30, "by the Lord,"),
        (31, 36, "and thus were made free"),
        (37, 38, "they"),
        (39, 40, "from wars"),
        (41, 42, "and contentions"),
        (43, 45, "among"),
        (46, 48, "themselves,"),
        (49, 49, "yea,"),
        (50, 54, "for the space of"),
        (55, 57, "the four years."),
    ],
    21: [
        (0, 0, "Nevertheless,"),
        (1, 3, "as"),
        (4, 6, "I have said,"),
        (7, 9, "the latter end"),
        (10, 16, "of the nineteenth"),
        (17, 18, "year,"),
        (19, 19, "yea,"),
        (20, 23, "notwithstanding"),
        (24, 26, "their peace"),
        (27, 29, "among"),
        (30, 32, "themselves,"),
        (33, 37, "they were reluctantly compelled"),
        (38, 40, "to fight with"),
        (41, 43, "their brethren,"),
        (44, 46, "the Lamanites."),
    ],
    22: [
        (0, 0, "Yea,"),
        (1, 4, "and in summary,"),
        (5, 8, "were never stopped"),
        (9, 11, "their wars"),
        (12, 14, "with the Lamanites"),
        (15, 18, "for the space of"),
        (19, 22, "many years,"),
        (23, 25, "notwithstanding"),
        (26, 29, "their great reluctance."),
    ],
    23: [
        (0, 1, "Now,"),
        (2, 4, "they were sorrowful"),
        (5, 7, "to raise up"),
        (8, 8, "weapons"),
        (9, 10, "against"),
        (11, 13, "the Lamanites,"),
        (14, 18, "because they delighted not"),
        (19, 22, "in the shedding of"),
        (23, 24, "blood;"),
        (25, 25, "yea,"),
        (26, 30, "and it was not the only"),
        (31, 31, "thing—"),
        (32, 34, "they grieved"),
        (35, 39, "to become the means"),
        (40, 43, "of sending forth"),
        (44, 45, "away"),
        (46, 48, "the many of"),
        (49, 51, "their brethren"),
        (52, 54, "from this world"),
        (55, 58, "into an eternal world,"),
        (59, 61, "not being prepared"),
        (62, 64, "to meet"),
        (65, 67, "their God."),
    ],
    24: [
        (0, 3, "Nevertheless,"),
        (4, 8, "they could not"),
        (9, 10, "give up"),
        (11, 13, "their lives,"),
        (14, 16, "that be slain"),
        (17, 19, "their wives"),
        (20, 23, "and their children"),
        (24, 27, "by the savage cruelty"),
        (28, 30, "of those"),
        (31, 35, "who were formerly"),
        (36, 39, "their brethren,"),
        (40, 40, "yea,"),
        (41, 44, "and had dissented"),
        (45, 48, "from their church,"),
        (49, 52, "and they left"),
        (53, 54, "them"),
        (55, 58, "and had gone"),
        (59, 60, "to destroy"),
        (61, 62, "them"),
        (63, 67, "by joining together with"),
        (68, 69, "the Lamanites."),
    ],
    25: [
        (0, 0, "Yea,"),
        (1, 5, "they could not"),
        (6, 6, "allow"),
        (7, 8, "that rejoice"),
        (9, 11, "their brethren"),
        (12, 14, "over"),
        (15, 17, "the blood of"),
        (18, 19, "the Nephites,"),
        (20, 24, "as long as there were"),
        (25, 26, "some"),
        (27, 30, "who kept"),
        (31, 32, "the commandments of"),
        (33, 34, "God,"),
        (35, 36, "for"),
        (37, 39, "the promise of"),
        (40, 41, "the Lord"),
        (42, 43, "was thus,"),
        (44, 47, "if they keep"),
        (48, 49, "his commandments"),
        (50, 54, "they would prosper"),
        (55, 57, "in the land."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
