"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 50 — Moroni fortifies
the Nephite cities and builds new ones; the Nephites prosper greatly; the
account of Morianton and the land of Lehi; Teancum defeats Morianton; the death
of the chief judge Nephihah and the appointment of his son Pahoran; the account
of Tubaloth and the Lamanites gathering to battle.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

No em-dash pre-splits needed for this chapter.

    python3 build_overrides_alma50.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 50

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 7, "stopped not"),
        (8, 9, "Moroni"),
        (10, 12, "the making of"),
        (13, 15, "preparations for war,"),
        (16, 20, "or the defending of"),
        (21, 22, "his people"),
        (23, 24, "from"),
        (25, 26, "the Lamanites;"),
        (27, 31, "for he commanded"),
        (32, 33, "that begin"),
        (34, 36, "his armies"),
        (37, 40, "in the beginning of"),
        (41, 43, "the twentieth year"),
        (44, 48, "of the reign of the judges,"),
        (49, 53, "that they should begin"),
        (54, 57, "digging up"),
        (58, 59, "heaps of earth"),
        (60, 60, "round about"),
        (61, 63, "at all the cities,"),
        (64, 67, "in the whole land"),
        (68, 71, "which belonged to"),
        (72, 73, "the Nephites."),
    ],
    2: [
        (0, 3, "And on the top"),
        (4, 7, "of those banks of earth"),
        (8, 11, "he commanded"),
        (12, 16, "that there be"),
        (17, 19, "large timbers,"),
        (20, 20, "yea,"),
        (21, 24, "a fence of large timbers"),
        (25, 27, "according to"),
        (28, 30, "the height of"),
        (31, 32, "a man,"),
        (33, 34, "set up"),
        (35, 37, "round about the cities."),
    ],
    3: [
        (0, 4, "And he commanded"),
        (5, 6, "that be built"),
        (7, 9, "round about on top"),
        (10, 14, "of those timber fences,"),
        (15, 18, "a fence of sharp pickets;"),
        (19, 21, "and they were strong"),
        (22, 23, "and high."),
    ],
    4: [
        (0, 3, "And he commanded"),
        (4, 5, "that be built"),
        (6, 7, "towers"),
        (8, 11, "which overlooked"),
        (12, 15, "those picket fences,"),
        (16, 20, "and he commanded"),
        (21, 22, "that be built"),
        (23, 25, "places of"),
        (26, 28, "safe protection"),
        (29, 31, "upon"),
        (32, 33, "those towers,"),
        (34, 40, "that they could not be struck"),
        (41, 42, "by the stones"),
        (43, 45, "and the arrows of"),
        (46, 47, "the Lamanites."),
    ],
    5: [
        (0, 3, "And they were prepared"),
        (4, 8, "that they might"),
        (9, 12, "cast down stones"),
        (13, 16, "from the top of"),
        (17, 18, "those towers,"),
        (19, 21, "according to"),
        (22, 24, "their will"),
        (25, 28, "and their strength,"),
        (29, 30, "and slay"),
        (31, 32, "him"),
        (33, 36, "who tried"),
        (37, 39, "to come near"),
        (40, 43, "to the wall of"),
        (44, 45, "the city."),
    ],
    6: [
        (0, 4, "And thus prepared"),
        (5, 6, "Moroni"),
        (7, 8, "strong places"),
        (9, 10, "round about"),
        (11, 12, "each city"),
        (13, 16, "in the whole land,"),
        (17, 21, "for the coming of"),
        (22, 24, "their enemies."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 4, "commanded"),
        (5, 6, "Moroni"),
        (7, 8, "his armies"),
        (9, 12, "that they go"),
        (13, 15, "into the wilderness"),
        (16, 17, "in the east;"),
        (18, 18, "yea,"),
        (19, 23, "and they went"),
        (24, 27, "and drove away"),
        (28, 30, "all the Lamanites"),
        (31, 35, "who were"),
        (36, 38, "in the wilderness"),
        (39, 40, "in the east"),
        (41, 45, "into their own lands,"),
        (46, 50, "which were south of"),
        (51, 54, "the land of Zarahemla."),
    ],
    8: [
        (0, 0, "And"),
        (1, 4, "the land of"),
        (5, 5, "Nephi"),
        (6, 7, "lay"),
        (8, 11, "in a straight line"),
        (12, 14, "from the sea"),
        (15, 16, "in the east"),
        (17, 20, "reaching to"),
        (21, 21, "the west."),
    ],
    9: [
        (0, 3, "And it came to pass that"),
        (4, 8, "when had driven away"),
        (9, 10, "Moroni"),
        (11, 13, "all the Lamanites"),
        (14, 16, "from the wilderness"),
        (17, 18, "in the east,"),
        (19, 21, "which was on"),
        (22, 26, "the north side of"),
        (27, 27, "the lands"),
        (28, 30, "which belonged to"),
        (31, 33, "themselves,"),
        (34, 37, "he commanded"),
        (38, 40, "that should"),
        (41, 41, "the people"),
        (42, 45, "who were in"),
        (46, 49, "the land of Zarahemla"),
        (50, 52, "and the land"),
        (53, 55, "round about,"),
        (56, 58, "should go"),
        (59, 61, "into the wilderness"),
        (62, 63, "in the east,"),
        (64, 67, "even unto"),
        (68, 68, "the borders"),
        (69, 71, "by the side of"),
        (72, 73, "the seashore,"),
        (74, 78, "and take for themselves"),
        (79, 80, "the land."),
    ],
    10: [
        (0, 4, "And he also placed"),
        (5, 5, "armies"),
        (6, 8, "on the side"),
        (9, 10, "in the south,"),
        (11, 13, "in the borders of"),
        (14, 16, "their lands;"),
        (17, 18, "and commanded"),
        (19, 20, "them"),
        (21, 22, "to set up"),
        (23, 24, "towers"),
        (25, 30, "that they might defend"),
        (31, 33, "their armies"),
        (34, 37, "and their people"),
        (38, 40, "from the hands of"),
        (41, 43, "their enemies."),
    ],
    11: [
        (0, 5, "And thus he blocked off"),
        (6, 10, "all the strongholds of"),
        (11, 12, "the Lamanites"),
        (13, 15, "in the wilderness"),
        (16, 17, "in the east,"),
        (18, 18, "yea,"),
        (19, 22, "and also on the side"),
        (23, 24, "in the west,"),
        (25, 26, "and strengthening"),
        (27, 29, "the fortified line"),
        (30, 33, "between"),
        (34, 35, "the Nephites"),
        (36, 38, "and the Lamanites,"),
        (39, 42, "between"),
        (43, 46, "the land of Zarahemla"),
        (47, 51, "and the land of Nephi,"),
        (52, 55, "from the sea"),
        (56, 57, "in the west,"),
        (58, 60, "extending"),
        (61, 63, "by the side of"),
        (64, 66, "the head of"),
        (67, 70, "the river Sidon—"),
        (71, 73, "had taken"),
        (74, 76, "the Nephites"),
        (77, 79, "all the land"),
        (80, 81, "northward,"),
        (82, 82, "yea,"),
        (83, 87, "the whole land which"),
        (88, 89, "was on"),
        (90, 94, "the north side of"),
        (95, 98, "the land of Bountiful,"),
        (99, 101, "according to"),
        (102, 104, "their desire."),
    ],
    12: [
        (0, 3, "And thus sought"),
        (4, 5, "Moroni,"),
        (6, 7, "together with"),
        (8, 9, "his armies,"),
        (10, 12, "which increased"),
        (13, 15, "each day"),
        (16, 17, "because of"),
        (18, 20, "the assurance of"),
        (21, 22, "protection"),
        (23, 26, "which came"),
        (27, 30, "upon them"),
        (31, 33, "from his works,"),
        (34, 35, "to take away"),
        (36, 37, "the strength"),
        (38, 40, "and the power"),
        (41, 43, "of the Lamanites"),
        (44, 47, "from their lands,"),
        (48, 50, "that there be no"),
        (51, 53, "their power"),
        (54, 56, "over"),
        (57, 59, "their lands."),
    ],
    13: [
        (0, 3, "And it came to pass that"),
        (4, 4, "began"),
        (5, 7, "the Nephites"),
        (8, 10, "the foundation of"),
        (11, 12, "a city,"),
        (13, 16, "and they named"),
        (17, 19, "the name of"),
        (20, 21, "the city"),
        (22, 23, "Moroni;"),
        (24, 28, "and it was by"),
        (29, 32, "the east sea;"),
        (33, 35, "and it was on"),
        (36, 39, "the south side"),
        (40, 42, "by the side of"),
        (43, 45, "the border of"),
        (46, 49, "the lands of the Lamanites."),
    ],
    14: [
        (0, 6, "And they also began to make"),
        (7, 10, "a foundation for"),
        (11, 12, "a city"),
        (13, 16, "between"),
        (17, 20, "the city of Moroni"),
        (21, 24, "and the city of"),
        (25, 25, "Aaron,"),
        (26, 29, "joining together"),
        (30, 31, "the borders of"),
        (32, 34, "Aaron and Moroni."),
        (35, 38, "And they named"),
        (39, 41, "the name of"),
        (42, 43, "the city,"),
        (44, 45, "or"),
        (46, 47, "the land,"),
        (48, 49, "Nephihah."),
    ],
    15: [
        (0, 4, "And they also began"),
        (5, 8, "in that same year"),
        (9, 10, "to build"),
        (11, 13, "many cities"),
        (14, 16, "on the side"),
        (17, 18, "in the north,"),
        (19, 21, "one"),
        (22, 24, "which they built"),
        (25, 29, "in a special way"),
        (30, 32, "which they named"),
        (33, 34, "Lehi,"),
        (35, 37, "which was on"),
        (38, 41, "the north side"),
        (42, 44, "by the side of"),
        (45, 46, "the borders of"),
        (47, 48, "the seashore."),
    ],
    16: [
        (0, 4, "And thus ended"),
        (5, 7, "the year"),
        (8, 9, "twentieth."),
    ],
    17: [
        (0, 0, "And"),
        (1, 6, "in these circumstances of prosperity"),
        (7, 9, "was"),
        (10, 13, "the people of Nephi"),
        (14, 17, "in the beginning of"),
        (18, 19, "the year"),
        (20, 24, "twenty and one"),
        (25, 29, "of the reign of the judges"),
        (30, 33, "over the people of"),
        (34, 34, "Nephi."),
    ],
    18: [
        (0, 5, "And they prospered exceedingly,"),
        (6, 11, "and they were also exceedingly wealthy;"),
        (12, 12, "yea,"),
        (13, 16, "and they multiplied"),
        (17, 20, "and grew strong"),
        (21, 23, "in the land."),
    ],
    19: [
        (0, 6, "And thus we see"),
        (7, 10, "the tender mercy"),
        (11, 11, "great"),
        (12, 15, "and the justice of"),
        (16, 18, "all the works of"),
        (19, 20, "the Lord,"),
        (21, 24, "in the fulfilling of"),
        (25, 27, "all his words"),
        (28, 31, "to the children of"),
        (32, 32, "men;"),
        (33, 33, "yea,"),
        (34, 38, "we can see,"),
        (39, 43, "at this very time,"),
        (44, 47, "the confirming of"),
        (48, 49, "his words"),
        (50, 54, "which he spoke"),
        (55, 56, "unto Lehi,"),
        (57, 58, "thus:"),
    ],
    20: [
        (0, 2, "Blessed art thou"),
        (3, 5, "and thy children;"),
        (6, 10, "and shall be blessed"),
        (11, 12, "they;"),
        (13, 16, "according as"),
        (17, 19, "their keeping of"),
        (20, 22, "my commandments"),
        (23, 27, "they shall prosper"),
        (28, 30, "in the land."),
        (31, 33, "But remember,"),
        (34, 37, "according as"),
        (38, 42, "their not keeping of"),
        (43, 44, "my commandments"),
        (45, 49, "shall be cut off"),
        (50, 51, "they"),
        (52, 54, "from the presence of"),
        (55, 56, "the Lord."),
    ],
    21: [
        (0, 3, "And we see"),
        (4, 5, "have been fulfilled"),
        (6, 7, "these promises"),
        (8, 11, "to the people of"),
        (12, 12, "Nephi;"),
        (13, 14, "because of"),
        (15, 17, "their quarrels"),
        (18, 21, "and their divisions,"),
        (22, 22, "yea,"),
        (23, 27, "their slaying of men,"),
        (28, 31, "and their robberies,"),
        (32, 35, "their bowing"),
        (36, 37, "to idols,"),
        (38, 41, "their fornications,"),
        (42, 47, "and their doing of abominable things,"),
        (48, 50, "which were"),
        (51, 56, "among themselves,"),
        (57, 60, "which came"),
        (61, 64, "upon them"),
        (65, 68, "their wars"),
        (69, 72, "and their destructions."),
    ],
    22: [
        (0, 3, "And those"),
        (4, 7, "who were faithful"),
        (8, 11, "in the keeping of"),
        (12, 13, "the commandments of"),
        (14, 15, "the Lord"),
        (16, 17, "were delivered"),
        (18, 20, "at all times,"),
        (21, 21, "while"),
        (22, 25, "the thousands upon thousands"),
        (26, 30, "of their wicked brethren"),
        (31, 33, "were given"),
        (34, 36, "into bondage,"),
        (37, 38, "or perished"),
        (39, 41, "by the sword,"),
        (42, 43, "or dwindled"),
        (44, 47, "in unbelief,"),
        (48, 50, "and joined with"),
        (51, 52, "the Lamanites."),
    ],
    23: [
        (0, 1, "But behold"),
        (2, 5, "there was no time"),
        (6, 8, "more joyful"),
        (9, 11, "among"),
        (12, 15, "the people of Nephi,"),
        (16, 17, "since"),
        (18, 20, "the days of Nephi,"),
        (21, 22, "than"),
        (23, 25, "the days of Moroni,"),
        (26, 26, "yea,"),
        (27, 31, "even unto"),
        (32, 34, "this time,"),
        (35, 38, "in the year"),
        (39, 43, "twenty and one"),
        (44, 48, "of the reign of the judges."),
    ],
    24: [
        (0, 3, "And it came to pass that"),
        (4, 5, "also ended"),
        (6, 8, "in peace"),
        (9, 10, "the year"),
        (11, 15, "twenty and two"),
        (16, 20, "of the reign of the judges;"),
        (21, 21, "yea,"),
        (22, 25, "and also the year"),
        (26, 30, "twenty and three."),
    ],
    25: [
        (0, 2, "And it came to pass"),
        (3, 5, "in the beginning"),
        (6, 8, "of the year"),
        (9, 13, "twenty and four"),
        (14, 18, "of the reign of the judges,"),
        (19, 23, "there would also have been"),
        (24, 25, "peace"),
        (26, 28, "among"),
        (29, 32, "the people of Nephi,"),
        (33, 36, "were it not for"),
        (37, 38, "a contention"),
        (39, 41, "which arose"),
        (42, 46, "among them"),
        (47, 49, "concerning"),
        (50, 53, "the land of Lehi"),
        (54, 57, "and the land of"),
        (58, 58, "Morianton,"),
        (59, 61, "which joined"),
        (62, 66, "upon the borders of"),
        (67, 67, "Lehi;"),
        (68, 72, "which were both"),
        (73, 74, "on the borders"),
        (75, 77, "by the side of"),
        (78, 79, "the seashore."),
    ],
    26: [
        (0, 1, "For behold,"),
        (2, 3, "the people"),
        (4, 7, "who dwelt"),
        (8, 11, "in the land of"),
        (12, 12, "Morianton,"),
        (13, 18, "claimed as theirs"),
        (19, 21, "a part of"),
        (22, 25, "the land of Lehi;"),
        (26, 27, "therefore"),
        (28, 30, "began"),
        (31, 33, "a great contention"),
        (34, 37, "between them,"),
        (38, 40, "insomuch that"),
        (41, 42, "took up"),
        (43, 47, "the people of Morianton"),
        (48, 50, "weapons of war"),
        (51, 53, "against"),
        (54, 56, "their brethren,"),
        (57, 60, "and they resolved"),
        (61, 62, "to slay"),
        (63, 64, "them"),
        (65, 67, "with the sword."),
    ],
    27: [
        (0, 1, "But behold,"),
        (2, 3, "fled"),
        (4, 4, "the people"),
        (5, 7, "who dwelt in"),
        (8, 11, "the land of Lehi"),
        (12, 15, "to the camp of"),
        (16, 16, "Moroni,"),
        (17, 19, "and pleaded"),
        (20, 22, "unto him"),
        (23, 25, "for help;"),
        (26, 27, "for behold"),
        (28, 31, "they were not wrong."),
    ],
    28: [
        (0, 3, "And it came to pass that"),
        (4, 5, "when found"),
        (6, 9, "the people of"),
        (10, 10, "Morianton,"),
        (11, 14, "who were led"),
        (15, 17, "by a man"),
        (18, 19, "named"),
        (20, 21, "Morianton,"),
        (22, 24, "had fled"),
        (25, 28, "the people of Lehi"),
        (29, 32, "to the camp of"),
        (33, 33, "Moroni,"),
        (34, 38, "they were exceedingly afraid"),
        (39, 41, "lest come"),
        (42, 45, "the army of Moroni"),
        (46, 48, "upon"),
        (49, 50, "them"),
        (51, 52, "and destroy"),
        (53, 54, "them."),
    ],
    29: [
        (0, 1, "Therefore,"),
        (2, 4, "put"),
        (5, 6, "Morianton"),
        (7, 10, "into their hearts,"),
        (11, 14, "that they flee"),
        (15, 18, "to the land which"),
        (19, 24, "was on the north side,"),
        (25, 27, "which was covered"),
        (28, 30, "with large lakes,"),
        (31, 35, "and take for themselves"),
        (36, 37, "the land"),
        (38, 40, "which was on"),
        (41, 44, "the north side."),
    ],
    30: [
        (0, 1, "And behold,"),
        (2, 5, "they would have accomplished"),
        (6, 7, "this plan,"),
        (8, 13, "(which would have brought"),
        (14, 15, "a sorrow)"),
        (16, 17, "but behold,"),
        (18, 19, "because"),
        (20, 20, "Morianton"),
        (21, 23, "was a man"),
        (24, 25, "of great anger,"),
        (26, 27, "therefore"),
        (28, 32, "he was angry"),
        (33, 36, "with one of"),
        (37, 39, "his maidservants,"),
        (40, 44, "and he came upon"),
        (45, 47, "her"),
        (48, 50, "and beat greatly"),
        (51, 53, "her."),
    ],
    31: [
        (0, 3, "And it came to pass that"),
        (4, 4, "fled"),
        (5, 7, "the maidservant,"),
        (8, 9, "and came"),
        (10, 13, "to the camp of"),
        (14, 14, "Moroni,"),
        (15, 17, "and told"),
        (18, 19, "unto Moroni"),
        (20, 21, "all things"),
        (22, 24, "concerning"),
        (25, 26, "the matter,"),
        (27, 31, "and also concerning"),
        (32, 34, "their intent"),
        (35, 37, "to flee"),
        (38, 40, "into the land"),
        (41, 45, "on the north side."),
    ],
    32: [
        (0, 1, "Now"),
        (2, 2, "behold,"),
        (3, 4, "the people"),
        (5, 9, "who were in the land of"),
        (10, 10, "Bountiful,"),
        (11, 12, "or"),
        (13, 13, "Moroni,"),
        (14, 16, "feared lest"),
        (17, 19, "they listen"),
        (20, 22, "to the words of"),
        (23, 23, "Morianton"),
        (24, 27, "and join with"),
        (28, 29, "his people,"),
        (30, 35, "and thus he obtain"),
        (36, 38, "those parts"),
        (39, 41, "of the land,"),
        (42, 47, "which would lay"),
        (48, 49, "a foundation"),
        (50, 52, "of grievous outcomes"),
        (53, 55, "among"),
        (56, 59, "the people of Nephi,"),
        (60, 60, "yea,"),
        (61, 62, "outcomes which"),
        (63, 65, "lead to"),
        (66, 67, "the overthrow"),
        (68, 71, "of their liberty."),
    ],
    33: [
        (0, 1, "Therefore"),
        (2, 5, "sent"),
        (6, 7, "Moroni"),
        (8, 9, "an army,"),
        (10, 11, "together with"),
        (12, 14, "their camp,"),
        (15, 17, "to intercept"),
        (18, 20, "the people of Morianton,"),
        (21, 22, "to stop"),
        (23, 25, "their fleeing"),
        (26, 28, "into the land"),
        (29, 30, "northward."),
    ],
    34: [
        (0, 3, "And it came to pass that"),
        (4, 7, "they did not stop"),
        (8, 9, "them"),
        (10, 12, "until"),
        (13, 16, "they had reached"),
        (17, 19, "to the borders of"),
        (20, 23, "the land of Desolation;"),
        (24, 26, "and there"),
        (27, 31, "they stopped"),
        (32, 33, "them,"),
        (34, 36, "by the side of"),
        (37, 39, "the narrow pass"),
        (40, 43, "which passed"),
        (44, 48, "by the side of the sea"),
        (49, 52, "leading to"),
        (53, 56, "the land northward,"),
        (57, 57, "yea,"),
        (58, 60, "by the side of"),
        (61, 62, "the sea,"),
        (63, 67, "on the west side"),
        (68, 72, "and on the east side."),
    ],
    35: [
        (0, 3, "And it came to pass that"),
        (4, 4, "met"),
        (5, 6, "the army"),
        (7, 9, "which was sent"),
        (10, 11, "by Moroni,"),
        (12, 14, "which was led"),
        (15, 17, "by a man"),
        (18, 20, "his name"),
        (21, 22, "was Teancum,"),
        (23, 25, "with the people of"),
        (26, 26, "Morianton;"),
        (27, 31, "and so very stubborn were"),
        (32, 34, "the people of Morianton,"),
        (35, 39, "(for they were urged"),
        (40, 42, "by his wickedness"),
        (43, 46, "and his flattering words)"),
        (47, 49, "insomuch that"),
        (50, 52, "a battle arose"),
        (53, 56, "between them,"),
        (57, 60, "in which slew"),
        (61, 62, "Teancum"),
        (63, 64, "Morianton"),
        (65, 66, "and overthrew"),
        (67, 68, "his army,"),
        (69, 72, "and took them"),
        (73, 73, "as prisoners,"),
        (74, 77, "and returned"),
        (78, 81, "to the camp of"),
        (82, 82, "Moroni."),
        (83, 87, "And thus ended"),
        (88, 90, "the year"),
        (91, 95, "twenty and four"),
        (96, 100, "of the reign of the judges"),
        (101, 103, "over"),
        (104, 107, "the people of Nephi."),
    ],
    36: [
        (0, 5, "And thus were brought back"),
        (6, 9, "the people of"),
        (10, 10, "Morianton."),
        (11, 14, "And upon"),
        (15, 17, "their making a covenant"),
        (18, 19, "to keep"),
        (20, 21, "the peace,"),
        (22, 25, "were restored"),
        (26, 27, "they"),
        (28, 31, "to the land of"),
        (32, 32, "Morianton,"),
        (33, 35, "and was made"),
        (36, 37, "a union"),
        (38, 41, "between them"),
        (42, 46, "and the people of Lehi;"),
        (47, 50, "and were also restored"),
        (51, 52, "they"),
        (53, 56, "to their lands."),
    ],
    37: [
        (0, 2, "And it came to pass"),
        (3, 7, "in the same year"),
        (8, 11, "was restored"),
        (12, 16, "to the people of Nephi"),
        (17, 18, "the peace"),
        (19, 22, "unto them,"),
        (23, 25, "died"),
        (26, 26, "Nephihah,"),
        (27, 29, "the chief judge"),
        (30, 31, "the second,"),
        (32, 37, "when he had sat"),
        (38, 40, "in the judgment-seat"),
        (41, 44, "with complete righteousness"),
        (45, 47, "before"),
        (48, 49, "God."),
    ],
    38: [
        (0, 3, "Nevertheless,"),
        (4, 6, "he refused"),
        (7, 7, "Alma"),
        (8, 10, "to keep"),
        (11, 11, "the records"),
        (12, 13, "and the things"),
        (14, 17, "which were regarded"),
        (18, 21, "by Alma and his father"),
        (22, 25, "as most sacred;"),
        (26, 27, "therefore"),
        (28, 31, "gave"),
        (32, 33, "Alma"),
        (34, 35, "those things"),
        (36, 38, "unto his son"),
        (39, 40, "Helaman."),
    ],
    39: [
        (0, 0, "Behold,"),
        (1, 3, "it came to pass that"),
        (4, 4, "was appointed"),
        (5, 7, "the son of"),
        (8, 8, "Nephihah"),
        (9, 10, "to sit"),
        (11, 13, "in the judgment-seat,"),
        (14, 16, "in place of"),
        (17, 18, "his father;"),
        (19, 19, "yea,"),
        (20, 23, "he was appointed"),
        (24, 26, "as chief judge"),
        (27, 28, "and governor"),
        (29, 31, "over"),
        (32, 33, "the people,"),
        (34, 35, "with"),
        (36, 37, "an oath"),
        (38, 41, "and a sacred ordinance"),
        (42, 43, "to judge"),
        (44, 46, "with righteousness,"),
        (47, 48, "and to keep"),
        (49, 50, "the peace"),
        (51, 54, "and the freedom of"),
        (55, 56, "the people,"),
        (57, 59, "and to give"),
        (60, 63, "unto them"),
        (64, 67, "their sacred privileges"),
        (68, 70, "to worship"),
        (71, 73, "the Lord"),
        (74, 76, "their God,"),
        (77, 77, "yea,"),
        (78, 79, "to support"),
        (80, 81, "and to defend"),
        (82, 84, "the work of"),
        (85, 86, "God"),
        (87, 90, "in all his days,"),
        (91, 92, "and to bring"),
        (93, 94, "the wicked"),
        (95, 97, "to judgment"),
        (98, 100, "according to"),
        (101, 103, "their transgressions."),
    ],
    40: [
        (0, 1, "Now"),
        (2, 2, "behold,"),
        (3, 5, "his name"),
        (6, 7, "was Pahoran."),
        (8, 10, "And sat"),
        (11, 11, "Pahoran"),
        (12, 15, "in the seat of"),
        (16, 17, "his father,"),
        (18, 20, "and began"),
        (21, 22, "his reign"),
        (23, 25, "over"),
        (26, 29, "the people of Nephi,"),
        (30, 33, "in the end of"),
        (34, 35, "the year"),
        (36, 40, "twenty and four."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
