"""Hand-curated TAM-phrase gloss overrides for Mosaea 17 — the martyrdom of Abinadi.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
subject `o ia` / agent `e ia` absorbed into the verb cluster, never split as a
bare "he" (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` fillers when a PP/object follows (rule 1), `mafai ona`/`ina ia`/
`ina ua` bound (rules 13/15), vocative `e`/`E …e` folded as "O X" (rule 12),
directional "forth" dropped (rule 12a). No pronoun/TAM word injected into a cell
whose span lacks that token; no content word repeats across adjacent cells
(except authentic Samoan doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah17.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 17
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "And"),
        (1, 2, "now,"),
        (3, 5, "it came to pass"),
        (6, 8, "had finished"),
        (9, 10, "speaking"),
        (11, 12, "Abinadi"),
        (13, 14, "these words,"),
        (15, 17, "commanded"),
        (18, 19, "the king"),
        (20, 21, "unto the priests"),
        (22, 23, "that they should"),
        (24, 24, "take"),
        (25, 26, "him"),
        (27, 28, "and cause"),
        (29, 29, "that"),
        (30, 30, "be slain"),
        (31, 33, "him."),
    ],
    2: [
        (0, 0, "But"),
        (1, 3, "there was"),
        (4, 5, "one"),
        (6, 8, "among"),
        (9, 10, "them"),
        (11, 13, "whose name"),
        (14, 15, "was Alma,"),
        (16, 18, "he also"),
        (19, 20, "was one who"),
        (21, 22, "descended"),
        (23, 25, "from Nephi."),
        (26, 26, "And"),
        (27, 28, "he was"),
        (29, 32, "a young man,"),
        (33, 37, "and he believed"),
        (38, 39, "the words"),
        (40, 43, "which had spoken"),
        (44, 44, "Abinadi,"),
        (45, 45, "for"),
        (46, 49, "he knew"),
        (50, 52, "concerning"),
        (53, 54, "the iniquity"),
        (55, 55, "which"),
        (56, 59, "had testified"),
        (60, 60, "Abinadi"),
        (61, 62, "against"),
        (63, 66, "them;"),
        (67, 68, "therefore"),
        (69, 71, "began"),
        (72, 76, "to plead"),
        (77, 79, "with the king"),
        (80, 80, "that"),
        (81, 82, "not"),
        (83, 85, "be angry"),
        (86, 87, "with Abinadi,"),
        (88, 88, "but"),
        (89, 89, "suffer"),
        (90, 91, "him"),
        (92, 95, "to depart"),
        (96, 98, "in peace."),
    ],
    3: [
        (0, 0, "But"),
        (1, 3, "was more wroth"),
        (4, 5, "the king,"),
        (6, 7, "and caused"),
        (8, 8, "that"),
        (9, 11, "be cast out"),
        (12, 12, "Alma"),
        (13, 15, "from among"),
        (16, 17, "them,"),
        (18, 20, "and sent"),
        (21, 22, "his servants"),
        (23, 24, "to pursue"),
        (25, 27, "him"),
        (28, 29, "that"),
        (30, 31, "they might slay"),
        (32, 34, "him."),
    ],
    4: [
        (0, 0, "But"),
        (1, 4, "he fled"),
        (5, 5, "from"),
        (6, 9, "before them"),
        (10, 11, "and hid"),
        (12, 14, "himself"),
        (15, 15, "and"),
        (16, 20, "they found not"),
        (21, 22, "him."),
        (23, 23, "And"),
        (24, 24, "while"),
        (25, 27, "he was hid"),
        (28, 30, "for days"),
        (31, 32, "many"),
        (33, 36, "he wrote"),
        (37, 38, "all the words"),
        (39, 42, "which had spoken"),
        (43, 43, "Abinadi."),
    ],
    5: [
        (0, 3, "And it came to pass"),
        (4, 4, "caused"),
        (5, 7, "the king,"),
        (8, 8, "that"),
        (9, 9, "should surround"),
        (10, 12, "his guards"),
        (13, 13, "Abinadi"),
        (14, 15, "and take"),
        (16, 17, "him;"),
        (18, 18, "and"),
        (19, 21, "they bound"),
        (22, 23, "him"),
        (24, 25, "and cast"),
        (26, 28, "into"),
        (29, 30, "the prison."),
    ],
    6: [
        (0, 0, "And"),
        (1, 3, "after had passed"),
        (4, 6, "three days,"),
        (7, 9, "when had finished"),
        (10, 13, "counseling"),
        (14, 15, "together with"),
        (16, 17, "his priests,"),
        (18, 21, "he caused"),
        (22, 22, "that"),
        (23, 24, "be brought again"),
        (25, 26, "him"),
        (27, 29, "before him."),
    ],
    7: [
        (0, 0, "And"),
        (1, 5, "he said"),
        (6, 8, "unto him:"),
        (9, 9, "Abinadi,"),
        (10, 12, "we have found"),
        (13, 14, "an accusation"),
        (15, 16, "against"),
        (17, 19, "thee,"),
        (20, 20, "and"),
        (21, 22, "meet is"),
        (23, 24, "death"),
        (25, 27, "unto thee."),
    ],
    8: [
        (0, 0, "Because"),
        (1, 4, "thou hast said"),
        (5, 9, "should come down"),
        (10, 11, "God"),
        (12, 13, "himself"),
        (14, 16, "among"),
        (17, 18, "the children"),
        (19, 20, "of men;"),
        (21, 21, "and"),
        (22, 23, "now,"),
        (24, 25, "because of"),
        (26, 27, "this cause"),
        (28, 33, "thou shalt be slain"),
        (34, 35, "unless"),
        (36, 39, "thou wilt recall"),
        (40, 40, "the words"),
        (41, 41, "evil"),
        (42, 42, "all,"),
        (43, 45, "which thou hast spoken"),
        (46, 47, "concerning"),
        (48, 50, "me"),
        (51, 51, "and"),
        (52, 53, "my people."),
    ],
    9: [
        (0, 1, "Now"),
        (2, 4, "said"),
        (5, 5, "Abinadi"),
        (6, 8, "unto him:"),
        (9, 12, "I say"),
        (13, 15, "unto thee,"),
        (16, 19, "I will not recall"),
        (20, 20, "the words"),
        (21, 25, "which I have spoken"),
        (26, 28, "unto thee"),
        (29, 31, "concerning"),
        (32, 33, "this people,"),
        (34, 34, "for"),
        (35, 37, "they are true;"),
        (38, 38, "and"),
        (39, 40, "that"),
        (41, 43, "ye may know"),
        (44, 46, "of their surety"),
        (47, 48, "therefore"),
        (49, 53, "have I suffered"),
        (54, 56, "myself"),
        (57, 60, "into your hands."),
    ],
    10: [
        (0, 0, "Yea,"),
        (1, 1, "and"),
        (2, 6, "I will suffer"),
        (7, 9, "even unto"),
        (10, 12, "death,"),
        (13, 13, "and"),
        (14, 17, "I will not recall"),
        (18, 20, "my very words,"),
        (21, 21, "but"),
        (22, 26, "they shall stand"),
        (27, 29, "as a testimony"),
        (30, 31, "against"),
        (32, 34, "you."),
        (35, 36, "And if"),
        (37, 39, "ye slay"),
        (40, 40, "me,"),
        (41, 45, "ye shall shed"),
        (46, 47, "the blood"),
        (48, 49, "guiltless,"),
        (50, 50, "and"),
        (51, 54, "shall stand"),
        (55, 56, "also this"),
        (57, 59, "as a testimony"),
        (60, 61, "against"),
        (62, 64, "you"),
        (65, 67, "in the day"),
        (68, 68, "last."),
    ],
    11: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "was about to"),
        (6, 7, "release"),
        (8, 9, "him"),
        (10, 12, "the king"),
        (13, 14, "Noah,"),
        (15, 15, "for"),
        (16, 19, "he feared"),
        (20, 22, "his words;"),
        (23, 23, "for"),
        (24, 27, "he was afraid"),
        (28, 28, "lest"),
        (29, 30, "come"),
        (31, 33, "upon him"),
        (34, 34, "the judgments"),
        (35, 37, "of God."),
    ],
    12: [
        (0, 0, "But"),
        (1, 4, "lifted up"),
        (5, 6, "the priests"),
        (7, 9, "their voices"),
        (10, 11, "against"),
        (12, 14, "him,"),
        (15, 16, "and began"),
        (17, 19, "to accuse"),
        (20, 21, "him,"),
        (22, 23, "saying:"),
        (24, 28, "He hath spoken evil"),
        (29, 31, "against the king."),
        (32, 33, "Therefore"),
        (34, 36, "was stirred up"),
        (37, 38, "the anger"),
        (39, 41, "of the king"),
        (42, 43, "against"),
        (44, 46, "him,"),
        (47, 47, "and"),
        (48, 52, "he delivered up"),
        (53, 54, "him"),
        (55, 56, "that"),
        (57, 57, "be slain."),
    ],
    13: [
        (0, 3, "And it came to pass"),
        (4, 5, "they took"),
        (6, 7, "him"),
        (8, 9, "and bound"),
        (10, 12, "him,"),
        (13, 14, "and scourged"),
        (15, 16, "his body"),
        (17, 19, "with faggots,"),
        (20, 20, "yea,"),
        (21, 23, "until he died."),
    ],
    14: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 4, "when"),
        (5, 5, "began"),
        (6, 9, "to burn"),
        (10, 11, "with the flames,"),
        (12, 16, "he cried"),
        (17, 20, "unto them,"),
        (21, 22, "saying:"),
    ],
    15: [
        (0, 0, "Behold,"),
        (1, 3, "even as"),
        (4, 5, "ye have done"),
        (6, 8, "unto me,"),
        (9, 13, "so likewise shall it be"),
        (14, 16, "that it come to pass"),
        (17, 17, "shall cause"),
        (18, 21, "your seed"),
        (22, 23, "that shall suffer"),
        (24, 25, "many"),
        (26, 27, "the pains"),
        (28, 31, "that I do suffer,"),
        (32, 35, "even the pains"),
        (36, 38, "of death"),
        (39, 41, "by fire;"),
        (42, 42, "and"),
        (43, 44, "this"),
        (45, 45, "because"),
        (46, 48, "they believe"),
        (49, 51, "in the salvation"),
        (52, 54, "of the Lord"),
        (55, 57, "their God."),
    ],
    16: [
        (0, 3, "And it shall come to pass"),
        (4, 8, "ye shall be afflicted"),
        (9, 11, "with all manner of"),
        (12, 13, "diseases"),
        (14, 15, "because of"),
        (16, 18, "your iniquities."),
    ],
    17: [
        (0, 0, "Yea,"),
        (1, 1, "and"),
        (2, 6, "ye shall be smitten"),
        (7, 10, "on every hand,"),
        (11, 11, "and"),
        (12, 15, "shall be driven"),
        (16, 17, "and scattered"),
        (18, 18, "you"),
        (19, 21, "hither"),
        (22, 24, "and thither,"),
        (25, 28, "even as"),
        (29, 29, "is driven"),
        (30, 31, "a flock"),
        (32, 32, "wild"),
        (33, 35, "by wild beasts"),
        (36, 37, "and ferocious."),
    ],
    18: [
        (0, 0, "And"),
        (1, 3, "in that day"),
        (4, 9, "ye shall be hunted,"),
        (10, 10, "and"),
        (11, 15, "ye shall be taken"),
        (16, 17, "by the hand"),
        (18, 21, "of your enemies,"),
        (22, 22, "and"),
        (23, 27, "then ye shall suffer,"),
        (28, 31, "even as"),
        (32, 33, "I suffer,"),
        (34, 35, "the pains"),
        (36, 38, "of death"),
        (39, 41, "by fire."),
    ],
    19: [
        (0, 2, "Thus doth"),
        (3, 4, "execute"),
        (5, 7, "God"),
        (8, 9, "vengeance"),
        (10, 12, "upon"),
        (13, 14, "them"),
        (15, 16, "those who"),
        (17, 19, "destroy"),
        (20, 21, "his people."),
        (22, 24, "O God,"),
        (25, 27, "receive"),
        (28, 29, "my soul."),
    ],
    20: [
        (0, 0, "And"),
        (1, 2, "now,"),
        (3, 6, "when had finished"),
        (7, 8, "speaking"),
        (9, 10, "Abinadi"),
        (11, 13, "these words,"),
        (14, 17, "he fell"),
        (18, 19, "down,"),
        (20, 22, "having suffered"),
        (23, 25, "death"),
        (26, 28, "by fire;"),
        (29, 29, "yea,"),
        (30, 34, "having been put to death"),
        (35, 35, "because"),
        (36, 40, "he would not deny"),
        (41, 41, "the commandments"),
        (42, 44, "of God,"),
        (45, 47, "having sealed"),
        (48, 49, "the truth"),
        (50, 52, "of his words"),
        (53, 55, "by his death."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
