"""
Hand-curated TAM-phrase gloss overrides for Mamona (Mormon) 8 — Moroni takes up the
record: the Nephites are all destroyed and Moroni alone is left, hunted by the
Lamanites; his father Mormon is slain. Moroni foresees the coming forth of this record
in a day of great wickedness, speaks as one from the dust to the latter-day reader, and
cries a searing woe upon the pride, pollutions, and hypocrisy of the last days.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15, vocative 12). `o le a` stays atomic and is never
fused with a following `se X` NP; cells go past 5 only for rule-2 (absorbed
subject) or rule-7 (`o le a` + verb + directional) clusters.

    python3 build_overrides_mormon8.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "mormon"
CHAPTER_NUM = 8

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "Behold,"),
        (1, 2, "I,"),
        (3, 4, "Moroni,"),
        (5, 7, "do finish"),
        (8, 9, "the record"),
        (10, 12, "of my father,"),
        (13, 14, "Mormon."),
        (15, 15, "Behold,"),
        (16, 19, "I have"),
        (20, 23, "a few things"),
        (24, 25, "to write,"),
        (26, 28, "which things"),
        (29, 32, "were commanded me"),
        (33, 35, "by my father."),
    ],
    2: [
        (0, 2, "And now"),
        (3, 5, "it came to pass that"),
        (6, 7, "had passed"),
        (8, 10, "the great battle"),
        (11, 13, "and terrible"),
        (14, 15, "at Cumorah,"),
        (16, 16, "behold,"),
        (17, 19, "the Nephites"),
        (20, 24, "who had escaped"),
        (25, 29, "into the south countries"),
        (30, 34, "were hunted by the Lamanites"),
        (35, 38, "until were destroyed"),
        (39, 41, "all of them."),
    ],
    3: [
        (0, 4, "And they also slew"),
        (5, 6, "my father,"),
        (7, 10, "and there remaineth"),
        (11, 13, "I alone"),
        (14, 15, "to write"),
        (16, 18, "the sad tale"),
        (19, 21, "of the destruction"),
        (22, 24, "of my people."),
        (25, 26, "But behold,"),
        (27, 31, "they are gone,"),
        (32, 35, "and I fulfil"),
        (36, 37, "the commandment"),
        (38, 40, "of my father."),
        (41, 42, "And whether"),
        (43, 45, "they will slay"),
        (46, 46, "me,"),
        (47, 50, "I know not."),
    ],
    4: [
        (0, 1, "Therefore"),
        (2, 6, "I will write"),
        (7, 9, "and hide up"),
        (10, 10, "the records"),
        (11, 13, "in the earth;"),
        (14, 17, "and whithersoever"),
        (18, 22, "I go"),
        (23, 25, "it mattereth not."),
    ],
    5: [
        (0, 0, "Behold,"),
        (1, 2, "made"),
        (3, 5, "my father"),
        (6, 7, "this record,"),
        (8, 11, "and he hath written"),
        (12, 13, "the purpose"),
        (14, 16, "for which it was made"),
        (17, 18, "And also behold,"),
        (19, 22, "I would also write"),
        (23, 27, "if I had"),
        (28, 29, "room"),
        (30, 33, "upon the plates,"),
        (34, 38, "but I have not;"),
        (39, 41, "and neither"),
        (42, 45, "have I also"),
        (46, 47, "ore,"),
        (48, 52, "for I am alone."),
        (53, 56, "My father hath been slain"),
        (57, 59, "in battle,"),
        (60, 62, "and all the people"),
        (63, 65, "of my kindred,"),
        (66, 68, "and there are no"),
        (69, 71, "friends of mine"),
        (72, 75, "nor any place"),
        (76, 80, "I may go;"),
        (81, 82, "and whether"),
        (83, 85, "it will be"),
        (86, 87, "long"),
        (88, 91, "will suffer me"),
        (92, 94, "the Lord"),
        (95, 98, "that I may live,"),
        (99, 102, "I know not."),
    ],
    6: [
        (0, 0, "Behold,"),
        (1, 3, "have passed away"),
        (4, 7, "four hundred years"),
        (8, 8, "since"),
        (9, 11, "the coming"),
        (12, 15, "of our Lord"),
        (16, 18, "and Savior."),
    ],
    7: [
        (0, 1, "And behold,"),
        (2, 6, "the Lamanites have hunted"),
        (7, 8, "my people,"),
        (9, 11, "the Nephites,"),
        (12, 14, "from"),
        (15, 16, "one city"),
        (17, 19, "to another,"),
        (20, 23, "and from one place"),
        (24, 26, "to another,"),
        (27, 30, "even until"),
        (31, 35, "they are no more;"),
        (36, 40, "and exceedingly great was"),
        (41, 43, "their fall;"),
        (44, 44, "yea,"),
        (45, 48, "exceedingly great"),
        (49, 50, "and marvelous"),
        (51, 52, "the destruction"),
        (53, 55, "of my people,"),
        (56, 58, "the Nephites."),
    ],
    8: [
        (0, 1, "And behold,"),
        (2, 5, "it is the hand"),
        (6, 8, "of the Lord"),
        (9, 11, "that hath done it."),
        (12, 14, "And behold also,"),
        (15, 18, "the Lamanites are at war"),
        (19, 21, "one"),
        (22, 24, "with another;"),
        (25, 27, "and become"),
        (28, 32, "the whole face of this land"),
        (33, 34, "a round"),
        (35, 38, "continual"),
        (39, 40, "one"),
        (41, 44, "of murdering"),
        (45, 48, "and bloodshed;"),
        (49, 53, "and there is none"),
        (54, 56, "who knoweth"),
        (57, 61, "the end of the war."),
    ],
    9: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 9, "I say no more"),
        (10, 12, "anything"),
        (13, 14, "concerning"),
        (15, 18, "them,"),
        (19, 23, "for there is none"),
        (24, 26, "save only"),
        (27, 28, "the Lamanites"),
        (29, 30, "and robbers"),
        (31, 34, "who do live"),
        (35, 39, "upon the land."),
    ],
    10: [
        (0, 4, "And there are none"),
        (5, 7, "who know"),
        (8, 10, "the true God"),
        (11, 12, "save"),
        (13, 15, "the disciples of Jesus,"),
        (16, 19, "who did remain"),
        (20, 22, "in the land"),
        (23, 25, "until"),
        (26, 27, "so great was"),
        (28, 29, "the wickedness"),
        (30, 31, "of the people"),
        (32, 35, "that would not suffer"),
        (36, 37, "them"),
        (38, 40, "the Lord"),
        (41, 44, "to abide still with"),
        (45, 47, "the people;"),
        (48, 49, "and whether"),
        (50, 54, "they are"),
        (55, 59, "upon the land"),
        (60, 61, "or not"),
        (62, 65, "there is no man"),
        (66, 68, "doth know."),
    ],
    11: [
        (0, 1, "But behold,"),
        (2, 4, "we did see"),
        (5, 7, "and my father"),
        (8, 11, "them,"),
        (12, 16, "and they did minister"),
        (17, 20, "unto us two."),
    ],
    12: [
        (0, 4, "And whosoever"),
        (5, 9, "receiveth this record,"),
        (10, 13, "and condemn not"),
        (14, 16, "because of the"),
        (17, 18, "imperfections"),
        (19, 21, "therein,"),
        (22, 25, "the same"),
        (26, 30, "shall know"),
        (31, 33, "of greater things"),
        (34, 36, "than these."),
        (37, 37, "Behold,"),
        (38, 39, "I am"),
        (40, 41, "Moroni;"),
        (42, 45, "and if it were possible,"),
        (46, 50, "I would show"),
        (51, 52, "all things"),
        (53, 55, "unto you."),
    ],
    13: [
        (0, 0, "Behold,"),
        (1, 3, "I make an end"),
        (4, 6, "of my speaking"),
        (7, 8, "concerning"),
        (9, 11, "this people."),
        (12, 13, "I am"),
        (14, 18, "the son of Mormon,"),
        (19, 22, "and my father"),
        (23, 27, "was a descendant"),
        (28, 29, "of Nephi."),
    ],
    14: [
        (0, 4, "And I am he"),
        (5, 9, "who hath hidden up"),
        (10, 11, "this record"),
        (12, 14, "unto the Lord;"),
        (15, 19, "the plates thereof"),
        (20, 23, "are of no worth,"),
        (24, 27, "because of the commandment"),
        (28, 30, "of the Lord."),
        (31, 31, "For"),
        (32, 37, "he hath indeed said"),
        (38, 41, "that none"),
        (42, 46, "shall obtain them"),
        (47, 50, "to get"),
        (51, 52, "gain;"),
        (53, 56, "but the record"),
        (57, 59, "thereof"),
        (60, 62, "is of great worth;"),
        (63, 67, "and whosoever"),
        (68, 70, "shall bring"),
        (71, 73, "to light,"),
        (74, 76, "the same"),
        (77, 80, "shall be blessed"),
        (81, 83, "by the Lord."),
    ],
    15: [
        (0, 4, "For none"),
        (5, 9, "can obtain"),
        (10, 11, "power"),
        (12, 14, "to bring"),
        (15, 17, "to light"),
        (18, 19, "save"),
        (20, 22, "it be given"),
        (23, 25, "unto him"),
        (26, 28, "by God;"),
        (29, 33, "for God willeth"),
        (34, 36, "that it be done"),
        (37, 40, "with an eye single"),
        (41, 43, "to his glory,"),
        (44, 47, "or the welfare"),
        (48, 49, "of the people"),
        (50, 53, "of the ancient covenant"),
        (54, 56, "of the Lord"),
        (57, 60, "long since scattered."),
    ],
    16: [
        (0, 4, "And blessed be he"),
        (5, 6, "who"),
        (7, 11, "shall bring"),
        (12, 13, "this thing"),
        (14, 16, "to light;"),
        (17, 17, "for"),
        (18, 21, "shall be brought"),
        (22, 24, "out of darkness"),
        (25, 27, "unto light,"),
        (28, 30, "according to"),
        (31, 32, "the word"),
        (33, 35, "of God;"),
        (36, 36, "yea,"),
        (37, 40, "it shall be brought"),
        (41, 45, "out of the earth,"),
        (46, 46, "and"),
        (47, 51, "shall shine forth"),
        (52, 56, "forth out of darkness,"),
        (57, 59, "and come"),
        (60, 62, "unto the knowledge"),
        (63, 64, "of the people;"),
        (65, 65, "and"),
        (66, 69, "shall be done"),
        (70, 72, "by the power"),
        (73, 75, "of God."),
    ],
    17: [
        (0, 4, "And if there be"),
        (5, 6, "faults,"),
        (7, 9, "they are the faults"),
        (10, 12, "of a man."),
        (13, 14, "But behold,"),
        (15, 18, "we know of no"),
        (19, 20, "fault;"),
        (21, 24, "nevertheless"),
        (25, 26, "knoweth"),
        (27, 29, "God"),
        (30, 31, "all things;"),
        (32, 33, "therefore,"),
        (34, 38, "he that condemneth,"),
        (39, 42, "let him beware"),
        (43, 47, "lest he be in danger"),
        (48, 50, "of the fire"),
        (51, 52, "of hell."),
    ],
    18: [
        (0, 0, "And"),
        (1, 5, "he saith:"),
        (6, 8, "Show"),
        (9, 11, "unto me,"),
        (12, 13, "or else"),
        (14, 17, "shall be smitten"),
        (18, 18, "thee—"),
        (19, 20, "beware"),
        (21, 23, "lest he"),
        (24, 25, "should command"),
        (26, 27, "the thing"),
        (28, 29, "which is forbidden"),
        (30, 32, "by the Lord."),
    ],
    19: [
        (0, 1, "For behold,"),
        (2, 4, "he that"),
        (5, 6, "judgeth rashly"),
        (7, 10, "shall be dealt hastily"),
        (11, 13, "and judged again;"),
        (14, 14, "for"),
        (15, 18, "shall be rewarded"),
        (19, 20, "he"),
        (21, 23, "according to"),
        (24, 25, "his works;"),
        (26, 27, "therefore,"),
        (28, 30, "he that"),
        (31, 32, "smiteth"),
        (33, 37, "shall be smitten again"),
        (38, 39, "he"),
        (40, 42, "by the Lord."),
    ],
    20: [
        (0, 0, "Behold,"),
        (1, 3, "that which"),
        (4, 7, "is said"),
        (8, 9, "the holy scriptures—"),
        (10, 14, "let not man"),
        (15, 17, "smite,"),
        (18, 22, "nor judge;"),
        (23, 26, "for judgment"),
        (27, 30, "is mine,"),
        (31, 34, "saith"),
        (35, 36, "the Lord,"),
        (37, 40, "and vengeance"),
        (41, 44, "is mine also,"),
        (45, 45, "and"),
        (46, 52, "I will repay."),
    ],
    21: [
        (0, 2, "And he"),
        (3, 5, "that breatheth out"),
        (6, 7, "anger"),
        (8, 10, "and strifes"),
        (11, 15, "against the work"),
        (16, 18, "of the Lord,"),
        (19, 22, "and against the people"),
        (23, 25, "of the covenant"),
        (26, 28, "of the Lord"),
        (29, 30, "who are"),
        (31, 35, "of the house of Israel,"),
        (36, 39, "and shall say:"),
        (40, 44, "We will destroy"),
        (45, 49, "the work of the Lord,"),
        (50, 54, "and will no more remember"),
        (55, 57, "the Lord"),
        (58, 59, "his covenant"),
        (60, 63, "which he hath made"),
        (64, 68, "with the house of Israel—"),
        (69, 72, "the same"),
        (73, 75, "is in danger"),
        (76, 80, "to be hewn down"),
        (81, 85, "and cast into the fire;"),
    ],
    22: [
        (0, 0, "For"),
        (1, 5, "shall still roll on"),
        (6, 7, "forward"),
        (8, 9, "the eternal purposes"),
        (10, 12, "of the Lord,"),
        (13, 16, "until be fulfilled"),
        (17, 19, "all his promises."),
    ],
    23: [
        (0, 1, "Search"),
        (2, 5, "the prophecies of Isaiah."),
        (6, 6, "Behold,"),
        (7, 12, "I cannot write"),
        (13, 14, "them."),
        (15, 15, "Yea,"),
        (16, 16, "behold"),
        (17, 20, "I say"),
        (21, 23, "unto you,"),
        (24, 26, "the saints"),
        (27, 29, "who"),
        (30, 32, "have gone before"),
        (33, 35, "before me,"),
        (36, 40, "who have dwelt in"),
        (41, 42, "this land,"),
        (43, 47, "shall cry out,"),
        (48, 48, "yea,"),
        (49, 54, "they shall cry out"),
        (55, 55, "even"),
        (56, 58, "unto the Lord"),
        (59, 61, "from the earth;"),
        (62, 66, "and as liveth"),
        (67, 68, "the Lord,"),
        (69, 73, "he will remember"),
        (74, 76, "the covenant"),
        (77, 79, "which he made"),
        (80, 82, "with them."),
    ],
    24: [
        (0, 4, "And he knoweth"),
        (5, 7, "their prayers,"),
        (8, 9, "which were made"),
        (10, 13, "for their brethren."),
        (14, 17, "And he knoweth"),
        (18, 20, "their faith,"),
        (21, 24, "for in his name"),
        (25, 29, "they could"),
        (30, 32, "remove mountains;"),
        (33, 36, "and in his name"),
        (37, 39, "they could"),
        (40, 42, "command"),
        (43, 44, "the earth"),
        (45, 46, "to be shaken;"),
        (47, 50, "and by the power"),
        (51, 53, "of his word"),
        (54, 57, "they did command"),
        (58, 58, "prisons"),
        (59, 61, "to tumble down"),
        (62, 64, "to the earth;"),
        (65, 65, "yea,"),
        (66, 68, "even"),
        (69, 71, "the fiery furnace"),
        (72, 77, "could not harm"),
        (78, 79, "them,"),
        (80, 83, "nor wild beasts,"),
        (84, 87, "nor poisonous serpents,"),
        (88, 91, "because of the power"),
        (92, 94, "of his word."),
    ],
    25: [
        (0, 1, "And behold,"),
        (2, 6, "and their prayers also"),
        (7, 9, "were for him"),
        (10, 13, "should be granted"),
        (14, 15, "it"),
        (16, 18, "by the Lord"),
        (19, 21, "to bring forth"),
        (22, 23, "these things"),
        (24, 25, "to light."),
    ],
    26: [
        (0, 4, "And there is none"),
        (5, 9, "need say"),
        (10, 15, "shall not come"),
        (16, 17, "these things,"),
        (18, 18, "for"),
        (19, 24, "shall truly come"),
        (25, 25, "indeed"),
        (26, 27, "unto them,"),
        (28, 28, "for"),
        (29, 32, "hath spoken it"),
        (33, 34, "the Lord;"),
        (35, 35, "for"),
        (36, 40, "shall come forth"),
        (41, 42, "these things"),
        (43, 44, "forth"),
        (45, 47, "out of the earth,"),
        (48, 52, "by the hand"),
        (53, 55, "of the Lord,"),
        (56, 60, "and there is none"),
        (61, 65, "who can stay it;"),
        (66, 66, "and"),
        (67, 71, "shall come"),
        (72, 73, "the day"),
        (74, 78, "that men shall say"),
        (79, 83, "there are no more"),
        (84, 85, "miracles;"),
        (86, 86, "and"),
        (87, 91, "it shall come"),
        (92, 96, "even as one"),
        (97, 99, "who spake"),
        (100, 103, "from the dead."),
    ],
    27: [
        (0, 0, "And"),
        (1, 5, "shall come"),
        (6, 7, "the day"),
        (8, 13, "shall cry out"),
        (14, 15, "the blood"),
        (16, 19, "of the saints"),
        (20, 22, "unto the Lord,"),
        (23, 24, "because of"),
        (25, 26, "secret combinations"),
        (27, 31, "and works of darkness."),
    ],
    28: [
        (0, 0, "Yea,"),
        (1, 5, "shall come"),
        (6, 7, "the day"),
        (8, 12, "when shall be denied"),
        (13, 17, "the power of God,"),
        (18, 18, "and"),
        (19, 23, "shall be corrupted"),
        (24, 24, "the churches"),
        (25, 28, "and be puffed up"),
        (29, 31, "in the pride"),
        (32, 35, "of their hearts;"),
        (36, 36, "yea,"),
        (37, 40, "even in the day"),
        (41, 46, "when shall rise up"),
        (47, 49, "leaders and teachers"),
        (50, 51, "of churches"),
        (52, 54, "in the pride"),
        (55, 58, "of their hearts,"),
        (59, 60, "even"),
        (61, 63, "to envy"),
        (64, 67, "them"),
        (68, 71, "who belong"),
        (72, 74, "to their churches."),
    ],
    29: [
        (0, 0, "Yea,"),
        (1, 5, "shall come"),
        (6, 7, "the day"),
        (8, 12, "when shall be heard"),
        (13, 15, "of fires,"),
        (16, 18, "and tempests,"),
        (19, 23, "and vapors of smoke"),
        (24, 26, "in foreign lands;"),
    ],
    30: [
        (0, 0, "And"),
        (1, 5, "shall also be heard"),
        (6, 6, "of wars,"),
        (7, 9, "rumors of wars,"),
        (10, 11, "and earthquakes"),
        (12, 14, "in divers places."),
    ],
    31: [
        (0, 0, "Yea,"),
        (1, 5, "shall come"),
        (6, 7, "the day"),
        (8, 12, "when there shall be"),
        (13, 15, "great pollutions"),
        (16, 20, "upon the face of the earth;"),
        (21, 25, "there shall be"),
        (26, 28, "murders,"),
        (29, 31, "and robbing,"),
        (32, 33, "and lying,"),
        (34, 35, "and deceivings,"),
        (36, 37, "and whoredoms,"),
        (38, 40, "and abominations"),
        (41, 43, "of all kinds;"),
        (44, 46, "at the time"),
        (47, 51, "when there shall be"),
        (52, 53, "many"),
        (54, 55, "who"),
        (56, 60, "shall say,"),
        (61, 62, "Do this,"),
        (63, 67, "or do that,"),
        (68, 71, "and it mattereth not,"),
        (72, 72, "for"),
        (73, 76, "will uphold"),
        (77, 79, "the Lord"),
        (80, 81, "such a one"),
        (82, 85, "at the last day."),
        (86, 88, "But wo"),
        (89, 91, "unto such,"),
        (92, 96, "for they are"),
        (97, 100, "in the gall of bitterness"),
        (101, 105, "and in bonds of iniquity."),
    ],
    32: [
        (0, 0, "Yea,"),
        (1, 5, "shall come"),
        (6, 8, "in the day"),
        (9, 13, "when there shall be"),
        (14, 16, "churches built up"),
        (17, 21, "that shall say:"),
        (22, 26, "Come unto me,"),
        (27, 27, "and"),
        (28, 31, "shall be forgiven"),
        (32, 32, "you"),
        (33, 35, "your sins"),
        (36, 39, "for your money."),
    ],
    33: [
        (0, 4, "O ye wicked"),
        (5, 6, "and perverse"),
        (7, 9, "and stiffnecked,"),
        (10, 14, "why have ye built up"),
        (15, 15, "churches"),
        (16, 18, "unto yourselves"),
        (19, 22, "to get"),
        (23, 23, "gain?"),
        (24, 28, "Why have ye altered"),
        (29, 31, "the holy word"),
        (32, 34, "of God,"),
        (35, 39, "that ye might"),
        (40, 42, "bring"),
        (43, 45, "damnation"),
        (46, 48, "upon"),
        (49, 51, "your souls?"),
        (52, 52, "Behold,"),
        (53, 55, "look ye"),
        (56, 60, "unto the revelations of God;"),
        (61, 62, "for behold,"),
        (63, 65, "cometh"),
        (66, 67, "the time"),
        (68, 70, "at that day"),
        (71, 75, "when shall be fulfilled"),
        (76, 78, "all these things."),
    ],
    34: [
        (0, 0, "Behold,"),
        (1, 3, "hath shown"),
        (4, 6, "the Lord"),
        (7, 9, "unto me"),
        (10, 13, "great and marvelous things"),
        (14, 15, "concerning"),
        (16, 17, "that which"),
        (18, 22, "must shortly come,"),
        (23, 25, "at that day"),
        (26, 31, "when shall come"),
        (32, 33, "these things"),
        (34, 36, "unto you."),
    ],
    35: [
        (0, 0, "Behold,"),
        (1, 4, "I speak"),
        (5, 7, "unto you"),
        (8, 9, "as if"),
        (10, 13, "ye were present"),
        (14, 17, "at this time,"),
        (18, 18, "and yet"),
        (19, 21, "ye are not"),
        (22, 24, "present."),
        (25, 26, "But behold,"),
        (27, 29, "hath shown"),
        (30, 30, "you"),
        (31, 33, "unto me"),
        (34, 36, "by Jesus Christ,"),
        (37, 40, "and I know"),
        (41, 42, "your"),
        (43, 45, "doings."),
    ],
    36: [
        (0, 3, "And I know"),
        (4, 6, "that ye do walk"),
        (7, 9, "in the pride"),
        (10, 13, "of your hearts;"),
        (14, 18, "and there are none"),
        (19, 23, "save it be a few"),
        (24, 28, "who are not puffed up"),
        (29, 30, "themselves"),
        (31, 32, "up"),
        (33, 35, "in the pride"),
        (36, 39, "of their hearts,"),
        (40, 42, "unto the wearing"),
        (43, 46, "of very costly apparel,"),
        (47, 49, "unto envyings,"),
        (50, 51, "and strifes,"),
        (52, 54, "and malice,"),
        (55, 56, "and persecutions,"),
        (57, 58, "and iniquities"),
        (59, 61, "of all kinds;"),
        (62, 66, "and your churches,"),
        (67, 67, "yea,"),
        (68, 71, "even every one,"),
        (72, 73, "have become polluted"),
        (74, 77, "because of the pride"),
        (78, 81, "of your hearts."),
    ],
    37: [
        (0, 1, "For behold,"),
        (2, 4, "exceedeth"),
        (5, 7, "your love"),
        (8, 9, "of money,"),
        (10, 13, "and your substance,"),
        (14, 18, "and your fine apparel,"),
        (19, 21, "and the adorning"),
        (22, 25, "of your churches,"),
        (26, 29, "more than your love"),
        (30, 33, "of the poor"),
        (34, 38, "and the needy,"),
        (39, 41, "the sick"),
        (42, 45, "and the afflicted."),
    ],
    38: [
        (0, 2, "O ye"),
        (3, 6, "who are polluted,"),
        (7, 10, "ye hypocrites,"),
        (11, 13, "ye teachers;"),
        (14, 14, "O,"),
        (15, 19, "who do sell"),
        (20, 21, "yourselves"),
        (22, 25, "for that which will decay,"),
        (26, 27, "why"),
        (28, 31, "do ye pollute"),
        (32, 34, "the holy church"),
        (35, 37, "of God?"),
        (38, 39, "Why"),
        (40, 43, "are ye ashamed"),
        (44, 45, "to take"),
        (46, 49, "upon you"),
        (50, 53, "the name of Christ?"),
        (54, 55, "Why"),
        (56, 60, "think ye not"),
        (61, 64, "that greater"),
        (65, 67, "is the worth"),
        (68, 70, "of happiness"),
        (71, 73, "endless"),
        (74, 78, "than that misery"),
        (79, 82, "which never endeth—"),
        (83, 84, "because of"),
        (85, 86, "the praise"),
        (87, 89, "of the world?"),
    ],
    39: [
        (0, 1, "Why"),
        (2, 5, "do ye adorn"),
        (6, 7, "yourselves"),
        (8, 9, "with that which"),
        (10, 13, "hath no life,"),
        (14, 17, "and yet ye suffer"),
        (18, 21, "the hungry,"),
        (22, 25, "and the poor,"),
        (26, 30, "and the naked,"),
        (31, 34, "and the sick"),
        (35, 36, "and afflicted,"),
        (37, 39, "to pass by"),
        (40, 43, "you,"),
        (44, 47, "and ye notice not"),
        (48, 49, "them?"),
    ],
    40: [
        (0, 0, "Yea,"),
        (1, 5, "why have ye built up"),
        (6, 9, "your secret combinations"),
        (10, 13, "to get gain,"),
        (14, 15, "and cause"),
        (16, 18, "that widows may mourn"),
        (19, 23, "whose husbands are dead"),
        (24, 28, "before the Lord,"),
        (29, 32, "and also orphans"),
        (33, 34, "to mourn"),
        (35, 39, "before the Lord,"),
        (40, 44, "and also to cry"),
        (45, 47, "unto the Lord"),
        (48, 51, "from the blood"),
        (52, 55, "of their fathers"),
        (56, 59, "and their husbands,"),
        (60, 62, "for vengeance"),
        (63, 65, "upon"),
        (66, 68, "your heads?"),
    ],
    41: [
        (0, 0, "Behold,"),
        (1, 3, "hangeth over"),
        (4, 5, "the sword"),
        (6, 8, "of vengeance"),
        (9, 12, "over you;"),
        (13, 15, "and soon"),
        (16, 18, "cometh"),
        (19, 21, "the time"),
        (22, 27, "that he shall avenge"),
        (28, 29, "the blood"),
        (30, 33, "of the saints"),
        (34, 37, "upon you,"),
        (38, 38, "for"),
        (39, 45, "he will no longer suffer"),
        (46, 48, "their cries."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
