"""Hand-curated TAM-phrase gloss overrides for Mosaea 13 — Abinadi protected by the Spirit; he recites the Ten Commandments and defends the law.

Follows GLOSSING_RULES.md and the no-injected-words rule: each cell's English
maps only to the Samoan words in that cell's span. TAM clusters atomic (rule 1),
subject `o ia` / agent `e ia` absorbed into the verb cluster, never split as a
bare "he" (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` fillers when a PP/object follows (rule 1), `mafai ona`/`ina ia`/
`ina ua` bound (rules 13/15), vocative `e`/`E …e` folded as "O X" (rule 12),
directional "forth" dropped (rule 12a). No pronoun/TAM word injected into a cell
whose span lacks that token; no content word repeats across adjacent cells
(except authentic Samoan doublings and correlatives).

To rebuild after editing:
    python3 build_overrides_mosiah13.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "mosiah"
CHAPTER_NUM = 13
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now"),
        (3, 6, "when had made an end"),
        (7, 8, "of hearing"),
        (9, 10, "the king"),
        (11, 13, "these words,"),
        (14, 18, "he said"),
        (19, 21, "unto his priests:"),
        (22, 24, "Take away"),
        (25, 26, "this man,"),
        (27, 28, "and slay"),
        (29, 31, "him;"),
        (32, 36, "for what"),
        (37, 39, "is our concern"),
        (40, 41, "to do"),
        (42, 44, "with him,"),
        (45, 45, "for"),
        (46, 49, "he is mad."),
    ],
    2: [
        (0, 4, "And they stood forth"),
        (5, 6, "and attempted"),
        (7, 8, "to lay"),
        (9, 11, "their hands"),
        (12, 14, "on him;"),
        (15, 15, "but"),
        (16, 20, "he withstood"),
        (21, 24, "them,"),
        (25, 27, "and said"),
        (28, 31, "unto them:"),
    ],
    3: [
        (0, 4, "Touch not"),
        (5, 7, "me,"),
        (8, 13, "for shall smite you"),
        (14, 16, "God"),
        (17, 20, "if come"),
        (21, 23, "your hands"),
        (24, 26, "upon me,"),
        (27, 27, "for"),
        (28, 32, "I have not delivered"),
        (33, 34, "the message"),
        (35, 38, "which sent me"),
        (39, 41, "the Lord"),
        (42, 44, "to deliver;"),
        (45, 50, "neither have I told"),
        (51, 52, "the thing"),
        (53, 56, "which ye requested"),
        (57, 60, "that I should tell;"),
        (61, 62, "therefore,"),
        (63, 68, "will not suffer"),
        (69, 71, "God"),
        (72, 74, "that I be destroyed"),
        (75, 78, "at this time."),
    ],
    4: [
        (0, 3, "But must"),
        (4, 5, "I fulfil"),
        (6, 6, "the commandments"),
        (7, 10, "which hath commanded me"),
        (11, 13, "God"),
        (14, 15, "and because"),
        (16, 19, "I have told"),
        (20, 22, "you"),
        (23, 24, "the truth,"),
        (25, 28, "ye are angry"),
        (29, 31, "with me."),
        (32, 34, "And again,"),
        (35, 39, "because I have spoken"),
        (40, 44, "the word of God"),
        (45, 48, "ye have judged"),
        (49, 51, "me"),
        (52, 53, "saying"),
        (54, 56, "I am mad."),
    ],
    5: [
        (0, 1, "Now"),
        (2, 3, "it came to pass"),
        (4, 7, "after had made an end"),
        (8, 9, "of speaking"),
        (10, 11, "Abinadi"),
        (12, 13, "these words"),
        (14, 15, "durst not"),
        (16, 17, "the people"),
        (18, 22, "of king Noah"),
        (23, 25, "to touch"),
        (26, 28, "their hands"),
        (29, 31, "on him,"),
        (32, 32, "for"),
        (33, 37, "was upon him"),
        (38, 42, "the Spirit of the Lord;"),
        (43, 45, "and shone"),
        (46, 47, "his face"),
        (48, 51, "with exceeding luster,"),
        (52, 54, "even as"),
        (55, 58, "the face of Moses"),
        (59, 61, "while he was"),
        (62, 66, "in the mount of Sinai,"),
        (67, 68, "while speaking"),
        (69, 71, "with the Lord."),
    ],
    6: [
        (0, 5, "And he spake"),
        (6, 8, "with power"),
        (9, 11, "and authority"),
        (12, 14, "from God;"),
        (15, 21, "and he continued"),
        (22, 23, "his words,"),
        (24, 25, "saying:"),
    ],
    7: [
        (0, 2, "Ye see"),
        (3, 7, "that ye have no power"),
        (8, 10, "to slay"),
        (11, 11, "me,"),
        (12, 13, "therefore"),
        (14, 20, "I will finish"),
        (21, 22, "my message."),
        (23, 23, "Yea,"),
        (24, 27, "and I perceive"),
        (28, 30, "that ye are pierced"),
        (31, 34, "in your hearts"),
        (35, 39, "because I tell"),
        (40, 42, "you"),
        (43, 45, "the truth"),
        (46, 47, "concerning"),
        (48, 50, "your iniquities."),
    ],
    8: [
        (0, 0, "Yea,"),
        (1, 5, "and also my words"),
        (6, 9, "do fill you"),
        (10, 12, "with wonder"),
        (13, 15, "and amazement,"),
        (16, 18, "and with anger."),
    ],
    9: [
        (0, 4, "But I finish"),
        (5, 6, "my message;"),
        (7, 9, "and then"),
        (10, 12, "it matters not"),
        (13, 15, "whither"),
        (16, 20, "I go,"),
        (21, 24, "if it so be"),
        (25, 27, "that I be saved."),
    ],
    10: [
        (0, 4, "But this much"),
        (5, 6, "of the things"),
        (7, 10, "I tell"),
        (11, 13, "unto you,"),
        (14, 16, "the thing"),
        (17, 19, "ye do"),
        (20, 22, "with me,"),
        (23, 27, "after this is ended,"),
        (28, 31, "shall be"),
        (32, 34, "as a type"),
        (35, 37, "and a shadow"),
        (38, 39, "of the things"),
        (40, 44, "which are to come."),
    ],
    11: [
        (0, 2, "And now"),
        (3, 6, "I read"),
        (7, 9, "unto you"),
        (10, 13, "the commandments of God"),
        (14, 15, "which remain"),
        (16, 19, "for I perceive"),
        (20, 23, "that are not written"),
        (24, 25, "they"),
        (26, 29, "in your hearts;"),
        (30, 33, "I perceive also"),
        (34, 36, "that ye have studied"),
        (37, 39, "and taught"),
        (40, 41, "iniquity"),
        (42, 45, "the most part"),
        (46, 49, "of your lives."),
    ],
    12: [
        (0, 2, "And now,"),
        (3, 5, "ye remember"),
        (6, 9, "that I said"),
        (10, 12, "unto you:"),
        (13, 16, "Thou shalt not make"),
        (17, 18, "for thyself"),
        (19, 20, "an idol"),
        (21, 22, "graven,"),
        (23, 26, "or any likeness"),
        (27, 28, "of things"),
        (29, 32, "which are in heaven"),
        (33, 34, "above,"),
        (35, 37, "or things"),
        (38, 41, "which are in the earth"),
        (42, 44, "beneath,"),
        (45, 47, "or things"),
        (48, 50, "which are in the water"),
        (51, 53, "under"),
        (54, 56, "the earth."),
    ],
    13: [
        (0, 2, "And again:"),
        (3, 6, "Thou shalt not bow down"),
        (7, 8, "thyself"),
        (9, 10, "unto them,"),
        (11, 15, "neither shalt thou serve"),
        (16, 17, "them;"),
        (18, 20, "for I"),
        (21, 23, "am the Lord"),
        (24, 25, "thy God"),
        (26, 29, "am a jealous God,"),
        (30, 32, "visiting"),
        (33, 36, "the iniquities of the fathers"),
        (37, 40, "upon the children,"),
        (41, 44, "unto the third generation"),
        (45, 47, "and fourth"),
        (48, 50, "of them"),
        (51, 54, "who hate"),
        (55, 57, "me;"),
    ],
    14: [
        (0, 2, "And showing"),
        (3, 5, "mercy"),
        (6, 7, "unto thousands"),
        (8, 10, "of them"),
        (11, 15, "who love"),
        (16, 18, "me"),
        (19, 20, "and keep"),
        (21, 23, "my commandments."),
    ],
    15: [
        (0, 4, "Thou shalt not take in vain"),
        (5, 9, "the name of the Lord"),
        (10, 11, "thy God;"),
        (12, 16, "for shall condemn"),
        (17, 19, "the Lord"),
        (20, 21, "him"),
        (22, 25, "that he"),
        (26, 27, "taketh in vain"),
        (28, 29, "his name."),
    ],
    16: [
        (0, 1, "Remember"),
        (2, 4, "the sabbath day,"),
        (5, 6, "to keep"),
        (7, 8, "it holy."),
    ],
    17: [
        (0, 3, "Six days"),
        (4, 7, "shalt thou labor,"),
        (8, 10, "and do"),
        (11, 14, "all thy work;"),
    ],
    18: [
        (0, 4, "But the seventh day,"),
        (5, 10, "the sabbath of the Lord"),
        (11, 12, "thy God,"),
        (13, 17, "thou shalt not do"),
        (18, 19, "any work,"),
        (20, 21, "thou,"),
        (22, 25, "nor thy son,"),
        (26, 29, "nor thy daughter,"),
        (30, 32, "thy manservant,"),
        (33, 36, "nor thy maidservant,"),
        (37, 40, "nor thy cattle,"),
        (41, 45, "nor the stranger"),
        (46, 48, "that is within"),
        (49, 51, "thy gates;"),
    ],
    19: [
        (0, 1, "For in"),
        (2, 4, "six days"),
        (5, 7, "made"),
        (8, 10, "the Lord"),
        (11, 12, "heaven"),
        (13, 15, "and earth,"),
        (16, 18, "and the sea,"),
        (19, 22, "and all things"),
        (23, 25, "that are therein;"),
        (26, 29, "wherefore"),
        (30, 32, "blessed"),
        (33, 35, "the Lord"),
        (36, 38, "the sabbath day,"),
        (39, 42, "and hallowed it."),
    ],
    20: [
        (0, 2, "Honor"),
        (3, 5, "thy father"),
        (6, 8, "and thy mother,"),
        (9, 10, "that"),
        (11, 11, "may be prolonged"),
        (12, 13, "thy days"),
        (14, 18, "upon the land"),
        (19, 21, "which giveth"),
        (22, 24, "the Lord"),
        (25, 26, "thy God"),
        (27, 29, "unto thee."),
    ],
    21: [
        (0, 4, "Thou shalt not kill."),
    ],
    22: [
        (0, 3, "Thou shalt not commit adultery."),
        (4, 7, "Thou shalt not steal."),
    ],
    23: [
        (0, 4, "Thou shalt not bear false witness"),
        (5, 9, "against thy neighbor."),
    ],
    24: [
        (0, 3, "Thou shalt not covet"),
        (4, 6, "the house"),
        (7, 11, "of thy neighbor,"),
        (12, 15, "thou shalt not covet"),
        (16, 18, "the wife"),
        (19, 23, "of thy neighbor,"),
        (24, 28, "nor his manservant,"),
        (29, 33, "nor his maidservant,"),
        (34, 37, "nor his ox,"),
        (38, 41, "nor his ass,"),
        (42, 44, "nor any"),
        (45, 47, "thing whatever"),
        (48, 52, "that is thy neighbor's."),
    ],
    25: [
        (0, 2, "And it came to pass"),
        (3, 6, "after had made an end"),
        (7, 7, "of finishing"),
        (8, 9, "Abinadi"),
        (10, 12, "these sayings"),
        (13, 18, "he said"),
        (19, 22, "unto them:"),
        (23, 28, "Have ye taught"),
        (29, 30, "this people"),
        (31, 33, "that they should"),
        (34, 35, "observe"),
        (36, 38, "in the doing"),
        (39, 42, "of all these things"),
        (43, 45, "that be kept"),
        (46, 47, "these commandments?"),
    ],
    26: [
        (0, 3, "I say"),
        (4, 6, "unto you,"),
        (7, 8, "Nay;"),
        (9, 11, "for if"),
        (12, 13, "ye had done,"),
        (14, 17, "would not have caused"),
        (18, 20, "the Lord"),
        (21, 23, "that I come"),
        (24, 26, "and prophesy"),
        (27, 28, "evil"),
        (29, 30, "concerning"),
        (31, 33, "this people."),
    ],
    27: [
        (0, 2, "And now"),
        (3, 6, "ye have said"),
        (7, 9, "that cometh"),
        (10, 11, "salvation"),
        (12, 16, "by the law of Moses."),
        (17, 20, "I say"),
        (21, 23, "unto you"),
        (24, 26, "that ye should"),
        (27, 29, "keep as yet"),
        (30, 33, "the law of Moses"),
        (34, 37, "for the present;"),
        (38, 42, "but I say"),
        (43, 45, "unto you,"),
        (46, 48, "cometh"),
        (49, 50, "the time"),
        (51, 57, "when shall no more be expedient"),
        (58, 59, "to keep"),
        (60, 64, "the law of Moses."),
    ],
    28: [
        (0, 0, "And"),
        (1, 5, "moreover,"),
        (6, 9, "I say"),
        (10, 12, "unto you,"),
        (13, 16, "that cometh not"),
        (17, 18, "salvation"),
        (19, 21, "by only"),
        (22, 23, "the law;"),
        (24, 27, "and were it not for"),
        (28, 29, "the atonement,"),
        (30, 34, "which shall make"),
        (35, 39, "God himself"),
        (40, 41, "for the sins"),
        (42, 43, "and iniquities"),
        (44, 46, "of his people,"),
        (47, 50, "unavoidably"),
        (51, 53, "must"),
        (54, 55, "perish"),
        (56, 57, "they,"),
        (58, 59, "notwithstanding"),
        (60, 62, "the law"),
        (63, 64, "of Moses."),
    ],
    29: [
        (0, 2, "And now"),
        (3, 6, "I say"),
        (7, 9, "unto you"),
        (10, 14, "that there should be"),
        (15, 16, "a law"),
        (17, 19, "given"),
        (20, 24, "to the children of Israel,"),
        (25, 25, "yea,"),
        (26, 28, "even a law"),
        (29, 30, "very strict;"),
        (31, 34, "for they"),
        (35, 37, "were a people"),
        (38, 40, "stiffnecked,"),
        (41, 42, "quick"),
        (43, 45, "they to do"),
        (46, 48, "iniquity,"),
        (49, 50, "and slow"),
        (51, 53, "they to remember"),
        (54, 56, "the Lord"),
        (57, 59, "their God;"),
    ],
    30: [
        (0, 1, "Therefore"),
        (2, 4, "there was"),
        (5, 6, "a law"),
        (7, 9, "given"),
        (10, 13, "unto them,"),
        (14, 14, "yea,"),
        (15, 17, "a law"),
        (18, 19, "of performances"),
        (20, 21, "and ordinances,"),
        (22, 24, "a law"),
        (25, 27, "which they should"),
        (28, 32, "observe strictly"),
        (33, 35, "from day"),
        (36, 38, "to day,"),
        (39, 41, "to keep"),
        (42, 43, "them"),
        (44, 46, "in remembrance"),
        (47, 49, "of God"),
        (50, 53, "and their duty"),
        (54, 56, "towards him."),
    ],
    31: [
        (0, 1, "But behold,"),
        (2, 5, "I say"),
        (6, 8, "unto you,"),
        (9, 12, "all these things"),
        (13, 15, "were types"),
        (16, 17, "of things"),
        (18, 22, "which are to come."),
    ],
    32: [
        (0, 2, "And now,"),
        (3, 7, "did they understand"),
        (8, 10, "the law?"),
        (11, 14, "I say"),
        (15, 17, "unto you,"),
        (18, 19, "Nay,"),
        (20, 24, "they did not all understand"),
        (25, 27, "the law;"),
        (28, 30, "and now"),
        (31, 34, "because of the hardness"),
        (35, 38, "of their hearts;"),
        (39, 43, "for they understood not"),
        (44, 48, "that could not be saved"),
        (49, 52, "any man"),
        (53, 55, "except through"),
        (56, 58, "the redemption"),
        (59, 61, "of God."),
    ],
    33: [
        (0, 1, "For behold,"),
        (2, 6, "did not prophesy"),
        (7, 7, "Moses"),
        (8, 11, "unto them"),
        (12, 13, "concerning"),
        (14, 17, "the coming"),
        (18, 20, "of the Messiah,"),
        (21, 25, "and that shall redeem"),
        (26, 28, "God"),
        (29, 30, "his people?"),
        (31, 31, "Yea,"),
        (32, 34, "and even"),
        (35, 37, "all the prophets"),
        (38, 41, "who have prophesied"),
        (42, 45, "since the beginning"),
        (46, 48, "of the world—"),
        (49, 53, "have they not spoken"),
        (54, 56, "in some measure"),
        (57, 58, "concerning"),
        (59, 61, "these things?"),
    ],
    34: [
        (0, 5, "Have they not said"),
        (6, 10, "that should come down"),
        (11, 14, "God himself"),
        (15, 19, "among the children"),
        (20, 21, "of men,"),
        (22, 23, "and take"),
        (24, 26, "upon him"),
        (27, 30, "the form of man,"),
        (31, 33, "and go forth"),
        (34, 37, "in mighty power"),
        (38, 42, "upon the face of the earth?"),
    ],
    35: [
        (0, 0, "Yea,"),
        (1, 7, "and have they not said also"),
        (8, 13, "that he should bring to pass"),
        (14, 16, "the resurrection"),
        (17, 20, "of the dead,"),
        (21, 23, "and he,"),
        (24, 26, "even he himself,"),
        (27, 30, "should be oppressed"),
        (31, 32, "and afflicted?"),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
