"""
Hand-curated TAM-phrase gloss overrides for Mamona (Mormon) 2 — Mormon, though young, is
made leader of the Nephite armies; the long retreat before the Lamanites, the loss of
cities and lands, the sorrow of the people that is not unto repentance but the sorrowing
of the damned, Mormon's grief at their wickedness, the fortifying of the land of Shem,
the many battles and treaties, and Mormon's recovery of the plates of Nephi as Ammaron
had directed.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: atomic 2-5 token
cells (TAM clusters 1, subject `o ia`/agent `e ia` absorbed 2, NP/PP atoms
split 3, `mai`-as-"from" 7, idioms 9, em-dash splits 11, `mafai ona`/`ina ia`/
`e tatau ona` bound 13/15). `o le a` stays atomic and is never fused with a
following `se X` NP; cells go past 5 only for rule-2 (absorbed subject) or
rule-7 (`o le a` + verb + directional) clusters.

    python3 build_overrides_mormon2.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "mormon"
CHAPTER_NUM = 2

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And it came to pass"),
        (3, 6, "in that same year,"),
        (7, 10, "there began again to"),
        (11, 12, "be"),
        (13, 15, "a war"),
        (16, 19, "between"),
        (20, 21, "the Nephites"),
        (22, 24, "and the Lamanites."),
        (25, 28, "And notwithstanding"),
        (29, 31, "I being young,"),
        (32, 35, "I was large in stature;"),
        (36, 37, "therefore"),
        (38, 41, "appointed me"),
        (42, 44, "the people"),
        (45, 46, "of Nephi"),
        (47, 49, "that I should be"),
        (50, 53, "their leader,"),
        (54, 57, "or the leader"),
        (58, 61, "of their armies."),
    ],
    2: [
        (0, 1, "Therefore"),
        (2, 4, "it came to pass"),
        (5, 7, "in the ten"),
        (8, 10, "and sixth"),
        (11, 13, "year"),
        (14, 18, "I did go forth"),
        (19, 20, "at the head"),
        (21, 23, "of an army"),
        (24, 26, "of the Nephites,"),
        (27, 28, "against"),
        (29, 31, "the Lamanites;"),
        (32, 33, "therefore"),
        (34, 36, "had passed away"),
        (37, 39, "three hundred"),
        (40, 43, "and twenty and six"),
        (44, 44, "years."),
    ],
    3: [
        (0, 2, "And it came to pass"),
        (3, 5, "in the year"),
        (6, 8, "three hundred"),
        (9, 12, "and twenty and seven"),
        (13, 16, "did come"),
        (17, 18, "the Lamanites"),
        (19, 21, "upon"),
        (22, 23, "us"),
        (24, 28, "with an exceedingly great power,"),
        (29, 31, "insomuch that"),
        (32, 33, "they did frighten"),
        (34, 35, "my armies;"),
        (36, 37, "therefore"),
        (38, 42, "they would not"),
        (43, 44, "fight,"),
        (45, 49, "and they began to retreat"),
        (50, 51, "towards"),
        (52, 54, "the north lands."),
    ],
    4: [
        (0, 3, "And it came to pass that"),
        (4, 6, "we did come"),
        (7, 9, "to the city"),
        (10, 11, "of Angola,"),
        (12, 15, "and we did possess"),
        (16, 17, "the city,"),
        (18, 20, "and make preparations"),
        (21, 23, "to defend"),
        (24, 26, "ourselves"),
        (27, 28, "against"),
        (29, 31, "the Lamanites."),
        (32, 35, "And it came to pass that"),
        (36, 37, "we did fortify"),
        (38, 39, "the city"),
        (40, 42, "according to"),
        (43, 45, "our might;"),
        (46, 48, "but notwithstanding"),
        (49, 52, "all our fortifications"),
        (53, 57, "yet did come"),
        (58, 59, "the Lamanites"),
        (60, 63, "upon us"),
        (64, 66, "and did drive out"),
        (67, 68, "us"),
        (69, 69, "out of"),
        (70, 71, "the city."),
    ],
    5: [
        (0, 4, "And they did drive out"),
        (5, 5, "also"),
        (6, 7, "us"),
        (8, 10, "out of the land"),
        (11, 12, "of David."),
    ],
    6: [
        (0, 3, "And we did march"),
        (4, 6, "and came"),
        (7, 9, "to the land"),
        (10, 11, "of Joshua,"),
        (12, 15, "which was"),
        (16, 17, "in the borders"),
        (18, 19, "west"),
        (20, 22, "by"),
        (23, 25, "the seashore."),
    ],
    7: [
        (0, 3, "And it came to pass that"),
        (4, 5, "we did gather"),
        (6, 8, "our people"),
        (9, 11, "as fast"),
        (12, 14, "as could"),
        (15, 16, "be done,"),
        (17, 20, "that we might"),
        (21, 23, "gather together"),
        (24, 25, "them"),
        (26, 30, "in one body."),
    ],
    8: [
        (0, 1, "But behold,"),
        (2, 3, "was filled"),
        (4, 5, "the land"),
        (6, 7, "with robbers"),
        (8, 10, "and with Lamanites;"),
        (11, 14, "and notwithstanding"),
        (15, 17, "the great destruction"),
        (18, 20, "which hung over"),
        (21, 23, "over"),
        (24, 25, "my people,"),
        (26, 29, "they did not repent"),
        (30, 32, "of their"),
        (33, 34, "evil doings;"),
        (35, 36, "therefore"),
        (37, 39, "was spread"),
        (40, 42, "all the land"),
        (43, 45, "with blood"),
        (46, 48, "and carnage,"),
        (49, 51, "on the part"),
        (52, 54, "of the Nephites"),
        (55, 58, "and also the part"),
        (59, 61, "of the Lamanites;"),
        (62, 66, "and it was a revolution"),
        (67, 68, "one complete"),
        (69, 71, "throughout"),
        (72, 74, "all the land."),
    ],
    9: [
        (0, 2, "And now,"),
        (3, 5, "there was"),
        (6, 7, "a king"),
        (8, 10, "of the Lamanites,"),
        (11, 14, "whose name"),
        (15, 16, "was Aaron;"),
        (17, 21, "and he came against"),
        (22, 25, "us"),
        (26, 28, "with an army"),
        (29, 33, "of forty and four"),
        (34, 34, "thousand."),
        (35, 36, "And behold,"),
        (37, 40, "I withstood"),
        (41, 43, "him"),
        (44, 46, "with an army"),
        (47, 51, "of forty and two"),
        (52, 52, "thousand."),
        (53, 56, "And it came to pass that"),
        (57, 58, "I"),
        (59, 61, "with my army"),
        (62, 63, "did beat"),
        (64, 65, "him"),
        (66, 69, "insomuch that"),
        (70, 73, "he fled"),
        (74, 74, "from"),
        (75, 76, "my presence."),
        (77, 78, "And behold,"),
        (79, 80, "was done"),
        (81, 83, "all these things,"),
        (84, 87, "and had passed away"),
        (88, 90, "three hundred"),
        (91, 93, "and thirty"),
        (94, 95, "years."),
    ],
    10: [
        (0, 3, "And it came to pass that"),
        (4, 6, "began to repent"),
        (7, 8, "the Nephites"),
        (9, 12, "of their iniquity,"),
        (13, 16, "and began to cry"),
        (17, 20, "even as"),
        (21, 22, "had been prophesied"),
        (23, 24, "by Samuel"),
        (25, 26, "the prophet;"),
        (27, 28, "for behold,"),
        (29, 31, "could not"),
        (32, 34, "any man"),
        (35, 36, "keep"),
        (37, 40, "that which was his own,"),
        (41, 42, "because of"),
        (43, 44, "the thieves,"),
        (45, 46, "and the robbers,"),
        (47, 49, "and the murderers,"),
        (50, 53, "and the magic art,"),
        (54, 55, "and the witchcraft"),
        (56, 58, "which was"),
        (59, 61, "in the land."),
    ],
    11: [
        (0, 4, "Thus there began"),
        (5, 6, "to be"),
        (7, 9, "a mourning"),
        (10, 12, "and a lamentation"),
        (13, 16, "in all the land"),
        (17, 18, "because of"),
        (19, 20, "these things,"),
        (21, 25, "and more especially"),
        (26, 27, "particularly"),
        (28, 30, "among the people"),
        (31, 32, "of Nephi."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 5, "I,"),
        (6, 7, "Mormon,"),
        (8, 9, "saw"),
        (10, 13, "their lamentation"),
        (14, 17, "and their mourning"),
        (18, 21, "and their sorrow"),
        (22, 24, "before"),
        (25, 26, "the Lord,"),
        (27, 30, "did begin to rejoice"),
        (31, 33, "my heart"),
        (34, 35, "within"),
        (36, 38, "me,"),
        (39, 41, "for I knew"),
        (42, 45, "the mercies"),
        (46, 48, "and the long-suffering"),
        (49, 51, "of the Lord,"),
        (52, 53, "therefore"),
        (54, 57, "I supposed"),
        (58, 63, "he would be merciful"),
        (64, 64, "unto"),
        (65, 68, "them,"),
        (69, 72, "that would again become"),
        (73, 74, "they"),
        (75, 78, "a righteous people."),
    ],
    13: [
        (0, 1, "But behold,"),
        (2, 4, "was vain"),
        (5, 7, "this my joy,"),
        (8, 9, "for"),
        (10, 12, "their sorrowing"),
        (13, 16, "was not"),
        (17, 19, "unto repentance,"),
        (20, 21, "because of"),
        (22, 23, "the goodness"),
        (24, 26, "of God;"),
        (27, 30, "but it was the sorrowing"),
        (31, 33, "of the damned,"),
        (34, 34, "because"),
        (35, 38, "would not always suffer"),
        (39, 40, "them"),
        (41, 43, "the Lord"),
        (44, 46, "always"),
        (47, 49, "to take happiness"),
        (50, 52, "in sin."),
    ],
    14: [
        (0, 0, "And"),
        (1, 5, "they did not come"),
        (6, 7, "unto Jesus"),
        (8, 11, "with broken hearts"),
        (12, 15, "and contrite spirits,"),
        (16, 19, "but they did curse"),
        (20, 22, "God,"),
        (23, 24, "and wish"),
        (25, 27, "to die."),
        (28, 31, "Nevertheless"),
        (32, 36, "they would struggle"),
        (37, 39, "with the sword"),
        (40, 43, "for their lives."),
    ],
    15: [
        (0, 3, "And it came to pass that"),
        (4, 5, "thus"),
        (6, 8, "came again"),
        (9, 10, "my sorrow"),
        (11, 13, "unto me,"),
        (14, 17, "and I saw"),
        (18, 20, "was passed"),
        (21, 22, "the day"),
        (23, 26, "of grace"),
        (27, 27, "from"),
        (28, 31, "them,"),
        (32, 32, "temporally"),
        (33, 34, "and spiritually;"),
        (35, 35, "for"),
        (36, 38, "I saw"),
        (39, 40, "thousands"),
        (41, 43, "of them"),
        (44, 47, "hewn down"),
        (48, 49, "because of"),
        (50, 52, "the open rebellion"),
        (53, 55, "against"),
        (56, 58, "their God,"),
        (59, 61, "and heaped up"),
        (62, 64, "as"),
        (65, 67, "the dung of beasts"),
        (68, 70, "upon"),
        (71, 72, "the land."),
        (73, 76, "And thus"),
        (77, 78, "passed away"),
        (79, 81, "three hundred"),
        (82, 85, "and forty and four"),
        (86, 87, "years."),
    ],
    16: [
        (0, 2, "And it came to pass"),
        (3, 5, "in the year"),
        (6, 8, "three hundred"),
        (9, 12, "and forty and fifth,"),
        (13, 17, "did begin to flee"),
        (18, 20, "the Nephites"),
        (21, 23, "before"),
        (24, 25, "the Lamanites;"),
        (26, 28, "and were pursued"),
        (29, 30, "they"),
        (31, 33, "until"),
        (34, 36, "they came"),
        (37, 39, "to the land"),
        (40, 41, "of Jashon,"),
        (42, 45, "only then could"),
        (46, 46, "be stopped"),
        (47, 48, "them"),
        (49, 49, "in"),
        (50, 52, "their flight."),
    ],
    17: [
        (0, 2, "And now,"),
        (3, 5, "the city"),
        (6, 7, "of Jashon"),
        (8, 10, "was near"),
        (11, 14, "the land where"),
        (15, 17, "had deposited"),
        (18, 19, "Ammaron"),
        (20, 20, "the records"),
        (21, 23, "unto the Lord,"),
        (24, 27, "that they might not be destroyed."),
        (28, 29, "And behold"),
        (30, 33, "I had gone"),
        (34, 36, "according to"),
        (37, 38, "the word"),
        (39, 40, "of Ammaron,"),
        (41, 42, "and took"),
        (43, 45, "the plates of Nephi,"),
        (46, 48, "and did make"),
        (49, 50, "a record"),
        (51, 54, "according to the words"),
        (55, 56, "of Ammaron."),
    ],
    18: [
        (0, 3, "And upon"),
        (4, 6, "the plates of Nephi"),
        (7, 10, "I did make"),
        (11, 13, "a full account"),
        (14, 16, "of all the wickedness"),
        (17, 20, "and abominations;"),
        (21, 24, "but upon"),
        (25, 26, "these plates"),
        (27, 31, "I did forbear to make"),
        (32, 34, "a full account"),
        (35, 38, "of their wickedness"),
        (39, 41, "and abominations,"),
        (42, 43, "for behold,"),
        (44, 47, "has been before"),
        (48, 49, "mine eyes"),
        (50, 51, "since"),
        (52, 53, "the time"),
        (54, 57, "that I could"),
        (58, 59, "behold"),
        (60, 61, "the ways"),
        (62, 64, "of man,"),
        (65, 68, "a continual scene"),
        (69, 71, "of wickedness"),
        (72, 74, "and abominations."),
    ],
    19: [
        (0, 1, "And O,"),
        (2, 3, "O wretched me,"),
        (4, 5, "because of"),
        (6, 8, "their wickedness;"),
        (9, 9, "for"),
        (10, 11, "is full"),
        (12, 13, "my heart"),
        (14, 16, "of sorrow,"),
        (17, 20, "all my days,"),
        (21, 22, "because of"),
        (23, 25, "their wickedness;"),
        (26, 29, "nevertheless,"),
        (30, 32, "I know"),
        (33, 37, "that shall be lifted up"),
        (38, 38, "I"),
        (39, 40, "on high"),
        (41, 44, "at the last day."),
    ],
    20: [
        (0, 3, "And it came to pass that"),
        (4, 5, "were again hunted"),
        (6, 7, "and driven"),
        (8, 8, "the people"),
        (9, 10, "of Nephi"),
        (11, 14, "in this year."),
        (15, 18, "And it came to pass that"),
        (19, 19, "were driven"),
        (20, 21, "we"),
        (22, 24, "until"),
        (25, 27, "we came"),
        (28, 30, "to the land"),
        (31, 32, "northward"),
        (33, 34, "which was called"),
        (35, 36, "Shem."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 5, "we did fortify"),
        (6, 6, "the city"),
        (7, 8, "of Shem,"),
        (9, 12, "and we did gather in"),
        (13, 15, "our people"),
        (16, 18, "as much"),
        (19, 21, "as could"),
        (22, 23, "be done,"),
        (24, 25, "that perhaps"),
        (26, 29, "we might"),
        (30, 31, "save"),
        (32, 33, "them"),
        (34, 34, "from"),
        (35, 36, "destruction."),
    ],
    22: [
        (0, 2, "And it came to pass"),
        (3, 5, "in the year"),
        (6, 8, "three hundred"),
        (9, 12, "and forty and six,"),
        (13, 16, "they began to"),
        (17, 18, "again attack"),
        (19, 20, "us."),
    ],
    23: [
        (0, 3, "And it came to pass that"),
        (4, 6, "I did speak"),
        (7, 9, "unto my people,"),
        (10, 12, "and did urge"),
        (13, 16, "them"),
        (17, 20, "with great energy,"),
        (21, 24, "that they would stand"),
        (25, 27, "boldly"),
        (28, 30, "before"),
        (31, 32, "the Lamanites"),
        (33, 34, "and fight"),
        (35, 38, "for their wives,"),
        (39, 42, "and their children,"),
        (43, 46, "and their houses,"),
        (47, 50, "and their homes."),
    ],
    24: [
        (0, 2, "And did arouse"),
        (3, 4, "them"),
        (5, 8, "somewhat to vigor"),
        (9, 11, "by my words,"),
        (12, 14, "insomuch that"),
        (15, 17, "they did not flee"),
        (18, 20, "from before"),
        (21, 22, "the Lamanites,"),
        (23, 26, "but did stand"),
        (27, 29, "with boldness"),
        (30, 31, "against"),
        (32, 35, "them."),
    ],
    25: [
        (0, 3, "And it came to pass that"),
        (4, 5, "we did contend"),
        (6, 8, "with an army"),
        (9, 11, "of thirty thousand"),
        (12, 14, "against"),
        (15, 16, "an army"),
        (17, 19, "of fifty thousand."),
        (20, 23, "And it came to pass that"),
        (24, 26, "we did stand"),
        (27, 30, "before them"),
        (31, 34, "with such firmness"),
        (35, 38, "that"),
        (39, 41, "they did flee"),
        (42, 42, "from"),
        (43, 45, "our presence."),
    ],
    26: [
        (0, 3, "And it came to pass that"),
        (4, 6, "when they had fled,"),
        (7, 9, "we did pursue"),
        (10, 11, "them"),
        (12, 13, "with"),
        (14, 16, "our armies,"),
        (17, 20, "and did meet again"),
        (21, 23, "them,"),
        (24, 25, "and did beat"),
        (26, 27, "them;"),
        (28, 31, "nevertheless"),
        (32, 34, "was not with"),
        (35, 36, "the strength"),
        (37, 39, "of the Lord"),
        (40, 42, "us;"),
        (43, 43, "yea,"),
        (44, 47, "we were left"),
        (48, 51, "to ourselves,"),
        (52, 54, "did not abide"),
        (55, 56, "the Spirit"),
        (57, 59, "of the Lord"),
        (60, 63, "in us;"),
        (64, 65, "therefore"),
        (66, 69, "we had become weak"),
        (70, 72, "like unto"),
        (73, 75, "our brethren."),
    ],
    27: [
        (0, 2, "And was sorrowful"),
        (3, 4, "my heart"),
        (5, 6, "because of"),
        (7, 9, "this great calamity"),
        (10, 12, "of my people,"),
        (13, 14, "because of"),
        (15, 17, "their wickedness"),
        (18, 20, "and their"),
        (21, 22, "abominations."),
        (23, 24, "But behold,"),
        (25, 28, "we did go forth"),
        (29, 30, "against"),
        (31, 33, "the Lamanites"),
        (34, 37, "and the band of robbers"),
        (38, 39, "of Gadianton,"),
        (40, 42, "until"),
        (43, 45, "we again took"),
        (46, 46, "the lands"),
        (47, 50, "of our inheritance."),
    ],
    28: [
        (0, 3, "And had passed away"),
        (4, 5, "the year"),
        (6, 8, "three hundred"),
        (9, 12, "and forty and ninth."),
        (13, 16, "And in the year"),
        (17, 19, "three hundred"),
        (20, 22, "and fiftieth,"),
        (23, 26, "we made"),
        (27, 28, "a treaty"),
        (29, 31, "with the Lamanites"),
        (32, 34, "and the band of robbers"),
        (35, 36, "of Gadianton,"),
        (37, 37, "in which"),
        (38, 41, "we did divide"),
        (42, 42, "the lands"),
        (43, 46, "of our inheritance."),
    ],
    29: [
        (0, 3, "And did give"),
        (4, 6, "the Lamanites"),
        (7, 10, "unto us"),
        (11, 12, "the land"),
        (13, 14, "northward,"),
        (15, 15, "yea,"),
        (16, 19, "even to"),
        (20, 22, "the passage"),
        (23, 24, "narrow which"),
        (25, 27, "which led"),
        (28, 30, "into the land"),
        (31, 32, "southward."),
        (33, 37, "And we did give"),
        (38, 40, "unto the Lamanites"),
        (41, 43, "all the land"),
        (44, 45, "southward."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
