"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 37 — Alma's charge
to Helaman concerning the sacred records: the plates of brass, the plates of
Nephi, the twenty-four gold plates and the interpreters; the word of God and
the Liahona as types; small and simple things bring to pass great things.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), em-dash source splits
(rule 11), `mafai ona`/`ina ia`/`e tatau ona` bound (rules 13/15).

Em-dash pre-splits done up front against bom_books.json:
  v13 `laueleele—ae`   -> 55 tokens
  v38 `faasinoala—pe`  -> 62 tokens

    python3 build_overrides_alma37.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 37

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "And now,"),
        (3, 5, "my son"),
        (6, 6, "Helaman,"),
        (7, 10, "I command"),
        (11, 13, "you"),
        (14, 17, "that ye take the records"),
        (18, 21, "which have been entrusted"),
        (22, 24, "with me;"),
    ],
    2: [
        (0, 5, "And I also command"),
        (6, 8, "you,"),
        (9, 13, "that ye keep a record"),
        (14, 16, "of this people,"),
        (17, 19, "even as"),
        (20, 22, "I have done,"),
        (23, 25, "upon"),
        (26, 28, "the plates of Nephi,"),
        (29, 33, "and keep sacred"),
        (34, 36, "all these things"),
        (37, 39, "which I have kept,"),
        (40, 43, "even as"),
        (44, 46, "I have kept"),
        (47, 49, "them;"),
        (50, 51, "for"),
        (52, 55, "for a wise purpose"),
        (56, 58, "they are kept."),
    ],
    3: [
        (0, 2, "And the plates"),
        (3, 5, "of brass, these,"),
        (6, 9, "which contain"),
        (10, 11, "these engravings,"),
        (12, 16, "which have the records"),
        (17, 19, "of the holy scriptures"),
        (20, 23, "upon them,"),
        (24, 27, "which have"),
        (28, 29, "the genealogy"),
        (30, 32, "of the fathers of"),
        (33, 35, "our forefathers,"),
        (36, 40, "even from the beginning—"),
    ],
    4: [
        (0, 0, "Behold,"),
        (1, 2, "it hath been prophesied"),
        (3, 6, "by our fathers,"),
        (7, 8, "that"),
        (9, 14, "they should be kept"),
        (15, 19, "and handed down"),
        (20, 23, "from one generation"),
        (24, 26, "to another,"),
        (27, 30, "and be kept and preserved"),
        (31, 34, "by the hand of"),
        (35, 36, "the Lord"),
        (37, 41, "until they should go forth"),
        (42, 43, "unto every nation,"),
        (44, 45, "and kindred,"),
        (46, 47, "and tongue,"),
        (48, 50, "and all people,"),
        (51, 54, "that they may know"),
        (55, 58, "the mysteries thereon."),
    ],
    5: [
        (0, 3, "And now behold,"),
        (4, 8, "if they are kept"),
        (9, 13, "they must retain"),
        (14, 16, "their brightness;"),
        (17, 17, "yea,"),
        (18, 22, "and they will retain"),
        (23, 23, "still"),
        (24, 26, "their brightness;"),
        (27, 27, "yea,"),
        (28, 32, "and so shall it be"),
        (33, 33, "also"),
        (34, 35, "with all the plates"),
        (36, 39, "which contain"),
        (40, 42, "holy writ."),
    ],
    6: [
        (0, 1, "Now"),
        (2, 5, "ye may suppose"),
        (6, 8, "that I am foolish"),
        (9, 11, "in this thing;"),
        (12, 13, "but behold"),
        (14, 17, "I say"),
        (18, 20, "unto you,"),
        (21, 25, "by small and simple things"),
        (26, 28, "are brought to pass"),
        (29, 30, "great things;"),
        (31, 34, "and small means"),
        (35, 39, "in many instances"),
        (40, 42, "doth confound"),
        (43, 44, "the wise."),
    ],
    7: [
        (0, 6, "And the Lord God doth work"),
        (7, 8, "by means"),
        (9, 11, "to bring about"),
        (12, 14, "his great purposes"),
        (15, 16, "and eternal;"),
        (17, 21, "and by very small means"),
        (22, 27, "the Lord doth confound"),
        (28, 29, "the wise,"),
        (30, 32, "and bringeth about"),
        (33, 36, "the salvation of souls"),
        (37, 38, "many."),
    ],
    8: [
        (0, 2, "And now,"),
        (3, 5, "hitherto"),
        (6, 9, "until this time"),
        (10, 12, "it is wisdom"),
        (13, 17, "in God"),
        (18, 22, "that these things are preserved;"),
        (23, 24, "for behold,"),
        (25, 27, "they have enlarged"),
        (28, 32, "the memory of this people,"),
        (33, 33, "yea,"),
        (34, 37, "and convinced many"),
        (38, 40, "of the error"),
        (41, 44, "of their ways,"),
        (45, 48, "and brought them"),
        (49, 51, "to the knowledge"),
        (52, 55, "of their God"),
        (56, 58, "unto the salvation"),
        (59, 62, "of their souls."),
    ],
    9: [
        (0, 0, "Yea,"),
        (1, 4, "I say"),
        (5, 7, "unto you,"),
        (8, 12, "were it not for these things"),
        (13, 16, "which are in"),
        (17, 18, "these records,"),
        (19, 23, "which are on"),
        (24, 25, "these plates,"),
        (26, 29, "could not"),
        (30, 34, "Ammon and his brethren"),
        (35, 36, "have convinced"),
        (37, 41, "so many thousands"),
        (42, 44, "of the Lamanites,"),
        (45, 49, "of the incorrect tradition"),
        (50, 53, "of their fathers;"),
        (54, 54, "yea,"),
        (55, 57, "these records"),
        (58, 61, "and their words"),
        (62, 66, "brought them"),
        (67, 69, "unto repentance;"),
        (70, 72, "that is,"),
        (73, 77, "they brought them"),
        (78, 80, "to the knowledge"),
        (81, 83, "of the Lord"),
        (84, 86, "their God,"),
        (87, 89, "and to rejoice"),
        (90, 92, "in Jesus Christ"),
        (93, 95, "their Redeemer."),
    ],
    10: [
        (0, 5, "And who knoweth"),
        (6, 10, "but what they will become"),
        (11, 12, "the means"),
        (13, 15, "of bringing"),
        (16, 19, "many thousands"),
        (20, 22, "of them,"),
        (23, 23, "yea,"),
        (24, 27, "and also many"),
        (28, 29, "thousands"),
        (30, 35, "of our stiffnecked brethren,"),
        (36, 38, "the Nephites,"),
        (39, 44, "who are now hardening"),
        (45, 47, "their hearts"),
        (48, 52, "in sin and iniquities,"),
        (53, 55, "to the knowledge"),
        (56, 59, "of their Redeemer?"),
    ],
    11: [
        (0, 1, "Now"),
        (2, 5, "these mysteries"),
        (6, 10, "are not yet fully made known"),
        (11, 13, "unto me"),
        (14, 17, "at this time;"),
        (18, 19, "therefore"),
        (20, 23, "I shall"),
        (24, 25, "forbear."),
    ],
    12: [
        (0, 3, "And it may suffice"),
        (4, 8, "if I only"),
        (9, 10, "say"),
        (11, 14, "they are preserved"),
        (15, 18, "for a wise purpose,"),
        (19, 21, "which purpose"),
        (22, 26, "is known unto God;"),
        (27, 27, "for"),
        (28, 32, "he doth counsel"),
        (33, 35, "in wisdom"),
        (36, 38, "over"),
        (39, 41, "all his works,"),
        (42, 44, "and straight are"),
        (45, 46, "his paths,"),
        (47, 50, "and his course"),
        (51, 54, "is an eternal round"),
        (55, 56, "one."),
    ],
    13: [
        (0, 0, "O"),
        (1, 3, "remember,"),
        (4, 6, "remember,"),
        (7, 9, "my son"),
        (10, 10, "Helaman,"),
        (11, 12, "how strict are"),
        (13, 17, "the commandments of God."),
        (18, 23, "And he said:"),
        (24, 27, "If ye will keep"),
        (28, 29, "my commandments"),
        (30, 34, "ye shall prosper"),
        (35, 37, "in the land—"),
        (38, 43, "but if ye keep not"),
        (44, 45, "his commandments"),
        (46, 51, "ye shall be cut off"),
        (52, 54, "from his presence."),
    ],
    14: [
        (0, 2, "And now"),
        (3, 5, "remember,"),
        (6, 8, "my son,"),
        (9, 13, "hath entrusted these things"),
        (14, 16, "by God"),
        (17, 19, "unto you,"),
        (20, 24, "which are sacred,"),
        (25, 28, "which he hath kept"),
        (29, 31, "sacred,"),
        (32, 36, "and also which"),
        (37, 41, "he will keep"),
        (42, 43, "and preserve"),
        (44, 47, "for a wise purpose"),
        (48, 51, "in him,"),
        (52, 56, "that he may"),
        (57, 58, "show forth"),
        (59, 60, "his power"),
        (61, 64, "unto future generations."),
    ],
    15: [
        (0, 3, "And now behold,"),
        (4, 7, "I tell"),
        (8, 10, "you"),
        (11, 13, "by"),
        (14, 17, "the spirit of prophecy,"),
        (18, 21, "that if ye transgress"),
        (22, 25, "the commandments of God,"),
        (26, 26, "behold,"),
        (27, 31, "these things which are sacred"),
        (32, 36, "shall be taken away"),
        (37, 39, "from you"),
        (40, 43, "by the power of"),
        (44, 45, "God,"),
        (46, 52, "and thou shalt be delivered up"),
        (53, 54, "unto Satan,"),
        (55, 60, "that he may sift"),
        (61, 61, "thee"),
        (62, 66, "as the chaff"),
        (67, 68, "of wheat"),
        (69, 72, "before the blowing of"),
        (73, 74, "the wind."),
    ],
    16: [
        (0, 4, "But if ye keep"),
        (5, 8, "the commandments of God,"),
        (9, 11, "and ye do"),
        (12, 16, "with these sacred things"),
        (17, 20, "according to that which"),
        (21, 24, "doth command you"),
        (25, 27, "by God,"),
        (28, 28, "(for"),
        (29, 32, "ye must"),
        (33, 34, "appeal"),
        (35, 37, "unto the Lord"),
        (38, 40, "for all things"),
        (41, 44, "whatsoever"),
        (45, 49, "ye must do"),
        (50, 52, "with them)"),
        (53, 53, "behold,"),
        (54, 57, "no power"),
        (58, 60, "of earth"),
        (61, 63, "or hell"),
        (64, 67, "can take away"),
        (68, 69, "them"),
        (70, 73, "from you,"),
        (74, 74, "for"),
        (75, 78, "God is powerful"),
        (79, 80, "to fulfil"),
        (81, 83, "all his words."),
    ],
    17: [
        (0, 0, "For"),
        (1, 5, "he will fulfil"),
        (6, 8, "all his promises"),
        (9, 13, "which he shall"),
        (14, 14, "make"),
        (15, 17, "unto you,"),
        (18, 18, "for"),
        (19, 21, "he hath fulfilled"),
        (22, 23, "his promises"),
        (24, 27, "which he hath made"),
        (28, 31, "unto our fathers."),
    ],
    18: [
        (0, 0, "For"),
        (1, 5, "he promised"),
        (6, 9, "unto them"),
        (10, 14, "that he would preserve"),
        (15, 16, "these things"),
        (17, 20, "for a wise purpose"),
        (21, 24, "in him,"),
        (25, 29, "that he might"),
        (30, 31, "show forth"),
        (32, 33, "his power"),
        (34, 37, "unto future generations."),
    ],
    19: [
        (0, 3, "And now behold,"),
        (4, 6, "hath he fulfilled"),
        (7, 9, "one purpose,"),
        (10, 14, "even the restoration"),
        (15, 19, "of many thousands"),
        (20, 22, "of the Lamanites"),
        (23, 25, "to the knowledge"),
        (26, 28, "of the truth;"),
        (29, 33, "and he hath shown forth"),
        (34, 35, "his power"),
        (36, 38, "through"),
        (39, 41, "them,"),
        (42, 48, "and he will show forth"),
        (49, 49, "also"),
        (50, 51, "his power"),
        (52, 54, "through"),
        (55, 57, "them"),
        (58, 61, "unto future generations,"),
        (62, 63, "therefore"),
        (64, 70, "they shall be preserved."),
    ],
    20: [
        (0, 1, "Therefore"),
        (2, 6, "I command"),
        (7, 9, "you,"),
        (10, 12, "my son"),
        (13, 13, "Helaman,"),
        (14, 16, "that ye be diligent"),
        (17, 18, "in fulfilling"),
        (19, 21, "all my words,"),
        (22, 25, "and that ye be diligent"),
        (26, 28, "in keeping"),
        (29, 33, "the commandments of God"),
        (34, 36, "even as"),
        (37, 40, "they are written."),
    ],
    21: [
        (0, 2, "And now,"),
        (3, 7, "I will speak"),
        (8, 8, "forth"),
        (9, 11, "unto you"),
        (12, 16, "concerning those plates"),
        (17, 19, "the twenty-four,"),
        (20, 23, "that ye keep them,"),
        (24, 29, "that may be made manifest"),
        (30, 32, "unto this people"),
        (33, 34, "the mysteries"),
        (35, 39, "and the works of darkness,"),
        (40, 44, "and their secret works,"),
        (45, 48, "or the secret works"),
        (49, 51, "of those"),
        (52, 55, "who have been destroyed;"),
        (56, 56, "yea,"),
        (57, 62, "that may be made manifest"),
        (63, 65, "unto this people"),
        (66, 70, "all their"),
        (71, 72, "murders,"),
        (73, 75, "and robbings,"),
        (76, 79, "and their plunderings,"),
        (80, 84, "and all their wickedness"),
        (85, 87, "and abominations;"),
        (88, 88, "yea,"),
        (89, 92, "and that ye preserve"),
        (93, 94, "these interpreters."),
    ],
    22: [
        (0, 1, "For behold,"),
        (2, 5, "the Lord saw"),
        (6, 9, "began to work"),
        (10, 11, "his people"),
        (12, 14, "in darkness,"),
        (15, 15, "yea,"),
        (16, 19, "they work secret"),
        (20, 22, "murders"),
        (23, 25, "and abominations;"),
        (26, 27, "therefore"),
        (28, 31, "said"),
        (32, 33, "the Lord,"),
        (34, 38, "if they did not repent"),
        (39, 43, "they should be destroyed"),
        (44, 45, "them"),
        (46, 50, "from off the face of the earth."),
    ],
    23: [
        (0, 3, "And said"),
        (4, 5, "the Lord:"),
        (6, 10, "I will prepare"),
        (11, 15, "unto my servant Gazelem,"),
        (16, 17, "a stone,"),
        (18, 22, "which shall shine"),
        (23, 23, "forth"),
        (24, 26, "from darkness"),
        (27, 29, "unto light,"),
        (30, 34, "that I may"),
        (35, 36, "discover"),
        (37, 39, "unto my people,"),
        (40, 44, "who serve"),
        (45, 47, "me,"),
        (48, 52, "that I may"),
        (53, 54, "discover"),
        (55, 58, "unto them"),
        (59, 63, "the works of their brethren,"),
        (64, 64, "yea,"),
        (65, 68, "their secret works,"),
        (69, 71, "their works"),
        (72, 74, "of darkness,"),
        (75, 78, "and their wickedness"),
        (79, 81, "and abominations."),
    ],
    24: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 8, "these interpreters"),
        (9, 10, "were prepared"),
        (11, 16, "that might be fulfilled"),
        (17, 20, "the word of"),
        (21, 22, "God,"),
        (23, 27, "which he spake,"),
        (28, 29, "saying:"),
    ],
    25: [
        (0, 4, "I will bring"),
        (5, 6, "forth"),
        (7, 9, "out of darkness"),
        (10, 12, "unto light"),
        (13, 17, "all their secret works"),
        (18, 22, "and their abominations;"),
        (23, 25, "and except"),
        (26, 28, "they repent"),
        (29, 34, "I will destroy"),
        (35, 36, "them"),
        (37, 41, "from off the face of the earth;"),
        (42, 47, "and I will bring"),
        (48, 50, "to light"),
        (51, 54, "all their secrets"),
        (55, 57, "and abominations,"),
        (58, 60, "unto every nation"),
        (61, 67, "which shall be theirs"),
        (68, 69, "this land"),
        (70, 73, "after there passeth"),
        (74, 76, "this time."),
    ],
    26: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 8, "we see"),
        (9, 12, "that they did not repent;"),
        (13, 14, "therefore"),
        (15, 19, "they have been destroyed,"),
        (20, 25, "and thus far hath been fulfilled"),
        (26, 29, "the word of"),
        (30, 31, "God;"),
        (32, 32, "yea,"),
        (33, 37, "their abominations"),
        (38, 38, "secret"),
        (39, 42, "have been brought forth"),
        (43, 45, "out of darkness"),
        (46, 49, "and made known"),
        (50, 53, "unto us."),
    ],
    27: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 9, "I command"),
        (10, 12, "you,"),
        (13, 15, "that ye retain"),
        (16, 19, "all their oaths,"),
        (20, 23, "and their covenants,"),
        (24, 27, "and their agreements"),
        (28, 32, "in their abominations"),
        (33, 33, "secret;"),
        (34, 34, "yea,"),
        (35, 39, "and their signs"),
        (40, 40, "all"),
        (41, 44, "and their things"),
        (45, 47, "of wonder"),
        (48, 50, "ye shall keep"),
        (51, 53, "from this people,"),
        (54, 58, "that they know not"),
        (59, 60, "them,"),
        (61, 66, "lest they should also fall"),
        (67, 69, "into darkness"),
        (70, 72, "and be destroyed."),
    ],
    28: [
        (0, 1, "For behold,"),
        (2, 6, "there is a curse"),
        (7, 10, "upon"),
        (11, 13, "all this land,"),
        (14, 18, "that shall come"),
        (19, 20, "destruction"),
        (21, 23, "upon"),
        (24, 26, "all them"),
        (27, 30, "who do the works"),
        (31, 33, "of darkness,"),
        (34, 36, "according to"),
        (37, 41, "the power of God,"),
        (42, 46, "when they are"),
        (47, 48, "fully ripe;"),
        (49, 50, "therefore"),
        (51, 53, "I desire"),
        (54, 56, "that might not be destroyed"),
        (57, 58, "this people."),
    ],
    29: [
        (0, 1, "Therefore"),
        (2, 5, "ye shall keep"),
        (6, 8, "these secret plans"),
        (9, 12, "of their oaths"),
        (13, 16, "and their covenants"),
        (17, 19, "from this people,"),
        (20, 22, "and only"),
        (23, 25, "their wickedness"),
        (26, 30, "and their murders"),
        (31, 35, "and their abominations"),
        (36, 39, "shall ye make known"),
        (40, 43, "unto them;"),
        (44, 48, "and ye shall teach"),
        (49, 50, "them"),
        (51, 52, "to abhor"),
        (53, 55, "such wickedness"),
        (56, 58, "and abominations"),
        (59, 62, "and murders;"),
        (63, 68, "and ye shall also teach"),
        (69, 72, "them"),
        (73, 76, "that these people were destroyed"),
        (77, 81, "because of their wickedness"),
        (82, 84, "and abominations"),
        (85, 89, "and their murders."),
    ],
    30: [
        (0, 1, "For behold,"),
        (2, 4, "they murdered"),
        (5, 9, "all the prophets of the Lord"),
        (10, 14, "who came"),
        (15, 17, "among them"),
        (18, 20, "to declare"),
        (21, 24, "unto them"),
        (25, 29, "concerning their iniquities;"),
        (30, 32, "and the blood"),
        (33, 37, "of those whom they murdered"),
        (38, 40, "did cry"),
        (41, 43, "unto the Lord"),
        (44, 46, "their God"),
        (47, 51, "for vengeance"),
        (52, 56, "upon those"),
        (57, 60, "who murdered"),
        (61, 62, "them;"),
        (63, 66, "and thus"),
        (67, 69, "did come"),
        (70, 74, "the judgments of God"),
        (75, 79, "upon these people"),
        (80, 83, "who do the works"),
        (84, 86, "of darkness"),
        (87, 89, "and secret combinations."),
    ],
    31: [
        (0, 0, "Yea,"),
        (1, 4, "and cursed be"),
        (5, 8, "forever and ever"),
        (9, 10, "the land"),
        (11, 14, "unto those"),
        (15, 18, "who do the works"),
        (19, 21, "of darkness"),
        (22, 24, "and secret combinations,"),
        (25, 28, "even unto"),
        (29, 30, "destruction,"),
        (31, 32, "except"),
        (33, 35, "they repent"),
        (36, 40, "before they are"),
        (41, 42, "fully ripe."),
    ],
    32: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 8, "remember"),
        (9, 9, "the words"),
        (10, 14, "which I have spoken"),
        (15, 17, "unto you;"),
        (18, 21, "trust not"),
        (22, 23, "those secret plans"),
        (24, 26, "unto this people,"),
        (27, 31, "but teach"),
        (32, 35, "them"),
        (36, 39, "an everlasting hatred"),
        (40, 44, "against sin"),
        (45, 47, "and iniquity."),
    ],
    33: [
        (0, 1, "Preach"),
        (2, 5, "unto them"),
        (6, 7, "repentance,"),
        (8, 10, "and faith"),
        (11, 14, "on the Lord"),
        (15, 16, "Jesus Christ;"),
        (17, 18, "teach"),
        (19, 22, "them"),
        (23, 25, "to humble"),
        (26, 28, "themselves"),
        (29, 31, "and to be meek"),
        (32, 34, "and lowly"),
        (35, 37, "in heart;"),
        (38, 39, "teach"),
        (40, 43, "them"),
        (44, 46, "to withstand"),
        (47, 49, "every temptation"),
        (50, 52, "of the devil,"),
        (53, 55, "with"),
        (56, 58, "their faith"),
        (59, 62, "on the Lord"),
        (63, 64, "Jesus Christ."),
    ],
    34: [
        (0, 1, "Teach"),
        (2, 5, "them"),
        (6, 9, "to never be weary"),
        (10, 13, "of the doing of"),
        (14, 15, "good works,"),
        (16, 18, "but to be meek"),
        (19, 21, "and lowly"),
        (22, 24, "in heart;"),
        (25, 25, "for"),
        (26, 28, "such"),
        (29, 33, "shall find"),
        (34, 35, "rest"),
        (36, 39, "to their souls."),
    ],
    35: [
        (0, 0, "O,"),
        (1, 3, "remember,"),
        (4, 6, "my son,"),
        (7, 10, "and learn wisdom"),
        (11, 13, "in thy youth;"),
        (14, 14, "yea,"),
        (15, 15, "learn"),
        (16, 18, "in thy youth"),
        (19, 22, "to keep the commandments"),
        (23, 25, "of God."),
    ],
    36: [
        (0, 0, "Yea,"),
        (1, 3, "and cry"),
        (4, 6, "unto God"),
        (7, 9, "for all things"),
        (10, 13, "that support thee;"),
        (14, 14, "yea,"),
        (15, 19, "let be unto the Lord"),
        (20, 24, "all thy doings,"),
        (25, 28, "and whithersoever"),
        (29, 33, "thou goest"),
        (34, 36, "let it be"),
        (37, 39, "in the Lord;"),
        (40, 40, "yea,"),
        (41, 43, "let be directed"),
        (44, 46, "all thy thoughts"),
        (47, 49, "unto the Lord;"),
        (50, 50, "yea,"),
        (51, 53, "let be placed"),
        (54, 57, "the affections of thy heart"),
        (58, 60, "upon the Lord"),
        (61, 62, "forever."),
    ],
    37: [
        (0, 4, "Counsel with the Lord"),
        (5, 8, "in all thy"),
        (9, 10, "doings,"),
        (11, 16, "and he will direct"),
        (17, 17, "thee"),
        (18, 20, "for good;"),
        (21, 21, "yea,"),
        (22, 25, "when thou liest down"),
        (26, 28, "at night"),
        (29, 32, "lie down unto the Lord,"),
        (33, 36, "that he may"),
        (37, 40, "watch"),
        (41, 43, "over you"),
        (44, 46, "in thy sleep;"),
        (47, 51, "and when thou risest"),
        (52, 54, "in the morning,"),
        (55, 58, "let thy heart be full"),
        (59, 61, "of thanks"),
        (62, 64, "unto God;"),
        (65, 69, "and if ye do"),
        (70, 71, "these things,"),
        (72, 77, "ye shall be lifted up"),
        (78, 79, "on high"),
        (80, 83, "at the last day."),
    ],
    38: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 10, "I have"),
        (11, 12, "somewhat"),
        (13, 17, "to say"),
        (18, 20, "concerning"),
        (21, 23, "the thing which"),
        (24, 29, "our fathers called"),
        (30, 32, "a ball,"),
        (33, 36, "or director—"),
        (37, 40, "or was called"),
        (41, 43, "by our fathers"),
        (44, 46, "Liahona,"),
        (47, 49, "which is,"),
        (50, 52, "being interpreted,"),
        (53, 55, "a compass;"),
        (56, 59, "and the Lord"),
        (60, 61, "prepared it."),
    ],
    39: [
        (0, 1, "And behold,"),
        (2, 5, "there cannot"),
        (6, 7, "any man"),
        (8, 11, "work a thing"),
        (12, 16, "of so curious a manner"),
        (17, 19, "of workmanship."),
        (20, 21, "And behold,"),
        (22, 23, "it was prepared"),
        (24, 27, "to show"),
        (28, 31, "unto our fathers"),
        (32, 33, "the course"),
        (34, 38, "which they should travel"),
        (39, 39, "thereby"),
        (40, 42, "in the wilderness."),
    ],
    40: [
        (0, 5, "And it did work for them"),
        (6, 8, "according to"),
        (9, 11, "their faith"),
        (12, 14, "in God;"),
        (15, 16, "therefore,"),
        (17, 22, "if they had"),
        (23, 24, "faith"),
        (25, 27, "to believe"),
        (28, 32, "that God could"),
        (33, 34, "cause"),
        (35, 37, "that should point"),
        (38, 40, "the spindles"),
        (41, 42, "the way"),
        (43, 47, "which they should go"),
        (48, 48, "therein,"),
        (49, 49, "behold,"),
        (50, 52, "it was done;"),
        (53, 54, "therefore"),
        (55, 59, "they had"),
        (60, 61, "this miracle,"),
        (62, 65, "and also many"),
        (66, 68, "other miracles"),
        (69, 70, "wrought"),
        (71, 74, "by the power of"),
        (75, 76, "God,"),
        (77, 82, "day by day."),
    ],
    41: [
        (0, 3, "Nevertheless,"),
        (4, 7, "because those miracles"),
        (8, 12, "were wrought by small means"),
        (13, 16, "it did show"),
        (17, 20, "unto them"),
        (21, 22, "marvelous works."),
        (23, 28, "but when they became"),
        (29, 29, "slothful,"),
        (30, 33, "and forgot to exercise"),
        (34, 36, "with diligence"),
        (37, 39, "their faith,"),
        (40, 44, "then ceased"),
        (45, 46, "those marvelous works,"),
        (47, 51, "and they did not go"),
        (52, 53, "forward"),
        (54, 57, "in their journey;"),
    ],
    42: [
        (0, 1, "Therefore,"),
        (2, 5, "they tarried"),
        (6, 8, "in the wilderness,"),
        (9, 13, "or did not travel"),
        (14, 17, "a direct course,"),
        (18, 20, "and were afflicted"),
        (21, 24, "with hunger"),
        (25, 28, "and thirst,"),
        (29, 30, "because of"),
        (31, 33, "their transgressions."),
    ],
    43: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 8, "I would"),
        (9, 11, "that ye should understand,"),
        (12, 16, "that these things are not without"),
        (17, 20, "a shadow;"),
        (21, 26, "for as were slothful"),
        (27, 30, "our fathers"),
        (31, 34, "to give heed to"),
        (35, 36, "this compass"),
        (37, 41, "(now these things"),
        (42, 43, "were temporal)"),
        (44, 47, "they did not prosper;"),
        (48, 51, "even so is it also"),
        (52, 54, "with things which are spiritual."),
    ],
    44: [
        (0, 1, "For behold,"),
        (2, 5, "it is as easy"),
        (6, 9, "to give heed"),
        (10, 14, "to the word of Christ,"),
        (15, 20, "which will point"),
        (21, 21, "out"),
        (22, 24, "to you"),
        (25, 27, "a straight course"),
        (28, 31, "leading to"),
        (32, 34, "eternal bliss,"),
        (35, 39, "as it was easy"),
        (40, 43, "for our fathers"),
        (44, 46, "to give heed"),
        (47, 49, "to this compass,"),
        (50, 54, "which would point out"),
        (55, 58, "unto them"),
        (59, 61, "a straight course"),
        (62, 65, "leading to"),
        (66, 69, "the promised land."),
    ],
    45: [
        (0, 2, "And now"),
        (3, 6, "I say,"),
        (7, 11, "is there not a type"),
        (12, 14, "in this thing?"),
        (15, 19, "For just as surely"),
        (20, 24, "as this director did bring"),
        (25, 28, "our fathers,"),
        (29, 32, "by following"),
        (33, 34, "its course,"),
        (35, 39, "to the promised land,"),
        (40, 45, "so also shall"),
        (46, 46, "carry"),
        (47, 49, "us"),
        (50, 53, "the words of Christ,"),
        (54, 58, "if we follow"),
        (59, 62, "their course,"),
        (63, 66, "beyond"),
        (67, 68, "this vale"),
        (69, 71, "of sorrow,"),
        (72, 74, "into a land"),
        (75, 77, "of promise"),
        (78, 82, "which is far better."),
    ],
    46: [
        (0, 0, "O"),
        (1, 3, "my son,"),
        (4, 8, "let us not"),
        (9, 9, "be slothful"),
        (10, 13, "because of the easiness"),
        (14, 16, "of the way;"),
        (17, 17, "for"),
        (18, 22, "so was it"),
        (23, 26, "with our fathers;"),
        (27, 27, "for"),
        (28, 31, "so was it prepared"),
        (32, 34, "for them,"),
        (35, 39, "that they might"),
        (40, 40, "live"),
        (41, 46, "if they would look"),
        (47, 48, "thereon;"),
        (49, 52, "even so also"),
        (53, 54, "is it"),
        (55, 57, "with us."),
        (58, 61, "is prepared"),
        (62, 64, "the way,"),
        (65, 70, "and if we will look"),
        (71, 75, "we may live"),
        (76, 77, "forever."),
    ],
    47: [
        (0, 2, "And now,"),
        (3, 5, "my son,"),
        (6, 6, "see"),
        (7, 9, "that ye take care"),
        (10, 12, "of these sacred things,"),
        (13, 13, "yea,"),
        (14, 14, "see"),
        (15, 18, "that ye look"),
        (19, 21, "to God"),
        (22, 25, "and live."),
        (26, 27, "Go"),
        (28, 30, "unto this people"),
        (31, 35, "and declare the word,"),
        (36, 39, "and be sober."),
        (40, 42, "My son,"),
        (43, 43, "farewell."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
