"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 19 — king Lamoni
raised from his trance; the queen and many others converted; Ammon
overpowered by the Spirit; Abish gathers the people; the church begins
among the Lamanites.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15).

Em-dash token split in the source per rule 11: `agalelei—ioe,` (v6) — so
v6 = 136 tokens.

    python3 build_overrides_alma19.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 19

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 3, "And it came to pass that"),
        (4, 5, "after had passed"),
        (6, 8, "two days"),
        (9, 12, "and two nights"),
        (13, 15, "they intended"),
        (16, 19, "to take"),
        (20, 21, "his body"),
        (22, 23, "and lay"),
        (24, 26, "in a sepulchre,"),
        (27, 30, "which they had made"),
        (31, 33, "for the purpose"),
        (34, 36, "of burying"),
        (37, 40, "their dead."),
    ],
    2: [
        (0, 1, "Now"),
        (2, 4, "having heard"),
        (5, 6, "the queen"),
        (7, 11, "of the fame of Ammon,"),
        (12, 13, "therefore"),
        (14, 18, "she sent"),
        (19, 20, "a message"),
        (21, 23, "unto him"),
        (24, 25, "and desired"),
        (26, 29, "that he should come"),
        (30, 31, "in"),
        (32, 34, "unto her."),
    ],
    3: [
        (0, 3, "And it came to pass that"),
        (4, 4, "did"),
        (5, 6, "Ammon"),
        (7, 13, "as he was commanded,"),
        (14, 17, "and went in"),
        (18, 20, "unto the queen,"),
        (21, 23, "and desired to know"),
        (24, 27, "what"),
        (28, 29, "thing"),
        (30, 34, "she would"),
        (35, 37, "that he should do."),
    ],
    4: [
        (0, 0, "And"),
        (1, 4, "she said"),
        (5, 7, "unto him:"),
        (8, 10, "have made known"),
        (11, 13, "unto me"),
        (14, 18, "the servants of my husband"),
        (19, 20, "that"),
        (21, 22, "thou art"),
        (23, 26, "a prophet of"),
        (27, 29, "a holy God,"),
        (30, 34, "and thou hast"),
        (35, 36, "power"),
        (37, 39, "to do"),
        (40, 43, "many mighty works"),
        (44, 46, "in his name;"),
    ],
    5: [
        (0, 1, "Now,"),
        (2, 6, "if this is the case,"),
        (7, 9, "I would"),
        (10, 13, "that thou shouldst go"),
        (14, 15, "in"),
        (16, 18, "and see"),
        (19, 20, "my husband,"),
        (21, 21, "for"),
        (22, 26, "he has been laid"),
        (27, 31, "upon his bed"),
        (32, 35, "for the space of"),
        (36, 38, "two days"),
        (39, 42, "and two nights;"),
        (43, 46, "and say"),
        (47, 48, "some"),
        (49, 53, "that he is not dead,"),
        (54, 57, "but others say"),
        (58, 61, "that he is dead"),
        (62, 64, "and that he stinketh,"),
        (65, 68, "and that ought"),
        (69, 71, "he be placed"),
        (72, 74, "in the sepulchre;"),
        (75, 80, "but as for myself,"),
        (81, 85, "he doth not stink"),
        (86, 88, "to me."),
    ],
    6: [
        (0, 1, "Now,"),
        (2, 5, "this was the thing"),
        (6, 9, "which desired"),
        (10, 10, "Ammon,"),
        (11, 11, "for"),
        (12, 14, "he knew"),
        (15, 17, "was"),
        (18, 21, "king Lamoni"),
        (22, 24, "under"),
        (25, 27, "the power of"),
        (28, 29, "God;"),
        (30, 32, "he knew"),
        (33, 34, "was cast away"),
        (35, 38, "the dark veil of"),
        (39, 41, "unbelief"),
        (42, 44, "from his mind,"),
        (45, 49, "and the light which"),
        (50, 52, "did light up"),
        (53, 54, "his mind,"),
        (55, 59, "which was the light of"),
        (60, 64, "the glory of God,"),
        (65, 70, "which was a marvelous light of"),
        (71, 72, "his goodness—"),
        (73, 73, "yea,"),
        (74, 76, "this light"),
        (77, 79, "had infused"),
        (80, 81, "his soul"),
        (82, 86, "with such great joy,"),
        (87, 90, "having been dispelled"),
        (91, 95, "the cloud of darkness,"),
        (96, 100, "and was lit up"),
        (101, 103, "in his soul"),
        (104, 106, "the light of"),
        (107, 111, "everlasting life,"),
        (112, 112, "yea,"),
        (113, 115, "he knew"),
        (116, 118, "that this"),
        (119, 120, "had overcome"),
        (121, 123, "his natural frame,"),
        (124, 131, "and he was carried away"),
        (132, 135, "in God—"),
    ],
    7: [
        (0, 1, "Now,"),
        (2, 4, "this was the thing"),
        (5, 8, "which desired"),
        (9, 10, "the queen"),
        (11, 13, "of him,"),
        (14, 16, "and it was the only"),
        (17, 19, "thing"),
        (20, 23, "which she desired."),
        (24, 25, "Therefore,"),
        (26, 31, "he went in"),
        (32, 33, "within"),
        (34, 36, "to see"),
        (37, 38, "the king"),
        (39, 41, "according to"),
        (42, 45, "the desire of"),
        (46, 47, "the queen"),
        (48, 50, "unto him;"),
        (51, 55, "and he saw"),
        (56, 58, "the king"),
        (59, 62, "and he knew"),
        (63, 67, "that he was not dead."),
    ],
    8: [
        (0, 0, "And"),
        (1, 5, "he said"),
        (6, 8, "unto the queen:"),
        (9, 13, "He is not dead,"),
        (14, 19, "but he sleepeth"),
        (20, 23, "in God,"),
        (24, 24, "and"),
        (25, 32, "he shall rise again"),
        (33, 37, "on the morrow;"),
        (38, 39, "therefore"),
        (40, 42, "bury not"),
        (43, 44, "him."),
    ],
    9: [
        (0, 3, "And then said"),
        (4, 5, "Ammon"),
        (6, 8, "unto her:"),
        (9, 12, "Believest thou"),
        (13, 15, "this?"),
        (16, 16, "And"),
        (17, 21, "she said"),
        (22, 24, "unto him:"),
        (25, 28, "there is no witness"),
        (29, 32, "unto me"),
        (33, 36, "save thy word,"),
        (37, 40, "and the word of"),
        (41, 43, "our servants;"),
        (44, 47, "nevertheless"),
        (48, 50, "I believe"),
        (51, 55, "that it shall be so"),
        (56, 61, "according as thou hast said."),
    ],
    10: [
        (0, 0, "And"),
        (1, 3, "said"),
        (4, 4, "Ammon"),
        (5, 7, "unto her:"),
        (8, 10, "Blessed art thou"),
        (11, 12, "because of"),
        (13, 15, "thy exceeding faith;"),
        (16, 19, "I say"),
        (20, 22, "unto thee,"),
        (23, 25, "woman,"),
        (26, 30, "there has not been"),
        (31, 34, "such great faith"),
        (35, 37, "among"),
        (38, 42, "all the people of the Nephites."),
    ],
    11: [
        (0, 3, "And it came to pass that"),
        (4, 6, "she watched over"),
        (7, 11, "the bed of her husband,"),
        (12, 15, "from that time"),
        (16, 19, "even until"),
        (20, 22, "the time of"),
        (23, 27, "the following day,"),
        (28, 33, "which Ammon had appointed"),
        (34, 41, "that he should rise."),
    ],
    12: [
        (0, 3, "And it came to pass that"),
        (4, 7, "he arose,"),
        (8, 10, "according to"),
        (11, 13, "the words of Ammon;"),
        (14, 14, "and"),
        (15, 19, "as he arose,"),
        (20, 23, "he stretched forth"),
        (24, 25, "his hand"),
        (26, 28, "unto the woman,"),
        (29, 31, "and said:"),
        (32, 34, "Blessed be"),
        (35, 39, "the name of God,"),
        (40, 43, "and blessed art thou."),
    ],
    13: [
        (0, 0, "For"),
        (1, 4, "as sure as"),
        (5, 8, "thou livest,"),
        (9, 9, "behold,"),
        (10, 13, "I have seen"),
        (14, 15, "my Redeemer;"),
        (16, 16, "and"),
        (17, 23, "he shall come forth,"),
        (24, 26, "and be born"),
        (27, 29, "of a woman,"),
        (30, 35, "and he shall redeem"),
        (36, 37, "all mankind"),
        (38, 41, "who believe"),
        (42, 44, "on his name."),
        (45, 46, "Now,"),
        (47, 51, "when he had"),
        (52, 53, "said"),
        (54, 56, "these words,"),
        (57, 58, "was swollen"),
        (59, 60, "his heart"),
        (61, 65, "within him,"),
        (66, 72, "and he sunk again"),
        (73, 75, "with joy;"),
        (76, 80, "and also sunk down"),
        (81, 82, "the queen,"),
        (83, 85, "being overpowered"),
        (86, 88, "by the Spirit."),
    ],
    14: [
        (0, 1, "Now"),
        (2, 5, "seeing"),
        (6, 6, "Ammon"),
        (7, 9, "poured out"),
        (10, 14, "the Spirit of the Lord"),
        (15, 17, "according to"),
        (18, 19, "his prayers"),
        (20, 24, "upon the Lamanites,"),
        (25, 27, "his brethren,"),
        (28, 32, "who had been"),
        (33, 34, "the cause of"),
        (35, 37, "so much mourning"),
        (38, 42, "among the Nephites,"),
        (43, 46, "or among"),
        (47, 51, "all the people of God"),
        (52, 53, "because of"),
        (54, 56, "their iniquities"),
        (57, 60, "and their traditions,"),
        (61, 64, "he fell down"),
        (65, 67, "upon his knees,"),
        (68, 70, "and began to"),
        (71, 72, "pour out"),
        (73, 74, "his soul"),
        (75, 77, "in prayer"),
        (78, 80, "and thanksgiving"),
        (81, 83, "to God"),
        (84, 88, "for what he had done"),
        (89, 91, "for his brethren;"),
        (92, 97, "and he was also overpowered"),
        (98, 100, "with joy;"),
        (101, 104, "and thus"),
        (105, 108, "had all sunk down"),
        (109, 113, "the three of them"),
        (114, 116, "to the earth."),
    ],
    15: [
        (0, 1, "Now,"),
        (2, 5, "when had seen"),
        (6, 9, "the servants of the king"),
        (10, 13, "that they had fallen,"),
        (14, 17, "also began to"),
        (18, 20, "they cry"),
        (21, 23, "unto God,"),
        (24, 24, "for"),
        (25, 28, "had come also"),
        (29, 32, "upon them"),
        (33, 37, "the fear of the Lord,"),
        (38, 42, "for it was they"),
        (43, 44, "who had stood"),
        (45, 49, "before the king"),
        (50, 52, "and testified"),
        (53, 55, "unto him"),
        (56, 58, "concerning"),
        (59, 63, "the great power of Ammon."),
    ],
    16: [
        (0, 3, "And it came to pass that"),
        (4, 7, "they did call on"),
        (8, 12, "the name of the Lord,"),
        (13, 16, "in their might,"),
        (17, 19, "even until"),
        (20, 23, "they had all fallen"),
        (24, 26, "to the earth,"),
        (27, 28, "save"),
        (29, 31, "one of"),
        (32, 34, "the Lamanitish women,"),
        (35, 39, "whose name was Abish,"),
        (40, 43, "she who"),
        (44, 48, "had been converted unto the Lord"),
        (49, 53, "for many years,"),
        (54, 55, "on account of"),
        (56, 60, "a remarkable vision of"),
        (61, 62, "her father—"),
    ],
    17: [
        (0, 1, "Thus,"),
        (2, 5, "having been converted"),
        (6, 8, "to the Lord,"),
        (9, 12, "and she had never"),
        (13, 15, "made it known,"),
        (16, 17, "therefore,"),
        (18, 22, "when she saw"),
        (23, 26, "had all fallen"),
        (27, 29, "the servants of Lamoni"),
        (30, 32, "to the earth,"),
        (33, 37, "and also her mistress,"),
        (38, 39, "the queen,"),
        (40, 43, "and the king,"),
        (44, 45, "and Ammon"),
        (46, 48, "lay prostrate"),
        (49, 53, "upon the earth,"),
        (54, 56, "she knew"),
        (57, 60, "that it was the power"),
        (61, 63, "of God;"),
        (64, 68, "and supposing"),
        (69, 71, "that this opportunity"),
        (72, 75, "by making known"),
        (76, 77, "unto the people"),
        (78, 80, "what had happened"),
        (81, 82, "among"),
        (83, 86, "them,"),
        (87, 91, "that by beholding"),
        (92, 93, "this scene"),
        (94, 98, "it would cause"),
        (99, 100, "them"),
        (101, 102, "to believe"),
        (103, 106, "in the power of"),
        (107, 108, "God,"),
        (109, 110, "therefore"),
        (111, 115, "she ran forth"),
        (116, 118, "from house"),
        (119, 121, "to house,"),
        (122, 124, "making it known"),
        (125, 126, "unto the people."),
    ],
    18: [
        (0, 3, "And it came to pass that"),
        (4, 5, "began to"),
        (6, 9, "they assemble together"),
        (10, 12, "themselves"),
        (13, 16, "unto the place of"),
        (17, 18, "the king."),
        (19, 22, "And there came"),
        (23, 26, "a multitude,"),
        (27, 31, "and to their astonishment,"),
        (32, 36, "they saw"),
        (37, 39, "the king,"),
        (40, 42, "and the queen,"),
        (43, 46, "and their servants"),
        (47, 49, "prostrate"),
        (50, 54, "upon the earth,"),
        (55, 59, "and they lay there"),
        (60, 61, "as though"),
        (62, 65, "they were dead;"),
        (66, 71, "and they also saw"),
        (72, 73, "Ammon,"),
        (74, 75, "and behold,"),
        (76, 77, "he was"),
        (78, 81, "a Nephite."),
    ],
    19: [
        (0, 2, "And now"),
        (3, 5, "began to"),
        (6, 6, "murmur"),
        (7, 7, "the people"),
        (8, 10, "among"),
        (11, 13, "themselves;"),
        (14, 18, "some saying"),
        (19, 23, "that a great evil"),
        (24, 24, "this"),
        (25, 27, "had come"),
        (28, 31, "upon them,"),
        (32, 35, "or upon"),
        (36, 37, "the king"),
        (38, 40, "and his house,"),
        (41, 41, "because"),
        (42, 44, "he had suffered"),
        (45, 47, "the Nephite"),
        (48, 49, "should remain"),
        (50, 52, "in the land."),
    ],
    20: [
        (0, 2, "But there were others"),
        (3, 5, "who rebuked"),
        (6, 9, "them,"),
        (10, 11, "saying:"),
        (12, 13, "hath brought"),
        (14, 16, "the king"),
        (17, 18, "this evil"),
        (19, 21, "upon his house,"),
        (22, 22, "because"),
        (23, 25, "he slew"),
        (26, 27, "his servants"),
        (28, 32, "who had suffered"),
        (33, 34, "to be scattered"),
        (35, 38, "their flocks"),
        (39, 42, "at the waters of Sebus."),
    ],
    21: [
        (0, 4, "And they also contended"),
        (5, 8, "against"),
        (9, 10, "those men"),
        (11, 13, "who stood at"),
        (14, 16, "the waters of Sebus"),
        (17, 18, "to scatter"),
        (19, 23, "the flocks of the king,"),
        (24, 24, "for"),
        (25, 27, "they were angry"),
        (28, 29, "with Ammon"),
        (30, 34, "because of the number of"),
        (35, 37, "their brethren"),
        (38, 40, "that he had slain"),
        (41, 44, "at the waters of Sebus,"),
        (45, 48, "while he defended"),
        (49, 53, "the flocks of the king."),
    ],
    22: [
        (0, 1, "Now,"),
        (2, 5, "one of"),
        (6, 8, "them,"),
        (9, 11, "he whose"),
        (12, 14, "brother"),
        (15, 16, "had been slain"),
        (17, 21, "with the sword of Ammon,"),
        (22, 23, "because of"),
        (24, 26, "his exceeding anger"),
        (27, 28, "with Ammon,"),
        (29, 33, "drew his sword"),
        (34, 36, "and went forth"),
        (37, 41, "that he might let it fall"),
        (42, 45, "upon Ammon,"),
        (46, 50, "to slay him;"),
        (51, 55, "and as he lifted"),
        (56, 57, "the sword"),
        (58, 62, "to smite him,"),
        (63, 63, "behold,"),
        (64, 68, "he fell down"),
        (69, 70, "dead."),
    ],
    23: [
        (0, 1, "Now"),
        (2, 4, "we see"),
        (5, 8, "that could not"),
        (9, 9, "be slain"),
        (10, 10, "Ammon,"),
        (11, 11, "for"),
        (12, 15, "the Lord had said"),
        (16, 17, "unto Mosiah,"),
        (18, 19, "his father:"),
        (20, 24, "I will spare"),
        (25, 26, "him,"),
        (27, 30, "it shall be done"),
        (31, 33, "unto him"),
        (34, 36, "according to"),
        (37, 38, "thy faith—"),
        (39, 40, "therefore,"),
        (41, 44, "committed"),
        (45, 46, "him"),
        (47, 48, "Mosiah"),
        (49, 51, "unto the Lord."),
    ],
    24: [
        (0, 3, "And it came to pass that"),
        (4, 6, "when beheld"),
        (7, 10, "the multitude"),
        (11, 13, "had fallen"),
        (14, 15, "the man"),
        (16, 18, "who was dead,"),
        (19, 23, "who lifted"),
        (24, 25, "the sword"),
        (26, 27, "to slay"),
        (28, 29, "Ammon,"),
        (30, 32, "came"),
        (33, 34, "the fear"),
        (35, 37, "upon"),
        (38, 40, "them all,"),
        (41, 44, "and they durst not"),
        (45, 47, "put forth"),
        (48, 50, "their hands"),
        (51, 52, "to touch"),
        (53, 55, "him,"),
        (56, 61, "or any of"),
        (62, 63, "them"),
        (64, 67, "who had fallen;"),
        (68, 71, "and began to"),
        (72, 74, "they marvel again"),
        (75, 77, "among"),
        (78, 80, "themselves"),
        (81, 84, "what"),
        (85, 87, "was the cause of"),
        (88, 90, "this great power,"),
        (91, 95, "or what"),
        (96, 98, "was the meaning of"),
        (99, 101, "all these things."),
    ],
    25: [
        (0, 3, "And it came to pass that"),
        (4, 8, "there were many"),
        (9, 13, "among them"),
        (14, 18, "who said"),
        (19, 20, "that Ammon"),
        (21, 25, "was the Great Spirit,"),
        (26, 30, "and others said"),
        (31, 35, "he was sent"),
        (36, 39, "by the Great Spirit;"),
    ],
    26: [
        (0, 2, "But others"),
        (3, 6, "rebuked"),
        (7, 10, "them all,"),
        (11, 12, "saying,"),
        (13, 14, "that he was"),
        (15, 17, "a monster,"),
        (18, 22, "who had been sent"),
        (23, 25, "by the Nephites"),
        (26, 28, "to torment"),
        (29, 31, "them."),
    ],
    27: [
        (0, 3, "And there were"),
        (4, 5, "some"),
        (6, 8, "who said"),
        (9, 10, "that Ammon"),
        (11, 13, "was sent"),
        (14, 17, "by the Great Spirit"),
        (18, 19, "to afflict"),
        (20, 21, "them"),
        (22, 23, "because of"),
        (24, 26, "their iniquities;"),
        (27, 27, "and"),
        (28, 32, "it was the Great Spirit"),
        (33, 36, "that had always attended"),
        (37, 39, "the Nephites,"),
        (40, 44, "who had ever delivered"),
        (45, 46, "them"),
        (47, 50, "out of their hands;"),
        (51, 55, "and they said"),
        (56, 60, "that it was this Great Spirit"),
        (61, 65, "who had destroyed"),
        (66, 68, "so many of"),
        (69, 71, "their brethren,"),
        (72, 73, "the Lamanites."),
    ],
    28: [
        (0, 3, "And thus"),
        (4, 5, "began to"),
        (6, 7, "be exceedingly sharp"),
        (8, 9, "the contention"),
        (10, 14, "among them."),
        (15, 18, "And while thus"),
        (19, 20, "they were contending,"),
        (21, 22, "came"),
        (23, 25, "the woman servant"),
        (26, 30, "who had caused"),
        (31, 33, "to be gathered together"),
        (34, 37, "the multitude,"),
        (38, 44, "and when she saw"),
        (45, 47, "the contention"),
        (48, 53, "which was among"),
        (54, 57, "the multitude,"),
        (58, 62, "she was exceedingly sorrowful,"),
        (63, 67, "even unto tears."),
    ],
    29: [
        (0, 3, "And it came to pass that"),
        (4, 7, "she went"),
        (8, 10, "and took by"),
        (11, 15, "the hand of the queen,"),
        (16, 16, "perhaps"),
        (17, 19, "that might"),
        (20, 22, "she raise"),
        (23, 24, "her"),
        (25, 27, "from the ground;"),
        (28, 32, "and as soon as"),
        (33, 38, "she touched"),
        (39, 41, "her hand"),
        (42, 47, "she arose"),
        (48, 52, "and stood"),
        (53, 55, "upon her feet,"),
        (56, 57, "and cried"),
        (58, 61, "with a loud voice,"),
        (62, 63, "saying:"),
        (64, 67, "O blessed Jesus,"),
        (68, 72, "who has saved"),
        (73, 73, "me"),
        (74, 77, "from an awful hell!"),
        (78, 82, "O blessed God,"),
        (83, 87, "have mercy"),
        (88, 90, "on this people!"),
    ],
    30: [
        (0, 4, "And when she had"),
        (5, 7, "said"),
        (8, 10, "these words,"),
        (11, 14, "she clapped"),
        (15, 16, "her hands,"),
        (17, 21, "being filled with joy,"),
        (22, 24, "and speaking"),
        (25, 28, "many words"),
        (29, 33, "which were not understood"),
        (34, 35, "by any;"),
        (36, 40, "and when she had"),
        (41, 42, "done"),
        (43, 45, "this,"),
        (46, 50, "she took"),
        (51, 53, "the king,"),
        (54, 55, "Lamoni,"),
        (56, 58, "by the hand,"),
        (59, 60, "and behold"),
        (61, 65, "he arose"),
        (66, 70, "and stood"),
        (71, 73, "upon his feet."),
    ],
    31: [
        (0, 2, "And she,"),
        (3, 7, "at the very moment,"),
        (8, 12, "in seeing"),
        (13, 14, "the contention"),
        (15, 18, "which was among"),
        (19, 20, "her people,"),
        (21, 24, "she went"),
        (25, 27, "and began to"),
        (28, 29, "she rebuke"),
        (30, 31, "them,"),
        (32, 34, "and to teach"),
        (35, 38, "them"),
        (39, 39, "the words"),
        (40, 44, "which she had heard"),
        (45, 49, "from the mouth of Ammon;"),
        (50, 54, "and as many of"),
        (55, 56, "them"),
        (57, 61, "as heard her words"),
        (62, 63, "believed,"),
        (64, 67, "and were converted to"),
        (68, 69, "the Lord."),
    ],
    32: [
        (0, 0, "But"),
        (1, 5, "there were many"),
        (6, 10, "among them"),
        (11, 12, "who"),
        (13, 16, "would not hear"),
        (17, 19, "his words;"),
        (20, 21, "therefore"),
        (22, 27, "they went"),
        (28, 31, "their way."),
    ],
    33: [
        (0, 3, "And it came to pass that"),
        (4, 7, "when Ammon arose"),
        (8, 12, "he also administered"),
        (13, 16, "unto them,"),
        (17, 21, "and so also"),
        (22, 22, "did"),
        (23, 27, "all the servants of Lamoni;"),
        (28, 30, "and they"),
        (31, 33, "did all declare"),
        (34, 36, "unto the people"),
        (37, 40, "the selfsame thing—"),
        (41, 42, "that"),
        (43, 44, "had been changed"),
        (45, 47, "their hearts;"),
        (48, 52, "that there was no more"),
        (53, 56, "in them"),
        (57, 58, "desire"),
        (59, 62, "to do evil."),
    ],
    34: [
        (0, 1, "And behold,"),
        (2, 3, "many"),
        (4, 7, "did declare"),
        (8, 10, "unto the people,"),
        (11, 15, "that they had seen angels"),
        (16, 18, "and had conversed"),
        (19, 21, "with them;"),
        (22, 24, "and thus"),
        (25, 29, "they told"),
        (30, 33, "them"),
        (34, 37, "things of God,"),
        (38, 40, "and of his righteousness."),
    ],
    35: [
        (0, 3, "And it came to pass that"),
        (4, 8, "there were many"),
        (9, 10, "that did believe"),
        (11, 13, "in their words;"),
        (14, 17, "and as many"),
        (18, 19, "as believed"),
        (20, 21, "were baptized;"),
        (22, 26, "and became"),
        (27, 28, "they"),
        (29, 31, "a righteous people,"),
        (32, 35, "and they did establish"),
        (36, 37, "a church"),
        (38, 40, "among"),
        (41, 43, "themselves."),
    ],
    36: [
        (0, 3, "And thus"),
        (4, 4, "did commence"),
        (5, 8, "the work of"),
        (9, 10, "the Lord"),
        (11, 15, "among the Lamanites;"),
        (16, 17, "thus"),
        (18, 22, "did begin to"),
        (23, 24, "pour out"),
        (25, 27, "the Lord"),
        (28, 29, "his Spirit"),
        (30, 34, "upon them;"),
        (35, 38, "and we see"),
        (39, 41, "is extended"),
        (42, 43, "his arm"),
        (44, 48, "to all people who"),
        (49, 50, "will repent"),
        (51, 52, "and believe"),
        (53, 55, "on his name."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
