"""Hand-curated TAM-phrase gloss overrides for 2 Nifae 13 — Isaiah 3."""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "2nephi"
CHAPTER_NUM = 13
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 1, "For behold,"),
        (2, 4, "the Lord,"),
        (5, 7, "the Lord"),
        (8, 9, "of Hosts,"),
        (10, 12, "doth take away"),
        (13, 15, "from Jerusalem,"),
        (16, 16, "and"),
        (17, 19, "from Judah,"),
        (20, 21, "the stay"),
        (22, 22, "and"),
        (23, 24, "the staff,"),
        (25, 27, "the whole staff"),
        (28, 30, "of bread,"),
        (31, 31, "and"),
        (32, 34, "the whole stay"),
        (35, 37, "of water"),
        (38, 40, "in life—"),
    ],
    2: [
        (0, 3, "The mighty man,"),
        (4, 4, "and"),
        (5, 8, "the man of war,"),
        (9, 11, "the judge,"),
        (12, 12, "and"),
        (13, 14, "the prophet,"),
        (15, 15, "and"),
        (16, 18, "the prudent man,"),
        (19, 19, "and"),
        (20, 21, "who hath"),
        (22, 22, "prolonged"),
        (23, 24, "his life;"),
    ],
    3: [
        (0, 2, "The captain"),
        (3, 5, "of fifty,"),
        (6, 6, "and"),
        (7, 9, "the honorable man,"),
        (10, 10, "and"),
        (11, 12, "the counselor,"),
        (13, 13, "and"),
        (14, 16, "the cunning artificer,"),
        (17, 17, "and"),
        (18, 20, "the eloquent orator."),
    ],
    4: [
        (0, 0, "And"),
        (1, 6, "I will give"),
        (7, 7, "children"),
        (8, 11, "unto them"),
        (12, 14, "to be as"),
        (15, 17, "their princes,"),
        (18, 18, "and"),
        (19, 22, "shall rule"),
        (23, 23, "babes"),
        (24, 25, "over"),
        (26, 27, "them."),
    ],
    5: [
        (0, 0, "And"),
        (1, 4, "shall be oppressed"),
        (5, 6, "the people,"),
        (7, 9, "every man"),
        (10, 10, "by"),
        (11, 12, "another,"),
        (13, 13, "and"),
        (14, 15, "every man"),
        (16, 16, "by"),
        (17, 18, "his neighbor;"),
        (19, 22, "shall behave"),
        (23, 23, "proudly"),
        (24, 25, "the child"),
        (26, 27, "against"),
        (28, 31, "the ancient,"),
        (32, 32, "and"),
        (33, 35, "the base"),
        (36, 39, "against the honorable."),
    ],
    6: [
        (0, 1, "When"),
        (2, 3, "take hold"),
        (4, 5, "a man"),
        (6, 6, "of"),
        (7, 8, "his brother"),
        (9, 11, "of the house"),
        (12, 14, "of his father,"),
        (15, 15, "and"),
        (16, 17, "say:"),
        (18, 18, "hast"),
        (19, 21, "thou"),
        (22, 22, "clothing,"),
        (23, 25, "be thou"),
        (26, 26, "and"),
        (27, 29, "our ruler,"),
        (30, 30, "and"),
        (31, 33, "leave not"),
        (34, 35, "this ruin"),
        (36, 38, "to come down"),
        (39, 41, "under thy hand—"),
    ],
    7: [
        (0, 2, "In that day"),
        (3, 7, "shall swear thereto"),
        (8, 9, "he,"),
        (10, 11, "saying:"),
        (12, 16, "shall not be"),
        (17, 17, "I"),
        (18, 18, "as"),
        (19, 20, "a healer;"),
        (21, 21, "for"),
        (22, 23, "is not"),
        (24, 26, "there"),
        (27, 29, "in my house"),
        (30, 31, "bread"),
        (32, 33, "nor"),
        (34, 35, "clothing;"),
        (36, 38, "make not"),
        (39, 39, "me"),
        (40, 40, "as"),
        (41, 42, "a ruler"),
        (43, 45, "of the people."),
    ],
    8: [
        (0, 0, "For"),
        (1, 2, "is ruined"),
        (3, 3, "Jerusalem,"),
        (4, 4, "and"),
        (5, 6, "is fallen"),
        (7, 7, "Judah,"),
        (8, 9, "because"),
        (10, 12, "their tongues"),
        (13, 13, "and"),
        (14, 16, "their things"),
        (17, 18, "done"),
        (19, 21, "are against"),
        (22, 24, "the Lord,"),
        (25, 26, "to provoke"),
        (27, 28, "the eyes"),
        (29, 31, "of his glory."),
    ],
    9: [
        (0, 2, "The show"),
        (3, 4, "of"),
        (5, 6, "their eyes"),
        (7, 9, "doth witness against"),
        (10, 13, "them,"),
        (14, 14, "and"),
        (15, 17, "declare thereto"),
        (18, 21, "their sin"),
        (22, 24, "is even as"),
        (25, 26, "Sodom,"),
        (27, 27, "and"),
        (28, 30, "cannot"),
        (31, 32, "they"),
        (33, 33, "hide it."),
        (34, 35, "Wo"),
        (36, 37, "unto"),
        (38, 39, "their souls,"),
        (40, 40, "for"),
        (41, 43, "they have rewarded"),
        (44, 46, "themselves"),
        (47, 49, "with evil!"),
    ],
    10: [
        (0, 1, "Say"),
        (2, 4, "unto the righteous"),
        (5, 7, "it is well"),
        (8, 11, "with them;"),
        (12, 12, "for"),
        (13, 17, "they shall eat"),
        (18, 19, "the fruit"),
        (20, 23, "of their doings."),
    ],
    11: [
        (0, 1, "Wo"),
        (2, 4, "unto the wicked,"),
        (5, 5, "for"),
        (6, 9, "shall perish"),
        (10, 11, "them;"),
        (12, 12, "for"),
        (13, 15, "the reward"),
        (16, 19, "of their hands"),
        (20, 22, "shall be"),
        (23, 23, "upon"),
        (24, 26, "them!"),
    ],
    12: [
        (0, 0, "And"),
        (1, 3, "my people,"),
        (4, 5, "children"),
        (6, 7, "are"),
        (8, 11, "their oppressors,"),
        (12, 12, "and"),
        (13, 14, "rule"),
        (15, 15, "women"),
        (16, 17, "over"),
        (18, 19, "them."),
        (20, 23, "O my people,"),
        (24, 26, "they"),
        (27, 28, "who"),
        (29, 30, "lead"),
        (31, 31, "thee"),
        (32, 34, "cause to err"),
        (35, 35, "thee"),
        (36, 36, "and"),
        (37, 37, "destroy"),
        (38, 39, "the way"),
        (40, 42, "of thy paths."),
    ],
    13: [
        (0, 1, "standeth up"),
        (2, 3, "the Lord"),
        (4, 5, "to plead,"),
        (6, 6, "and"),
        (7, 7, "standeth"),
        (8, 9, "to judge"),
        (10, 11, "the people."),
    ],
    14: [
        (0, 4, "will enter"),
        (5, 6, "the Lord"),
        (7, 9, "into judgment"),
        (10, 11, "together with"),
        (12, 12, "the ancients"),
        (13, 15, "of his people"),
        (16, 16, "and"),
        (17, 18, "his princes;"),
        (19, 19, "for"),
        (20, 23, "ye have eaten up"),
        (24, 25, "the vineyard"),
        (26, 26, "and"),
        (27, 28, "the spoil"),
        (29, 32, "of the poor"),
        (33, 33, "in"),
        (34, 36, "your houses."),
    ],
    15: [
        (0, 5, "What mean ye?"),
        (6, 8, "Ye beat to pieces"),
        (9, 10, "my people,"),
        (11, 11, "and"),
        (12, 12, "grind"),
        (13, 14, "faces of"),
        (15, 16, "the poor,"),
        (17, 20, "saith thereto"),
        (21, 22, "the Lord"),
        (23, 24, "the God"),
        (25, 26, "of Hosts."),
    ],
    16: [
        (0, 4, "Moreover,"),
        (5, 7, "saith"),
        (8, 9, "the Lord:"),
        (10, 10, "Because"),
        (11, 12, "are haughty"),
        (13, 13, "the daughters"),
        (14, 15, "of Zion,"),
        (16, 16, "and"),
        (17, 18, "walk"),
        (19, 19, "and"),
        (20, 21, "stretch"),
        (22, 22, "with"),
        (23, 24, "wanton eyes,"),
        (25, 25, "and"),
        (26, 26, "walking"),
        (27, 27, "and"),
        (28, 28, "mincing"),
        (29, 32, "as they go,"),
        (33, 33, "and"),
        (34, 34, "tinkling"),
        (35, 37, "their feet—"),
    ],
    17: [
        (0, 3, "Therefore"),
        (4, 8, "will smite thereto"),
        (9, 11, "by the Lord"),
        (12, 13, "with a scab"),
        (14, 15, "the crown"),
        (16, 18, "of the head"),
        (19, 20, "of the daughters"),
        (21, 22, "of Zion,"),
        (23, 23, "and"),
        (24, 27, "will discover"),
        (28, 30, "by the Lord"),
        (31, 32, "their"),
        (33, 34, "secret parts."),
    ],
    18: [
        (0, 2, "In that day"),
        (3, 7, "will take away thereto"),
        (8, 10, "by the Lord"),
        (11, 12, "the bravery"),
        (13, 14, "of"),
        (15, 17, "their tinkling ornaments,"),
        (18, 18, "and"),
        (19, 20, "cauls,"),
        (21, 21, "and"),
        (22, 23, "round tires"),
        (24, 26, "like unto"),
        (27, 28, "the moon;"),
    ],
    19: [
        (0, 1, "The chains,"),
        (2, 3, "and the bracelets,"),
        (4, 5, "and the mufflers;"),
    ],
    20: [
        (0, 1, "The bonnets,"),
        (2, 3, "and ornaments of the legs,"),
        (4, 5, "and the headbands,"),
        (6, 6, "and"),
        (7, 8, "the tablets,"),
        (9, 10, "and the earrings;"),
    ],
    21: [
        (0, 1, "The rings,"),
        (2, 2, "also"),
        (3, 3, "and"),
        (4, 7, "nose jewels;"),
    ],
    22: [
        (0, 4, "The changeable suits of apparel,"),
        (5, 5, "and"),
        (6, 7, "the mantles,"),
        (8, 9, "the wimples,"),
        (10, 10, "and"),
        (11, 13, "the crisping pins;"),
    ],
    23: [
        (0, 1, "The glasses,"),
        (2, 2, "and"),
        (3, 5, "the fine linen,"),
        (6, 7, "and the hoods,"),
        (8, 8, "also"),
        (9, 9, "and"),
        (10, 10, "the veils."),
    ],
    24: [
        (0, 0, "And"),
        (1, 5, "shall come"),
        (6, 6, "also,"),
        (7, 9, "instead of"),
        (10, 11, "sweet smell"),
        (12, 16, "there shall be"),
        (17, 19, "the stink;"),
        (20, 20, "and"),
        (21, 23, "instead of"),
        (24, 25, "a girdle,"),
        (26, 30, "shall be"),
        (31, 32, "a rent;"),
        (33, 33, "and"),
        (34, 36, "instead of"),
        (37, 40, "well-set hair,"),
        (41, 43, "baldness;"),
        (44, 44, "and"),
        (45, 47, "instead of"),
        (48, 52, "a stomacher,"),
        (53, 55, "a girding"),
        (56, 59, "of sackcloth;"),
        (60, 62, "burning"),
        (63, 65, "instead of"),
        (66, 66, "beauty."),
    ],
    25: [
        (0, 3, "shall fall"),
        (4, 6, "thy men"),
        (7, 9, "by the sword"),
        (10, 10, "and"),
        (11, 13, "thy mighty men"),
        (14, 16, "in the war."),
    ],
    26: [
        (0, 0, "And"),
        (1, 4, "shall lament"),
        (5, 5, "and"),
        (6, 6, "mourn"),
        (7, 8, "her gates;"),
        (9, 9, "and"),
        (10, 13, "shall be desolate"),
        (14, 15, "she,"),
        (16, 16, "and"),
        (17, 20, "shall sit"),
        (21, 22, "upon"),
        (23, 25, "the ground."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
