"""Hand-curated TAM-phrase gloss overrides for Iaroma 1 — Nephites prosper for two hundred years.

Re-glossed to follow GLOSSING_RULES.md and the no-injected-words rule: each
cell's English maps only to the Samoan words in that cell's span. TAM clusters
atomic (rule 1), subject/agent pronouns absorbed only when their token is IN
the span (rule 2), NP/PP atoms split (rule 3), `mai`-as-"from" (rule 7), no
anaphoric-`ai` "thereto" fillers (rule 1), `mafai ona`/`ina ia`/`ina ua` bound
(rules 13/15), vocative `e` → "O X" (rule 12), directional "forth" dropped
(rule 12a). No pronoun/TAM word is injected into a cell whose span lacks that
token, and no content word repeats across adjacent cells.

To rebuild after editing:
    python3 build_overrides_jarom1.py
"""
from __future__ import annotations
import json, sys
from pathlib import Path

BOOK_ID = "jarom"
CHAPTER_NUM = 1
ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"

VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 2, "Now behold,"),
        (3, 4, "I,"),
        (5, 6, "Jarom,"),
        (7, 9, "I write"),
        (10, 13, "a few small words"),
        (14, 16, "according to"),
        (17, 18, "the commandment"),
        (19, 21, "of my father,"),
        (22, 23, "Enos,"),
        (24, 25, "that"),
        (26, 27, "may"),
        (28, 28, "be kept"),
        (29, 31, "our genealogy."),
    ],
    2: [
        (0, 0, "And"),
        (1, 2, "because of"),
        (3, 4, "the smallness"),
        (5, 7, "of these plates,"),
        (8, 8, "and"),
        (9, 9, "because"),
        (10, 11, "are written"),
        (12, 13, "these things"),
        (14, 16, "for the intent"),
        (17, 19, "of the welfare"),
        (20, 23, "of our brethren"),
        (24, 26, "the Lamanites,"),
        (27, 30, "wherefore,"),
        (31, 34, "it must needs"),
        (35, 36, "I write"),
        (37, 37, "only"),
        (38, 41, "a few small things;"),
        (42, 42, "but"),
        (43, 48, "I shall not write"),
        (49, 49, "the things"),
        (50, 52, "concerning"),
        (53, 54, "my prophesyings,"),
        (55, 56, "nor"),
        (57, 58, "my revelations."),
        (59, 60, "For"),
        (61, 62, "what"),
        (63, 65, "other thing"),
        (66, 68, "greater"),
        (69, 71, "could"),
        (72, 73, "I write"),
        (74, 75, "than"),
        (76, 76, "the things"),
        (77, 78, "written"),
        (79, 81, "by my fathers?"),
        (82, 82, "For"),
        (83, 84, "have they"),
        (85, 88, "not revealed"),
        (89, 89, "indeed"),
        (90, 91, "the plan"),
        (92, 94, "of salvation?"),
        (95, 98, "I say"),
        (99, 101, "unto you,"),
        (102, 102, "Yea;"),
        (103, 103, "and"),
        (104, 106, "this is enough"),
        (107, 109, "for me."),
    ],
    3: [
        (0, 0, "Behold,"),
        (1, 3, "many things"),
        (4, 6, "must"),
        (7, 7, "be done"),
        (8, 10, "among"),
        (11, 12, "this people,"),
        (13, 14, "because of"),
        (15, 16, "the hardness"),
        (17, 20, "of their hearts,"),
        (21, 23, "and the deafness"),
        (24, 27, "of their ears,"),
        (28, 30, "and the blindness"),
        (31, 34, "of their minds,"),
        (35, 37, "and the stiffness"),
        (38, 41, "of their necks;"),
        (42, 45, "nevertheless,"),
        (46, 47, "is"),
        (48, 50, "exceedingly merciful"),
        (51, 52, "still"),
        (53, 54, "God"),
        (55, 58, "unto them,"),
        (59, 59, "and"),
        (60, 63, "hath not yet swept off"),
        (64, 65, "them"),
        (66, 68, "from off"),
        (69, 70, "the land."),
    ],
    4: [
        (0, 0, "And"),
        (1, 2, "many"),
        (3, 5, "there are"),
        (6, 8, "among"),
        (9, 10, "us"),
        (11, 12, "who"),
        (13, 14, "have"),
        (15, 15, "revelations"),
        (16, 17, "many,"),
        (18, 18, "for"),
        (19, 23, "they are not stiffnecked"),
        (24, 24, "all."),
        (25, 25, "And"),
        (26, 28, "as many"),
        (29, 30, "as"),
        (31, 34, "are not stiffnecked"),
        (35, 35, "and"),
        (36, 37, "have faith,"),
        (38, 39, "had communion"),
        (40, 40, "with"),
        (41, 43, "the Holy Spirit,"),
        (44, 45, "which"),
        (46, 49, "maketh manifest"),
        (50, 50, "things"),
        (51, 53, "unto the children"),
        (54, 55, "of men,"),
        (56, 58, "according to"),
        (59, 61, "their faith."),
    ],
    5: [
        (0, 2, "And now,"),
        (3, 3, "behold,"),
        (4, 6, "two hundred"),
        (7, 7, "years"),
        (8, 10, "had passed,"),
        (11, 11, "and"),
        (12, 14, "had waxed strong"),
        (15, 16, "the people"),
        (17, 18, "of Nephi"),
        (19, 21, "in the land."),
        (22, 24, "they observed"),
        (25, 26, "to keep"),
        (27, 28, "the law"),
        (29, 30, "of Moses"),
        (31, 34, "and the sabbath day"),
        (35, 36, "holy"),
        (37, 39, "unto the Lord."),
        (40, 40, "And"),
        (41, 44, "they profaned not;"),
        (45, 45, "neither"),
        (46, 48, "did they blaspheme."),
        (49, 49, "And"),
        (50, 53, "were exceedingly strict"),
        (54, 54, "the laws"),
        (55, 57, "of the land."),
    ],
    6: [
        (0, 0, "And"),
        (1, 2, "were scattered"),
        (3, 4, "they"),
        (5, 7, "upon"),
        (8, 10, "much of"),
        (11, 12, "the face of the land,"),
        (13, 13, "and"),
        (14, 16, "the Lamanites also."),
        (17, 17, "And"),
        (18, 20, "were greater"),
        (21, 23, "their numbers,"),
        (24, 25, "than"),
        (26, 27, "those"),
        (28, 30, "of the Nephites;"),
        (31, 31, "and"),
        (32, 34, "they loved"),
        (35, 38, "murder"),
        (39, 39, "and"),
        (40, 40, "would drink"),
        (41, 42, "the blood"),
        (43, 44, "of beasts."),
    ],
    7: [
        (0, 3, "And it came to pass"),
        (4, 6, "they came"),
        (7, 11, "many times"),
        (12, 14, "to battle against"),
        (15, 18, "us,"),
        (19, 21, "the Nephites."),
        (22, 22, "But"),
        (23, 26, "our kings"),
        (27, 27, "and"),
        (28, 30, "our leaders"),
        (31, 34, "were mighty men"),
        (35, 37, "in the faith"),
        (38, 40, "of the Lord;"),
        (41, 41, "and"),
        (42, 44, "they taught"),
        (45, 46, "the people"),
        (47, 48, "the ways"),
        (49, 51, "of the Lord;"),
        (52, 55, "wherefore,"),
        (56, 60, "we did withstand"),
        (61, 63, "the Lamanites"),
        (64, 64, "and"),
        (65, 66, "swept away"),
        (67, 68, "them"),
        (69, 69, "from"),
        (70, 72, "our lands,"),
        (73, 73, "and"),
        (74, 78, "we began to fortify"),
        (79, 81, "our cities,"),
        (82, 83, "or"),
        (84, 87, "whatsoever place"),
        (88, 91, "of our inheritance."),
    ],
    8: [
        (0, 0, "And"),
        (1, 4, "we multiplied"),
        (5, 6, "exceedingly,"),
        (7, 7, "and"),
        (8, 9, "spread"),
        (10, 12, "upon"),
        (13, 14, "the land,"),
        (15, 15, "and"),
        (16, 18, "became exceedingly rich"),
        (19, 21, "in gold,"),
        (22, 24, "and in silver,"),
        (25, 26, "and"),
        (27, 28, "precious things,"),
        (29, 29, "and"),
        (30, 31, "fine workmanship"),
        (32, 33, "wrought"),
        (34, 35, "of wood,"),
        (36, 37, "in buildings,"),
        (38, 40, "and in machinery,"),
        (41, 43, "and in iron"),
        (44, 47, "and copper also,"),
        (48, 50, "and brass"),
        (51, 53, "and steel,"),
        (54, 54, "and"),
        (55, 56, "made"),
        (57, 58, "all manner of"),
        (59, 60, "tools"),
        (61, 62, "of every kind"),
        (63, 65, "to till"),
        (66, 67, "the ground,"),
        (68, 68, "and"),
        (69, 69, "weapons"),
        (70, 71, "of war—"),
        (72, 72, "yea,"),
        (73, 75, "the arrow"),
        (76, 77, "sharp-pointed,"),
        (78, 80, "and the quiver,"),
        (81, 83, "and the dart,"),
        (84, 86, "and the javelin,"),
        (87, 89, "and all preparations"),
        (90, 91, "for war."),
    ],
    9: [
        (0, 0, "And"),
        (1, 3, "because thus"),
        (4, 6, "we were prepared"),
        (7, 8, "to meet"),
        (9, 10, "the Lamanites,"),
        (11, 12, "wherefore"),
        (13, 17, "they did not prevail"),
        (18, 21, "against us."),
        (22, 22, "But"),
        (23, 24, "was verified"),
        (25, 26, "the word"),
        (27, 29, "of the Lord,"),
        (30, 34, "which he spake"),
        (35, 38, "unto our fathers,"),
        (39, 40, "saying:"),
        (41, 44, "Inasmuch as"),
        (45, 47, "ye keep"),
        (48, 50, "my commandments,"),
        (51, 55, "ye shall prosper"),
        (56, 58, "in the land."),
    ],
    10: [
        (0, 3, "And it came to pass"),
        (4, 4, "did threaten"),
        (5, 6, "the prophets"),
        (7, 9, "of the Lord"),
        (10, 11, "the people"),
        (12, 13, "of Nephi,"),
        (14, 16, "according to"),
        (17, 18, "the word"),
        (19, 21, "of God,"),
        (22, 23, "that"),
        (24, 24, "if"),
        (25, 28, "they did not keep"),
        (29, 29, "the commandments,"),
        (30, 30, "but"),
        (31, 32, "should fall"),
        (33, 35, "into transgression,"),
        (36, 39, "should be destroyed"),
        (40, 41, "they"),
        (42, 44, "from off"),
        (45, 46, "the face of the land."),
    ],
    11: [
        (0, 3, "Wherefore,"),
        (4, 6, "did labor"),
        (7, 9, "diligently"),
        (10, 10, "the prophets,"),
        (11, 12, "and priests,"),
        (13, 14, "and teachers,"),
        (15, 17, "exhorting"),
        (18, 19, "the people"),
        (20, 23, "with all long-suffering"),
        (24, 25, "to diligence;"),
        (26, 26, "and"),
        (27, 29, "they taught"),
        (30, 31, "the law"),
        (32, 33, "of Moses,"),
        (34, 36, "and the intent"),
        (37, 40, "for which was given;"),
        (41, 41, "and"),
        (42, 43, "persuading"),
        (44, 47, "them"),
        (48, 48, "that"),
        (49, 51, "they should look"),
        (52, 53, "forward"),
        (54, 56, "unto the Messiah,"),
        (57, 57, "and"),
        (58, 58, "believe"),
        (59, 65, "he would come"),
        (66, 67, "as though"),
        (68, 70, "already"),
        (71, 74, "he had come."),
        (75, 77, "And thus"),
        (78, 79, "the manner"),
        (80, 83, "did they teach"),
        (84, 85, "them."),
    ],
    12: [
        (0, 3, "And it came to pass"),
        (4, 6, "by the doing"),
        (7, 9, "of this thing"),
        (10, 13, "they kept"),
        (14, 15, "them"),
        (16, 18, "from being destroyed"),
        (19, 21, "upon"),
        (22, 23, "the face of the land,"),
        (24, 24, "for"),
        (25, 27, "they did prick"),
        (28, 30, "their hearts"),
        (31, 33, "with the word,"),
        (34, 34, "and"),
        (35, 36, "continually stirring up"),
        (37, 38, "them"),
        (39, 40, "to repentance."),
    ],
    13: [
        (0, 3, "And it came to pass"),
        (4, 5, "had passed"),
        (6, 8, "two hundred"),
        (9, 10, "and thirty"),
        (11, 13, "and eight"),
        (14, 15, "years—"),
        (16, 19, "according to"),
        (20, 20, "the ways"),
        (21, 22, "of wars,"),
        (23, 24, "and contentions,"),
        (25, 26, "and dissensions,"),
        (27, 30, "for the space of"),
        (31, 34, "much of the time."),
    ],
    14: [
        (0, 0, "And"),
        (1, 2, "I,"),
        (3, 4, "Jarom,"),
        (5, 7, "I do not"),
        (8, 9, "write again"),
        (10, 12, "more things,"),
        (13, 13, "for"),
        (14, 15, "are small"),
        (16, 16, "the plates."),
        (17, 18, "But behold,"),
        (19, 21, "O my brethren,"),
        (22, 24, "can"),
        (25, 26, "ye look"),
        (27, 29, "at the other plates"),
        (30, 31, "of Nephi;"),
        (32, 33, "for behold,"),
        (34, 35, "are engraven"),
        (36, 40, "upon them"),
        (41, 41, "the records"),
        (42, 45, "of our wars,"),
        (46, 48, "according to"),
        (49, 49, "the writings"),
        (50, 51, "of kings,"),
        (52, 53, "or"),
        (54, 54, "those"),
        (55, 57, "they caused"),
        (58, 59, "to be written."),
    ],
    15: [
        (0, 0, "And"),
        (1, 4, "I deliver"),
        (5, 6, "these plates"),
        (7, 8, "into the hands"),
        (9, 11, "of my son,"),
        (12, 13, "Omni,"),
        (14, 15, "that"),
        (16, 16, "be kept"),
        (17, 18, "they"),
        (19, 21, "according to"),
        (22, 22, "the commandments"),
        (23, 25, "of my fathers."),
    ],
}


def build_words(source_words, spec):
    next_expected = 0
    for s, e, _ in spec:
        if s != next_expected: raise ValueError(f"gap at {s} expected {next_expected}")
        if e < s or e >= len(source_words): raise ValueError(f"bad range {s}..{e} src len {len(source_words)}")
        next_expected = e + 1
    if next_expected != len(source_words): raise ValueError(f"spec ends at {next_expected} src has {len(source_words)}")
    out = []
    for s, e, g in spec:
        for i in range(s, e): out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[e]["sm"], "en": g})
    return out


def main():
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)
    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    n = 0
    for v in chapter["verses"]:
        spec = VERSE_SPECS.get(v["num"])
        if not spec: continue
        try:
            existing["verses"][f"{BOOK_ID}|{CHAPTER_NUM}|{v['num']}"] = build_words(v["words"], spec)
            n += 1
        except ValueError as exc:
            print(f"v{v['num']}: {exc}", file=sys.stderr); sys.exit(1)
    OVERRIDES_PATH.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {n} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
