"""
Hand-curated TAM-phrase gloss overrides for Alema (Alma) 8 — Alma preaches
in Melek and is rejected at Ammonihah; an angel sends him back; he meets
Amulek, who receives him.

Run AFTER build_phrase_overrides.py so this chapter's hand-curation
overlays the auto-glossed entries.

Follows GLOSSING_RULES.md and the no-injected-words rule: TAM clusters
atomic (rule 1), subject `o ia` / agent `e ia` absorbed into the verb
cluster, never split as a bare "he" (rule 2), NP/PP atoms split (rule 3),
`mai`-as-"from" (rule 7), idioms kept whole (rule 9), `mafai ona`/`ina ia`/
`e tatau ona` bound (rules 13/15). Em-dash token `faapea—Ia` (v29) split in
the source per rule 11 — so v29 = 73 tokens.

    python3 build_overrides_alma8.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BOOK_ID = "alma"
CHAPTER_NUM = 8

ROOT = Path(__file__).resolve().parent.parent
BOOKS_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_books.json"
OVERRIDES_PATH = ROOT / "O le Tusi a Mamona Interlinear" / "Resources" / "bom_overrides.json"


VERSE_SPECS: dict[int, list[tuple[int, int, str]]] = {
    1: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "it came to pass that"),
        (6, 8, "returned"),
        (9, 9, "Alma"),
        (10, 13, "from the land of"),
        (14, 14, "Gideon,"),
        (15, 18, "after having"),
        (19, 21, "taught"),
        (22, 24, "the people of"),
        (25, 25, "Gideon"),
        (26, 29, "many things"),
        (30, 33, "which cannot"),
        (34, 34, "be written,"),
        (35, 38, "having"),
        (39, 40, "established"),
        (41, 43, "the order of"),
        (44, 45, "the church,"),
        (46, 48, "according as"),
        (49, 51, "he had done"),
        (52, 52, "before"),
        (53, 56, "in the land of"),
        (57, 57, "Zarahemla,"),
        (58, 58, "yea,"),
        (59, 63, "he returned"),
        (64, 67, "to his own house"),
        (68, 69, "at Zarahemla"),
        (70, 72, "to rest"),
        (73, 75, "himself"),
        (76, 77, "from the labors"),
        (78, 80, "which he had performed."),
    ],
    2: [
        (0, 0, "And"),
        (1, 3, "thus"),
        (4, 4, "ended"),
        (5, 8, "the ninth"),
        (9, 10, "year"),
        (11, 13, "of the reign"),
        (14, 15, "of the judges"),
        (16, 19, "over the people of"),
        (20, 20, "Nephi."),
    ],
    3: [
        (0, 2, "And it came to pass"),
        (3, 5, "in the commencement"),
        (6, 9, "of the tenth"),
        (10, 11, "year"),
        (12, 14, "of the reign"),
        (15, 16, "of the judges"),
        (17, 19, "over"),
        (20, 22, "the people of"),
        (23, 23, "Nephi,"),
        (24, 28, "departed"),
        (29, 29, "Alma"),
        (30, 31, "from thence"),
        (32, 34, "and took"),
        (35, 36, "his journey"),
        (37, 40, "over into the land of"),
        (41, 41, "Melek,"),
        (42, 47, "on the west of"),
        (48, 49, "the river"),
        (50, 51, "of Sidon,"),
        (52, 56, "on the west"),
        (57, 59, "by"),
        (60, 61, "the borders of"),
        (62, 63, "the wilderness."),
    ],
    4: [
        (0, 0, "And"),
        (1, 3, "began to"),
        (4, 6, "he teach"),
        (7, 8, "the people"),
        (9, 12, "in the land of"),
        (13, 13, "Melek"),
        (14, 16, "according to"),
        (17, 19, "the holy order"),
        (20, 22, "of God,"),
        (23, 23, "by which"),
        (24, 29, "he had been called;"),
        (30, 30, "and"),
        (31, 33, "began to"),
        (34, 36, "he teach"),
        (37, 37, "the people"),
        (38, 42, "throughout all the land of"),
        (43, 43, "Melek."),
    ],
    5: [
        (0, 3, "And it came to pass that"),
        (4, 5, "came"),
        (6, 6, "the people"),
        (7, 9, "to him"),
        (10, 13, "throughout all the borders of"),
        (14, 15, "the land"),
        (16, 20, "which was by the side of"),
        (21, 22, "the wilderness."),
        (23, 23, "And"),
        (24, 25, "were baptized"),
        (26, 27, "they"),
        (28, 32, "throughout all the land;"),
    ],
    6: [
        (0, 4, "having finished"),
        (5, 6, "the work"),
        (7, 8, "in Melek"),
        (9, 14, "he departed"),
        (15, 16, "thence,"),
        (17, 19, "and traveled"),
        (20, 22, "a journey"),
        (23, 25, "of three days"),
        (26, 31, "on the north of"),
        (32, 34, "the land of"),
        (35, 35, "Melek;"),
        (36, 36, "and"),
        (37, 41, "he came"),
        (42, 44, "to a city"),
        (45, 47, "which was called"),
        (48, 48, "Ammonihah."),
    ],
    7: [
        (0, 1, "Now"),
        (2, 3, "it was"),
        (4, 7, "the custom"),
        (8, 11, "of the people of Nephi"),
        (12, 14, "to call"),
        (15, 17, "their lands,"),
        (18, 21, "and their cities,"),
        (22, 25, "and their villages,"),
        (26, 26, "yea,"),
        (27, 29, "even"),
        (30, 34, "all their small villages,"),
        (35, 37, "after the name of"),
        (38, 39, "him"),
        (40, 41, "who"),
        (42, 44, "first possessed"),
        (45, 46, "them;"),
        (47, 47, "and"),
        (48, 51, "thus it was"),
        (52, 54, "with"),
        (55, 57, "the land of"),
        (58, 58, "Ammonihah."),
    ],
    8: [
        (0, 3, "And it came to pass that"),
        (4, 6, "when had come"),
        (7, 7, "Alma"),
        (8, 11, "to the city of"),
        (12, 12, "Ammonihah"),
        (13, 15, "began to"),
        (16, 18, "he preach"),
        (19, 20, "the word"),
        (21, 23, "of God"),
        (24, 27, "unto them."),
    ],
    9: [
        (0, 1, "Now"),
        (2, 4, "great was"),
        (5, 6, "the hold of"),
        (7, 7, "Satan"),
        (8, 10, "upon the hearts of"),
        (11, 12, "the people of"),
        (13, 15, "the city of"),
        (16, 16, "Ammonihah;"),
        (17, 18, "therefore"),
        (19, 24, "they would not hearken"),
        (25, 27, "unto the words of"),
        (28, 28, "Alma."),
    ],
    10: [
        (0, 3, "Nevertheless"),
        (4, 6, "labored much"),
        (7, 7, "Alma"),
        (8, 10, "in the spirit,"),
        (11, 12, "wrestling"),
        (13, 15, "with God"),
        (16, 21, "in mighty prayer,"),
        (22, 24, "that he would"),
        (25, 26, "pour out"),
        (27, 28, "his Spirit"),
        (29, 31, "upon"),
        (32, 32, "the people"),
        (33, 34, "who"),
        (35, 36, "were in"),
        (37, 38, "the city;"),
        (39, 39, "and"),
        (40, 41, "that he would"),
        (42, 44, "also grant"),
        (45, 47, "that he might"),
        (48, 49, "baptize"),
        (50, 51, "them"),
        (52, 54, "unto repentance."),
    ],
    11: [
        (0, 3, "Nevertheless,"),
        (4, 6, "they hardened"),
        (7, 9, "their hearts,"),
        (10, 12, "saying"),
        (13, 15, "unto him:"),
        (16, 16, "Behold,"),
        (17, 19, "we know"),
        (20, 21, "that thou art"),
        (22, 23, "Alma;"),
        (24, 24, "and"),
        (25, 27, "we know"),
        (28, 29, "that thou art"),
        (30, 33, "high priest"),
        (34, 36, "over the church"),
        (37, 40, "which thou hast established"),
        (41, 46, "in many parts of"),
        (47, 48, "the land,"),
        (49, 52, "according to"),
        (53, 54, "your tradition;"),
        (55, 55, "and"),
        (56, 60, "we are not"),
        (61, 64, "any of"),
        (65, 66, "thy church,"),
        (67, 67, "and"),
        (68, 72, "we do not believe"),
        (73, 77, "in such foolish traditions."),
    ],
    12: [
        (0, 0, "And"),
        (1, 2, "now"),
        (3, 5, "we know"),
        (6, 7, "because"),
        (8, 9, "we"),
        (10, 14, "are not any of"),
        (15, 17, "thy church"),
        (18, 20, "we know"),
        (21, 24, "thou hast no power"),
        (25, 29, "over us;"),
        (30, 30, "and"),
        (31, 34, "thou hast delivered up"),
        (35, 36, "the judgment-seat"),
        (37, 38, "unto Nephihah;"),
        (39, 40, "therefore"),
        (41, 44, "thou art not"),
        (45, 48, "the chief judge"),
        (49, 53, "over us."),
    ],
    13: [
        (0, 1, "Now"),
        (2, 7, "when had said"),
        (8, 9, "the people"),
        (10, 11, "this,"),
        (12, 15, "and withstood"),
        (16, 18, "all his words,"),
        (19, 21, "and reviled"),
        (22, 24, "him,"),
        (25, 26, "and spit"),
        (27, 29, "upon him,"),
        (30, 31, "and caused"),
        (32, 36, "that he should be cast out"),
        (37, 40, "of their city,"),
        (41, 45, "he departed"),
        (46, 47, "thence"),
        (48, 50, "and took"),
        (51, 52, "his journey"),
        (53, 54, "towards"),
        (55, 56, "the city"),
        (57, 59, "which was called"),
        (60, 60, "Aaron."),
    ],
    14: [
        (0, 3, "And it came to pass that"),
        (4, 8, "as he was journeying"),
        (9, 9, "thither,"),
        (10, 12, "being weighed down"),
        (13, 15, "with the weight of"),
        (16, 17, "sorrow,"),
        (18, 21, "wading through"),
        (22, 24, "much tribulation"),
        (25, 28, "and anguish of"),
        (29, 30, "soul,"),
        (31, 32, "because of"),
        (33, 35, "the wickedness of"),
        (36, 36, "the people"),
        (37, 40, "who were in"),
        (41, 43, "the city of"),
        (44, 44, "Ammonihah,"),
        (45, 47, "it came to pass"),
        (48, 49, "while was weighed down"),
        (50, 50, "Alma"),
        (51, 54, "with the weight of"),
        (55, 56, "sorrow,"),
        (57, 57, "behold,"),
        (58, 60, "appeared"),
        (61, 63, "an angel of"),
        (64, 65, "the Lord"),
        (66, 68, "unto him,"),
        (69, 71, "saying:"),
    ],
    15: [
        (0, 2, "Blessed art thou,"),
        (3, 3, "Alma;"),
        (4, 5, "therefore,"),
        (6, 10, "lift up"),
        (11, 12, "thy head"),
        (13, 14, "and rejoice,"),
        (15, 15, "for"),
        (16, 19, "thou hast"),
        (20, 22, "great cause"),
        (23, 26, "to rejoice;"),
        (27, 27, "for"),
        (28, 30, "thou hast been faithful"),
        (31, 34, "in keeping"),
        (35, 36, "the commandments of"),
        (37, 38, "God"),
        (39, 43, "from the time"),
        (44, 47, "which thou receivedst"),
        (48, 50, "thy first message"),
        (51, 54, "from him."),
        (55, 55, "Behold,"),
        (56, 57, "I am"),
        (58, 59, "he"),
        (60, 61, "that"),
        (62, 63, "delivered"),
        (64, 65, "that message"),
        (66, 68, "unto thee."),
    ],
    16: [
        (0, 0, "And"),
        (1, 1, "behold,"),
        (2, 5, "I am sent"),
        (6, 7, "to command"),
        (8, 8, "thee,"),
        (9, 13, "that thou return"),
        (14, 17, "to the city of"),
        (18, 18, "Ammonihah,"),
        (19, 22, "and preach again"),
        (23, 24, "unto the people"),
        (25, 27, "of the city;"),
        (28, 28, "yea,"),
        (29, 30, "preach"),
        (31, 34, "unto them."),
        (35, 35, "Yea,"),
        (36, 37, "say"),
        (38, 41, "unto them,"),
        (42, 43, "except"),
        (44, 46, "they repent,"),
        (47, 50, "will destroy"),
        (51, 52, "them"),
        (53, 57, "the Lord God."),
    ],
    17: [
        (0, 1, "For behold,"),
        (2, 5, "they do study"),
        (6, 9, "at this time"),
        (10, 12, "that may"),
        (13, 14, "they destroy"),
        (15, 17, "the liberty of"),
        (18, 19, "thy people,"),
        (20, 20, "(for"),
        (21, 26, "thus saith"),
        (27, 29, "the Lord)"),
        (30, 32, "a thing which"),
        (33, 37, "is contrary to"),
        (38, 38, "the statutes,"),
        (39, 40, "and judgments,"),
        (41, 42, "and commandments,"),
        (43, 47, "which he has given"),
        (48, 50, "unto his people."),
    ],
    18: [
        (0, 1, "Now"),
        (2, 4, "it came to pass that"),
        (5, 8, "after had received"),
        (9, 10, "Alma"),
        (11, 12, "his message"),
        (13, 16, "from the angel of"),
        (17, 18, "the Lord"),
        (19, 21, "speedily"),
        (22, 25, "he returned"),
        (26, 29, "to the land of"),
        (30, 30, "Ammonihah."),
        (31, 31, "And"),
        (32, 35, "he entered"),
        (36, 38, "the city"),
        (39, 42, "by another way,"),
        (43, 43, "yea,"),
        (44, 47, "by the way which"),
        (48, 54, "is on the south"),
        (55, 58, "of the city of"),
        (59, 59, "Ammonihah."),
    ],
    19: [
        (0, 0, "And"),
        (1, 5, "as he entered"),
        (6, 8, "the city,"),
        (9, 13, "he was an hungered,"),
        (14, 14, "and"),
        (15, 18, "he said"),
        (19, 21, "to a man:"),
        (22, 26, "Will ye give"),
        (27, 28, "something to eat"),
        (29, 32, "to an humble servant"),
        (33, 35, "of God?"),
    ],
    20: [
        (0, 0, "And"),
        (1, 3, "said"),
        (4, 5, "the man"),
        (6, 8, "unto him:"),
        (9, 10, "I am"),
        (11, 14, "a Nephite,"),
        (15, 15, "and"),
        (16, 18, "I know"),
        (19, 20, "that thou art"),
        (21, 24, "a holy prophet"),
        (25, 27, "of God,"),
        (28, 30, "for thou art"),
        (31, 34, "the man"),
        (35, 36, "of whom"),
        (37, 40, "said"),
        (41, 42, "an angel"),
        (43, 46, "in a vision:"),
        (47, 49, "Thou shalt receive"),
        (50, 51, "him."),
        (52, 53, "Therefore,"),
        (54, 56, "go"),
        (57, 58, "with me"),
        (59, 61, "into my house"),
        (62, 62, "and"),
        (63, 67, "I will impart"),
        (68, 70, "unto thee"),
        (71, 73, "of my food;"),
        (74, 74, "and"),
        (75, 77, "I know"),
        (78, 81, "that wilt be"),
        (82, 82, "thou"),
        (83, 84, "a blessing"),
        (85, 87, "unto me"),
        (88, 90, "and my house."),
    ],
    21: [
        (0, 3, "And it came to pass that"),
        (4, 4, "received"),
        (5, 6, "him"),
        (7, 9, "the man"),
        (10, 12, "into his house;"),
        (13, 13, "and"),
        (14, 17, "the name of"),
        (18, 19, "this man"),
        (20, 21, "was Amulek;"),
        (22, 22, "and"),
        (23, 25, "he brought forth"),
        (26, 26, "bread"),
        (27, 30, "and meat"),
        (31, 33, "and set"),
        (34, 36, "before"),
        (37, 37, "Alma."),
    ],
    22: [
        (0, 3, "And it came to pass that"),
        (4, 4, "ate"),
        (5, 6, "Alma"),
        (7, 7, "bread"),
        (8, 10, "and was filled;"),
        (11, 11, "and"),
        (12, 16, "he blessed"),
        (17, 18, "Amulek"),
        (19, 21, "and his house,"),
        (22, 22, "and"),
        (23, 25, "he gave"),
        (26, 27, "thanks"),
        (28, 30, "unto God."),
    ],
    23: [
        (0, 0, "And"),
        (1, 4, "after had"),
        (5, 7, "he eaten"),
        (8, 10, "and was filled"),
        (11, 14, "he said"),
        (15, 16, "unto Amulek:"),
        (17, 18, "I am"),
        (19, 20, "Alma,"),
        (21, 21, "and"),
        (22, 23, "am"),
        (24, 27, "the high priest"),
        (28, 30, "over"),
        (31, 32, "the church"),
        (33, 35, "of God"),
        (36, 39, "throughout the land."),
    ],
    24: [
        (0, 0, "And"),
        (1, 1, "behold,"),
        (2, 4, "I have been called"),
        (5, 7, "to preach"),
        (8, 9, "the word"),
        (10, 12, "of God"),
        (13, 15, "among"),
        (16, 18, "all this people,"),
        (19, 21, "according to"),
        (22, 24, "the spirit of"),
        (25, 25, "revelation"),
        (26, 27, "and prophecy;"),
        (28, 28, "and"),
        (29, 32, "I was in"),
        (33, 36, "this land"),
        (37, 37, "but"),
        (38, 41, "they would not receive"),
        (42, 42, "me,"),
        (43, 43, "but"),
        (44, 47, "they cast out"),
        (48, 48, "me"),
        (49, 49, "and"),
        (50, 52, "I was about to"),
        (53, 55, "turn my back"),
        (56, 58, "upon this land"),
        (59, 60, "forever."),
    ],
    25: [
        (0, 0, "But"),
        (1, 1, "behold,"),
        (2, 4, "I have been commanded"),
        (5, 9, "that I should turn again"),
        (10, 12, "and prophesy"),
        (13, 15, "unto this people,"),
        (16, 16, "yea,"),
        (17, 18, "and to testify"),
        (19, 20, "against"),
        (21, 24, "them"),
        (25, 27, "concerning"),
        (28, 29, "their iniquities."),
    ],
    26: [
        (0, 0, "And"),
        (1, 2, "now,"),
        (3, 3, "Amulek,"),
        (4, 4, "because"),
        (5, 7, "thou hast fed"),
        (8, 10, "me"),
        (11, 13, "and thou hast taken"),
        (14, 14, "me"),
        (15, 19, "into thy house,"),
        (20, 21, "art blessed"),
        (22, 22, "thou;"),
        (23, 23, "for"),
        (24, 26, "I was an hungered,"),
        (27, 27, "for"),
        (28, 30, "I had fasted"),
        (31, 34, "many days."),
    ],
    27: [
        (0, 0, "And"),
        (1, 3, "many days"),
        (4, 6, "tarried"),
        (7, 7, "Alma"),
        (8, 10, "with Amulek"),
        (11, 14, "before began to"),
        (15, 17, "he preach"),
        (18, 19, "unto the people."),
    ],
    28: [
        (0, 3, "And it came to pass that"),
        (4, 4, "did increase"),
        (5, 6, "the wickedness"),
        (7, 8, "of the people."),
    ],
    29: [
        (0, 3, "And came"),
        (4, 5, "the word"),
        (6, 7, "to Alma,"),
        (8, 10, "saying:"),
        (11, 12, "Go;"),
        (13, 16, "and also say"),
        (17, 19, "unto my servant"),
        (20, 21, "Amulek,"),
        (22, 23, "go forth"),
        (24, 26, "and prophesy"),
        (27, 29, "unto this people,"),
        (30, 31, "saying—"),
        (32, 34, "Repent ye,"),
        (35, 35, "for"),
        (36, 40, "thus saith"),
        (41, 43, "the Lord,"),
        (44, 45, "except"),
        (46, 48, "ye repent,"),
        (49, 54, "I will visit"),
        (55, 57, "this people"),
        (58, 60, "in mine anger;"),
        (61, 61, "yea,"),
        (62, 62, "and"),
        (63, 69, "I will not turn away"),
        (70, 72, "my fierce anger."),
    ],
    30: [
        (0, 0, "And"),
        (1, 3, "went forth"),
        (4, 4, "Alma,"),
        (5, 7, "and Amulek,"),
        (8, 10, "among"),
        (11, 11, "the people,"),
        (12, 14, "to declare"),
        (15, 16, "the words of"),
        (17, 18, "God"),
        (19, 22, "unto them;"),
        (23, 23, "and"),
        (24, 25, "were filled"),
        (26, 27, "they"),
        (28, 31, "with the Holy Ghost."),
    ],
    31: [
        (0, 0, "And"),
        (1, 5, "they had"),
        (6, 7, "power"),
        (8, 10, "given"),
        (11, 14, "unto them,"),
        (15, 17, "insomuch that"),
        (18, 20, "could not"),
        (21, 21, "be confined"),
        (22, 24, "they"),
        (25, 26, "in dungeons;"),
        (27, 30, "neither was it possible"),
        (31, 33, "that any man"),
        (34, 35, "could slay"),
        (36, 39, "them;"),
        (40, 43, "nevertheless"),
        (44, 47, "they did not exercise"),
        (48, 50, "their power"),
        (51, 54, "until"),
        (55, 57, "they were bound"),
        (58, 59, "in bands"),
        (60, 61, "and cast"),
        (62, 64, "into"),
        (65, 66, "prison."),
        (67, 68, "Now,"),
        (69, 70, "was done"),
        (71, 72, "this"),
        (73, 76, "that might"),
        (77, 79, "show forth"),
        (80, 82, "the Lord"),
        (83, 84, "his power"),
        (85, 87, "through"),
        (88, 91, "them."),
    ],
    32: [
        (0, 3, "And it came to pass that"),
        (4, 6, "they went forth,"),
        (7, 9, "and began to"),
        (10, 10, "preach"),
        (11, 13, "and to prophesy"),
        (14, 15, "unto the people,"),
        (16, 19, "according to"),
        (20, 21, "the spirit"),
        (22, 24, "and power"),
        (25, 27, "which had given"),
        (28, 30, "the Lord"),
        (31, 34, "unto them."),
    ],
}


def build_words(source_words: list[dict], spec: list[tuple[int, int, str]]) -> list[dict]:
    next_expected = 0
    for start, end, _ in spec:
        if start != next_expected:
            raise ValueError(f"gap or overlap at index {start} (expected {next_expected})")
        if end < start or end >= len(source_words):
            raise ValueError(f"bad range {start}..{end} (source len {len(source_words)})")
        next_expected = end + 1
    if next_expected != len(source_words):
        raise ValueError(
            f"spec ends at {next_expected} but source has {len(source_words)} words"
        )

    out: list[dict] = []
    for start, end, gloss in spec:
        for i in range(start, end):
            out.append({"sm": source_words[i]["sm"], "en": "·"})
        out.append({"sm": source_words[end]["sm"], "en": gloss})
    return out


def main() -> None:
    books = json.loads(BOOKS_PATH.read_text(encoding="utf-8"))
    book = next(b for b in books["books"] if b["id"] == BOOK_ID)
    chapter = next(c for c in book["chapters"] if c["num"] == CHAPTER_NUM)

    existing = {"version": 1, "verses": {}}
    if OVERRIDES_PATH.exists():
        existing = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))

    written = 0
    for verse in chapter["verses"]:
        spec = VERSE_SPECS.get(verse["num"])
        if not spec:
            continue
        try:
            new_words = build_words(verse["words"], spec)
        except ValueError as exc:
            print(f"v{verse['num']}: {exc}", file=sys.stderr)
            sys.exit(1)
        key = f"{BOOK_ID}|{CHAPTER_NUM}|{verse['num']}"
        existing["verses"][key] = new_words
        written += 1

    OVERRIDES_PATH.write_text(
        json.dumps(existing, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {written} verse overrides to {OVERRIDES_PATH}")


if __name__ == "__main__":
    main()
